### ISSUE TITLE
Remote widgetset-compilation should honour proxy-settings

### ISSUE THREAD

**Issue by vonloxley** [vaadin/framework#10001]
Setting vaadin.widgetset.mode to cdn breaks the compilation if the local system is behind a proxy. Please honour the http.proxyHost and http.proxyPort system-properties if possible.

Please see https://vaadin.com/forum#!/thread/16768029 for a disussion.

**Comment by hesara** [comment]
Remote widgetset compilation uses HTTPS to communicate with the server, so you probably need to set the properties https.proxyHost and https.proxyPort .

**Comment by vonloxley** [comment]
Thanks, but that doesn’t help either. AFAIK resteasy ignores those settings and expects it’s users to figure out how to connect to the internet.
