### ISSUE TITLE
Grid lazy loading: implement keyset pagination in addition to offset pagination

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#10014]
The _seek method_ or _keyset pagination_ is more efficient than offset pagination. See the [We need tool support for keyset pagination](http://use-the-index-luke.com/no-offset) article for lots of details, benchmarks and so on.

Also see the article describing [jOOQ's seek support](https://blog.jooq.org/2013/10/26/faster-sql-paging-with-jooq-using-the-seek-method/).

Since keyset pagination doesn't support jumping to a specific page, I would imagine the scroll bar to work as follows: the first batch is fetched and when the user scrolls to the bottom, another batch is automatically fetched, added at the bottom and the scroll thumb shrinks. This allows continuous scrolling using the mouse wheel or keeping PgDn pressed.

**Comment by pwilkin** [comment]
Vaadin 8 does not have an `SQLContainer` - instead, you are expected to write your own implementation for the `BackEndDataProvider`. This is exactly to avoid problems like this where technically a view-level framework is supposed to tackle backend-level issues. 

In other words - nothing prevents you from writing a `BackEndDataProvider` that implements keyset pagination. It's up to you how you interpret the `offset` and `limit` parameters in the `Query` object.

Also, some databases (such as MSSQL) don't even **support** offset statements - you actually have to implement offsets in MSSQL via keyset, see eg. https://stackoverflow.com/questions/2135418/equivalent-of-limit-and-offset-for-sql-server).

**Comment by TatuLund** [comment]
Closed based on answer provided by @pwilkin Thanks.
