### ISSUE TITLE
Custom DataProvider called from grid with NULL Filter of type Optional

### ISSUE THREAD

**Issue by Flamenco** [vaadin/framework#10012]
The callbacks to _fetch_ and _size_ contain a paramter with filter member type _Optional_ but the value is NULL if the filter is not set.

The means having to NULL check, then check the optional for a possible null value too.

An optional type should never be NULL.

**Comment by tsuoanttila** [comment]
If I understood the issue correctly, you are getting `null` from `query.getFilter()`? 

Quick look at the [related code](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/provider/Query.java#L139) it seems to be returning `Optional.ofNullable(filter)`. If there's a case where you actually get a `null`, I'd like to know so I can fix it ASAP. The intention behind using the `Optional` is to avoid the null check, not add additional ones.

**Comment by Flamenco** [comment]
IIRC if you don't set the filter in the first place, it will be null as a parameter.
