### ISSUE TITLE
Vaadin 8.1.0: Validating outside inline editor fails because values aren't provided

### ISSUE THREAD

**Issue by sebastiansto** [vaadin/framework#10017]
Hi there,

If you try to trigger the data validation outside of the inside editor (for a global validation check), the validation always fails because the values in the custom validator are always null no matter the real value in the field.

Please fix this bug, so that data which is imported into the grid e.g. via file can be validate before committing.

Thank you and best regards,
Sebastian

A sample:
```
ListDataProvider<ObjectNode> dataProvider = retrieveList();

Grid<ObjectNode> grid = new Grid<>(dataProvider);
grid.getEditor().setEnabled(true);
Binder<ObjectNode> binder = grid.getEditor().getBinder();

//
// repeated for all fields
//

String fieldName = "field1";
TextField fieldEdit = new TextField();

Validator<String> validator = new Validator<String>() {
	@Override
	public ValidationResult apply(String value, ValueContext context) {
		return isValidValue(value);
	}
};

Binding<ObjectNode, String> fieldBinding = binder.forField(fieldEdit).withValidator(validator).bind(json -> json.get(fieldName).textValue(), 
		(json, fieldValue) -> json.put(fieldName, fieldValue));

grid.addColumn(json -> json.get(fieldName).textValue()).setCaption(fieldName).setId(fieldName).setEditorBinding(fieldBinding);


//
// Somewhere triggered by a final commit button:
//

if (!grid.getEditor().getBinder().isValid()) {
	grid.setComponentError(new UserError(UIConfiguration.MESSAGE_INPUT_VALIDATION_FAILED));
	return false;
}
```

**Comment by pwilkin** [comment]
Do you mean external validation when the editor is not enabled or external validation when there is a line being edited?

**Comment by sebastiansto** [comment]
I mean when **grid.getEditor().setEnabled(true);** is enabled, but the inline editor is not open (for me it doesn't matter).

Imagine you import multiple rows into the grid via dataProvider from a file dump (I working here with Json objects).
In that case you didn't edit the rows and couldn't check row by row if the data is valid.

If you hit now the commit button, there should be a final check for valid data. But here the values are null, while calling the validators.

**Comment by sebastiansto** [comment]
> If you want to use the Binder's feature of validating items, you can loop over all the elements provided by the underlying DataProvider and manually do grid.getEditor().setBean().

Ah ok, so the the validation isn't meant to use it for the whole grid.
Do you mean then something like this?
```
for (ObjectNode row : rowList) {
	grid.getEditor().getBinder().setBean(row);
	if (!grid.getEditor().getBinder().isValid()) {
		grid.getEditor().getBinder().removeBean();
		grid.setComponentError(new UserError(UIConfiguration.MESSAGE_INPUT_VALIDATION_FAILED));
		return false;
	}
	grid.getEditor().getBinder().removeBean();
}
```

**Comment by pwilkin** [comment]
Yep, something like that should work.

**Comment by sebastiansto** [comment]
Ok, thank you. Then this issue can be closed.
