### ISSUE TITLE
Grid rows blink when applying a filter

### ISSUE THREAD

**Issue by julienpicard** [vaadin/framework#10010]
Hi Vaadin team!

There's a bug we've found with our team.

Vaadin version: 8.1.4

Bug description: 
When you apply a filter to a grid which changes the number of rows displayed by the grid, you can see the rows are blinking. With a more heavy loaded server, you can even see empty rows being drawn into the grid, then the cells content being added.

This behaviour didn't occur with Vaadin V7 grid.

Reproducible example:
You'll find attached to this issue a gif showing the blink effect. Reproduced with the Vaadin Demo.

![grid-blinks](https://user-images.githubusercontent.com/31998640/30498979-c49fd6d4-9a26-11e7-9d9b-3ebf91a6c78b.gif)

**Comment by TatuLund** [comment]
> With a more heavy loaded server, you can even see empty rows being drawn into the grid, then the cells content being added.

This is natural behavior of the Grid lazy loading, i.e. it keeps only visible rows + small buffer in Browser memory. The possible flicker is related to the same thing. Totally flicker free operation would require all the rows to be in Browser memory, and that would be too costly in generic cases.
