### ISSUE TITLE
Images in Grid in Chrome are changing when the rows are selected

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10023]
I'm using the latest version 8.1.4 of Vaadin. The code is simple consists of three columns where one column is an Image component. When that row is selected the Image component changes the image to another row's image for the grid. Eventually after a number of select and unselect (the image also changes on unselect) the image eventually settles on an image.

```
public StreamResource getImageForGrid()
{
	StreamResource streamResource = new StreamResource(
		() -> {
			System.out.print("Line is not output sometimes when rendering grid");
			return new ByteArrayInputStream(getConvertedThumbnailImage());
		}, name + ".jpg");

	streamResource.setCacheTime(0);
	return streamResource;
}

```
For whatever reason the System.out.println line will not be executed in Chrome consistently. In Firefox it's always called when rendering the grid but in Chrome the System.out.println is often not called which results in the above weird error and behavior.

My grid consists of:

`grid.addComponentColumn(gridData -> new Image(gridData.getName(), gridData.getImageForGrid());`

The only reason I'm using Image components is that there is no other way to present server generate thumbnails in a grid other than this way that I can see...

**Comment by FollowSteph** [comment]
I was able to resolve the issue with the following add-on: https://vaadin.com/directory#!addon/grid-renderers-collection-for-vaadin7

**Comment by anasmi** [comment]
Based on your last comment it looks like you have found a way to add the image to the Grid and it works correct currently! :)
We are going through  the process of closing fixed or unverified issues to get more attentions to the ones, which are still outstanding. 
I will close this one, but, please, re-open it, if you disagree with this.

Have a good day! 
Regards,
Anastasia

**Comment by FollowSteph** [comment]
Yes I did but it would be great not to have to rely on an add-on that may or may not disappear at any moment. To me this would still seem like a bug within the Vaadin framework that hasn't been resolved...

**Comment by anasmi** [comment]
Hi,
this add-on will not be removed as it's maintained by Vaadin employees : )
Also, have you tried to use ImareRenderer, which is built-in in the framework?
```
ImageRenderer
Renders the cell as an image. The column type must be a Resource, as described in Images and Other Resources; only ThemeResource and ExternalResource are currently supported for images in Grid.

Column<Person, ThemeResource> imageColumn = grid.addColumn(
    p -> new ThemeResource("img/"+p.getLastname()+".jpg"),
    new ImageRenderer());
```
This is taken directly from documentation: 
[Grid](https://vaadin.com/docs/v8/framework/components/components-grid.html)
