### ISSUE TITLE
Styling InlineDateField specific cells

### ISSUE THREAD

**Issue by TatuLund** [vaadin/framework#10039]
We need to have a sort of StyleProvider or cell specific styles on InlineDateField. The goal for us is to change the style of date cells.

For instance, we want to have the background of 2017/01/01 in red color and the background of 2017/02/08 in green color, or color weekends and workdays differently and highlight local specific holidays.

The features could be somewhat analogous what is provided by this [Tuning DateField add-on:](https://vaadin.com/directory#!addon/tuning-datefield)

**Comment by anasmi** [comment]
Resolved by https://github.com/vaadin/framework/pull/10305
