### ISSUE TITLE
TextField with Input Prompt & Listener buggy in MS Edge

### ISSUE THREAD

**Issue by gbougiakas** [vaadin/framework#10034]
Version 8.1.2

if one has a TextField with an input prompt and a ValueChangeLister / TextChangeListener on the TextField when user clicks in it in Edge then prompt text does not dissapear. Even if user manually deletes the prompt text and types something else the listener never gets triggered.

Works fine in Chrome/Firefox.

**Comment by TatuLund** [comment]
I tried to reproduce this, can be done e.g. with https://demo.vaadin.com/sampler/#ui/data-input/text-input/text-field using Edge, and it works correctly.
