### ISSUE TITLE
Last cell of grid's row drops to the next row (Material Theme)

### ISSUE THREAD

**Issue by mike392** [vaadin/framework#10086]
Can you, please, help me with the following issue?
I have the following code snippet defining the grid:
@bean
@scope("session")
public Grid getGrid() {
Grid grid = new Grid<>();
grid.setSizeFull();
grid.addColumn(DisplayPolygon::getFrequencyBand).setCaption(columnNames[0]);
grid.addColumn(DisplayPolygon::getEirp).setCaption(columnNames[1]);
grid.addColumn(DisplayPolygon::getBandwidth).setCaption(columnNames[3]);
grid.addColumn(DisplayPolygon::getSatelliteName).setCaption(columnNames[2]);
grid.setStyleName(MaterialTheme.TABLE_COMPACT);
return grid;
}
When it's rendered - then you can see that last cell of the second row is pushed to the next row.

When I try to remove the specification of width in the browser - like that:

It moves back to the end.

I've tried plenty of things:

setWidthUndefined(true);
setExpandRatio(1) for all the columns
setMaxWidth for first, last and all columns
tried to set custom StyleGenerator with corresponding setting the "width: auto" to that style
Thank you so much in advance!!!

**Comment by tsuoanttila** [comment]
Hi,

Where is this `MaterialTheme.TABLE_COMPACT` from? It could be that the specific theme is using some style settings that are not taken into account by the escalator when it is counting the size of each row. This will in turn cause the overflow to next row.

**Comment by mike392** [comment]
It's like inherited from Valo in Material theme (I suppose)

**Comment by mike392** [comment]
Actually I found was was the issue:) Can you, please, communicate to someone to make ammendments or consider additional revison of that?

I've just commented out the following in the v-grid.scss file of the Material theme
`  .v-grid-row:not(:first-child) {
    border-top: 1px solid $v-table-border-color;
    //padding-right: 20px;
  }`

And it solved the issue. Seems like this unnecessary padding may provide problems.

**Comment by hesara** [comment]
If the material theme you are using is from the add-on https://vaadin.com/directory/component/material , please create an issue in its issue tracker at https://github.com/appreciated/material/issues and close this issue.

**Comment by mike392** [comment]
Yes - I'm using thу theme from add-on. Thank you!
