### ISSUE TITLE
Add vaadin-maven-plugin to vaadin-bom

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#10103]
Add vaadin-maven-plugin to vaadin-bom

**Comment by hesara** [comment]
What would really be needed would be a pluginManagement section, but unfortunately that would not get used from the BOM as it is used with scope `import` - see e.g. https://stackoverflow.com/questions/32475578/centralizing-plugin-version-in-something-similar-to-a-bom/32475888#32475888 .

On the other hand, adding the plug-in version in dependencyManagement of the BOM would only be of use to plug-in developers extending vaadin-maven-plugin, which I believe to be a very marginal group.

Closing this ticket as something we cannot fix in practice. Consider using a parent project that defines plug-in versions instead.

**Comment by taurus227** [comment]
OK, thank you!
