### ISSUE TITLE
GridLayout with Renderers

### ISSUE THREAD

**Issue by pwilkin** [vaadin/framework#10108]
As of now, `GridLayout` is the only component that you can use to implement data that has a Grid-like rendering, but because of the data variability does not fit into the "every row has the same height" rule that Grid must follow. However, `GridLayout` can only use components, which makes it slow in rendering large amounts of data. Therefore, it should be possible to render cells in a `GridLayout` not only with components, but also with `Renderer`s to make it faster.

Possibly a milestone towards #8711.

**Comment by TatuLund** [comment]
GridLayout is a bad baseline for this kind of purpose, and its architecture is not fit for this requirement.
