### ISSUE TITLE
Several comboboxes do not get cleared at once(Up!)

### ISSUE THREAD

**Issue by mike392** [vaadin/framework#10106]
Can you, please, help me with the following issue.

I have 5 ComboBox objects - 1 along with Lable included in HorizontalLayout, 2 along with Label included in HorizontalLayout, 2 along with Label included in HorizontalLayout,. All of them are the included in a VerticalLayout.

I have a button to clear all the specified values of ComboBox objects. If I select all the values like this:
![image](https://user-images.githubusercontent.com/16647651/30953797-2b4cf90c-a436-11e7-82cb-fbc70f474f59.png)

Then I press CLEAR FILTERS and it goes like this:
![image](https://user-images.githubusercontent.com/16647651/30953848-5570a6de-a436-11e7-94f1-7ac3fb3eb9be.png)

"CLEAR BUTTON" control is powered by the following listener (I even explicitly tried to clear object by object - nothing helps!):
`clearFilterButton.addClickListener((Button.ClickListener) clickEvent -> {          
            bandSelector = mainViewUtils.clearSelector(bandSelector);
            upLinkPolarizationSelector = mainViewUtils.clearSelector(upLinkPolarizationSelector);
            upLinkFrequencySelector = mainViewUtils.clearSelector(upLinkFrequencySelector);
            downLinkPolarizationSelector = mainViewUtils.clearSelector(downLinkPolarizationSelector);
            downLinkFrequencySelector = mainViewUtils.clearSelector(downLinkFrequencySelector);
        });`
The *Selector objects are instantiated via Spring using config like this:
`@Bean
    @Qualifier("bandSelector")
    @Scope("prototype")
    public ComboBox<String> getBandSelector() {
        ComboBox box = new ComboBox();
        box.setItems(filterUpdaterService.getBandSelector());
        box.setTextInputAllowed(false);
        box.setEmptySelectionAllowed(true);
        box.setPopupWidth("13vw");
        return box;
    }` 
You can see that all the code is of standard functionality. I have also mainViewUtils.clearSelector method which is the following:
`public <T> ComboBox<T> clearSelector(ComboBox<T> item) {
        item.clear();
        item.setValue(null);
        return item;
    }`
The strangest thing is - when I try to debug that stuff I see something like this:
![image](https://user-images.githubusercontent.com/16647651/30954279-3d024470-a438-11e7-871f-45af05567333.png)
You see - the ComboBox objects didn't even get processed for clearing - but they are already nulls and I see values on actual controls on UI.
Seems like there are problems with communication of UI and back-end of something.

I have othe examples of ComboBox objects being cleared not simultaneously. Like this, for example
Before click Clear Filters
![image](https://user-images.githubusercontent.com/16647651/30954400-b2d33b28-a438-11e7-9de2-4ad8bb4fabca.png)
After click Clear Filters
![image](https://user-images.githubusercontent.com/16647651/30954429-cb0e35b2-a438-11e7-9e77-2b18e98dc702.png)

Please, help me with that!

**Comment by mike392** [comment]
Please, provide any input for that!

**Comment by TatuLund** [comment]
This should be fixed in Vaadin 8.8+ by https://github.com/vaadin/framework/pull/11412
