### ISSUE TITLE
Add Automatic-Module-Name to the manifest of each module

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#10132]
To help users use Vaadin Framework with Java 9 before we have had the chance to properly modularize everything, we should include a suitable `Automatic-Module-Name` entry in the manifest of each jar file.

**Comment by Legioth** [comment]
I'm starting to consider that there might not be any reason to to this for Framework 8. Adding the module name manifest is mainly a way of making it easier to eventually migrate to Java 9 and JPMS. Doing a proper migration would probably require dropping support for Java 8, which is something that we wouldn't want to do in any 8.x version.

I'm therefore wondering whether we should skip the manifest for Framework and instead only do it for Flow (https://github.com/vaadin/flow/issues/2580)?

**Comment by jreznot** [comment]
We would prefer that Vaadin 8.x will not be modularized since it requires explicit exports and building for Java 9.

**Comment by mathisdt** [comment]
I might be mistaken, but I think adding `Automatic-Module-Name` entries into the manifest files would only make it easier to migrate to a future modularized Vaadin version. It would in no way force modularization of any application using Vaadin 8, and nobody would have to drop the support of Java 8 - it would only ensure that the automatic module names (if an application already uses Vaadin 8 with Java 9) will match the future Vaadin module names (after migrating to said future modularized Vaadin version).

**Comment by jreznot** [comment]
Actually not, because you have to compile module-info.java into module-info.class. It cannot be done using Java 8.

**Comment by Legioth** [comment]
Some additional things to consider: http://blog.joda.org/2018/03/jpms-negative-benefits.html

**Comment by TatuLund** [comment]
This can't be implemented in Vaadin 8 due Java 8 compatibility

**Comment by Legioth** [comment]
Adding a `Automatic-Module-Name` manifest entry has nothing to do with Java 8 compatibility. It's even possible to include `module-info` classes while still also supporting Java 8.

Another question is whether it's worth the effort to do so for Vaadin 8 since new development is mostly focused on Vaadin 14.x.
