### ISSUE TITLE
Grid ColumnResizeListener - old column width reported to server

### ISSUE THREAD

**Issue by FlorianFratte** [vaadin/framework#10139]
Hi,

I'm using Vaadin Version 8.1.5 and stumbled upon a quite strange behaviour:

I have a grid and added a `ColumnResizeListener`. Within the listener on `columnResize` I need to get the new size of the column.
The problem now is, that according to the client side logs, the OLD width is reported to the server so when I call `getWidth` on the affected column I always get the previous width 

> INFO: Sending push (websocket) message to server: {"csrfToken":"...","rpc":[["476","com.vaadin.shared.ui.grid.GridServerRpc","columnResized",["0",**48**]]],"syncId":18,"clientId":18}

In this case **48** is the initial size (before the resize)

I also checked the docs for `GridServerRpc.columnResized` and it says

>    @param pixels
>                the new width of the column in pixels

 I tried with Chrome and Firefox and the results are the same

Any ideas what may cause this issue? (and how to make it work as it should)

Thanks a lot
Kind Regards
Florian

**Comment by FlorianFratte** [comment]
Hi again,

I found out that the issue only shows up when the `ColumnResizeMode` is `SIMPLE`
If the `ColumnResizeMode` is `ANIMATED`, the column widths are reported as expected - however events are send all the way while dragging

In my oppinion also in SIMPLE mode the size should get reported back correctly after the column has been resized


Kind Regards
Florian

**Comment by OlliTietavainenVaadin** [comment]
Still needs to be fixed for 8

**Comment by tsuoanttila** [comment]
Picked for 8.3.1
