### ISSUE TITLE
VaadinIcons icons swapped

### ISSUE THREAD

**Issue by fante76** [vaadin/framework#10140]
Vaadin version : 8.1.5

Codes for SEARCH_PLUS and SEARCH_MINUS icons in VaadinIcons class are swapped: using SEARCH_PLUS will display e minus.

**Comment by acsadam0404** [comment]
This is in the wrong repo. Duplicates https://github.com/vaadin/vaadin-icons/issues/37

**Comment by anasmi** [comment]
Hi,

the issue was finally fixed and merged into master branch today! Thank you for bug report and help in improving framework : ) 
Pr: https://github.com/vaadin/framework/pull/11281
