### ISSUE TITLE
Grid refresh broken

### ISSUE THREAD

**Issue by rappenze** [vaadin/framework#10152]
Vaadin Version 8.1.4

Grid refresh does not work since [commit](https://github.com/vaadin/framework/commit/7b506a70c89c83451b113a7549b6fbe2268b5b26#diff-346b6fedd0c2add2cd7f351aa3ae0bbb) because the ActiveDataHandler does not contain the current object as mentioned in the code comment.

Here the relevant part of the commit which introduced the bug:
![datacommunicator](https://user-images.githubusercontent.com/29733488/31328605-55cd8fb8-acd6-11e7-8d1b-5eeae2d9b104.png)

To fix either the shown code should be reverted or in my opinion much better the refreshData() method in ActiveDataHandler class should be implemented properly. There is just an empty default method in the implemented DataGenerator interface.

Be aware that this problem only occurs if refreshItem() is called with a completely new object with same id. It does work if just some data within the object is changed.

**Comment by tsuoanttila** [comment]
There's test to this exact functionality in the Framework in `com.vaadin.tests.data.DataProviderRefresh`. If you're still facing this issue, can you provide a simple UI that reproduces the issue? That would speed up the debugging and fixing any possible leftover issues with the lazy data communication when refreshing items.

**Comment by rappenze** [comment]
Thanks for the feedback. You're right, my analysis was not completely correct.

What my UI does is that it selects the row and refreshes it in same call. So the refresh method shown in screenshot is called twice, first with old data (when calling select) and second with refreshed data (when explicitly refreshing the data through data provider). The cause of the issue is that the add method in the used HashSet for the field updatedData (see as well in the screenshot) just adds the element if it is not already in the list. What I would expect is that always the last call to refresh wins so you should always replace the object in the HashSet updatedData instead of just adding the first time.

Also there is second problem that the refresh() method is sometimes selected synchronously (e.g. in select row method) and sometimes is called at the end of the request with UI.access() as done with DataRefreshEvent. So anyway it is then unclear which call wins if we have multiple calls to request a row refresh().

I see that there are no simple solution to decide which is the correct object at the end, but at least it would be great if you find a solution where it is possible to refresh the data of a row and select the row in same call.

So if you add to your test a new button with combination of select and data refresh, you should see the problem:
```java
    addComponent(new Button("Select and replace together", e -> {
      grid.select(foo);
      dataProvider.refreshItem(new Bean("Bar", 10));
    }));
```
and
```java
    @Test
    public void select_and_replace_together() {
        openTestURL();
        GridElement grid = $(GridElement.class).first();
        assertFalse("Row should not be initially selected",
                grid.getRow(0).isSelected());

        // Replace item and select it
        $(ButtonElement.class).caption("Select and replace together").first().click();
        assertTrue("Row should be selected after item replace",
                grid.getRow(0).isSelected());
        assertEquals("Grid content was not updated.", "{ Bar, 10 }",
                grid.getCell(0, 0).getText());
    }
```

**Comment by TatuLund** [comment]
> dataProvider.refreshItem(new Bean("Bar", 10));

This is not the correct usage of refreshItem(..). The method does not add the item to data provider. Attempt of trying to refresh item that is not in the data provider leads to nothing.
