### ISSUE TITLE
adding a nested property to a grid lead to unsuitable id

### ISSUE THREAD

**Issue by OSchwark** [vaadin/framework#10159]
Hello together,
when I have a class
`public class Company{
    private String name;
}`
and a class
`public class Customer{
    private String name;
}`

and I add them to a bean class e.g.
```java
public class Bean{
    private Company company;
    private Customer customer;
}
``` 

And I add the bean to a grid and add the names of both objects as column via nested properties:
```javaGrid<Bean> grid = new Grid<>(Bean.class);
grid.addColumn("company.name");
grid.addColumn("customer.name");
```

I got an exception because both columns get `name` as id.
It is even not possible to overwrite the ids.

I am forced to use nested properties as we are using SOAP webservices and autogenerate the classes. Our SAP SOAP webservice has several properties that are simply named "value".

I assume this is a bug. 
Regards
Oliver

**Comment by hesara** [comment]
While perhaps not directly resolving this, I believe #9925 adds some of the basic mechanisms needed to support this (differentiating between nested IDs with the full path vs. just the last part).
