### ISSUE TITLE
Several comboboxes do not get cleared at once(Up!!!)

### ISSUE THREAD

**Issue by mike392** [vaadin/framework#10165]
Can you, please, help me with the following issue.

I have 5 ComboBox objects - 1 along with Lable included in HorizontalLayout, 2 along with Label included in HorizontalLayout, 2 along with Label included in HorizontalLayout,. All of them are the included in a VerticalLayout.

I have a button to clear all the specified values of ComboBox objects. If I select all the values like this:

Then I press CLEAR FILTERS and it goes like this:

"CLEAR BUTTON" control is powered by the following listener (I even explicitly tried to clear object by object - nothing helps!):
clearFilterButton.addClickListener((Button.ClickListener) clickEvent -> { bandSelector = mainViewUtils.clearSelector(bandSelector); upLinkPolarizationSelector = mainViewUtils.clearSelector(upLinkPolarizationSelector); upLinkFrequencySelector = mainViewUtils.clearSelector(upLinkFrequencySelector); downLinkPolarizationSelector = mainViewUtils.clearSelector(downLinkPolarizationSelector); downLinkFrequencySelector = mainViewUtils.clearSelector(downLinkFrequencySelector); });
The *Selector objects are instantiated via Spring using config like this:
@Bean @Qualifier("bandSelector") @Scope("prototype") public ComboBox<String> getBandSelector() { ComboBox box = new ComboBox(); box.setItems(filterUpdaterService.getBandSelector()); box.setTextInputAllowed(false); box.setEmptySelectionAllowed(true); box.setPopupWidth("13vw"); return box; }
You can see that all the code is of standard functionality. I have also mainViewUtils.clearSelector method which is the following:
public <T> ComboBox<T> clearSelector(ComboBox<T> item) { item.clear(); item.setValue(null); return item; }
The strangest thing is - when I try to debug that stuff I see something like this:

You see - the ComboBox objects didn't even get processed for clearing - but they are already nulls and I see values on actual controls on UI.
Seems like there are problems with communication of UI and back-end of something.

I have othe examples of ComboBox objects being cleared not simultaneously. Like this, for example
Before click Clear Filters

After click Clear Filters

Please, help me with that!
(link to original issue - https://github.com/vaadin/framework/issues/10106)

**Comment by pwilkin** [comment]
If you could provide a minimal reproducible code sample for the problem, there's a bigger chance that someone would be able to help.

**Comment by pwilkin** [comment]
Also, some information about the version of Vaadin that you're using would be nice.

**Comment by mike392** [comment]
I'll try to make a github so that you can check this out. Will it be okay?
Thanks in advance!

**Comment by mike392** [comment]
Sorry, everything is fine! I've found out the reason for this - I tried to call setItems after clearing the checkbox.
