### ISSUE TITLE
NativeSelect double tabindex

### ISSUE THREAD

**Issue by jringbox** [vaadin/framework#10163]
So, the issue I'm having is tab navigation with NativeSelect.  The generated code is shown below.

```
<div tabindex="0" class="v-select v-widget nativeselect v-select-nativeselect" style="outline-style: none;" id="thing">
<select class="v-select-select" size="1" tabindex="0">
<option value="1">Thing 1</option>
<option value="2">Thing 2</option>
</select>
</div>
```

Evidently, I have to double tab to navigate to the select element.

Why does the div have a tabindex and the select have a tabindex?

The only part of the generated HTML code that should have a tabindex is the select element.  Am I missing something?  Is there a way to remove the tabindex on the div but keep it on the select element or is there a way to create the NativeSelect without having it wrap a div around the select?

Is this a bug?

Vaadin Version: 8.1.2
Last working: 7.7.9 (that I used)

**Comment by tsuoanttila** [comment]
Looks like a bug indeed. The Vaadin 8 implementation of NativeSelect uses GWT Listbox and a `FocusableFlowPanelComposite` that is meant to take care of focus event from child widgets to make it easier to implement the focus handling on the client-side. However it seems that at least in this case (might be more components using the same `Composite`) the wrapping `div` gets an extra `tabindex`.

As a first fix `VNativeSelect` constructor could call `getElement().removeAttribute("tabindex")`.
