### ISSUE TITLE
java.io.NotSerializableException: java.time.format.DateTimeFormatter in LocalDateRenderer

### ISSUE THREAD

**Issue by ossd** [vaadin/framework#10175]
When using a LocalDateRenderer in Grid column:

`grid.addColumn(MyDocument::getDate).setCaption("Datum").setRenderer(new LocalDateRenderer(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM).withLocale(Locale.GERMANY)));`

I'll get a:

`java.io.NotSerializableException: java.time.format.DateTimeFormatter`

on redeploy. This is because java.time.format.DateTimeFormatter is not Serializable and is a member variable from LocalDateRenderer.

Vaadin 8.1.5

import com.vaadin.ui.Grid;
import com.vaadin.ui.renderers.LocalDateRenderer;
import java.time.format.DateTimeFormatter;

**Comment by ossd** [comment]
A PresentationValueProvider solves the problem for me. But the LocalDateRender still has broken serialization.

`grid.addColumn(MyDocument::getDate, date -> date == null ? null : date.format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM).withLocale(Locale.GERMANY)));
`

**Comment by knoobie** [comment]
Push! 

This was also mentioned in the Vaadin Dev Day in Hamburg (Germany) as well.

**Comment by knoobie** [comment]
Still an issue
