### ISSUE TITLE
InlineDateField does not select dates between October 16 and 31 - Problem on Brazil 

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/framework#10189]
- Vaadin Framework version (7.7.9)
Days between October 16 and 31 are not being selected.
-Steps to reproduce:
1. Make a project in vaadin 7.7.9 or go to https://demo.vaadin.com/sampler/#ui/data-input/dates/date-picker
2. Click in October 16,17,18, 19...

**Comment by acsadam0404** [comment]
Couldn't reproduce on the sampler:

![image](https://user-images.githubusercontent.com/5070542/31851575-e2087bb4-b668-11e7-9cc5-fd78ee56a1eb.png)

The sampler is using a 8.x version I beleive.

**Comment by Ramonrune** [comment]
When I click between this dates automatically the focus of the blue cell disappears, but the problem persists on sampler.  I'm using Google chrome 62.0.3202.62 64 bits.

![22222](https://user-images.githubusercontent.com/16857245/31851710-025de38c-b64a-11e7-9428-ce5e092cefec.png)

Any idea what it could be?

Thanks

**Comment by Ramonrune** [comment]
Anyone ?

**Comment by Ramonrune** [comment]
After some tests, this is the problem:

On October 16 Brazil entered daylight saving time.
To reproduce exactly this problem go to "Date and time" in operating system and "Change date and time", put timezone to (UTC-03:00) Brasilia and mark "Automatically adjust clock for DayLight Saving Time".

Now try to reproduce this problem:
1. Go to https://demo.vaadin.com/sampler/#ui/data-input/dates/date-picker
2. Click in October 16,17,18, 19...

This is probably causing problems in Brazil.




![1](https://user-images.githubusercontent.com/16857245/31996939-0256cbb6-b969-11e7-8536-7fd7aa54e094.PNG)

**Comment by Ramonrune** [comment]
Anyone please?

**Comment by Ramonrune** [comment]
Anyone please ? Some peoples in Brazil are encountering the same problem.

**Comment by Ramonrune** [comment]
Someone please ?

**Comment by Ramonrune** [comment]
Someone ?

**Comment by elmot** [comment]
Might be related to #9765

**Comment by elmot** [comment]
This might be fixed already. Please reevaluate the issue against new Vaadin 8 version.

**Comment by Ramonrune** [comment]
Problem fixed in Vaadin 8 version, thanks
