### ISSUE TITLE
Scrollbar of "long" tree jumps when node is selected and tree is wrapped by a panel (Vaadin 8.1.5, IE 11)

### ISSUE THREAD

**Issue by Petikoch** [vaadin/framework#10196]
In the following example...

```
package example;

import com.vaadin.annotations.PreserveOnRefresh;
import com.vaadin.annotations.Theme;
import com.vaadin.data.TreeData;
import com.vaadin.data.provider.TreeDataProvider;
import com.vaadin.server.VaadinRequest;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import java.util.stream.IntStream;

@SpringUI
@PreserveOnRefresh
@Theme("valo")
public class TreeInPanelJumpingScrollbarUI extends UI {

	@Override
	protected void init(VaadinRequest request) {
		TreeData<String> treeData = new TreeData<>();
		treeData.addItem(null, "Mercury");
		treeData.addItem(null, "Venus");
		treeData.addItem(null, "Earth");
		treeData.addItem(null, "MorePlanets");
		IntStream.rangeClosed(1, 100).forEach(value -> treeData.addItem("MorePlanets", "Planet" + value));
		treeData.addItem(null, "EvenMorePlanets");
		IntStream.rangeClosed(1, 100).forEach(value -> treeData.addItem("EvenMorePlanets", "AnotherPlanet" + value));

		TreeDataProvider<String> inMemoryDataProvider = new TreeDataProvider<>(treeData);
		Tree<String> tree = new Tree<>(inMemoryDataProvider);

		Panel panel = new Panel(tree);
		panel.setHeight("50%");
		panel.setWidth("50%");

		VerticalLayout verticalLayout = new VerticalLayout(panel);

		verticalLayout.setWidth("100%");
		verticalLayout.setHeight("100%");

		setContent(verticalLayout);
	}
}
```

... when 

- I run it 
- expand node "EventMorePlanets"
- select node "AnotherPlanet50"

then the scollbar jumps first up and then down 

Expected: 
There is absolutely no need to scoll up and down on selection by user-clicks in the GUI, imho.

This is a similar issue like https://github.com/vaadin/framework/issues/7342 but in Vaadin 8 instead of 7

**Comment by Petikoch** [comment]
Workaround:

Remove the panel and put the tree directly into the verticallayout:

```
                        TreeDataProvider<String> inMemoryDataProvider = new TreeDataProvider<>(treeData);
                        Tree<String> tree = new Tree<>(inMemoryDataProvider);

                        tree.setHeight("50%");
                        tree.setWidth("50%");

                        VerticalLayout verticalLayout = new VerticalLayout(tree);
```

--> No jumping scrollbar

**Comment by Petikoch** [comment]
I just checked if it is still an issue also in latest - 8.3.2 - vaadin (IE 11): *Yes, it is.*

Why is it important to fix? It's an annoying bug.

**Comment by Petikoch** [comment]
I just checked if it is still an issue also in latest - 8.5.1 - vaadin (IE 11): *Yes, it is.*

Why is it important to fix? It's an annoying bug.

**Comment by Petikoch** [comment]
The issue is still there with the latest vaadin Framework 8 release

**Comment by Petikoch** [comment]
The issue is still there with the latest vaadin Framework 8 release

**Comment by TatuLund** [comment]
There is nothing in Vaadin that makes this behavior, unfortunatelly it is purely due IE11 internal logic and we cannot do much about it. Actually there is further issue. For example if you select another item after "AnotherPlanet50", say e.g. "AnotherPlanet46" it jumps to top and stays there, which makes me think it is the same IE11 bug that causes this problem: https://github.com/vaadin/framework/issues/7874
