### ISSUE TITLE
V8 suggestion: allow null as argument to ValidationResult.error or make SimpleValidationResult constructor public

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#10204]
Small improvement would be to allow null as argument to `ValidationResult.error` [here](https://github.com/vaadin/framework/blob/d0b5741b81d214491c93d4d042c79e10bb4f192e/server/src/main/java/com/vaadin/data/ValidationResult.java#L131) or make `SimpleValidationResult` constructor public.

It is common to have methods that validate stuff and return either error message or null - validation package has no idea that vaadin exists nor should it. Right now I have to do either of these:
````java
public ValidationResult apply(String value, ValueContext context) {
	String error = actualValidation(value);
	return new CopyPaste_Of_SimpleValidationResult(error);
}

// Whole SimpleValidationResult is copy pasted somewhere here

public ValidationResult apply(String value, ValueContext context) {
	String error = actualValidation(value);
	if (error == null) {
		return ValidationResult.ok();
	} else {
		return ValidationResult.error(error);
	}
}
````

Following would be more elegant:
````java
public ValidationResult apply(String value, ValueContext context) {
	String error = actualValidation(value);
	return new ValidationResult.SimpleValidationResult(error);
}

//or
public ValidationResult apply(String value, ValueContext context) {
	String error = actualValidation(value);
	return ValidationResult.error(error);
}
````

That check can not prevent a bug nor anything like that, it just forces user to write a bit more boilerplate.

**Comment by pwilkin** [comment]
The latter is terrible - you use a factory method that is supposed to create an error result, but make it actually return an OK result. 

If a factory method is supposed to behave that way, it should be something different, like for example `ValidationResult.fromErrorMessage(String message)`

**Comment by tsuoanttila** [comment]
The recommended way to use `Validators` is to use the factory methods provided by us to remove all the boilerplate. Currently the most flexible way is to provide a `Predicate<VALUE>` that contains the code that checks if the validation is ok or not and an `ErrorMessageProvider` that takes a `ValueContext` and returns the error message as a `String`. 

Is some information missing from the `ValueContext` that you'd need to create the error message in this case? Is there something else you can't achieve with these? 

We can extend the `ValueContext` to provide more information and add an option to use a `BiPredicate` to pass in the value and the context for the validation if needed.

**Comment by SomMeri** [comment]
@tsuoanttila Thank you for hints and answer. 

Validation I have to do is pretty complex, the value is expression in different programming language I have to parse, validate against some additional rules etc etc etc. It can result in many different errors.  Unless guard and errorMessageProvider communicate, I would have to run validation twice (once to see whether guard has to return true or false) and once to return error message. Alternatively I would have to run guard, store the error message somewhere and return it in provider. A single if-null is simpler.

@pwilkin Yeah, there is something on call name being misleading in such case.
