### ISSUE TITLE
Deprecate the constructor methods of `LocalDateRenderer` and `LocalDateTimeRenderer` taking a String formatting pattern

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/framework#10207]
# Column-renderer for java.time types

The [`LocalDateRenderer`](https://vaadin.com/download/release/8.1/8.1.5/docs/api/com/vaadin/ui/renderers/LocalDateRenderer.html) and [`LocalDateTimeRenderer`](https://vaadin.com/download/release/8.1/8.1.5/docs/api/com/vaadin/ui/renderers/LocalDateTimeRenderer.html) classes enable flexible formatting of `java.time.LocalDate` and `java.time.LocalDateTime` objects for display in a Vaadin Grid. 

Both classes offer constructor methods taking a String argument intended to be the formatting pattern to be specified in a `java.time.DateTimeFormatter` object. Though well-intentioned, this  was a poor design choice. 

This design is making the Vaadin Grid column-renderer classes responsible for feeding that pattern into the instantiation of a `DateTimeFormatter` object. Assigning that responsibility is a violation of the [Separation of Concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) design principle. The Vaadin Grid column renderers’ job is to *use* a `DateTimeFormatter` in presenting the date-time object on-screen. The column-renderers should not be responsible for *instantiating* the `DateTimeFormatter`. 

For one thing, instantiating the `DateTimeFormatter` is a complicated matter, involving the complicated rules of formatting pattern code characters, [`Locale`](https://docs.oracle.com/javase/9/docs/api/java/util/Locale.html), [`FormatStyle`](https://docs.oracle.com/javase/9/docs/api/java/time/format/FormatStyle.html), and localization. Another complication: there have been some minor bugs in parsing formatting strings in Java 8, now fixed in Java 9. The column-renderer classes should not be getting in the middle of that. 

Another smaller concern is performance, as the current implementation of those classes stores the pattern String rather than caching a `DateTimeFormatter`, and then instantiates a fresh `DateTimeFormatter` over and over for display of each cell in the grid. So, countless instances created and garbage-collected needlessly rather than one. 

# Solution

The column renderers also offer constructors that take as an argument an already-instantiated `DateTimeFormatter`. That is wise, and these constructors should remain while deprecating the constructors that take a String for a formatting pattern.  This solution solves all the above-listed concerns ( separation-of-concerns & performance). 

For example, keep this:

    public LocalDateTimeRenderer(DateTimeFormatter formatter) { … }  // 👍

…and keep this:

    public LocalDateTimeRenderer(DateTimeFormatter formatter, String nullRepresentation) { … }  // 👍

…but deprecate for removal this:

    public LocalDateTimeRenderer(String formatPattern) { … }  // 👎

… and this:

    public LocalDateTimeRenderer(String formatPattern, Locale locale) { … }  // 👎

… and this:

    public LocalDateTimeRenderer(String formatPattern, Locale locale, String nullRepresentation) { … }  // 👎

« fin »

**Comment by ossd** [comment]
It's not a good idea to save a reference of DateTimeFormatter in the renderer. DateTimeFormatter is not serialisable and the renderer as part of the grid prevent the view from serialisation.
#10175

**Comment by elmot** [comment]
Thanks for your ideas, but there is a bunch of concerns.
As @ossd already mentioned, there are troubles with the serialization of `LocalDateFormatter` and `LocalDateTimeFormatter`
Also the framework usually provides a set of low-level functions with maximum flexibility, and a set shortcut functions for simplicity. Those constructors are of the second type, and I am sure someone uses that. As a conclusion, we are not going to deprecate those constructors.

Related to #10175
