### ISSUE TITLE
Uncaught client side exception when rendering trying to render invisible component in ComponentColumn

### ISSUE THREAD

**Issue by schaerl** [vaadin/framework#10201]
Hi,

I found this issue using Vaadin 8.1.5. I'm trying to create a grid that only shows some components in the row when a certain flag is set. By default, this flag is set to false. When the grid is rendered for the first time with an invisible component, "Uncaught client side exception" errors appear in debug mode (see attached screenshot). It does not appear break anything, but I'm not sure what's going on behind the scenes. It is, however, highly annoying when debugging the app,

This only happens if the grid is rendered with an invisible component, rendering the visible component and setting it invisible works as expected.

If you refresh the grid data provider with an invisible component, a single error appears.

Reproduction:
1. Start a Vaadin app with the code below.
2. Open the browser on [http://localhost:8080/?debug](url) -> error
3. Toggle the CheckBox on and off -> no more errors

If you set INIT to "true", no error will appear. 
If you uncomment the refresh in the ValueChangeListener, you will get an error when toggling the box off, no matter the value of INIT.

```
public class MyUI extends UI {

    private static final boolean INIT = false;
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        Grid<Object> grid = new Grid<>();
        ComboBox<String> cb = new ComboBox<>();
        cb.setVisible(INIT);
        CheckBox check = new CheckBox();
        check.setValue(INIT);
        check.addValueChangeListener(event -> {
            cb.setVisible(event.getValue());
            // If this is not commented out, another error appears
            // grid.getDataProvider().refreshAll(); 
        });
        
        grid.setItems("Item");
        grid.addComponentColumn(item -> {
            return cb;
        }).setCaption("comboBox");
        
        layout.addComponents(check, grid);
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```
![image](https://user-images.githubusercontent.com/12117159/31713562-ed2a7c7a-b3fe-11e7-90e8-5909458e2001.png)

**Comment by tsuoanttila** [comment]
There is most likely a missing `null` check in the `Renderer` implementation inside of `ComponentRendererConnector`. Components that are not visible most likely have `connectorId` but some part of the client-side is likely not initialised for for invisible components.
