### ISSUE TITLE
Grid Multiselect Checkbox won't trigger with key 'space'

### ISSUE THREAD

**Issue by knoobie** [vaadin/framework#10221]
Currently it's not possible to select a row in a grid with the keyboard while focusing the checkbox that should trigger the select. 

Workflow: 

- Create a simple Grid and enable MULTISELECT
- Open Grid UI
- Tab til you reach a checkbox to select a row (select all checkbox works with space!)
- Press 'space'

Expected behaviour:  checkbox is checked / row selected
Current behaviour:  checkbox won't be checked / row not selected

**Comment by tsuoanttila** [comment]
`CheckBox` widgets created in `MultiSelectionRenderer` are not handling the events as expected.
