### ISSUE TITLE
Widget set cloud compilation 'fetch' fails

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#10233]
Tried to use [Widget set cloud compilation](https://vaadin.com/blog/demystifying-widget-set-cloud-compilation#comments) in Vaadin 8.1.5 with `<widgetsetMode>fetch</widgetsetMode>`. When I try to deploy my application, I get an error saying:
```Failed to load the widgetset: ./VAADIN/widgetsets/com.host.project.MyWidgetSet/com.host.project.MyWidgetSet.nocache.js?1508684041912```
and in the server logs:
```INFO:  Requested resource [/VAADIN/widgetsets/com.host.project.MyWidgetSet/com.host.project.MyWidgetSet.nocache.js] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.```
And sure enough, the file has a different name:
```
$ find . -name '*.nocache.js'
./widgetset/target/classes/VAADIN/widgetsets/ws200d64e83ef46da4175a3927cb709c9d/ws200d64e83ef46da4175a3927cb709c9d.nocache.js
```
If I use `<widgetsetMode>local</widgetsetMode>` everything works and the file name is correct:
```
$ find . -name '*.nocache.js'
./target/classes/VAADIN/widgetsets/com.host.project.MyWidgetSet/com.host.project.MyWidgetSet.nocache.js

```
The widget set name is specified in the `@Widgetset("com.host.project.MyWidgetSet")` annotation of the UI class and in the configuration of the maven-jar-plugin in the widgetset module:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Vaadin-Package-Version>1</Vaadin-Package-Version>
                            <Vaadin-Widgetsets>com.host.project.MyWidgetSet</Vaadin-Widgetsets>
                        </manifestEntries>
                    </archive>
                    <!-- Exclude some unnecessary files generated by the 
                        GWT compiler. -->
                    <excludes>
                        <exclude>VAADIN/gwt-unitCache/**</exclude>
                        <exclude>VAADIN/widgetsets/WEB-INF/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
```

**Comment by Artur-** [comment]
Try removing the `@Widgetset` annotation. This will allow the framework to determine the name of the widget set based on the fetched file.
