### ISSUE TITLE
Really minor issue with VaadinIcons.Search"Minus" and "Plus

### ISSUE THREAD

**Issue by agusalex** [vaadin/framework#10231]
On vaadin version 8.1.5 the Minus and Plus icons are swapped so I had to pick Minus to display a Plus sign

``
VaadinIcons.SEARCH_MINUS; // displays a plus sign.
 VaadinIcons.SEARCH_PLUS; // displays a minus sign.
``

**Comment by acsadam0404** [comment]
Duplicates https://github.com/vaadin/framework/issues/10140
