### ISSUE TITLE
Adding a column with a nested property to a grid will cause an IllegalArgumentException if the page is reloaded.

### ISSUE THREAD

**Issue by schaerl** [vaadin/framework#10243]
https://github.com/vaadin/framework/pull/8916 allows the usage of nested properties in grids, however it breaks when you add a nested property column and then refresh the page. Here is a short example:

```
public class MyUI extends UI {
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        Grid<Person> grid = new Grid(Person.class);
        grid.addColumn("address.street");
        setContent(grid);
    }

    private class Person {
        private String name;
        private Address address;

        public Person(String name, Address adr) {
            this.name = name;
            this.address = adr;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Address getAddress() {
            return address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }

    }

    private class Address {
        private String street;

        public Address(String str) {
            this.street = str;
        }

        public String getStreet() {
            return street;
        }

        public void setStreet(String street) {
            this.street = street;
        }

    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

}
```

Running this code and opening the page will show a grid with the columns Address, Name and Street. When reloading(F5) the page, an IllegalArgumentException will be thrown. 

When reloading the page, the grid is constructed a second time, but since the propertySet is already present, it will be reused (c.f. `public static <T> PropertySet<T> get(Class<? extends T> beanType)` in BeanPropertySet).
Since the constructor creates columns for each property definition (using its `getName()` function as input to `addColumn()`), it will try to create one for the street property as well. But `getName()`for this property will return `street` which will not be found in the Person bean and therefore the exception is thrown

**Comment by schaerl** [comment]
I realized that this seems to be a duplicate of https://github.com/vaadin/framework/issues/9960 and it also seems related to https://github.com/vaadin/framework/issues/10159 and https://github.com/vaadin/framework/issues/9609

**Comment by TatuLund** [comment]
There is comment in https://github.com/vaadin/framework/issues/9960 claiming this is fixed in 8.3.0

**Comment by TatuLund** [comment]
Yes, this fixed by https://github.com/vaadin/framework/pull/9925

**Comment by schaerl** [comment]
The issue is now changed. Now the exception thrown is "java.lang.IllegalStateException: There is already a column for address.street"

The following test shows this:
```
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import com.vaadin.ui.Grid;

public class VaadinIssue10243AddNestedColumnTwiceBreaks {

   /**
    * This shows that Issue 10243 is still broken.
    * See:https://github.com/vaadin/framework/issues/10243
    */
   @Test
   public void testIssue10243() {
       Grid<Person> grid1 = new Grid(Person.class);
       grid1.addColumn("address.street");
       Grid<Person> grid2 = new Grid(Person.class);
       Assertions.assertThrows(IllegalStateException.class, () -> grid2.addColumn("address.street"));

   }

   class Person {
       public Address address;

       public Address getAddress() {
           return address;
       }
   }

   class Address {
       public String street;

       public String getStreet() {
           return street;
       }
   }
}
```

**Comment by tsuoanttila** [comment]
Can you please open a new ticket for this issue.
