### ISSUE TITLE
CheckBoxGroup: cannot deselect item

### ISSUE THREAD

**Issue by tistvan** [vaadin/framework#10245]
Vaadin Framework version: 8.1.5

Description of the bug:
When I use CheckBoxGroup with a DataProvider which has a custom getId() mechanism, the user cannot remove the selection from the initially selected items. The bug is only reproducible when the DataProvider contains different instances than the CheckBoxGroup's value.

If possible, minimal reproducible example:

```java

public static class TestItem2 {
    private Long id;
    private String name;

    public TestItem2(Long id, String name) {
        this.id = id;
        this.name = name;
    }
    //getters, setters
}

CheckBoxGroup<TestItem2> checkBoxGroup = new CheckBoxGroup<>();
List<TestItem2> data = Arrays.asList(new TestItem2(1L, "first"), new TestItem2(2L, "second"), new TestItem2(3L, "third"));
DataProvider<TestItem2, ?> dataProvider = new ListDataProvider<TestItem2>(data) {
    @Override
    public Object getId(TestItem2 item) {
        return item.getId();
    }
};
checkBoxGroup.setDataProvider(dataProvider);

Set<TestItem2> selection = Sets.newHashSet(new TestItem2(2L, "second"));
checkBoxGroup.setValue(selection);
checkBoxGroup.setItemCaptionGenerator(TestItem2::getName);

```
In the example above the selection cannot be removed from the "second" item.

Thanks,
István

**Comment by tistvan** [comment]
I reproduced the bug in VaadinFiddle: https://vaadinfiddle.com/editor/preview/6e2e88d73b0695f6f3895cdc9763ce32e8a7350f8939a120054a82bfccc4138f/src/main/java/org/vaadin/vaadinfiddle/MyUI.java
In this example you can't deselect the second checkbox.

**Comment by tlvlp** [comment]
I'm facing the same problem and [also found a similar one from 7 years ago](https://vaadin.com/forum/-/message_boards/view_message/226388)

After some prodding, it seems that there is no event fired at all when an item is deselected from an AbstractMultiSelect component so the old values will be added back when a new event is fired by selecting something. 
This way the items can never be removed, only added to the list.

**Comment by tistvan** [comment]
Works with Vaadin 8.3.3

**Comment by tlvlp** [comment]
Awesome, thanks! Back then I ended up writing a custom checkboxgroup with a very minimalist implementation
