### ISSUE TITLE
Hiding v-loading-indicator causes huge delay in rendering

### ISSUE THREAD

**Issue by musikpirat** [vaadin/framework#10250]
When a custom theme sets the height of .v-loading-indicator to 0px, rendering of the UI is delayed for at least five seconds. The vaadin debug console says "Assuming CSS loading is not complete, postponing render phase. (.v-loading-indicator height == 0)"

Hiding the loading indicator with display:none works fine.

**Comment by Legioth** [comment]
The framework uses the the height of the loading indicator to detect whether a theme is loaded. It's therefore recommended that a theme uses some other mechanism instead of `height: 0` if it's desired to completely hide the loading indicator.

**Comment by musikpirat** [comment]
I understand the motivation behind that mechanism, but it is very unintuitive. At least the error message should drop a hint what might be the cause. The css has been loaded and was working exactly as expected. So I would prefere a message that is visible even outside of the debug console.
