### ISSUE TITLE
Calling Grid.setItems(...) more than once should reuse existing ListDataProvider

### ISSUE THREAD

**Issue by Flamenco** [vaadin/framework#10266]
Vaadin Framework version 8.1.6

Calling setItems(...) on a Grid will create a default ListDataProvider.  Calling setItems(...) again will create a new ListDataProvider.  This, at the very least, wipes out all filters and existing references to the original dataProvider.

**Comment by Flamenco** [comment]
Solution Ideas:

From HasDataProvider
Since this is an interface, it can't _cache_ the state, so the Grid itself would need to override this and own the ListDataProvider instance.
```
@Override
    public default void setItems(Collection<T> items) {
        setDataProvider(DataProvider.ofCollection(items));
    }
```

Another option would be for the Grid check if the current data provider was a ListDataProvider, and if so call either call setList() on it, or to maintain a mutable list, updating it on subsequent calls to setItems.

**Comment by pwilkin** [comment]
The problem is, the `Grid` has no idea whether the previous data provider was created using `setItems` or in some other way (i.e. by specifying a data provider). Working around this might introduce too much unneeded logic. However, I do believe that there should be a way to transfer the filtering.

**Comment by Flamenco** [comment]
I think if you call setItems, and the grid does not have a data provider, it should cache the provider created after the call.  If setItems is called again, and the data provider has not changed, and it is an instance of ListDataProvider, it should update the cached provider instead of creating a new one.  That's not too complicated.

**Comment by Flamenco** [comment]
setItems is a bit of a 'black-box' convenience function anyway...

**Comment by tsuoanttila** [comment]
If you don't have any custom setup in your `DataProvider` the setItems is a handy way to use the components. If doing lots of set up, like filters, you should use `Grid::setDataProvider` and keep the reference by yourself. Then changing the content of the DataProvider and calling `DataProvider::refreshAll` will reset the content of the Grid while keeping your DataProvider and it's setup intact.

**Comment by Flamenco** [comment]
@tsuoanttila I understand how to use ListDataProvider directly.  The reality is that setItems is a shortcut for creating a ListDataProvider, and it is counterproductive, inconsistent, and non-intuitive to recreate the provider on subsequent calls.  IMO keeping the data provider is even more ‘handy’.

At the very least, you should document that the provider will be wiped out every time setItems() is called, but I feel pretty strongly that the current behavior is not ideal and 99% of the use cases would prefer the implementation similiar to the way I suggest.  The other 1% could do as you suggest and mange the provider directly.

**Comment by Flamenco** [comment]
We have rewritten large chunks of Vaadin over here after deciding that going through official channels for PRs and bug/feature reports is like pulling teeth.
