### ISSUE TITLE
RichTextArea removes the closing backslash in image tag

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10261]
For whatever reason the following code:
```
<img src=""/> 
```
results in:
```
<img src=""> 
```
when doing a getValue() from the RichTextArea. This is fine for rendering html but I also need to pass the resulting html as xml to generate a PDF and it fails as this is not legal xml code, it needs the closing backslash. 

The bug is that the RichTextArea should not edit valid html code...

**Comment by elmot** [comment]
In html4 self-closing tags are invalid. In html5 void elements may or may not contain the slash at the end.
`<img src=""/>` technically is equivqlent to `<img src="">`

I close the ticket as not a bug.
