### ISSUE TITLE
setVisible() on another component causes the current component to lose focus

### ISSUE THREAD

**Issue by OldIMP** [vaadin/framework#10270]
- Vaadin Framework version: 8.1.5
- Description of the bug
Assume that there're 2 components A&B in a layout and component A has the focus. If we call programmatically `setVisible(false)` on component B. then component A will lose focus. This is especially annoying if component A is a TextField and component B is refreshed according to its content.
- If possible, minimal reproducible example
```java
textField.addValueChangeListener(event -> errorLabel.setVisible(false));
```
will cause the textField to lose focus as soon as the user starts to type anything and interrupts the user's input
- Workaround
Right now we have to refocus the textField everytime:
```java
textField.addValueChangeListener(event -> {
    errorLabel.setVisible(false);
    textField.focus();
});
```

**Comment by anasmi** [comment]
Hi,
I have tested it with 8.3.3 version and was not able to reproduce the issue. Could you check if upgrade solve the problem for you?

**Comment by anasmi** [comment]
Actually was not able to reproduce in 8.1.5 either.


This is my code(should follow exactly the same logic as yours):
 ```
Label errorLabel=new Label("Error");
        final TextField name = new TextField();
        name.setCaption("Type your name here:");
        name.addValueChangeListener(event -> {
            errorLabel.setVisible(false);
        });

```

What have I missed?

**Comment by OldIMP** [comment]
Retested w/ 8.5.2. Can't reproduce anymore.

@anasmi thx for the feedback. The Github mail was blocked by Gmail spam filter so i didn't see it. Sry! 😄

**Comment by anasmi** [comment]
No problem : ) Thanks for the feedback !
