### ISSUE TITLE
View.enter() is not always called when navigating back

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#10281]
- Vaadin Framework version 8.2.0.alpha2

When moving from a view with a parameter e.g. `/tabbed-view/third-tab` to the view's root e.g. `/tabbed-view` with browser's back button the view's enter method is not called.

This is inconsistent with moving from `/tabbed-view/second-tab` to `/tabbed-view/second-tab` with back button: `enter()` is called.

Also subsequently navigating from `/tabbed-view/second-tab` to `/tabbed-view/second-tab` and to `/tabbed-view`: `enter()` is called on both navigation events.

Video demo: `enter()` method should always called when navigating back. It shows a notification, updates the active tab & page title. : https://www.youtube.com/watch?v=S_XRM_ap-PY

Test application:
https://github.com/Wnt/push-state-test

**Comment by Wnt** [comment]
Issue still persist in Vaadin 8.3.3 and 8.4.0.alpha1

**Comment by tsuoanttila** [comment]
Can you test if PR #10404 does anything to this issue? I think it's related to some parts of this but the contributor has not answered any of my open questions...

**Comment by Wnt** [comment]
Tried running with Vaadin 8.3-SNAPSHOT compiled from from https://github.com/Darsstar/framework/tree/pushstate_navigation but the issue still persists.

**Comment by Wnt** [comment]
The issue still exist in the latest released version of Vaadin (8.5.1)
