### ISSUE TITLE
Grid: Moving horizontally between components within the grid by using tabulator key (Vaadin 8).

### ISSUE THREAD

**Issue by lordmikefin** [vaadin/framework#10288]
Issue with Vaadin '8.1.6'

###### Preparation
First you need a grid with columns outside the view. So that the grid has horizontal scroll bar.
Each cell has to have focusable component in them.

#### 1st "feature"
Now select (focus on) the first component within the grid and started moving to next and next component until focus finally end up to the last visible component in that row.

Now look at the horizontal scroll bar. It has not moved. This is not what I would expect.

###### How it should work instead
I think scroll bar should move with the view.

#### 2nd "feature"
(Use the same grid)
First move the horizontal scroll bar to the end.
And select (focus on) the last component on a row.
What happens -> Focus is moved to the 1st component on the next row. This works as I would expect.

But the component is out of view. This is not what I would expect.

###### How it should work instead
I think the view and the scroll bar should move with focus movement.

##### Related issue
I think this issue relates to [issues 8188](https://github.com/vaadin/framework/issues/8188) and [issues 7781](https://github.com/vaadin/framework/issues/7781)

**Comment by tsuoanttila** [comment]
This one is most likely fixed along with the other mentioned issues, including #10287

**Comment by TatuLund** [comment]
1st issue is duplicate of #8188 and fixed in 8.4.0

**Comment by AndreiBoaghe** [comment]
> 1st issue is duplicate of #8188 and fixed in 8.4.0

Is still reproducible in 8.4.5.
Is there update on this issue? Is there any workaround???

**Comment by tsuoanttila** [comment]
Can you please post example code where you see this failing?

**Comment by AndreiBoaghe** [comment]
Demo (change the file extension from zip to war):
[grid.sample-1.0-SNAPSHOT.zip](https://github.com/vaadin/framework/files/2209847/grid.sample-1.0-SNAPSHOT.zip)


1.  Select the TextField, which is not entirely displayed.

![image](https://user-images.githubusercontent.com/23465246/42941047-1e1ea530-8b64-11e8-95fd-131134cc7f67.png)

2. Press the "Tab" button.

3. As you can see at the screen below horizontal scrollbar remained in its left most position, while the Grid content moved to the right. 

![image](https://user-images.githubusercontent.com/23465246/42941302-00410f20-8b65-11e8-91cb-42b96f79a260.png)

For more detailed issue description see: [https://github.com/vaadin/framework/issues/7781](url)

**Comment by AndreiBoaghe** [comment]
Hi, any update?)
Bug is still reproducible
