### ISSUE TITLE
RichTextArea and/VS Accordion

### ISSUE THREAD

**Issue by dantedantas** [vaadin/framework#10299]
- Vaadin Framework version: 8.1.4
- Browser test: Chrome, IE, Firefox.
- SO: Win10 Enterprise 2016 LTSB

Vaadin Forum:
[https://vaadin.com/forum/#!/thread/16862536](https://vaadin.com/forum/#!/thread/16862536)

Hello,
I am using a RichTextArea inside of an Accordion and the component RichTextArea doesn't show any text on the Text area. 
When I load the project and call a Notification event by using the getValue() method, the text is there.

```
//        my_RichTextArea.addValueChangeListener(event -> {
//        	Notification.show("Value changed X:", String.valueOf(event.getValue()),
//                    Type.TRAY_NOTIFICATION);
//        			}
```

If I use the RichTextArea alone I don't have any problem.

Below a screenshot of my project. 
![okkk](https://user-images.githubusercontent.com/10854571/32495308-735f1cda-c3c5-11e7-9e35-05a2e2eed809.jpg)

Code:

```
Accordion accordion = new Accordion();

RichTextArea rtaMainProduct = new RichTextArea();
rtaMainProduct.setSizeFull();

Layout tab2 = new VerticalLayout(); 
tab2.addComponent(rtaMainProduct);

accordion.addTab(tab2, "Text", VaadinIcons.PACKAGE, 0);
        
rtaMainProduct.setValue("<h1>Hello</h1>\n" +
            "<p>This rich text area contains some text.</p>");
```

**Comment by dantedantas** [comment]
Please, may someone help me?

**Comment by igux28** [comment]
I'm facing the same problem and it seems still is not a solution.
Any trick at least??
I made it worked adding the vaadin 7 compatibility package and using the Vaadin 7 RichTextAreaComponent but this is not the best solution...
@dantedantas Did you solved it ??

Thanks!
