### ISSUE TITLE
Remove unnecessary width calculation on Grid initial render

### ISSUE THREAD

**Issue by abishekram** [vaadin/framework#10301]
- Vaadin Framework version: 7.7.11

In Grid, initial column rendering is taking to much time.On addition of each column, width is calculated in client side.

It was fixed in vaadin 8. But still available in vaadin 7.

https://github.com/vaadin/framework/pull/8848

**Comment by TatuLund** [comment]
This was done by https://github.com/vaadin/framework/pull/11261 and https://github.com/vaadin/framework/pull/11199
