### ISSUE TITLE
Tree not allowing same item multiple times

### ISSUE THREAD

**Issue by vpanu** [vaadin/framework#10314]
Version 8.1.6
I need to show user roles as tree, with same user (User 2) within 2 roles (Admins and Supervisors):

TreeData<String> data = new TreeData<>();
data.addItems(null, "Roles")
                .addItems(null, "Admins", "Supervisor")
                .addItems("Admins", "User 1", "User 2")
                .addItems("Supervisors", "User 2", "User 3");

Because in version 8 Tree is actually a TreeGrid I cannot do this (on version 7 it works fine):
java.lang.IllegalArgumentException: Cannot add the same item multiple times: User 2

**Comment by skulai** [comment]
Same issue. Cannot add the same item multiple times: 
Did you find any solution to this?

**Comment by TatuLund** [comment]
"java.lang.IllegalArgumentException: Cannot add the same item multiple times: "

This exception is thrown by TreeGrid and is intentional behavior. I.e. current implementation is not supporting duplicate items and this is just consistency check.

**Comment by vpanu** [comment]
I understand it's an intentional behavior, but please check the example and let me know why I cannot do a basic tree where the same child (User 2) belongs to 2 parent nodes (roles Admins and Supervisors)

**Comment by vpanu** [comment]
On Vaadin 7 we used the Tree component and the model consists in Hibernate beans from DB and it works fine. On Vaadin 8, if I'll override the equals method to include the parent_id (so the same DB object will return equals==false as suggested) it will impact the Hibernate behavior.
TreeGrid replacement for the Tree was one of the reasons not to upgrade to Vaadin 8.

**Comment by TatuLund** [comment]
Overriding equals is not a good idea, using DTO layer was what I had in my mind, i.e. not using data base objects directly.
