### ISSUE TITLE
Multiple clicks on Combo-box leads to its flickering and collapse

### ISSUE THREAD

**Issue by Vinod08** [vaadin/framework#10310]
Vaadin Framework version - 7.6.8

Summary of the issue - 
Multiple clicks on Combo-box leads to its flickering and collapse

Reproducible steps - 

1. Clicked multiple times in quick succession on the drop-down arrow of the Combo-box.
2. Now click on the Combo-box, you can observe the combo-box flickers and it collapses immediately. It does not allow the user to a value inside the combo-box.

**Comment by tsuoanttila** [comment]
Fixed in 7.7.1, see issue #6744

**Comment by Vinod08** [comment]
Thanks Team for fixing the issue.
