### ISSUE TITLE
Tree item selection not working when parent has icon

### ISSUE THREAD

**Issue by vpanu** [vaadin/framework#10313]
Version 8.1.6
Any clicks on the red zone will not be recognized and the item selection will not be performed:
 
![image](https://user-images.githubusercontent.com/14961660/32690691-4cddf842-c703-11e7-9d2b-63e248d142b7.png)

Vaadin 8 sampler: (https://demo.vaadin.com/sampler/#ui/grids-and-trees/tree-grid/tree-sample)

**Comment by elmot** [comment]
Still valid
