### ISSUE TITLE
Using Page.pushState() can cause browser to load resources from wrong URLs

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#10329]
- Vaadin Framework version 8.2.0.alpha2

When you call `Page.pushState()` in the enter method of a View the browser (Chromium version 62.0.3202.75) to load favicon from a wrong url:
navigate to 
https://vaadinfiddle.com/editor/container/musing_northcutt
(the app is using `@PushStateNavigation` with navigator)
the browser tries to load favicon from:
https://vaadinfiddle.com/editor/container/musing_northcutt/src/main/java/org/vaadin/VAADIN/themes/vaadin-fiddle/favicon.ico

The View that opens from https://vaadinfiddle.com/editor/container/musing_northcutt calls `Page.getCurrent().pushState("https://vaadinfiddle.com/editor/container/musing_northcutt/src/main/java/org/vaadin/vaadinfiddle/MyUI.java");`
in the enter method.

I guess the relative path the browser is trying to use for the favicon is only valid for the initial page URL, but not for the pushed URL anymore.

**Comment by elmot** [comment]
Is the issue reproducible outside of vaadinfiddle?

**Comment by Wnt** [comment]
@elmot Yes.

**Comment by chvndb** [comment]
Having the same issue here.

**Comment by TatuLund** [comment]
We have been unable to reproduce this since Vaadin 8.8.5
