### ISSUE TITLE
Issue with input prompt for Vaadin 7 fields when using Vaadin Board

### ISSUE THREAD

**Issue by mrminy** [vaadin/framework#10335]
- Vaadin Framework version: 8.1.6 (in compatibility mode)
- JDK: 1.8.0_144
- The bug does not apply for Chrome 62
- The bug applies for Firefox 57, IE 11 and Edge 40

The bug:
When Vaadin-board is included in the pom.xml, Vaadin 7 fields (at least TextField and ComboBox) does not work with input prompt. What happens is that the browsers (FF, IE and Edge) does not remove the input prompt, but rather begins to edit the prompt. Therefore, the value of the field is never set.

This only happens when importing Vaadin-board in the pom.xml:
```
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-board</artifactId>
	<version>1.0.1</version>
</dependency>
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-board-precompiled</artifactId>
	<version>1.0.1</version>
</dependency>
```

Example image of an edited input prompt in v7 TextField: 
![vaadin_error](https://user-images.githubusercontent.com/14825623/32938761-8c841340-cb7d-11e7-9fa1-a645d1efd57d.PNG)

**Comment by TatuLund** [comment]
The reason is probably the same (webcomponents_lite.js polyfill library) as with this issue: https://github.com/vaadin/framework/issues/10414
