### ISSUE TITLE
 UIScoped, NormalUIScoped or SessionScoped @CDIView does not work as expected

### ISSUE THREAD

**Issue by bingtimren** [vaadin/framework#10341]
Environment:
Vaadin 8.1.6, Vaadin-CDI 2.0.0, WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) server

Summary of the problem:
By definition, UIScoped, NormalUIScoped or SessionScoped beans all should have just one instance per UI or user session. However, when an UIScoped, NormalUIScoped, or SessionScoped @CDIView annotated View was created by CDIViewProvider in navigation, and if that view @Observes certain event, then if such event was fired, it seems that the CDI container does not realise there is already an instance (so as to directly call the observer method of that existing instance). Then, a new instance was initiated, and that new instance received, or "observed" the event. However, the first CDIView, more importantly, the CDIView that was actually shown to the user, did not receive the event.

A full description of the problem is at [here](https://vaadin.com/forum/#!/thread/16871878)

A minimal reproducible example is also attached.

Bing
[GridLayoutProblemDemo.zip](https://github.com/vaadin/framework/files/1487421/GridLayoutProblemDemo.zip)

**Comment by tsuoanttila** [comment]
Hi @bingtimren,

can you test if this issue exists in the 3.0.0.alpha1 version of our CDI plugin? There's a number of fixes regarding this topic.

**Comment by tsuoanttila** [comment]
Also this seems to be more or less in the wrong repo. https://github.com/vaadin/cdi is the location for CDI related issues.

**Comment by tsuoanttila** [comment]
Issue moved to [vaadin/cdi #228](https://github.com/vaadin/cdi/issues/228) via [**ZenHub**](https://www.zenhub.com/)
