### ISSUE TITLE
combobox-multiselect have bug

### ISSUE THREAD

**Issue by yanghua0311** [vaadin/framework#10364]
<dependency>
	<groupId>org.vaadin.addons</groupId>
	<artifactId>vaadin-combobox-multiselect</artifactId>
	<version>2.2</version>
</dependency>
cannot make multiple choices，It's a strange problem, like an incompatible browser

**Comment by Legioth** [comment]
The component that you're referred to is a third party add-on that is not part of the core Vaadin Framework. Please file an issue at https://github.com/bonprix/vaadin-combobox-multiselect instead.
