### ISSUE TITLE
Rows beneath grid details are rendered on top of the details after markAsDirty() V7 regression

### ISSUE THREAD

**Issue by neelu-sarkar** [vaadin/framework#10363]
Noticed after the upgrade from v7.7.10 to 7.7.11. This appears to be a regression that is holding up our upgrade to the latest version. I've also tested with 7.7.12 and the same issue occurs.

Steps to recreate in our application:
1. View grid and open grid details for a row.
2. Perform an interaction in the app that marks the grid as dirty and re-renders it. With Firefox and Edge this can sometimes require 2 of these interactions. Chrome and IE seem to only require one.

It looks like the height of the grid details hasn't been calculated correctly with very similar symptoms to the ones described in https://github.com/vaadin/framework/issues/7319

The details is rendered 'behind' the rows beneath the one the details is open for. Moving the mouse over these rows causes a kind of 'mouse over' effect and parts of the details then get moved to the front temporarily.

After inspecting the row where the details is shown, it looks like the wrong height has been calculated. I've tried setHeight() explicitly for the component displayed in the details, but it didn't have any effect.

This is a high priority bug for us as we can't upgrade without this being resolved.

**Comment by wbadam** [comment]
This was introduced with https://github.com/vaadin/framework/pull/9799. There is a patch under review for master https://github.com/vaadin/framework/pull/10343, once it's merged, it can be backported to 7.7 branch.
