### ISSUE TITLE
Vaadin 8 Grid - Menubar disappear

### ISSUE THREAD

**Issue by avsart** [vaadin/framework#10379]
I use Vaadin 8.1.5.

My grid has component columns. One of columns is HorizontalLayout that contains TextField and MenuBar. But MenuBar disappears when i scroll the grid. When i expand the column, menubar starts to appear. But when scroll it disappears again. It just paints the parts thats seen on the screen. 

![2017-11-27 16_11_39-construction portal](https://user-images.githubusercontent.com/34054360/33306576-2afb24ec-d424-11e7-891b-3dae8f1de91f.jpg)

My code: 
`
grid.addComponentColumn(item -> {
			return createBigDecimalFieldColumn(item, DetailEstimateLine::getTotalPrice, DetailEstimateLine::setTotalPrice, true);
		});
`
.........................

`
 private HorizontalLayout createBigDecimalFieldColumn(DetailEstimateLine line,
			ValueProvider<DetailEstimateLine, BigDecimal> getter, Setter<DetailEstimateLine, BigDecimal> setter,
			boolean showMenuBar)
	{
		
                HorizontalLayout layout = new HorizontalLayout();
		layout.setWidth(100, Unit.PERCENTAGE);
		layout.setSpacing(false);
		layout.setMargin(false);
		layout.addStyleName(ValoTheme.LAYOUT_COMPONENT_GROUP);
		
                BigDecimalField priceField = createBigDecimalField(line, getter, setter);
		layout.addComponent(priceField);
		if (showMenuBar)
		{
			MenuBar barMenu = new MenuBar();
			barMenu.addStyleName(ContractorTheme.MENUBAR_MORE);
			barMenu.addStyleName(ContractorTheme.MENUBAR_GRAY);
			barMenu.setHtmlContentAllowed(true);
			barMenu.addStyleName(ValoTheme.MENUBAR_BORDERLESS);
			barMenu.addStyleName(ContractorTheme.DROPDOWN_NOCARET);
			MenuItem priceMenu = barMenu.addItem("<div class='contr-icon ai-20 ai-more'></div>", null, null);
			priceMenu.addItem(ContractorHelper.getResourceString(detailEstimateListID, 45), new Command()
			{
				@Override
				public void menuSelected(final MenuItem selectedItem)
				{
					openWorkItemAnlyPrices(line);
				}
			});
			priceMenu.addItem(ContractorHelper.getResourceString(detailEstimateListID, 46), new Command()
			{
				@Override
				public void menuSelected(final MenuItem selectedItem)
				{
					openWorkItemOldPrices(line);
				}
			});
			barMenu.setEnabled(line.getLineType().getId() == ContractorConstant.DETESTIMATELINETYPE_WORKITEMGROUP
					? false
					: true);
			layout.addComponent(barMenu);
			layout.setComponentAlignment(barMenu, Alignment.MIDDLE_RIGHT);
		}
		layout.setExpandRatio(priceField, 1.0f);
		return layout;
	}`

**Comment by anasmi** [comment]
Hi, 
have you checked that the height of your layout(textfield + menubar) inside the cell is not bigger, than the height of the cell itself? Also, the height of the layout's components should not exceed the height of the grid's cell
