### ISSUE TITLE
Grid is to slow to use with many columns

### ISSUE THREAD

**Issue by Dirk43** [vaadin/framework#10375]
Hi, 
we have an performance issue with vaadin 8 and Grid. 
We found similar issues here #10232. 
In our case we have a grid with more than 100 columns (but only 40 rows). Rendering takes more then 4 minutes. 
Vaadin Version is 8.1.6. 
The old table component is much faster.

Find attached a small project that shows a grid with 100 columns and 40 rows. 
[vaadin.grid.zip](https://github.com/vaadin/framework/files/1502137/vaadin.grid.zip)

**Comment by pleku** [comment]
Hey, thanks for the test case.

Closing this as a duplicate for #10375, please refer to that issue instead.

**Comment by Dirk43** [comment]
?? #10375 is this issue, you mean  cloasing this as a duplicate of #10232

**Comment by pleku** [comment]
Oops, yeah that one. Thanks
