### ISSUE TITLE
ComboBox treats cursor keys like changes of the text.

### ISSUE THREAD

**Issue by RobertZenz** [vaadin/framework#10374]
This is reproducible in the [ComboBox sample application](https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box).

The cursor keys are treated by the combobox like changes of the text, which means that the currently entered value is committed as searchterm and the cursor is reset to the end of the text.

Reproduce:

 1. Focus combobox
 2. Press down a few times to select an item, the selected items is pasted into the textfield.
 3. Press left/right keys.

**Comment by bassmartin** [comment]
This seems to be fixed in 8.5.1

**Comment by elmot** [comment]
@bassmartin, @knoobie thanks
