### ISSUE TITLE
Connection lost by click deep-linking on Mobile browser

### ISSUE THREAD

**Issue by tstsogoo** [vaadin/framework#10398]
Vaadin 8.2.0.beta1
Spring boot
@Push(transport = Transport.WEBSOCKET_XHR)

link exapmle: 
`Label label_tel = new Label("<a href='tel:" + tel+ "'>" + tel+ "</a>", ContentMode.HTML);`

**Comment by elmot** [comment]
Please try to use ```target="_blank"``` attribute
