### ISSUE TITLE
Disabled checkboxes or radio buttons can't be seen from the UI (again!!!)

### ISSUE THREAD

**Issue by Saxintosh** [vaadin/framework#10407]
### Description of the bug

Disabled option in CheckboxGroup or RadioButtonGroup looks exactly like a normal option.

### Example code to reproduce

this doesn't work:

    rbg = new RadioButtonGroup<>("My Disabled Group");
    rbg.setItems("One", "Two", "Three");
    rbg.setItemEnabledProvider(item-> !"Two".equals(item)); // doesn't work
    rbg.getDataProvider().refreshAll(); // still doesn't work

strange behaviour: if triggered at a later time, the getDataProvider().refreshAll() will finally shows as disable the "disabled item"!

    Button button = new Button("Click Me");
    button.addClickListener(e -> {
        rbg.getDataProvider().refreshAll(); // now it works!!!
    });

**Comment by Saxintosh** [comment]
The bug is still present in 8.2.1

**Comment by Saxintosh** [comment]
Bug still present in 8.3.1

**Comment by timothygruetzner** [comment]
Could this please be fixed? Issue is present since a long time..

**Comment by mstahv** [comment]
I placed a bounty on this: ![Bounty amount](https://api.bountysource.com/badge/issue?issue_id=52293132)

**Comment by mstahv** [comment]
Thanks Teemu for fixing this, spend your bounty well ;-)
