### ISSUE TITLE
Drag & Drop on Laptop with TouchScreen

### ISSUE THREAD

**Issue by StephaneOCS** [vaadin/framework#10408]
Vaadin framework 8.1.7.

Drag & Drop not working on Latptop with Touchscreen (like XPS 15)

Drag & drog don't work on this cumputer without "setMobileHtml5DndEnabled(true);"

With setMobileHtml5DndEnabled(true) , on a Grid,  we can drag only the first element.
I can reproduce the problem on "https://demo.vaadin.com/sampler/#ui/drag-drop/grid-reorder-rows-html5".

I must disable touch event "chrome://flags/ -> Touch Events API = disable" to be able to use the drag&drop.

On firefox, the drag&drop work with a graphical bug : There is a big shift between the mouse and the selected component.

**Comment by appreciated** [comment]
Possible duplicate with #9974? 
If so please close this issue and give the other some thumbs up!
