### ISSUE TITLE
Upload component allows upload to start with no file being selected

### ISSUE THREAD

**Issue by phansson** [vaadin/framework#10419]
Component:  `Upload`
Vaadin Framework version:   8.1.7  (latest and greatest, also reproduced on 8.2beta)

Problem: In non-immediate mode user can press the "Upload" button even if no file is selected:

![upload](https://user-images.githubusercontent.com/1903550/33711911-f59a1a32-db45-11e7-9325-4b3cbf44be35.png)

If the button is actually pressed it creates calls to `receiveUpload()` with parameters:

    filename = ""
    mimeType = "application/octet-stream"

All in all this is a usability bug and it should be easy to fix.

**Comment by tarekoraby** [comment]
This seems like a design feature, not a bug. From the Upload component docs:
> If the field is empty uploaded the file name will be empty string and file length 0 in the upload finished event.

See also https://github.com/vaadin/framework/issues/2821
