### ISSUE TITLE
Possible to shift-tab out of modal Window when custom tabindex is set

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#10415]
Note: There are some other tickets related to this issue and also some fixes, including this one: https://github.com/vaadin/framework/pull/10260 . However, in 8.1.7 this is still reproducible and broken, I believe it relates to the custom tab indexes.

- Vaadin Framework version 8.1.7 , doesn't seem to depend on browser
- Steps to reproduce: 
* Run and open example app.
* Click button to open modal Window
* Click on first text field inside window to focus on it
* Press shift+tab. 
Outcome: focus moves outside Window
Expected: focus does not move outside Window

- Example app
[window-tab-test.zip](https://github.com/vaadin/framework/files/1531683/window-tab-test.zip)

**Comment by elmot** [comment]
That might be a duplicate of #10654.
Can you verify if is fixed in 8.4.x?
