### ISSUE TITLE
Tabsheet does not scroll to left after tab was closed

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#10418]
This is no real bug, but a rather annoying usability issue if the user has many open tabs.

![menuleiste](https://user-images.githubusercontent.com/3159661/33705841-2b52d132-db32-11e7-8cbb-0fa3b589af3f.gif)

In general the tabsheet is not really extendable, which prevents us from fixing some issues by ourselves.
It would be really nice to not embedd everything in (private) inner classes to make subclassing
easier :-) E.g. we want to introduce a context menus on the tabs (there is another issue for this, see
#9725)

**Comment by tsuoanttila** [comment]
The UX issue of not scrolling automatically is indeed a pain. 

The `ContextClick` features on a `TabSheet` is actually something you can improve. You basically have to extend the `TabSheet` and make a custom `Connector` for it. In the connector override the `protected void sendContextClickEvent` and have it call your own RPC that takes in all the data you want. Then fire the corresponding `MyCustomTabSheetContextClickEvent` and now you have all the information you wanted to add there. 

Then you can use for example our ContextMenu add-on to create the menu on the server and show it. Unfortunately some manual

**Comment by bjung82** [comment]
Hi,

can you please elaborate a litte bit on your proposed solution for the context-menu? I don't know
how to get the information on which tab-header the right-click has happened.. and then how to "fire
the corresponding context click event"?

Your answer seems to be truncated ;-)

**Comment by tsuoanttila** [comment]
Let's give an example. The `Grid` component has custom context click events on the server. Can be found [here](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L415).

There's a [corresponding RPC](https://github.com/vaadin/framework/blob/master/shared/src/main/java/com/vaadin/shared/ui/grid/GridServerRpc.java#L64) for telling the information needed for Grid context clicks to the server.

To fire the custom event the [server-side implementation](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L634) of the RPC uses the given information to fire the desired event.

The client-side connector has overridden the default implementation that only sends the information on where the component was clicked and uses the APIs of the Grid, but could use any the DOM as well, to figure out the needed information and sends it to the server. This implementation is available [here](https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/connectors/grid/GridConnector.java#L654).

For example the [implementation](https://github.com/vaadin/framework/blob/master/compatibility-client/src/main/java/com/vaadin/v7/client/ui/table/TableConnector.java#L82) of the `Table` uses more the DOM and less the Widget APIs to figure out what part of the `Table` the context click is targeting.

If the API of the TabSheet on the client is too closed, you can use for example `Tab::setId` or `Tab::setStyleName` to help you find the correct tab.

**Comment by bjung82** [comment]
Thank you very much for your tipps for #9725 - we implemented this and I just closed #9725.

**Comment by bjung82** [comment]
This issue was caused by a CSS- margin in our implementation which confused the scroller of the tabsheet.
