### ISSUE TITLE
ItemClickListener in Grid does not get triggered on Resources or Layouts in columns.

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/framework#10425]
If I have a Column with a custom component (e.g. layout) or a Resource , the ItemClickEvent does not fire.

**Comment by TatuLund** [comment]
Have you checked this one, I think it is about the same thing https://github.com/vaadin/framework/issues/10237

**Comment by tsuoanttila** [comment]
#10412  might be the thing you are interested in. For the custom component column call `column.setWidgetEventsAllowed(true)`
