### ISSUE TITLE
Modal Window doesn't disable background for screen readers

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#10424]
- Tested with Windows 10 + Chrome 62 + NVDA 2017.4 screen reader
- Reproducable in Sampler: https://demo.vaadin.com/sampler/#ui/structure/window
- Open the Window and check the Modal checkbox
- Move mouse over some component behind the modality curtain
- Outcome: components behind the modality curtain are dictated
- Expected: components behind the modality curtain are ignored, possibly with the `aria-disabled` flag set in the root UI element
See https://www.w3.org/WAI/PF/aria/states_and_properties#aria-disabled:
> Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. See related aria-hidden and aria-readonly.

> For example, irrelevant options in a radio group may be disabled. Disabled elements might not receive focus from the tab order. For some disabled elements, applications might choose not to support navigation to descendants. In addition to setting the aria-disabled attribute, authors SHOULD change the appearance (grayed out, etc.) to indicate that the item has been disabled.

> The state of being disabled applies to the current element and all focusable descendant elements of the element on which the aria-disabled attribute is applied.

Consider also using the [aria-modal](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) property:

> aria-modal=true | div | Tells assistive technologies that the windows underneath the current dialog are not available for interaction (inert).

**Comment by Legioth** [comment]
From a semantic point of view, `aria-modal` sounds like a much better match than adding `aria-disabled` all over the place.

**Comment by knoobie** [comment]
I would prefer aria-model as well, keep in mind that aria-model is from ARIA 1.1 and not all screenreader support this spec - of course it would be good in the long run.
