### ISSUE TITLE
Upload component:  ChangeListener only fires once

### ISSUE THREAD

**Issue by phansson** [vaadin/framework#10420]
Component:  `Upload`

Problem: The `Upload.ChangeListener` only fires once.
Vaadin Framework version:   8.1.7  (latest and greatest, also reproduced on 8.2beta)

## How to reproduce:

Use the below minimal example:

```java
public class MyUI extends UI 
        implements Upload.Receiver, Upload.ChangeListener {

    private static final Logger LOGGER = Logger.getLogger(MyUI.class.getName());
    
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        Upload upload = new Upload("Upload file", this);
        upload.setImmediateMode(false);
        upload.addChangeListener(this);
        layout.addComponents(upload);
        setContent(layout);
    }

    @Override
    public OutputStream receiveUpload(String filename, String mimeType) {
        // a NULL outputstream, does nothing
        return new OutputStream() {
            @Override
            public void write(int b) throws IOException {
            }
        };
    }

    @Override
    public void filenameChanged(Upload.ChangeEvent event) {
        LOGGER.log(Level.INFO, "filenameChange() called !!");
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}

```

Steps:

- Start the web app.
- Pick a file and press "Upload". Check in the log that the filenameChanged() method has fired.
- Repeat previous step (possibly with another file this time). Notice that filenameChanged() method doesn't fire again.

## Why is this serious ?

The Upload component has a [usability bug](https://github.com/vaadin/framework/issues/10419) in that allows the "Upload" button (in non-immediate mode) to be pressed, even if no file is selected. To workaround this, you can use the `Upload.ChangeListener` (together with `Upload.FinishedListener`) to enable/disable the button that starts the upload. However, if `Upload.ChangeListener` doesn't really work (except first time), then such a workaround won't work.

**Comment by alexandru78** [comment]
> Component: `Upload`
> 
> Problem: The `Upload.ChangeListener` only fires once.
> Vaadin Framework version: 8.1.7 (latest and greatest, also reproduced on 8.2beta)
> 
> ## How to reproduce:
> Use the below minimal example:
> 
> ```java
> public class MyUI extends UI 
>         implements Upload.Receiver, Upload.ChangeListener {
> 
>     private static final Logger LOGGER = Logger.getLogger(MyUI.class.getName());
>     
>     @Override
>     protected void init(VaadinRequest vaadinRequest) {
>         final VerticalLayout layout = new VerticalLayout();
>         
>         Upload upload = new Upload("Upload file", this);
>         upload.setImmediateMode(false);
>         upload.addChangeListener(this);
>         layout.addComponents(upload);
>         setContent(layout);
>     }
> 
>     @Override
>     public OutputStream receiveUpload(String filename, String mimeType) {
>         // a NULL outputstream, does nothing
>         return new OutputStream() {
>             @Override
>             public void write(int b) throws IOException {
>             }
>         };
>     }
> 
>     @Override
>     public void filenameChanged(Upload.ChangeEvent event) {
>         LOGGER.log(Level.INFO, "filenameChange() called !!");
>     }
> 
>     @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
>     @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
>     public static class MyUIServlet extends VaadinServlet {
>     }
> }
> ```
> 
> Steps:
> 
> * Start the web app.
> * Pick a file and press "Upload". Check in the log that the filenameChanged() method has fired.
> * Repeat previous step (possibly with another file this time). Notice that filenameChanged() method doesn't fire again.
> 
> ## Why is this serious ?
> The Upload component has a [usability bug](https://github.com/vaadin/framework/issues/10419) in that allows the "Upload" button (in non-immediate mode) to be pressed, even if no file is selected. To workaround this, you can use the `Upload.ChangeListener` (together with `Upload.FinishedListener`) to enable/disable the button that starts the upload. However, if `Upload.ChangeListener` doesn't really work (except first time), then such a workaround won't work.

same thing still happens in Vaadin Framework version: 8.8.6

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin/framework/issues/10419
