### ISSUE TITLE
Tooltip stuck on mobile devices (Touch devices)

### ISSUE THREAD

**Issue by renierr** [vaadin/framework#10435]
- Vaadin Framework version
7.7.10
- Description of the bug
If you have Tooltips on Captions (or somewhere else) and use a mobile Browser like Chrome mobile on Android - with a touch device.

The Tooltip get stuck and you can not remove it.

- example
1. Long touch on a caption with a Tooltip
2. Tooltip appear
3. Touch somewhere else (clear area) to remove to tooltip
4. BUG: Tooltip stays visible

This only happen if the Tooltip is larger then the viewport. If the Tooltip is small enough to fit - you can remove the tooltip by touching in a clear area.

Strangely, if the tooltip get stuck you can touch other captions and the tooltip changes but the position stays absolute and it won't get removed if you select or navigate somewhere else.

**Comment by renierr** [comment]
If i add a margin-left > 1px on v-tooltip the effekt is gone - strange.

**Comment by KatriHaapalinna** [comment]
Issue is reproducible in Vaadin Framework version 8.4.5

**Comment by mil3stone** [comment]
This issue can be reproduced with Vaadin Framework 8.6.2

**Comment by jeffreybegley** [comment]
This issue can be reproduced with Vaadin framework 8.9.2.  

The comment from 2017 hinting at a workaround didn't work when I tried it: "If i add a margin-left > 1px on v-tooltip the effekt is gone - strange."  I tried 2px and 5 px but the bug still happened.

Once the bug has happened, there's no way to get rid of the tooltip, other than refreshing the webpage.

**Comment by Ansku** [comment]
Have you tried if it's still there in Vaadin 8.13.0 ? I just noticed this comment right now and my workday is just ending, but would be good to confirm, since 8.9.2 is quite old already.

**Comment by jeffreybegley** [comment]
Hi Ansku.  Yes: I verified just now that the bug still occurs with Vaadin 8.13.0.

**Comment by Ansku** [comment]
Thanks for the report, seems to have been a pretty straightforward oversight!
