### ISSUE TITLE
DateField Popup: Header Buttons dont have aria-labels

### ISSUE THREAD

**Issue by m-escher** [vaadin/framework#10454]
Buttons (e.g. prev month/year, next month/year) in the Popup from DateField don't have aria-labels.
Their functionalities are therefore unknown for screenreaders like JAWS or NVDA

![datefield-buttons](https://user-images.githubusercontent.com/32167467/34161020-773d14d0-e4cf-11e7-8c65-c7647da79575.png)

**Comment by Legioth** [comment]
One small challenge here is that the label would probably be language dependent, and thus require explicit server-side API for configuration.

**Comment by jouni** [comment]
Are the buttons focusable? Instead of making them focusable and having a label, I think we should follow the recommended keyboard shortcuts for navigating months and years. Not sure if all screen reader users are aware of those, though.
