### ISSUE TITLE
Grid.Column#setSortable(false) has no effect

### ISSUE THREAD

**Issue by knoobie** [vaadin/framework#10467]
Using Grid with a "simple Datasource (setItems(List))" and adding columns with #setSortable(false) has no effect. 

## Code Example:

        grid.addColumn(Entity::getA).setSortable(false).setCaption("A");
        grid.addColumn(Entity::getB).setCaption("B");

## Expectation:

- [x] Column 'A' should **not be sortable** and there should be **no stylename** 'sortable'.
- [x] Column 'B' should be sortable and there should be a stylename 'sortable'.

## Current behaviour:

- [ ] Column 'A' _is sortable_ and _has the stylename_ 'sortable'.
- [x] Column 'B' is sortable and has the stylename 'sortable'.

Version:
- Vaadin Version: 8.2.0 & 8.3-SNAPSHOT

**Comment by tsuoanttila** [comment]
Seems like we need to introduce some kind of "explicitly not sortable" flag and not update the state when changing the data provider.

**Comment by ChrisKClark** [comment]
Not just when the dataprovider is changed: Grid.Column sortable state is also overridden when Column.setId() calls updateSortable().

**Comment by tsuoanttila** [comment]
See PR #10604
