### ISSUE TITLE
DateField not submitted on Return

### ISSUE THREAD

**Issue by guttormvik** [vaadin/framework#10488]
This is an issue in both 8.2.0 and 8.1.7
It works in 7.7.10

The following code has a textfield, a date field and a button. The button has Enter as shortcut.
When writing something in the textfield, it is submitted when I press Enter.
When writing something in the date field, it is *not* submitted when I press Enter.
It *is* submitted if I tab out of the field before pressing Enter, or if I click the button.

``` java
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        final TextField name = new TextField();
        name.setCaption("Type your name here:");

        final DateField dateField = new DateField("Date of birth");  
        
        Button button = new Button("Click Me");
        button.setClickShortcut(KeyCode.ENTER, 0);
        button.addClickListener(e -> {
            layout.addComponent(new Label("Thanks " + name.getValue() + ", it works! Your Date of birth is: " + dateField.getValue()));
        });
        
        layout.addComponents(name, dateField, button);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

Edit: I should add that in 8.1.7 it fails with both the regular version and the v7 compatibility version.
I have not tested the compatibility version in 8.2.
I have tested with Chrome 63.0, Edge 40 and Firefox 57.0

**Comment by wbadam** [comment]
This seems to be a regression. After the component was changed to be a non-legacy component, the value is no longer sent to the server when shortcut is pressed.
