### ISSUE TITLE
Grid has wrong width if no header

### ISSUE THREAD

**Issue by fante76** [vaadin/framework#10485]
Vaadin Framework 8.2.0

A grid without header (by grid.removeHeaderRow(0)) doesn't apply width settings, both on single columns then in whole grid.
The following code works on Vaadin 8.7.1

```
capGrid.setItems(capabilities);
capGrid.removeHeaderRow(0);
capGrid.setColumns("name");
capGrid.getColumn("name").setExpandRatio(1).setWidth(200);
capGrid.setSizeFull():
```

![image](https://user-images.githubusercontent.com/12963376/34482064-f9c0859a-efb5-11e7-90ef-30605af7f36a.png)

**Comment by rappenze** [comment]
This bug was introduced with pull request #10384. The code to add select all checkbox does not check if the header exists.
![missingnullcheck](https://user-images.githubusercontent.com/29733488/35218183-f72ee7c8-ff6d-11e7-927f-8e4901a92d9c.png)

So this bug is limited to grids where no default header row exists and the grid is in multi select mode.

Client side exception is:
![image](https://user-images.githubusercontent.com/29733488/35218274-4de0ebe8-ff6e-11e7-8097-5b96003cff01.png)

**Comment by buuzta** [comment]
Bug still exists in Vaadin 8.5.1.
Happens either with removeHeaderRow(0) or setHeaderVisible(false).

**Comment by anasmi** [comment]
Hi,

please, correct me, if I am wrong, but I don't think this is a bug per se. 
In your code you are setting explicitly the width and the expand rate on the same column simultaneously. In this case width is taking precedence.(The result you see)  If you want to specify the minimum width column should have, then you should probably use _setMinimumWidth_. 
```
Grid<String> grid = new Grid<>();
                    grid.addColumn(ValueProvider.identity());
                    grid.addColumn(String::valueOf).setExpandRatio(1).setWidth(250);
                    grid.setItems("a", "b");
                    grid.setSizeFull();
                    grid.setSelectionMode(Grid.SelectionMode.MULTI);
                   // grid.setHeaderVisible(false);
```
The code above produce to me the same visual result regardless of me having header column or not. (I hope its reproduce your use case also)

Using **setWidth**:
![withwidth](https://user-images.githubusercontent.com/15248706/45029576-ce03df80-b051-11e8-9b01-7517930d9952.jpg)


Using **setMinimunWidth** instead: 

![withminwidth](https://user-images.githubusercontent.com/15248706/45029580-d2c89380-b051-11e8-8ec0-e93c85db1aae.jpg)

Have I miss something? Could you share the code you have, if it's not the same as above?

**Comment by fante76** [comment]
My code is written above. The problem happens using grid.removeHeaderRow(0), you are not using it on your example. May be your workaround fits, I will try as soon as possible, but you can't said its not a bug.

**Comment by anasmi** [comment]
Hi,

indeed you are correct. When removing the row like you did I was able to reproduce the back.
In a meanwhile, you can use _grid.setHeaderVisible(false);_  as a workaround, but problem does indeed exist.

Thanks for clarifications!
