### ISSUE TITLE
Reloading page in Vaadin 8.2 while UI is annotated with @PreserveOnRefresh will reload all old notifications

### ISSUE THREAD

**Issue by Govanm** [vaadin/framework#10481]
- Vaadin Framework version (8.2.0)

 I updated our vaadin application from 8.1.7 to 8.2.0. I noticed a  major change in notifications. Reloading page would show all old  notifications (closed by user) again and user have to close them  manually. We are using @PreserveOnRefresh annotation in our UI and I  noticed that if I am removing @PreserveOnRefresh then reloading page  will not cause showing old notifications. We are using  @PreserveOnRefresh to maintain selected tab in application tab sheet. I found a solution to both keep @PreserveOnRefresh and not showing old  notifications while reloading page. By adding a closeListener (added in  Vaadin 8.2) and removing notification manually as below:
```
    Notification notification = new Notification("Parsing warning", message,
            Notification.Type.TRAY_NOTIFICATION);
    notification.setDelayMsec(-1);
    notification.addCloseListener((Notification.CloseListener) e -> e.getNotification().remove());
    notification.show(Page.getCurrent());

```
But this is not optimal for user to addCloseListener for every notification while using @PreserveOnRefresh.  By default Notifications should be removed even if @PreserveOnRefresh has been used . Then it is possible to have a flag in Notification constructor in case a user want to preserve a notification even after closing it with page reload.

**Comment by Artur-** [comment]
The Notifications are accidentatlly left on the server side when closed. The PR #10483 should fix this also

**Comment by mstahv** [comment]
Just faced this myself, really nasty in mobile apps (home screen web apps) where you want to keep the session between starts -> old irrelevant notifications are shown.
