### ISSUE TITLE
Followup for #8855 - window has to be resizable to remove focus trap

### ISSUE THREAD

**Issue by knoobie** [vaadin/framework#10484]
The issue #8855 isn't resolved for us because it only works if the window is resizable. Windows that aren't resizable won't change focus if you tab on the bottom of the window. 

**Example**:
- https://demo.vaadin.com/sampler/#ui/structure/window
- Config: modal = true, resizable = false

**Expected**:
- Focus should not be trapped when reaching bottom

**Actual**:
- Focus is trapped on the bottom 

Changing resizable to true fixes the problem. 

**Vaadin Version: 8.2+**

**Comment by OlliTietavainenVaadin** [comment]
This is probably happening because `getFocusableChildren` in `FocusUtil.java` will return even non-displayed elements, and the first child element it finds when called from `focusOnFirstFocusableElement` is the `display: none` resize button. Focus should go to the first visible element instead.
