### ISSUE TITLE
Highly stylized VButton should be able to grow vertically

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1048]
**Originally by @jouni**

___
The current implementation of VButton doesn't make it easy to make highly stylized themes for it. Horizontal growing is achieved with the sliding doors method, but vertically the button always stays the same (visually) when the contents of the button are taller than the default height, or when `Button.setHeight` is used

Possible solutions include using a TABLE element inside the button, which some other frameworks use. This should be the *last* solution, since TABLE's are very problematic and slow.

The Cameleon theme has these kind of stylized, growing buttons, but they rely on border-radius to look nice, which doesn't work in IE (until IE9 is released). Should image-only based solutions support this kind of flexibility, or is this issue not worth fixing?

___
 Imported from https://dev.vaadin.com/ issue #4422

**Comment by jouni** [comment]
Won’t fix/invalid.
