### ISSUE TITLE
strange component resizing after text is set to a textarea

### ISSUE THREAD

**Issue by salOd** [vaadin/framework#10496]
Hi,

i found this issue working with Vaadin 8.1.7. 

I reproduced it within your minimal Vaadin Maven Project  
[vaadin-app.zip](https://github.com/vaadin/framework/files/1603423/vaadin-app.zip)

There is a layout with 2 textareas and 1 button. The layout itself takes all the available space to grow by setting height/width to 100%. The first area is set to fullsize to fill the free space in the layout. A click on the button adds text to the second textArea. This causes the second area+button to jump off the layout and getting clipped.

`@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setSizeFull();

        TextArea someText = new TextArea("Some Text");
        someText.setSizeFull();
        layout.addComponent(someText);

        TextArea status = new TextArea("Status");
        status.setWidth(100, Unit.PERCENTAGE);
        layout.addComponent(status);

        Button button = new Button("Fill Status");
        button.addClickListener(e -> {
            status.setValue("OK");
        });

        layout.addComponent(button);
        layout.setExpandRatio(someText, 1f);

        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}`

**Comment by anasmi** [comment]
Hi,
that's not the proper solution, but a workaround.
You can call the `JavaScript.getCurrent().execute("vaadin.forceLayout();");`	to update the layout in your click listener.
As you might notice resizing the browser window restores the textAreas to the correct position and this JavaScript just updates the Layout without need of dragging browser window

**Comment by salOd** [comment]
hey anasmi, thanks for ur reply. Forcing the layout to update seems a good idea, never knew that this is possible in that way
