### ISSUE TITLE
Vaadin 8.2.0 Grid with multiselect shows label next to selection-checkbox

### ISSUE THREAD

**Issue by KasparScherrer** [vaadin/framework#10509]
After upgrading the Vaadin Framework to 8.2.0 Grids with SelectionMode.MULTI not only have a selection-checkbox as first column (expected behaviour), but also a Label that says "Selects row number XX". 

This Label is quite wide and uses a lot of precious space of the grid. This new behaviour is nowhere documented in the [release notes](https://vaadin.com/download/release/8.2/8.2.0/release-notes.html) of 8.2.0 

A possibility to remove this label has yet to be found. 
After downgrading to version 8.1.6 the labels are gone.

A minimal code example and screenshot can be found in my related [Stackoverflow question](https://stackoverflow.com/questions/48168507/vaadin-8-2-0-grid-how-to-remove-the-labels-from-multiselection-checkboxes?noredirect=1#comment83349208_48168507)

**Comment by knoobie** [comment]
This label should not be visible. This label was introduced by me in #10223. 

Do you have a custom theme where you excluded global.scss? Or is your css cached / old?

**Comment by tsuoanttila** [comment]
What @knoobie just commented. Also which browser you are using when you run into this issue?

**Comment by Artur-** [comment]
The label is visible if you are using an old theme version

**Comment by KasparScherrer** [comment]
It turned out that our project setup was not optimal, which is why I had to manually copy the updated VAADIN folder with the theme to another location. Thank you for the responses, they helped me a lot in finding the source of the problem (old CSS). 
I'm sorry for mistaking the whole thing as an issue of the framework.  I'm closing this issue now.
