### ISSUE TITLE
TreeGrid: setItemIconGenerator(IconGenerator<T>) has no effect

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#10503]
Hi,

it seems that the icon-generator is not called (besides from some readDesign stuff we are not using).

We implemented some workaround with fiddling with the caption to get the icon displayed before the text again. BTW: this workaround is also used in your sampler.

It would be nice if this would work again (IIRC, in Vaadin 7 that was the case).

Regards
Benjamin

**Comment by tsuoanttila** [comment]
I am not finding the referenced method in the TreeGrid. Which component this is related to?

**Comment by bjung82** [comment]
It's inherited from here:
com.vaadin.ui.AbstractListing.setItemIconGenerator(IconGenerator<T>)

**Comment by tsuoanttila** [comment]
The `AbstarctListing::setItemIconGenerator` is on purpose in `protected` scope and exposed to `public` only in components that actually support using it. There's no support for this feature in `TreeGrid` and thus it does not make the method to `public`.

**Comment by bjung82** [comment]
Ok, I inherited the TreeGrid for our applications and therefore can simply call this protected method.
It's no real issue for us (a "workaround" is in place).

But IIRC in Vaadin 7 there was a simpler way for adding an icon to the hierarchy column.
For better usability of the treegrid it would be nice to support this method here, too.

You can close this issue if yout want :-)

**Comment by tsuoanttila** [comment]
There's a related ticket #10611 that kind of links back to the issue in this ticket.

For the "simpler way for adding an icon to the hierarchy column" there's a couple things you can do, but what we might want to do in the FW is to expose the Tree renderer and make a way to use that with the TreeGrid as well. It's a bit of a special case, so would need some marker API for making the FW handle it automatically correctly..
