### ISSUE TITLE
Grid : Focus doesn't change on item selection when component renderer  is used

### ISSUE THREAD

**Issue by MatthieuCoelho** [vaadin/framework#10510]
If I have a Column with a custom component (e.g. layout) or a Resource , the grid focus doesn't change when item is selected.
Vaadin Framework version 8.2.0 and version8.3.0 alpha1

**Comment by MatthieuCoelho** [comment]
See #10412

**Comment by pinonpierre** [comment]
Correct, I have the same issue from my side.

**Comment by MatthieuCoelho** [comment]
Same issue in Vaadin version 8.3.0

**Comment by alethut** [comment]
I have the same issue in version 8.3.0
When i use .setHandleWidgetEvents(true) in the componentColumn i have a 

java.lang.NoSuchMethodError: com.vaadin.ui.Grid$Column.setHandleWidgetEvents(Z)Lcom/vaadin/ui/Grid$Column;

**Comment by anasmi** [comment]
@alethut , actually, your issue is different one, as you are getting the NoSuchMethodError.
What you did? Could you share the code example?

The code below woks just fine for me(still the original focus issue discussed in this thread is still there)
`Column col = grid.addComponentColumn(person -> {
			HorizontalLayout l = new HorizontalLayout();
			l.addComponent(new Label(person.getName()));
			return l;
		}).setCaption("Name");

		col.setHandleWidgetEvents(true);`

**Comment by TatuLund** [comment]
Check also this one
https://github.com/vaadin/framework/issues/10237

**Comment by TatuLund** [comment]
Duplicate: https://github.com/vaadin/framework/issues/9649

**Comment by TatuLund** [comment]
The focus works if you base your custom component in ComponentColumn on e.g. Panel, which is focusable. Non-focusable component will naturally repell the focus.
