### ISSUE TITLE
Component column in TreeGrid does not behave like Grid (components loose focus)

### ISSUE THREAD

**Issue by go4st** [vaadin/framework#10528]
The components in a component column within a TreeGrid loose focus to the row. This behaviour is does not occur at a normal Grid.

Example code: 

HorizontalLayout horizontalLayout = new HorizontalLayout();

TreeGrid<String> treeGrid = new TreeGrid<>();
treeGrid.setItems("test1", "test2");
treeGrid.addComponentColumn(item -> new TextField());

Grid<String> grid = new Grid();
grid.setItems("test1", "test2");
grid.addComponentColumn(item -> new TextField());

horizontalLayout.addComponents(treeGrid, grid);

**Comment by tsuoanttila** [comment]
I think that this is related to the fact that Components in treegrid are in the "HierarchyColumn" and not just a regular column. The hierarchy renderer does some extra with clicks and other events..

**Comment by go4st** [comment]
Ok but is this the desired behaviour, because this makes components in the component column not useable.

**Comment by tsuoanttila** [comment]
Most likely not, the comment I added there was a general note as to why it behaves differently. It was meant as a personal reminder that I know where to start looking once I get back to this ticket one day.

**Comment by go4st** [comment]
Ok thank you, it would be great if this could be fixed soon!
