### ISSUE TITLE
GridLayout keep spaces for empty rows

### ISSUE THREAD

**Issue by cornzy** [vaadin/framework#10537]
When making all compnents of a row in GridLayout invisible the layout still have som extra space for the empty row. This only occures with `setSpacing(true)`, the extra space is exactly the spacing for the empty row.

In [grid_layout_spacing.zip](https://github.com/vaadin/framework/files/1631687/grid_layout_spacing.zip) there is a little example to reproduce.

Reproduced with vaadin 7.7.11

**Comment by cornzy** [comment]
maybe this issue is related to #5230 but it has nothing to do with column span.

**Comment by Ansku** [comment]
`setHideEmptyRowsAndColumns(true)` does this as long as two conditions are fulfilled:
* the non-visible component is set to only cover one column in one row, not merged GridLayout cells
* there is no expand ratio set for the column and row in question

Expanding the hiding feature to cover those two use cases would be non-trivial and potentially performance-damaging, so we'll consider them separately if someone requests them. A new, more specific issue should be created for that purpose if the need should arise.
