### ISSUE TITLE
Conflict between RichTextArea and button with ClickShortcut

### ISSUE THREAD

**Issue by MichelePollini** [vaadin/framework#10536]
I think there are some conflicts between adding ClickShortcut on Button and RichTextArea.
If I write in richTextArea in presence of clickShortcut I have a client NullPointerException.
In my real application I have a clickShortcut in loginView and a RichTextArea in another view but the exception is present anyway.

I tried with Vaadin 8.2.0 and 8.2.1

```
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        final RichTextArea name = new RichTextArea();
        name.setCaption("Type your name here:");

        Button button = new Button("Click Me");
        button.setClickShortcut(ShortcutAction.KeyCode.ENTER);
        button.addClickListener(e -> {
            layout.addComponent(new Label("Thanks " + name.getValue() 
                    + ", it works!"));
        });
        
        layout.addComponents(name, button);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by MichelePollini** [comment]
Noone have same bug if you try with example code?

**Comment by mcollovati** [comment]
The problem seem to be that `VRichTextArea.client` is not initialized by `RichTextAreaConnector`; a similiar initialization is done, for example, in `NativeButtonConnector.init`.

I'll open a PR soon
