### ISSUE TITLE
When leaving view while editing in a grid, editor won't work anymore

### ISSUE THREAD

**Issue by sirbris** [vaadin/framework#10543]
Vaadin Framework version 8.2.1

When a grid is in edit mode and you change the view before cancelling/committing the value and go back afterwards to that view the editor in the grid won't open anymore.

Reproduce:
https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/item-editor
start editing a cell (don't close the editor)
click on "Grid" in the top left menu
click on "Item Editor" 
now try double click on a cell -> editor won't work

**Comment by pwilkin** [comment]
Is this perhaps an instance of #10146 ?

**Comment by sirbris** [comment]
seems related, yes! cannot say for sure, that's the same thing though

**Comment by pwilkin** [comment]
Actually, I checked it and the issue is more serious - `Grid` does not seem to take into account any visibility/attachment changes, so whenever the editor is open when the `Grid` is taken away from the view in any way, the editor is broken afterwards. I'll be doing a pull request for this.
