### ISSUE TITLE
grid column frozen column reorder issue with SelectionMode.MULTI

### ISSUE THREAD

**Issue by focbenz** [vaadin/framework#10546]
*Expected:*
Similar to issue #8265 we encountered an issue with reordering columns that are actually frozen columns. When using frozen columns in our grids we also think that reordering frozen columns should not be allowed. It looks like the first selector column is not excluded from the not-reorderable-range.

Grid with 2 columns FIRST and LAST and SelectionMode.MULTI

Steps to reproduce reordering frozen columns:
- Drag first frozen column and drop behind second
*Actual:*
--> The LAST column is now the frozen column but reordering should not be possible !

Hint: Reordering the frozen column is not possible if SelectionMode.NONE is used

[Update 2019-07-26]:
Issue can still be observed with latest Vaadin 8.8.5

*Sample project:*
https://github.com/FOCONIS/vaadingridfrozencolumnreorder

*Sample code:*
```
final VerticalLayout layout = new VerticalLayout();
layout.addComponent(new Label("Frozen columns can be reordered with unhidden columns with: " + 
		com.vaadin.shared.Version.getFullVersion()));
Label issueLabel = new Label("Demonstrate problem in <a href=\"https://github.com/vaadin/framework/issues/10546\">grid column frozen column reorder issue with SelectionMode.MULTI</a>");
issueLabel.setContentMode(ContentMode.HTML);
layout.addComponent(issueLabel);

// Create new Grid
Grid<HashMap<String, String>> grid = new Grid<>("My test grid to reorder columns");

// Fill the grid with data to sort
List<HashMap<String, String>> rows = new ArrayList<>();
String FIRST = "Frozen Column (Should not be reordered)";
String LAST = "Last Name Column";

// Grid for Vaadin 8 without bean class from https://vaadin.com/forum/#!/thread/16038356/16816582
for (int i = 0; i < 20; i++) {
	HashMap<String, String> fakeBean = new HashMap<>();
	fakeBean.put(FIRST, "first" + i);
	fakeBean.put(LAST, "last" + i);
	rows.add(fakeBean);
  }

grid.setItems(rows);

// Add the columns based on the first row
HashMap<String, String> s = rows.get(0);
for (Map.Entry<String, String> entry : s.entrySet()) {
	grid.addColumn(h -> h.get(entry.getKey())).setCaption(entry.getKey()).setId(entry.getKey());
}
grid.getColumn(LAST).setHidable(true);
grid.setSelectionMode(SelectionMode.MULTI);
// without the selector column the issue cannot be observed
// grid.setSelectionMode(SelectionMode.NONE);
grid.setFrozenColumnCount(1);
grid.setColumnReorderingAllowed(true);
grid.setSizeFull();

layout.addComponent(grid);
layout.setMargin(true);
layout.setSpacing(true);

setContent(layout);
```

**Comment by focbenz** [comment]
I did not verify this issue with the latest 8.4.3 release yet ... but this should be fixed if still reproducible.

**Comment by focbenz** [comment]
Could be easily verified with new sample project if required.

**Comment by focbenz** [comment]
Issue can still be observed with latest framework 8 Vaadin 8.8.5:

![image](https://user-images.githubusercontent.com/23717010/61953638-384da780-afb7-11e9-8132-f0b8357c7104.png)

Sample project to easily reproduce the issue available on GitHub:
https://github.com/FOCONIS/vaadingridfrozencolumnreorder

**Comment by TatuLund** [comment]
Yes, this is simple indexing issue since internal index of the column is +1 if there is selection column present.
