### ISSUE TITLE
Window setDelay

### ISSUE THREAD

**Issue by r2rK** [vaadin/framework#10552]
I would like to ask, about two vaadin components which could be use in a similar way, about "com.vaadin.ui.Notification" and "com.vaadin.ui.Window".

Both that components can be used to inform users, "Window" is more robust but I cannot find function/solution which has "Notification" like "Notification.setDelayMsec(int delayMsec)"

It would be very helpfull if "Window" also would have it. (From graphical point of view, it would look really nice and cool, if "Window" could show and disappear with time delay).
(Vaadin version 8.1.0)

**Comment by tsuoanttila** [comment]
One way to do this is to use `Push` and a background thread with the timer. Open the window, start timer to close it, remember to use `UI.access()` to make sure the client will get the message.

```
@Push
public class MyExampleUI extends UI {
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        setContent(new Label("Example content"));
        Window window = new Window("Closing in 5 seconds");
        window.setContent(new Label("Window content"));
        addWindow(window);
        new Thread(() -> {
            try { Thread.sleep(5000); } catch (InterruptedException e) {}
            access(() -> window.close());
        }).start();
    }
}
```
