### ISSUE TITLE
@PushStateNavigation causes my rest API redirecting to the login screen.

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/framework#10578]
When using @PushStateNavigation all non Vaadin Pages are redirecting to the login page. Is there a way to tell @PushStateNavigation to ignore these urls. If not it would be great to add this.

Thanks in advance

**Comment by TatuLund** [comment]
Push state navigation assumes that all url in the root context belong to it. So you should configure the rest end point to different root url than your ui.

**Comment by TheSilentHorizon** [comment]
@TatuLund Thats a good information but this makes my issue even more complicated.

/ is the Root for my Vaadin UI.

/api/ is the Root for my RESTful Services.  

And changing the root for my Vaadin UI is not really what I want. Any solution for this?

**Comment by tsuoanttila** [comment]
Moved to correct repository. This is specific to the Vaadin Spring plug-in implementation. Might be that we will solve it in a more generic way in the framework but the driving use-case comes from Spring.
