### ISSUE TITLE
Notification close events are sent even though there are no listeners attached

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#10570]
- Vaadin Framework version (e.g. 8.2.1)

Notification close events are sent even though there are no listeners attached. This causes obsolete "chattines" and even large obsolete requests.

**Comment by Artur-** [comment]
The framework is always listening so it can remove the notification from the hierarchy

**Comment by mstahv** [comment]
I think that could be at least lazy if it there are no listeners.
