### ISSUE TITLE
Communication error message not showing with push enabled

### ISSUE THREAD

**Issue by f92dev** [vaadin/framework#10583]
I noticied that after 3 heartbeats missed the communication error notification is not appearing if push is enabled in my application.
This is a bit confusing for the users because the page gets disabled and all components grayed out. The only thing they can do is to reload the page.

(i'm using Vaadin 8.2.1)

This is how to reproduce the problem:

Servlet config:
```
@WebServlet(urlPatterns = "/*")
@VaadinServletConfiguration(ui = MyUI.class, productionMode = false, heartbeatInterval = 5)
public class MyServlet extends VaadinCDIServlet {
// code
}
```
UI config:
```
@CDIUI("test")
@Push(transport = Transport.WEBSOCKET_XHR, value = PushMode.AUTOMATIC)
public class TestUI extends UI {
// code
}
```

In the screenshow below you can see the client debug log
![error](https://user-images.githubusercontent.com/17615321/35615637-05ba90ba-0673-11e8-9c0f-395c28ba43b9.png)

**Comment by sirbris** [comment]
Is there a workaround?

**Comment by sirbris** [comment]
see also https://github.com/vaadin/framework/issues/5836

**Comment by TatuLund** [comment]
> @WebServlet(urlPatterns = "/*")

One cause of problems may be missing async supported, see

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/MyVaadinUI.java#L162

I have not noticed this issue in newer Vaadin versions. So it is either the above, or some later fix in Push that has fixed the problem.
