### ISSUE TITLE
One constructor of Button fails to register RPC

### ISSUE THREAD

**Issue by markathomas** [vaadin/framework#10599]
- Vaadin Framework version:
at least 8.2.1+

- Description of the bug:
Constructor of button:
`public Button(Resource icon, ClickListener listener) {
        setIcon(icon);
        addClickListener(listener);
    }`
fails to call `this()` resulting in no registration of ServerRpc

**Comment by knoobie** [comment]
See #10566

**Comment by Legioth** [comment]
Duplicate of https://github.com/vaadin/framework/issues/10540
