### ISSUE TITLE
Notification cannot be shown a second time

### ISSUE THREAD

**Issue by wbadam** [vaadin/framework#10598]
After the change in #10483, it is not possible to show the same notification for a second time.
```Java
sample = new Notification("Notification message", "Notification description");
showButton = new Button("Show notification", event -> sample.show(Page.getCurrent()));
```
When button clicked for the second time, an exception is thrown.
```
java.lang.IllegalStateException: An extension can not be set to extend a new target after getting detached from the previous.
```

`close()` removes the extension and cannot be reattached again.

Can be tested in the [sampler](https://demo.vaadin.com/sampler/?debug#ui/interaction/notification) by clicking the button, dismissing the notification and clicking the button again.

**Comment by kaaljabr** [comment]
I also have this issue when I updated to the latest Vaadin version

**Comment by wbadam** [comment]
@kaaljabr a workaround is to create a `Notification` object each time you show a notification, something similar to the following:
```Java
new Button("Show notification", event -> new Notification("Notification message", "Notification description").show(Page.getCurrent()));
```

**Comment by kaaljabr** [comment]
Yes I figured it out. I prefer using the same Notification object instead of creating it every time. Do you know which version this issue was introduced? I moved from 8.1.0 to 8.3.1. I know on 8.1.0 it was fine.

**Comment by tsuoanttila** [comment]
#10027 in `8.2.0.alpha2`

**Comment by TatuLund** [comment]
Cannot reproduce with 8.9.3
