### ISSUE TITLE
Because Button swallows click-event, click listener on layout parent of the button is not called

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#10594]
See VButton:110

sinkEvents(Event.ONCLICK | Event.MOUSEEVENTS | Event.FOCUSEVENTS | Event.KEYEVENTS); 

It seems like a bug, because for other components , e.g. Image/VImage
this is working (no call to sinkEvents() for other components.

**Comment by scardanzan** [comment]
It's not a bug, if you look at the JavaDoc for the addLayoutClickListener method, you will see that it mentions that it's up to the targeted component to propagate the event. Button doesn't propagate the event on purpose. Was there a problem you were trying to solve that needed that propagation? You could always call the method executed on the layoutClickListener from the button clickListener.
