### ISSUE TITLE
Bug: DateField.setDateFormat(...) does not format year's week numbers

### ISSUE THREAD

**Issue by OddDev** [vaadin/framework#10603]
**Vaadin Framework version**
7.7.13

**Description of the bug**
When setting a SimpleDateFormat with "w"s to show the year's week number, the DateField ignores these parameters and doesn't format them.
Extended description to be found here: https://stackoverflow.com/q/48622176/2641361 

**Minimal reproducible example**
```
public class CalendarWeekField extends DateField {

public CalendarWeekField() {
    super();
    this.setLocale(UI.getCurrent().getLocale());
    this.setDateFormat("ww yyyy");
    this.setShowISOWeekNumbers(true);
}
```

Creating and instance of this class results in a Datefield displaying the selected date's year but not the week numbers (like e.g. " 2018"). 

![gif displaying the bug](https://i.stack.imgur.com/WOx9i.gif "Choosing a date results in the white-space and year only")

**Comment by OddDev** [comment]
Bug is also reproducible in the sampler. https://demo.vaadin.com/sampler/#ui/data-input/dates/popup-date-field

**Comment by mathisdt** [comment]
This is still a bug in the latest Vaadin 8 release. Also see sampler as linked above.

**Comment by mathisdt** [comment]
@TatuLund, thanks for following up! Yes, the issue still persists when using "ww YYYY" - it even gets worse because when using the format string "ww YYYY" *nothing* ist formatted except the space.

**Comment by mathisdt** [comment]
The issue is also still present in Vaadin 8.6.3.

format string | formatted value when selecting January 14th, 2019
---------------- | ---------------------------------------------------------------
"ww yyyy" | " 2019"
"ww YYYY" | " "

**Comment by invenius** [comment]
This still does not work as expected in Vaadin 8.9.1. Neither "w" nor "Y" is recognized as format string.

**Comment by mlopezFC** [comment]
For what I was able to see, this depends on [this feature request](https://github.com/gwtproject/gwt/issues/4010) that is still not implemented in GWT.
