### ISSUE TITLE
How to reset text input?

### ISSUE THREAD

**Issue by jouni** [vaadin/framework#10608]
_From @ropoman on February 6, 2018 9:46_

I am using ComboBox with .setTextInputAllowed(true). When I type characters into the combo box it filters the values. 
I have three options to close the combo box:
1. select one of the filtered values
2. click somewhere else in the form to close the combo box
3. close the form
In case 3 I have the problem that the combo box is still filtered when I open the form again. Tried with Firefox, Chrome and Edge

_Copied from original issue: vaadin/vaadin-combo-box#612_

**Comment by ropoman** [comment]
I was using vaadin 8.3.0

**Comment by ropoman** [comment]
I tried to implement a workaround by setting private currentFilterText, but currentFilterText is always ""

**Comment by TatuLund** [comment]
Have you checked 8.3.1, which has this fix: https://github.com/vaadin/framework/issues/10284 ? There will be further improvement in 8.4.0 via https://github.com/vaadin/framework/pull/10606
