### ISSUE TITLE
Missing HTML-Tooltip for TreeItem

### ISSUE THREAD

**Issue by philmu** [vaadin/framework#10615]
Vaadin 8.3.0

Actually you can use
`public void setItemDescriptionGenerator(DescriptionGenerator<T> descriptionGenerator)` in com.vaadin.ui.Tree to generate an preformatted tooltip.

For HTML-Tooltip we need a second operation in com.vaadin.ui.Tree:
`public void setItemDescriptionGenerator(DescriptionGenerator<T> descriptionGenerator, ContentMode contentMode)` which calls the existing operation `treeGrid.setDescriptionGenerator(descriptionGenerator, contentMode);`

**Comment by AkiValiaho** [comment]
I've fixed this issue on the following pull request:

https://github.com/vaadin/framework/pull/10677

**Comment by elmot** [comment]
Fixed in 8.4.0.alpha1 with 0af3b7d
