### ISSUE TITLE
Pageable Grid

### ISSUE THREAD

**Issue by henrik-dvlpr** [vaadin/framework#10623]
I want to use the grid with paging. I want to display 20 items per page and go forward or backward with buttons. 

Its not simple to develop a good custom solution to handle it. It would be great if the framework have a solution on board.

Currently only scrolling is available. 

Greetings!

**Comment by TatuLund** [comment]
There is Paged data provider in this add-on

https://vaadin.com/directory/component/gridextensionpack-add-on

**Comment by henrizzle** [comment]
Thanks, I will check it out soon!
