### ISSUE TITLE
Grid -> DataProvider -> DataProviderListenerdoes not receives DataChangedEvents

### ISSUE THREAD

**Issue by mrbu** [vaadin/framework#10625]
DataProviderListener should be invoked after each refreshAll of the DataProvider.
But it isn't never invoked. 

```
Grid<RowDto> rowDtoGrid = new Grid<>();
rowDtoGrid.getDataProvider().addDataProviderListener(event -> {
          //do Something <- never invoked
 });
rowDtoGrid.getDataProvider().refreshAll();
```
Vaadin Framework version: 8.3.1

**Comment by tsuoanttila** [comment]
The given code example does not compile, there's no method `addDataProviderListener` in `Grid`. Tested the functionality of the `DataProvider` listeners with the following code and my test passed:
```
    @Test
    public void testDataProviderListener() {
        Grid<String> grid = new Grid<>();
        AtomicInteger callCount = new AtomicInteger(0);
        grid.getDataProvider().addDataProviderListener(e -> {
            callCount.getAndIncrement();
        });
        assertEquals(0, callCount.get());
        grid.getDataProvider().refreshAll();
        assertEquals(1, callCount.get());
    }
```

**Comment by mrbu** [comment]
I'm sorry for wrong code.

```
@Test
    public void testDataProviderListener() {
        Grid<String> grid = new Grid<>();
        grid.addComponentColumn(o -> new Button());
        AtomicInteger callCount = new AtomicInteger(0);
        grid.getDataProvider().addDataProviderListener(e -> {
            callCount.getAndIncrement();
        });
        grid.setItems(new ArrayList<>());
        assertEquals(0, callCount.get());
        grid.getDataProvider().refreshAll();
        assertEquals(1, callCount.get());
    }
```

There is a test which fails. It depends with the invoke of setItems.

**Comment by mrbu** [comment]
Okay. I'm now not sure, if it is realy a bug. 
setItems creates a new instance of ListDataProvider, that's why there is no listener anymore.

**Comment by tsuoanttila** [comment]
Calling `setItems` creates a new `DataProvider` instance that contains your data. The new instance won't have your listener and it will not be called. 

If you want to have it you should use `DataProvider myData = DataProvider.ofCollection(myList)`, tell `Grid` to use that `grid.setDataProvider(myData)`, make changes to `myList` and then call `myData.refreshAll()`.

**Comment by mrbu** [comment]
Alright. I missed the side effect of `setItems`.
Thank you.
