### ISSUE TITLE
Window adds position absolute to content and doesn't remove it at any point

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/framework#10645]
- Vaadin Framework version (e.g. 8.3.1)
- Chrome

- Description of the bug
Styles for Window content are changed and never reverted
- Minimal reproducible example
```
        final VerticalLayout layout = new VerticalLayout();
        layout.setSizeFull();
        layout.setMargin(false);
        layout.setSpacing(false);

        final Label label = new Label("text");
        label.setSizeFull();
        label.setId("label");
        Button button = new Button("Open in a window", new ClickListener() {
            @Override
            public void buttonClick(ClickEvent event) {
                final Window window = new Window("Label Window");
                window.setContent(label);
                window.setWidth("50%");
                window.setHeight("50%");
                getUI().addWindow(window);
                window.addCloseListener(new CloseListener() {
                    @Override
                    public void windowClose(CloseEvent e) {
                        layout.addComponent(label);
                    }
                });
            }
        });
        layout.addComponents(button, label);
        setContent(layout);
```

- Expected behavior
Result for `document.querySelector('#label').style.position` should be the same before opening the window and after closing it

- Actual behavior
Label position is changed to absolute after being the content of the window.
In the case of a Label it's not noticeable, but in other components, like Charts, changing to position absolute will result in wrong size of the component in the layout.
Note, this doesn't seem to happen in the label doesn't have full size.

**Comment by scardanzan** [comment]
It's probably not the best idea to reuse instances of components on Windows, but in order to avoid the position change you can wrap the label in a layout, only the component set as the content gets its position altered.
