### ISSUE TITLE
Documentation bug: dead links

### ISSUE THREAD

**Issue by gaurav-nelson** [vaadin/framework#10657]
Hello,

I am the autor of [asciidoc-link-check](https://github.com/gaurav-nelson/asciidoc-link-check), a tool to check if the hyperlinks used in an asciidoc file are live (or dead).

I ran it on your docs repository and found following dead links:

```
FILE: ./addons-downloading.asciidoc
[✖] http://vaadin.com/download/

FILE: ./advanced/advanced-dragndrop.asciidoc
[✖] https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite

FILE: ./articles/CreatingSecureVaadinApplicationsUsingJEE6.asciidoc
[✖] http://www.netbeans.org
[✖] http://www.w3.org/1999/xhtml

FILE: ./articles/GettingStartedOnNetBeans.asciidoc
[✖] http://www.netbeans.org

FILE: ./clientsideapp/clientsideapp-entrypoint.asciidoc
[✖] http://google-web-toolkit.googlecode.com/svn/tags/1.7.0/distro-source/core/src/gwt-module.dtd

```
 
I think most of these issues could be caught prior to publishing content in the repository. We use a post-commit hook to check for all dead hyperlinks. Maybe this could be added to your project's CONTRIBUTING guide.

To use the post-commit hook, authors can create a `post-commit.sh` file, inside the `.git` folder of the docs repository.

```bash
#!/bin/bash 
echo -e "\e[32mPOST COMMIT HYPERLINKS CHECK\e[0m" 
COMMIT_HASH="$(git rev-parse @~)" #get the previous commit hash 

#run the loop for every modified or added file
for i in $(git diff --name-only "${COMMIT_HASH}") ; do

    fileList[$N]="$i"
    echo "$(asciidoc-link-check $i -p)" #check all hyperlinks in this file
    echo $'\n'
    let "N= $N + 1" 
done 
echo -e "\e[32mDONE!\e[0m"
```
Now after every commit, this script checks hyperlinks in all modified or newly added files.

**Comment by Legioth** [comment]
I would prefer to see this kind of check integrated into the Maven workflow and through that checked by validation builds instead of being each contributor's own responsibility.
