### ISSUE TITLE
Pressing space bar in Grid header rows selects the xth grid row

### ISSUE THREAD

**Issue by focbenz** [vaadin/framework#10650]
We are using e.g. text filters in additional header rows of the Grid. In case the space bar is pressed while entering text in one of the TextFields in the e.g. second header row the second row in the grid is selected.

*Expected:*
While entering text and also pressing space bar in a header row only that elements gets the input

*Actual:*
The second grid row gets selected when text containing spaces is entered in a TextField in the second header row

![vaadin_spacebar_selects_2nd_grid_row](https://user-images.githubusercontent.com/23717010/36549941-4d433a1c-17f4-11e8-90d5-c02c4ee95bb1.jpg)

*Affected Vaadin version: 8.3.1*
8.3.1 is affected
8.2.1 is not affected

*sample demonstrating the problem:*
[gridheaderrows.zip](https://github.com/vaadin/framework/files/1748637/gridheaderrows.zip)

**Comment by fleahy** [comment]
I think there's a general issue with the space bar and the Grid in versions >= 8.3.0. I see similar behaviour but in the grid editor instead, it does not accept a space bar input. Exactly the same code but using Vaadin version 8.2 works fine, I can type in space in the data in the editor.

**Comment by TatuLund** [comment]
I think this is regression from same patch as this one: https://github.com/vaadin/framework/issues/10597

**Comment by m-bermel** [comment]
Any eta on this fix as it didn't make it into the 8.3.2 maintenance release?
