### ISSUE TITLE
How to implement Tab-Design with Vaadin Navigator

### ISSUE THREAD

**Issue by henrizzle** [vaadin/framework#10661]
Hello,

I want to create a UI with the Tab-Design. The key feature is that one view can be opened multiple times. 

The UI view container is a tab sheet and contains all **opened** views. The tab sheet is used only for switching between opened views. A navigation bar is used to open a new view as tab. I want also use this with Spring Boot!

See example:
![tab-design-example](https://user-images.githubusercontent.com/5278350/36675117-667df3ac-1b08-11e8-8a2a-0c79de5ba6d6.png)

How can I implement this with vaadin without implementing an custom solution (routing etc.)?

**Comment by christopherbryanboyd** [comment]
I actually wrote an implementation of this awhile ago in Vaadin 7, if I get a chance I will upload a Vaadin 8 version to github and link it here.

I basically extended TabSheet, with a custom ViewDisplay and Navigator, and when a user would try to navigate to a URL (or click the menu button corresponding to a particular View / Tab), the TabSheet would either switch to that particular Tab if it was available, or create one.

**Comment by wodencafe** [comment]
I actually wrote an implementation of this awhile ago in Vaadin 7, if I get a chance I will upload a Vaadin 8 version to github and link it here.

I basically extended TabSheet, with a custom ViewDisplay and Navigator, and when a user would try to navigate to a URL (or click the menu button corresponding to a particular View / Tab), the TabSheet would either switch to that particular Tab if it was available, or create one.

**Comment by anasmi** [comment]
Hi, 
actually you will get more answers/support on forum , since it's not an issue : )
https://vaadin.com/forum

**Comment by henrizzle** [comment]
Hello, thanks for the replies! I have created a topic in the [forum](https://vaadin.com/forum/#!/category/10391260) now.

**Comment by henrizzle** [comment]
If anyone has the same problem, look at the new Vaadin 10. With it you can build a Tab-Designed application. 

Worked for me: Use `@SpringComponene` and `@RequestScope` instead of `@Route()` and build a navigation `RootLayout` that has a `Tabs` components with your open pages ([see documentation](https://vaadin.com/components/vaadin-tabs/java-examples) and scroll down to Tabs with pages).
