### ISSUE TITLE
[PopupView] Incorrect display of GridLayout

### ISSUE THREAD

**Issue by glebfox** [vaadin/framework#10668]
# Description

If we use GridLayout as a PopupView content, then it has the wrong size and all nested components overflow each other.

# Minimal reproducible example
```
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupView;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import javax.servlet.annotation.WebServlet;

@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        VerticalLayout layout = new VerticalLayout();
        layout.setSizeFull();
        layout.setMargin(true);

        // Content for the PopupView
        // Create a 4 by 4 grid layout
        GridLayout grid = new GridLayout(2, 2);
        grid.setSpacing(true);

        grid.addComponent(new Label("Label 1"));
        TextField textField = new TextField();
        textField.setWidth("250px");
        grid.addComponent(textField);

        grid.addComponent(new Label("Label 2"));
        textField = new TextField();
        textField.setWidth("250px");
        grid.addComponent(textField);

        // The component itself
        PopupView popup = new PopupView("Open the popup", grid);
        popup.setHideOnMouseOut(false);
        layout.addComponent(popup);

        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

# Expected behavior
GridLayout is displayed correctly  as if it isn't placed within **PopupView**:

![image](https://user-images.githubusercontent.com/6077149/36786757-fac69f98-1ca0-11e8-9c5b-0448da819eef.png)

# Actual behavior
GridLayout is displayed incorrectly:

![image](https://user-images.githubusercontent.com/6077149/36786587-5c5615c8-1ca0-11e8-9793-c0115779b533.png)

# Other Information
**Vaadin Framework version**: `7.7.13` and `8.3.1`
**Browser version**: Google Chrome 64.0.3282.186

**Comment by mikke-alekstra** [comment]
Hello!

I faced this same problem today.

```
        GridLayout gl = new GridLayout(10, 10);
        gl.setSpacing(true);
        
        for (int i = 0; i < 10; i ++) {
            for (int j = 0; j < 10; j ++) {
                gl.addComponent(new Label(String.valueOf(i * 10 + j)), j, i);
            }
        }
        
        PopupView pv1 = new PopupView(null, gl);
        
        Button b1 = new Button("CLICK 1");
        b1.addClickListener(click -> {
            pv1.setPopupVisible(true);
        });
        
        PopupView pv2 = new PopupView("CLICK 2", gl);
```
Popup for initially minimized pv1 is always incorrect. Popup for pv2 changes randomly being most of the times incorrect.

Vaadin 8.12.3
Liferay 7.3.5
OpenJDK 11

Please inform if you have any news about this issue. Thanks!

**Comment by Ansku** [comment]
I don't have a suitable Liferay instance at hand to test that particular combination right now, but https://github.com/vaadin/framework/pull/12138 should fix the issue. The fix is already available in 8.13-SNAPSHOT

**Comment by mikke-alekstra** [comment]
Thanks for a quick reply!

I was able to reproduce the case with the 8.12-3 & Jetty web server. Switched to 8.13-SNAPSHOT and yes, GridLayout appeared correctly. Also Liferay with 8.13-SNAPSHOT worked well.

**Comment by Ansku** [comment]
Great to hear, thank you for testing! I'll mark this issue resolved. It's a too big change to include in the 8.12 branch and it will take some time before we get 8.13.0 out (the first alpha is in the pipeline), but we are working on it :)
