### ISSUE TITLE
Incorrect treatment of encoded '/' character (%2F) in the URL

### ISSUE THREAD

**Issue by armansahakyan** [vaadin/framework#10671]
* Vaadin Framework version: 8.3.1
* Browsers: Chrome, Firefox, Edge, etc
* Description of the bug (with a small debugging help):
After enabling slash '/' encoding for Tomcat, it is not possible to encode them (%2F) in urls, as Vaadin mistakenly ignores the encoding and treats them as normal / characters in VaadinServletService.getStaticFileLocation which in turn is used by BootstrapHandler.setupMainDiv which therefore infers the wrong bootstrap javascript file location (inserts an extra ../ to the bootstrap file location). 
This prompts the "Failed to load the bootstrap javascript ...." browser message.

* How to reproduce
Any minimal vaadin application. An example URL will look like so:
myvaadin:8080/urlbug/c=%2F

* Expected behavior
%2F in the urls should be treated as such and must not affect how Vaadin defines the bootstrap javascript file path.

**Comment by TatuLund** [comment]
This decoding of of encoded characters and normalizing of the paths are necessary for filtering out possible malicious paths, e.g. path traversal vulnerabilities. This is normally done already at container level.
