### ISSUE TITLE
Grid column automatic widths doesn't match browsers' overflow calculation

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/framework#10689]
Vaadin Framework 8.3.0
Chrome 63 / Firefox 58

I suspect that the way Grid calculates column widths based on contents doesn't take into account how browsers round element dimensions to solid pixels when rendering them, and how this affects whether the column's contents overflow the column width or not, leading to columns that are 1px too narrow to fit their contents, and thereby unncessary text overflows (with ellipsis).

1. Grid calculates the width of a column's content, with subpixel-accuracy, e.g. 50.25px.
2. Browser rounds this to 50.00px when rendering the TD.
3. Text is still 50.25px, thus overflows the TD.

**Comment by Artur-** [comment]
#8502 ?

**Comment by rolfsmeds** [comment]
I thought it might be that, yes, but if so, I would expect the following:
* Bigger discrepancy with really wide fonts (e.g. Courier)
* Columns too wide instead of too narrow with a really narrow font (e.g. Arial Narrow)
* Problem goes away if you set the font to sans-serif.

I've tested all three scenarios, and none of those come true.

Instead, the columns are always some fraction of a pixel too narrow, regardless of font.

If I override the cell width with the same value rounded up to the nearest full pixel, the content fits.

**Comment by Artur-** [comment]
Do you happen to have an example project publicly available?

**Comment by rolfsmeds** [comment]
Nope, but I can give you a demo if you come visit me :)
