### ISSUE TITLE
Grid: unbuffered editor enabling and then disabling keeps doubleclickbehaviour

### ISSUE THREAD

**Issue by dangerground** [vaadin/framework#10688]
- Vaadin Framework version: 8.3.1
- Browser version: Version 64.0.3282.140 (Official Build) (64-bit)

### Description of the bug
By using an extra button to disable/enable the grid editor (for read/update modes) I call the Grid::getEditor().setEnabled method and observed a different behaviour from default to inbetween enabled editors.

### Expected behavior
Doubleclicking a row on an enabled -> disabled -> enabled editor should not throw an exception

### Actual behavior
server-side EditorImpl::doEdit is called and throws IllegalStateException("Editing is not allowed when Editor is disabled.")

**Comment by nhp3007** [comment]
I'm also experiencing this issue when using GridFastNavigation add-on (which has the setting to open editor with single-click enabled by default). Just wanted to add that the issue is not only with the double-click behavior but single-click as well.

**Comment by TatuLund** [comment]
@tsuoanttila I tend to agree, I checked this https://github.com/vaadin/framework/issues/10413 yesterday with 8.4.4. and I think the sequence is the same.

**Comment by nhp3007** [comment]
We were on Vaadin Framework version 8.4.3. I upgraded the version to 8.4.4 and tried it out. I am still getting the error. Let me try creating a simple UI code to see if I can recreate it there.

**Comment by tsuoanttila** [comment]
@nhp3007 any luck reproducing the issue? I tried it a few times more myself and still can't reproduce it no matter what I try to do.

**Comment by mehdi-vaadin** [comment]
The exception occurs when we try to disable `Grid` editor when it is in the editing state (any state except `INACTIVE`). And the problem is canceling editor programmatically doesn't work when editing is disabled. So, it makes sense to call cancel editing automatically when it's going to be disabled.

**Comment by mehdi-vaadin** [comment]
By the way, a temporary workaround solution is to use Server Push, for example:
```
if (grid.getEditor().isOpen()) {
    grid.getEditor().cancel();
    getUI().push();
}
grid.getEditor().setEnabled(false);

```
Of course, Server Push is needed to be activated by `Push` annotation.
