### ISSUE TITLE
Memmory leak caused by StreamVarible 

### ISSUE THREAD

**Issue by doggy-dev** [vaadin/framework#10695]
The StreamVaiable gets removed from pidToNameToStreamVariable in
https://github.com/vaadin/framework/blob/ead24c18282f793231c4ef5015851731693153a8/server/src/main/java/com/vaadin/ui/ConnectorTracker.java#L863
but it is still present in streamVariableToSeckey. This prevents the garbage collector from disposing it.

When I upload a lot of big files without changing the page this can cause an OutOfMemmoryError.
I'm using Vaadin 7.7.13

**Comment by bjung82** [comment]
Vaadin 8.2.0 seems to bee affected to  - not verified, I only inspected the code!

**Comment by tsuoanttila** [comment]
Picked fix to 8.4.5

**Comment by doggy-dev** [comment]
As this issue has been merged, maybe it should be tagged and closed?

**Comment by elmot** [comment]
@doggy-dev , thanks
