### ISSUE TITLE
TreeGrid row stripes are applied wrong after collapsing parent row

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/framework#10694]
Vaadin Framework 8.3.1

When a row with child rows is expanded in a TreeGrid, the v-row-stripe stylenames for the rows below the expanded one are updated accordingly. This is correct.

But when the row is collapsed, the v-row-stripe stylenames are not adjusted back, leading to multiple striped or non-striped rows in sequence (if the collapsed row had an odd number of child rows).

**Comment by elmot** [comment]
Can you provide a reproducible example?

**Comment by rolfsmeds** [comment]
Unfortunately no; I don't have the project in question set up any more. I think my description describes it quite well :) Lazy loading may have been involved, though, in case that helps.
