### ISSUE TITLE
Grid columns reordering does not behave correctly when grid is empty

### ISSUE THREAD

**Issue by margus80** [vaadin/framework#10699]
- Vaadin Framework version 8.3.1, not in 8.3.0
- Browser version FF 58.0.2, IE 11.0

- Description of the bug
Grid columns reordering does not behave correctly when no initial data in the grid. After drag and drop a column the column header will stay visible near the cursor. Clicking in somewhere else does custom reordering on every click. Reordering and even all other functionality sometimes stop working after multiple reordering tries. Also F5 button does not function on that. In a while of clicking somewhere or pressing Esc will stop the problematic behavior.

![image](https://user-images.githubusercontent.com/37216313/37211574-0baf8e80-23b5-11e8-8f7c-5455c04b1264.png)

- Minimal reproducible example
```
Grid<Person> grid = new Grid<>();
grid.setColumnReorderingAllowed(true);

List<Person> data = new ArrayList<>();
DataProvider<Person, ?> dataProvider = DataProvider.ofCollection(data);
grid.setDataProvider(dataProvider);

grid.addColumn(Person::getFirstName).setId("firstName").setCaption("First name");
grid.addColumn(Person::getLastName).setId("lastName").setCaption("Last name");
grid.addColumn(Person::getAge).setId("age").setCaption("Age");
grid.addColumn(Person::getAddress).setId("address").setCaption("Address");
grid.addColumn(Person::getEmail).setId("email").setCaption("E-mail");
grid.setColumnOrder("firstName", "lastName", "age", "address", "email");

HorizontalLayout gridLayout = new HorizontalLayout();
gridLayout.addComponent(grid);

setContent(gridLayout);
```

```
public class Person {
	private String firstName;
	private String lastName;
	private String age;
	private String address;
	private String email;

	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
}
```

- Expected behavior
After drag and drop additional grid column header must not be visible anymore near the cursor and all functionality must work normally.

- Actual behavior
After drag and drop additional grid column header will stay visible near cursor and clicking in somewhere does custom reordering on every click.

**Comment by drewoko** [comment]
Any update?
