### ISSUE TITLE
Binder needs to support enable/disable rather than just complete removal

### ISSUE THREAD

**Issue by bsutton** [vaadin/framework#10709]
Vaadin 8 Binder now supports the concept of removing a binding.

> binder.removeBinding(this.usernameField);

This is great but painful.

If you are buiding a UI which allows a user to show/hide some fields then you need to be able to dynamically add/remove bindings.

Whilst remove does removing the binding, adding the binding back in requires you to re-stipulate the full bind statement.

If we had enable /disable I could just go
> bind.disable(this.usernameField);

and then

> bind.enable(this.usernameField);

rather than:

> binder.removeBinding(this.usernameField);

and then

> binder.forField(this.usernameField)
>	.bind(AccountRequest::getUsername, AccountRequest::setUsername);

**Comment by tsuoanttila** [comment]
If the field itself is in not in the UI, the Binder will update it's value when you change a bean but since the user has no way to modify that value, the value will not change (unless you do it in the application code).

So for example: 
```
TextField name = new TextField();
Binder<Person> binder = new Binder<>();
binder.bind(name, Person::getName, Person::setName);
binder.setBean(new Person("Teemu")); // This will set name TextField to have value "Teemu"

layout.removeComponent(name);
```

Above example will have a TextField that is bound in the Binder, but since the control is not available in the UI the user will not be able to change the value. Selecting which controls you give to the user does not require you to remove anything from the Binder itself.

**Comment by bsutton** [comment]
Teamu,
thanks for the reponse, however its not going to achieve the desired outcome.

The first problem is that you have replaced one complexity with another.
Adding/removing components is problematic as it requires you to track the location of the insertion point for the component when you want to re-add it to the UI. In complex UIs this is not always simple.

The second issue is that its not about the user changing the value, its about not forcing the field to have valid content.

A simple scenario might be a combo box that controls whether a users is sent email notifications.
If the combo is selected then the user MUST enter an email address into a textfield.
So the email text field has an email validator and is required.
If the check box is not selected then we don't care what the email text field contains and it may indeed be blank.

Adding/removing the component won't achieve this. I need to be able to enable/disable the binding based on the combo box selection.

Brett

**Comment by tsuoanttila** [comment]
Starting in 8.4, we have a new feature for `Binding` called `setReadOnly(boolean readOnly)`. Setting this to `true` will mark the field it's bound to to be read-only as well and will not write the value from this binding to the bean. This should help with some parts of this issue that you have. It  is still up to debate whether a read-only binding should if complain the bean contained illegal values or not.. (read from bean, value not modified, but value not passing validator)

One option to remove the things from the layout is to set `component.setVisible(false)` which will hide it from the UI, keeping it still in its normal place and you can tell your validator to not check the value if the field is hidden and binding is read only, but that once again is just moving the complexity to another place.

**Comment by tsuoanttila** [comment]
In a similar way, we could whip up a `Bindining::setEnabled` with boolean parameter and completely filter out those bindings for every purpose.

**Comment by bsutton** [comment]
The set enable does feel like a very simple implementation and elegantly
solves the issue.

On 15 Mar. 2018 1:14 am, "Teemu Suo-Anttila" <notifications@github.com>
wrote:

In a similar way, we could whip up a Bindining::setEnabled with boolean
parameter and completely filter out those bindings for every purpose.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vaadin/framework/issues/10709#issuecomment-373035502>,
or mute the thread

**Comment by bsutton** [comment]
I did find a work around for this problem which I thought I would put here for the record.

Create a new 'conditional required' validator.

```
package au.org.noojee.orionmonitor.fields;

import java.util.function.Function;

import com.vaadin.data.ValidationResult;
import com.vaadin.data.Validator;
import com.vaadin.data.ValueContext;

public class ConditionalRequired <T> implements Validator<T>
{
	private static final long serialVersionUID = 1L;
	private Function<T, Boolean> f;
	private String error;
	public ConditionalRequired(String error, Function<T, Boolean> f)
	{
		this.f = f;
		this.error = error;
	}

	@Override
	public ValidationResult apply(T value, ValueContext context)
	{
		
		if (f.apply(value) == true)
		{
			return ValidationResult.ok();
		}
		else
			return ValidationResult.error(error);
	}
}
```

To use the validator:

````
binder.forField(this.accountField)
    .withValidator(new ConditionalRequired<>("Select the Account."
        , account -> account != null || this.actionField.getValue() == Action.NEW_ACCOUNT))
    .bind(AccountRequest::getAccount, AccountRequest::setAccount);

````

In this example the accountField field is not required if the the actionField is NEW_ACCOUNT otherwise its a required field.

Essentially if the conditional clause returns 'false' then the error will be displayed.
