### ISSUE TITLE
DesignAttributeHandler inconsistency between reading and writing attributes with no value

### ISSUE THREAD

**Issue by oluwasayo** [vaadin/framework#10703]
- Vaadin Framework version: starting from 8.3.0.alpha1

When reading a design, attributes with no value are [not permitted by DesignAttributeHandler](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/declarative/DesignAttributeHandler.java#L108-L111). However, writing out boolean attributes writes them without values.

**Comment by TatuLund** [comment]
Actually fixed by https://github.com/vaadin/charts/commit/239ec6dc115fb2c3676ad10a801f197d69f66d64 but left accidentally open.
