### ISSUE TITLE
Binder needs to support lambda nested properties

### ISSUE THREAD

**Issue by bsutton** [vaadin/framework#10708]
The binder doesn't do a great job with nested properties.

You can now bind using a string such as:

bind("parent.child")

but this is poor form as you can't then refactor your code without the binder breaking.

The binder needs to support lambdas in the same way that a grid does:

e.g
```
class Parent
{
   Child child;
}

class Child
{
String name;
}

Binder<Parent> binder;

binder.bind(parent -> parent.child.name);
```
This form will allow for code refactoring without breakage and make it consistent with Grid column binding.

**Comment by TatuLund** [comment]
I think you have slight misunderstanding about syntax. In your case the binding should roughly this way:

```
Binder<Parent> binder = new Binder<>();

TextField childNameField = new TextField();

binder.forField(childNameField).bind(
  parent -> parent.getChild().getName(),
  (parent, name) -> parent.getChild().setName(name));

```

**Comment by tsuoanttila** [comment]
According to a quick test, this at least works with 8.3.1:
```
        final TextField name = new TextField("parent.child.name");

        Binder<Parent> binder = new Binder<>();
        binder.bind(name, parent -> parent.child.name,
                (parent, newName) -> parent.child.name = newName);

        Parent p = new Parent();
        Child c = new Child();
        p.child = c;
        c.name = "Pekka";

        binder.setBean(p);

        layout.addComponents(name,
                new Button("Output!", e -> Notification.show(p.child.name)));
```

**Comment by bsutton** [comment]
OK that worked, so thank you.

It might help if the doco provided this example. I'm still getting my head
around lambdas and this certainly wasn't an obvious solution.

**Comment by bsutton** [comment]
thanks for the help.
