### ISSUE TITLE
UIClientRpc#uiClosed is not invoked

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/framework#10702]
On the server side we do the following:
```
ui.getPage().setLocation(redirectUrl.addPathSegment("logout").build().uri());
ui.setContent(null);
ui.close();
```

The browser receives this:
`PUSH: "syncId": 41, "clientId": 21, "changes" : [["change",{"pid":"0"},["0",{"id":"0"},["open",{"src":"http:\/\/localhost:9494\/anything\/logout","name":"_self","popup":false}]]]], "state":{}, "types":{"0":"0"}, "hierarchy":{"0":["1452","2412","2","3","4","177","178","179","180"]}, "rpc" : [["0","com.vaadin.shared.ui.ui.UIClientRpc","uiClosed",[false]]], "meta" : {"async":true}, "resources" : {}, "timings":[12626, 2]`

But the code inside the UIConnector-registerRpc -> uiClosed is not invoked.
Not just the deferred callback is ignored but we manually added some additional code/logging there without the Scheduler which is also not reached.

From the above written response the "open" & also the "hierarchy" parts are evaluated as expected so we assume only the rpc calls are omitted which means we cannot workaround the issue with an rpc call on another component.

Reproducible 
- IE 11.850.15.063.0; Edge 40.15.063.674.0; Firefox 58.0.2 (64bit); (_Not in Chrome_)
- The Vaadin version is 8.0.6
- Jetty version 9.2.9.v20150224

**Comment by TatuLund** [comment]
This ticket has been left uncommented. Just noting, that closing ui is not the correct logout procedure, instead one should invalidate underlying http session.

`VaadinSession.getCurrent().getSession().invalidate();`
