### ISSUE TITLE
removeBean does not clear fields when using read/write Bean.

### ISSUE THREAD

**Issue by bsutton** [vaadin/framework#10725]
RemoveBean was modifed under #8287 to clear the fields associated with the bean.

The problem is that if you use read/write bean there is no simple way to clear the fields.

All we really need is to change the 'clearField' method from private to public and then uses of read/write bean will have a simple way of clearing the fields. 
Alternativly removeBean should always clear fields even if the bean isn't currently associated.

Supporting this method is importing for implementing CRUDs where you build the edit page fields once and re-use the page each time you edit/create a new entity.
Calling readBean doesn't clear combo box fields if the bound entity member is null (so maybe this is the real problem?)

**Comment by tsuoanttila** [comment]
Calling `readBean` with `null` invokes `Binder::clearFields` which calls `HasValue::clear` on all bound fields. `clear` is defined to do `setValue(getEmptyValue())` which in the case of mentioned combobox is practically `comboBox.setValue(null)`. 

From `Binder::readBean` JavaDoc
```
     * @param bean
     *            the bean whose property values to read or {@code null} to
     *            clear bound fields
```
We do have some tests for this functionality and the tests are passing. Can you provide a code example where this does not work to make it easier and faster to debug and fix?

**Comment by bsutton** [comment]
OK, using readBean(null) worked, I had missed the comment about it clearing fields.

I've been using the online vaadin book and I doesn't cover this fairly important aspect of using beans.
It also falls somewhat short of explaining the relationship between setBean/removeBean, readBean/WriteBean. It also doesn't do a great job of explaining what technique you should use if different circumstances.

Also if readBean clears the field then why do we need removeBean when logically setBean should do the same as readBean when called with null.

I will close this issue as the report problem isn't a bug.

thanks,
brett
