### ISSUE TITLE
Documentation discusses about FocusShortcut which don't exist anymore

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#10730]
Original website feedback:
On the page: https://vaadin.com/docs/v8/framework/advanced/advanced-shortcuts.html?utm_source=email&utm_content=51577051

`AbstractField.FocusShortcut` appears so many times in this document but can't find in the library. 

Kindly look into and update

**Comment by anasmi** [comment]
https://github.com/vaadin/framework/issues/8297

**Comment by mstahv** [comment]
Closing as duplicate to #8297
