### ISSUE TITLE
vaadin 8.3.0 Grid::setDataProvider turns all columns to sortable

### ISSUE THREAD

**Issue by andreika63** [vaadin/framework#10732]
- Vaadin Framework version 8.3.0
- Description of the bug
Grid initializes with:
 grid.getColumns().forEach(c -> c.setSortable(false)); //disable sorting on all columns after all columns configured

after we use method Grid#setDataProvider all colums turns to sortable
p.s. my dataprovider is not inmemory provider

com.vaadin.ui.Grid#internalSetDataProvider
com/vaadin/ui/Grid.java:4733
com/vaadin/ui/Grid.java:1167
com/vaadin/ui/Grid.java:840 always returns true

p.s. I'll generate some example code if needed

**Comment by TatuLund** [comment]
Does this happen also in 8.3.2?

See: https://github.com/vaadin/framework/issues/10467

**Comment by andreika63** [comment]
Hi, 8.3.2 looks fine!
https://github.com/andreika63/gridDataProvider
