### ISSUE TITLE
archetype -widget is incompatible with directory instructions

### ISSUE THREAD

**Issue by tmattsso** [vaadin/framework#10736]
when building the widget using this archetype, it produces a ZIP file that Directory rejects. The fault is in the manifest files; Directory checks the anifest headers, and the build does not include the correct ones.

**Comment by tsuoanttila** [comment]
This issue is in the wrong repository, it should be opened in https://github.com/vaadin/archetypes instead.

**Comment by tsuoanttila** [comment]
Moved.
