### ISSUE TITLE
 Vaadin 7.7.13 StreamResource filename with '#' breaks download

### ISSUE THREAD

**Issue by OpenESignForms** [vaadin/framework#10747]
To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version: 7.7.13
- Browser version: All
- Tomcat 8.5
- Description of the bug
As described in the forum: https://vaadin.com/forum/thread/17008991/17021057
We are on Vaadin 7.7.13, and our code for creating a StreamResource sets the filename parameter to a value like "Yozons #1234.pdf" as this was the file name uploaded into our system.  For downloading, when we create the StreamResource, the resulting connector URL is invalid and results in a 404.  If the '#' is removed from the file name, it works normally.

Below is our Tomcat access log showing that once the '#' was found in the filename, it just stopped the URL prematurely and thus gets a 404:

0:0:0:0:0:0:0:1 - - [13/Mar/2018:19:28:39 -0500] "GET /open-eSignFormsVaadin/ui/APP/global/0/legacy/0/Yozons%20 HTTP/1.1" 404 16049

Below is the same access log after renaming the file to remove the '#'.  This then works with a valid URL:

0:0:0:0:0:0:0:1 - - [13/Mar/2018:19:38:36 -0500] "GET /open-eSignFormsVaadin/ui/APP/global/0/legacy/0/Yozons%201234.pdf HTTP/1.1" 200 84639

The issue isn't the browser, it's the StreamResource that doesn't encode the filename correctly. I do not create the URL, just the filename for the StreamResource (that is, I do not specify any of the URL '/APP/globa/0/legacy/0/' either).

If I do a traditional download all using UTF-8 encoding, and set the content-disposition header filename="Yozons #123.pdf" there is no issue whatsoever. I can download the file with the '#' symbold from my vaadin app via other schemes without issue, just when I try to use a StreamResource.

It's only that StreamResource is not generating a useful URL when the filename contains a '#' symbol, which is not really weird as they are uploading and downloading files, and file names are not restricted to un-encoded URL characters. Nowhere in the documention does it suggest when I specify the filename param to StreamResource I should be specially encoding it, as StreamResource already encoded things like the space (%20), which I didn't do.

**Comment by mcollovati** [comment]
Seems like the problem is that `ConnectorResource` registered via `GlobalResourceHandler` 
does not URL encode the filename.

Here is the relevant part of code
```
public void register(Resource resource, ClientConnector ownerConnector) {
    if (resource instanceof ConnectorResource) {
        if (!(ownerConnector instanceof LegacyComponent)) {
            throw new IllegalArgumentException(
                    "A normal ConnectorResource can only be registered for legacy components.");
        }
        ConnectorResource connectorResource = (ConnectorResource) resource;
        if (!legacyResourceKeys.containsKey(resource)) {
            String uri = LEGACY_TYPE + '/'
                    + Integer.toString(nextLegacyId++);
            String filename = connectorResource.getFilename();
            if (filename != null && !filename.isEmpty()) {
                uri += '/' + filename;
            }
            legacyResourceKeys.put(connectorResource, uri);
            legacyResources.put(uri, connectorResource);
            registerResourceUsage(connectorResource, ownerConnector);
        }
    }
}
```

As you can see `filename` is taken as is.
By contrast in `ResourceReference` when using non global handled `ConnectorResource`
there is the following code

```
private static String getConnectorResourceBase(String filename,
        ClientConnector connector) {
    String uri = ApplicationConstants.APP_PROTOCOL_PREFIX
            + ApplicationConstants.APP_PATH + '/'
            + ConnectorResource.CONNECTOR_PATH + '/'
            + connector.getUI().getUIId() + '/' + connector.getConnectorId()
            + '/' + encodeFileName(filename);
    return uri;
}
```
And here `filename` is encoded.

I suppose you are using `Embedded` component that in Vaadin 7.7.x registers resources in `GlobalResourseHandler` (via `paintContent` method) whereas in Vaadin 8.x resource is handled directly  by `ConnectorResourceHandler`.

This kind of problem is however still relevant in Vaadin 8 as `GlobalResourseHandler` is used for handling icons in menu items and in compatibility packages
