### ISSUE TITLE
Combobox not correctly rendered when adding an icon in grid editor

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10748]
The exact same combobox code in a form and in the grid editor are rendered differently. In the form it's fine but as soon as I put the same combobox with an icon in a grid editor it seems to ignore any space needed to render the icon as shown in the screenshot. The code is just:

`comboBox.setItemIconGenerator(...);`
`grid.setEditorBinding(binder.forField(combobox)...bind());`

I didn't see a way to attach a screenshot so if you want to see how it's rendered you can view my forum post at: [https://vaadin.com/forum/thread/17020970](https://vaadin.com/forum/thread/17020970)

**Comment by anasmi** [comment]
Hi, 
this might not be related at all, but what is the height of you icon, combobox and the *line* combobox in? If icon's height, for example, exceeds the height of the editor's line, you might see some weird rendering problems like this. (I have seen something similar when scrolling, but this might not be related through. Just a guess)

**Comment by FollowSteph** [comment]
I'm using the icons from the Fam3SilkIcon add-on: https://vaadin.com/directory/component/fam3-silk-icons. Specifically just the dots (Fam3SilkIcon.BULLET_BLACK, etc.). All that to say it's a 16x16 icon.

**Comment by anasmi** [comment]
Could you check in inspect tab(developer tools),if it overflows the row or not?

**Comment by TatuLund** [comment]
I could replicate the issues with VaadinIcons as well.

**Comment by FollowSteph** [comment]
Honestly I'm not sure how to do this. I just tried to inspect it but finding the specific element and knowing exactly which properties is definitely a struggle. That being said if you just add that plugin you will be able to replicate it.

**Comment by anasmi** [comment]
Hi,
I managed to reproduce the problem and find a possible solution : ) The problem is that style applied for **cells-editing** is overriding the default style and icons in this case are not taken into account.
The fix is to add this line to your style themes:
```
.v-filterselect .v-icon + [class*="input"]{
     padding-left: 37px !important;
} 
```
It should set the padding left to 37px (As it usually does, not the 18px in case of v-grid-editor-cells)
Below are two screenshots, with problem occured and problem eliminated by applying fix.

I hope it will also solve the issue in your case : )

![overriden style](https://user-images.githubusercontent.com/15248706/37949683-4ec7e806-319e-11e8-982b-9319ec681ff7.jpg)
![importantipplied](https://user-images.githubusercontent.com/15248706/37949685-5217cf26-319e-11e8-810c-91a7bb843e94.jpg)

**Comment by FollowSteph** [comment]
Thank you, yes that seemed to resolve the issue. 

Assuming this will be fixed in an upcoming release would it be possible to also fix the editors (ComboBox, TextField) etc so that if the column is not wide enough that it will right align. In other words it seems to go to the end of the line but then as soon as you click on any field in the editor it right aligns, even if it's not a field you're in. I've submitted the following bug for it: https://github.com/vaadin/framework/issues/10763

**Comment by anasmi** [comment]
Hi,

I think it will not be included in the upcoming release for now, as it needs testing and we will need to verify that this change doesn't break themes in other cases. I suggest you to include this change into your theme for now, but if I will have a moment  at some point I will try to make a pull request, but can't promise anything :( 

Anyway, I am glad to hear it works  for you : )

I will also check then another bug, you have found, when will have a moment. 

Have a nice day! :)

**Comment by FollowSteph** [comment]
Hopefully it will make it soon, but I can appreciate there being more testing. 

If you're going to look into that bug you may also want to look at: https://github.com/vaadin/framework/issues/10764 because it's probably related. All to do with the grid editor.

**Comment by FollowSteph** [comment]
I also added another bug with the Grid Editor at: https://github.com/vaadin/framework/issues/10772 I'm only mentioning here is so that if there are any fixes they can be done as a batch. Basically they are all issues with the Grid Editor and how it's rendered.
