### ISSUE TITLE
Scroll to selected Combobox item issue

### ISSUE THREAD

**Issue by Vilkaz** [vaadin/framework#10741]
- Vaadin Framework version (e.g. 8.3.1)
- Browser version : Chrome Version 64.0.3282.186 (Offizieller Build) (64-Bit)
- Web container name and version : Spring boot 2.0.0
- Description of the bug
After a Homepage is loaded, with the first click on an ComboBox, which has 
Value and setScrollToSelectedItem(true)

The SuggestionBox still shows the Items from top down, not from the value.

But ! when you click away, and click the ComboBox drop down arrow again, the sugesstion box works corectly and shows the options including the selected value.

- Minimal reproducible example

```
public class Item {
    private Long id;
    private String name;
   //constructors, getters setters
}
```
 ```
        List<Item> items = new ArrayList<>();

        LongStream.range(1,100)
                .forEach(l -> items.add(new Item(l, "item:"+l)));
        Item selectedItem = new Item(50l, "SHOW ME");
        items.set(50, selectedItem);

        ComboBox<Item> box = new ComboBox<>("items", items);
        box.setItemCaptionGenerator(Item::getName);
        box.setScrollToSelectedItem(true);
        box.setValue(selectedItem);
```
[demo on heroku / potentialy slow start](https://vaadin-scroll-to-selected-item.herokuapp.com/)
- Expected behavior
![image](https://user-images.githubusercontent.com/8351796/37768463-051bbddc-2dce-11e8-9928-38759e94b03d.png)

- Actual behavior
![image](https://user-images.githubusercontent.com/8351796/37768482-17a12a50-2dce-11e8-8f9c-674ad0210916.png)

p.s. i know ... we have picky testers :)

**Comment by anasmi** [comment]
Reproducible without Spring also

**Comment by TatuLund** [comment]
This fix https://github.com/vaadin/framework/pull/10796 introduced in Vaadin 8.5.0 could have potentially fixed this issue as well, since it alters the selection state logic. This should be verified.

**Comment by Vilkaz** [comment]
I just updated the demo application. Vaadin is now 8.5.1 but the bug is stil there :(
[github link](https://github.com/Vilkaz/combobox-scroll-to-selected-item)
[demo](https://vaadin-scroll-to-selected-item.herokuapp.com/)

**Comment by sergeydobro** [comment]
Still reproducible for 8.8.2
