### ISSUE TITLE
valo inline-icon is incorrectly rendered

### ISSUE THREAD

**Issue by marquiswang** [vaadin/framework#10752]
Copying from stale issue https://github.com/vaadin/framework/issues/7071

This is broken for me using Vaadin 8.3.2, on OS X in Chrome and Safari.

```
VerticalLayout verticalLayout = new VerticalLayout();
TextField nameField = new TextField("Name");
nameField.setIcon(FontAwesome.USER);
nameField.addStyleName(ValoTheme.TEXTFIELD_INLINE_ICON);
verticalLayout.addComponent(nameField);
```
produces this correctly:

![ef8686f6-c379-11e6-9f7a-2afbd63ca234](https://cloud.githubusercontent.com/assets/851745/21257719/ef8686f6-c379-11e6-9f7a-2afbd63ca234.png)

while this code:

```
VerticalLayout verticalLayout = new VerticalLayout();
TextField nameField = new TextField("Name");
nameField.setIcon(FontAwesome.USER);
nameField.addStyleName(ValoTheme.TEXTFIELD_INLINE_ICON);
FormLayout formLayout = new FormLayout(nameField);
verticalLayout.addComponent(formLayout);
```

produces this:
![ef8686f6-c379-11e6-9f7a-2afbd63ca234](https://cloud.githubusercontent.com/assets/851745/21257810/4a8c6b60-c37a-11e6-95c5-49bdc5757724.png)

**Comment by OlliTietavainenVaadin** [comment]
Looks like the issue is not limited to FormLayout, you can also see it in the Sampler https://demo.vaadin.com/sampler/#ui/data-input/text-input/text-field . Just add the `inline-icon` style name and choose an icon.

**Comment by TatuLund** [comment]
This is probably related to https://github.com/vaadin/framework/issues/9089

**Comment by TatuLund** [comment]
After taking closer look, this is not related to #9089. Also the clitch pointed by @OlliTietavainenVaadin in Sampler seems to be different issue, and problem in Sampler code (there is a flaw in the styles of the resizeable layout where TextField). 

FormLayout hijacks the caption, and after that the Icon is not a child element in TextField at all. So the normal styles how inline icon is implemented, cannot possibly work.

However, a workaround is possible, but its application specific.

When inline icon style is added, the v-icon will have position: absolute set. The .v-caption will be still augmented by the style name you give with `textField.addStyleName("my-text-field")` This gives a possibility that you can do something like follows

```
	.v-caption-my-text-field > .v-icon {
		top: 37px;
		left: 57px !important;
	}

```
