### ISSUE TITLE
OSGi Portlets on Liferay 7

### ISSUE THREAD

**Issue by mltpz** [vaadin/framework#10755]
Dear all, 
according to [https://vaadin.com/docs/v8/framework/portal/portal-osgi.html](https://vaadin.com/docs/v8/framework/portal/portal-osgi.html) it should be possible to install OSGi support in Liferay using the following script:

> java -jar blade.jar sh start https://repo1.maven.org/maven2/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/external/gentyref/1.2.0.vaadin1/gentyref-1.2.0.vaadin1.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-shared/8.1.0/vaadin-shared-8.1.0.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-server/8.1.0/vaadin-server-8.1.0.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-osgi-integration/8.1.0/vaadin-osgi-integration-8.1.0.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-client-compiled/8.1.0/vaadin-client-compiled-8.1.0.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-themes/8.1.0/vaadin-themes-8.1.0.jar
java -jar blade.jar sh start https://repo1.maven.org/maven2/com/vaadin/vaadin-liferay-integration/8.1.0/vaadin-liferay-integration-8.1.0.jar
java -jar blade.jar sh start file:<path_to_liferay_portlet.jar>

The above script works fine changing vaadin version from 8.1.0 to 8.1.6, but there's an error changing the version to latest 8.3.1 or 8.3.2. Error is:

> org.osgi.framework.BundleException: Could not resolve module: com.vaadin.server [532] 
Unresolved requirement: Import-Package: com.vaadin.sass.internal; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.cache; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.client; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.cpr; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.handler; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.interceptor; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.atmosphere.util; version="2.4.11.vaadin2"; resolution:="optional" 
Unresolved requirement: Import-Package: org.jsoup; version="[1.11.0,2.0.0)" >

Used Liferay version is 7.0-ga5

Do you have any suggestion to install Vaadin 8.3.2 with Liferay 7.0-ga5?
Regards

**Comment by Artur-** [comment]
The error message says that you need jsoup >=1.11.0. Have you tried installing a newer jsoup than 1.8.3?

**Comment by mltpz** [comment]
Sorry, I'm not expert about OSGi and Maven and I didn't understood that error message.
Yes, installing the 1.11.2 (latest) version of jsoup no error is raised.
Please, close this issue

**Comment by mstahv** [comment]
The documentation should definitely be updated on this part, which was already started by @Artur- 

As the example in doc has hardcoded version numbers, it should definitely contain a hint how to detect the correct dependency version. mvn dependency:tree would probably be an easy way for users to find them out?

Also the archetype maven coordinates has hardcoded version number. I'd just leave the version out of that part altogether.

**Comment by TatuLund** [comment]
The documentation was recently reviewed and revised. We also tested that portlet can actually be deployed by following the instructions.

https://vaadin.com/docs/v8/framework/portal/portal-osgi.html
