### ISSUE TITLE
Make it possible to embed a Vaadin UI based on an element instance instead of based on an element id

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#10766]
The way it's currently implemented, `UIConnector.init` creates a `RootPanel` to attach itself to using `RootPanel.get(rootPanelId)`. This doesn't work when the target element is inside the Shadow DOM of an element since `document.getElementById(id)` doesn't include encapsulated elements.

To make it possible to embed Vaadin applications inside a Web Component, we should make it possible to provide an element instance in the application configuration (i.e. the same place where e.g. `serviceUrl`  is configured).

The only constructor of `RootPanel` is `private`,  and none of the internal callers are really helpful for creating an instance based on an arbitrary element. It might be feasible to use JSNI to manually call the `private` constructor, or alternatively just create a `AbsolutePanel` instead since Vaadin itself doesn't use any API specific to `RootPanel`. In either case, care should also be taken to ensure the widget gets properly detached when appropriate, similarly to how a `RootPanel` works by default.

**Comment by elmot** [comment]
Implemented with #10785
