### ISSUE TITLE
Fire an event when anything in a UI is marked as dirty

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#10765]
Make it possible to register a listener on the `UI` level that receives an event whenever any connector in that UI is marked as dirty (i.e. through `ConnctorTracker.markDirty(ClientConnector)`). 

The event should at the very least contain a reference to the originating UI and the connector that was marked as dirty.

The event should only be fired if the connector wasn't already dirty prior to calling `markDirty()`.

**Comment by knoobie** [comment]
Could this be used to resolve pro/support#2418 as well? Kinda sounds like a good starting point for me.

**Comment by caalador** [comment]
It might. At least the now something has happened would be consistent.

**Comment by tsuoanttila** [comment]
PR Merged, closing issue.
