### ISSUE TITLE
The width of a TextArea component does not match the width of the Grid column in the Editor

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10779]
If I have:

grid.addColumn(myPojo::getValue)
      .setEditorBinding(binder, myTextArea);

Then the width of the TextArea does not match the width of the column but stays a small box

**Comment by TatuLund** [comment]
This is related to https://github.com/vaadin/framework/issues/10776

TextArea is not a component by nature that is suitable to inline editor use case.
