### ISSUE TITLE
Editing a TextArea in a Grid Editor causes all the editor fields to be lost if the TextArea is more than a few lines

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10776]
If you type in say "aa" and then carriage return a dozen times the TextArea will get a scrollbar. This will eventually lead to the other fields not being displayed in the Grid Editor. You can get back by moving the caret to the top of the TextArea but if you try to scroll up in the TextArea then you're stuck and cannot see the rest of the fields in the Grid.

**Comment by TatuLund** [comment]
TextArea as multi row input, is not the best match in Grid. The first thing ofcourse is to set row height to be big enough to accomodate the TextArea. Intuitively I tend to think, that one would not use TextArea in Grid's editor at all. Instead you could use it for editing longer texts in proper master detail pattern (i.e. click row to open form and edit), also if the text is long, probably I would show only the beginning of the text in the Grid with ellipsis.

Could you add screenshots illustrating the case.

**Comment by FollowSteph** [comment]
It's so that they can add a quick note to a Notes field. In some cases it's more than a line but generally no more then 2-3 lines.

It's not the height of the TextArea but rather the width. Attached is a screenshot as requested. Notice the width is not used up like it would be with a TextField

![gridtextarea](https://user-images.githubusercontent.com/19716286/38182155-8edf14c6-3605-11e8-95ce-77d19f17f05a.jpg)

**Comment by FollowSteph** [comment]
Also just to be clear it doesn't seem to matter if it's the last or first column in the table.
