### ISSUE TITLE
DateField addValueChangeListener() is not reflecting changes by typing date manually

### ISSUE THREAD

**Issue by maushomu** [vaadin/framework#10774]
DateField addValueChangeListener() is not reflecting changes by typing date manually. It is necessary to leave the field to fire value change listener. Seems to be mentioned also here: https://github.com/vaadin/framework/issues/8905

Please fix.

**Comment by TatuLund** [comment]
Fixed by https://github.com/vaadin/framework/pull/10518 in Vaadin 8.4.0

There is still issue in compatibility library, but closing as duplicate as other reports exist https://github.com/vaadin/framework/issues/10854
