### ISSUE TITLE
Cannot add an Image thumbnail component to a Grid Editor so that the user knows which image is being edited

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#10780]
I have a table of pictures (in our software it's pictures of the building that are being rented for example) and as such the user will generally include details such as what the picture is of but also notes such as the condition of the items. An example would be a picture of the oven and then comments about it's condition, etc. The problem is that if you try to use the Grid Editor I cannot find a way to display the thumbnail. The renderer is gone which means you would have to add an Image component but you can't link the Image to a Binder as far as I can tell. Therefore it would be great to add the ability to see the thumbnail in cases like this.

![gridpictures](https://user-images.githubusercontent.com/19716286/38182528-128da5c4-3608-11e8-87f3-564a9ee5652a.jpg)

**Comment by TatuLund** [comment]
This is working as designed. Renderers are not applied in editor row, to avoid conflict with possible Field in edit row. Image component is not a Field, thus you can't bind it directly. In your case you would need to create custom Field, that e.g. uses Image.

**Comment by knoobie** [comment]
Sounds like a good usecase for https://github.com/vaadin/framework/blob/82ff6cfab34c67f5bfcd9453689c0996945156b1/server/src/main/java/com/vaadin/data/ReadOnlyHasValue.java (untested idea)

**Comment by elmot** [comment]
@knoobie, you are right, it was made exactly for cases like this one. There is no example for images but basic usage example is here:
https://github.com/vaadin/framework/blob/940a1ef584c82e343474863408771ff091044bdc/server/src/test/java/com/vaadin/data/ReadOnlyHasValueTest.java#L54-L57
