### ISSUE TITLE
Button keeps disabled after download

### ISSUE THREAD

**Issue by Gaspode44** [vaadin/framework#10807]
* Vaadin Framework version: checked with 8.3.1 and 8.3.3
* Browser version: Firefox 59.0.2, IE 11
* Web container name and version: Jetty 8.1.5

* Scenario: Button extended with FileDownloader and flagged with setDisableOnClick(true)
* Bug: The button keeps disabled after download finished for Firefox and IE. Chrome 65.0.3325.181 works fine.

I found out that the order of requests is different for Firefox and Chrome:
* Firefox: First ClickListener then getFileDownloadResource
* Chrome: First getFileDownloadResource then ClickListener 
I don't know if this is relevant for this issue.

**Comment by knoobie** [comment]
Do you enable the button afterwards? See Documentation of setDisableOnClick

 https://github.com/vaadin/framework/blob/6541b7bad2e41c57a7731611a3f2f7032a5ce947/server/src/main/java/com/vaadin/ui/Button.java#L498

**Comment by knoobie** [comment]
I sounds more like a bug to me that the button automaticly re-enables afterwards. I have never heard about this or seen it in my code. 

See: https://demo.vaadin.com/sampler/#ui/interaction/button

Configure: setDisableOnClick=true and the button stays disabled after you clicked it.

**Comment by Gaspode44** [comment]
But I am very happy that it works with mine code :-) And  I think this is the way it should be.
You are right. In this example it stays disabled. But if you afterwards remove the "Enabled" flag and then set it again the button also keeps disabled as it was not possible for me to enable it manually in my code.

**Comment by Gaspode44** [comment]
Strange, now it works to manually enable it. Don't know what is is different compared to my last try.
But still it is mysterious that it works automatically for Chrome also with extension and for all browsers without extension.
Thanks for your advice.
(And the different request order is annoying when generating download content dynamically. But I will make an extra issue for that.)

**Comment by knoobie** [comment]
FYI: You could take a look at  @mstahv's DownloadButton in [viritin](https://github.com/viritin/viritin/blob/68930963ac4009e2c47b87377f9820b602e9be6a/viritin/src/main/java/org/vaadin/viritin/button/DownloadButton.java). It's working wonderful.

**Comment by Gaspode44** [comment]
Looks good, but as far as I see it does not address my problem, which is that on the one hand different browsers call ClickListener and getFileDownloadResource in different orders and on the other hand I have different kinds of responses (dynamically generated download code that will be returned by getFileDownloadResource or GUI changes, e.g. showing a message if content generation was not possible for some reason by ClickListener... or sometimes even both.)
So I need the first called request (regardless which one it may be) to generate the content so that the ClickListener can afterwards return the error message and the getFileDownloadResource can return the (temporarily buffered) content. (But the second request should not generate the content again.)
I now have a solution for this, but better never only one of both request appear (connection problems or so).
