### ISSUE TITLE
DesignFormatter should have addConverter/removeConverter public

### ISSUE THREAD

**Issue by joergriegel** [vaadin/framework#10819]
If you supply user-defined data to components, the DesignObjectConverter comes in and always calls the toString method of the object as the inputType is taken from the getter of data. No chance to apply a proper toModel/toPresentation converter for that. In effect, user objects are not serializable thru the valuable Vaadin declaritive approach. Please find a way to supply user-defined converters here to enable e.g. Button components carry click-action supplemental data.

**Comment by TatuLund** [comment]
addConverter and removeConverter are protected, so you should be able to override those by extending the class, say like this

```
	public class MyDesignFormatter extends DesignFormatter {
		@Override
		public <T> void addConverter(Class<?> type, Converter<String, ?> converter) {
	        	
		}
	}

```

**Comment by joergriegel** [comment]
Thank you for that. But I saw no possibilty to register a custom DesignFormatter. It is just instantiated in DesignAttributeHandler and no setter to replace the formatter: 
`private static DesignFormatter FORMATTER = new DesignFormatter();`
Could you give me a hint to do this?

**Comment by joergriegel** [comment]
With a weird reflection trick I made addConverter public. But wouldn't it be a great feature for users of the declarative approach to be able to supply their own converters?

**Comment by elmot** [comment]
@joergriegel, potentially you can you convert your reflection trick into actual pull-request. This is fastest way to include a feature into the framework. The only one thing - we need a test for it.

**Comment by Artur-** [comment]
There is no need to supply a global converter to handle a specific value in a specific component. `Component.readDesign` and `getCustomAttributes` exists so you can override the behavior for a component.

**Comment by joergriegel** [comment]
Hi Artur. I find this a very cumsy approach as one must then reimplement all stuff that makes up a differentiated component just to be able to use declaritive stuff. Could you give a simple example for a Button with a custom data tag? Also, I don't see your point with the add-ons: the probability is so little that developers register the same type that it is insignificant, or if they register a common type it is very probably that they implement the same converter stuff. Either way the damage doing so is little. For my optinion it has more importance to easily enable the declaritive approch than to protect developers from misusing the converter registration.
