### ISSUE TITLE
Window component loses scrolling when field inside is clicked (reproducible)

### ISSUE THREAD

**Issue by mheicke** [vaadin/framework#10828]
- Vaadin Framework version
current released version on demo.vaadin.com/sampler (2018-04-17)

- Browser version
Google Chrome Version 65.0.3325.181 64-Bit, Safari Version 11.1 (12605.1.33.1.3) under OS X 10.12.6 (also under Chrome on Windows 10)

- Description of the bug
it seems like the calls of `getState().positionY = positionY; getState().positionX = positionX; getState().centered = false;`  in `setPositionX(int positionX)` and `setPositionY(int positionY)` in class `com.vaadin.ui.window` somehow lead to an update of the client UI. In this case the v-has-height class and height css style of a particular div is removed which leads to the behaviour described below.
div before: `<div class="v-window v-widget v-has-width v-has-height" role="dialog" aria-relevant="additions" aria-labelledby="gwt-uid-33" style="margin-left: 0px; margin-top: 0px; left: 0px; top: 0px; z-index: 10000; visibility: visible; position: absolute; overflow: visible; width: 300px; height: 150px; min-width: 0px; min-height: 36px;">`
div after: `<div class="v-window v-widget v-has-width"              role="dialog" aria-relevant="additions" aria-labelledby="gwt-uid-33" style="margin-left: 0px; margin-top: 0px; left: 0px; top: 0px; z-index: 10000; visibility: visible; position: absolute; overflow: visible; width: 300px; min-width: 0px; min-height: 36px;">`

- Minimal reproducible example
Go to https://demo.vaadin.com/sampler/#ui/structure/window, resize the browser window so the vaadin-popup-window will not completly fit. Open the popup window (see the scrollbar on the right). Click one of the checkboxes

- Expected behavior
the scrollbars should stay and it should still be possilbe to scroll

- Actual behavior
the scrollbars will disappear since the window pops into full height and it's not longer possible to scroll

When the methods setPositionX(int positionX) and setPositionY(int positionY) in window are overwritten with no call of super, the behaviour seems to be normal again, but I don't have the feeling that this is a valid fix ;)

**Comment by mheicke** [comment]
PS: image proof of the behaviour:

![bildschirmfoto 2018-04-17 um 14 55 52](https://user-images.githubusercontent.com/246571/38870897-7d70193c-424f-11e8-92bf-00b53b858401.png)
![bildschirmfoto 2018-04-17 um 14 55 57](https://user-images.githubusercontent.com/246571/38870898-7d8c8180-424f-11e8-822e-8b8f25ef05d3.png)

**Comment by elmot** [comment]
Seems to be a duplicate of #10652.
@mheicke, can you, please, revalidate your case against Vaadin 8.5.0.beta1?

**Comment by mheicke** [comment]
@elmot we just checked Vaadin 8.5.0.beta2 and the problem seems to remain, sorry :(

**Comment by elmot** [comment]
The sampler is made out of 8.4.5, since 8.5 is not out yet

**Comment by mheicke** [comment]
@elmot just wanted to let you know, the bug does still remain with Vaadin 8.5.1 (see the sampler)

**Comment by elmot** [comment]
@mheicke thanks

**Comment by mheicke** [comment]
It is still valid, a simple reproducible example is provided

**Comment by anasmi** [comment]
Do you still experience this issue? I can't reproduce it anymore in Chrome using https://demo.vaadin.com/sampler/#ui/structure/window

**Comment by mheicke** [comment]
@anasmi you are right, it seems to be fixed. Must have happened in one of the last releases. I'll close the ticket

**Comment by anasmi** [comment]
Thanks for checking back!
