### ISSUE TITLE
No args c-tor exception

### ISSUE THREAD

**Issue by TeoPaius** [vaadin/framework#10836]
Using Vaadin 8.1.7 I got this error 

`javax.servlet.ServletException: com.vaadin.server.ServiceException: com.vaadin.server.ServiceException: com.cyberschnitzel.View.MainWindow doesn't have a public no-args constructor
	com.vaadin.server.VaadinServlet.service(VaadinServlet.java:383)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)`

I'm using the basic vaadin template generated from intellij so there should be no problem.
If I try to add the no args c-tor I get this error
`SEVERE: Servlet.service() for servlet [BloodDonationServlet] in context with path [] threw exception [com.vaadin.server.ServiceException: java.lang.IllegalArgumentException: Unable to create an instance of {0}. Make sure the class is public and that is has a public no-arg constructor.] with root cause
java.lang.IllegalAccessException: class com.vaadin.util.ReflectTools cannot access a member of class com.cyberschnitzel.View.MainWindow with modifiers "public"
`
The MainWindow code looks like this
`@Theme("mytheme")
class MainWindow extends UI {
    private static final boolean PRODUCTION_MODE = false;

    public MainWindow() { }

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        final TextField name = new TextField();
        name.setCaption("Type your name here:");

        Button button = new Button("Click Me");
        button.addClickListener(e -> layout.addComponent(new Label("Thanks " + name.getValue()
                + ", it works!")));
        
        layout.addComponents(name, button);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "BloodDonationServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MainWindow.class, productionMode = PRODUCTION_MODE)
    public static class MyUIServlet extends VaadinServlet {
        // Override this function to do stuff when server initializes (get connection to DB, start schedulers etc)
        @Override
        protected void servletInitialized() throws ServletException {
            super.servletInitialized();

            initializeServices();
        }

        // Override this function to do stuff when server finishes normally (stop connection to DB, stop threads etc)
        @Override
        public void destroy() {
            super.destroy();

            teardownServices();
        }

        /**
         * This method will start a thread to initialize the Database etc
         */
        private void initializeServices() {
            new Thread(() -> {

                // This will get the database connection
                // noinspection Convert2MethodRef
                DatabaseUtil.getConnection();
            }).run();
        }

        /**
         * This method will do the cleanup
         */
        private void teardownServices() {
            DatabaseUtil.closeConnection();
        }
    }
}
`
It works on macOS and Linux, but not on Windows.
If I comment the annotations @WebServlet and @VaadinServletConfiguration I don't get the errors, but the ui doesn't show up.

**Comment by vanpana** [comment]
I also get this error

**Comment by TeoPaius** [comment]
Fixed it, I made the MainWindow public
