### ISSUE TITLE
Checked checkbox on a tabsheet gets unchecked when navigating away and back to the tab

### ISSUE THREAD

**Issue by koendecock** [vaadin/framework#10859]
- Tested and reproducible on Vaadin Framework version 7.7.13 and 8.2.0
- Issue only appears in Safari (tested with Safari version 11.1) (no issues on chrome and firefox)
- Web container: Tomcat 7.0.40
- Description of the bug: I've for a tabsheet with 2 tabs, on the first tab I've a checkbox (checked). When the application loads, the first tab is visible and the checkbox is checked. When I navigate to the second tab and navigate back to the first tab, the checkbox is unchecked. The issue only appears on Safari. I could not reproduce the issue on chrome, neither on firefox.
- Expected behavior: I expected the checkbox on the first tab to still be checked.
- Actual behavior: The checkbox on the first tab is unchecked

**Comment by Saxintosh** [comment]
I have a similar behaviour.
A checked checkbox appear unchecked until I click in any part of the browser window... after that, it appears checked... only in Safari.

**Comment by kvalev** [comment]
I have the exact same issue - loading a page with a checkbox that is supposed to be checked, shows it as unchecked (although in html the state is set to checked).
Tested with Safari 11.1, Vaadin 7.7.13 and Valo theme. The issue does not appear in Safari 11.0.2 or 10.1.1.

**Comment by christianpoitras** [comment]
A workaround is to call focus() on any element in the page.

**Comment by Saxintosh** [comment]
Christian: Unfortunately, it doesn't work!

**Comment by christianpoitras** [comment]
I am affected by this problem since the most recent update of Safari. I use Vaadin 8.4.2 and I don't use tabs. The normally checked by default checkboxes appear unchecked on page load, but they become checked as soon as any request is send to the server - like the user clicking anywhere on the page.

When calling `focus()` on an element that is visible on the page, it seems to force the browser to send a request and update the checkboxes. This workaround may not work in Vaadin 7.X.

**Comment by Saxintosh** [comment]
It seems that you are lucky.
Now I'm using Vaadin 8.4.3 and in 3 different situations of my webApp and I've tried to call the .focus() on the component, on a label, on a button, or on the checkbox itself.
None of this worked for me.

**Comment by christianpoitras** [comment]
You may be right.
Also when I use focus(), the checkboxes do appear unchecked for a second before getting refreshed. It is better to wait for an actual solution from the Vaadin team.

**Comment by Saxintosh** [comment]
Yes, even if it seems that they are too busy. Probably with too many projects.
