### ISSUE TITLE
v7.DateField not submitted on Return

### ISSUE THREAD

**Issue by guttormvik** [vaadin/framework#10854]
This is an issue in 8.4.0 when using com.vaadin.v7.ui.DateField
It works when using the regular com.vaadin.ui.DateField.

Issue #10488 fixed this for the regular DateField, and was published in 8.4.0
Same test-case as then will show the issue, as long as you import com.vaadin.v7.ui.DateField:

The following code has a textfield, a date field and a button. The button has Enter as shortcut.
When writing something in the textfield, it is submitted when I press Enter.
When writing something in the date field, it is *not* submitted when I press Enter.
It *is* submitted if I tab out of the field before pressing Enter, or if I click the button.

``` java
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        final TextField name = new TextField();
        name.setCaption("Type your name here:");

        final DateField dateField = new DateField("Date of birth");  
        
        Button button = new Button("Click Me");
        button.setClickShortcut(KeyCode.ENTER, 0);
        button.addClickListener(e -> {
            layout.addComponent(new Label("Thanks " + name.getValue() + ", it works! Your Date of birth is: " + dateField.getValue()));
        });
        
        layout.addComponents(name, dateField, button);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by KyleRogers** [comment]
Verified this issue with Vaadin 8.3.3 and 8.6.2 and 8.6.4

This issue is IMPORTANT for us because we need to maintain larger products developed with Vaadin 7 that cannot be migrated to pure Vaadin 8 so far.
