### ISSUE TITLE
com.vaadin.util.FileTypeResolver.getIcon(..) uses non-existent theme resources in Vaadin 8

### ISSUE THREAD

**Issue by TatuLund** [vaadin/framework#10851]
The class com.vaadin.util.FileTypeResolver is mostly used as helper by FilesystemContainer, which is in compatibility package. Furthermore FileTypeResolver uses icons from Runo theme, which are not in Vaadin 8, hence producing broken icons. Vaadin Framework version:  8.3.3

**Comment by elmot** [comment]
I don't think this is a bug

**Comment by TatuLund** [comment]
> I don't think this is a bug

If there is other users for this helper than FilesystemContainer, then you are right.

In that case, the bug is that getIcon(..) uses Runo theme, and that is a bug, which should be addressed.
