### ISSUE TITLE
Copy all referenced images from base theme to reindeer and runo during build/packaging

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1086]
**Originally by @jouni**

___
Both Runo and Reindeer use generic loading indicator images from the Base theme. Reindeer also uses the shadows provided by Base.

To make each theme independent of each other, necessary images should be copied in addition to the concatenation of the stylesheets.

The whole theme build process needs review and improvements.

___
 Imported from https://dev.vaadin.com/ issue #4593

**Comment by jouni** [comment]
Won’t fix, IMo.
