### ISSUE TITLE
Grid is rendered very slowly when it contains visible row-details

### ISSUE THREAD

**Issue by lubomirmatus** [vaadin/framework#10878]
Vaadin 8.3.2, running on TomEE 7.0.4, Windows 7 x64. Browsers: Firefox 59.0.3, Chrome 66.0.3359.139.

I have grid with many rows (hundreds), data from `DataProvider`. I want to display row details for selected rows (many, maybe half of all rows). I have set the details visible using `grid.setDetailsVisible(row, true)`.

When the view with such grid is displayed, the rendering of page is very slow, the browser is stucked and warning dialog about "slow page" pops up. After a long time everything (the grid with row details) are rendered. Then you can scroll the grid.

Scrolling such grid is also slow. When you scroll down to see next rows, you can see the intermediate rendering states of details layout, like all components are sitting in the top left corner and then are moved to their positions. (Row details layout is simple `GridLayout` with ~20 `Label` texts).

It seems that grid is trying to somehow "prerender" all the row detail layouts.

It would be fine to render details for visible rows only.

**Comment by TatuLund** [comment]
In Vaadin 8.9.0 there is a big update on details row handling. It should have improved the performance as well to some extent, I would recommend to check.

**Comment by lubomirmatus** [comment]
OK, thank you. I'll check it.

**Comment by Ansku** [comment]
Rendering details rows only for the rendered rows is one of the changes introduced in 8.9.0, and there were other performance improvements as well.
