### ISSUE TITLE
VerticalLayout layouting algorithm does not take the height of empty HorizontalLayout into account

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#10881]
Vaadin 8.4.0
Chromium 65.0.3325.181 on Ubuntu 18.04
Tomcat 9.0.5

As can be seen from the screenshot, the bottom button is pushed below the screen and outside of the parent vertical layout. It seems as if the horizontal layout height has been calculated to be 0 pixels, and the layouting algorithm then allots more space to the `tree` than it deserves.

![bug](https://user-images.githubusercontent.com/254091/39619175-850bf060-4f8f-11e8-9b0f-e7b080ada345.png)

This bug is triggered by the following layout:
```kotlin
        verticalLayout {
            setSizeFull(); isMargin = false
            tree<String> {
                expandRatio = 1f
            }
            horizontalLayout()
            button {
                icon = VaadinIcons.QUESTION
            }
        }
```

**Comment by mvysny** [comment]
[vaadinbug.zip](https://github.com/vaadin/framework/files/1973713/vaadinbug.zip)
Just run `./gradlew build appRun`

**Comment by pwilkin** [comment]
Possibly related to #10185?
