### ISSUE TITLE
DateField DateResolution.Month not working porperly

### ISSUE THREAD

**Issue by xasz** [vaadin/framework#10886]
I having problems with the DateField with DateResolution set to Month.
It is not updating its values properly.
As you click on the Datefield and the popup for choosing the value opens, you can choose a month with the arrow keys and the visible value of the field changes. As soon as on i click for example on a save button and the Datefield popup is still opened, the old value is saved in the Datefield.

I am Using Vaadin 8.3.3 with Valotheme.
Here some not working example:

`			DateField field = new DateField("Choose a Date without loosing blur");
			field.setResolution(DateResolution.MONTH);
			
			Button button = new Button("Click me while Datefield month popup is still open", 
					event -> Notification.show("You will see null or the old value" + field.getValue()));`

**Comment by TatuLund** [comment]
I think this is related to https://github.com/vaadin/framework/issues/11108

**Comment by TatuLund** [comment]
Or possibly this one https://github.com/vaadin/framework/issues/11099

**Comment by mlopezFC** [comment]
I was able to reproduce this issue with the informed Vaadin version 8.3.3, but in the latest one (8.10.3) it's not reproducible anymore, so this probably was solved with the fixes of one of those issues.
It can be closed.
