### ISSUE TITLE
Grid: New line with required TextFields is not validated properly

### ISSUE THREAD

**Issue by mirkoliver** [vaadin/framework#10891]
My Grid with TextFields as editors has some required columns. When editing and leaving required fields empty, it is not possible to leave the Editor - a validation error message is shown. This is the normal behaviour.

But after adding a new line in Grid via

```
itemList.add(new MyBean());
grid.getDataProvider().refreshAll();
```
and editing one or more field but also leaving one or more required fields empty, the Editor can be left without any error message.

Only if first I add to every field a value, leave the field (remaining in Editor) and then navigate back to one or more required fields and delete their values, the Editor cannot be left any more and the validation error messages occur.

Does this have to do something with these Vaadin github issues?

[https://github.com/vaadin/framework/issues/9000](https://github.com/vaadin/framework/issues/9000)

[https://github.com/vaadin/framework/pull/10422](https://github.com/vaadin/framework/pull/10422)

I'm using Vaadin Framework version 8.4.1.

**Comment by mlopezFC** [comment]
Hi! ... I did some tests, and I see that is behaving correctly according to [Tatu's explanation](https://github.com/TatuLund/GridFastNavigation/issues/69#issuecomment-387060694) about this design decision.
