### ISSUE TITLE
The version (x) of the browser you are using is outdated and not supported

### ISSUE THREAD

**Issue by guttormvik** [vaadin/framework#10890]
If an user with an old browser version visits our application, he or she gets the error message in the title.
That is fine, but this error page has no cacheing information, so it might be cached. Not only in the user's browser, which again would be fine, but also in proxies.
We have an nginx frontend which caches this response, so as soon as one user with an old browser visits the page, it messes up for subsequent users as well.

( For some reason ctrl-F5 does not fix the issue. We have to purge the nginx cache to get around it. Not sure if this is relevant )

We are on Vaadin 8.3.0.

**Comment by Legioth** [comment]
We should either set no-cache headers, or at the very least include a `Vary: User-Agent, Accept` header.

**Comment by guttormvik** [comment]
We found out why ctrl-F5 didn't force a reload of the page; We were lacking the foolowing in our nginx.conf:
`proxy_cache_bypass  $http_cache_control;`
Main issue remains though
