### ISSUE TITLE
ComboBox closes immediately after opening

### ISSUE THREAD

**Issue by ropoman** [vaadin/framework#10915]
0. Using Firefox, Edge or Chrome
1. Go to https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box
2. Open the combobox by clicking on the down arrow
3. Close the combobox by clicking somewhere on the gray background
4. Open the combobox again and it will close immediately until you reload the page

**Comment by tsuoanttila** [comment]
Hi @ropoman and thanks for the issue. It seems that the issue does not happen if you select any value form the ComboBox. I need to take a look at the Sampler code if it is using the old  `NewItemHandler`. The symptoms of this issue are really close to the one where combobox tries to add a new value but actually doesn't, leaving it internally in a broken state.

**Comment by ropoman** [comment]
Any news on this?

**Comment by pinonpierre** [comment]
Hi,

Same issue for me

**Comment by anasmi** [comment]
Hi,

do you still experience this issue under any circumstances? I can't reproduce it in sampler anymore

**Comment by ropoman** [comment]
This seems to be fixed

**Comment by anasmi** [comment]
Thanks for the update!
