### ISSUE TITLE
TabSheet: RemoveTab in cycle, caption is remain.

### ISSUE THREAD

**Issue by Gamarnik** [vaadin/framework#10925]
Hello, 
In our project we use (Vaadin 8.4.1) tabSheet to navigate in user interface. But if we want to close all tabs with one click than components are deleted, but captions on tabs are remain. Situation repeated if tabs go beyond the frame.
 
```
closeAllTabs.addClickListener(event -> {
                    VaadinUI.getInstance().getTabs().removeAllTabs();
                }
        );

public void removeAllTabs() {
        while (getComponentCount() > 0) {
            removeTab(getTab(0));
        }
    }
```
So https://github.com/vaadin/framework/issues/10911 is already actual.

**Comment by Gamarnik** [comment]
```
class TestTabs extends Window {
        TestTabs() {
            setWidth("700px");
            setHeight("500px");
            center();
            TabsController tabsController = new TabsController();
            tabsController.setSizeFull();
            Panel panel = new Panel(tabsController);
            panel.setSizeFull();
            setContent(panel);
            setModal(true);
        }
        public void show() {
            UI.getCurrent().addWindow(this);
        }
    }
```

    class TabsController extends GridLayout {
        private HorizontalLayout buttonLayout = new HorizontalLayout();
        private Button addTab = new Button("Add tab");
        private Button allTabsClose = new Button("Close all tabs");
        private Button add10Tabs = new Button("Add 10 tabs");
        private TabSheet tabSheet = new TabSheet();

        HorizontalLayout getTabContent() {
            HorizontalLayout horizontalLayout = new HorizontalLayout();
            horizontalLayout.addComponent(new Label("Tab content"));
            return horizontalLayout;
        }

        void getTab() {
            TabSheet.Tab tab = tabSheet.addTab(getTabContent(), "Tab");
            tab.setClosable(true);
            tabSheet.setSelectedTab(tab);
        }

        TabsController () {
            super(1,2);
            addTab.addClickListener(event -> getTab());
            add10Tabs.addClickListener(event -> {
               for (int i = 0; i < 10; i++) {
                   getTab();
               }
            });
            allTabsClose.addClickListener(event -> {
                while (tabSheet.getComponentCount() > 0) tabSheet.removeTab(tabSheet.getTab(0));
            });
            buttonLayout.addComponent(addTab);
            buttonLayout.addComponent(add10Tabs);
            buttonLayout.addComponent(allTabsClose);
            addComponent(buttonLayout, 0, 0);
            tabSheet.setSizeFull();
            addComponent(tabSheet, 0 ,1);
        }
    }

**Comment by elmot** [comment]
Works on my machine
![2018-06-08_14-18-19](https://user-images.githubusercontent.com/5366945/41155533-136a18ca-6b27-11e8-9aef-d80f27e646e9.gif)

**Comment by elmot** [comment]
Please compile your code using latest Vaadin(8.4.3), ensure you are using proper widgetset, run your test with `?debug` URL parameter, check if any client-side error is shown. If there is no errors shown and the problem still exists, then open another ticket with complete example project, and all the details including browser and Vaadin version.

**Comment by krizda** [comment]
This is still actual. You need to add more tabs than view can show.
![image](https://user-images.githubusercontent.com/12607604/41475640-016d79c2-70c8-11e8-9aa6-65cf23b59fc5.png)

**Comment by elmot** [comment]
There is a workaround:
- Enable push support with`@Push` annotation
- Perform `UI.getCurrent().push();` after each tab removal.

**Comment by krizda** [comment]
UI.getCurrent().push(); works.
Thank you
