### ISSUE TITLE
Combobox does not fire onValueChangeEvent

### ISSUE THREAD

**Issue by neerup** [vaadin/framework#10926]
In Vaadin Framework 8.5.0.alpha1 combobox does not fire the onValueChangeEvent when the user selects an item in the combobox.
It work in Vaadin 8.4.x

ComboBox<String> cb = new ComboBox<>();
cb.addValueChangeListener(event -> {
  // Is not called when user selects value in combobox
});

**Comment by tsuoanttila** [comment]
Just tested with a fresh singlemodule archetype from 8.5.0.alpha1 with the following code

```
        ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("Foo", "Bar", "Baz");
        comboBox.addValueChangeListener(e -> Notification
                .show("Selected: " + e.getValue(), Type.TRAY_NOTIFICATION));
```

Seems to be working. Did you remember to recompile the widgetset after version number change?

**Comment by neerup** [comment]
Argh.... Sorry the error occurs when I set the value programatically...

**Comment by tsuoanttila** [comment]
Added a Button with ClickListener `e -> comboBox.setValue("Bar")` and notification is displayed as expected. If you have the code where the error is reproduced, please share the whole code.

**Comment by neerup** [comment]
Found the error
In 8.4.1 .setValue() always fires a SingleSelectionEvent
But in 9.5.0.alpha1 .setValue() only fires the SingleSelectionEvent when the value actually changes... 

I will change my code accordingly.
Sorry for trouble...
