### ISSUE TITLE
Grid editor tabs to uneditable fields

### ISSUE THREAD

**Issue by neerup** [vaadin/framework#10970]
When grid editor is open and not all fields are open for edit, pressing tab should move focus between the editable fields skipping the uneditable fields.

In the example below, tapping from first editable field hides the focus, tabbing again focuses the second editable field. This i very confusing for the user.

Vaadin Framework version 8.4.3

Minimal code to reproduce
```
		Grid<String[]> grid = new Grid<>();
		grid.getEditor().setEnabled(true);
		grid.getEditor().setBuffered(true);
		TextField a = new TextField();
		BindingBuilder<String[], String> aa = grid.getEditor().getBinder().forField(a);
		grid.addColumn(e -> e[0]).setCaption("A").setEditorBinding(aa.bind(e -> e[0], (row, value) -> row[0] = value));
		grid.addColumn(e -> e[1]).setCaption("B");
		TextField c = new TextField();
		BindingBuilder<String[], String> cc = grid.getEditor().getBinder().forField(c);
		grid.addColumn(e -> e[2]).setCaption("C").setEditorBinding(cc.bind(e -> e[2], (row, value) -> row[2] = value));
		grid.setItems(new String[] {"1", "2", "3"}, new String[] {"1", "2", "3"}, new String[] {"1", "2", "3"});

```

**Comment by TatuLund** [comment]
This has been implemented in [GridFastNavigation add-on](https://vaadin.com/directory/component/gridfastnavigation-add-on)
