### ISSUE TITLE
java.lang.NoClassDefFoundError: com/vaadin/v7/ui/Upload$Receiver

### ISSUE THREAD

**Issue by tstsogoo** [vaadin/framework#10979]
vaadin 8.4.3 with 

> https://vaadin.com/directory/component/easyuploads

**Comment by elmot** [comment]
This is an issue for an addon, and we here can not do anything related to that. Better to report to their repository. 
And, as far as I see, you did that already
PS. First of all, ensure if you have `vaadin-compatibility-server` dependency in your project
