### ISSUE TITLE
Method listener: getting selection and value change events 

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/framework#10993]
_From @Mi-tweber on June 20, 2018 13:11_

### Description
I love the possibility to register a listener by **java.lang.reflect.Method**, which is default functionality AbstractClientConnector:

`com.vaadin.server.AbstractClientConnector.addListener(Class<?> eventType, Object target, Method method)`

There is a problem with it regarding (Tree)Grid and item selection. Both Grid and TreeGrid use an internal selection model that also handles the events caused by selection. Since the standard SelectionModels SingleSelectionModelImpl and MultiSelectionModelImpl extend **com.vaadin.ui.components.grid.AbstractSelectionModel**, they also extend AbstractClientConnector themselves which is way up in their class hierarchy and holds an **com.vaadin.event.EventRouter** instance. 

Ergo: there are 2 EventRouters: the one of the Grid and the one of the SelectionModel. Since the selection is handled in the SelectionModel, selection events are distributed via the SelectionModel's EventRouter, not via the one of the Grid.

If you add a **com.vaadin.event.selection.SelectionListener** to a Grid, it will automatically be added to the internal SelectionModel's EventRouter. But if you add a method-based-listener to the Grid to listen for SelectionEvents, it will never get triggered, because it is added to the Grid's EventRouter.

### Expected outcome
A method-based-listener listening for SelectionEvent.class causes its method to be called when a SelectionEvent is fired.

### Actual outcome
The method is never called.

### Steps to reproduce
1) Call Grid.addListener(SelectionEvent.class, *someObject*, *someMethod*)
2) Select some Grid item
3) The method is not called

### Browsers Affected
All, this is a server-side problem.

### Suggested Fix
I don't know the architectural requirement for **com.vaadin.server.AbstractExtension** in the framework, but a possible very general fix would be that an AbstractExtension to a ClientConnector would always forward its EventRouter's events to its parent connector. Since AbstractSelectionModel is such an extension, the problem would be fixed.

A more specific fix would simply be to add a listener to the SelectionModel in Grid.setSelectionModel(GridSelectionModel<T> model) that calls Grid.fireEvent(EventObject event), at least that is how my workaround works:

````java 
public class TreeGrid<T> extends com.vaadin.ui.TreeGrid<T> {

	private static final long serialVersionUID = 1L;
	
	private Registration listenerReg;

	@Override
	protected void setSelectionModel(GridSelectionModel<T> model) {
		super.setSelectionModel(model);
		if (this.listenerReg != null) {
			this.listenerReg.remove();
		}
		this.listenerReg = model.addSelectionListener(event -> fireEvent((EventObject) event));
	}
}
`

_Copied from original issue: vaadin/vaadin-grid#1313_

**Comment by TatuLund** [comment]
I think this is somewhat addressed by https://github.com/vaadin/framework/pull/10939 in Vaadin 8.6. I.e. the correct usage of Grid as field is to use either grid.asMultiSelect() or grid.asSingleSelect().
