### ISSUE TITLE
Cannot open more than 5 browser tabs when using Long Polling / Atmosphere and Firefox or Chrome

### ISSUE THREAD

**Issue by TatuLund** [vaadin/framework#10994]
It is not possible to open more than five browser tabs when using Atmosphere Push / Long Polling with Chrome & Firefox

Chrome has limitation of keeping five http requests open at the same time. Hence, if you use Long Polling with Atmosphere Push, it is not possible to open more than five browser tabs. To overcome this limitation there is a feature in Atmosphere which allows sharing one request with Browser tabs, but it is not used in Vaadin.

- Vaadin Framework version: (e.g. 8.4.4)
- Browser version: all new Chrome  & Firefox versions

- Expected behavior: Can open more than five browser tabs

- Actual behavior: Opening of new browser tab hangs when using Chrome  & Firefox (works on Edge)

- Workaround; Use WebSockets if possible

- How to replicate: See attached test project

[multi-ui-bug-example.zip](https://github.com/vaadin/framework/files/2132223/multi-ui-bug-example.zip)

**Comment by elmot** [comment]
Possibly there might be another workaround - use several domains for the same web server.

**Comment by TatuLund** [comment]
See: https://github.com/Atmosphere/atmosphere/wiki/Sharing-connection-between-Browser%27s-windows-and-tabs

**Comment by AlexByte** [comment]
> Chrome has limitation of keeping five http requests open at the same time

Where is that written?

**Comment by harrwiss-swt** [comment]
Regarding 
> > Chrome has limitation of keeping five http requests open at the same time
> Where is that written?

More information about browser connection limitations and various workarounds can be found here:
https://stackoverflow.com/questions/18584525/server-sent-events-and-browser-limits

This page, which lists "Number of connections per hostname" may also be interesting:
http://www.browserscope.org/?category=network

**Comment by Benjoyo** [comment]
I don't see any real solution here. How can I configure Vaadin to share the connections between tabs or to use a different transport? Currently more than 5 tabs are impossible, everything just freezes, which is a terrible experience. Major dealbreaker.

**Comment by TatuLund** [comment]
> How can I configure Vaadin to share the connections between tabs or to use a different transport?

Use transport parameter in @Push annotation to configure different transport

@Push(transport = Transport.WEBSOCKET)
