### ISSUE TITLE
Vaadin 8 is throwing JS Exception on deleting a row using delete button column

### ISSUE THREAD

**Issue by sanketmore1011** [vaadin/framework#10995]
Vaadin Framework version: 8.4.3
Browser version: 67.0.3396.87
Web container name: Tomcat 8

Example
```java
Column<VRow, ?> col = this.addComponentColumn(r ->
{
	Button button = new Button(c.getIcon());
	button.setDisableOnClick(true);
	if(c.getStyles()!=null)
		button.addStyleNames(c.getStyles());
	button.setHeight(20, Unit.PIXELS);
	button.addClickListener(e ->
	{
		c.getAction().processRow(r, VTreeGrid.this);
	});
	return button;
});
```
where c is Column Configuration POJO which defines what column it is.

Scenario
When I delete multiple rows from grid and scroll down a bit and again delete row, it throws JS Exception

com.example.myapplication.widgetset.myapplication-0.js:7137 Mon Jun 25 15:08:57 GMT+530 2018 com.vaadin.client.ui.AbstractComponentConnector
SEVERE: Widget is still attached to the DOM after the connector (ButtonConnector (703)) has been unregistered. Widget was removed.

**Comment by elmot** [comment]
First note, unrelated to the bug: using components in Grid cell is quite heavyweight, there is better alternative for your case - com.vaadin.ui.renderers.ButtonRenderer. You may try to use it instead.

**Comment by mimarko** [comment]
I can confirm that bug and I think in any case (no matter how heavyweight it using components)  should be fixed.

**Comment by elmot** [comment]
@duffrohde,  did you make any pull-request related to this?

**Comment by duffrohde** [comment]
Not yet. I have a pull request that is of higher priority to me and therefore I have saved this fix for later.

**Comment by TatuLund** [comment]
Grid Renderers Collection has DeleteButtonRenderer implementation that works, i.e. is applicable workaround for this issue, also regular ButtonRenderer could be used as mentioned by elmot https://vaadin.com/directory/component/grid-renderers-collection-for-vaadin7

Also, we are working on wider fix on Escallator indexing issues. That may also fix this problem.
