### ISSUE TITLE
Grid multiselect checkbox behavior is wrong when using unbuffered editor

### ISSUE THREAD

**Issue by TatuLund** [vaadin/framework#11028]
Grid multiselect checkbox behavior is wrong and inconsistent when using unbuffered editor. Multiselection checkboxes are disabled, but the selection works when click checkbox column outside the the selection box. Furthermore there is ellipsis displayed on the edit row which should not be there.

- Vaadin Framework version (e.g. 8.4.4)

- Minimal reproducible example: trivial

- Expected behavior: Multiselection checkboxes are enabled on all rows and work normally when unbuffered editor is used

- Actual behavior: Multiselection checkboxes are disabled on rows except the editor, but the selection works when click checkbox column outside the the selection box. 

Proposals for fix

- Enable multiselection when unbuffered editor is used

or

- Add API to enable multiselection when unbuffered editor is used and fix behavior to be consistent

See: https://github.com/TatuLund/GridFastNavigation/issues/60

**Comment by ky2ninh** [comment]
I meant how do I get to the nightly builds?

**Comment by ky2ninh** [comment]
I cloned the code but do not see the fix for #11028 yet include. The last thing I see if at 06:05 today for "Serialization - update LocalDate(Time)Renderer examples with a note.

**Comment by knoobie** [comment]
If you checkout master and build it, you should be able to use this fix.

**Comment by ky2ninh** [comment]
I cloned master but I don't see the fix included yet. No commit labeled as #11028. Do you have nightly build and weekly build that I can use with Maven?

**Comment by knoobie** [comment]
You can find the latest snapshots [here](https://oss.sonatype.org/content/repositories/vaadin-snapshots/), hope that helps!

**Comment by ky2ninh** [comment]
I see snapshots for 6, 7, and 10, but not vaadin 8 under https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/vaadin/. Am I not looking at the right subdirectory?

**Comment by knoobie** [comment]
You can find them below com/vaadin - there is vaadin-server and so on.

**Comment by tsuoanttila** [comment]
The patch is available in both `8.6-SNAPSHOT` and `8.5-SNAPSHOT`, also soon in an 8.5 named build in the `vaadin-prereleases` maven repository. This change might get merged also to the next 8.4 maintenance build which is scheduled for next week.

**Comment by ky2ninh** [comment]
I incorporated 8.6-SNAPSHOT but the problem isn't fixed. 

I have a row with a checkbox. When I first clicked on the checkbox, the row is selected for edit. Only on second click that the checkbox becomes checked. Once a row is in edit mode, I can click once on any checkboxes in that row and it would become checked. This is Vaadin 8.6 Grid, with a Checkbox component being rendered using ComponentRenderer, with GridFastNavigation for inline editing, with a CheckBox field bound to the c;olumn.

This is how it looks after first click on the checkbox
![image](https://user-images.githubusercontent.com/6173892/42582598-2e61b772-84f5-11e8-98cf-c4d4d64772e6.png)

**Comment by TatuLund** [comment]
@ky2ninh the issue illustrated in your picture is different than the one described in the original description. The issue that has been fixed was concerning the row selection checkboxes, i.e. the left most column. 

The behavior you observe is more or less intentional. The first click is opening the editor (without the add-on you would need to double click) and not propagated further. Thus you need to click the checkbox second time after editor has been opened.

**Comment by ky2ninh** [comment]
Tatu, is there anyway to achieve what I need, to be able to check the checkbox on first click?

**Comment by elmot** [comment]
Have a look at https://vaadin.com/directory/component/grid-renderers-collection-for-vaadin7/2.2.10
`CheckboxRenderer`

**Comment by ky2ninh** [comment]
I tried the CheckboxRenderer but that didn't help. Tatu, is there a way for GridFastNavigation to propagate the Mouse Click event from opening the editor to select/unselect the checkbox?

**Comment by ky2ninh** [comment]
Can you see if there's a bug in GridFastNavigation. It seems that the EditorOpenEvent is being fired twice for all subsequent rows that enter into edit mode after the first row enters into edit mode. If you click outside and cancel out of edit mode, it will reset. But once you enter edit mode with one row, all subsequent rows enter into edit mode, the EditorOpenEvent will be fired twice.

Code 
private void initGridNavigation() {
		try {
			FastNavigation<CustomerDefault> navigation = new FastNavigation<CustomerDefault>(customerDefaultsGrid,
					false, true);

			navigation.addClickOutListener(event -> {
				customerDefaultsGrid.getEditor().cancel();
			});

			navigation.addEditorOpenListener(new EditorOpenListener() {

				@Override
				public void onEvent(org.vaadin.patrik.events.EditorOpenEvent event) {
					System.out.println("EditorOpenEvent column=" + event.getColumn() + "; row=" + event.getRow());

					List<CustomerDefault> customerDefaults = customerDefaultsGrid.getDataCommunicator()
							.fetchItemsWithRange(event.getRow(), 1);

					for (CustomerDefault customerDefault : customerDefaults) {
						System.out.println("\n" + customerDefault.getCustName() + " has Billing Receipts value of "
								+ customerDefault.getBillingReceipts());
					}

					CustomerDefault customerDefault = customerDefaults.get(0);

					ValueProvider<CustomerDefault, Boolean> getter = (ValueProvider<CustomerDefault, Boolean>) customerDefaultsGrid
							.getColumns().get(event.getColumn() - 1).getEditorBinding().getGetter();

					Boolean oldValue = getter.apply(customerDefault);
					Boolean newValue = !oldValue;

					System.out.print("\t Billing Receipts checkbox for " + customerDefault.getCustName()
							+ " has current value of " + oldValue + " is being changed to new value " + newValue);

					Setter<CustomerDefault, Boolean> setter = (Setter<CustomerDefault, Boolean>) customerDefaultsGrid
							.getColumns().get(event.getColumn() - 1).getEditorBinding().getSetter();
					setter.accept(customerDefault, newValue);
					customerDefaultsGrid.getDataProvider().refreshItem(customerDefault);
				}

			});

Output 
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5250 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=3

ABC 1947 5232 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5232 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=3

ABC 1947 5232 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5232 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=0

ABC 1941 5703 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5703 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=0

ABC 1941 5703 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5703 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5213 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5250 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5216 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5213 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5216 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5250 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5213 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5216 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5250 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5213 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5216 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5250 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=2

ABC 1941 5250 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5250 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1947 5216 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=1

ABC 1947 5216 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1947 5216 has current value of false is being changed to new value true
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of true
	 Billing Receipts checkbox for ABC 1941 5213 has current value of true is being changed to new value false
EditorOpenEvent column=2; row=4

ABC 1941 5213 has Billing Receipts value of false
	 Billing Receipts checkbox for ABC 1941 5213 has current value of false is being changed to new value true

**Comment by TatuLund** [comment]
@ky2ninh I can't reproduce your issue in my demo app. Could you report this issue in https://github.com/TatuLund/GridFastNavigation/issues Also same applies your feature request / question about letting the click event propagate. However that is a bit problematic, since in most cases it is not wanted. You could approach us also via commercial support channels.
