### ISSUE TITLE
 Scrollbar of the disabled vaadin.ui.Table does not scroll.

### ISSUE THREAD

**Issue by DeepikaB5** [vaadin/framework#11039]
Iam facing same issue on vaadin.ui.table. - Scrollbar of the disabled Table does not scroll.
Table is disabled so that no edits can be done but this disables the scrollbar also.
Need: When table contains large number of records, then the user may want to see those records. In order to see them the user needs to scroll down. If the scroll is disabled then the user can't see all the records.

Thus it is important that the scroll works when the table is disabled, to enable user to see all the records in the table.

VerticalLayout vl= new VerticalLayout();
vl.addStyleName("v-scrollable");
Table table = new Table();
table.addStyleName("v-scrollable");
table.setSizeFull();
vl.addComponent(table);
vl.setSizeFull();
vl.setExpandRatio(table, 1.0f);
...
table.setEditable(false);

Please suggest how to make scrollbar enabled for disabled table.

- Vaadin Framework version: 6.7.6
- Browser version:  Google chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by tsuoanttila** [comment]
Have you if any recent version of Vaadin would bring any help to your issue? The most recent version of each major Vaadin versions are:
- Vaadin 6: `6.8.18`
- Vaadin 7: `7.7.13`
- Vaadin 8: `8.4.5`
- Vaadin 10: `10.0.1`

I'd also like to remind you that the official support for Vaadin 6 has [ended](https://vaadin.com/blog/vaadin-framework-6-is-becoming-end-of-life-now-what-) in February, 2017.

**Comment by DeepikaB5** [comment]
I dont think its version related but framework usability issue. Can you please assist?
Also upgrading version is not possible currently.

**Comment by tsuoanttila** [comment]
The newer versions of the framework contain updates to the usability of the components, and the whole `Table` has already been replaced by the `Grid`, that has all necessary configurations customise it as much as needed.

**Comment by DeepikaB5** [comment]
Are you saying it is not possible in Vaadin 6? Is there a way/workaround to enable scrollbar on disabled table?

**Comment by elmot** [comment]
We do not support Vaadin 6 anymore.
I'd recommend you to use actual version of Vaadin, most probably 8 in your case, and also replace your `Table` with `Grid`.
If you have experienced similar problems with Vaadin 8, please open another ticket.

If you want to use latest web technologies, please use [Vaadin 10](https://vaadin.com/start#vaadin10) 
If you have experienced similar any problems with Vaadin 10, please open a ticket [here](https://github.com/vaadin/flow/issues).

**Comment by break45** [comment]
@DeepikaB5 if you are working for a company, we can still provide commercial support for the discontinued Vaadin 6 version, and/or help you with the migration to Vaadin 8 or Vaadin 10 which are supported until 2022 and 2023 respectively.

If you are interested, you can get in touch with me --> olli.murto (at) vaadin.com

**Comment by DeepikaB5** [comment]
I resolved this issue by enabling the table and disabling all the components within the table.
