### ISSUE TITLE
Empty Required ComboBox seems to be valid

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11049]
Hi,

On Vaadin 8.4.1:

        Binder<AtomicReference<String>> binder = new Binder<>();

        ComboBox<String> comboBox = new ComboBox<>("ComboBox");

        ListDataProvider<String> dataProvider = new ListDataProvider<>(new ArrayList<>(Arrays.asList("one", "two", "three")));
        comboBox.setDataProvider(dataProvider);

        comboBox.setEmptySelectionAllowed(false);
        comboBox.setNewItemProvider(value -> {
            dataProvider.getItems().add(value);
            dataProvider.refreshAll();
            return Optional.of(value);
        });
        binder.forField(comboBox)
                .asRequired("required")
                .bind(AtomicReference::get, AtomicReference::set);
        mainLayout.addComponent(comboBox);

        Button button = new Button("Submit");
        button.addClickListener(event1 -> binder.validate());
        mainLayout.addComponent(button);

To reproduce the issue:
- Click on Submit => The ComboBox become in error because is required
- Choose "one" item
- Click on Submit => The ComboBox is now valid
- Clear the field by pressing backspace 3 times
- The field is empty but shouldn't because EmptySelectionAllowed is not allowed
- Click on Submit => The ComboBox is still valid!

Thanks,

**Comment by anasmi** [comment]
Maybe you can use it as a workaround in a meanwhile.
Removing ```comboBox.setEmptySelectionAllowed(false);``` makes validations work. (Through, in this case you can choose empty value, on the other hand)
