### ISSUE TITLE
Grid and TreeGrid render rows on top of each other while being resized

### ISSUE THREAD

**Issue by mlindfors** [vaadin/framework#11044]
Seems to be an older issue, but is still happening with Vaadin 8.4.5:

When you first scroll to the bottom of a grid and then resize it by dragging, something breaks with the indexing and it renders two rows on top of each other. It's easiest to reproduce by putting a Grid inside a VerticalSplitPanel, but seems to be happening just as well by resizing the whole browser window with a single Grid instance in it. The exact same thing happens also with a TreeGrid when it's been expanded and scrolled to the bottom.

Steps to reproduce with the MyUI example UI below:
1. Scroll the upper grid to the bottom so that you can see the 100th row
2. Drag the split bar up so that the last item visible is number 94
3. Slowly drag the split bar down, and see that the row below 94 is now 96. With any luck you can actually see the row 96 being put on top of row 95.

Scrolling up and then back down fixes the situation.

The expected behaviour is for Grid to keep the rows properly rendered even while resizing.

Here's the sample UI, should be a straight drop in for a single module Vaadin archetype project, and below it a screenshot showing the issue in effect:
```
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        layout.setSizeFull();
        setContent(layout);

        Grid<TestBean> grid1 = buildGrid();
        Grid<TestBean> grid2 = buildGrid();
        
        VerticalSplitPanel split = new VerticalSplitPanel(grid1, grid2);
        split.setSizeFull();
        
        layout.addComponent(split);
        layout.setExpandRatio(split, 1);
    }

    private Grid<TestBean> buildGrid() {
        Grid<TestBean> grid = new Grid<>(TestBean.class);
        grid.setSizeFull();
        grid.getColumn("value").setHidable(true).setHidden(true);
        TestBean folder = new TestBean(true);
        List<TestBean> list = new ArrayList<>();
        for (int i = 1; i <= 100; i++) {
        	list.add(new TestBean(false, i + " new item " + (i * 42)));
        }
        grid.setItems(list);
        return grid;
    }
    
    public class TestBean {
        private String name = "name";
        private String value = "value";
        private boolean folder = false;

        public TestBean(boolean inFolder) {
            folder = inFolder;
        }

        public TestBean(boolean inFolder, String inName) {
            folder = inFolder;
            name = inName;
        }

        public String getName() {
            return name;
        }

        public void setName(String inName) {
            name = inName;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String inValue) {
            value = inValue;
        }

        public void setFolder(boolean inFolder) {
            folder = inFolder;
        }

        public boolean isFolder() {
            return folder;
        }
        
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

<img width="894" alt="screen shot 2018-07-12 at 11 24 06" src="https://user-images.githubusercontent.com/19856964/42621380-4da5c93a-85c6-11e8-8e23-4ad31ada780e.png">

**Comment by sirbris** [comment]
Happens less often now but sill occurs sometimes (8.5.1)

**Comment by mlindfors** [comment]
> Happens less often now but sill occurs sometimes (8.5.1)

Just out of curiosity: does the issue happen in 8.5.1 in the exact same circumstance depicted in this ticket i.e. scroll to the bottom, shrink the grid, then enlarge it again, at which point two rows are put on top of each other? Or is there some other sequence which causes this to happen?

I'm asking this, since there's an upcoming fix which actually rectifies Escalator's indexing in the scenario depicted above, and which should fix the issue once and for all. That fix is very, very specific, though, so if something similar is happening in some other scenario, then the indexing most probably is failing in some other branch of the logic handling the adding and removing of Escalator row slots. In that case I suspect a new issue needs to be created.

**Comment by sirbris** [comment]
Can still be reproduced in Vaadin 8.6.1
![rendering _data](https://user-images.githubusercontent.com/664179/49087513-7db6ab00-f257-11e8-93f5-0a3a2aee0cbc.png)

**Comment by ZheSun88** [comment]
Hi @sirbris , There will be a new maintenance release scheduled today with some fix related to the Escalator. Could you verify with that after it is available? And if this bug is still reproducible, please create a new ticket instead of comment here, which is hard to trace. Thanks
