### ISSUE TITLE
Trying to change value in ColorPicker

### ISSUE THREAD

**Issue by yoursnowyfriendleo** [vaadin/framework#11045]
Hi there,
when trying to change HEX value in ColorPicker component, i.e. changing the current HEX value, it always re-write the value with current (#ffffff), not new value.
The only way to change a value is to select all text in a textfield (including #) and pasting new value (including #), e.g. pasting '#123456'.
Using latest Firefox, Vaadin 8.1.7
Cheers

**Comment by tsuoanttila** [comment]
Looks like a duplicate of https://github.com/vaadin/framework/issues/10802 fixed in `8.4.0`. Please test with a more recent version of Vaadin 8 and if you have further issues with the ColorPicker, please open a new ticket.

**Comment by yoursnowyfriendleo** [comment]
It is a duplicate, indeed. Thanks.
