### ISSUE TITLE
Update Supported Browser / Application Server in Release Notes

### ISSUE THREAD

**Issue by knoobie** [vaadin/framework#11050]
While reading the [latest release notes](https://vaadin.com/download/release/8.4/8.4.5/release-notes.html) I noticed that the supported **application servers** and **desktop browsers** are kinda outdated. 

Are this really the currently supported versions, or are these not updated?

For example, missing latest versions (as of 15.07.2018):

**Application Servers**:
- Apache Tomcat 8.5 and 9
- JBoss EAP 7 
- Wildfly 12 and 13
- Glassfish 5

**Desktop Browsers**:
- Mozilla Firefox (latest version, currently **61**)
- Mozilla Firefox ESR (latest version, currently **60** ESR)
- Internet Explorer 11, Edge (latest version) _(always valid :+1: )_
- Safari 9+ _(always valid :+1: )_
- Google Chrome (latest version, currently 67)

**Comment by tsuoanttila** [comment]
The evergreen browsers are a bit tricky to keep track of and remember to update the release notes every time something updates. I'll think of a better way to mention them. 

For JBoss EAP 7, Wildfly 12 and 13, and Glassfish 5 I think we do not have an integration test for to make sure it actually works. It _should_ work, but not tested. 

The tomcat versions mentioned are tested as part of testing the FW itself, so could just add them.

**Comment by knoobie** [comment]
I think you can go with 54+ or so, like you did with Safari. That would make it easier for you. You normally test against the latest versions with your screenshot tests. So I don't think that this would do any harm. 

It's a little bit harder for the application servers. There should be integration tests, like you mentioned. You can use this ticket as starting point if you find some time to update the integration tests.

**Comment by tsuoanttila** [comment]
Closing this ticket. Biggest part of it is already taken care of with #11062 and goes into release notes of 8.5.0. Opened new tickets for Glassfish (#11076) and JBoss EAP (#11077).
