### ISSUE TITLE
String-to-UUID Converter.

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/framework#11051]
[This issue parallels one posted to Vaadin Flow 10, [Issue # 4400](https://github.com/vaadin/flow/issues/4400).]

Vaadin 8 Framework offers several handy implementations of [`Converter`](https://vaadin.com/download/release/8.4/8.4.5/docs/api/com/vaadin/data/Converter.html) such as `StringToBooleanConverter` and `StringToIntegerConverter`. 

I suggest adding another for the common type [`java.util.UUID`](https://docs.oracle.com/javase/10/docs/api/java/util/UUID.html) for [Universally unique identifier (UUID)](https://en.wikipedia.org/wiki/Universally_unique_identifier
) values. UUID values are common in enterprise apps for generating identifiers without needing a central registration authority. 

The 128 bits of a UUID are canonically presented as five groups of hexadecimal digits separated by a hyphen, such as `ab664df2-8859-11e8-9a94-a6cf71072f73`, as discussed [in Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), the [`java.util.UUID::toString`](https://docs.oracle.com/javase/10/docs/api/java/util/UUID.html#toString()) JavaDoc, and the [RFC 4122](https://tools.ietf.org/html/rfc4122) spec.

The implementation is utterly simple, with only two core lines of code:

    String s = myUuid.toString() ;

and 

    UUID myUuid = UUID.fromString( s ) ;

Attached is a single _StringToUuidConverter.java.txt_ file, my take on an implementation. (GitHub would not accept .java, so I appended .txt to the file name.)

[StringToUuidConverter.java.txt](https://github.com/vaadin/framework/files/2195959/StringToUuidConverter.java.txt)

**Comment by knoobie** [comment]
You can create a Pull Request with your changes easily with the Github UI (if you don't wanna checkout the whole project locally).

See: https://github.com/vaadin/framework/tree/master/server/src/main/java/com/vaadin/data/converter and click on "Create new file". Github is going to guide you through the process.

**Comment by elmot** [comment]
A good thing to make your own addon

**Comment by basil-bourque** [comment]
> You can create a Pull Request with your changes easily with the Github UI (if you don't wanna checkout the whole project locally).
> 
> See: https://github.com/vaadin/framework/tree/master/server/src/main/java/com/vaadin/data/converter and click on "Create new file". Github is going to guide you through the process.

Thanks for suggesting that. I gave it a try, my very first Pull Request:
https://github.com/vaadin/framework/pull/11387
