### ISSUE TITLE
ComboBox Popup floats along with mouse scroll when used in Sub-Window

### ISSUE THREAD

**Issue by amanver16** [vaadin/framework#11052]
Hi there,
I am facing this issue while using ComboBox component on top of Sub-Window component. The popup of combo box scrolls along with the Mouse Scroll. I know this issue has been reported earlier and was fixed in later versions of vaadin. But I am using vaadin compatibility combo box component. So this issue still persists. I guess the fix was not applied to Compatibility Server/Client Jars. 
Note : This problem only occurs while combo box is used on window component. It works fine on views. 
I am using,

- Vaadin-client/server

-  version : 8.4.5

- vaadin-compatibility-server/client : version : 8.4.5

- browser : Chrome 61 or Above

- Java : 8

- Maven : 3.5

 
combo box component is vaadin-compatibility component i.e. v7 component (It's the requirement, can't change it to normal component).

**Comment by anasmi** [comment]
Closing as #11055 was merged to the master and should address the problem.
