### ISSUE TITLE
ComboBox: select empty item does not invoke bean's setter

### ISSUE THREAD

**Issue by andreika63** [vaadin/framework#11071]
- Vaadin Framework version 8.4.5
- Browser version Chrome 66.0.3359.139 
- Web container name and version SpringBoot 1.5.2.RELEASE
- Description of the bug
I'm using ComboBox in my form with Binder and when I select empty (first) value in browser, setter method on my bean does not invoked. May be this is a binder bug....

**Comment by anasmi** [comment]
Are you using _setBean_ to bind the properties? (writeBean doesn't update fields automatically). If this is the case, could you check with the 8.6-SNAPSHOT version if problem is still reproducible? 

And if still there, could you, please, provide the example to reproduce the problem?

**Comment by andreika63** [comment]
sorry, I was wrong
