### ISSUE TITLE
Grid infinite scroll hindered by DetailsManagerConnector

### ISSUE THREAD

**Issue by petrixh** [vaadin/framework#11098]
While working on a customer project, we noticed that the grid starts to slow down somewhere between 100k and 1M rows even when proper lazy loading is done. At 10M rows the browser actually freezes from time to time while scrolling and at 100M rows Chrome starts asking if the user wants to force quit the tab.

Tracked this down to the DetailsManagerConnector#refreshDetailsVisibility()
there is a for-loop that loops though the entire dataSource.size() (not just the visible rows) and looks for detail rows (probably tries to hide/show them). In our case, we don't need the details row, so the workaround (below) will probably do short term, however this should still be addressed in the FW. 

Steps to reproduce (or use included example project) : 
1) Create a grid with a simple lazy loading data provider
2) Start increasing the size of the container (or just set it to 10 000 000)
3) Navigate to your app and wait for the UI to load
4) Try to scroll the grid, it'll be quite jerky..

Workaround: 
The DetailsManagerConnector seems to be the cause, fortunately if you don't need the details row, you can remove the extension and happily scroll through your infinite grid.

```
grid.getExtensions().stream().filter(e -> e instanceof DetailsManager)
				.collect(Collectors.toList()).stream().forEach(detailsManager -> grid.removeExtension(detailsManager));
```
Vaadin FW: 8.3.3 and 8.5.0
Browser: Latest Chrome on OS X
Container: Tomcat

Expected: You should be able to scroll until numerics start to overflow somewhere :P 

If it's hard to fix otherwise, could we change the extension so that it's only added to the grid if a details row generator is added? 

[gridscroll.zip](https://github.com/vaadin/framework/files/2247956/gridscroll.zip)

**Comment by TatuLund** [comment]
Is the observation of the slowed down performance with details row duplicate of this https://github.com/vaadin/framework/issues/10878 ?

**Comment by TatuLund** [comment]
Also your observation that you have had success beyond million rows is interesting. Previously we have seen that on Chrome scrolling stops working on ~800K rows. This requires more investigation, might be that newer version of Chrome allows taller divs or something like that. See: https://github.com/vaadin/framework/issues/6290

**Comment by petrixh** [comment]
#10878 could be related.. the problem in this case is probably the for-loop that will "do something" to each of the details rows for each row in the grid (100 rows 50 details rows probably ends up doing 5000 updates of the 50 details rows).

#6290 While I have to confess that I didn't count the rows it does appear to be working based on my quick tests... I'll try to remember to retest and update here if it doesn't work... However, we are using chrome, and IE does have a limit of 2 something million pixels for the height of a div (stumbled on that about 1-2 years ago with the good old Vaadin table)... However, I thought the grid used the escalator pattern and a custom scroller exactly to address that (I could be wrong) ?

**Comment by knoobie** [comment]
> If it's hard to fix otherwise, could we change the extension so that it's only added to the grid if a details row generator is added

+1
