### ISSUE TITLE
Vaadin 7 Documentation Error

### ISSUE THREAD

**Issue by tamasmucs** [vaadin/framework#11095]
I think there a mistake in your v7 documentation in _converter factory_ section.
https://vaadin.com/docs/v7/framework/datamodel/datamodel-properties.html

Doc says that the ConverterFactory instance can be set by Application.getCurrentApplication().setConverterFactory, however (v 7.7.5) I believe that should be UI.getSession().setConverterFactory(...)

**Comment by anasmi** [comment]
Hi,

thanks for letting us know : ) 

You are indeed right, the code there was from Vaadin 6 and should be updated

**Comment by anasmi** [comment]
The pull request addressing the issue was merged, so closing it.
