### ISSUE TITLE
TwinColSelect right column caption misaligned

### ISSUE THREAD

**Issue by loehra** [vaadin/framework#11106]
As depicted in attached screenshot the right caption of a TwinColSelect is not aligned properly with the left edge of the right column. It seems that this only happens, if there is no global caption set.

![screenshot from 2018-08-08 07-24-04](https://user-images.githubusercontent.com/42197577/43817873-13c66cc6-9adc-11e8-8508-7198c24c090f.png)

- Vaadin Framework version (e.g. 8.4.1): 
- Browser version: Chrome 68.0.3440.75
- Web container name and version: Spring Boot web application
- Minimal reproducible example:
```
        TwinColSelect<Position> mySelect = new TwinColSelect<>();
        mySelect.setLeftColumnCaption("Available Positions");
        mySelect.setRightColumnCaption("Chosen Positions");
```

**Comment by TatuLund** [comment]
As a workaround you could try the following style in your theme (maybe !important needed):

```
.v-select-twincol-caption-right {
    width: 11.3em;
}

```
