### ISSUE TITLE
DateField ValueChange does not change value in same week

### ISSUE THREAD

**Issue by Vilkaz** [vaadin/framework#11111]
I see many different Datefield bugs here, i did not found exact mine so i post a new Issue.

- Vaadin Framework version (e.g. 8.5.1)
- Browser version : Chrome 68.0.3440.106  (64-Bit)
- Spring-boot 2
- Description of the bug

Businesslogic : The Date always has to be set on sunday. Same Week but always sunday
1: Select NOT a sunday in different week - > The Datefield sets Date on sunday
2: Click on the Show Datefield Value -> the correct Date will be shown
3: Select NOT a Sunday in same Week as currently selected- > the Datefield does not sets the Date on sunday.
4: Click on the Show Datefield Value -> the sunday of the selected week will will be show
This means, the Value of Datefield is different, then the value on the Screen. The bug only works, if you stay in same week!
If you change the week, the correct value will be displayed.

- Minimal reproducible example

https://github.com/Vilkaz/VaadinBugDatefieldValue/blob/master/src/main/java/de/vilkas/vaadin/DatefieldBug/StartView.java

```
  DateField dateField = new DateField();
        dateField.addValueChangeListener(
            event ->
                dateField.setValue(event.getValue().with(TemporalAdjusters.nextOrSame(DayOfWeek.SUNDAY)))
        );
  setContent(dateField);
```

- Expected behavior
After the ValueChangeEvent changes the value, the DateField on screen should be updated. Like it works after you change value in different Week.
- Actual behavior
Only changes Value, if the week is different

[Demo on Heroku](https://vaadinbugdatefield.herokuapp.com/)

**Comment by KatriHaapalinna** [comment]
Hi, could you check if this is reproducible in the latest version (8.7.1)? The behaviour is present in 8.5.1 but not in 8.7.1 with your example.
