### ISSUE TITLE
Read Only CheckBoxGroup animates options clicking

### ISSUE THREAD

**Issue by glebfox** [vaadin/framework#11113]
### Environment
- Vaadin Framework version: 8.5.1
- Browser version: Google Chrome 68.0.3440.106

### Description of the bug

If clicking on options when CheckBoxGroup is **read only**, then options change their color, i.e. animate clicks on them.

### Minimal reproducible example

1. Go to https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/check-box-group
2. Set **Read Only** to `true`

### Expected behavior

Options do not respond to a click.

### Actual behavior

http://g.recordit.co/nN4PJ3R6pL.gif

**Comment by anasmi** [comment]
It looks like span tag for v-checkbox is missing "**v-readonly**" style name. At least, adding it in the Chrome DevTools fixes the issue

**Comment by glebfox** [comment]
Hi, 

The issue still reproduces, except the animation of clicking. It seems that a span tag for v-checkbox is missing `v-disabled` style name.

![image](https://user-images.githubusercontent.com/6077149/51040800-dc4ea300-15d1-11e9-8ab3-06045d46d3d5.png)

**Comment by ZheSun88** [comment]
please create another ticket for the issue, instead of commenting in a closed one. 
which issue you are referring to, it looks this ticket is the addressing the animation issue, and it has been fixed.

**Comment by anasmi** [comment]
@glebfox Do you mean that option, which is set to be read-only misses the 'v-disabled' style name?
If it's so, then it's an expected behavior. (Otherwise, why would you like to use read-only, if you expecting it to behave the same way as disabled? : ))
(If it's not the case, could you, please, create a new issue describing the problem, as @ZheSun88  has noticed, as the origin one is already closed by pr)

**Comment by glebfox** [comment]
@anasmi @ZheSun88 thank you for your answers and sorry for an unclear description of the issue. No need for a new one.

**Comment by anasmi** [comment]
@glebfox No problem! We are here to help and thank you for contributing and asking :)
