### ISSUE TITLE
GridRowDragger does not check source in handleDrop

### ISSUE THREAD

**Issue by hveini** [vaadin/framework#11125]
- Vaadin Framework version: 8.5.1

- Description of the bug:
When there are multiple Grids with each having own GridRowDragger in same UI, the Drop events affect others.
This is related to bug https://github.com/vaadin/framework/issues/10697

- Minimal reproducible example

Have two grids and they GridRowDraggers:

(this is in jRuby)
```
class OneColumnGrid <  com.vaadin.ui.Grid
    def initialize items
        setDataProvider(com.vaadin.data.provider.ListDataProvider.new(java.util.ArrayList.new(items)))
        @column=self.addColumn( com.vaadin.data.ValueProvider.impl do |meth,val|
            val
        end
        )
        @column.setSortable false
        @gridRowDragger=com.vaadin.ui.components.grid.GridRowDragger.new self
    end
end
.
.
.
gridA=OneColumnGrid.new ['one','two',three']
gridB=OneColumnGrid.new ['alfa','beta','gamma']
addComponent gridA,gridB

````
- Expected behavior
1) drag item(s) from gridA to gridB
  no change in gridA nor in gridB
2) drag item(s) from gridB to gridA
  no change in gridA nor in gridB

- Actual behavior
1) drag item(s) from gridA to gridB
  no change in gridA nor in gridB
2) drag item(s) from gridB to gridA
  The items selected in 1. are dropped to gridA 

I got this fixed, by extending GridRowDragger and checking the source in handleDrop:
(this is in jRuby)
```
class MyGridDragger < com.vaadin.ui.components.grid.GridRowDragger
    alias_method :parent_handleDrop, :handleDrop
    def initialize sGrid,tGrid=nil
        @sGrid=sGrid
        if tGrid.nil?
            super(@sGrid)
        else
            super(@sGrid,tGrid)
        end
    end

    def handleDrop event
        if( event.getDragSourceComponent.isPresent &&
           event.getDragSourceComponent.get==@sGrid )
             parent_handleDrop event
        end
    end
end
```

**Comment by mlopezFC** [comment]
Hi!
I wasn't able to reproduce this issue with Vaadin 8.5.1.
I tried with the following code, that I think it could be the java version of the code provided for reproducing it, but dragging items from one grid to the other never ended with dropping items successfully:

```
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final HorizontalLayout layout = new HorizontalLayout();
        
        Grid<String> grid1 = new Grid<>();
        grid1.setItems("one","two","three");
        grid1.addColumn(item->item).setSortable(false);
        new GridRowDragger<>(grid1);
        
        Grid<String> grid2 = new Grid<>();
        grid2.setItems("alpha","betta","gamma");
        grid2.addColumn(item->item).setSortable(false);
        new GridRowDragger<>(grid2);
        
        layout.addComponents(grid1,grid2);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by TatuLund** [comment]
@mlopezFC "I tried with the following code, that I think it could be the java version of the code provided for reproducing it, but dragging items from one grid to the other never ended with dropping items successfully" Did this later issue happen also with Vaadin 8.10.5 ?

**Comment by mlopezFC** [comment]
I've just tried and the problem is **not** reproducible in latest version (8.10.5)
