### ISSUE TITLE
IE 11 font-icons not rendered due to head meta tag http-equiv=X-UA-Compatible not on first position

### ISSUE THREAD

**Issue by gerald24** [vaadin/framework#11129]
With Vaadin 8.3+ one customer had an issue with no font-icon was rendered on IE 11/Windows 7 because the head meta tag for http-equiv=X-UA-Compatible was not the first child element.

Our solution for this was moving this meta tag on first position (see also https://stackoverflow.com/a/28490514/2867179)

Workaround in the code:
adding a BootstrapListener to the session which moves the meta tag on first position:

```
     getService().addSessionInitListener(event -> {
            event.getSession().addBootstrapListener(new BootstrapListener() {
                @Override
                public void modifyBootstrapFragment(final BootstrapFragmentResponse response) {
                }

                @Override
                public void modifyBootstrapPage(final BootstrapPageResponse response) {
                    ensureIeCompatibleMetaTagFirstPosition(response.getDocument().head());

                }
            });
        });
```

```
    private static void ensureIeCompatibleMetaTagFirstPosition(final Element head) {
        for (int i = 0; i < head.childNodeSize(); i++) {
            Element child = head.child(i);
            if ("meta".equals(child.tagName()) && "X-UA-Compatible".equals(child.attr("http-equiv"))) {
                head.insertChildren(0, child);
                return;
            }
        }
    }
```

**Comment by TatuLund** [comment]
This is a known nuisance, since some components rely on FontAwesome fonts, like CheckBox, etc. thus reported e.g. here https://github.com/vaadin/framework/issues/10792

And here https://github.com/vaadin/framework/issues/5361

**Comment by TatuLund** [comment]
See workaround at https://github.com/vaadin/framework/issues/10792
