### ISSUE TITLE
ComboBox returns null with Preselected Value

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/framework#11157]
@FirstWithThisName commented on [Mon Sep 03 2018](https://github.com/vaadin/vaadin-combo-box-flow/issues/123)

# Vaadin ComboBox returns null

[![the shown combobox][1]][1]

there I get the preselected value:

     this.binder.forField(this.cmbxStockArea).withValidator((t) -> {

            if (cmbxStockArea.getValue().equals("")) {
                return false;
            }
            return cmbxStockArea.getValue() != null;
        }, "es muss ein Lagerplatz gewählt werden").bind(Stock::getStockArea, Stock::setStockArea);

Stock#getStockArea returns just a String.  
There I get the the selections.

        this.stockPresenter.getStockAreaSelection().getCmbxSelectedStockArea().setDataProvider(DataProvider.fromStream(StreamSupport.stream(f.spliterator(), false)));

The Validator is working correctly, I printed out getCmbxSelectedStockArea().getValue() and it is null.

After selecting the preselection again by hand everything works fine.

I found this https://github.com/vaadin/vaadin-combo-box-flow/issues/85, but it should be fixed.  

I am using Vaadin 8.

[original stackoverflow question](https://stackoverflow.com/questions/51860509/vaadin-combobox-returns-null?noredirect=1#comment90874698_51860509)

  [1]: https://i.stack.imgur.com/N09lf.png

---

@ZheSun88 commented on [Mon Sep 03 2018](https://github.com/vaadin/vaadin-combo-box-flow/issues/123#issuecomment-418081980)

Hi, Thanks for reporting the issue, Could you let me know which version of platform and  `comboBox`  that you are using? from the original question on stackoverflow, you mentioned that you are using vaadin 8, is that correct??

---

@FirstWithThisName commented on [Mon Sep 03 2018](https://github.com/vaadin/vaadin-combo-box-flow/issues/123#issuecomment-418082641)

Yes, this is correct, i am using vaadin 8.  
How do I figure out the version of the ComoBox I am using?

---

@ZheSun88 commented on [Mon Sep 03 2018](https://github.com/vaadin/vaadin-combo-box-flow/issues/123#issuecomment-418083768)

Okay, this repository is for vaadin flow, which starts with Vaadin 10. In this case, i am going to move this issue to https://github.com/vaadin/framework  and you will get proper help there.

**Comment by FirstWithThisName** [comment]
I think it is a problem of the binder.

``` java
stockPresenter.getBinder().readBean(this.stock);  
// This is a workaround.  
stockPresenter.getCmbxStockArea().setValue(stock.getStockArea());
```

this works.
