### ISSUE TITLE
VCustomLayout could inject the location string as an additional stylename for the component in the location

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1117]
**Originally by @jouni**

___
Having the location name as an additional style name for the contained widget in that location slot would reduce the need to use specify a class name for the location element itself.

This would also simplify the CSS and Java code, when the Java coder wouldn't have to add custom stylenames for the components to make the styling easier, and it the CSS coder wouldn't have to write too complex selectors to match the widgets (e.g. `.location-element-class .v-label`).

___
 Imported from https://dev.vaadin.com/ issue #5078

**Comment by jouni** [comment]
Not a real issue, I would say. Please close.
