### ISSUE TITLE
DataProvider only loads 99 entries out of 600.

### ISSUE THREAD

**Issue by tamimmahmudkhan** [vaadin/framework#11175]
I am using Vaadin8. My problem is with the setDataProvider() lambda for the grid component not working as intended. I have a database with 600 entries atm and whenever I try to use the dataProvider lambda shown in your youtube tutorial my grid loads with only 99 entities and a lot of empty cells. I have a selection listener running which is what I used to find out the number of the last entity. When I was using an h2 database the lambda would run and show a notification(intended) but then the page would try to reload and fail as indicated by the flashing blue loading bar on the top of the browser window. This problem persists in Firefox Quantam and Chrome. I have a [link](https://github.com/tamimmahmudkhan/company-management/tree/vaadin-bug-report) to the branch github repo of the bug. Using setItems() still works as intended and I can see all 600 entries. That implementation is on my master branch.

**Comment by tamimmahmudkhan** [comment]
How do I retrieve only the sublist directly from the database? There is no method for that. The only methods are findAll() or findByID().

**Comment by Zixxl** [comment]
There is a blog entry for lazy loading in Vaadin 8:
[https://vaadin.com/blog/lazy-loading-with-vaadin-8](https://github.com/alejandro-du/lazy-loading-spring-demo)

There is also a link for an implementation in spring:
[https://github.com/alejandro-du/lazy-loading-spring-demo](https://github.com/alejandro-du/lazy-loading-spring-demo)
