### ISSUE TITLE
Help detect memory leaks caused by growing RPC queue for detached components

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#11184]
If a detached component for some reason receives external updates, and those updates cause new RPC calls to be enqueued, then the queue will just keep growing longer and longer since it's only purged for attached components. This kind of memory leak can be very hard to diagnose since one must understand both the structure of the application and the structure of Vaadin's RPC mechanism to understand the root cause based on a heap dump.

It would be possible to help application developers discover and understand such situations by logging a warning if the RPC queue of a detached component grows over some threshold value. There might still be specific component types where the queue should be allowed to grow long without triggering redundant warnings, so it would be recommendable to have a `protected` method that the component can override to use a non-default threshold.

To make it easier to automatically test for this kind of situation, it might also be good if the default threshold could be reduced and the overrun behaviour could be changed globally based on e.g. a system parameter.

**Comment by knoobie** [comment]
Are you referring to these classes? We are currently looking for a memory leak. 
 
![grafik](https://user-images.githubusercontent.com/3968629/49377227-daa7da80-f709-11e8-8b6a-cdc34d52733d.png)
