### ISSUE TITLE
Grid detailsGenerator  renderer issue

### ISSUE THREAD

**Issue by querryjk** [vaadin/framework#11185]
Vaadin version 8.5.1
When I change the size of the browser or when I change the active tab and the details of the grid are open, the details of the grid stop working correctly until the component is re-attached

In Vaadin version 8.4.4 work ok.

![imagen1](https://user-images.githubusercontent.com/32563663/45485800-2bd2ae80-b759-11e8-88c7-3a3c6e2adcd9.jpg)

![imagen2](https://user-images.githubusercontent.com/32563663/45485799-2bd2ae80-b759-11e8-846d-cd32888838d6.jpg)

![image](https://user-images.githubusercontent.com/32563663/45486033-f8445400-b759-11e8-99d6-5ffcd288c126.png)

    public TestView() {
	    Grid<Pojo> grid = new Grid<>();
	    grid.setSizeFull();
	    
        Column<Pojo, String> col0 = grid.addColumn(s -> {
           return "col0";
       }).setCaption("col0").setExpandRatio(1);
        
        Column<Pojo, String> col1 = grid.addColumn(s -> {
           return "col1";
       }).setCaption("col1").setExpandRatio(1);
        
        grid.setItems(new Pojo(), new Pojo(), new Pojo());
      
        grid.setDetailsGenerator(t -> {
        	Label l1=new Label("label1");
        	Label l2 =new Label("label2");
        	
			VerticalLayout vertical= new VerticalLayout(l1,l2);
			vertical.addStyleName("red");			
			return vertical;
		});
        
        grid.addItemClickListener(e->{
        	grid.setDetailsVisible(e.getItem(), !grid.isDetailsVisible(e.getItem()));
        });
        
        addComponents(grid);
    }
    class Pojo {
       String col0, col1, col3;

	public String getCol0() {
		return col0;
	}

	public void setCol0(String col0) {
		this.col0 = col0;
	}

	public String getCol1() {
		return col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

	public String getCol3() {
		return col3;
	}

	public void setCol3(String col3) {
		this.col3 = col3;
	}
      
    }

**Comment by strxetics** [comment]
i have the same problem.

**Comment by TatuLund** [comment]
Closed as duplicate to #11139
