### ISSUE TITLE
Draggable TextField are not editable in IE

### ISSUE THREAD

**Issue by sarahfuchs** [vaadin/framework#11202]
- Vaadin Framework version 8.4.5
- Browser version InternetExplorer 11, exact Version number: 11.165.17134.0
- Web container name and version: Apache Tomcat Version 9.0.8
- Description of the bug:
InternetExplorer: TextField ignores all input if its marked as draggable
Other browsers work. TextFields not marked as draggable works in IE
- Minimal reproducible example: 
TextField tf = new TextField();
DragSourceExtension<AbstractComponent> dragSource = new DragSourceExtension<AbstractComponent>(tf);

- Expected behavior:
TextField is editable, also in IE if the TextField is marked as draggable
- Actual behavior - see Bug description

**Comment by TatuLund** [comment]
I can confirm this.

There is also workaround. You can wrap the text field in CssLayout and extend the CssLayout with DrgSourceExtension instead. This seemed work for me.
