### ISSUE TITLE
The Tooltip of a MenuItem inside a Window is not displayed

### ISSUE THREAD

**Issue by focbenz** [vaadin/framework#11212]
*Expected:*
The Tooltip of a MenuItem should also be displayed when the MenuBar is displayed in a Window.

*Actual:*
No Tooltip is displayed for MenuItems inside a Window

*Steps to reproduce:*
- Show MenuItem Tooltip outside Window -> :heavy_check_mark: 
- Show MenuItem Tooltip inside Window -> :x: 

![vaadin8nomenuitemtooltipinwindow](https://user-images.githubusercontent.com/23717010/46195989-1c7d6480-c306-11e8-9066-e4d7f7469119.jpg)

*Affected versions:*
Issue can be observed with latest Vaadin 8.5.2 release
[UPDATE 2019-07-25]
Issue can still be observed with the latest Vaadin 8.8.5 release

*Sample project with failing Testbench test case:*
https://github.com/FOCONIS/vaadintooltipinmenuitem

*Sample code:*
```
        final VerticalLayout layout = new VerticalLayout();
        layout.addComponent(new Label("No Tooltip in menuItem dialog with: " + 
        		com.vaadin.shared.Version.getFullVersion()));
        Label issueLabel = new Label("Demonstrate MenuBar Tooltip problem when displayed in a Dialog box");
        issueLabel.setContentMode(ContentMode.HTML);
        layout.addComponent(issueLabel);
        
        Button openDialogButton = new Button("Open Dialog");
        openDialogButton.addClickListener(event -> {
        	Window dialog = new Window();
        	dialog.center();
        	dialog.setWidth("500px");
        	dialog.setHeight("500px");
        	
            MenuBar dialogmenuBar = new MenuBar();
            MenuItem menuItem = dialogmenuBar.addItem("First item in dialog");
            MenuItem firstDropdownItem = menuItem.addItem("Dropdown dialog item");
            firstDropdownItem.setDescription("Dropdown dialog Item Tooltip");
        	
        	dialog.setContent(dialogmenuBar);
        	addWindow(dialog);
        });
        
        MenuBar menuBar = new MenuBar();
        MenuItem menuItem = menuBar.addItem("First item");
        MenuItem firstDropdownItem = menuItem.addItem("Dropdown item");
        firstDropdownItem.setDescription("Dropdown Item");
 
        layout.addComponent(openDialogButton);
        
        layout.addComponent(menuBar);
        layout.setMargin(true);
        layout.setSpacing(true);
        
        setContent(layout);
```

**Comment by focbenz** [comment]
Oh noes ... such a nice bug description. Please try and fix this annoyance.

**Comment by focbenz** [comment]
The issue can still be verified in Vaadin 8.8.5 - and I have created a sample project with failing Testbench test case to illustrate the problem:
https://github.com/FOCONIS/vaadintooltipinmenuitem

**Comment by TatuLund** [comment]
This sounds quite strange. I did brief checking of the code. The default z-index of a overlay is 20000 and Tooltip uses it +1. Window is an overlay, but it overrides the default base value with 10000 (subsequent windows will be adding some offset on top of this base). Which means that Window should not appear on top of Tooltip. But apparently there must be something somewhere that messes the logic.

**Comment by javier-godoy** [comment]
Reproduced in Vaadin 8.10.3. 
When opening the MenuBar inside of Window, the v-tooltip text isn't updated, and its position remains at left: -5000px; top: -5000px.

**Comment by Ansku** [comment]
The problem is within connector identifying logic when an element within an overlay is owned by another element within another overlay. Got it working within nested Windows already, nested PopupViews need to wait until next week.
