### ISSUE TITLE
Support openxmlformats MIME types

### ISSUE THREAD

**Issue by Seb-Sch** [vaadin/framework#11235]
The following version is affected: Vaadin 8.5.2

Please add openxmlformats MIME types to FileTypeResolver.

The following types are missing:
`application/vnd.openxmlformats-officedocument. spreadsheetml.sheet` -->` *.xlsx`
`application/vnd.openxmlformats-officedocument. wordprocessingml.document` --> `*.docx`

**Comment by TatuLund** [comment]
Actually those two are not the only ones missing, ref https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc
