### ISSUE TITLE
Large text area is cut off in Firefox

### ISSUE THREAD

**Issue by edler-san** [vaadin/framework#11233]
A customer is creating a large text area to display some content via
```
TextArea area = new TextArea("FileTextArea");
area.setSizeFull();
area.setHeight(1510, Unit.PIXELS);
area.setWidth("10000px");
area.setValue(inputStreamString);
area.setReadOnly(true);
area.setEnabled(false);
area.setStyleName("textarea.v-textarea");
final Window subWindow = new Window("Fatal File", area);
subWindow.center();
subWindow.setWidth("90%");
subWindow.setHeight("20%");
subWindow.setModal(true);

```
Vaadin version 8 (assuming latest 8.5.x)
It renders as expected in IE and Chrome, Firefox' rendering seems off a few pixels and then cutting off the bottom part.

Mid section rendering - left is Firefox, right is IE. White line added for reference.
![](https://abload.de/img/bildschirmfoto2018-10urdzm.png)
Firefox' seems to use slightly more space.

Bottom section rendering - top is IE and bottom Firefox. The cut-off part is highlighted.
![](https://abload.de/img/bildschirmfoto2018-101zc4g.png)

**Comment by scardanzan** [comment]
Hi, I tried to reproduce the issue, but the sample code provided is not matching the screenshots, its also complicated because we are missing the content that is being displayed, and you are adding a style which could be the cause of the issue. Can you provide a sample project to reproduce the issue?

**Comment by TatuLund** [comment]
At brief look it seems that it just due different browsers, the font rendering is not pixel by pixel equal, so this is probably nothing attributed to Vaadin, but just how things are with different browsers.
