### ISSUE TITLE
Vaadin 8.5.2 drag and drop grid headers columns are not working on google chrome

### ISSUE THREAD

**Issue by rodrifmed** [vaadin/framework#11236]
Vaadin version: 8.5.2
SO: Ubuntu 18.04.1 LTS,
Browser: Chrome Version 69.0.3497.92 (Official Build) (64-bit)
IDE: Eclipse Photon Release (4.8.0)
Spring boot
To create the grid Im using a ObjectNode class from Jackson Json library. So I need to create the columns with the addColumn using ValueProvider. And Im using addColumnReorderListener to store the position of the columns everytime the user drag and drop the columns.

**Comment by TatuLund** [comment]
Tried to reproduce with https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features using latest Chrome and problem did not happen.
