### ISSUE TITLE
ComboBox with setPageLength=0 does not filter on Property

### ISSUE THREAD

**Issue by sukhmel** [vaadin/framework#11246]
ComboBox set to render text from Property does not filter correctly when page size is 0:
 * no filtering:
    ![default](https://user-images.githubusercontent.com/5804169/46957067-6c4a8280-d09f-11e8-9603-4244281b550a.png)

 * with filter:
    ![default](https://user-images.githubusercontent.com/5804169/46957128-8f753200-d09f-11e8-9e5e-548ae9b04b6a.png)

Minimal example:

```Java
public static class ItemUI {
    private final String displayName;
    public final Long id;

    public ItemUI(String displayName, Long id) {
        this.displayName = displayName;
        this.id = id;
    }

    public String getDisplayName() {
        return displayName;
    }
}

/*...*/
    final BeanContainer<Long, TestUI> container = new BeanContainer<>(TestUI.class);
    container.setBeanIdResolver(item -> item.id);
    container.addBean(new ItemUI("empty", 1L);

    final ComboBox comboBox = new ComboBox();
    comboBox.setPageLength(0);
    comboBox.setItemCaptionMode(AbstractSelect.ItemCaptionMode.PROPERTY);
    comboBox.setItemCaptionPropertyId("displayName");
    comboBox.setContainerDataSource(container);
    comboBox.setInvalidAllowed(false);
    comboBox.setTextInputAllowed(true);
```

- Vaadin Framework version: 7.7.8

- Expected behavior: filter should be applied

- Actual behavior: no elements are shown

- Reason: [ `getLastItemIndexOnCurrentPage` in ComboBox.java](https://github.com/vaadin/framework/blob/f7279f7330a3673e88e97552bb623fc21c2971e9/server/src/main/java/com/vaadin/ui/ComboBox.java#L616) does not take zero (effectively infinite) `pageLength` into account.

**Comment by anasmi** [comment]
Closing as pull request addressing the issue was merged
