### ISSUE TITLE
type: Array properties not synchronized to the server

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#11248]
`<vaadin.version>11.0.0</vaadin.version>` 
- Chrome on Windows 10

Array properties defined in a Polymer template html are not properly synchronized to the server. Based on https://www.polymer-project.org/2.0/docs/devguide/model-data , 
> When modifying arrays, Polymer provides a set of array mutation methods that mimic Array.prototype methods, with the exception that they take a path string as the first argument. The path argument identifies an array on the element to mutate, with the following arguments matching those of the native Array methods.

So modifying Array properties directly should not work (without extra notification) and that's fine. But even with the Polymer mutation method, the server side is not notified.

Sample project: https://github.com/OlliTietavainenVaadin/flowtestarray

**Comment by knoobie** [comment]
Wrong Repo :sweat_smile:
