### ISSUE TITLE
Enum values disappear from NativeSelect inside Grid Editor Vaadin 8.5.2

### ISSUE THREAD

**Issue by canberkizgi** [vaadin/framework#11274]
I have a NativeSelect component in Vaadin 8.5.2 but i've encountered a problem.
I list Enum types in NativeSelect component, 
	but after second or third selection(it does'nt matter which one) some enum types disappear in NativeSelect component.
**This problem doesn't exist in Vaadin 8.2.0, I encountered this problem 8.5.2(also 8.5.0)**

Here are the some screenshoots:
<img width="813" alt="evidence1" src="https://user-images.githubusercontent.com/28841094/47434549-75c4a080-d7ab-11e8-8a13-aeb906b274f1.png">
<img width="791" alt="evidence2" src="https://user-images.githubusercontent.com/28841094/47434569-79f0be00-d7ab-11e8-9dd6-2efe7d01f259.png">
<img width="808" alt="evidence3" src="https://user-images.githubusercontent.com/28841094/47434573-7cebae80-d7ab-11e8-881a-590a4ec598fd.png">

**Comment by OlliTietavainenVaadin** [comment]
I could not reproduce the issue. Attached sample project: 
[v8-enum-nativeselect.zip](https://github.com/vaadin/framework/files/2513465/v8-enum-nativeselect.zip)

**Comment by canberkizgi** [comment]
[v8-enum-nativeselect-buggy.zip](https://github.com/vaadin/framework/files/2513682/v8-enum-nativeselect-buggy.zip)
I reproduce the issue with modifying your sample project.
Can you check it?

**Comment by OlliTietavainenVaadin** [comment]
Minimal reproducible UI:
```
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout(
            new Label("Keep opening the editor and selecting an enum value. Eventually the list will not show " + "all options"), createGrid());
        setContent(layout);
    }

    public Component createGrid() {
        Grid<Person> grid = new Grid<>();
        grid.setItems(new Person(Enum.baz), new Person(Enum.foo), new Person(Enum.bizzle));
        grid.setSizeFull();
        grid.setSelectionMode(Grid.SelectionMode.NONE);

        NativeSelect<Enum> ns = new NativeSelect<>();
        ns.setItems(Enum.values());
        grid.addColumn(Person::getEnumValue).setCaption("Enum value").setEditorComponent(ns, Person::setEnumValue);
        grid.getEditor().setEnabled(true);
        return grid;
    }

    enum Enum {
        foo, bar, baz, bizzle, quux
    }

    public static class Person {
        Enum enumValue;

        public Person(Enum progress) {
            this.enumValue = progress;
        }

        public Enum getEnumValue() {
            return enumValue;
        }

        public void setEnumValue(Enum enumValue) {
            this.enumValue = enumValue;
        }
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by ZheSun88** [comment]
I have tested with the current `master` (8.7-SNAPSHOT) but I cannot reproduce this bug with the `Minimal UI`( by @OlliTietavainenVaadin ). I believe the recent fix on `NativeSelect` has some effects on this bug. https://github.com/vaadin/framework/commit/5e33b383fdf31f2ea15603f3a30bcb1e3c22d081

will test with the other sample.

**Comment by anasmi** [comment]
Hi,

I was not able to reproduce the bug mentioned in this ticket either, but I have found another one related.

After selecting different NativeSelects and different options inside, value is reset to empty. 
To demonstrate : 
![nativeselectsingrid](https://user-images.githubusercontent.com/15248706/48262960-2332e780-e42d-11e8-82d0-852888b9ae85.gif)
(In this case value is still on client side, but dropped by server. Refactoring seems to fix this)
