### ISSUE TITLE
Binder.removeBinding issue

### ISSUE THREAD

**Issue by nbabb** [vaadin/framework#11280]
In Vaadin flow 1.0.5, I have several fields bound to a Binder instance.  When I remove a binding (where there are still other bound properties) it is calling unbind.  It seems like it should only call unbind when the count of bound properties is zero?  Here is the code.

    public void removeBinding(String propertyName) {
        Objects.requireNonNull(propertyName, "Property name may not be null");
        Optional.ofNullable(boundProperties.get(propertyName))
                .ifPresent(Binding::unbind);
    }

I end up receiving errors after I remove the binding

java.lang.NullPointerException: This Binding is no longer attached to a Binder
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.validate(Binder.java:1027) ~[flow-data-1.0.5.jar:na]

from my other bound fields that are still using the binding.

Perhaps I'm misunderstanding how this should work?

**Comment by rsk-munendra** [comment]
I am also getting similar issue when using removeBinding(field). 
Seems like when bindings are removed, still the corresponding field validators are not cleared.

**Comment by lulnope** [comment]
The issue is located in `Binder` class in its `protected void removeBindingInternal(Binding<T, ?> binding)` method. Currently it looks as follows:
```
protected void removeBindingInternal(Binding<BEAN, ?> binding) {
        if (bindings.remove(binding)) {
            boundProperties.entrySet()
                    .removeIf(entry -> entry.getValue().equals(binding));
        }
    }
```
it's missing:
`changedBindings.remove(binding)`
which should resolve this error:
`java.lang.NullPointerException: This Binding is no longer attached to a Binder`
Currently a dirty workaround might look like this:
```
public class WorkaroundBinder<T> extends Binder<T> {

	public WorkaroundBinder() {
		super();
	}

	public WorkaroundBinder(Class<T> beanType, boolean scanNestedDefinitions) {
		super(beanType, scanNestedDefinitions);
	}

	public WorkaroundBinder(Class<T> beanType) {
		super(beanType);
	}

	public WorkaroundBinder(PropertySet<T> propertySet) {
		super(propertySet);
	}
	
	@Override
	protected void removeBindingInternal(Binding<T, ?> binding) {		
		super.removeBindingInternal(binding);
		try {
// if binder does not validate changedBindings is not cleared (possibly a mistake in doWriteIfValid method) as such
// a reference to binding might be left hanging in that set.
// This hack removes hanging reference from changedBindings .
			Field field = Binder.class.getDeclaredField("changedBindings");
			field.setAccessible(true);
			Set<Binding<T, ?>> changedBindings = (Set<Binding<T, ?>>) field.get(this);
			changedBindings.remove(binding);
		} catch (IllegalArgumentException | IllegalAccessException | NoSuchFieldException | SecurityException e) {
			e.printStackTrace();
		}
	}
	
}
```

**Comment by KatriHaapalinna** [comment]
Hi, this is the repository for Vaadin Framework (i.e. versions 7 and 8). You seem to be using the newer version, Vaadin Flow, which is located in a different repository.
Please create the issue to the GH repository of Vaadin Flow here: https://github.com/vaadin/flow/issues

**Comment by kpy3no** [comment]
instead of using remove binding i create only one binding for a field and judging by current state in runtime choose what i'm going to validate
