### ISSUE TITLE
Error Message at startup when people use Firefox on IOS

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11296]
On Vaadin 8.6.0 with the last Firefox on Iphone (Iphone X - IOS 12.0.1)

When the user connect to my Vaadin Application, a message is displayed:

![errorfirefox](https://user-images.githubusercontent.com/4507910/48144266-d9bd8d80-e2b0-11e8-8812-b1cb9ddcafff.jpg)

**Comment by anasmi** [comment]
Hi Pierre,

it's indeed looks like this issue might appear. The reason for this is behind those lines: https://github.com/vaadin/framework/blob/master/shared/src/main/java/com/vaadin/shared/VBrowserDetails.java#L679

So at start up we are checking, what version of the browser is and for the Firefox it should be larger than 45.

Firefox for iOS versions are ranging lower (The newest version is indeed 14 https://itunes.apple.com/fi/app/firefox-web-browser/id989804926?mt=8), so as a false-positive it's assumed that browser is not supported. Basically, we could test is device a mobile or not and give "green light" to mobile devices, but at this point I am not sure about reliable way of detecting mobile/PC nor could make this decision.

I would suggest you to override the `isTooOldToFunctionProperly` mtethod of the VBrowserDetails. (extend it on the client side and then replace your custom class in widgetSet) 
You could try to detect, if device is touch and then return 'false' from the method.

We haven't came across this before, but I hope you could implement the workaround above.

**Comment by pinonpierre** [comment]
Thanks for the workaround @anasmi but will Vaadin change it?

**Comment by anasmi** [comment]
I don't think there is any. We are checking against version number, and all of them are smaller than 45 (At least, what I have found, the latest one is 14).

I will share also this ticket with the team, I hope someone will comment here

**Comment by OlliTietavainenVaadin** [comment]
The official supported browsers list (as seen here: https://vaadin.com/download/release/8.6/8.6.0/release-notes.html ) does not include Firefox on iOS:
> Vaadin Framework 8.6.0 supports the following desktop browsers:
> 
> Mozilla Firefox 54+
> Mozilla Firefox ESR 52+
> Internet Explorer 11, Edge (latest version)
> Safari 9+
> Google Chrome 59+
> 
> Additionally, Vaadin Framework supports the built-in browsers in the following mobile operating systems:
> 
> iOS 9+
> Android 4+ with Chrome 42+

 We could quite easily make a change that allows iOS Firefox users to pass without that warning screen, but official support is a different matter.

**Comment by KyleRogers** [comment]
We ran into this issue as well with a customer complaining about being unable to use the web application.

Today [Firefox for iOS is at version 19.0 ](https://www.mozilla.org/en-US/firefox/ios/19.0/releasenotes/) although the [wiki page about Firefox for iOS](https://en.wikipedia.org/wiki/Firefox_for_iOS) wasn't updated, yet. According to that wiki page Firefox for iOS is **not based on Gecko rendering engine but uses the built-in iOS WebKit-based rendering framework** instead.

Same [seems to apply for Google Chrome for iOS](https://techcrunch.com/2017/01/31/google-open-sources-chrome-for-ios/?guccounter=1&guce_referrer_us=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_cs=fULtRiIMHtOTqwE7iJDsQw) although their versions seem to be in par with the official release numbers making it maybe even harder to distinguish WebKit renedering engine in Chrome for iOS from Chrome's Blink used in Android or desktop versions of the browser.

I'm neither a browser nor rendering engine expert - any pearls of wisdom you Vaadiners can share with us? We could overwrite the browser check but I'm not sure weather this will make things better or worse.

**Comment by ffdybuster** [comment]
I also was made aware of this problem. I worked around it by replacing `UnsupportedBrowserHandler` by our own handler (which shows the message in our styles), which also uses a modified version of `isTooOldToFunctionProperly()`. To make it easier for others, I've created a PR (#11739) to fix this in Vaadin.
