### ISSUE TITLE
RadioButtonGroup doesn't work correctly when visibility was turned off

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11294]
Hi,

First of all, please note that it become very problematic for us because we waited to migrate our 8.4 version since the 8.5 version is out but a bug was never be solved in 8.5. (https://github.com/vaadin/framework/issues/11143)

We waiting this 8.6.0 version for a long time ago but we still have an issue with RadioButtonGroup!

Hope it will be fixed very soon...

The issue, take this code:

    VerticalLayout verticalLayout = new VerticalLayout();
    setCompositionRoot(verticalLayout);

    RadioButtonGroup<Boolean> radio = new RadioButtonGroup<>("Radio", Arrays.asList(true, false));
    verticalLayout.addComponent(radio);

    Button hideButton = new Button("Hide");
    hideButton.addClickListener(event1 -> radio.setVisible(false));
    verticalLayout.addComponent(hideButton);

    Button setAndShowButton = new Button("Set and Show");
    setAndShowButton.addClickListener(event1 -> {
        radio.setValue(true);
        radio.setVisible(true);
    });
    verticalLayout.addComponent(setAndShowButton);
To reproduce:

Click on "false" radio button
Click on "Hide" button
Click on "show" button
Click on "false" radio button => The value is not selected and the radioButtonGroup has "null" value
Can you help us please?

Thanks,

**Comment by ZheSun88** [comment]
Fixed in PR #11304
