### ISSUE TITLE
Update V8 CVAL license documentation

### ISSUE THREAD

**Issue by tmattsso** [vaadin/framework#11297]
On this docs page (https://vaadin.com/docs/v8/framework/addons/addons-cval.html) we describe how to get and use CVAL licenses; it is horribly outdated and contains factual errors (like the filenames not starting with a dot, 'my account' actually being called 'my services' etc.). Coordinate with @johannesh2 so that the page also covers any new trial pages on vaadin.com.

**Comment by tmattsso** [comment]
Johannes mentioned that the documentation should be updated ASAP; new trial pages will change it again at some point.

**Comment by johannesh2** [comment]
I went through the page and it's not that outdated. The license portal should be fixed and the screenshots updated yes.

**Comment by johannesh2** [comment]
Actually I heard from a CTO, that the dot in the file name does not matter.

**Comment by tmattsso** [comment]
Good to know, then my patch should fix all the things 👍
