### ISSUE TITLE
Add generics to the Container interfaces

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1132]
**Originally by @wolfie**

___
Afaik, the absolutely most common use of Containers is to add some actual POJO as the itemId, and then populate Properties in a custom manner. Currently, the Containers only talk about Objects, which leads to much (potentially unnecessary) explicit casting. Having generics would make the the code cleaner.

I understand the use of Containers as a general repository of data. Generics doesn't take that away, you can still use Object as the type, if you really want to.

PS: My request is concerned mostly of converting itemIds from Object to typed. I understand that Properties is hard to get type safe, without making major changed to the API. But making Properties type safe on the same go would be much appreciated, too.

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/2872
