### ISSUE TITLE
Positioning of detail views in Vaadin Grid is broken

### ISSUE THREAD

**Issue by m-koops** [vaadin/framework#11337]
**Vaadin Framework version:** v8.6.1
**Browser version:** Chrome 70.0.3538.102
**Web container name and version:** Tomcat 9

**Description of the bug:** 
In our project we have noticed that the upgrade of the Vaadin framework from v8.4.5. to v8.6.1 has broken the calculation of the translate3d vectors for the row details panels. As a result the detail panels are misaligned and overlapping the grid rows.

See attached the fragments from the html. Only difference between the 2 samples is the vaadin framework in which the page was rendered.

[grid render - v8.4.5.txt](https://github.com/vaadin/framework/files/2620315/grid.render.-.v8.4.5.txt)
[grid render - v8.6.1.txt](https://github.com/vaadin/framework/files/2620316/grid.render.-.v8.6.1.txt)

**Comment by TatuLund** [comment]
This is probably related to https://github.com/vaadin/framework/issues/11288

**Comment by Ansku** [comment]
This one should also be fixed in 8.9.0.beta3 as part of the massive detail row reworking done for #11288
