### ISSUE TITLE
ComboBox.newItemProvider Issue when an new Item is set a second time /2

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#11347]
Hi,

I still have the bug in 8.6.2

https://github.com/vaadin/framework/issues/11317

Regards,

**Comment by pinonpierre** [comment]
Still in 8.6.3

**Comment by anasmi** [comment]
I am not able to reproduce this bug anymore in 8.6.3 following the steps described in the ticket above.

I will close this issue due to this, but , please, create a new one, with the steps how to reproduce, description and code snippet, if the problem still exists for you under any circumstances.

**Comment by pinonpierre** [comment]
For Information: dataProvider.refreshAll() must be used instead of dataProvider.refreshItem(value) to see the fix work.
