### ISSUE TITLE
Combobox dropdown stays open/showed, when you input data quickly and exit with TAB-Key (Vaadin 7 and 8)

### ISSUE THREAD

**Issue by simpletasks** [vaadin/framework#11354]
Tested on Vaadin 7.7.6 and 7.7.15
Tested on Chrome 70.0.3538.110 and  Firefox 63.0.3
Tested on Jetty 9.2.3.v20140905

When using tab for moving from one combobox to another after entering one or
two digit value combobox option list stays open.

Reproduction:
Four Combobox<Integer> components in horizontal layout. Every combobox has list of some integers.
Use tab to focus first combobox, enter one digit number value and follow with fast tab press to focus next combobox.
Almost every time option list on one to all comboboxes stays open.
Value change listeners are not called but blur listeners are (I set valueChangeListener and BlurListener). This result in losing new value entered in combobox.
Use case is better when override Combobox class  and add TextChangeListener in which I can fire valueChangeEvent.
In this case new values are saved and blur listener can use them.
 But option list for combobox still stay open.

![vaadin-bug](https://user-images.githubusercontent.com/27790652/49457710-955bd980-f7eb-11e8-81ec-cd8d98d3d0e1.png)

  I expect that even in fast typing new values in comboboxes followed with fast tab usage will show correct combobox
 behavior. On blur option list should be hidden or removed from page.
 
 Now, combobox do not save new value, that is first problem. Adding TextChangeListeners looks like help but I'm not sure  is this solution good enough for every case.
 Second problem is that combobox option list stays open when using keyboard to fast.

**Comment by simpletasks** [comment]
Problem can also be seen here:
https://demo.vaadin.com/book-examples-vaadin7/book/#component.select.common.basic

Type fast: 1) enter any letter and immediately press tab. Option list stays open even empty.

**Comment by anasmi** [comment]
This issue should be fixed by this pull request : https://github.com/vaadin/framework/pull/11436
