### ISSUE TITLE
Combobox functionality of the long items depends on the browser

### ISSUE THREAD

**Issue by Satsu80** [vaadin/framework#11368]
- Vaadin Framework version: 8.3.2
- Browser version: Firefox 63.0.3, Chrome 63.0.3239.84
- Web container name and version: jboss wildfly
- Description of the bug:
Combobox functionality of the long items depends on the browser.
FIREFOX:
1. Combobox current item is short text like "Any". (No need to truncate text). There is long text items in combobox popup when it is opened.
2. Select one long text item -> Text is shown in combobox but it is not truncated and no "..." is added.
3. Click somewhere outside combobox/**Click combobox arrow two times** -> Text is truncated and "..." is added.
4. Select another long text item -> Text is not truncated and the middle part of the text is displayed.
**5. Click somewhere outside combobox -> Nothing happend
6. Click combobox arrow two times -> Text is truncated and "..." is added.**
CHROME:
1. Combobox current item is short text like "Any". (No need to truncate text). There is long text items in combobox popup when it is opened.
2. Select one long text item -> Text is shown in combobox but it is not truncated and no "..." is added.
3. Click somewhere outside combobox -> Text is truncated and "..." is added.
4. Select another long text item -> Text is not truncated and the middle part of the text is displayed.
**5. Click combobox arrow two times -> Nothing happend
6. Click somewhere outside combobox -> Text is truncated and "..." is added.**

- Expected behavior: Long text items should be truncated and "..." added after it is selected from popup, and there should be no differences between browser.
- Actual behavior: See steps above.

**Comment by TatuLund** [comment]
Is this same as https://github.com/vaadin/framework/issues/9795 ?
