### ISSUE TITLE
Small wdith of MenuBar leads to IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Flaurite** [vaadin/framework#11374]
- Vaadin Framework version 8.6.1
- Description of the bug
If `MenuBar` has some MenuItems and has width is about "50px" will be shown only one button with "right-arrow":
![image](https://user-images.githubusercontent.com/22093943/49937810-63382f00-fef1-11e8-9b5b-0a09e8b84def.png)
But in this case we can't see sub items because of `IndexOutOfBoundsException`
- Minimal reproducible example
1. Create MenuBar and set width "50px";
2. Add some items to the MenuBur;
3. Start the application and add "?debug" mode
- Expected behavior
We can open menu items
- Actual behavior
`IndexOutOfBoundsException` is occured.
``
``
    
After investigation a problem we get error in this line:
```
com.vaadin.client.ui.VMenuBar$CustomMenuItem#onLoad() (906)
```

**Comment by Flaurite** [comment]
Related to: Vaadin framework https://github.com/vaadin/framework/issues/11374

**Comment by anasmi** [comment]
Hi,

there is a good news actually : ) 

It seems like this pull request solves the problem : https://github.com/vaadin/framework/pull/11285

It's waiting for author for tests, but with your report I could add tests based on this use case.
Thank you very much for reporting the issue! :)
