### ISSUE TITLE
Grid: Moving horizontally between components within the grid by using TAB

### ISSUE THREAD

**Issue by AndreiBoaghe** [vaadin/framework#11379]
- The old issue with Vaadin **8+** (also tested with the latest stable **8.6.3** version)
- Brief description: odd behavior with the Grid horizontal scrolling when using "focusable" components in the header cells.

**Steps to reproduce the issue:**

- Select the TextField, which is not entirely displayed.

![image](https://user-images.githubusercontent.com/23465246/42941047-1e1ea530-8b64-11e8-95fd-131134cc7f67.png)

- Press the "Tab" button.

- As you can see at the screen below horizontal scrollbar remained in its left most position, while the Grid content moved to the right. 

![image](https://user-images.githubusercontent.com/23465246/42941302-00410f20-8b65-11e8-91cb-42b96f79a260.png)

**Demo application** (change the file extension from zip to war):
[grid.sample-1.0-SNAPSHOT.zip](https://github.com/vaadin/framework/files/2209847/grid.sample-1.0-SNAPSHOT.zip)
**Demo project** (created using vaadin-archetype-application)
[GridSample.zip](https://github.com/vaadin/framework/files/2212774/GridSample.zip)

_PS: This issue has been created as a copy of the following stale issues_: #10288, #7781

**Comment by altefcat** [comment]
Hi have exactly the the same issue in my application. Can you consider this issue and increase the priority level. I already saw same issue on different forums. Thx you
