### ISSUE TITLE
Slow Grid Scrolling on Huawei Mate 10 Pro

### ISSUE THREAD

**Issue by lochehong** [vaadin/framework#11393]
The Grid scroling is very jerky and slow some phones e.g. huawei mate 10 pro.
i can't find the reason why. it's faster on some lower specc huawei phones.
both using chrome browser.

- Vaadin Framework Grid 5.2.5

- Browser version
Chrome V71.0.3578.99

- Web container name and version
- Description of the bug
- Minimal reproducible example
- Expected behavior
Smooth Scrolling
- Actual behavior
Slow scrolling even after all data is loaded.

**Comment by anasmi** [comment]
Hi,

you've mentioned that you are using vaadin-grid 5.2.5, this indicates that you are using Vaadin 10+. 

I've moved the issue to vaadin-grid-flow repository. https://github.com/vaadin/vaadin-grid-flow/issues/478

Thanks for reporting the issue! : )
