### ISSUE TITLE
BindingBuilder.asRequired() returns true for nulls

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#11401]
Vaadin 8.6.3. I have the following binder setup:
```java
        final Binder<Person> binder = new Binder<>(Person.class);
        final TextField name = new TextField();
        name.setCaption("Type your name here:");
        binder.forField(name).withNullRepresentation("").asRequired().bind("name");
```
The problem is that with this setup, an empty `TextField` passes the `asRequired()` validation and null is passed into `Person.setName()` with the following code:
```java
if (binder.isValid() && binder.writeBeanIfValid(p)) { 
  // all ok
}
```

**Comment by mvysny** [comment]
[vaadin-app.zip](https://github.com/vaadin/framework/files/2717052/vaadin-app.zip)
Attaching a project reproducing the issue.

**Comment by TatuLund** [comment]
I think this is distantly related to also issue https://github.com/vaadin/framework/issues/9000

In the both cases I assume the problem is that asRequired() does not fail with empty string.

Changing asRequired() sounds trivial, but how much side effects it would have?

**Comment by TatuLund** [comment]
Default implementation of asRequired() is a short hand for the following

See: https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/data/Binder.java#L912

`asRequired(Validator.from(value -> !Objects.equals(value, field.getEmptyValue())`

The method with custom asRequired validator is also public, see

https://vaadin.com/api/framework/8.6.3/com/vaadin/data/Binder.BindingBuilder.html#asRequired-com.vaadin.data.Validator-

Which gives a workaround

`asRequired(Validator.from(value -> (field.getValue() != null || !Objects.equals(value, field.getEmptyValue()))`

**Comment by mvysny** [comment]
Thank you for posting the workaround. Yet I believe that nulls effectively mean "no value" and thus the standard asRequired() method should catch them in addition with the empty value, exactly as your workaround suggests.

**Comment by Legioth** [comment]
I think there's an even easier workaround, but I'm too lazy to test it in practice. The null representation converter and the required validator are forming a processing chain where order matters. If you change the order between validator and the converter, then the validator will see the original value from the field (i.e. `""`) rather than `null` and thus fail validation.

```
binder.forField(name).asRequired().withNullRepresentation("").bind("name");
```

**Comment by NetRob** [comment]
> I think there's an even easier workaround, but I'm too lazy to test it in practice. The null representation converter and the required validator are forming a processing chain where order matters. If you change the order between validator and the converter, then the validator will see the original value from the field (i.e. `""`) rather than `null` and thus fail validation.
> 
> ```
> binder.forField(name).asRequired().withNullRepresentation("").bind("name");
> ```

setting **asRequired** before **withNullRepresentation** actually solves it for me 👍
