### ISSUE TITLE
@PushStateNavigation with @PreserveOnRefresh does not work correctly

### ISSUE THREAD

**Issue by apgsga-stb** [vaadin/framework#11416]
If your UI has both annotations, @PushStateNavigation and @PreserveOnRefresh, then the navigation does not work properly. Changing the URL in the browsers address bar does not switch the view. This is because navigation is not performed in that case. See classes UIInitHandler and UI.

As a workaround I have overridden doRefresh in my UI-Class:
```
  @Override
  public void doRefresh(final VaadinRequest request) {
    super.doRefresh(request);
    final RadNavigator navigator = getNavigator();
    if (navigator != null) {
      navigator.navigateTo(navigator.getState());
    }
  }
```

**Comment by TatuLund** [comment]
Thanks for reporting this, I issued pull request for a fix and to test if there are failing regression tests.
