### ISSUE TITLE
Setting autocomplete to a random number prevents setting autocomplete to 'off'

### ISSUE THREAD

**Issue by mcsherrylabs** [vaadin/framework#11437]
Google Chrome 71.0.3578.80 (Official Build) on Ubuntu
Chromium Version 71.0.3578.98 (Official Build) on Ubuntu
Vaadin 8.5.2 (but I note the code has not changed in latest 8.x release)
ComboBox  see #7820

![combo_problem](https://user-images.githubusercontent.com/6160346/51733633-d3ea7380-2079-11e9-82d4-104390fac0d1.png)

Problem -
In the above setup chrome autocomplete  boxes overshadow the dropdown making for a horrible UX. 
Using viritin HtmlElementPropertySetter doesn't override the random number set in referenced PR

Desired Outcome - 
Setting the autocomplete property to "off" by editing the DOM in chrome developer tools prevents the chrome options popping up. This is the desired outcome.

This seems like a 'simple fix' ... replace the random number generation with "off". I have not checked this on Firefox or IE. --reaches for helmet--

**Comment by mcsherrylabs** [comment]
Guys, I don't mind fixing this, it's a simple fix, but ... 

Can I get some indication of whether setting the 

```autocomplete=off```

 instead of a random number is an acceptable fix please?

**Comment by TatuLund** [comment]
The inconvenience about this is that Chrome is not supporting autocomplete="off" at the moment as we would wish. This is a bit of a problem with all frameworks, not just Vaadin. There are lengthy discussions about this in various places, notably this thread at StackOverflow

https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

as well as the change request in Chromium issue tracker

https://bugs.chromium.org/p/chromium/issues/detail?id=587466

The most common way to tackle this has been using random numbers there, but it is not fool proof.

**Comment by mcsherrylabs** [comment]
Thanks for the reply @TatuLund 

It looks like this was fixed in chrome -> https://codereview.chromium.org/1473733008

This test confirms my experience -> https://stackoverflow.com/a/52082658/10124106

Try it! (at your leisure)

My issue is not with password fields by the way, just combo box dropdowns.

**Comment by TatuLund** [comment]
Note, there still issues with Chrome regarding autocomplete=off setting:

https://bugs.chromium.org/p/chromium/issues/detail?id=928305&can=1&q=component%3AUI%3EBrowser%3EAutofill

**Comment by mcsherrylabs** [comment]
It's difficult to follow that thread, but it seems like no one could reproduce the reported issue with autocomplete=off ?
