### ISSUE TITLE
GAEApplicationServlet too eager with session cleanup

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1143]
**Originally by @hezamu**

___
It seems that the servlet closes all applications after every request. GAEApplicationServlet.java:356 removes the context from the session, which will in turn result in Application.close() being called.
```
public class TestcaseApplication extends Application {
    @Override
    public void init() {
        setMainWindow(new Window("Testcase Application"));
    }

    @Override
    public void close() {
        System.out.println("Close called");
        super.close();
    }
}
```

Just loading the app in a browser results in close() being called twice. This happens with GAE dev server, but not with ApplicationServlet on Tomcat.

Not sure if this is a defect in Vaadin or the GAE dev server but it needs to be addressed because it causes problems when developing for GAE.

___
 Imported from https://dev.vaadin.com/ issue #5228

**Comment by hezamu** [comment]
This issue can be closed, probably no longer relevant.
