### ISSUE TITLE
GridLayout row heights do not get equally distributed with many rows

### ISSUE THREAD

**Issue by lexcution** [vaadin/framework#11440]
GridLayout row heights do not get equally distributed if GridLayout has lots of rows.
This issue is clearly similar to the #7642 issue but reproducible with small height size.
Not much to explain, the last ticket was quite clear. 

**Test**
- To test it, create a gridLayout with many rows (EG: 100)
- Set the height of the gridLayout to 100%
- Add a bit of different color on each line
- Here we GO
![image](https://user-images.githubusercontent.com/24249974/51919544-ee0eb380-23e3-11e9-9e7e-71d14d92f5d6.png)

**Expected**
- The expected result should be similar height on each slots.

**Details**
- **Browser version** :
  Edge  42.17134.1.0
  Chrome 71.0.3578.98
  Firefox 64.0.2

**Comment by TatuLund** [comment]
This is a good observation, but I would not say it is a bug. GridLayout calculates the row heights to closest int value, so therefore +/-1  deviation as observed here is possible (see code: https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/VGridLayout.java#L62 )

**Comment by lexcution** [comment]
Hi @TatuLund , Thanks for your quick answer 😃 
I get the idea. Nevertheless, should there be an "**Harmonizing**" function which go through the list of created row to equalized them and in the end, fix this "little problem" !? 
Not something by default but maybe just a method which allow you to choose how your GridLayout will be displayed.
