### ISSUE TITLE
RadioButtonGroup - a wrong item is marked as selected after changing data provider 

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11454]
#### Vaadin Framework version: 8.6.3, 8.7.0
Note: this is regression, the issue is not reproducible on 8.5.2

####  Description of the bug
Changing items data provider in radio button causes it to look like a new item was selected. This affects only client side, the `getValue` and `getSelectedItem`  methods keep returning value from old data provider.

For example, I have radio with four items `aaa, bbb, ccc, ddd` where `ccc` is selected. I change items to contain four new items `111, 222, 333, 444`. On the screen, it suddenly looks like `333` was selected. On the server, both `getValue` and `getSelectedItem` return the old `ccc`.

####  Minimal reproducible example
````java
RadioButtonGroup<String> radio = new RadioButtonGroup<>();
radio.setItems("aaa", "bbb", "ccc", "ddd");

layout.addComponent(radio);
layout.addComponent(new Button(
		"New Data Provider - without selected item",
		e -> radio.setItems("111", "222", "333", "444")
));
// button to print some debug info
layout.addComponent(new Button("Investigate",
		e -> {
			Optional<String> selectedItem = radio.getSelectedItem();
			System.out.println("selectedItem.isPresent " + selectedItem.isPresent());
			if (selectedItem.isPresent()) {
				System.out.println("radio.get " + selectedItem.get());
			}
			System.out.println("radio.getValue " + radio.getValue());
		}));
````

* Select item `333`.
* Press `New Data Provider - without selected item`.
* Press `Investigate`.

####  Expected behavior
* Nothing is selected.

Console contains either:
````sh
selectedItem.isPresent false
radio.getValue null
````
or maybe
````
selectedItem.isPresent true
radio.get ccc
radio.getValue ccc
````
####  Actual behavior
* `333` is selected

Console contains:
````sh
selectedItem.isPresent true
radio.get ccc
radio.getValue ccc
````

* Unexpected item is selected - `333` should not be selected.
* Result of `getValue` and `getSelectedItem` does not match state visible on screen.

**Comment by SomMeri** [comment]
Workaround:
````java
radio.setDataProvider(myNewDataProvider);
radio.updateSelectedItemState(radio.getValue()); // removes wrong selection
````

The `updateSelectedItemState` method is protected inside `RadioButtonGroup`. You have to extend the radio button group and make it public first.

**Comment by anasmi** [comment]
Hi,

thank you for reporting this! 
I am not sure yet, what is the correct way of fixing this, but an easier workaround would be calling directly `radio.setSelectedItem(null); ` before or after changing the dataProvider. Then you don't need to extend the component at all
