### ISSUE TITLE
IE11 DateField, the cursor jumps to the beginning of input after first value change

### ISSUE THREAD

**Issue by johannest** [vaadin/framework#11455]
Vaadin Framework version: 8.7.0
Browser version: IE11
Web container name and version: Jetty 9.4.12.v20180830
Description of the bug: After refreshing the page/view containing a datefield, and after changing the value of the DateField first time, the cursor jumps in the beginning of the input field. 
Minimal reproducible example: 
```
DateField df = new DateField();
layout.addComponent(df);
```

Expected behavior: The cursor should stay at the end of the input field after the value change as it works in the other browsers. Tested browsers with expected behavior: Chrome, Edge, Firefox

Actual behavior: See the description above and the attached screeshot: 
![image](https://user-images.githubusercontent.com/2297689/52633999-b36e4600-2ece-11e9-8646-b2b780d2d9e5.png)

**Comment by TatuLund** [comment]
The fix proposal (although it is working) was not accepted in framework, however add-on Directory exists (based on same fix) that can be used as workaround

https://vaadin.com/directory/component/datefieldfocusfixed
