### ISSUE TITLE
Firefox 65 first button click not handled in Vaadin 7.7.15

### ISSUE THREAD

**Issue by johnmharris** [vaadin/framework#11462]
- Vaadin Framework 7.7.15
- Firefox 65.0.1

Something we've noticed that appears to have broken with the latest Firefox build, a vaadin button now requires clicking twice before the UIDL is issued.

- hover over button- bg colour changes
- click once- no uidl, bg colour reverts
- click again- uidl sent

In VButton when the button is clicked but no UIDL is sent the following events are processed:

- onMouseDown
- onMouseOut (targetInsideButton is false)
- onMouseUp

Whereas clicking it again results in 'Down, Up, Click' as you would expect.

During mouse out when targetInsideButton return is false the var state is:

- event.getRelatedTarget(): `<span class="v-button-caption">`
- getElement():  `<div class="v-button v-widget" tabindex="0" role="button">`
- DOM.eventGetTarget(event): `<div class="v-button v-widget" tabindex="0" role="button">`
- getElement().isOrHasChild(DOM.eventGetTarget(event)):  true
- getElement().isOrHasChild(event.getRelatedTarget()): true

**Comment by TatuLund** [comment]
I tried to reproduce this issue, but I could not.

Steps I did

Create Vaadin 7 single module project from archetype in Eclipse, jetty:run

Click the button -> works at first click

**Comment by johnmharris** [comment]
In our test harness the button must not be focused first to show this problem. The click has to be on the button caption span rather button parent div.

Subsequent clicks will always result in the UIDL being sent. Other browsers (chrome, ie, edge) are OK. Older firefox (52, the 32bit ver) still works as expected. Have *not* checked Firefox 64.

**Comment by TatuLund** [comment]
Can you reproduce the issue with the simple test application, like the one I mentioned?

**Comment by johnmharris** [comment]
Yes using a trivial vaadin app in grails, will attempt to reproduce with the eclipse plugin too. Thanks for taking a look.

**Comment by johnmharris** [comment]
Could **not** reproduce in the 7.7.15 archetype, which led me to discover the problem is caused by a line in our custom vaadin theme (a fork of valo):
```
.v-button:focus:after {
  display: none;
}
```
This line shouldn't have been used in the first place, but interestingly hadn't caused this click problems in firefox until very recently.

Clearly not a problem in the vaadin framework after all, but thanks for your input.
