### ISSUE TITLE
7.7.16: Grid scrolling with open editor in unbuffered mode throws IllegalStateException

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#11463]
Version: 7.7.16
Code to reproduce: 
```
------
 Collection<Person> people = personList();
        BeanItemContainer<Person> container =
                new BeanItemContainer<Person>(Person.class, people);
        final Grid grid = new Grid(container)
        grid.setSizeFull();
        grid.setEditorEnabled(true);
        grid.setEditorBuffered(false);
        setContent(grid);
------
 private List<Person>  personList(){
        List<Person> people=new ArrayList<>();
        for(int i=0;i<100;i++){
          people.add(new Person("Name" + i, 24+i));
        }
        return people;
    }
```
Steps to reproduce: 
- click on any cell and scroll, exception is thrown

Error:  **Caused by: java.lang.IllegalStateException: Row with logical index 72 is currently not available in the DOM**

Exception is thrown at this point (Also, this is most likely the pr, which introduced the regression): https://github.com/vaadin/framework/commit/062caa5b844dd6540b101dd04c612bc8e5948ad4#diff-6cd1edd3140e7674e92302b06bbc34d9R2145

**Comment by TatuLund** [comment]
Closed via https://github.com/vaadin/framework/pull/11467
