### ISSUE TITLE
Hiding Vaadin files hosted on a server

### ISSUE THREAD

**Issue by tzkuat** [vaadin/framework#11468]
Hi,

I'm currently using Vaadin v7 and I would have a question about Vaadin configuration.
I noticed that currently a user that is not authenticated is able to enumerate files within Vaadin repositories  ("/.../VAADIN/.../compilation-mappings.txt" for instance). Once those files are listed, it's even possible to read their contents. 
I tried to deactivate this by editing my Apache Tomcat's "web.xml" like this:

```
<init-param>
<param-name>listings</param-name>
<param-value>false</param-value>
</init-param>
```

But it doesn't seem to work.
Could you please help me fixing this matter?

Thanks in advance!

**Comment by TatuLund** [comment]
This is duplicate of https://github.com/vaadin/framework/issues/9154
