### ISSUE TITLE
Grid Multiselect with select all checkbox and filtering

### ISSUE THREAD

**Issue by jensgoe** [vaadin/framework#11479]
- Vaadin Framework version: 8.4.5
- Browser version: any

## Description of the bug
I have a grid to select multiple items and a ListDataProvider with filtering. If i add a filter to show e.g. 10 of 100 items and press the select-all checkbox everything seems ok. Even getSelectedItems() returns the 10 items. After clearing the filters i can see in the grid that all items are selected.

## Expected behavior
Only the items are selected that got selected as the filters were active.

## Actual behavior
All items are selected after clearing the filters.

## Problem
The problem might be that the "select-all-checkbox" is in checked state after all (visible) items got selected. After clearing the filter the "select-all-checkbox" is still in checked state and so the grid applies its state to all items. And then all items are selected.

**Comment by jensgoe** [comment]
Just noticed that this is a visual issue. Calling grid.getSelectedItems() returns the correctly selected items. But the grid displays all the items as selected. My current workaround is to rembember the currently selected items before clearing the filters and restore the selection. This updates the grids selection but this is a lot of overhead because every item is selected independently (no setSelections-method).

**Comment by pleku** [comment]
Oops didn't read the second comment.

If the visual selection and server side selection are not in sync with the select all, then that is a bug.

**Comment by SomMeri** [comment]
We have the same problem. Another possible workaround is to uncheck select all checkbox each time data set changes.

Custom grid:
````java
// Extend vaadin api so that it is possible to uncheck select all programmatically
@SuppressWarnings({ "javadoc", "serial" })
public class CustomGrid<T> extends Grid<T> {

        // ...

	@Override
	public GridSelectionModel<T> setSelectionMode(SelectionMode selectionMode) {
		Objects.requireNonNull(selectionMode, "Selection mode cannot be null.");
		if (SelectionMode.MULTI.equals(selectionMode)) {
			CustomMultiSelectionModelImpl<T> model = new CustomMultiSelectionModelImpl<>();
			setSelectionModel(model);
			return model;
		}

		return super.setSelectionMode(selectionMode);
	}

	@SuppressWarnings("serial")
	public static class CustomMultiSelectionModelImpl<T> extends MultiSelectionModelImpl<T> {

		public void uncheckSelectAllCheckBox() {
			getState().allSelected = false;
		}

	}

}
````
And then in grid do this:
````java
	// ...
	dataProvider.addDataProviderListener(this::fixSelectionOnDataChange);
	// ...

	@SuppressWarnings("unchecked")
	private void fixSelectionOnDataChange(DataChangeEvent<Object> dataChangeEvent) {
		Container dataContainer = getDataContainer();
		// find filtered out elements that should no longer be selected
		Set<Object> noLongerAvailable = grid.getSelectedItems().stream()
				.filter(thing -> null == dataContainer.getItem(thing)).collect(Collectors.toSet());

		// if possible deselect all items at once
		if (!noLongerAvailable.isEmpty()) {
			GridSelectionModel<Object> selectionModel = grid.getSelectionModel();
			if (selectionModel instanceof MultiSelectionModel<?>) {
				MultiSelectionModel<Object> multi = (MultiSelectionModel<Object>) (GridSelectionModel<?>) selectionModel;
				multi.deselectItems(noLongerAvailable.toArray());
			} else {
				for (Object uvailable : noLongerAvailable) {
					selectionModel.deselect(uvailable);
				}
			}
		}

		uncheckSelectAllCheckboxVaadinIssue11479();
	}

	// https://github.com/vaadin/framework/issues/11479		
	@SuppressWarnings("unchecked")
	private void uncheckSelectAllCheckboxVaadinIssue11479() {
		GridSelectionModel<Object> selectionModel = grid.getSelectionModel();
		if (selectionModel instanceof CustomMultiSelectionModelImpl<?> && isSelectAllCheckBoxVisible()) {
			CustomMultiSelectionModelImpl<Object> multi = (CustomMultiSelectionModelImpl<Object>) (GridSelectionModel<?>) selectionModel;
			multi.uncheckSelectAllCheckBox();
		}
	}

````

**Comment by jensgoe** [comment]
I tested this issue with version 8.8.6 and it still exists.
Steps to reproduce:
- implement a multiselect grid with filtering
- add 10 items to the grid
- use a filter to only make 2 items visible
- click the select all checkbox in the header --> all items are selected, OK
- clear the filter or change it in a way that more than the two items are visible --> still all items are selected. NOT OK (getSelectedItems() returns the 2 selected items)

After clearing the filter I would expect that the "select all checkbox" gots cleared and that only the 2 items that was previously selected are in selected state. The method getSelectedItems() behaves that way.
