### ISSUE TITLE
CheckBoxGroup do layout after completely loaded window

### ISSUE THREAD

**Issue by Flaurite** [vaadin/framework#11486]
- Vaadin Framework version: 8.6.4
- Description of the bug
When a window contains `CheckBoxGroup` sometimes you can see some kind of flickering. After an investigation, it turns out that `CheckBoxGroup` starts to add its content after completly loaded window. You can see it in the attached gif (Grid is shifted down):
![checkboxgroup](https://user-images.githubusercontent.com/22093943/53953372-9bb06900-40ec-11e9-8160-8cd71e792a07.gif)

When we have Window with complicated content such flickering is very noticeable.

- Minimal reproducible example
Steps to reproduce:
1. Create `Window` 
2. Add `CheckBoxGroup` and `Grid` to the `Window` with some data.
3. In the dev tools of your browser add CPU throttling:
![image](https://user-images.githubusercontent.com/22093943/53953812-c9e27880-40ed-11e9-8c1b-76050cafbcd9.png)
4. Open window.
- Expected behavior
Probably, `CheckBoxGroup` should load data and do layout before completely loaded Window

**Comment by mlopezFC** [comment]
According [to this](https://github.com/cuba-platform/cuba/issues/1661#issuecomment-540615007), the original reported problem was not related to CheckBoxGroup doing the layouting after completely loading the window, so probably this is not a big issue after all, and it could happen also with other components.
