### ISSUE TITLE
ComboBox html captions problem

### ISSUE THREAD

**Issue by lubomirmatus** [vaadin/framework#11491]
Hi

I'm using vaadin 8.7.1 on Windows 7 x64 with TomEE 7.0.2.
I have tryed to use HTML captions in `ComboBox` using `setCaptionAsHtml(true);` and set caption generator using `setItemCaptionGenerator(MyComponent::giveMeSomeHtmlCaption)`. The captions are still rendered in plain text mode. Items in drop-down and item in input-field, both are still in plain-text with all html tags visible.

I have also spotted that ValoTheme styles like `ValoTheme.COMBOBOX_SMALL` are applied only to `ComboBox` input-field, but not to items in drop-down list. I think, the drop-down should use the same style as is set for ComboBox.

**Comment by TatuLund** [comment]
ComboBox method setCaptionAsHtml(true) is not related to item captions. It sets the caption of the ComboBox itself to accept html. Combox does not support html in item captions. 

There is old feature request about it https://github.com/vaadin/framework/issues/2132, but it was not implemented and style generator for item captions was implemented instead. 

If your goal is to apply e.g. bold font to item caption, you can do it as described on StackOverflow here: https://stackoverflow.com/questions/52442208/vaadin-combobox-set-items-as-html-not-work/52443653#52443653

In Vaadin 10+ ComboBox allows template rendering, which sort of implements this feature: https://vaadin.com/components/vaadin-combo-box/java-examples/using-components

**Comment by lubomirmatus** [comment]
Thanks for your answer.
The ComboBox items are of class with more members. I want to display more class members of item. For example: one on the left side and second on the right side of line. So the custom renderer is the mechanism I need, style generator is not sufficient for this. 
This mechanism is already implemented in vaadin 10, it would be fine to backport it also to vaadin 8.

**Comment by Legioth** [comment]
> This mechanism is already implemented in vaadin 10, it would be fine to backport it also to vaadin 8.

Backporting these kinds of features to Vaadin 8 is not practical since Vaadin 10 uses a completely different architecture and new implementations of all components.

**Comment by ZheSun88** [comment]
Hi @lubomirmatus , if there is no further question here, i am going to close this ticket. Also we'd like to help you on https://vaadin.com/forum/category/1007558/04-framework for framework related questions.
