### ISSUE TITLE
Panel.setScrollTop() fails with impossibly large numbers

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1149]
**Originally by @wolfie**

___
Setting the scroll-top position (might affect scroll-left position equally) to a very large number (verified with Integer.MAX_VALUE and values a bit less than that) behaves just like giving a zero as the argument.

Expected behavior: always scroll to the end (or, at least to the pixel specified by the maximum integer value).

___
 Imported from https://dev.vaadin.com/ issue #5274

**Comment by OlliTietavainenVaadin** [comment]
This is not yet fixed in 7.7. It's reproducable with the following:

````java
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        Panel panel = new Panel();
        panel.setSizeFull();
        Button b1 = new Button("scroll " + Integer.MAX_VALUE, e -> {
            panel.setScrollTop(Integer.MAX_VALUE);
        });
        layout.addComponents(b1);
        String s = "";
        for (int i = 0; i < 10000; i++) {
            s += i + "<br />";
        }
        Label label = new Label(s, ContentMode.HTML);
        layout.addComponent(label);
        panel.setContent(layout);
        setContent(panel);
    }
````

Scrolls down to the bottom in Chrome and Firefox, but not IE or Edge.
