### ISSUE TITLE
Notification API+Doc doesn't mention additional styles

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#11492]
Vaadin 8.7.0. The Valo Theme Test app demoes multitude of additional Notification styles, such as dark, success, failure, bar etc, at https://demo.vaadin.com/valo-theme/#!common

However, such styles are not mentioned in the documentation at https://vaadin.com/docs/v8/framework/application/application-notifications.html , nor in the Notification java API.

**Comment by TatuLund** [comment]
Will be included in 8.9.2
