### ISSUE TITLE
Cannot disable ES5 transpilations

### ISSUE THREAD

**Issue by brunojcm** [vaadin/framework#11504]
- Vaadin Framework version: 13.0.1
- Browser version: Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

If I disable the ES5 transpile in the maven build, with `<skipEs5>true</skipEs5>`, I still get the following exception, even with latest Chrome and also Safari:

```
java.lang.IllegalArgumentException: Failed to find the bundle manifest file 'frontend://vaadin-flow-bundle-manifest.json' in the servlet context for 'ES5' browsers. If you are running a dev-mode servlet container in maven e.g. `jetty:run` change it to `jetty:run-exploded`. If you are not compiling frontend resources, include the 'vaadin-maven-plugin' in your build script. Otherwise, you can skip this error either by disabling production mode, or by setting the servlet parameter 'original.frontend.resources=true'.
```

Vaadin plugin is obsviouly enabled, just skipping ES5, but this error happens anyway. ES5 support is pretty useless for me, so I would like to avoid having to compile it.

Can you fix this bug, please?

**Comment by anasmi** [comment]
Hi, 

this repository is for Vaadin 8 related issue. I have moved the issue to the /flow as it will get more attention there. Please, follow the status there. I will close this one. Thank you for reporting the issue through! :)

**Comment by brunojcm** [comment]
Thanks!

**Comment by anasmi** [comment]
No problem :)
