### ISSUE TITLE
Setting new DataSource to existing Grid leads to "DataChangeHandler can't be null" exception in Browser

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/framework#11500]
https://github.com/vaadin/framework/blob/f11ea958cce7a3b273bc041e6a20a399dd23e6ac/compatibility-client/src/main/java/com/vaadin/v7/client/widgets/Grid.java#L7027

To remove the obsolete DataChangeHandler the grid shouldn't empty the handler list by calling the method addDataChangeHandler with "null". This leads to an "DataChangeHandler can't be null" exception in ListDataSource.

Instead **set** the DataChangeHandler to null or remove them accordingly.

**Comment by anasmi** [comment]
Fixid by this https://github.com/vaadin/framework/commit/7cd94ce0b02bb4ecd7826283d3928e3a66e39301 ,

**Comment by anasmi** [comment]
Fixed by this pull request https://github.com/vaadin/framework/pull/11473
