### ISSUE TITLE
Up and Down arrows do not work in Firefox 65

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#11502]
## Description of the bug

Navigation arrows do not work in UI components with Firefox 65.

Affected UI components:

- MenuBar
- Slider
- V7 Tree
- Table
- V7 Slider
- Calendar

Vaadin Framework version 8.0.* - 8.7.*
Browser version: Firefox 65.0+

## Minimal reproducible example

1. Open UI with Table / Slider / MenuBar component
2. Hit Up/Down arrow button in Table or in MenuBar (or left/right in Slider)

- Expected behavior

Arrow buttons should change selected row / value of component.

- Actual behavior

Nothing happens.

## Proposed fixes

We need to disable old workaround with key press event handlers for Firefox 65+:

https://github.com/cuba-platform/vaadin/commit/4d2df4a51afe3756bbc232b5758854c2a237e8e0

https://github.com/cuba-platform/vaadin/commit/83b786529e42c8b2b10348647587e48ddc384fe9

**Comment by TatuLund** [comment]
I think this issue is related to this one: https://github.com/vaadin/framework/issues/11465

**Comment by anasmi** [comment]
Hi,

as @TatuLund mentioned it's related to the same issue DateField has experienced. The correct way would be to remove the separate event handling of keypress for the Firefox as you seem to do in your branch. Through, do you now which version of FF exactly requires the workaround added? I've tested with 48 back then(the one, which was supported when 8.0.0 was released https://vaadin.com/download/release/8.0/8.0.0/release-notes.html ) and it's  working already there without the adjustments. The changes you proposed seems good to me, I am just wondering if you have found the case, where it actually breaks without the workaround from 2011 :) 
Also, do you want to create a pull request to the master branch? 

Through, thanks for bringing up this issue!

**Comment by jreznot** [comment]
> Hi,
> 
> as @TatuLund mentioned it's related to the same issue DateField has experienced. The correct way would be to remove the separate event handling of keypress for the Firefox as you seem to do in your branch. Through, do you now which version of FF exactly requires the workaround added? 

I believe we should not try to change the behavior for Firefox before 65 because it worked, so I've just added check for gecko version.

**Comment by anasmi** [comment]
It's definitely a safer way and I don't have anything against it. I was just wondering, if you know the version, where it requires the workaround :)
