### ISSUE TITLE
Potential XSS vulnerability with Panel caption

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#11521]
[panel-xss.zip](https://github.com/vaadin/framework/files/3022302/panel-xss.zip)

- Vaadin Framework version: 8.0.0-8.7.1
- Browser version: Any

- Description of the bug

1. Panel interprets caption as HTML by default.
2. Panel interprets caption as HTML even if we set `captionAsHtml` to `false` explicitly.

- Minimal reproducible example

UI code:
```java
@Theme("mytheme")
public class MyUI extends UI {
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        Panel panel = new Panel();
        panel.setWidth("200px");
        panel.setHeight("200px");

        panel.setCaption("<b>BOLD CAPTION</b><img src=x onerror=\"alert('persistent XSS attack');\">");

        // even if we set captionAsHtml to false explicitly
        panel.setCaptionAsHtml(false);

        panel.setContent(new VerticalLayout());
        
        setContent(panel);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

- Expected behavior

Panel must show caption `<b>BOLD CAPTION</b><img src=x onerror="alert('persistent XSS attack');">`.

- Actual behavior

It interprets caption as HTML and triggers passed JS code.

![Panel XSS](https://user-images.githubusercontent.com/1066152/55228436-80d89c80-5233-11e9-95ea-1543f4f8decd.png)

Relates to: https://github.com/cuba-platform/cuba/issues/1993

**Comment by TatuLund** [comment]
Thanks for pointing this out. I inspected the implementation of the Panel. Luckily this should be trivial to fix and I did pull request of proposed fix.
