### ISSUE TITLE
Warning messages for ConnectorTracker

### ISSUE THREAD

**Issue by gmarfia88** [vaadin/framework#11559]
Calling `com.vaadin.ui.AbstractComponentContainer#removeAllComponents` and `com.vaadin.ui.Table#removeAllItems `several messages like "com.vaadin.ui.ConnectorTracker [..] Tried to unregister _XXX_ which is not registered" are logged.

In addition, other messages like "com.vaadin.ui.ConnectorTracker : cleanConnectorMap unregistered connector XXX. This should have been done when the connector was detached." are also logged.

We are using Vaadin Version 8.7.2 compatibility mode.

**Comment by TatuLund** [comment]
Are you sure about that com.vaadin.ui.Table? With Vaadin 8 Table has been moved -> com.vaadin.v7.ui

**Comment by gmarfia88** [comment]
I have found the same problem in Vaadin 7.7.11 and Vaadin 8.7.2 compatibility mode. 

Let me know. 
Thanks.

**Comment by TatuLund** [comment]
Is it practically the same one than this https://github.com/vaadin/framework/issues/8723 ?

**Comment by gmarfia88** [comment]
Not exactly. I have two cases:

1) In the first I receive this message: "com.vaadin.ui.ConnectorTracker [..] Tried to unregister XXX which is not registered" and there isn't a Grid component
2) In the second this: "com.vaadin.ui.ConnectorTracker : cleanConnectorMap unregistered connector XXX. This should have been done when the connector was detached."

Thanks.

**Comment by Ansku** [comment]
I couldn't reproduce this with either 7.7-SNAPSHOT or 8.12-SNAPSHOT so this has either got fixed in the meantime or more information is required.
