### ISSUE TITLE
Creating add-on for Grid Editor

### ISSUE THREAD

**Issue by AlexByte** [vaadin/framework#11590]
Is it possible to override this line using add-on? https://github.com/vaadin/framework/blob/543a842e673f74b4053bcd22d1603bc3a84e6534/server/src/main/java/com/vaadin/ui/components/grid/EditorImpl.java#L134

**Comment by TatuLund** [comment]
I think this question would be better addressed as[Forum discussion](https://vaadin.com/forum). Could you start thread there and also tell more what and why your trying to achieve by this. There could be alternative approaches as well.

**Comment by TatuLund** [comment]
Closed by https://github.com/vaadin/framework/pull/11574
