### ISSUE TITLE
Notification object cannot be reused

### ISSUE THREAD

**Issue by lubomirmatus** [vaadin/framework#11594]
Hi

I'm using vaadin framework 8.8.0, on win7 x64, tomee 7.

I'm trying to use `Notification` according to `Valo Theme Test` [demo](https://demo.vaadin.com/valo-theme/#!common) and it's source code. But I'm getting exceptions when the notification object is used second time.

Example:
```
class MyView ... {
  private Notification n;
  private Button b;

  // ...

  private void build() {
    n = new Notification("");
    n.setDescription("Hello notification");

    b = new Button("Click me");
    b.addClickListener(e -> {
      n.show(Page.getCurrent()); // first time shows, second time raises exception
    });
  }
```
Exception:
```
java.lang.IllegalStateException: An extension can not be set to extend a new target after getting detached from the previous.
	at com.vaadin.server.AbstractExtension.setParent(AbstractExtension.java:88)
	at com.vaadin.server.AbstractClientConnector.addExtension(AbstractClientConnector.java:588)
	at com.vaadin.server.AbstractExtension.extend(AbstractExtension.java:77)
	at com.vaadin.ui.Notification.show(Notification.java:393)
	at com.myUI.myView.lambda$1(myView.java:XXX)
...
```

I need to create new `Notification` object each time I want to show it.

**Comment by Legioth** [comment]
`Notification` was changed to work as an `Extension` for https://github.com/vaadin/framework/pull/10027. As a side effect, the same instance can no longer be reused.

There isn't really any easy way of avoiding this, but it would at least make sense to update the demo to do thing in a way that works with newer Vaadin versions.

**Comment by anasmi** [comment]
A demo page you have mentioned is for [Vaadin 7](https://demo.vaadin.com/valo-theme/#!common), but an example has to be fixed here indeed : https://demo.vaadin.com/sampler/#ui/interaction/notification

Thank you for reporting an issue!
