### ISSUE TITLE
Grid with no cells fails with "IllegalArgumentException: Row index (0) is above maximum (-1)" when `scrollTo()` is called

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#11603]
Vaadin 8.8.2. Building on top of the issue https://github.com/vaadin/framework/issues/11558 where the fix was not complete. Trying to scroll by using the `scrollTo()` still causes the stacktrace to appear in the browser.

**Comment by mvysny** [comment]
[vaadin8-app.zip](https://github.com/vaadin/framework/files/3223818/vaadin8-app.zip)

Compile the attached app, run it with `mvn jetty:run`, go to http://localhost:8080 and click the button. The browser's console will still contain the `IllegalArgumentException: Row index (0) is above maximum (-1)` exception.

**Comment by Ansku** [comment]
Grid does not allow scrolling to a row index that doesn't exist, the real issue here is that the error didn't happen on the server-side already. That was fixed in https://github.com/vaadin/framework/pull/11771 which will be included in 8.9.2 release.
