### ISSUE TITLE
Vaadin 8.8.2 produced "null.$_nullMethod" on compiled widgtset

### ISSUE THREAD

**Issue by renierr** [vaadin/framework#11612]
To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
8.8.2
- Browser version
not relevant - widgetset compile
- Web container name and version
not relevant - widgetset compile
- Description of the bug
Compiling the Widgetset produced "null.$nullMethod" on several locations in the compiled Javascript.

Here is a snipped from a compiled code (detailed output) - there are more placed where this is generated:
`_.com_google_gwt_user_client_ui_PopupPanel_autoHide = false;
_.com_google_gwt_user_client_ui_PopupPanel_autoHideOnHistoryEvents = false;
_.com_google_gwt_user_client_ui_PopupPanel_isAnimationEnabled = false;
_.com_google_gwt_user_client_ui_PopupPanel_isGlassEnabled = false;
_.com_google_gwt_user_client_ui_PopupPanel_leftPosition = 0;
_.com_google_gwt_user_client_ui_PopupPanel_modal = false;
_.com_google_gwt_user_client_ui_PopupPanel_previewAllNativeEvents = false;
_.com_google_gwt_user_client_ui_PopupPanel_showing = false;
_.com_google_gwt_user_client_ui_PopupPanel_topPosition = 0;
var com_google_gwt_user_client_ui_PopupPanel_impl;
var com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1user_1client_1ui_1PopupPanel_12_1classLit = java_lang_Class_createForClass__Ljava_lang_String_2Ljava_lang_String_2Lcom_google_gwt_core_client_JavaScriptObject_2Ljava_lang_Class_2Ljava_lang_Class_2($intern_290, 'PopupPanel', 217, com_google_gwt_lang_ClassLiteralHolder_Lcom_1google_1gwt_1user_1client_1ui_1SimplePanel_12_1classLit);
function com_google_gwt_user_client_ui_PopupPanel$1_$onResize__Lcom_google_gwt_user_client_ui_PopupPanel$1_2Lcom_google_gwt_event_logical_shared_ResizeEvent_2V(){
  var height, width_0, winHeight, winWidth;
  null.$_nullMethod();
  winWidth = (com_google_gwt_user_client_Window_$clinit__V() , com_google_gwt_dom_client_Document_$getClientWidth__Lcom_google_gwt_dom_client_Document_2I($doc));
  winHeight = com_google_gwt_dom_client_Document_$getClientHeight__Lcom_google_gwt_dom_client_Document_2I($doc);
  null.$_nullMethod((com_google_gwt_dom_client_Style$Display_$clinit__V() , $intern_141));
  null.$_nullMethod((com_google_gwt_dom_client_Style$Unit_$clinit__V() , $intern_333));
  null.$_nullMethod($intern_333);
  width_0 = com_google_gwt_dom_client_Document_$getScrollWidth__Lcom_google_gwt_dom_client_Document_2I($doc);
  height = com_google_gwt_dom_client_Document_$getScrollHeight__Lcom_google_gwt_dom_client_Document_2I($doc);
  null.$_nullMethod($wnd.Math.max(width_0, winWidth) + $intern_150);
  null.$_nullMethod($wnd.Math.max(height, winHeight) + $intern_150);
  null.$_nullMethod($intern_336);
}`

I searched for this and this seams GWT releated - issue there with draft compile
see: https://github.com/gwtproject/gwt/issues/9330

- Minimal reproducible example
compile without draft and look at the produces Widgetset

**Comment by renierr** [comment]
[vaadin-app.zip](https://github.com/vaadin/framework/files/3264890/vaadin-app.zip)
Here is a Demo App based on the Vaadin Maven artifact.
Compiled Widgetset has the obove "null.$_nullMethod" calls on several locations

**Comment by anasmi** [comment]
Hi,

I've tried your example and there is no error during compilation process thrown.
![compilation](https://user-images.githubusercontent.com/15248706/60154374-d0f1db80-97ef-11e9-9f86-f7fd9d480893.jpg)


 Also, trying to open your project in a browser and a `Widgetset is not found` error is shown/printed to server logs. You would need to specify in your `UI` a full path to a `AppWidgetset` like this : `@Widgetset("org.test.AppWidgetset")`

**Comment by renierr** [comment]
This issue is not about a compilation error.
The compiler produces wrong JavaScript code without errors.

Calling this generated functions inside the Browser (Javascript) will cause an error inside the Browser console. See reference ticket to gwt.

In short compilation work's but produces malicious JavaScript code.
In the demo the JavaScript code is not called but it's there search inside the widgetset after null.

**Comment by anasmi** [comment]
Alright, what is the exact file to look for? At least, can't seem to find any `null.$_nullMethod()` under the `target../Vaadin/widgetsets`
