### ISSUE TITLE
Add a CSS class to the Grid Editor when editing a selected row

### ISSUE THREAD

**Issue by gatanaso** [vaadin/framework#11634]
Update the vaadin grid editor to add a CSS class to the grid editor div to indicate that the current row being edited is `selected` (similarly to how the editor applies the CSS classes for `buffered` and `unbuffered` modes).

Having this class would enable users to style the editor differently based on whether a row is `selected` or not selected. For example, to apply a different background color, it could be used as:
```
.v-grid-editor-cells-selected {
 div {
  background: blue;
 }
}
```

**Comment by ZheSun88** [comment]
added to Framework since `8.9.0`
You could try it with Framework `8.9.0.alpha1` with add

```
        <repository>
            <id>vaadin-prereleases</id>
            <url>https://maven.vaadin.com/vaadin-prereleases</url>
        </repository>
```
to your `pom.xml`
