### ISSUE TITLE
ListSelect valueChanged event not firing in IE11 when upgraded to framework v8.8.5

### ISSUE THREAD

**Issue by fun-ruby** [vaadin/framework#11654]
UI behavior worked as expected with framework v8.7.2 in IE11.

Just upgraded to v8.8.5 and observed this bug in the same IE11 browser (identical browser settings).

Can confirm bug **is not** in Google Chrome v75.0.3770.100.

* Vaadin Framework version 8.8.5
* IE11 version 11.0.9600.19398
* Description of the bug
   * when list value is changed, dependent content (buttons, text, list content) are NOT updated.
* Expected behavior
   * dependent content are updated
* Actual behavior
   * dependent content stayed in their original state, as if list value had not changed.

**Comment by ZheSun88** [comment]
We made a fix (#11658) for a similar issue, which will be released with the next framework release

**Comment by fun-ruby** [comment]
@ZheSun88 that's great! Looking forward to the next release.

Thanks!
