### ISSUE TITLE
Vaadin 8 TreeGrid - WidgetEvents of first column are handled regardless of setting Column.setHandleWidgetEvents 

### ISSUE THREAD

**Issue by SonReimer** [vaadin/framework#11663]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues for Vaadin Flow (Vaadin v10 Java Framework) should go to https://github.com/vaadin/flow

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
- Browser version
- Web container name and version
- Description of the bug
- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by SonReimer** [comment]
Version 8.8.5, Firefox 60.5.1esr,tomcat 8.0.41
A MenuBar is taken as component for a ComponentColumn. 
The grid has SelectionMode.SINGLE.
When clicking on the bar, I expect that the corresponding row should be toogled only, if Column.setHandleWidgetEvents is set to true which is not the case by default.
If I now click on the bar to open it, the selection of the corresponding row is toggled regardless of setting Column.setHandleWidgetEvents. Trying the same with a button, evryting is fine and setting of Column.setHandleWidgetEvents is recognized.

**Comment by SonReimer** [comment]
Example:
```
    TreeGrid<Object> grid = new TreeGrid(Object.class);
    
    ValueProvider<Object, Component> rowMenuValueProvider = new ValueProvider<Object, Component>() {
      
      @Override
      public Component apply(Object aSource) {
        Button button = new Button("Click");
        return button;
      }

    };
    grid.addComponentColumn(rowMenuValueProvider).setId("row1");
    grid.addComponentColumn(rowMenuValueProvider).setId("row2");
    grid.addColumn(object -> "object").setId("object");
    grid.setColumns("row1", "row2", "object");
    
    List<Object> items = new ArrayList<Object>();
    items.add(new Object());
    items.add(new Object());
    grid.setItems(items);

```

**Comment by TatuLund** [comment]
This could be on purpose, see: https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/treegrid/TreeGridConnector.java#L311

**Comment by SonReimer** [comment]
So it works as designed. Thx for your quick answer. A solution would be to create a separate column for the buttons.
