### ISSUE TITLE
Grid Editor is not opening at last row on 110% page scale

### ISSUE THREAD

**Issue by AlexByte** [vaadin/framework#11672]
- Vaadin Framework version
8.8.5
- Browser version
Chrome 75
- Description of the bug
Grid Editor is not opening at last row on 110% page scale on double click with mouse.
- Minimal reproducible example
https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/item-editor
![grid editor2](https://user-images.githubusercontent.com/25251772/62046594-fddf4700-b210-11e9-9713-511d72b112b1.gif)

- Expected behavior
Editor should be opened at last row on double mouse click at 110% page scale.
- Actual behavior
Editor is opening only after double click on last row and pulling the scroll bar to the end or and  scrolling up or and setting scale to 100%.

**Comment by TatuLund** [comment]
I tested this, and I could not reproduce the problem using Chrome Version 75.0.3770.142 (Official Build) (64-bit) and Windows 10

**Comment by AlexByte** [comment]
@TatuLund Can you record video? Have you tested at 110% scale?

**Comment by AlexByte** [comment]
I think this is due to the row bounce after scrolling to the end.
![scrolling](https://user-images.githubusercontent.com/25251772/62047496-50216780-b213-11e9-9fd4-fc3c41c195d8.gif)

**Comment by SonReimer** [comment]
This is the same under Firefox 60.7.0esr (64-Bit) with 100% scale using the Item Editor demo above

**Comment by Ansku** [comment]
There seems to be an uncaught client-side exception. `ScrollbarBundle.getScrollPos()` triggers an assertion error due expected and calculated scroll positions being one pixel off of each other, possibly thanks to the zoom causing a different rounding result.

**Comment by SonReimer** [comment]
After updating vaadin dependencies to 8.9.3 in my application and clearing the cache problem still resides in my application (with 100% scale). It's the same behavior with 
https://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/item-editor (with 100% scale)

**Comment by SonReimer** [comment]
I've tested this under Firefox Version 60.7.0esr (64-Bit) and Chrome Version 78.0.3904.108 (64-Bit)

**Comment by Ansku** [comment]
Hm, interesting. Now that we've got the sampler updated I can indeed still reproduce the problem there, but not in my local dev environment. I'll look into it.
