### ISSUE TITLE
The "See the complete list of changes since 8.8.4" link is wrong

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11680]
Link location: https://github.com/vaadin/framework/releases/tag/8.8.5

Link is: https://github.com/vaadin/framework/compare/8.8.4....8.8.5
Should be: https://github.com/vaadin/framework/compare/8.8.4..8.8.5

**Comment by ZheSun88** [comment]
Thanks for reporting this. updated. :-)
