### ISSUE TITLE
Grid.scrollTo is broken

### ISSUE THREAD

**Issue by evanzel** [vaadin/framework#11706]
Vaadin version: 8.9.0.beta3
Probably a side effect of #11438.
Grid.scrollTo(rowindex, ScrollDestination.START) just won't work.
It will clear the grid and won't scroll anywhere.

Minimal reproducible example:

```
Grid<Integer> grid = new Grid<>();
grid.addColumn(Integer::intValue).setCaption("number");
grid.setItems(IntStream.range(0, 100).boxed());
TextField tf = new TextField("row index", "50");
Button button = new Button("Scroll to above row index", (event) -> {
    int rowindex = Integer.parseInt(tf.getValue());
    grid.scrollTo(rowindex, ScrollDestination.START);
});
setContent(new VerticalLayout(tf, button, grid));
```

**Comment by harrwiss-swt** [comment]
If scrollTo is really broken, than it would be very important to fix this for Beta3

**Comment by TatuLund** [comment]
It seems that it is only Grid.scrollTo(rowindex, ScrollDestination.START) that is affected I tested

Grid.scrollTo(rowindex, ScrollDestination.ANY)
Grid.scrollTo(rowindex, ScrollDestination.END)
Grid.scrollTo(rowindex, ScrollDestination.MIDDLE)
and
Grid.scrollTo(rowindex)

And they work correctly.

**Comment by evanzel** [comment]
I tested ScrollDestination.END for small indexes, for rows that are initially displayed, and the result is not correct.
