### ISSUE TITLE
Push with websockets fails after reconnecting.

### ISSUE THREAD

**Issue by lennartfricke** [vaadin/framework#11702]
- Vaadin Framework version: 8.8.5
- Browser version: Firefox 68.0.2, Chrome 76.0.3809.132
- Web container name and version: jetty 9.4.14

## Description of the bug
  - start application
  - disconnect the network (pull cable)
  - wait until "Websocket closed" is logged into JS-Console
  - connect the network
  - Click the button
  - Nothing happens

```java
@Push(value = PushMode.MANUAL, transport = Transport.WEBSOCKET)
public class TestUI extends UI {

	private TextArea t;

	@Override
	protected void init(final VaadinRequest request) {

		setPollInterval(1000);

		final VerticalLayout layout = new VerticalLayout();
		final Button l = new Button("Click");
		t = new TextArea();
		l.addClickListener(e -> {
			t.setValue(t.getValue() + "\nTEST");
		}
		);
		layout.addComponent(l);
		layout.addComponent(t);

		setContent(layout);

	}
}
```

Expected TEST printed into TextArea.
Actual nothing happens.

We tracked the issue down into client-side code.
It seems that the active request tracking in MessageSender (hasActiveRequest field),
blocks further messages to be send to the websocket even after reconnect.
We found that, when push fails during send hasActiveRequest is true.
The only way to reset seems to be by giveUp in DefaultConnectionStateHandler
or receiving an answer.
After reconnect neither happens, but the server is waiting for a new request, thus
blocking the whole application.

We subclassed the DefaultConnectionStateHandler to reset hasActiveRequest after
reconnect using the following code:
```java
public class PatchedConnectionStateHandler extends DefaultConnectionStateHandler {

	@Override
	public void pushOk(final PushConnection pushConnection) {
		super.pushOk(pushConnection);

		final MessageSender messageSender = getConnection().getMessageSender();
		if (pushConnection.isBidirectional() && messageSender.hasActiveRequest()) {
			messageSender.endRequest();
		}
	}
}
```
which fixes the problem

This seems to be a duplicate of #7399

**Comment by TatuLund** [comment]
Thanks for the detailed description, it seems to make sense and the solution proposal. I value your effort and time working on this. I made a pull request to test this fix.

**Comment by TatuLund** [comment]
Possibly related to https://github.com/vaadin/framework/issues/7719 as well

**Comment by lennartfricke** [comment]
#11791 does not fix this issue. I just tried with current 8.9 branch and the code above and Firefox 70.0.1.

Please reopen.

**Comment by TatuLund** [comment]
> I just tried with current 8.9 branch

Which version exactly you tried? We have not yet made a release with this fix.

**Comment by lennartfricke** [comment]
I just used a fresh git checkout, checked out 8.9 and put the test code in uitests

**Comment by TatuLund** [comment]
And you managed to recompile the widgetset also? The fix is in clientside code.

**Comment by lennartfricke** [comment]
On my developer machine, there are only 8.9-SNAPSHOT packages on the local maven repo.
They match the js files found in the browser. So I believe they are recompiled. I also find the string:
"Dropping the response of a request before a resync request."

I started the UI using mvn jetty:run-exploded in the uitest subproject.

**Comment by TatuLund** [comment]
@lennartfricke Is it failing in your case in similar fashion than before the fix?

**Comment by lennartfricke** [comment]
It seems to be exactly the same behaviour as before.

**Comment by TatuLund** [comment]
> there are only 8.9-SNAPSHOT

Have you tried it with 8.10-SNAPSHOT?

**Comment by lennartfricke** [comment]
Should I?

**Comment by TatuLund** [comment]
Yes, 8.9-SNAPSHOT is decprecated.

**Comment by lennartfricke** [comment]
I tested after switching to master and recompiling vaadin-client-compiled and vaddin-compatibility-client, it is still the same.

**Comment by Ansku** [comment]
The fix is within the vaadin-client module, that must be compiled first.

**Comment by lennartfricke** [comment]
Hello, I really appreciate that you are looking into this issue
and did another fresh checkout and recompiled all modules using `mvn install` on the root project.
I also checked if the log message "Dropping the response of a request before a resync request.", that was introduced by your change, can be found in the compiled java script on the browser using the browser's developer tools and found it. What else do you need as confirmation that I tested with the a client side code containing the fix?

I would greatly appreciate if you tried reproducing the bug as well. It can be done quite easy by using the example code on the first post interactively using a browser in a VM and disconnecting the VM from the network for some time. I now once experienced vaadin falling back long polling.

**Comment by gatanaso** [comment]
Hello,

First of all thank you for the work you have done towards identifying and resolving this issue. 

We are using Vaadin version 8.9.4 and experienced an issue when using push (websocket-xhr). Namely after a call to `setTheme()` the client-server were not able to sync. For example, this is how the browser console looked after that operation:
![Screen Shot 2020-04-07 at 17 55 29](https://user-images.githubusercontent.com/15094658/78862520-3db52a00-7a40-11ea-98f3-ecd9bef210d0.png)

What helped with our issue was reverting to Vaadin version 8.9.0, after which this issue did not happen and push worked nicely. My assumption is that #11791 might have unintentionally caused this quirk in the client-server communication, however it would be nice if it could be further investigated.

**Comment by Ansku** [comment]
See also: #11299
