### ISSUE TITLE
Grid frozen column cell content html tags stripped

### ISSUE THREAD

**Issue by AndrasJanurik** [vaadin/framework#11716]
- Vaadin Framework version: 8.8.6
- Browser version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- Web container name and version: Tomcat 9.0.24

- Description of the bug:
I upgraded from 8.8.3 to 8.8.6.
Now the the html tags are missing from (only) the frozen columns of the grid, the rest of the columns are fine.
I can give you some sample html outputs of a frozen column cell.
8.8.3:
`<td class="v-grid-cell frozen last-frozen v-grid-cell-focused" role="gridcell" colspan="1" style="height: 28px; width: 248.469px; transform: translate3d(0px, 0px, 0px);"><span class="grid-highlight1">Cell content text...</span></td>`
8.8.6:
`<td class="v-grid-cell frozen last-frozen v-grid-cell-focused" role="gridcell" colspan="1" style="height: 28px; width: 308.203px; transform: translate3d(0px, 0px, 0px);">Cell content text...</td>`

Expected cell content: `<span class="grid-highlight1">Cell content text...</span>`
Actual cell content: Cell content text...

Maybe it has something to do with 8.8.5 where the release notes says it has a bug fix: Sanitize caption used in Grid header. Just a guess.

**Comment by TatuLund** [comment]
> Maybe it has something to do with 8.8.5 where the release notes says it has a bug fix: Sanitize caption used in Grid header. Just a guess.

That change is applied only to header captions, not Grid body cells

**Comment by TatuLund** [comment]
Could you add screenshots before / after and code that reproduces the problem.

In Grid body cells you should have HtmlRenderer inorder to have html content there.

**Comment by AndrasJanurik** [comment]
Sorry, I had more time to investigate and I realized that I was loosing html content from the grid header when using the `column.getCaption()` which returned the full html caption in 8.8.3, but not in 8.8.6 since it is now sanitized (8.8.5). Closing the issue.
