### ISSUE TITLE
Misaligned list builder parts in Chrome

### ISSUE THREAD

**Issue by edler-san** [vaadin/framework#11712]
This is an issue with at least 8.8.6 and 8.9.0.beta3 as can be seen on https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/list-builder

Chrome 76.0.3809.132 (Offizieller Build) (64-Bit) is used. Firefox is unaffected.
![image](https://user-images.githubusercontent.com/19165931/64328087-2525f280-cfcd-11e9-999a-649899316d26.png)

Especially in larger list this can render a complete UI useless (version 8.8.6 here) 
![image](https://user-images.githubusercontent.com/19165931/64328172-44248480-cfcd-11e9-9d08-879508022815.png)

**Comment by alexandru78** [comment]
same happens on vaadin 7

**Comment by TatuLund** [comment]
This looks like issue due some recent change in Chrome, there has not been changes in the code of this component lately, that could explain this.

**Comment by TatuLund** [comment]
For some reason the problem does not happen on my computer Chrome: Version 76.0.3809.132 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/14309836/64430374-d9ed0c00-d0c0-11e9-9110-e95b5da2bb0b.png)

**Comment by knoobie** [comment]
I could reproduce the misalignment with chromium on ubuntu. My windows 7 and MacOS didn't have the error.

**Comment by TatuLund** [comment]
I tested this with another Windows 10 PC with Chrome, and there the issue happens. This makes the problem really weird

![image](https://user-images.githubusercontent.com/14309836/64489048-5f0a2980-d257-11e9-8f1a-af164e3126e5.png)

Also I inspected the DOM with dev tools, and v-select-twincol-buttons does have correct styles, most importantly "vertical-align: top" is there, but Chrome just does not honor it in this case. Which makes the problem extremely hard to solve

![image](https://user-images.githubusercontent.com/14309836/64489068-8a8d1400-d257-11e9-8b23-f4f97a34d283.png)

**Comment by TatuLund** [comment]
There is an issue reported in Chromium bug tracker that seem to match the conditions of our observed issue

https://bugs.chromium.org/p/chromium/issues/detail?id=1001664&q=vertical-align&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by TatuLund** [comment]
The ticket I linked has the following workaround "Disabling LayoutNG in chrome://flags returns correct behavior."

I tested the above hint on my computer, and it indeed seems to fix the problem.

**Comment by jontto** [comment]
I can confirm that this workaround works for our Vaadin 8.8.6 based application also (although I don't like this workaround...)

**Comment by TatuLund** [comment]
As there were comment in Chromium bug tracker "approved for merge to M78, branch:3904" I tested this today with Chrome 78 having LayoutNG enabled, and the problem seem to have disappeared.
