### ISSUE TITLE
Too many UI instances are created in Session Replication environment, which causes Push feature doesn't work

### ISSUE THREAD

**Issue by yurili8** [vaadin/framework#11726]
- Vaadin Framework version: 8.9.0
- Browser version: Chrome 75
- Web container name and version: SpringBoot 2.16

To support the HA, I already modify my project to do the session replication, which will saved to Redis for all the session data, include the VaadinSession instance, which contains the UI instances.
So, it is working as following:
1. save the data in the session to Redis before the request ends.
2. deserialize the data from redis.
3. create new session instance based on the deserialized httpsession, all the UI instances are created.
4. after that, the push connection will be closed for the old UI instances. and new one connected.
5. If user click "refresh" button, also, many UI instances will be created. and it will repeat the step 4.
6. when background logic try to refresh the UI components, the push doesn't work. because there are too many UI instances in the container with the same name, the one try to refresh is not the latest one, the connection already lost. Also all the UI instances has the session instance, namely if you call the "isAttached", it will return true.

7. On every action in the page, it will try to repeat the step4.

I think this is a bug problem in the HA environment.
Actually I only setup one server node currently.

**Comment by TatuLund** [comment]
Please check the comment by Artur in this pull request discussion https://github.com/vaadin/framework/pull/9189 related to issue https://github.com/vaadin/framework/issues/9188
