### ISSUE TITLE
Grid.scrollTo(0, ScrollDestination.MIDDLE) is broken

### ISSUE THREAD

**Issue by michaelgmoretti** [vaadin/framework#11732]
- Vaadin Framework version:  8.9.0
- Browser version:  Google Chrome version 77.0.3865.90 (Official Build) (64-bit)
- Web container name and version:  Apache Tomcat 9.0.22 
- Description of the bug:
After executing Grid.scrollTo(0, ScrollDestination.MIDDLE) on a Grid with 2 items, the 2nd item disappears!
- Minimal reproducible example:
Add 2 items to a Grid, then call Grid.scrollTo(0, ScrollDestination.MIDDLE)
- Expected behavior:  All rows should be visible.
- Actual behavior:  2nd row disappears.

Note that this is not a bug in version 8.8.6, only 8.9.0.

**Comment by TatuLund** [comment]
This is probably regression from https://github.com/vaadin/framework/pull/11438 similar to https://github.com/vaadin/framework/issues/11706
