### ISSUE TITLE
Grid disappear totally after select an item from comboBox - Vaadin 14

### ISSUE THREAD

**Issue by Danuta97** [vaadin/framework#11747]
Hello! I'm using a grid to display data. When I click on a grid row it opens a dialog where i'm editing the selected row. When I select a value from a comboBox and press confirm to save changes **the grid disappears totally**. I saw that this problem appears **only in Chrome browser**
. How can I fix this problem? (I attached a print screen with the grid with opened dialog for editing and another one with the grid after i pressed confirm button in the dialog)

Thanks!

![dialog](https://user-images.githubusercontent.com/44115275/66651384-8fb8f680-ec3b-11e9-8980-76c7a2200ba4.png)
![nogrid](https://user-images.githubusercontent.com/44115275/66651385-8fb8f680-ec3b-11e9-89b0-08f06086e434.png)

**Comment by TatuLund** [comment]
Hi, thanks for the report, we have transfered this report to another issue tracker where it belongs https://github.com/vaadin/vaadin-grid-flow/issues/788
