### ISSUE TITLE
DataProvider.refreshItem, KeyMapper thread-safety

### ISSUE THREAD

**Issue by lennartfricke** [vaadin/framework#11796]
Vaadin Framework version: 8.8.5
Browser version: Firefox 68.0.2, Chrome 76.0.3809.132
Web container name and version: jetty 9.4.14

# Bug Description
We experience random Exceptions in the form of:
```
Caused by: java.lang.NullPointerException: Cannot provide an id for a null item.
at java.util.Objects.requireNonNull(Objects.java:228)
at DataProvider.getId (removed our class names)
at com.vaadin.ui.components.grid.MultiSelectionModelImpl.lambda$updateSelection$4(MultiSelectionMod
elImpl.java:424)
at java.util.Collection.removeIf(Collection.java:414)
at com.vaadin.ui.components.grid.MultiSelectionModelImpl.updateSelection(MultiSelectionModelImpl.ja
va:423)
at com.vaadin.ui.components.grid.MultiSelectionModelImpl$GridMultiSelectServerRpcImpl.select(MultiS
electionModelImpl.java:54)
```

when selecting item in a grid, whose `DataProvider.refreshItem` method is called from a background thread, that we use to load slow loading data asynchronously.

Debugging and instrumentation brought me to the point, that we suspect the following:
- The null item comes from `KeyMapper.get`
- There is no null item explicitly put into the KeyMapper
- There are two threads calling methods of KeyMapper
- There is a chance that KeyMapper.refresh and KeyMapper.key, maybe also KeyMapper.remove interfere
- Thus the keyObjectMap might be left in an inconsistent state

Unfortunately we cannot reproduce the problem during testing.

# Questions

The source code of DataCommunicator.attachDataProviderListener let's me think, that it refreshItem should be thread-safe. Is that even the case? Or is it expected to hold the session lock during calling DataProvider.refreshItem?

If the DataProviderListener in the DataCommunicator should be thread-safe. There are at least three synchronization errors:
```java
        dataProviderUpdateRegistration = getDataProvider()
                .addDataProviderListener(event -> {
                    if (event instanceof DataRefreshEvent) {
                        T item = ((DataRefreshEvent<T>) event).getItem();
                        getKeyMapper().refresh(item); // 2. access to key mapper is not guarded nor thread-safe
                        generators.forEach(g -> g.refreshData(item)); // 3. generators also hold state and are might not be thread-safe
                        getUI().access(() -> refresh(item));
                    } else {
                        reset = true; // 1. reset is not guarded nor volatile
                        getUI().access(() -> markAsDirty());
                    }
                });
```

It should be noted that these issues were introduced by a single change: 2f6f2970bc8ea8bb7d4745b9e87255874ef9fb5e

We are now trying to workaround it by adding synchronization to the KeyMapper, as obtaining
the session lock in the DataProvider is difficult as the UI is not known in advance.
I will report if that makes the exception disappear.

But it does not remove all issues above, so I'm also asking for a clarification from your side. Thank you very much.

**Comment by TatuLund** [comment]
> when selecting item in a grid, whose DataProvider.refreshItem method is called from a background thread, that we use to load slow loading data asynchronously.

If you call DataProvider.refreshItem or DataProvider.refreshAll from background thread, that should always be done in application in runnable via UI.access(). It is access that takes care of locking. If you use those methods without UI.access() you will run in the troubles as you have noticed.

**Comment by lennartfricke** [comment]
Ok.

What is irritating is, that in the code of attachDataProviderListener displayed above, also UI.access is used. Moreover change 5708366ebf49e1c5c800b4684a735d1cd1868772 indicates, that there at least once was the intent to be able to share DataProviders between multiple UIs.

But if that is not the case I know how to workaround.

**Comment by TatuLund** [comment]
Thanks for your reply. To clarify, your referenced commit is related to use special case of having multiple browser tabs in same session (each tab is an UI) and not access from background thread.

**Comment by lennartfricke** [comment]
Is it ok to ask you just to fully understand? What would happen if the two access functions in above doe are replaced by unguarded calls refresh(item) and markAsDirty().

**Comment by TatuLund** [comment]
These will trigger e.g. Grid to update itself in UI, and for example ConcurrentModifictionException could occur.

**Comment by lennartfricke** [comment]
I really do not get it.


If I'm as the caller of refreshItem or refreshAll has to make sure that a session lock is hold, why does the code in the listener of the DataCommunicator also tries to get hold of the lock, by using UI.access()?
Said differently the UI.access calls would prevent ConcurrentModifictionExceptions, that are impossible already prevented by using UI.access at the call side of refreshItem/refreshAll that fire the events.




Or this there something else about the UI.access call e.g. setting current UI?

**Comment by lennartfricke** [comment]
Unfortunately I didn't get any reply until now.

Just wanted to say that I understand that I need to hold the session lock, that is the usual policy.
I'm little disappointed about it, because DataProvider is not "attached" to any UI or Session as other GUI elements. And hoped that the code I showed could be expanded so that locking is done in the listeners, if necessary. If that is not the case, I'm okay with it and you can close the issue.

I also corrected spelling mistakes in the comment above and I'm still curious why the UI.access is needed in the listener code.

Thank you.

**Comment by TatuLund** [comment]
>  I'm still curious why the UI.access is needed in the listener code.

DataProvider is calling the UI component as I tried to explain here https://github.com/vaadin/framework/issues/11796#issuecomment-551590622

> If that is not the case, I'm okay with it and you can close the issue.

Yes, I will close.
