### ISSUE TITLE
Add setButtonCaptionAsHtml method to Upload component

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11810]
- Vaadin Framework version (e.g. 8.9.2)

Upload button component allows me to customize caption on the upload button only with strings. It is not possible to set arbitrary html into it. 

I want to be able to do this:
````java
Upload upload = new Upload(null, this::receiveUpload);
upload.setButtonCaptionAsHtml(true);
upload.setButtonCaption(VaadinIcons.UPLOAD.getHtml());
````

And see this on screen:
![image](https://user-images.githubusercontent.com/618879/68773712-543f8c80-062c-11ea-9121-a904e7cbbfdf.png)

Normal buttons have such functionality.

**Comment by TatuLund** [comment]
This feature has been also implemented in https://vaadin.com/directory/component/uploadbutton-add-on
