### ISSUE TITLE
Tree expand/collapse stops responding if the expand/collapse arrow is clicked when the Tree is disabled

### ISSUE THREAD

**Issue by mlindfors** [vaadin/framework#11822]
The following happens with Vaadin 8.9.2, tested on Firefox 70.0.1, Chrome 78.0.3904.97, and Safari 12.1.2:
If a Tree is disabled and the node expand/collapse arrow is clicked, it causes the expand/collapse functionality to stop working even when the Tree is subsequently enabled.

Let's take the following VaadinUI init:
```
    @Override
    protected void init(VaadinRequest request) {
        VerticalLayout layout = new VerticalLayout();
        setContent(layout);
        
        Tree<String> tree = new Tree<>();
        TreeData<String> treeData = new TreeData<>();
        String parent1 = "Parent 1";
        treeData.addItem(null, parent1);
        treeData.addItem(parent1, "Child 1.1");
        treeData.addItem(parent1, "Child 1.2");
        treeData.addItem(parent1, "Child 1.3");
        String parent2 = "Parent 2";
        treeData.addItem(null, parent2);
        treeData.addItem(parent2, "Child 2.1");
        treeData.addItem(parent2, "Child 2.2");
        treeData.addItem(parent2, "Child 2.3");
        String parent3 = "Parent 3";
        treeData.addItem(null, parent3);
        treeData.addItem(parent3, "Child 3.1");
        treeData.addItem(parent3, "Child 3.2");
        treeData.addItem(parent3, "Child 3.3");
        tree.setTreeData(treeData);
        
        Button button = new Button("Change status");
        button.addClickListener(event -> {
           tree.setEnabled(!tree.isEnabled());
        });
        
        layout.addComponent(tree);
        layout.addComponent(button);
        
        tree.setEnabled(false);
    }
```
Steps to reproduce:
- run the UI
- click one of the expand/collapse arrows
- press the "Change status" button, which enables the Tree
- try to expand a node

Expected behaviour:
- the node expands and collapses when the Tree is enabled

Actual behaviour:
- the expand/collapse arrow is unresponsive even when the Tree is enabled

Also note that the Tree is disabled when the UI is initialised, yet the styling doesn't reflect this. The proper disabled style is visible only after the Tree has been enabled and then disabled once.

**Comment by Ansku** [comment]
TreeGrid also has this same issue.
