### ISSUE TITLE
Fix 11506 fixed only portion of 11502

### ISSUE THREAD

**Issue by Enerccio** [vaadin/framework#11844]
Just by static analysis of the source code, bug  #11502 which was fixed in vaadin8+ via #11503 is "fixed" by #11506, for some reason only doing the fix in VSlider, keeping VScrollTable among others unfixed, why?

**Comment by TatuLund** [comment]
Yes, because VScrollTable is fixed by https://github.com/vaadin/framework/pull/11508

**Comment by Enerccio** [comment]
https://mvnrepository.com/artifact/com.vaadin/vaadin-client/7.7.17 does not contain the fix then, weird

**Comment by Enerccio** [comment]
Ok nvm, the maven version is just horribly, horribly outdated :)

**Comment by TatuLund** [comment]
@Enerccio , yes, and there is natural explanation for that. Vaadin 7 free support ended February 2019, and we have not released public updates after that. We have however customers subscribing to commercial extended maintenance of Vaadin 7, who will receive updated versions via other channels. You can find more information about it here: https://vaadin.com/pricing

**Comment by Enerccio** [comment]
ah makes sense. I built it from sources myself
