### ISSUE TITLE
addLayoutClickListener (in VerticalLayout) is called only for double-click

### ISSUE THREAD

**Issue by ropoman** [vaadin/framework#11850]
addLayoutClickListener(e->{
				doSomething();
			});
- Vaadin Framework version 8.9.3
The listener is called for double-clicks only. I am sure this worked for single clicks at some point in an older version of Vaadin

**Comment by TatuLund** [comment]
I tried this on my test app with Vaadin 8.9.3 and event did happen also for single clicks, i.e. I cannot reproduce the problem.

**Comment by ropoman** [comment]
Sorry for wasting your time. It turns out the problem was cookiebot.com
