### ISSUE TITLE
vaadin 8.9.3 - maybe grid spacer broken on grid with HeightMode.UNDEFINED

### ISSUE THREAD

**Issue by alexandru78** [vaadin/framework#11856]
- Vaadin Framework version 8.9.3
- Browser version Chrome 79.0.3945.88
- Web container name and version Jetty 9.4.22
- Description of the bug
Grid detail often shows a white band that covers part of the detail.
- Minimal reproducible example
<pre>
    private BGrid createPlanningsGrid() {
        BGrid result = new BGrid<>(context);
        result.setSizeFull();
        result.setHeightMode(HeightMode.UNDEFINED);
        result.setSelectionMode(Grid.SelectionMode.SINGLE);
        result.addSelectionListener(event -> {
            result.getBDataProvider().getItems().forEach(item -> result.setDetailsVisible(item, false));
            final Set selection = event.getAllSelectedItems();
            if (CollectionUtils.isNotEmpty(selection)) {
                result.setDetailsVisible(selection.iterator().next(), true);
                result.scrollTo(selection.iterator().next());
            }
        });
        result.setDetailsGenerator(rowReference -> new VerticalLayout(new Label("I disappear")));
        return result;
    }
</pre>
- Expected behavior
to see the detail without white bands, like it was in vaadin 8.8.6
- Actual behavior
there is a white band covering part of the detail
<img width="1103" alt="devtools" src="https://user-images.githubusercontent.com/12274745/71385892-62e57000-25ea-11ea-94f9-1becf2b4e4aa.png">
<img width="1133" alt="vaadin8 8 6" src="https://user-images.githubusercontent.com/12274745/71385893-62e57000-25ea-11ea-9364-a6c658e35cdf.png">
<img width="1135" alt="vaadin8 9 3" src="https://user-images.githubusercontent.com/12274745/71385895-637e0680-25ea-11ea-8926-af746e026072.png">

**Comment by TatuLund** [comment]
I managed to replicate the problem on one of my test apps with Vaadin 8.9.4. This bug is apparently a regression due improvements made for details row handling in Vaadin 8.9.0.

@alexandru78  Just noting. Your example code for reproducing the problem is not sufficient. Requirement for minimal reproducible example is to be self sufficient and not containing custom classes or 3rd party libraries.

**Comment by alexandru78** [comment]
> @alexandru78 Just noting. Your example code for reproducing the problem is not sufficient. Requirement for minimal reproducible example is to be self sufficient and not containing custom classes or 3rd party libraries.

first of all thank you for taking a look and for pointing it out.
you're right. I apologise for the mistake. should I delete it or may I label it with something similar to "My grid is similar to:"?
