### ISSUE TITLE
ComboBox Improvement (#11852) Causing other issues

### ISSUE THREAD

**Issue by dyachera** [vaadin/framework#11866]
I just recently updated to 8.9.4 and it looks like fix #11852 caused the combo box on one of my windows to no longer function correctly so I cannot upgrade to latest. Before this I had a combobox on a window in a horizontalLayout at the very bottom of the window and when you opened up the options the select options rendered above the combobox so you could see all available options. After upgrading to 8.9.4 when I go to click on the comboBox I can only see one option and all the others render off the screen below the combobox. I have to hover over the first option and press the down arrow key in order for them to be shown as the window shrinks in height. This does not happen in 8.9.3 or 8.9.2

**Comment by Ansku** [comment]
Could you add a simple test case that reproduces this issue? When I try it out, if the Window is at the bottom of the screen the options open above as usual, and if the Window is in the middle of the screen the options open below (beyond the limits of the Window). This happens whether I use mouse to open the popup with all the options or start writing into the input field to get the filtered options. In my current test I have VerticalLayout as the main content of the Window, and the last component within the VerticalLayout is a HorizontalLayout that contains the ComboBox.

**Comment by dyachera** [comment]
Sure I will look into extracting a simple case today.  In the current setup it is a window With a verticalLayout as content and a panel on top of the horizontalLayout (which is in verticalLayout as well) to fill the content.  There is a bunch going on so I will and try to figure out a good minimum case

**Comment by dyachera** [comment]
Here is a quick example and screenshot, let me know if you needed anything else

[compare.pdf](https://github.com/vaadin/framework/files/4053726/compare.pdf)

```
public void test() {
		int screenHeight = Page.getCurrent().getBrowserWindowHeight() - 20;
		Window testWindow = new Window();
		
		VerticalLayout windowContent = new VerticalLayout();
		testWindow.setContent(windowContent);
		final Panel formPanel = new Panel();
		formPanel.setHeight(screenHeight - 100 + "px");
		VerticalLayout panelContent = new VerticalLayout();
		panelContent.setWidth("90%");
		panelContent.setMargin(false);

		formPanel.setContent(panelContent);
		windowContent.addComponent(formPanel);
		
		VerticalLayout formFooter = new VerticalLayout();
		formFooter.setHeight("70px");
		HorizontalLayout controlBar = new HorizontalLayout();
		controlBar.setMargin(false);
		controlBar.setSpacing(true);
		formFooter.addComponent(controlBar);
		ComboBox<String> testCombo = new ComboBox<String>();
		controlBar.addComponent(testCombo);
		ArrayList<String> testItems = new ArrayList<String>(
			    Arrays.asList("1", "2", "3", "4", "5", "6"));
		testCombo.setItems(testItems);
		Button closeButton = new Button("Close");
		closeButton.addClickListener(click -> testWindow.close());
		controlBar.addComponent(closeButton);
		windowContent.addComponent(formFooter);
		UI.getCurrent().addWindow(testWindow);
	}
```

**Comment by Ansku** [comment]
Thanks, I'll check it out.

**Comment by dyachera** [comment]
Was just wondering if there was any update on this issue, or if it is one that is going to be looked into.  I tried version 8.10.1 today and saw that everything was still rendering off screen.  Thanks

**Comment by TatuLund** [comment]
This is probably the same as this one https://github.com/vaadin/framework/issues/11894

**Comment by TatuLund** [comment]
This should be fixed by https://github.com/vaadin/framework/pull/11902

**Comment by Ansku** [comment]
> Was just wondering if there was any update on this issue, or if it is one that is going to be looked into. I tried version 8.10.1 today and saw that everything was still rendering off screen. Thanks

Sorry, I was still optimizing my fix a month ago when I landed on a longer sick leave. Tatu's solution does the trick but adds some unnecessary update cycles that I'm still hoping to get rid of.
