### ISSUE TITLE
Menu border is not straight on Chrome (mac OS)

### ISSUE THREAD

**Issue by echarlus** [vaadin/framework#11878]
On chrome (at least since version 77), the border drawn around menus titles is not straight, there is a small "staircase effect". 
I can still reproduce the issue with : 
Chrome Version 79.0.3945.130 (Build officiel) (64 bits)
Mac OS 10.14.6
Vaadin 8.9.4

To reproduce, go to https://demo.vaadin.com/sampler/#ui/interaction/menu-bar with chrome 78 or 79 on mac os and see the display of the right border when the menu is opened.
<img width="604" alt="Capture d’écran 2020-01-25 à 14 50 04" src="https://user-images.githubusercontent.com/7509875/73122204-776aae80-3f82-11ea-84a0-cd57c83a0b53.png">

I had reported this in early september 2019 but no fix has been provided.
See screenshot.

**Comment by netsrotr** [comment]
We also face that issue. It seems related to the Browser's handling of focus rectangles: we can reproduce the issue at Chrome (latest), but not at Firefox.

**Comment by TatuLund** [comment]
This is issue has been already reported in https://github.com/vaadin/framework/issues/11720, so I will close this as duplicate.
