### ISSUE TITLE
DateField range-end does not forbit dates after year 9999 correctly

### ISSUE THREAD

**Issue by cdir** [vaadin/framework#11881]
With vaadin 8.9.2 I have set `dateField.setRangeEnd(LocalDate.ofYearDay(9999, 365))`. 

When I open the small calendar pop-up with december 9999 the "next month" button is disabled. However the "next year" button is active and all days in year 10000+ are enabled.

I also expected a validation marker in the browser however I am confused about the javadoc:

``
If the value is set after this date (taking the resolution into account), the component will not validate.
``

**Comment by TatuLund** [comment]
I tried to replicate this issue, but I am not sure I could.

> When I open the small calendar pop-up with december 9999 the "next month" button is disabled. 

In my case the button is not disabled. I.e. I can browse the pop-up beyond boundaries both with month and year buttons.

> If the value is set after this date (taking the resolution into account), the component will not validate.

This however works as it shoyuld. If I click date that is beyond range end, the DateField will show error.

![image](https://user-images.githubusercontent.com/14309836/73837151-86225280-4819-11ea-8ff4-bedbf0e3e840.png)

**Comment by TatuLund** [comment]
I did some code inspection, and it looks like that in DateField is no feature that would restrict the use of the buttons depending on range start / end.

**Comment by cdir** [comment]
@TatuLund when I set range end to 31.1.8000 and open the date picker with that date I cannot navigate to the next month nor next year. But When I give range end to 31.12.9999 only next month button is disabled but not next year button.

With the validation message you are right. We had a server side validation that did not had a problem with the date and hence the server calls setComponentError(null) which overwrites the existing client-side message. But as far I can see there is no way to check server-side whether the transferred date is valid or not.

**Comment by TatuLund** [comment]
I found couple of issues in lexicographical comparison logic of the DateField range end and made proposal to fix.
