### ISSUE TITLE
HierarchicalQuery#getOffset always rerurns 0

### ISSUE THREAD

**Issue by yurili8** [vaadin/framework#11889]
Hi,
I'm using TreeGrid with a HierarchicalDataProvider, but HierarchicalQuery's offset is always equals 0 according to the following code

framework/server/src/main/java/com/vaadin/data/provider/HierarchyMapper.java 
Line 493 in 2d806a5 

Is there any bug or HierarchicalDataProvider shouldn't be used with very big trees?

**Comment by TatuLund** [comment]
Hi, I am closing this ticket as duplicate to #11447 in order to keep our bug tracker manageable.
