### ISSUE TITLE
Wrong Popup direction on ComboBox

### ISSUE THREAD

**Issue by BernhardWa** [vaadin/framework#11894]
The popup of a Combobox always open below even if there is actually no space. The Popup shown then is too small and not sowing all items as there is just not enough space (See attachment). This occurs with the Vaadin Versions 8.10.0 and 8.9.4
![Combobox](https://user-images.githubusercontent.com/53933601/74849844-82262280-5339-11ea-92ef-869f955bad41.png)

**Comment by TatuLund** [comment]
I tried to reproduce the problem with demo.vaadin.com/sampler by reducing the Window size so that ComboBox popup does not fit below, and it worked correctly by opening it on top of field. So I cannot reproduce this.

**Comment by BernhardWa** [comment]
Ok, May be I need to investigate this further but I can reproducte it and went back to the version 8.9.3 where it works fine for me. On the versions 8.10.0 and 8.9.4 the ComboBox always opens below, with 8.9.3 it opens on top. I check if i can find out more about this behaviour.

**Comment by BernhardWa** [comment]
I can reproducte it when I put the ComboBox in a HorizontalLayout. Then the Popup always opens blow the ComboBox instead of above.

**With HorizontalLayout** (Popup opens blow which is wrong)

![WithHorizontalLayout](https://user-images.githubusercontent.com/53933601/75136674-b1e07c00-56e5-11ea-9c7b-ad4325e37222.png)

Code:
```
public class InfoDialog extends Window {

  public InfoDialog() {
    setResizable(false);
    setCaption("Info");
    setWidth(200, Unit.PIXELS);

    ComboBox<Integer> comboBox = new ComboBox<>();
    comboBox.setItems(Arrays.asList(50, 100, 200, 500, 1000));
    comboBox.setValue(50);
    comboBox.setWidth(120, Unit.PIXELS);

    HorizontalLayout horizontalLayout = new HorizontalLayout();
    horizontalLayout.addComponent(comboBox);
		
    setContent(horizontalLayout);
  }
}
```


**Without HorizontalLayout:** (Looks correct)

![WithoutHorizontalLayout](https://user-images.githubusercontent.com/53933601/75136676-b3aa3f80-56e5-11ea-80d5-8c177c8d24ad.png)

Code:
```
public class InfoDialog extends Window {
  private static final long serialVersionUID = 1L;
	
  public InfoDialog() {
    setResizable(false);
    setCaption("Info");
    setWidth(200, Unit.PIXELS);
		
    ComboBox<Integer> comboBox = new ComboBox<>();
    comboBox.setItems(Arrays.asList(50, 100, 200, 500, 1000));
    comboBox.setValue(50);
    comboBox.setWidth(120, Unit.PIXELS);

//  HorizontalLayout horizontalLayout = new HorizontalLayout();
//  horizontalLayout.addComponent(comboBox);
		
    setContent(comboBox);
  }
}
```
