### ISSUE TITLE
Grid in VerticalLayout is broken after browser resize

### ISSUE THREAD

**Issue by ericflock** [vaadin/framework#11893]
To reproduce:
	
	@Override
	protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        final Grid grid = new Grid(GridExampleHelper.createContainer()); // container with at least 100 rows
        grid.setSizeFull();
        layout.addComponent(grid);
        layout.setSizeFull();
        layout.setExpandRatio(grid, 2);
        setContent(layout);
    }

1. set the browser window to not be maximized.
2. scroll down to the last row.

![vaadin-grid-issue1](https://user-images.githubusercontent.com/40864945/74842845-497f4c80-532b-11ea-968b-9d4e20660d4e.PNG)

3. resize the browser height and reduce it by the height of approximately one row.
4. scroll down again 

![vaadin-grid-issue2](https://user-images.githubusercontent.com/40864945/74842867-50a65a80-532b-11ea-82e8-ca497d94fc92.PNG)

		-> a row is missing.

5. scroll one row up again 

![vaadin-grid-issue3](https://user-images.githubusercontent.com/40864945/74842877-556b0e80-532b-11ea-9d2d-eecf73ac19ad.PNG)

		-> a duplicate row is visible

I reproduced it with Firefox 68.2.0esr and Chrome 80.0.3987.106
in vaadin 7.7.17

in vaadin 8+ it seems to be ok

**Comment by TatuLund** [comment]
I could not reproduce the issue. However it still could be related to https://github.com/vaadin/framework/issues/11892

**Comment by ij11** [comment]
It seems to be not related to the mentioned issue. We could provide some more details for reproducing the issue
