### ISSUE TITLE
No PopUp for empty DateField if current day is not in range

### ISSUE THREAD

**Issue by sevenzebras** [vaadin/framework#11895]
- Vaadin Framework version
8.10.0 (8.9.4 is not affected)
- Browser version
IE11, FF 68.5.0esr, Chrome 76.0.xx (probably all)
- Description of the bug
If the range of an empty DateField is set to a value that does not include the current day no datepicker popup is displayed on click. Instead only a small circle is shown. If you preset a date in range everything works fine. 
- Minimal reproducible example
```
       DateField from = new DateField("From:");
       from.setRangeStart(LocalDate.now().plusDays(1l));
       //OR
       from.setRangeEnd(LocalDate.now().minusDays(1l));
```
- Expected behavior
![grafik](https://user-images.githubusercontent.com/14329634/74855051-6ffbb280-5340-11ea-9e47-c7ca32827aad.png)

- Actual behavior
![grafik](https://user-images.githubusercontent.com/14329634/74854474-a97fee00-533f-11ea-9e69-ee4b41066519.png)

**Comment by TatuLund** [comment]
I did some testing and I can confirm the issue.

It also looks like that this is regression of this bug fix https://github.com/vaadin/framework/pull/11879
