### ISSUE TITLE
Criterion instances are not serialized correctly

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/framework#11909]
Vaadin Framework version: 8.10.2

Description of the bug
Set criteria in a DropTargetExtension instance will not be serialized and thus it won't be send to the client side.

Minimal reproducible example
```
public class DemoUI extends UI {

  @Override
  protected void init(VaadinRequest request) {
    Button button = new Button();
    button.setCaption("drag me");
    DragSourceExtension<Button> dragSource = new DragSourceExtension<>(button);
    dragSource.setPayload("test", "value");

    Button droparea = new Button();
    droparea.setCaption("drop here");
    DropTargetExtension<Button> dropTarget = new DropTargetExtension<>(droparea);
    dropTarget.addDropListener(e -> {
      System.out.println("droparea drop listener invoked (expected to happen)");
    });
    dropTarget.setDropCriterion("test", "value");

    Button droparea2 = new Button();
    droparea2.setCaption("drop not here");
    DropTargetExtension<Button> dropTarget2 = new DropTargetExtension<>(droparea2);
    dropTarget2.addDropListener(e -> {
      System.out.println("droparea2 drop listener invoked (should not happen)");
    });
    dropTarget2.setDropCriterion("test", "value2");

    VerticalLayout layout = new VerticalLayout(button, droparea, droparea2);
    setContent(layout);
  }
}
```

Initial loading of the demo application sends the following typical response to the browser.
```
{
  "v-uiId": 2,
  "uidl": "{'Vaadin-Security-Key':'58b59192-308b-4c59-977c-da659debcf9e','Vaadin-Push-ID':'f4712a96-50a7-47ff-a535-7f4c7bc581f4','syncId': 0, 'resynchronize': true, 'clientId': 0, 'changes' : [['change',{'pid':'16'},['0',{'id':'16'}]]], 'state':{'16':{'localeServiceState':{'localeData':[{'name':'en_US','monthNames':['January','February','March','April','May','June','July','August','September','October','November','December'],'shortMonthNames':['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],'shortDayNames':['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],'dayNames':['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],'firstDayOfWeek':0,'dateFormat':'M/d/yy','twelveHourClock':true,'hourMinuteDelimiter':':','am':'AM','pm':'PM'}]},'theme':'valo','height':'100.0%','width':'100.0%'},'17':{'spacing':true,'childData':{'18':{'alignmentBitmask':5,'expandRatio':0},'20':{'alignmentBitmask':5,'expandRatio':0},'22':{'alignmentBitmask':5,'expandRatio':0}},'marginsBitmask':15,'width':'100.0%'},'18':{'caption':'drag me'},'19':{'payload':{'test':{'key':'test','value':'value','valueType':'STRING'}},'registeredEventListeners':['dragstart','dragend']},'20':{'caption':'drop here'},'21':{'criteria':[{}]},'22':{'caption':'drop not here'},'23':{'criteria':[{}]}}, 'types':{'16':'0','17':'4','18':'1','19':'3','20':'1','21':'2','22':'1','23':'2'}, 'hierarchy':{'16':['17'],'17':['18','20','22'],'18':['19'],'20':['21'],'22':['23']}, 'rpc' : [], 'meta' : {'repaintAll':true}, 'resources' : {}, 'typeMappings' : { 'com.vaadin.ui.AbstractComponent' : 5 , 'com.vaadin.ui.AbstractOrderedLayout' : 6 , 'com.vaadin.ui.UI' : 7 , 'com.vaadin.ui.VerticalLayout' : 4 , 'com.vaadin.ui.AbstractSingleComponentContainer' : 8 , 'com.vaadin.server.AbstractExtension' : 9 , 'com.vaadin.ui.AbstractFocusable' : 10 , 'DemoUI' : 0 , 'com.vaadin.ui.Button' : 1 , 'com.vaadin.ui.AbstractLayout' : 11 , 'com.vaadin.ui.AbstractComponentContainer' : 12 , 'com.vaadin.server.AbstractClientConnector' : 13 , 'com.vaadin.ui.dnd.DropTargetExtension' : 2 , 'com.vaadin.ui.dnd.DragSourceExtension' : 3 }, 'typeInheritanceMap' : { '5' : 13 , '6' : 11 , '7' : 8 , '4' : 6 , '8' : 5 , '9' : 13 , '10' : 5 , '0' : 7 , '1' : 10 , '11' : 12 , '12' : 5 , '2' : 9 , '3' : 9 }, 'timings':[1171, 2]}"
}
```

Expected behavior
It is expected that the server serializes both Criterion instances correctly such that all related data such as key, value etc. is available to the client (browser).

Actual behavior
In the response above both Criterion instances have been serialized as
`'21':{'criteria':[{}]}` and `'23':{'criteria':[{}]}`.

**Comment by TatuLund** [comment]
I think this is the same as https://github.com/vaadin/framework/issues/9834

**Comment by muhammetaltindal** [comment]
@TatuLund the issue #9834 you have mentioned is specifically about the drag and drop mechanism of the TreeGrid. I have found the reason why the Criterion is not transferred to the client. The reason can be found in `com.vaadin.server.JsonCodec#getProperties`. However, I don't know if the following root cause of the serializing issue described here in #11909 also solves the issue #9834 you've mentioned.

This method will be called to find out which properties (basically class fields) and values of a certain instance of a certain class should be serialized/deserialized. It collects the target properties by finding target _method properties_ and target _field properties_ using the corresponding methods `MethodProperty.find(type)` and `FieldProperty.find(type)`. 

However, the method `MethodProperty.find(type)` only returns those method properties which do have a _read method_ *and* a _write method_ (basically, it only returns those where getter *and* setter are defined). The method `FieldProperty.find(type)` only returns those properties where the corresponding class field is *public*.

Now, in the Criterion there exists the fields `private String key` and `private String value`. Plus, there is only a getter `public String getKey()` and a getter `String getValue()` but there are *no* setter methods for the fields `key` and `value`. Hence, no properties at all will be serialized for the class `Criterion`.

How to try out:
1. Copy the source code of class `com.vaadin.shared.ui.dnd.criteria.Criterion` to your own project (keep same package).
1. Create setters `public void setKey(String key)` and `public void setValue(String value)`.
1. Start same minimal reproducible example demo app above.
1. The criteria data is serialized now correctly. You can observe this in the UIDL data send to the client 
`...\"21\":{\"criteria\":[{\"key\":\"test\",\"value\":\"value\"}]},...` and
`...\"23\":{\"criteria\":[{\"key\":\"test\",\"value\":\"value2\"}...`.
1. Remaining issue: the drop criteria feature still did not work for me. So, for the demo app above the drop listener in dropTarget2 has been called on the server side (after a drop on droparea2) although I expected it not to trigger.

**Comment by muhammetaltindal** [comment]
The setters for the fields `private ValueType valueType` and `private ComparisonOperator operator` also need to be added for proper serialization/deserialization on client side. Otherwise the method `com.vaadin.shared.ui.dnd.criteria.Criterion#resolve` will not work as expected on the client side. After adding all setters GWT recompilation is required.

Then the demo app works as expected, i.e. the drop listener of `dropTarget` is triggered and the drop listener of `dropTarget2` is not triggered when dropping the `button` onto `droparea` and `droparea2`.

**Comment by TatuLund** [comment]
@muhammetaltindal thanks for your detailed comments.
