### ISSUE TITLE
The `Page.open` method is on Firefox blocked by popup blocker. 

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11917]
- Vaadin Framework version:  8.10.0
- Browser version: Firefox 74.0 (64-bit)

- Description of the bug
The `Page.open` method is on Firefox blocked by popup blocker. The issue is only on Firefox, it works correctly in Edge and Chrome.

As a result, it is not possible to open new tab from java on the server side (from button callback). I know about `BrowserWindowOpener`, but that needs to know url in advance. I have to calculate url dynamically after button click.

- Minimal reproducible example
`ui.getPage().open("www.google.com", "_blank");`

- Expected behavior
Url opens in new tab.

- Actual behavior
Firefox prevents popup and shows warning.

**Comment by TatuLund** [comment]
Yes, this a known thing and `BrowserWindowOpener `exists because of the limitations of the browsers. I.e. they require user event to happen in order not to be block the opening of the new window / tab.

**Comment by SomMeri** [comment]
The `Page.open` is somehow working around that limitation in Chrome and Edge.  The BrowserWindowOpener does not allow me to dynamically calculate url, it has to be known before the user clicked. 

In javascript, there I can think of possible workarounds for Firefox too, (start interval that will periodically check some shared variable on whether url info came back from request), I hoped something like that would be in vaadin too.

**Comment by TatuLund** [comment]
> The Page.open is somehow working around that limitation in Chrome and Edge.

I do not think so. You may have accepted the popups in the browser. The same applies also in Vaadin 14. At least when I last time used it, Chrome blocked opening the window.

> The BrowserWindowOpener does not allow me to dynamically calculate url

This would be a new feature. There is at least one add-on which does something into that direction

https://vaadin.com/directory/component/enhanced-window-opener/

I do not know how it has been implemented.

**Comment by SomMeri** [comment]
Thank you very much for the suggestion,it seems to be what I am looking for. For anybody else:

Constructor
````java
		aaa = new EnhancedBrowserWindowOpener()
				.popupBlockerWorkaround(true)
				.doExtend(this);
````

inside onclick handler:
````java
		aaa.open("#!documents");
		aaa.open("http://www.google.com");
````


Btw, `BrowserWindowOpener ` really works for me on two separate computers. I am sure that chrome is blocking popups, because I tested how it works in javascript https://sommeri.github.io/simple-samples-js/open-link-in-new-tab/open-link-in-new-tab.html and popups got blocked. 

Thank you again.

**Comment by SomMeri** [comment]
The other extension first opens a window, then sends request and then changes url in that new window.
