### ISSUE TITLE
Vaadin push from a background thread with LONG_POLLING

### ISSUE THREAD

**Issue by neher** [vaadin/framework#11942]
Whenever we need to do some sort of calculations on a background thread, we show a modal popup window with progress and messages to give feedback to our users.

But with our current setup, (manual push, long polling as transport and animations disabled), these busy windows sometimes won't disappear.  They stay on the screen, and there is no way to close them.

I added an minimal reproducible example where you can see the bug in action.
[CloseWindowAsync.java.zip](https://github.com/vaadin/framework/files/4429192/CloseWindowAsync.java.zip)

- Vaadin Framework version : 8.10.0

- Expected behavior :
When you click on a button, the window should be closed.

- Actual behavior :
When you click on a button, the window is still open. And there is no way we can close it.

I found 2 workarounds in the above example.
If we enable the animations again or switch to websockets as transport, the windows close properly.
Unfortunately, I can't use either of these 2 workarounds in our program for different reasons.

**Comment by Ansku** [comment]
Seems like it breaks whenever the long-polling message reaches the client-side before the xhr message. Wasn't able to get it to happen at all on Chrome and on Firefox it took some trying, but with Edge it's relatively easy to reproduce. Haven't had time to look deeper into it yet to see what exactly goes wrong with the handling when the long-polling message is already pending for the xhr message to be dealt with first. I'm just about to start a vacation, though, so might be a while before I can give this a more thorough look.

**Comment by neher** [comment]
I could reproduce it every time with Firefox (version was 74.0.1 on ubuntu 18.04 when I created the issue)
