### ISSUE TITLE
Vaadin grid column appears shrinked in the production stage.

### ISSUE THREAD

**Issue by Krishuthapa** [vaadin/framework#11977]
I am using vaadin grid with lit-element. In the local environment, the vaadin grid after rendering recalculates the width and displays the content correctly. But in the production, the columns are shrunk and are not corrected even after the page refresh. The vaadin grid is used to render many customer elements and even canvas and I have 25 columns in it. How can I get solution to this issue? I have used auto-width attribute in the `<vaadin-grid-column>` and renderers to render content and headers.

**Comment by tomivirkki** [comment]
Do not double-post https://github.com/vaadin/vaadin-grid/issues/1721
