### ISSUE TITLE
Main window eats focus when moving focus away from modal popup with shift-tab

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1197]
**Originally by @henrikerola**

___
When trying to move focus with keyboard from a field in a modal window to browser's address bar, the main window gets the focus and keeps it. In the attached test application, after pressing shift-tab twice when focus is in the TextField, you cannot remove the focus from the main window with keyboard and for example adding a new tab with ctrl-t doesn't work. 

Tested with FF3.6, Safari 5 and IE8. See also #5495.

**Comment by torok-peter** [comment]
Fixed by #3960 .
