### ISSUE TITLE
Unhiding columns in Grid is now broken

### ISSUE THREAD

**Issue by evanzel** [vaadin/framework#11970]
### Description
On a Multiselectable Grid unhiding a column renders in its place the previous one.
 
Steps to reproduce:
Hide column 1 and then unhide it. checkboxes column appears in its place.
Hide column 2 and then unhide it. column 1 appears in its place.
likely a regression from https://github.com/vaadin/framework/pull/11967
### Minimal reproducible example:
```
    final VerticalLayout layout = new VerticalLayout();
        Grid<Integer> grid = new Grid<>();
        grid.setSelectionMode(Grid.SelectionMode.MULTI);
        grid.addColumn(i -> {
            return "col 1: " + i;
        }).setCaption("col #1").setHidable(true);
        grid.addColumn(i -> {
            return "col 2: " + i;
        }).setCaption("col #2").setHidable(true);
        grid.setItems(IntStream.range(0, 100).boxed());
        layout.addComponent(grid);
        setContent(layout);
```

**Comment by TatuLund** [comment]
@evanzel Thanks for reporting this promptly. The previous fix was indeed causing this regression.
