### ISSUE TITLE
Combobox - wrong popup menu positioning

### ISSUE THREAD

**Issue by AndreevXSoft** [vaadin/framework#12029]
Vaadin Framework version 8.11.0 and 8.10.5

While writing in the field and only one item matches, the popup menu is being positioned incorrectly.

![combobox_wrong_popup_position](https://user-images.githubusercontent.com/1454017/83643616-e7d0ae80-a5b8-11ea-8948-335da6a48d4b.png)

I guess this fix caused this problem: [https://github.com/vaadin/framework/issues/11894](https://github.com/vaadin/framework/issues/11894)

Version Vaadin 8.9.4 does not have this problem, but in this version when there is not enough space below for the popup menu, it does not show above.

**Comment by evanzel** [comment]
I stumbled upon the same ugliness.
When the popup is positioned above and then you continue with filtering the items and the number of filtered items is less than the pagelength the popup continues to be positioned at the same y position, so we get an empty space.
