### ISSUE TITLE
Vaadin 8.10.4 upgrade to Vaadin 8.11.0: the upload button invisible

### ISSUE THREAD

**Issue by CNBroderick** [vaadin/framework#12031]
Vaadin 8.10.4 upgrade to Vaadin 8.11.0: 
the server.droporchoose.UploadComponent --> upload button invisible.
back to 8.10.4 is worked

**Comment by TatuLund** [comment]
Thanks for reporting this. I think this is regression from one of the fixes and improvements made to Upload component in version 8.11.

**Comment by Ansku** [comment]
Would you happen to have a code example that reproduces this issue? I just tried creating a new project and adding this add-on according to the usage example in the Directory, and the button is where I'd expect to see it.

**Comment by CNBroderick** [comment]
Okay, I will reply you in 12 - 18 hours later, and I will use 8.11.1(lasted) if it bug can review.

**Comment by CNBroderick** [comment]
Flow is example code. The upload button caption can visible version <= 8.10.4 but invisible beyond 8.11.0, 8.11.1.

```Java
public class TestUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        setContent(new HorizontalLayout(
                new Label("Right is upload"),
                createUploadButton(),
                new Label("left is upload")

        ));
    }

    private Upload createUploadButton() {
        AtomicReference<File> file = new AtomicReference<>();
        Upload upload = new Upload(null, (filename, mimeType) -> {
            try {
                file.set(new File(System.getProperty("java.io.tmpdir") + File.separator + "abc.xlsx"));
                return new FileOutputStream(file.get());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
                return null;
            }
        });
        upload.setImmediateMode(true);
        upload.setAcceptMimeTypes("application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        upload.setButtonStyleName("v-button v-widget tiny v-button-tiny primary v-button-primary v-has-width");
        upload.setButtonCaption("upload Excel file");
        return upload;
    }
}
```

Flow is demo result screen (Lasted Edge):
![image](https://user-images.githubusercontent.com/27131135/87222802-aac2bd80-c3a9-11ea-9b3e-948645c2510c.png)

**Comment by Ansku** [comment]
I copy-pasted that to my test project as is and tested it on Chrome, Firefox, and Edge, and I can see the button with the expected text within the `v-button-caption` span in all of them. Is it possible that you are using an old/cached version of the widgetset? A mismatch between server and client version could explain why it's not displaying correctly to you. You can check the versions by adding `?debug` to the URL and checking what the second tab (with a little "i" icon) has to say.

**Comment by CNBroderick** [comment]
Yeah, I have always ignore before. I received this message, but it seems will disappear after a while. 
And not found a good method to solve it by google.

Until now i trying to execute mvn clean , jetty run.

Thanks, It's widgetset problems.

```
July 13, 2020 5:32:31 pm. com.vaadin.server.communication.ServerRpcHandler checkWidgetsetVersion
Warning: 
=================================================================
The widgetset in use does not seem to be built for the Vaadin
version in use. This might cause strange problems - a
recompile/deploy is strongly recommended.
 Vaadin version: 8.11.1
 Widgetset version: 8.10.4
=================================================================
```

Now, I tr

**Comment by Ansku** [comment]
If you run `mvn install` after `mvn clean`, that should fix the widgetset issue.
