### ISSUE TITLE
issue while trying to upgrade from vaadin 8 to vaadin 14 version

### ISSUE THREAD

**Issue by keshav105** [vaadin/framework#12030]
I followed the below link to upgrade.

https://vaadin.com/docs/mpr/introduction/step-1-migration-guide.html

Please find the attachment of pom.xml file.

Below error i can see when application try to starts :

. ____ _ __ _ _ /\ / ' __ _ () __ __ _ \ \ \
( ( )__ | '_ | '| | ' / ` | \ \ \
\/ __)| |)| | | | | || (| | ) ) ) ) ' || .__|| ||| |_, | / / / / =========||==============|/=//// :: Spring Boot :: (v2.1.9.RELEASE)

23:10:16.158 [localhost-startStop-1] INFO o.s.boot.StartupInfoLogger.logStarting 50 - Starting App on keshav-Latitude-E6540 with PID 6831 (/home/keshav/clone/unblur/unblur-webapp/target/unblur/WEB-INF/classes started by tomcat8 in /var/lib/tomcat8) 23:10:16.163 [localhost-startStop-1] INFO o.s.boot.SpringApplication.logStartupProfileInfo 652 - The following profiles are active: dev WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/keshav/clone/unblur/unblur-webapp/target/unblur/WEB-INF/lib/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int) WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release 23:10:17.070 [localhost-startStop-1] ERROR o.s.boot.SpringApplication.reportFailure 823 - Application run failed java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:181) at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141) at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327) at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151) at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131) at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91) at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5225) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1135) at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1870) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.vaadin.spring.security.config.AbstractVaadinSecurityConfiguration] from ClassLoader [ParallelWebappClassLoader context: unblur delegate: false ----------> Parent Classloader: java.net.URLClassLoader@15327b79 ] at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:507) at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:404) at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:417) at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:389) at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:447) at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:738) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:679) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:647) at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1518) at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1023) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:189) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:156) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.addBeanType(BeanTypeRegistry.java:149) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:137) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.updateTypesIfNecessary(BeanTypeRegistry.java:132) at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:96) at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:269) at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:262) at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:251) at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:171) at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:145) at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ... 30 common frames omitted

I feel this issue is because of spring boot version mismatch, but i am not able to get an appropriate version, please suggest the fix.

Thanks
KK,

[web_pom.pdf](https://github.com/vaadin/framework/files/4732466/web_pom.pdf)
[parent_pom.pdf](https://github.com/vaadin/framework/files/4732470/parent_pom.pdf)

Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues for Vaadin Flow (Vaadin v10 Java Framework) should go to https://github.com/vaadin/flow

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
- Browser version
- Web container name and version
- Description of the bug
- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by TatuLund** [comment]
> I feel this issue is because of spring boot version mismatch, but i am not able to get an appropriate version, please suggest the fix.

With Vaadin 14 you need to use Spring Boot 2+

**Comment by keshav105** [comment]
Thanks @TatuLund  for the reply but i can't see the 2+ Vaadin Spring Extensions version the latest i can see is 2.0.0  please check the below link :

https://mvnrepository.com/artifact/org.vaadin.spring.extensions 
https://mvnrepository.com/artifact/org.vaadin.spring.extensions/vaadin-spring-ext-security

Please let me know if you know any 2+ Vaadin Spring Extensions version for following dependencies
 1. vaadin-spring-ext-security
2.  vaadin-spring-ext-core
3. vaadin-spring-ext-boot
4. vaadin-spring-ext-test

**Comment by TatuLund** [comment]
> t i can't see the 2+ Vaadin Spring Extensions 

I did not refer to those, but Spring Boot itself.

When using MPR, you need to let vaadin-bom to define Vaadin spring add-on version.

See documentation https://vaadin.com/docs/v14/mpr/introduction/step-3-spring-boot.html
