### ISSUE TITLE
Vaadin 8 Grid goes blank after continous data filtering with PagedDataProvider 

### ISSUE THREAD

**Issue by Gowthami-BK** [vaadin/framework#12032]
Hi,

I am using vaadin 8 grid with pagination. When I keep changing the filter values for some period of time continously, the grid goes blank. 

Can any one please help me to solve this issue please?

- Vaadin Framework version (e.g. 8.1.0)

**Comment by TatuLund** [comment]
Thanks for the report, but more details are needed.

In the framework there is no PagedDataProvider, so could you check if this is related to an add-on. If so, I think this issue should be reported in the associated add-on repository instead.

Your report does not contain reproducible code example. This would be needed before issue can be inspected.
