### ISSUE TITLE
iPad/tablet vaadin-dialog-overlay scrolling not working

### ISSUE THREAD

**Issue by chirastefan** [vaadin/framework#12044]
the scrolling for `vaadin-dialog-overlay` component for iPad(Chrome/Safari)/tablet(Chrome) is not working, it only works with 2 fingers and in that case, it's buggy, 
tried adding `-webkit-overflow-scrolling: touch; and overflow: scroll` "to everything"

**Comment by TatuLund** [comment]
Hi @chirastefan , this is issue tracker for Vaadin 8 issues. The problem you have has been already reported in the correct repository of the Vaadin Dialog component of our new framework https://github.com/vaadin/vaadin-dialog-flow/issues/196

**Comment by chirastefan** [comment]
this https://github.com/vaadin/vaadin-dialog-flow/issues/196 is not related to what I'm mentioning in this issue, anyway, I'll open another issue in that repo
