### ISSUE TITLE
Panel footer lines inconsistent in Runo theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1204]
**Originally by @jojule**

___
A "footer cut-line" was added to panels and subwindows in Runo theme in order to visually show where the content is cut. This (still) seems like a "hack". Now Runo theme also includes gray subwidnow that does not have a cut-line. 

Should we a) either remove cut-line from all panels and windows, b) add it to gray window or c) leave the theme as is?

If we leave the cut-lines - should they really cross the resize handles too? Looks broken.

Would there be a better way to resolve the original issue of cutting content in containers with round corners?

**Comment by jouni** [comment]
Wontfix, please close.
