### ISSUE TITLE
Atmosphere dependency warning

### ISSUE THREAD

**Issue by ahmadazimi** [vaadin/framework#12088]
vaadin version 14.3.4
vaadin-push version 8.11.2
spring boot version 2.3.2.RELEASE

There is a warning in console when we run **Vaadin Spring Boot based** application:

> Vaadin depends on Atmosphere 2.4.30.slf4jvaadin1 but version 2.4.30.vaadin1 was found.
This might cause compatibility problems if push is used.

Sometimes the server push in application gets timeout! I guess this warning may be the source of my problem.
Is there any chance to fix this warning?

**Comment by TatuLund** [comment]
> vaadin version 14.3.4

This is issue tracker for Vaadin 8, so the correct place to report Vaadin 14 related Push issue is https://github.com/vaadin/flow/issues

> vaadin-push version 8.11.2

This does not match. You should let vaadin-bom define the version. That may be the actual problem in your application.

**Comment by ahmadazimi** [comment]
Thank you @TatuLund 
So, you mean I should use it like this and just remove the version?

```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-push</artifactId>
</dependency>
```

**Comment by TatuLund** [comment]
> So, you mean I should use it like this and just remove the version?

Actually, with Vaadin 14 you can remove the whole dependency, as it is included in vaadin-core

See: https://github.com/vaadin/platform/blob/master/vaadin-core/pom.xml#L40
