### ISSUE TITLE
Binder - There is no way to setBean and skip writeback

### ISSUE THREAD

**Issue by daniel-scoalainformala** [vaadin/framework#12092]
Vaadin version: 14.1.2

There is no way to **setBean** without the binder **writing back** the "Presentation" values that the bound fields display.
This is a serious issue, as it replaces initial Bean values with field "Presentation" values. This causes side effects which affects our application. 

It is not acceptable for the Binder to change Bean values without permission. This causes bugs in our application.
For example, it replaces NULL values with "0" or "" or whatever a field's default value is.

Because Vaadin put **private methods in a library (not to mention FINAL classes)**, we are forced to use Reflection to deal with this issue (and others in Grid, Column , ColumnEditor, Components, you name it etc...), until hopefully this issue is resolved. We run a production App and are unable to wait 1-2 years until Vaadin fixes issues that require one line of code, or to add getters/setters to a variable, or change access modifiers etc.

The proposed fix is to implement the following method: **setBean(BEAN bean, boolean writeBackValues)**

Here is the code that should be implemented: 
```
public void setBean(BEAN bean) {
    setBean(bean, true);
}

public void setBean(BEAN bean, boolean writeBackChanges) {
        checkBindingsCompleted("setBean");
        if (bean == null) {
            if (this.bean != null) {
                doRemoveBean(true);
                clearFields();
            }
        } else {
            doRemoveBean(false);
            this.bean = bean;
            getBindings().forEach(b -> b.initFieldValue(bean, writeBackChanges));
            // if there has been field value change listeners that trigger
            // validation, need to make sure the validation errors are cleared
            getValidationStatusHandler().statusChange(
                    BinderValidationStatus.createUnresolvedStatus(this));
            fireStatusChangeEvent(false);
        }
    }
```

Reporting this bug in the hope that it'll get fixed in the next 12-120 months. We previously had Business Prime/Premium support and it was very disappointing for more than one reason. Warranty / Bug fix priority is an illusion.

Thank you.

**Comment by Legioth** [comment]
> Vaadin version: 14.1.2

This repository is for Vaadin 8 only. Let's keep the discussion in the issue tracker related to Vaadin 10+ to avoid duplication.

If a conclusion is reached there and it would be desirable to backport the same change also to Vaadin 8, then let's consider that then.
