### ISSUE TITLE
ComboBox Issue -  two selected items(v14.3.4)

### ISSUE THREAD

**Issue by RichardSadlon** [vaadin/framework#12101]
If I have a  pre-filled value in the combobox and I try to change it using autocomplete instead of directly selecting a value, the combobox value is changed and filter works properly, but there is a visual issue, combobox displays both values as selected(see the demo at the end).  This happens only on the first use.

### Here is the code to demonstrate the problem:
`
public class ComboBoxExample extends VerticalLayout {

    private ConfigurableFilterDataProvider<DocumentVersionDto, Void, DocumentVersionFilterDto> dataProvider;
    private Binder<DocumentVersionFilterDto> binder;

    private ComboBox<Integer> yearComboBox;
    private DocumentVersionFilterDto filter;

    public ComboBoxExample(ConfigurableFilterDataProvider<DocumentVersionDto, Void, DocumentVersionFilterDto> dataProvider) {
        this.dataProvider = dataProvider;
        this.filter = initDefaultFilter();
        dataProvider.setFilter(filter);
        initUi();
        initBinding(filter);
    }

    private DocumentVersionFilterDto initDefaultFilter() {
        var defaultFilter = new DocumentVersionFilterDto();
        defaultFilter.setYear(LocalDate.now().getYear() - 1);
        return defaultFilter;
    }

    private void initUi() {
        yearComboBox = new ComboBox<>("Year", reverseRangeClosed(2010, 2020).boxed().collect(Collectors.toList()));
        yearComboBox.addValueChangeListener(this::searchByYear);
        add(new FormLayout(yearComboBox));
    }

    private void initBinding(DocumentVersionFilterDto filter) {
        binder = new Binder<>(DocumentVersionFilterDto.class);
        binder.bind(yearComboBox, DocumentVersionFilterDto::getYear, DocumentVersionFilterDto::setYear);
        binder.setBean(filter);
    }

    private void searchByYear(AbstractField.ComponentValueChangeEvent<ComboBox<Integer>, Integer> comboBoxIntegerComponentValueChangeEvent) {
        filter.setYear(comboBoxIntegerComponentValueChangeEvent.getValue());
        binder.setBean(filter);

        if (binder.isValid()) {
            dataProvider.setFilter(binder.getBean());
        }
    }
}

`
### Demo
![vaadin_combobox](https://user-images.githubusercontent.com/20667143/92475497-c5fd4e00-f1dd-11ea-9a68-9a98a8af6d98.gif)

**Comment by TatuLund** [comment]
This is issue tracker for Vaadin 8 issues. The correct issue tracker for Vaadin 14 ComboBox is here https://github.com/vaadin/vaadin-combo-box-flow/issues
