### ISSUE TITLE
Grid with lots of columns + setMinimumWidthFromContent + setHeightByRows fails with 8.12.0

### ISSUE THREAD

**Issue by mikke-alekstra** [vaadin/framework#12139]
Vaadin Framework version 8.12.0
Latest Chrome/Firefox browser versions
Liferay CE version 7.3.5 GA6

A grid with columns having setMinimumWithFromContent set to false to see ellipsis if content exceends column width.
So many columns that content exceends column width.
Grid's setHeightByRows set to exact number of data rows.

With Vaadin version <= 8.11.3 grid was shown as expected.
With 8.12.0 the grid is not shown, please wait spinner stays rolling.

Please see below a sample code that fails with 8.12.0 (and works with 8.11.3). 20 columns was well enough for my browser window size.

```
    @Override
    protected void init(VaadinRequest request) {
        
        Random random = new Random();
        
        List<DummyGridRow> gridRows = new ArrayList<DummyGridRow>();
        gridRows.add(new DummyGridRow(random));
        
        Grid<DummyGridRow> grid = new Grid<DummyGridRow>();
        for (int i = 0; i < 20; i++) {
            grid.addColumn(DummyGridRow::getValue)
            .setCaption("[" + i + "] Quite dummy column")
            .setMinimumWidthFromContent(false);
        }
        
        grid.setItems(gridRows);
        grid.setHeightByRows(gridRows.size());
        grid.setWidthFull();

        this.setContent(grid);
        
    }

    class DummyGridRow {
        
        private Random random = null;
        
        public DummyGridRow(Random random) {
            this.random = random;
        }
        
        public int getValue() {
            return this.random.nextInt(1000000000);
        }
        
    }

```

**Comment by TatuLund** [comment]
I think it could be regression due https://github.com/vaadin/framework/pull/12058
