### ISSUE TITLE
Upload component's appearance has changed in Chrome

### ISSUE THREAD

**Issue by mikke-alekstra** [vaadin/framework#12140]
Vaadin Framework 8.11.3
Linux Chromium 83.0.4103.116
Windows Chrome 86.0.4240.111
Liferay CE 7.3.6 GA6

This problem relates probably to changes in one of Chrome's latest versions but I thought it would be good to inform you anyway. Unfortunately I don't have an old version of Windows Chrome to test with.

Simple Upload component having setImmediateMode=false inside a wide Layout component.

Linux Chromium 83.0.4103.116
![Linux_Chromium](https://user-images.githubusercontent.com/27726112/97702299-70477280-1ab7-11eb-8540-8d28e2651fe8.png)

Windows Chrome 86.0.4240.111
![Windows_Chrome](https://user-images.githubusercontent.com/27726112/97702373-8a815080-1ab7-11eb-8373-c02cfaf76d3f.png)

Sample code I used:
```
    @Override
    protected void init(VaadinRequest request) {
        
        Upload upload = new Upload();
        upload.setImmediateMode(false);
        
        VerticalLayout mainLayout = new VerticalLayout();
        mainLayout.setWidth(1024, Unit.PIXELS);
        mainLayout.addComponent(upload);
        
        this.setContent(mainLayout);
        
    }
```

**Comment by TatuLund** [comment]
Yes, the button whose looks has changed, is native button. And Chrome 85 changed the looks of the native elements. Changes are more prominent if you are using some of the ancient legacy themes instead of Valo.
