### ISSUE TITLE
Re-selecting DynaBean in Grid after updating property that is part of object's equality

### ISSUE THREAD

**Issue by development-s365** [vaadin/framework#12142]
## Environment
- Vaadin Framework version **8.9.2**

## Description
I am currently using a `DynaBean` to dynamically create an object to map to a SQL row at runtime.  
I have a simple setup where I determine the equality of a `DynaBean` by using the primary keys' values with the `EqualsBuilder` and `HashcodeBuilder`.  
Selecting the items work fine but after I *update* a value that is part of the primary key (part of a composite key) and refresh the grid to then re-select the item, the item gets reselected but cannot be de-selected and after refreshing only the dataprovider the item cannot even be selected.

**Comment by development-s365** [comment]
Current workaround that I am using:  
Instead of overriding the `equals` and `hashcode` of my dynabean, I just opted to create my own `isEqual(obj)` method that checks for equality. Then after refreshing the data filtering the local list of items that the grid is using to find a match and use this to essentially re-select the item

**Comment by TatuLund** [comment]
The important thing with `equals `is that it should be stable regarding object property changes. So for example if you have `Person `bean, which has property `name`. If you change the `name`, the identity of the object should not change. 

If you want to use some "intelligent" helper, that violate the above assumption, then you can extend `DataProvider` and override its `getId()` method. By default `getId()` uses object itself. But you can e.g. override it to use `Person#getId()`, or any other identifying stable property.
