### ISSUE TITLE
NPE when calling UI.setMobileHtml5DndEnabled() from ui.access

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#12152]
When I try to call UI.setMobileHtml5DndEnabled() from ui.access() from a background thread, Vaadin fails with NPE at

```
java.lang.NullPointerException
at com.vaadin.server.VaadinServletService.getStaticFileLocation(VaadinServletService.java:106)
at com.vaadin.ui.UI.loadMobileHtml5DndPolyfill(UI.java:2003)
at com.vaadin.ui.UI.setMobileHtml5DndEnabled(UI.java:1985)
```

The reason is most probably that `VaadinRequest.getCurrent()` returns null in `ui.access()`.

If `UI.setMobileHtml5DndEnabled()` does not support this mode, it should cleanly fail with `IllegalStateException`.

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version: 8.8.5

**Comment by mvysny** [comment]
The workaround would be to call `UI.setMobileHtml5DndEnabled()` from `UI.init()`.

**Comment by TatuLund** [comment]
> The reason is most probably that VaadinRequest.getCurrent() returns null in ui.access().

Yes, that is correct. And for security reasons it should return null when called from background thread.

**Comment by mvysny** [comment]
> Yes, that is correct. And for security reasons it should return null when called from background thread.

Sure, that makes sense. However, that makes setMobileHtml5DndEnabled() impossible to be called from ui.access(), and having an IllegalStateException there would be a godsend.

**Comment by TatuLund** [comment]
> IllegalStateException there would be a godsend.

Yes, that would be more intuitive way to signal the error to the developer.
