### ISSUE TITLE
vaadin 8 grid performance question - could applyColumnWidthsWithExpansions reuse knowledge?

### ISSUE THREAD

**Issue by alexandru-prigoreanu** [vaadin/framework#12172]
- Vaadin Framework version: 8.12.1
- Browser version: chrome 87.0.4280.88
- Description of the bug: applyColumnWidthsWithExpansions does not reuse knowledge on container height changed from undefined to 100% and viceversa
- Minimal reproducible example
For testing purposes i have a VerticalLayout with a button "reset height" and a grid with 16 rows and 16 columns.
```

    private VerticalLayout createContentLayout() {
        VerticalLayout contentLayout = new VerticalLayout();
        contentLayout.setSpacing(true);
        contentLayout.setId("contentLayout");
        contentLayout.addComponent(new Button("reset height", event -> {
            if (contentLayout.getHeight() == -1.0f) {
                contentLayout.setHeight(100, Unit.PERCENTAGE);
            } else {
                contentLayout.setHeightUndefined();
            }
        }));
        Grid grid = new Grid<>();
        List objects = Lists.newArrayList();
        for (int i = 0; i < 16; i++) { //add 16 columns
            String caption = nextString();
            grid.addColumn(item -> nextString()).setCaption(nextString()).setId(caption);
            objects.add(caption);
        }
        grid.setDataProvider(new ListDataProvider<>(objects));
        grid.setSizeFull();

        VerticalLayout gridLayout = new VerticalLayout(grid);
        gridLayout.setSizeFull();
        contentLayout.addComponent(gridLayout);
        contentLayout.setExpandRatio(gridLayout, 1.0f);
        return contentLayout;
    }

    private static String nextString() {
        return "" + Math.abs(RANDOM.nextDouble());
    }

    private static final Random RANDOM = new Random();

```
When the button "reset height" is clicked the contentLayout height is either set to undefined or to 100%. Too much time is taken by the function applyColumnWidthsWithExpansion. In the real case scenario the button click might take up to 2 seconds to perform and will block the user interaction for that amount of time.
When button "reset height" is clicked and we are in the collapsedGrid screenshot, the grid will get expanded and viceversa when we are in the expandedGrid screenshot and we click the button, the grid will get collapsed.

![collapsedGrid](https://user-images.githubusercontent.com/74921454/101494589-8b6a9500-3935-11eb-88ba-02a5bdd16303.png)
![applyColumnWidthsWithExpansionOnCollapse](https://user-images.githubusercontent.com/74921454/101494590-8c032b80-3935-11eb-90fc-5d0fbf3b2a3f.png)
![expandedGrid](https://user-images.githubusercontent.com/74921454/101494592-8c032b80-3935-11eb-88c9-7455f9974b79.png)
![applyColumnWidthsWithExpansionOnExpand](https://user-images.githubusercontent.com/74921454/101494593-8c032b80-3935-11eb-9732-9ee6af82f206.png)

- Expected behavior
1. when the button is clicked and it expands the grid i expect that applyColumnWidthsWithExpansion would take less time to perform since it is needed only for the not yet visible rows which is one and a half row
2. when the button is clicked and it collapses the grid i expect that applyColumnWidthsWithExpansion would not take any time at all
- Actual behavior
1. when expanding the grid applyColumnWidthsWithExpansion takes roughly 400ms in the provided case
2. when collapsing the grid applyColumnWidthsWithExpansion takes roughly 400ms in the provided case

Is it possible to "reuse the knowledge on the widths on the already visible rows" and calculate the widths on the rows not yet visible only and make applyColumnWidthsWithExpansion be more performant?

thank you for your time and support!

**Comment by Ansku** [comment]
Not trivially, I'm afraid, as there is no existing mechanism that would tell the AutoColumnWidthsRecalculator that only the height of the Grid has changed. That method is triggered through quite a few different mechanisms, and as far as it's concerned there might have been a horizontal resize too, or instead. That isn't to say that there isn't any room for optimizing the overall logic, but as it is that method cannot assume that the columns don't actually need recalculating.

**Comment by alexandru-prigoreanu** [comment]
@Ansku thank you for your reply. should we close this?

**Comment by Ansku** [comment]
Sorry, I thought I already answered but apparently I forgot to actually write it down 😅  We have two options here: we can leave this open as a feature request to rewrite the column width management in a way that would allow for this sort of optimization (not sure if it's plausible, would require a closer look, but it's probably not a fast approach so might not ever actually happen), or we can close this as an answered question. Either way I've been planning to take a look at the performances in the framework come next year, if I find a free moment for it, and some of the potential avenues of investigation are within Grid, so could be that we'll manage to make it a bit snappier through some other approach.

**Comment by alexandru-prigoreanu** [comment]
@Ansku thank you! ok let's close it. looking forward to it.
