### ISSUE TITLE
Lower the specificity of the caption selector for NativeButton

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1218]
**Originally by @jouni**

___
Remove the [unnecessarily specific selector](http://dev.vaadin.com/browser/versions/6.4/WebContent/VAADIN/themes/base/button/button.css#L99) from Base theme that makes custom themeing harder.

Change
```
.v-nativebutton .v-nativebutton-caption
```
to
```
.v-nativebutton-caption
```

From [forum](http://vaadin.com/forum/-/message_boards/message/216257).

___
 Imported from https://dev.vaadin.com/ issue #5585

**Comment by jouni** [comment]
Wontfix, as the Base theme will be deprecated in version 8.
