### ISSUE TITLE
#12132 leads to NPEs

### ISSUE THREAD

**Issue by lennartfricke** [vaadin/framework#12207]
With Vaadin 8.12.1, we get NPE Exceptions in code introduced in #12132.

As also pointed  out in https://github.com/vaadin/framework/pull/12132#discussion_r576280435.

Though it is rather unlikely that a `field_value == null`  leads to a `model_value != null`, there might be cases this happens.

We encountered null -> Optional.empty -> null, but chains like null -> default value -> null might also be possible.
This also questions the null check of `value` in line https://github.com/vaadin/framework/blob/949434a935638cf130535f9d4bf2e6702e2c0a00/server/src/main/java/com/vaadin/data/Binder.java#L1287

Maybe the solution is:
```java
FIELDVALUE converted = convertToFieldType(value);
if (!Objects.equals(field.getValue(), converted)) {
    getField().setValue(converted);
}
```

The code leads to "immediate" normalization of values in the gui by running the conversion back and forth and makes it more difficult to allow users to enter values that have multiple representations e.g. enter decimal values too slow with StringToDoubleConverter and default TextFields is quite challenging when typing slowly. :wink:

**Comment by TatuLund** [comment]
> The code leads to "immediate" normalization of values in the gui by running the conversion back and forth and makes it more difficult to allow users to enter values that have multiple representations

There are different value change modes in TextField to overcome the possible issues regarding this. If you use eager mode, the input can become clunky, but you can use delayed mode instead and control it by parameters, so that TextField waits for next key press longer.
