### ISSUE TITLE
Grid/TreeGrid with full width cells can make the page unresponsive

### ISSUE THREAD

**Issue by muhammetaltindal** [vaadin/framework#12235]
### Vaadin Framework version
8.12.3

### Browser version
Chrome 88.0.4324.190 (Official Build) (64-bit)
Edge: 89.0.774.45 (Official build) (64-bit)
Firefox: 86.0 (64-bit)

### Operating System
Windows 8 and 10

### Web container name and version
jetty-9.4.17.v20190418; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67

### Description of the bug
Interestingly this bug does not happen on IE11 (Version 1909 (OS Build 18363.1379)). It seems that the bug starts to occur at Vaadin version 8.12.0. Before the version 8.12.0 this bug does not occur.

The bug occurs in a tree grid with one column. The style of the cell in each row is styled in a way that it fills the whole visible row. It seems to have something to do with the identified scrollbar thickness. For example on macOS the scrollbar thickness is zero in the browsers Chrome, Firefox, Edge and Safari. On windows usually the scrollbar thickness is greater 0, e.g. 17.

The following description shows how we can end up in an endless scripting.
- The VisibilityChangeEvent is fired when a scrollbar visibility changes.
- Then the handler of VisibilityChangeEvent in Escalator#setupScrollbars 
in verticalScrollbar.addVisibilityHandler(...) is called 
which is in the end firing VerticalScrollbarVisibilityChangeEvent.
- The handler of VerticalScrollbarVisibilityChangeEvent 
is in the Grid constructor in Escalator#addVerticalScrollbarVisibilityChangeHandler
where it calls Grid#recalculateColumnWidths
which schedules the autoColumnWidthsRecalculator
which calls applyColumnWidths or applyColumnWidthsWithExpansion
- Then setColumnWidths(Map<Integer, Double> indexWidthMap, boolean recalculateElementSizes)
is called with recalculateElementSizes=true
which calls Escalator#recalculateElementSizes
which calls Scroller#recalculateScrollbarsForVirtualViewport
which calls verticalScrollbar.setOffsetSizeAndScrollSize
which calls fireVisibilityChangeIfNeeded on verticalScrollbar 
which again fires VisibilityChangeEvent.
- Then everything starts again from the handler in Escalator#setupScrollbars.

The same issue occurs also for the Grid component.

Here is a video about the problem:
https://public.centerdevice.de/4eae2f0a-619d-4f3a-bd01-accf7b289cfa

### Minimal reproducible example

The demo UI code.
```java
package de.codecentric.vaadin.demo;

import java.util.stream.IntStream;
import java.util.stream.Stream;

import com.vaadin.annotations.Theme;
import com.vaadin.data.provider.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.data.provider.CallbackDataProvider;
import com.vaadin.data.provider.HierarchicalDataProvider;
import com.vaadin.data.provider.HierarchicalQuery;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.TreeGrid;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.renderers.ComponentRenderer;

@Theme("demo")
public class DemoUI extends UI {

  int childCount = 5;

  @Override
  protected void init(VaadinRequest vaadinRequest) {
    TreeGrid<String> treeGrid = treeGrid();
    Grid<String> grid = grid();

    Button add = addRowButton(treeGrid, grid);
    Button delete = deleteRowButton(treeGrid, grid);

    VerticalLayout content = new VerticalLayout(treeGrid, add, delete);
    Button switchGrid = switchGridButton(treeGrid, grid, content);
    content.addComponent(switchGrid);

    setContent(content);
  }

  private Button openWindowButton(Window window) {
    return new Button("open grid", e -> {
      if (window.getParent() == null) {
        window.center();
        addWindow(window);
      }
    });
  }

  private Button switchGridButton(TreeGrid<String> treeGrid, Grid<String> grid, VerticalLayout content) {
    return new Button("switch", e -> {
      if (grid.getParent() == null) {
        content.replaceComponent(treeGrid, grid);
      } else {
        content.replaceComponent(grid, treeGrid);
      }
    });
  }

  private Button deleteRowButton(TreeGrid<String> treeGrid, Grid<String> grid) {
    return new Button("delete", e -> {
      childCount--;
      grid.getDataProvider().refreshAll();
      treeGrid.getDataProvider().refreshAll();
    });
  }

  private Button addRowButton(TreeGrid<String> treeGrid, Grid<String> grid) {
    return new Button("add", e -> {
      childCount++;
      grid.getDataProvider().refreshAll();
      treeGrid.getDataProvider().refreshAll();
    });
  }

  private Grid<String> grid() {
    Grid<String> grid = new Grid<>();
    grid.setCaption("grid");
    grid.setWidth("460px");
    grid.setHeight("400px");
    grid.setHeaderVisible(false);
    grid.setRowHeight(40);
    grid.addColumn(this::newLabel, new ComponentRenderer());
    grid.setDataProvider(
        new CallbackDataProvider<>(q -> IntStream.range(0, childCount).mapToObj(String::valueOf), q -> childCount));
    return grid;
  }

  private TreeGrid<String> treeGrid() {
    TreeGrid<String> grid = new TreeGrid<>();
    grid.setCaption("tree grid");
    grid.setWidth("460px");
    grid.setHeight("400px");
    grid.setHeaderVisible(false);
    grid.setRowHeight(40);
    grid.addColumn(this::newLabel, new ComponentRenderer());
    grid.setDataProvider(treeDataProvider());
    return grid;
  }

  private HierarchicalDataProvider<String, Object> treeDataProvider() {
    return new AbstractBackEndHierarchicalDataProvider<String, Object>() {
      @Override
      public int getChildCount(HierarchicalQuery<String, Object> hierarchicalQuery) {
        return childCount;
      }

      @Override
      public boolean hasChildren(String s) {
        return false;
      }

      @Override
      protected Stream<String> fetchChildrenFromBackEnd(HierarchicalQuery<String, Object> hierarchicalQuery) {
        return IntStream.range(0, childCount).mapToObj(String::valueOf);
      }
    };
  }

  private Label newLabel(String s) {
    Label label = new Label(s);
    label.setWidthFull();
    return label;
  }
}
```

The demo theme, which is important for the problem to occur.
```css
@import "../valo/valo";
.demo {
  @include valo;

  .v-treegrid {
    .v-treegrid-cell { padding: 0; }
    .v-treegrid-expander { position: absolute; }
    tr[style], td[style] {
      width: auto !important;
      min-width: 100% !important;
    }
  }
    
  .v-grid {
    .v-grid-cell { padding: 0; }
    tr[style], td[style] {
      width: auto !important;
      min-width: 100% !important;
    }
  }
}
```

### Expected behavior
The page should not get unresponsive.

### Actual behavior
The page gets unresponsive.

**Comment by muhammetaltindal** [comment]
In the actual use-case there is only one column in the tree grid. Some rows may contain a text much longer so that the column would need to be much wider than the full-width (related to the wrapper) in order to be able to scroll horizontally to view the whole content.

We've written an extension which is registering scroll and data change listeners on the target tree grid. The listeners update the body-row-container and the current column width to the maximum required width which might be larger than the full-width of the tree grid itself. Before the `width: auto !important` was making sure that you could measure the actually required width by overriding the currently set width. One programmatic way is to clone the row and clear the width style of the `tr` and `td` elements and measure the offset width of the `td` element.

Thank you for the hint to go for the pure programmatic way. After adjusting the extension to work without any additional css, the problem didn't occur anymore. In my opinion this issue can be closed.

**Comment by Ansku** [comment]
Ah, I see, the potential for needing horizontal scrolling didn't occur to me from the example case. Glad to hear you got it working!
