### ISSUE TITLE
Window cannot be dragged when using touch screen 

### ISSUE THREAD

**Issue by Jantoni1** [vaadin/framework#12257]
- Vaadin version: 8.11.0
- Browser version: Chrome 89.0.4389.82 
- Web container: Tomcat 8
- Bug description: When using a touch screen device, the user cannot drag the window by dragging the header.
- [Minimal reproducible example](https://github.com/Jantoni1/vaadin-window-minimal-example)
- Expected behavior: when touching and moving the finger, the user should be able to drag the window
- Actual behavior: nothing happens
- Steps to reproduce: Enable mobile device preview (e.g. in Chrome) and try to move the window by dragging the header.

**Comment by TatuLund** [comment]
This is trivial to reproduce on demo.vaadin.com/sampler using Windows 10 2-in-1 device.

**Comment by TatuLund** [comment]
Just a not. For some weird reason this bug was fixed in Vaadin 7.6.6, but the fix has not been picked to Vaadin 8 development branch, possibly due human error, see more: https://github.com/vaadin/framework/issues/6790
