### ISSUE TITLE
TreeTable scroll position erratic on update

### ISSUE THREAD

**Issue by petrixh** [vaadin/framework#12251]
While working on a customer case, an issue with the TreeTable scroll position being erratic at times came up. 

Steps to reproduce (more details in the UI class in the example app):

1. compile and run the app
2. Navigate to the application with Firefox
  - This can be reproduced with Chrome as well, but sometimes Chrome seems to work just fine while FF seems
  easier to break... Probably depends on how much/many items are opened above, not sure...
  - Tested with FF 86.0.1 on OS X
3. Expand some nodes at the top, for instance -1, 0, 10 and 110
4. Scroll all the way down
5. Expand node 9 and 9009
6. Make sure the TreeTable is scrolled all the way down
7. Select the check box for node 9010

Bug: the tree refreshes and the scroll position is lost, i.e. node 9010 is no longer visible

Expected: Even after a container refresh the TreeTable holds the correct scroll position

If the same test is done with the Reindeer-theme, the issue is not present. Also, with the Valo theme, if the TreeTable is given the "TABLE_NO_HORIZONTAL_LINES" style, then the issues seems to go away or at least be hidden. 

Tested with: 

Vaadin 7.7.17

Browser: Firefox 86.0.1, Chrome 89.8.4389.82 on OS X, however originally found in older browsers and repeatable in other environments as well. 

Test app included for reproducing the issue. 

[v7-treetable-scroll-bug.zip](https://github.com/vaadin/framework/files/6180452/v7-treetable-scroll-bug.zip)

**Comment by jokiljuh** [comment]
Thanks Petri for reporting this.
