### ISSUE TITLE
TextField with StringToBigDecimalConverter deletes the decimal separator immediately

### ISSUE THREAD

**Issue by gero1992** [vaadin/framework#12262]
- Vaadin Framework version - 8.12.4
- Browser version - Chrome 89.0.4389.90
- Web container name and version - Embedded tomcat on spring-boot 2.4.3
- Description of the bug

When I use a TextField with a StringToBigDecimalConverter the decimal separator gets deleted quite fast. The user needs to be very quick in order to fill properly the value. Up to vaadin 8.12.0 the decimal separator was not deleted at all and the user still had a valid value. I think it's related to https://github.com/vaadin/framework/pull/12132.

- Minimal reproducible example

`TextField textField = new TextField("Some caption");
        Binder<ExampleBean> binder = new Binder<>();
        binder.forField(textField).withConverter(new StringToBigDecimalConverter("ERROR")).bind(ExampleBean::getBigDecimal, ExampleBean::setBigDecimal);
        binder.setBean(new ExampleBean());`

` public class ExampleBean {
    private BigDecimal bigDecimal = BigDecimal.ONE;
    // Getter and setter
    }
}`

- Expected behavior

The decimal separator doesn't get deleted so the user can fill his value without getting worrried about speed.
![expected](https://user-images.githubusercontent.com/41724817/113172058-5bc6fc00-9248-11eb-8b36-7ad5896ccb1c.gif)

- Actual behavior

The value gets deleted in less than a second
![current](https://user-images.githubusercontent.com/41724817/113172037-579ade80-9248-11eb-8dfd-a805496240e3.gif)

**Comment by TatuLund** [comment]
You can avoid this problem by using TextField#setValueChangeMode(..) with some other value than ValueChangeMode.EAGER.

Furthermore, in Vaadin 8.13.0 there will be API to disable writing back of the converted value: https://github.com/vaadin/framework/pull/12246

Vaadin 8.13.0.beta1 was released yesterday if you wish to test it.

**Comment by gero1992** [comment]
Thank you for the quick reply and for the tip! Yes, this solves the problem. I will try that in the beta version as well :).
