### ISSUE TITLE
NumberFormatException in MouseEventDetails on Chrome(89.0.4389.114)

### ISSUE THREAD

**Issue by yonury** [vaadin/framework#12263]
I have similar problem with #2549. 
I dont have this problem on Firebox and IE, but I have the problem on Chrome.
I haven't encountered this problem until the last two weeks.

Vaadin version: 6.7.3 
GWT Version: 2.3.0
Win: 10

java.lang.NumberFormatException: For input string: "920.888916015625" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:580) at java.lang.Integer.parseInt(Integer.java:615) at com.vaadin.terminal.gwt.client.MouseEventDetails.deSerialize(MouseEventDetails.java:119) at com.vaadin.ui.Button.changeVariables(Button.java:217) at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1455) at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1399) 

Any idea?

Regards

**Comment by TatuLund** [comment]
Thanks for reporting.

Couple of notes, Vaadin 6 is un-fortunately not supported and maintained anymore, so if there is a bug, it wont be fixed.

> Vaadin version: 6.7.3

This is an old version, the last Vaadin 6 release was 6.8.18. I would recommend to upgrade to it, even if it wont necessarily fix this problem.

My understanding is that the coordinates should be allways integer unless in some rare cases Browser when not set to 100% zoom level, they produce decimal values. So setting zoom level to 100% may be a workaround.

**Comment by winddev** [comment]
> I have similar problem with #2549.
> I dont have this problem on Firebox and IE, but I have the problem on Chrome.
> I haven't encountered this problem until the last two weeks.
> 
> Vaadin version: 6.7.3
> GWT Version: 2.3.0
> Win: 10
> 
> java.lang.NumberFormatException: For input string: "920.888916015625" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:580) at java.lang.Integer.parseInt(Integer.java:615) at com.vaadin.terminal.gwt.client.MouseEventDetails.deSerialize(MouseEventDetails.java:119) at com.vaadin.ui.Button.changeVariables(Button.java:217) at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.changeVariables(AbstractCommunicationManager.java:1455) at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.handleVariableBurst(AbstractCommunicationManager.java:1399)
> 
> Any idea?
> 
> Regards

It is possible to extend needed component(Button) and override some logic when deSerialize is invoked
