### ISSUE TITLE
Feature Request: ComboBox, display arbitrary HTML

### ISSUE THREAD

**Issue by eischet** [vaadin/framework#12268]
A customer has asked me for "hit highlighting" in a ComboBox, and I came up with this after a bit of hacking the current Vaadin 8.14-snapshot:

![image](https://user-images.githubusercontent.com/1009970/115387829-78b57600-a1db-11eb-987c-4f95c37f0478.png)

In this case I've extended VComboBox::ComboBoxSuggestion with an additional htmlCaption field that is generated by a SerializableBiFunction<T, String, String> {  String apply(T item, String searchText); } that can look at the current text and each item. Only if this function returns something other than null or "" it's used instead of the regular caption for the menu item.
The filtering logic itself is unchanged and still works on the caption only.

An additional feature of this approach is that by adding normally "unseen" text into the caption I can let my users find things by alias words, which was the primary use case, e.g.:

![image](https://user-images.githubusercontent.com/1009970/115388088-c5994c80-a1db-11eb-8928-9e4723af2f85.png)

Same item, different alias:

![image](https://user-images.githubusercontent.com/1009970/115388141-d649c280-a1db-11eb-8622-2ea28a532a27.png)

In these cases, the actual item is the same. Its caption contains the names of a bunch of Muppets, so the normal filtering logic can find it, but the HTML generator produces a more meaningful representation by highlighting the keywords.

I don't know if you're still doing this kind of updates on Vaadin 8, but having something like this in the product would be most welcome. Or, alternatively, I could probably wrap this into an add-on to extend the regular combo box.

Regards, Stefan

My quick hack is here: https://github.com/eischet/framework/tree/vaadin-ticket-12268

**Comment by TatuLund** [comment]
This is something that has been requested before, as can be seen here https://github.com/vaadin/framework/issues/2132

The use case is rather valid, this in our new generation framework (i.e. today Vaadin 14 is the LTS) the feature has been implemented.

**Comment by eischet** [comment]
OK, thanks for the reply. I'll take that as a "no" and write an add-on for myself. I hope V14+ and I will be ready for each other one fine day. ;-)
