### ISSUE TITLE
Vaadin 7 on IBM WAS log full of warnings

### ISSUE THREAD

**Issue by aleuC** [vaadin/framework#12311]
We have a Vaadin 7 (Vaadin 7.7.17) application running on IBM WAS, that uses vaadin push.
The log is full of these warnings (which makes it difficult to analyze any other issues):

> [14/05/21 7.21.15:311 CEST] 0004ba80 SystemErr     R com.ibm.ws.logging.WsLogger deliverOrBuffer mag 14, 2021 7:21:15 AM com.ibm.ws.webcontainer.internal.WebContainer handleRequest
> GRAVE: SRVE0255E: Un host virtuale/WebGroup per gestire /Provia/PUSH non è stato definito.
> 
> [14/05/21 7.21.32:481 CEST] 0000062a util          W com.ibm.ws.webcontainer.util.VirtualHostContextRootMapper map SRVE0316W: La richiesta corrisponde al root di contesto [/Provia/*] con alias host virtuale di [webint.*:80].
> [14/05/21 7.21.32:482 CEST] 0000062a SystemErr     R com.ibm.ws.logging.WsLogger deliverOrBuffer mag 14, 2021 7:21:32 AM com.ibm.ws.webcontainer.util.VirtualHostContextRootMapper map
> AVVERTENZA: SRVE0316W: La richiesta corrisponde al root di contesto [/Provia/*] con alias host virtuale di [webint.*:80].

Do you know the problem? Do you know if it can be solved in any way?

**Comment by TatuLund** [comment]
Push client will send connection keep-alive pings to /PUSH, there is some issue in your server or proxy settings.
