### ISSUE TITLE
TwinColSelect behavior when removing items from being selected

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1232]
**Originally by @snyholm**

___
When moving items from the right "container" to the left one, the items get selected in the left container, but the items already selected there also stay selected. This leads to funky behavior where you can have items selected that you did not remember.

Suggestion: when moving items from right to left, deselect all items in the left container and select only the ones you moved.

___
 Imported from https://dev.vaadin.com/ issue #5658

**Comment by TatuLund** [comment]
Closed in favor of https://github.com/vaadin/framework/issues/11287
