### ISSUE TITLE
Push with websocket could not setup the connection between browser and server in Vaadin 8.13.1

### ISSUE THREAD

**Issue by yurili8** [vaadin/framework#12326]
After upgrade from 8.9.3 to 8.13.1, the websocket doesn't work any more.

I have two servers and one Nginx  works as the proxy. It is working well in 8.9.3 but after we upgrade from 8.9.3 to 8.13.1, it is showing the following error.

`
Firefox can't establish a connection to wss://xxxxxxxxxx/vaadinServlet/PUSH?v-uiId=1&v-pushId=159a960f-c9ef-4097-9473-33ae3f56f777&X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2.vaadin2-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true 。

Websocket failed on first connection attempt. Downgrading to long-polling and resending
`

my client os is windows 10 and the version of firefox is 89.0.1

**Comment by TatuLund** [comment]
I tested this with one of my more complete application examples and could not reproduce. I do not recall that we have changes that should affect this, although there has been bug fixes between 8.9.3 in Push integration and small update in Atmosphere framework itself.

**Comment by yurili8** [comment]
Well, it is confusing me.

Actually, I am using 8.9.3 currently for the production environment. But we met one issue. The session will be timeout in high frequency. sometimes, when user is browsing the page and input some data, the session will be timeout. After a long term investigation, we found we could fix the issue by remove the @Push annotation,  namely discard the push feature.

And then, I am thinking whether it is a bug in 8.9.3. I start to plan to upgrade to 8.13.1. After I change the vaadin's version and deploy it to the production environment. even worse, the web socket seems stop working while only long-polling works.

I don't think there is any special setting in the production environment. we have two server nodes behind the nginx proxy. all the setting is the typical setting. the route policy is IPHash。

Actually I noticed that the session timeout issues exist even in our standalone environment without nginx. if there are not many users, this issue is hard to reproduce. if there are a lot of users, 100 for example, the session timeout issue will come out time in time.

**Comment by fanyy** [comment]
> 
> 
> Well, it is confusing me.
> 
> Actually, I am using 8.9.3 currently for the production environment. But we met one issue. The session will be timeout in high frequency. sometimes, when user is browsing the page and input some data, the session will be timeout. After a long term investigation, we found we could fix the issue by remove the @Push annotation, namely discard the push feature.
> 
> And then, I am thinking whether it is a bug in 8.9.3. I start to plan to upgrade to 8.13.1. After I change the vaadin's version and deploy it to the production environment. even worse, the web socket seems stop working while only long-polling works.
> 
> I don't think there is any special setting in the production environment. we have two server nodes behind the nginx proxy. all the setting is the typical setting. the route policy is IPHash。
> 
> Actually I noticed that the session timeout issues exist even in our standalone environment without nginx. if there are not many users, this issue is hard to reproduce. if there are a lot of users, 100 for example, the session timeout issue will come out time in time.

Do you have any workaround bypass this issue? I also have the session timeout issue for a long time. Push is the feature we need, I can't just remove this feature from my project.

**Comment by Ansku** [comment]
This is probably a configuration issue with the proxy rather than anything strictly Vaadin specific. For `Nginx` potential problem points could be e.g. missing `ip_hash` configuration. You might also want to set `max_fails` to 0 to avoid getting the server marked as unavailable if there are any temporary issues. http://nginx.org/en/docs/http/load_balancing.html

**Comment by yurili8** [comment]
> This is probably a configuration issue with the proxy rather than anything strictly Vaadin specific. For `Nginx` potential problem points could be e.g. missing `ip_hash` configuration. You might also want to set `max_fails` to 0 to avoid getting the server marked as unavailable if there are any temporary issues. http://nginx.org/en/docs/http/load_balancing.html

Thanks for your advice. I will have a try.
I may close this issue firstly and open another one for the session timeout issue if the issue is still there with your advice.
