### ISSUE TITLE
Styles adds the same CSS string multiple times

### ISSUE THREAD

**Issue by Flaurite** [vaadin/framework#12343]
### Environment
- Vaadin Framework version 8.13.2

### Description of the bug
`Page.Style#add(String)`  does not check that style has already added like in the `Page.Style#add(Resource)`.
#### Minimal reproducible example
1. Add the following code:
```
@Override
protected void init(VaadinRequest vaadinRequest) {
    final VerticalLayout layout = new VerticalLayout();
    Button button = new Button("Add style");
    button.addClickListener(clickEvent -> {
        Page.Styles styles = Page.getCurrent().getStyles();
        styles.add(".my-style { color: red; }");
    });
    layout.addComponent(button);
    setContent(layout);
}
```
2. Launch the app and click on the button several times.
3. Open dev-tools of the browser tab and navigate to `<head>` element.

**Actual behavior**
Style added several times:
![image](https://user-images.githubusercontent.com/22093943/125964775-a3485bcc-b939-4a48-b4fd-0e88dce5f47b.png)

**Comment by TatuLund** [comment]
The contract of this feature is quite badly documented. I recall that it has worked always like this. It is not the most frequently used feature, thus we have not received much feedback regarding this. I just remember that someone introduced this method to me noting this caveat. Is this a bug or not, is a borderline case. But it is nevertheless rather straightforward to fix it.
