### ISSUE TITLE
Implement all Runo theme Panel decorations for IE

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1234]
**Originally by @jouni**

___
The lower part of the panel element (v-panel-deco?) is missing in IE, while being displayed in Firefox and other modern browsers (see screenshots). This is because the Panel uses the :before pseudo element to display the lower left rounded corner, and IE doens't support generated elements in versions 6 and 7.

In earlier versions of Vaadin, this was as good as it gets, since there were not enough elements to apply background images to. Additional elements have been introduced in later versions, so this is now possible to fix.

This can be implemented in IE8 with the generated element, but for IE6/7 an alternated solution is needed. One solution is to remove the :before generated element altogether, and place the background image in the .v-panel root element, and move the top-left background image to the .v-panel-captionwrap.

**Comment by jouni** [comment]
Wontfix
