### ISSUE TITLE
CSS rule and style injection API

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1238]
**Originally by @jojule**

___
Quite often developers want to control styles from Java code without creating or modifying a custom theme. Furthermore, sometimes it is necessary to change styles dynamically.

Proposal API:

```
interface com.vaadin.terminal.Stylable {

   /** Injects given style to the outmost element of the implementing paintable */
   public void addStyleInjection(stylename, value);

   public void removeStyleInjection(stylename);

   public void removeAllStyleInjections();

   /** Injects CSS rule that matches to elements within the outmost element of the implementing paintable */
   public void addCSSInjection(selector, stylename, value);

   public void removeCSSInjection(selector, stylename);
   
   public void removeCSSInjections(selector);

   public void removeAllCSSInjections();
}
```

AbstractComponent should implement Stylable.

addCSSInjection could be implemented by adding a random class to outmost element of the implementing paintable, catenating that class as a prefix to selector and adding the result to css.

This is a related - complementing - to #5500

**Comment by DoriamVell** [comment]
Hello! On project what I'm working for, we have need to give customer's admins possibility to customize UI theme to reflect 3rd party styling. We can't process All customers with their themes. Also, it's not good idea to force customers to create CSS\SCSS files, cause it's very not user-friendly.
We will be happy to have possibility to dinamically change style of specified tags (like borders, foreground, background, etc.) for whole UI without using "setStyleName()" for each Vaadin element. It will be perfect instrument for our users to customize their UI like they want.
Predefined themes is also not option, cause only 4 tags with 4 different color will result to need to have 16 predefined theme to reflect all possible combinations.

**Comment by TatuLund** [comment]
This has been implemented in Flow.
