### ISSUE TITLE
Vaadin applications do not work on localhost without a network connection (Windows)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1244]
**Originally by @Artur-**

___
To reproduce (in Windows):
 - Disconnect from the network
 - Open a locally deployed application

Result is a communication error (server down?).

Pretty nasty for e.g. Visual Editor.

___
 Imported from https://dev.vaadin.com/ issue #5716

**Comment by TatuLund** [comment]
Vaadin 6 is not a supported product, thus we are closing this as wont fix.
