### ISSUE TITLE
Support for Liferay 7.4.3.5 GA5

### ISSUE THREAD

**Issue by mikke-alekstra** [vaadin/framework#12502]
Hello!

Liferay CE 7.4.3.5 GA5 was released last night. Liferay's kernel version has been updated to 29.0.1 and it seems that Vaadin's server/bnd.bnd should be updated to meet the new kernel version.

I have not had time to test this yet but based on the previous Liferay release updates I believe Vaadin 8.14.3 is not compatible with the new Liferay release.

**Comment by TatuLund** [comment]
I checked the version number you gave as it looked suspicious to mee, as the previous update with 7.4.3 was update to kernel version 16.3.

Liferay has strange versioning style, as there has been big number of major kernel releases during short period of time

https://mvnrepository.com/artifact/com.liferay.portal/com.liferay.portal.kernel

And the product version has sub-maintenance bump.
