### ISSUE TITLE
Embedded pdf = new Embedded();  pdf.setType(Embedded.TYPE_BROWSER); pdf.setMimeType("application/pdf"); pdf.setSource(r); pdf.setSizeFull(); windows 10 browser pdf file show but windows11+ not show 

### ISSUE THREAD

**Issue by divyadeepa266** [vaadin/framework#12500]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues for Vaadin Flow (Vaadin v10 Java Framework) should go to https://github.com/vaadin/flow

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
- Browser version
- Web container name and version
- Description of the bug
- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by Ansku** [comment]
Closed in favour of #12501
