### ISSUE TITLE
DnD drop event is missing

### ISSUE THREAD

**Issue by andreika63** [vaadin/framework#12516]
- Vaadin Framework version (8.14.3)
- Browser version Version 97.0.4692.71 (Official Build) (64-bit)
- Web container name and version: vaadin-spring.version 2.1

Hello, I've tried to use drag and drop with components as described here (https://vaadin.com/docs/v8/framework/advanced/advanced-dragndrop). But drop events doesn't propogate to backend.
Му goal is use grid's row as drag source and some dropable componet (grid, layout....)
While drag and drop action take in place threre are only 2 events is propogated to backend:
`{
  "csrfToken": "9e03b15b-5085-4d90-a152-971ce94cc3c1",
  "rpc": [
    [
      "1077",
      "com.vaadin.shared.ui.grid.GridDragSourceRpc",
      "dragStart",
      [
        [
          "7"
        ]
      ]
    ]
  ],
  "syncId": 99,
  "clientId": 99
}`
and
`{
  "csrfToken": "9e03b15b-5085-4d90-a152-971ce94cc3c1",
  "rpc": [
    [
      "1077",
      "com.vaadin.shared.ui.grid.GridDragSourceRpc",
      "dragEnd",
      [
        "NONE",
        [
          "7"
        ]
      ]
    ]
  ],
  "syncId": 100,
  "clientId": 100
}`
DOM elements has the same listener function on different events and minified js is so hard to debug.
How drop events should be passed to backend?

**Comment by TatuLund** [comment]
I tried to reproduce the problem with the examples we have, but I was not able to.
