### ISSUE TITLE
Grid steals input focus from text field during repaint

### ISSUE THREAD

**Issue by thevaadinman** [vaadin/framework#12526]
In Framework 8.14.3 (and very likely every previous version) attempting to add a real-time filtering function to Grid causes the text field to lose input focus when the Grid repaints as the data provider's contents are updated.

Expected behavior is to be able to keep typing without Grid stealing focus.
Can be replicated on both Chrome and Firefox.

Minimal project for reproducing the issue attached, provided by a customer.

[grid-focus-steal.zip](https://github.com/vaadin/framework/files/8169875/grid-focus-steal.zip)

**Comment by TatuLund** [comment]
Fixed in 8.15.1
