### ISSUE TITLE
The provided license key does not allow usage of vaadin-framework 8.20.0

### ISSUE THREAD

**Issue by rPraml** [vaadin/framework#12587]
Today, our dev licenses cannot be verified.

It seems that the SSL certificate of https://sso.vaadin.com is expired.

I realize you want to validate licenses. But it is bad if the entire dev team is "down" now due to a "single point of failure" in one of the external vaadin servers.

Please consider to implement some caching with "grace period" to avoid such situations in future!

Roland

**Comment by TatuLund** [comment]
This is being worked on. That SSL certificate expiry affects all products of ours, not just Vaadin 8.

**Comment by TatuLund** [comment]
License checking should work now.

**Comment by rPraml** [comment]
Unfortunately not for my account.

I get a 'Server returned HTTP response code: 500 for URL: https://tools.vaadin.com/vaadin-license-server/licenses/pro' response.

I also have problems in my account. I can log in, but then I get "Sorry, looks like something went wrong gathering your account information. Our team is informed already!"

So I'll wait for now and let you do your work ;)

**Comment by TatuLund** [comment]
It may require couple of retries. I am getting now more and more testimonials that it finally works.
