### ISSUE TITLE
ColorPickerHistory always sets white color

### ISSUE THREAD

**Issue by krockamichael** [vaadin/framework#12592]
Vaadin version: 8.14.3
Browser: any, e.g. Chrome Version 114.0.5735.199 (Official Build) (64-bit)
Container: TomEE, J2EE

**Steps to reproduce:**

1.  Let's have a Vaadin screen with ColorPicker
2. ColorPicker features also history - ColorPickerHistory
3. Upon clicking cell in history a ValueChangeEvent is fired
4. This value change event, however, has value set to white rgb(255,255,255) and not the actual color that is present in the history cell
5. This is due to the fact that the ColorPickerHistory.getValue() returns the white color

Workaround:
None.

**Comment by ladislavlencucha** [comment]
@Ansku in which version is this fix going to be available?

**Comment by Ansku** [comment]
My guess would be 8.27.0, but it hasn't been added to a milestone quite yet and the summer vacations are slowing things down a bit.
