### ISSUE TITLE
vaadin8.24.0 correspond vaadin-spring-boot-starter version，maven repository not fund?

### ISSUE THREAD

**Issue by admlke** [vaadin/framework#12610]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues for Vaadin Flow (Vaadin v10 Java Framework) should go to https://github.com/vaadin/flow

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
- Browser version
- Web container name and version
- Description of the bug
- Minimal reproducible example
- Expected behavior
- Actual behavior

**Comment by TatuLund** [comment]
Could you edit your ticket title and description and express more clearly the issue and how to replicate it. If you are about to ask a generic question you should contact either Vaadin customer support (if you have support subscription) or ask the question in Vaadin's Forum https://vaadin.com/forum/c/vaadin-6-7-8/5
