### ISSUE TITLE
Support for fixed-size columns given in em

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1294]
**Originally by _dma_k_**

___
Currently it is not possible to define a fixed-size columns in units other than pixels. Sometimes the table columns contain fixed-length strings, but the actual width depends on fond size. Therefore the is a need for em units support (or font points).

Relative discussion: http://vaadin.com/forum/-/message_boards/message/239826

___
 Imported from https://dev.vaadin.com/ issue #5897

**Comment by Frettman** [comment]
Would be nice to have. Was looking for that, too.
