### ISSUE TITLE
Container interfaces should specify behavior when an item is filtered out

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1335]
**Originally by @hesara**

___
The Container and Container.Filterable interfaces does not specify, what should be returned by getItem(Object) and getContainerProperty(Object, Object) when an item is filtered out.

Container.Filterable interface javadoc does specify that the operations in Container.Ordered and Container.Indexed should take the filter into account, but does not explicitly say how the above mentioned Container methods should behave.

The interface javadoc should specify the behavior, and all standard containers should conform to it. Currently, e.g. IndexedContainer returns null from these methods, but BeanItemContainer returns the contained values regardless of the filter.

Returning null might be problematic for some containers that create new item instances dynamically in getItem() - to be investigated.

See also #4498.

___
 Imported from https://dev.vaadin.com/ issue #6043

**Comment by KyleRogers** [comment]
Ticket can be closed as Container got removed in Vaadin 8 and replaced with DataProvider, see https://vaadin.com/download/release/8.0/8.0.0/release-notes.html#incompatible
