### ISSUE TITLE
IE7 caches DownloadStreams even when cacheTime=0

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1340]
**Originally by @tepi**

___
When using a DownloadStream along with the StreamResource, and using the Application.getMainWindow().open(..) to serve the Resource as a download to the user, the file will be cached by IE7 even when DownloadStream.setCacheTime(0) has been called.

In AbstractApplicationServlet.handleDownload(..) the response gets the following header: "Cache-Control" = "no-cache", which does not seem to be enough to prevent IE7 from caching the file.

Adding the following header to the stream by hand seemed to solve the problem and force IE7 to stop caching the file:
"Cache-Control" = "no-store, no-cache, must-revalidate, Post-Check=0, Pre-Check=0"

I'm not sure if all the values above are necessary, I took the header from a blog where users were complaining about how to prevent IE7 from caching.

___
 Imported from https://dev.vaadin.com/ issue #6051

**Comment by anasmi** [comment]
Hi,

as IE7 is not officially supported version of Vaadin anymore, please, create a new ticket for us, if the issue is still outstanding for IE11 or comment here and we will open one.
