### ISSUE TITLE
Sprites affect other sprites when zooming

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1358]
**Originally by @Artur-**

___
When browser zoom level is set to something else than 1 some sprites get rendering artifacts at the outer edges. The artifacts seem to originate from nearby sprites. This could be fixed by adding a one pixel border below and to the right of each sprite.

The problem is most visible in mobile devices such as iPad and iPhone where it is very easy to zoom in and out.

___
 Imported from https://dev.vaadin.com/ issue #6128

**Comment by jouni** [comment]
Not sure if this is still an issue. I don’t see any problem on my iPhone at least. Would close as wontfix.
