### ISSUE TITLE
IE7: Tree calculates width wrong when in Panel and width is undefined

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1390]
**Originally by @Artur-**

___
To reproduce:

1. Add a tree to a Panel

2. Set Panel size and content to undefined width

3. Try to collapse and expand the tree

Result: 

In IE7 the branches that are wider then the tree will be cropped.

In IE8 there is an additional extra grey space at the bottom of the panel after collapsing all and expanding the first node.

**Comment by TatuLund** [comment]
IE7 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
