### ISSUE TITLE
PopupDateField with time controls has really bad usability

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1400]
**Originally by @Artur-**

___
When the user uses a PopupDateField with resolution HOUR/MINUTE/SECONDS/MILLISECONDS he only gets to selecting the year, month and day before the popup is closed automatically. The popup should not be closed when selecting the day and the value should be sent/set when the selection of all values is complete. Escape should close the popup and abort all changes at all times.

___
 Imported from https://dev.vaadin.com/ issue #6253

**Comment by hesara** [comment]
PopupDateField is deprecated and moved to the compatibility package in Vaadin 8, and the support for time selection through the new DateField is removed in Vaadin 8. Time selection should typically be done with a separate component for better user experience.

Most likely we will not be making further improvements to the time resolution support of the old PopupDateField, but possibly introducing a TimeField at some point in the future to make it easier to select a time.
