### ISSUE TITLE
Table should be sortable by rowheader/id as well

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#141]
**Originally by @jojule**

___
Description:	 Opened: 2005-10-06 16:49
The Table rowheader column should be treated in the same manner as other columns
regarding sorting: one should be able to sort ascending/descending by rowheader
as well. The component does not currently support this (requires component+uidl
change)

___
 Imported from https://dev.vaadin.com/ issue #162

**Comment by KyleRogers** [comment]
As Vaadin Table reaches EOL soon, this can be closed. Or am I wrong?
