### ISSUE TITLE
Stateless Mode

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1437]
**Originally by @jojule**

___
The proposal outlines a new operation mode for Vaadin applications where HttpSession or server-side state is not needed for applications at all. This is an optional operation mode that could widen the scope of application where Vaadin could be used, not a default or recommended mode of operation.

## Enabling

Set parameter stateless = true in web.xml for the ApplicationServlet.

## Implementation

After each http-request, the application state is serialized and removed from the HttpSession. The serialized application state sent along UIDL to the client. Client stores the application state in a javascript variable. Whenever the client contacts the server, it also sends the application state along the request parameters.

## Security

The implementation must guarantee that the client can not modify the application state. This is done by maintaining a random salt in server and adding a SHA-2 checksum calculated from the serialized state+salt in the end of the state.

For many applications, the state might not contain any secrets that can not be revealed to the client. Still in some cases the developer chooses to store some server-side secrects (such as password for DB connection). In order to keep the state secret, the state is encrypted with a random key stored in the server using AES-256. 

Open question: how the key and salt are stored and shared between the servers in clustered configurations?

## Optimizations

The serialization state size can grow quite large. Thus the state should be compressed with GZIP before sending to client. 
The effect of encryption to performance should be measured and if the effect is noticeable, a parameter for turning encryption off should be added to web.xml. Still the encryption must be on by default.

Quick tests show for a really small application, state can be around 8kb, but it can be compressed to 3.5kb with GZIP. Each additional TextField (with a random caption ("foo" + Math.random()) adds the size of the serialized session by 134 bytes. When GZIP is used, the state size per TextField goes down to 13 bytes and thus is just the size of the captions. 

Research if using a stored seed copy of an app after init() as a seed to compression algorithm would make the compression more efficient. One way to initialize the compression dictionary is to use http://download.oracle.com/javase/1.5.0/docs/api/java/util/zip/Deflater.html#setDictionary(byte[]). 

## Use cases

 - Use in large public facing web-sites where per user session is not allowed. The use would mostly be small embedded mini-applications
 - Clustering environments where sticky sessions are not available. (While as Google App Engine is such an environment, the current memcached based server-side session sharing is probably better option for most applications)
 - Embedding small mini-applications with the new embedding mechanism to any web pages without burden of session management for the server.

## Feasibility

Stateless mode could be useful and practical for really small applications with only a bit of state. A practical limit for the (compressed) state size could be some tens of kilobytes.

Serialization time for an application with some 1000 UI components (textfields) resulting to 152kb of (uncompressed, unencrypted, unsigned) state is 3ms in 2.4GHz core duo MacBook. By adding more components, we measured the serialization time to be proportional to the number of components in the application. Guesstimate for overhead including both serialization, deserialization, compression, encryption and signing is around 0.01ms / component in the application. 

Simple applications embedded to public facing web-sites are the most likely users of the stateless mode. These applications include registration forms, small calendars, insurance calculators, questionaires and such mini-applications. For these applications the number of components is typically something between 10-100. If we guesstimate the average to be 30 components, we may estimate that overhead for such application is 0,3ms of server CPU time and 10kB of combined in+out data transfer per http-request. Lets assume that an user causes in average 15 UIDL ajax requests per day. A public facing system with 1 million daily users would add just 5% overhead to one server CPU for serializations. A more visible cost would be the additional 150GB of combined I+O bandwidths needed (in Amazon EC2 this would cost about 15 USD / day).

This implementation should probably be ad add-on to Vaadin implemented on top of #7207

**Comment by pleku** [comment]
Issue moved to [vaadin/flow #3757](https://github.com/vaadin/flow/issues/3757) via [**ZenHub**](https://www.zenhub.com/)
