### ISSUE TITLE
DateField should support setting an invalid date string

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1472]
**Originally by @hesara**

___
The DateField component supports getting an invalid date string from the client to the server, but it is not possible to set such an invalid string on the server and communicate it to the client.

See also the related tickets #6248 and #6407.

___
 Imported from https://dev.vaadin.com/ issue #6506

**Comment by TatuLund** [comment]
It is not possible to implement this with Vaadin 8 strongly typed concept.
