### ISSUE TITLE
Tabsheet with style Reindeer.TABSHEET_MINIMAL is rendered incorrectly in IE6/IE7

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1485]
**Originally by @Artur-**

___
The line ends at the last tab and not at the end of the Tabsheet. See attached images or PackageIcons sample ([http://demo.vaadin.com/6.5-nightly/sampler/#PackageIcons]).

___
 Imported from https://dev.vaadin.com/ issue #6579

**Comment by jouni** [comment]
Wontfix.
