### ISSUE TITLE
[JsonPaintTarget] Use concurrent collections instead of synchronization

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1487]
**Originally by @tehapo**

___
`JsonPaintTarget` could get rid of synchronization by using `java.util.concurrent.ConcurrentHashMap`. The change might even have some effect on performance as the `getTag` method is called very frequently.

See the attached patch.

___
 Imported from https://dev.vaadin.com/ issue #6584

**Comment by KyleRogers** [comment]
The Map has been removed, patch cannot be applied anymore. Issue can be closed.

**Comment by hesara** [comment]
The map was moved to LegacyCommunicationManager.typeForKey and made a plain HashMap.

**Comment by hesara** [comment]
Not sure exactly when this has been a problem, tried to trace back to 6.x - marking as fixed in 6.5 but possibly already earlier.
