### ISSUE TITLE
Clicking on slider should change slider value

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1496]
**Originally by @johndevs**

___
Currently clicking on the Slider only moves the keyboard focus to the slider. 

A more common behavior is that clicking on the slider sets the value either to a clicked position or moves the slider in some increment toward the clicked position.

___
 Imported from https://dev.vaadin.com/ issue #6622

**Comment by Fedoresko** [comment]
https://github.com/vaadin/framework/blob/52b7d447296a7c8c6f48f0c8b15abb7e250dc640/client/src/main/java/com/vaadin/client/ui/VSlider.java#L273 
Just this line looks shitty and causes problem.

**Comment by mil3stone** [comment]
This issue still exists. Checked it by using the slider provided @ https://demo.vaadin.com/sampler/#ui/data-input/other/slider

You can change the value only by clicking the slider button and move it up/down. Clicking on the bar itself is without function.
