### ISSUE TITLE
Combobox improvements

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1517]
**Originally by _kynao_**

___
Propositions : 

- Multiple select http://www.smartclient.com/smartgwt/showcase/#multi_select_combobox_category

- Drop down list grid http://www.smartclient.com/smartgwt/showcase/#dropdown_grid_combobox_category

- Add on the fly http://www.smartclient.com/smartgwt/showcase/#select_other_combobox_category

- Pick tree http://www.smartclient.com/smartgwt/showcase/#picktree_combobox_category

___
 Imported from https://dev.vaadin.com/ issue #6738

**Comment by TatuLund** [comment]
> Add on the fly http://www.smartclient.com/smartgwt/showcase/#select_other_combobox_category

Note, this use case has been supported since Vaadin 7,
