### ISSUE TITLE
Miller Columns

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1524]
**Originally by _kynao_**

___
Proposition illustrated here
http://www.smartclient.com/smartgwt/showcase/#featured_miller_columns

It may look simple but is a nice efficient component in terms of navigation. 

I would see to let the choice of displaying initially the different columns if we want to focus on a default value on each column.

___
 Imported from https://dev.vaadin.com/ issue #6749

**Comment by hezamu** [comment]
This issue can be closed, no longer relevant.
