### ISSUE TITLE
Enhance tabbing order/focus handling in "editable" Table

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1545]
**Originally by @mstahv**

___
Currently there are several inconveniences when using a Table which contains focusable components. Especially when there is a lot of rows in the table and a scrollbar is visible (pagelenght != 0).

E.g. if Table contains textfields on each row, the focus gets jam into table. Each tabulator press moves to next field, which may be on next row, and user can break away from the Table only by tabbing to the end/start of the Table or by using a mouse. Best would be that the focus breaks out of Table if the component is the last visible focusable component.

Also tabbing order of the table is currently bit counter intuitive. Table is after its children in tabbing order. To make the previously described case work somewhat correctly (without changing every other focusable component in Vaadin), we must probably make it focus both before and after.

Note, this is most likely very expensive to implement properly. Also has rather big regression risk.

___
 Imported from https://dev.vaadin.com/ issue #6853

**Comment by TatuLund** [comment]
Proper keyboard navigation is nowadays possible in Grid in Vaadin 7 / Vaadin 8 using https://vaadin.com/directory/component/gridfastnavigation-add-on
