### ISSUE TITLE
IE9: Table column is sometimes too wide

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1546]
**Originally by @Artur-**

___
See http://demo.vaadin.com/6.6-nightly/sampler/#TableHeaderIcons

The first column should be only so wide that the flags fit into it nicely. In IE9 there is some additional white space to the right of the flags.

___
 Imported from https://dev.vaadin.com/ issue #6854

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
