### ISSUE TITLE
Context menus should pop up on top of touch

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1554]
**Originally by @mstahv**

___
On touch devices context menus currently open as they do on pointer devices. It would be better for users if the menu would pop on top instead. This way finger/hand would not be over the appearing menu. This is especially bad currently for right handed persons.

___
 Imported from https://dev.vaadin.com/ issue #6873

**Comment by jouni** [comment]
This behavior has been/will be improved/redesigned with the vaadin-context-menu element: github.com/vaadin/vaadin-context-menu

The common pattern on (small) touch devices is to show the menu as an action/bottom sheet. For larger touch devices it might be okay to open the menu above the touch target.
