### ISSUE TITLE
FormLayout should support multiple columns

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1573]
**Originally by _martin.bolcina@gmail.com_**

___
FormLayout should be more like GridLayout. 

Now it is only possible to have fields in vertical order. You can not have for example two column form which is very common.

If you use GridLayout for form too achive this it works but the problem is that labels are put above fields and not on left of field like in FormLayout.

It would be great if either FormLayout would support more columns (and also vertical and horizontal span) or GridLayout would offer such label position as FormLayout. 

___
 Imported from https://dev.vaadin.com/ issue #6957

**Comment by TatuLund** [comment]
Vaadin 10+ onwards new FormLayout is totally remade and supports columns and is responsive.
