### ISSUE TITLE
Layout size recalculation not triggered on zoom in IE8 and IE7

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1576]
**Originally by @tepi**

___
To reproduce:

1. Open Sampler in IE8 or IE7.
2. Zoom out a few steps.
3. There are empty borders on the left and bottom sides of the main layout.

Seems there is no resize event fired on zoom.

___
 Imported from https://dev.vaadin.com/ issue #6966

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
