### ISSUE TITLE
Waiting for UIDL spinner redesign

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1614]
**Originally by @jojule**

___
Now long requests change the color of the spinner to yellow and red. The colors really do not have any meaning and they are disturbing from UX perspective. Should a user reach to red spinner somehow? How? Why?

Proposal for better design:
 - For the first 500ms, do not show any indicator
 - If the request lasts over 500ml, show a 
     - (In case of mouse operated UI) Change mouse cursor to a hourglass.
     - (In case of touch UI) spinner positioned to right top corner of the absolute window area (browser canvas or portlet or app-div). Make sure to position absolutely to keep it allways there even when page is scrolled.
 - No indications on how long the user has waited, but add css-classes for different stages (XHR sent, response downloaded (set before rendering), XHR failed - trying again). Do not use these classes in default themes
 - After 5 seconds of inactivity or failing XHR, show centered (to app-div) message div: "Problems with the connection to the server. Trying to reconnect" with a spinner. Gray out the application below and block events to application.
 - Allow customization of the above error message with Window.setConnectionDownErrorMessage(String)
 - Allow disabling of the above connection error dialog by Window.getConnectionDownErrorMessage() == null

**Comment by jouni** [comment]
I think we have done work towards this with the now default Valo progress indicator and the new reconnecting indicator. I would vlose this and ask for new, more specific issues if there are still things we can improve.
