### ISSUE TITLE
Add multi-select to NativeSelect

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1624]
**Originally by _OpenESignForms_**

___
Would like NativeSelect to add support for multiselect.

Per the Forum thread (http://vaadin.com/forum/-/message_boards/view_message/372165), it seems that the GWT ListBox it's built on supports it, and of course the actual native select in HTML supports it as well.

___
 Imported from https://dev.vaadin.com/ issue #7153

**Comment by jouni** [comment]
As NativeSelect is meant to use the native `<select>` element, we can’t change how it works. So this is a wontfix in my opinion.

We will probably add multi-select to ComboBox in the future. The relevant issue for that is #1517.

**Comment by OpenESignForms** [comment]
Any why can't <select multiple> be used?

http://www.w3schools.com/tags/att_select_multiple.asp

**Comment by jouni** [comment]
As I understand (have to admit, didn’t read the specs), having the `multiple` attribute causes the `<select>` element to transform from a dropdown into a list select, and I thought that was not what was wanted?

**Comment by OpenESignForms** [comment]
You are right.  You can close this.  In fact, the use of ListSelect is exactly what we do use for our multi-selects.  

I don't recall if old time browsers did this differently, or if it was a result of our generating selection lists via DB configuration in which we extended NativeSelect to do the work, but then found if the DB config allowed for multiple selections, it would break if we just called to the method to allow multiple choices (so we had to use NativeSelect or ListSelect instead).  Anyway, it's an old issue and not something we're stuck on at all.  I think we just used a ListSelect and set the rows to 1 for single select mode.

**Comment by jouni** [comment]
Alright, thanks for feedback! 👍🏻
