### ISSUE TITLE
Calendar panel height calculation fails

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1626]
**Originally by @tepi**

___
1. Go to http://demo.vaadin.com/sampler/#DatePopup
2. Keep switching between September 2011 and October 2011 using the date selection buttons.
3. Notice that in October, the calendar panel grows 1 pixel out of its containing popup, overflowing it.

Issue reproduced at least with IE7, IE8 and FF3.

This also happens with the inline datefield, and is especially annoying there when trying to theme a border around the datefield. This seems to be impossible due to this bug.

**Comment by TatuLund** [comment]
I could not reproduce this with a modern browser.

IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
