### ISSUE TITLE
Easy API for plugging in UI state storage engines

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1642]
**Originally by @jojule**

___
Now the state is stored in HttpSession (or in memcached in case of AppEngine). We should make it easy for people to implement their own storage engines for session state. In many cases HttpSession might not be the best place to store UI state and easing the selection of the storage would encourage people to choose alternatives.

I would consider this for Vaadin 7 to support use-cases that are either highly clustered or want to support "really really long" sessions pushed to disk for example.

#6349 should also be based on this feature. 

___
 Imported from https://dev.vaadin.com/ issue #7207

**Comment by TatuLund** [comment]
VaadinService#storeSession and VaadinService#removeSession methods are overrideable since Vaadin 7.6
