### ISSUE TITLE
ComboBox / AbstractSelect NewItem added again/erroneously when de-focusing

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1646]
**Originally by @emarc**

___
Initiated from this thread: http://vaadin.com/forum/-/message_boards/view_message/547437 (contains example code demonstrating the problem)

When tabbing out of (or otherwise de-focusing) a ComboBox, an extra newitem is sent to the server in some cases. 

If the item is previously added and selected on the serverside, a focus/defocus will send a newitem-change to the server. The DefaultNewItemHandler will try to add the item, but usually the container rejects the duplicate (silently). 

The same behavior can be seen in the Sampler by watching the UIDL traffic - when adding a new item, one newitem-change gets sent when pressing enter, another when tabbing out of the ComboBox.

Note: This anomaly is usually not detected since the container rejects the duplicate item.

I verified this with Sampler for 6.6, 6.5 and 6.4.

___
 Imported from https://dev.vaadin.com/ issue #7215

**Comment by VovaViter** [comment]
7.7.7 bug present
