### ISSUE TITLE
Table: Row select with mouse right-click and show context menu

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1672]
**Originally by _mortihead_**

___
I have table with right-click context menu

```
static final Action ACTION_OPEN = new Action("Open");
static final Action ACTION_PRINT = new Action("Print...");
static final Action ACTION_DELETE = new Action("Delete");
static final Action[] ACTIONS = new Action[] { ACTION_OPEN, ACTION_PRINT, ACTION_DELETE };

```

But while context menu apear selected row in table is not show!

http://vaadin.com/forum/-/message_boards/view_message/560324
http://vaadin.com/forum/-/message_boards/view_message/170794

I want this component work like e.g. Windows Explorer does - if the right clicked row is not selected, select it and show context menu!

Selecting row with right click can do in this code:

```
tblResult.addListener(new ItemClickListener() {
    public void itemClick(ItemClickEvent event) {
        if (event.getButton()==ItemClickEvent.BUTTON_RIGHT) {
            tblResult.select(event.getItemId());
        }
    }
});
```

But in this case the context menu just shows up (for half second) and disappears right away, the record is selected still. 

___
 Imported from https://dev.vaadin.com/ issue #7327

**Comment by FoxyBOA** [comment]
ItemClickEvent workaround doesn't work anymore with Tree 8.1 (click event doesn't have getButton() method anymore)

**Comment by hesara** [comment]
Related to that, see #9335.

**Comment by data443-cboyd** [comment]
This is what I use for this issue, with GridContextMenu (You'll have to use your own generic type, for the sake of the example I'm using Object):
```
	addGridContextMenuOpenedListener( new ComponentEventListener<GridContextMenu.GridContextMenuOpenedEvent<Object>>()
		{

			@Override
			public void onComponentEvent( GridContextMenuOpenedEvent<Object> event )
			{

				if ( event.getItem().isPresent() )
				{
					Grid<Object> grid = ((Grid<Object>) getTarget());
					grid.select( event.getItem().get() );
				}
			}
		} );
```
