### ISSUE TITLE
Table Inside Table

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1682]
**Originally by _Abhiram_**

___
This is an Extention to the existing Table Component. A new Component can be added at the Row level instead of just the Cell Level. The Added component at the Row lev will behave as the child of the above row and can expanded or collapsed from the parent row.

Simplifing the requirement of "table embedding" to a generic case of "allow embedding of a component under table row with expand/collapse".
1. The embedded component will be loaded when the expand arrow is clicked. 
2. The loading of the component can be lazy/eager customizable(optional)
3. Width of the component is always the width of the row. If it is more horizontal scroll bar should appear for the component.
4. Height of the component is fixed (must be given). If the component height is more than given height vertical scroll bar should appear. 
5. Padding (Left, Right, Top and Bottom) to the embedded component should be allowed (Default zero padding).
6. Zero, one or more than one expansion can be shown at a time  
7. Expansions should be shown by pushing below rows downwards and should not overlap the below rows.
8. Collapse/Expand Icon/Image should be customizable (Developer should be able to be change the image/icon).

In the end this feature would allow putting another table (or any other component) inside the Table row.

___
 Imported from https://dev.vaadin.com/ issue #7358

**Comment by santeriv** [comment]
(note to self)
