### ISSUE TITLE
Component should add setName() and getName() method

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1701]
**Originally by _likebean_**

___
In many circumstances,It need the funtion:ComponentContainer.getComponent("componentName"),
So It need getName() and setName() method on component to support this funtion.the name used to identify the component.

___
 Imported from https://dev.vaadin.com/ issue #7429

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/3065

There is getId/setId methods since Vaadin 7.0
