### ISSUE TITLE
Portlet expired session handling should be more customizable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1719]
**Originally by @hesara**

___
Certain exceptions such as SessionExpiredException are only logged using logger.finest()/fine() by AbstractApplicationPortlet.handleRequest() without the possibility to customize their handling.

AbstractApplicationServlet has methods handling those exceptions, and the methods can be overridden for customization. The same approach should be taken in AbstractApplicationPortlet.

See http://vaadin.com/forum/-/message_boards/view_message/208778 for more details.

___
 Imported from https://dev.vaadin.com/ issue #7477

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/2868
