### ISSUE TITLE
Theme files loaded from a css file using AlphaImageLoader only works in the root context

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1726]
**Originally by @Legioth**

___
Theme files loaded from a css file using AlphaImageLoader for IE 6 only works in the root context as AlphaImageLoader resolves file paths relative to the document path instead of the path of the css file. The currently used workaround, to define all paths starting with /VAADIN/themes, assumes that the application is deployed in the root context.

___
 Imported from https://dev.vaadin.com/ issue #7496

**Comment by Artur-** [comment]
IE6? Did anybody say outdated issue?
