### ISSUE TITLE
Add EL expression data binding furture

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1755]
**Originally by _likebean_**

___
Need function like following:

Label label1 = new Label();
label1.setId("label1");
...
Label label2 = new Label();
label2.setValue("#label1.value");

when label1 value changed,the label2 value will  auto change.
I think this will make vaadin more powerful.

L.J.W 

___
 Imported from https://dev.vaadin.com/ issue #7569

**Comment by jouni** [comment]
Closing as wontfix. @Legioth and @Artur- can disagree and reopen if they see something this as relevant.
