### ISSUE TITLE
Pass possible exceptions to CustomizedSystemMessages

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1768]
**Originally by @Peppe**

___
Vaadin has a possibility to modify the messages like "Internal Error" and "Session Expired" through CustomizedSystemMessages. Often there is some exception that causes these errors, and sometimes you would like to customize the message based on the exception. Today you won't get the exception in CustomizedSystemMessages so you can't know what the reason for the error was. 

You can catch the error in Application.terminalError, but AbstractApplicationServlet.handleServiceException(request,response,applicaiton,throwable) calls first criticalNotification and den terminalError. That means that the notification to the user is already rendered when it gets to the terminalError.

As a solution, handleServiceException() could pass the throwable to the CustomizedSystemMessages, where after you could check those when building the messages.

You'd need to change AbstractApplicationServlet.handleServiceException(), line 988
```
criticalNotification(request, response, ci.getInternalErrorCaption(),
 ci.getInternalErrorMessage(), null, ci.getInternalErrorURL());
```
to
```
criticalNotification(request, response, ci.getInternalErrorCaption(e),
 ci.getInternalErrorMessage(e), null, ci.getInternalErrorURL(e));
```
and build up a few wrapper methods for all the getters of SystemMessages in CustomizedSystemMessages:

```
public String getInternalErrorMessage(Throwable throwable) {
  return getInternalErrorMessage(throwable);
}
```

**Comment by TatuLund** [comment]
For centralized error handling one should use VaadinSession#setErrorHandler(ErrorHandler)
