### ISSUE TITLE
Text alignment in ComboBox and DateField changed in Chrome 14

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1771]
**Originally by @Legioth**

___
The recently launched Chrome 14 renders the text in ComboBox and DateField on pixel lower than in previous versions of Chrome, causing baseline alignments with captions in a FormLayout to fail.

This can be seen e.g. in EmptyFieldErrorIndicators which should have aligned labels as well as in a multitude of different tests where the text has just moved without causing any visible misalignments.

___
 Imported from https://dev.vaadin.com/ issue #7641

**Comment by jouni** [comment]
Probably very much outdated.
