### ISSUE TITLE
Error indicator missing for IE8 (Chameleon)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1803]
**Originally by @Artur-**

___
When a component should show an error indicator and you are using the Chameleon theme the error indicator is shown in all browser but Internet Explorer 8. 

See test: com.vaadin.tests.components.label.LabelTooltip-chameleon.html

___
 Imported from https://dev.vaadin.com/ issue #7721

**Comment by jouni** [comment]
Probably obsolete, as the old themes will be deprecated in version 8.
