### ISSUE TITLE
Error indicator is not transparent in IE6 (Chameleon)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1804]
**Originally by @Artur-**

___
The error indicator in Chameleon is not shown with a transparent background in IE6.

See test: com.vaadin.tests.components.label.LabelTooltip-chameleon.html

___
 Imported from https://dev.vaadin.com/ issue #7722

**Comment by jouni** [comment]
Probably obsolete, as the old themes will be deprecated in version 8.
