### ISSUE TITLE
Error indicator causes part of component to be hidden in IE7 (Chameleon)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1805]
**Originally by @Artur-**

___
An undefined wide Label with an error indicator inside a GridLayout is clipped when using the Chameleon theme. Looks like the width reserved for the Label is what would be required if the error indicator was not there.

See test: com.vaadin.tests.components.label.LabelTooltip-chameleon.html

___
 Imported from https://dev.vaadin.com/ issue #7723

**Comment by jouni** [comment]
Probably obsolete, as the old themes will be deprecated in version 8.
