### ISSUE TITLE
Support column group

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1817]
**Originally by _wattlee_**

___
Please refer to forum thread [https://vaadin.com/forum/-/message_boards/view_message/775226].[[BR]]
Column group is a normal usage in table. It's supported by most of RIA frameworks, and there is no sch a feature in Vaadin.

___
 Imported from https://dev.vaadin.com/ issue #7759

**Comment by TatuLund** [comment]
This has been implemented in Grid component since Vaadin 7.6
