### ISSUE TITLE
Add Tree feature to disable expanding/collapsing of nodes

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1929]
**Originally by _comag_**

___
There should be a possibility to prevent the user to expand or collapse nodes of a tree.

Some ideas:[[BR]]

1) Tree.setModifiable/Immutable/...(boolean): affects collapsing/expanding of all nodes[[BR]]

2) Tree.setExpandable(itemId, boolean), Tree.setCollapsable(itemId, boolean): affects collapsing/expanding of single nodes[[BR]]

3) make ExpandListener and CollapseListener vetoable (let return a Boolean or Enum in nodeExpand() / nodeCollapse()). this requires an additional client/server roundtrip.[[BR]]

___
 Imported from https://dev.vaadin.com/ issue #7982

**Comment by tsuoanttila** [comment]
This feature exists in the Vaadin 8 Tree as `setItemCollapseAllowedProvider`.
