### ISSUE TITLE
Add expandItemsRecursively and collapseItemsRecursively to the TreeTable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1934]
**Originally by _Equilibrix_**

___
The TreeTable should contain the methods *[expandItemsRecursively](https://vaadin.com/api/com/vaadin/ui/Tree.html#expandItemsRecursively(java.lang.Object))* and *[collapseItemsRecursively](https://vaadin.com/api/com/vaadin/ui/Tree.html#collapseItemsRecursively(java.lang.Object))* as the Tree does. 

It is, of course, possible to implement this behavior by recursively going through the structure of the hierarchical container and call *setCollapsed* on every child but it would be nice to have this as a core feature, possibly more effectively implemented than doing it manually.

___
 Imported from https://dev.vaadin.com/ issue #7995

**Comment by tsuoanttila** [comment]
This feature exists in the Vaadin 8 TreeGrid
