### ISSUE TITLE
Remove Container.Ordered

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1948]
**Originally by @Legioth**

___
Remove Container.Ordered. This interface has little real life value and complicates all container implementations by requiring implementation of 8 extra methods. Also complicates all components that use containers by requiring them to handle Containers that are not indexed. All Container.Ordered methods will still be available in all core container implementations.

___
 Imported from https://dev.vaadin.com/ issue #8025

**Comment by pleku** [comment]
Not part of FW 8.0
