### ISSUE TITLE
Tabel multiselect Set<Object>

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1971]
**Originally by _florianpirchner_**

___
Hi,

i know that the use of util.Sets for AbstractSelects multi selection was a design decision of vaadin. And in the most cases it may be useful. But it is a real blocker if the selected elements should be used in the order of the table index.

Ekkehard and me are working on the map integration into redVoodo right now. And it is really necessary, that the map shows the points and paint lines between them in the order they appear in the table.

Actually we solved the problem by storing the index of the result set in the item id and let implement it Comparable. Then we are able to sort the entries after table.getValue().

But it increases the dependencies of the Container to the UI elements and the business logic of redVoodo.

Are there any thoughts about some kind of a switch that defines whether Sets or Lists should be returned by the table? SortedSet would also be fine.

Kind regards,
Florian Pirchner

___
 Imported from https://dev.vaadin.com/ issue #8063

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/2370
