### ISSUE TITLE
Error indicator misplaced for TextField in IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1977]
**Originally by @Artur-**

___
See test com.vaadin.tests.validation.ValidationOfRequiredEmptyFields and attached images. The error indicator should be placed next to the required indicator and not below it.

___
 Imported from https://dev.vaadin.com/ issue #8078

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
