### ISSUE TITLE
Setting a caption for "no selection" in a Select is clumsy

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#1995]
**Originally by @wolfie**

___
Instead of using a caption, I decided to utilize the "null selection" functionality in Selects.

The I assumed (and wished) the code required would be something in the lines of:
```
select.setItemCaption(null, "My Caption");
```

instead, i need to write:
```
Object nullId = new Object();
select.addItem(nullId);
select.setItemCaption(nullId, "My Caption");
select.setNullItemId(nullId);
```

I feel the latter is unnecessarily long code. Since "null" is the value when selecting the "null item" anyways, I have a hard time understanding why null needs a magic object associated to it.

PS: The JavaDoc is pretty unclear on the proper way of configuring null items, at the very least, the javadoc needs improvement.

**Comment by TatuLund** [comment]
Vaadin 8 changed concept from null item to empty selection in Select, ComboBox etc.
