### ISSUE TITLE
Liferay theme - h1-h4 styles display as plain text

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2012]
**Originally by _tomeklipski_**

___
Tested on Liferay 6.0.6 CE (Vaadin theme, jar and widgetset updated to 6.7.3).

To make it work, you can add something like this:

```
.v-label-h1,
.v-label h1,
.v-label-h2,
.v-label h2,
.v-label-h3,
.v-label h3,
.v-label-h4,
.v-label h4 {
	margin: 0;
	font-weight: bold;
	}

.v-label-h1,
.v-label h1 {
	padding: .75em 0 .5em 0;
	font-size: 1.85em;
	}

.v-label-h2,
.v-label h2 {
	padding: .67em 0 .33em 0;
	font-size: 1.4em;
	}

.v-label-h3,
.v-label h3 {
	margin: .71em 0 .29em 0;
	font-size: 1.1em;
	}

.v-label-h4,
.v-label h4 {
	padding: .23em 0;
	font-size: 1em;
	}
.v-label-color {
    color: #287ECE;
}
```

to styles.css in liferay theme. CSS values copied from chameleon theme but real theme could use these from Liferay's Alloy UI.

___
 Imported from https://dev.vaadin.com/ issue #8147

**Comment by jouni** [comment]
Probably not worth fixing, as all old themes will be deprecated in version 8.
