### ISSUE TITLE
Check if TextField null representation can be removed

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2041]
**Originally by @Artur-**

___
Converters can handle null representation for all components, not only TextField. Check if there is any reason to keep null representation and null setting allowed or if the same features can be better implemented using a Converter.

___
 Imported from https://dev.vaadin.com/ issue #8189

**Comment by Legioth** [comment]
Does not make sense as of Vaadin 8.0 because the null representation is no longer a feature of the field component.
