### ISSUE TITLE
Tree display problem on IE with zoom

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2045]
**Originally by _alocquet_**

___
There is a problem displaying tree when user zoom in the page on IE. Some lines are displaid in the tree with no reason.

You can reproduce easily the bug on Vaadin sampler on IE7 and on IE8, but neither on Firefox nor on Chrome. Go on sampler and zoom in the page (browser zoom ~ Ctrl +).

I think that these lines come from arrow.png or sprintes.png image.

___
 Imported from https://dev.vaadin.com/ issue #8197

**Comment by jouni** [comment]
Wontfix
