### ISSUE TITLE
Notify Container when the Component is attached/detatched

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2072]
**Originally by _mthomas_**

___
I would like an interface or some method to notify a Container that is the ContainerDataSource of a given Component that the Component has been attached/detached from the application.

Use case:  Component 'A' has Container 'C' as its ContainerDataSource.  'C' listens to events from an object 'O' that is outside the Vaadin framework (e.g. singleton Spring Bean, JMS Queue/Topic, ESB, etc.).  Now if 'A' is removed from the application 'C' is still a listener to 'O' and if 'O' fires an event then 'C' changes and causes 'A' to repaint.  At this point an error occurs because the detached Component 'A' has no Window as its top-most parent.

___
 Imported from https://dev.vaadin.com/ issue #8262

**Comment by Artur-** [comment]
The whole Container/Item/Property concept has been retired and moved to the v7 compatibility package in master. It is highly unlikely that these concepts will receive new features.
