### ISSUE TITLE
setImmediate(boolean) should be declared in Component interface

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2080]
**Originally by @marlonrichert**

___
Right now, setImmediate(boolean) is declared in AbstractComponent, which means that if I want to call it on a given Component, I need to cast it to AbstractComponent first. This shouldn't be necessary.

___
 Imported from https://dev.vaadin.com/ issue #8276

**Comment by Artur-** [comment]
Wontfix, setImmediate has been removed from Component in master
