### ISSUE TITLE
Allow HTML in combobox options

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2132]
**Originally by _alocquet_**

___
Actually, combobox options allows only simple text.
It should be great to allow usage of HTML.

 1. add a boolean in FilterSelectSuggestion constructor
 2. in VFilterSelect updateFromUIDL() method, put a boolean to manage HTML usage.

___
 Imported from https://dev.vaadin.com/ issue #8400

**Comment by santeriv** [comment]
(note to self)

**Comment by Legioth** [comment]
This might actually make (slightly) more sense with Framework Vaadin 8 where the rendering and filtering can be detached from each other.

**Comment by TatuLund** [comment]
This has been implemented in Vaadin 10+ ComboBox as template renderer https://vaadin.com/components/vaadin-combo-box/java-examples/using-components
