### ISSUE TITLE
Make UploadInterruptedException public

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2141]
**Originally by _snicoll_**

___
I am building a simple layout similar to the sampler "upload immediate" thing. All things are working fine except that I want to show an error notification if the upload failed.

When the user press cancel (see http://demo.vaadin.com/sampler#ImmediateUpload) this will actually triggers an UploadInterruptedException. Which will call the FailedListener.

Of  course, when such a case happens, I do NOT want to show the notification since the user has pressed cancel explicitly. I can't check for that case since the exception is not public API

Maybe relying on that exception is bad as well, a flag that would state the upload has been interrupted  would be better.

Thanks

___
 Imported from https://dev.vaadin.com/ issue #8418

**Comment by TatuLund** [comment]
It is public https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L214
