### ISSUE TITLE
Refactor event router so it does not use reflection

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2276]
**Originally by @Artur-**

___
The event router should be simplified to be similar to the EventBus in GWT. Reflection should be removed and instead all Event classes should be forced to extend com.vaadin.ui.Component.Event. com.vaadin.ui.Component.Event should define an 
```
public abstract void dispatch(T listener);
```
which event classes implement, typically as
```
listener.whatevermethodisdefined(this);
```

___
 Imported from https://dev.vaadin.com/ issue #8640

**Comment by TatuLund** [comment]
This was partially done in Vaadin 8 and is fully completed in Vaadin 8.12.
