### ISSUE TITLE
Make overwriting showCommunicationError easier (make methods protected instead of private)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2349]
**Originally by _knut.hertel_**

___
When trying to overwrite the default showCommunicationError method in ApplicationConnection, one cannot use the internally called
showError() Method as it is defined as private. One can also not replace the showError() Method as the methods to use a redirect are also private.
So in order to create your own showError() Methods, at least showError() and redirect() and NotificationRedirect should be protected.

Use Case:
In our application two different scenarios can lead to a communication error (a session timeout of the underlying SiteMinder SSO infrastructure or a real network problem). We want to display
two different messages and two different redirect URLs. Currently this is not possible, due to the restrictive access rights to the methods.

___
 Imported from https://dev.vaadin.com/ issue #8752

**Comment by TatuLund** [comment]
Text and url have been possible to be configured since Vaadin 7 using CustomizedSystemMessages.
