### ISSUE TITLE
Replace all "/VAADIN/" hard coded strings with a constant you can override in AbstractApplicationServlet

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2378]
**Originally by @johndevs**

___
Currently it is really hard  to change the default static resources folder name due to the fact that the folder name has been hard coded in multiple places in the AbstractApplicationServlet. 

A better way would be to have a protected getter which would return that folder name for easy extension. 

___
 Imported from https://dev.vaadin.com/ issue #8806

**Comment by TatuLund** [comment]
In Vaadin 8, the use case has been fixed effectively by this change using init parameters for custom resources folder: https://github.com/vaadin/framework/commit/1e978a6ba0924c240803543a31d024b7c649f4ce
