### ISSUE TITLE
Support RFC 1867 accept attribute for file upload

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2410]
**Originally by @hesara**

___
The RFC 1867 accept attribute enables defining which MIME types are selectable in a file upload dialog. While the browser support is limited, many newer versions of browsers do support it. We could add support for setting the attribute in the Upload component, with a warning that not all browsers respect it.

See http://en.wikipedia.org/wiki/File_select#Accept_attribute and the forum thread https://vaadin.com/forum/-/message_boards/view_message/428096 .

___
 Imported from https://dev.vaadin.com/ issue #8857

**Comment by sirbris** [comment]
will this be integrated in Vaadin 8 or is there a workaround maybe?

**Comment by focbenz** [comment]
Would be a nice feature for guiding the use to select only specified files.

**Comment by sirbris** [comment]
no workaround at least?

**Comment by BenICE** [comment]
I guess you already found a way around, but here is how we solved it:
```
String javascript = "Array.from(document.getElementsByClassName('gwt-FileUpload')).forEach("
		+ "function(element, index, array){element.setAttribute('accept', '" + validImageFormats + "')});";
JavaScript javaScript = JavaScript.getCurrent();
javaScript.execute(javascript);
```

Still I vote to have it properly integrated into vaadin :)

**Comment by focbenz** [comment]
Nice - accept in Vaadin 8.5.0!
