### ISSUE TITLE
Empty space in bottom of Table in IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2450]
**Originally by @Legioth**

___
The row height rounding in IE9 sometimes causes extra space in the bottom of a Table with pagelength=0. This happens e.g. if the height of one row is 19.8 and there are two rows in the table. This gives a total height of 39.6 which requires 40px of space to avoid scrolling but it is displayed as 39px. The extra pixel that is there to avoid scrolling is then displayed as a white line between the last row and the table border.

Related to #6852 and caused problems when fixing #6039.

This can be seen in the test com.vaadin.tests.components.table.PropertyValueChange

___
 Imported from https://dev.vaadin.com/ issue #8937

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
