### ISSUE TITLE
Navigator.navigateBack() or history is often needed

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2520]
**Originally by @emarc**

___
In the new Navigator API, there is no built in history (server side). This is sometimes needed - arguably most often to navigate back to the previous View.

Though this can be implemented in application logic e.g by adding a ViewChangeListener and remembering the previous View(s), it would be convenient if this was made easier. 

One possibility is to add Navigator.navigateBack(), another is to pass the previous View to View.navigateTo().

Note: if View is made to implement ViewChangeListener, as proposed in #9055, this is probably a non-issue since the ViewChangeEvent contains the previous View.

___
 Imported from https://dev.vaadin.com/ issue #9058

**Comment by sknitelius** [comment]
I don't think its a problem if there is a discrepancy between the browser history and the server sided history.

In the end effect it would be really handy to have a back and forward stack that is written to each time navigateTo is called. 

So that you could easily call navigator.back().

**Comment by TatuLund** [comment]
This is implemented in Vaadin 8.2 @PushStateNavigation, see more

https://vaadin.com/docs/v8/framework/advanced/advanced-pushstate.html
