### ISSUE TITLE
Add a "context://" protocol

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2523]
**Originally by @Legioth**

___
The framework is currently supporting theme://, app:// and connector:// URI schemes which on the client-side are resolved based on runtime information. Explicit support for these could be used together with @JavaScript and @StyleSheet annotations as those do not accept e.g. ThemeResource instances.

We could provide explicit support including proper documentation of these.

If we decide to support the existing schemes, we could also consider adding e.g. context:// which is resolved relative to the deployed context path (essentially the same as app://) and vaadin:// which is resolved relative to the /VAADIN/ directory (essentially theme://../../ assuming the themes folder is always located inside VAADIN). 

___
 Imported from https://dev.vaadin.com/ issue #9062

**Comment by Artur-** [comment]
`vaadin://` has been implemented a long time ago but `context://` would still be useful as there is currently no way to refer to e.g. a file in "src/main/webapp"
