### ISSUE TITLE
cannot insert values into combobox that are not already part of the value list

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2560]
**Originally by _vinaddala_**

___
```
 String[] cities = new String[] { "Berlin", "Brussels","Helsinki", "Madrid", 
"Oslo", "Paris", "Stockholm" };
	            ComboBox l = new ComboBox("Please select a city");
	            for (int i = 0; i < cities.length; i++) {
	                l.addItem(cities[i]);
	            }
	            l.setValue("xyz");
	            l.setImmediate(true);
```

Using the above code, the value "xyz" is not set in the combobox. The reason I want to do this is that I want to show value "xyz" but once the user changes it to something like "Oslo" they should not be allowed to choose "xyz". I also don't want "xyz" to appear in the list of combobox value choices. "xyz" can be considered a temporary/default value.

workaround: do l.addValue("xyz") first.

___
 Imported from https://dev.vaadin.com/ issue #9137

**Comment by TatuLund** [comment]
Implemented in Vaadin 7.0 by ComboBox#setNewItemsAllowed(boolean)
