### ISSUE TITLE
No real way to define null label on combo box

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2587]
**Originally by _frosiere_**

___
It's currently impossible to define the label of a null item except by doing a new item, then to set the value of the null label, ...

Concrete example: suppose a comboBox containing a list of persons and displaying the first name of the person. 

A way we have for the moment is to create a new person, then to set the first name of these person with the null label we want, then to call setNullSelectionItemId with this person on the combo box... 

Really?!!! Why is it so complex?

This problem could be solved by given a way to override the default value displayed for the null item:

@see Select#paintContent

```
        if (paintNullSelection) {
            target.startTag("so");
            target.addAttribute("caption", ""); 
            // IT SHOULD BE POSSIBLE TO GIVE A CUSTOM VALUE
            target.addAttribute("key", "");
            // IT SHOULD BE POSSIBLE TO GIVE A CUSTOM VALUE
            target.endTag("so");
        }
```

I joined the code we had to override just to be able to provide a custom value instead of the default one.

In the new version of Vaadin, it could be really nice to add a method to set the null label easily.

___
 Imported from https://dev.vaadin.com/ issue #9176

**Comment by tsuoanttila** [comment]
This feature is available in Vaadin 8 ComboBox using method `ComboBox::setEmptySelectionCaption` and achievable in Vaadin 7 ComboBox via `ComboBox::setNullSelectionItemId`
