### ISSUE TITLE
Ability to support the itemrenderer concept (flex) or Template concept (Sencha GXT)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2632]
**Originally by _sberube_**

___
One of the most powerful features of flex was the concept of an item renderer. Lets take a list for example. For each item  in the list the renderer would define how the row would appear to the user. 

Sencha GXT (also based on GWT) provides this in the form of a template.

Here is an example:
http://stackoverflow.com/questions/3999034/how-to-set-item-renderer-for-listview-in-ext-gwt

The basic example is this:
public initializeView()
{
listView.setStore(listStore);
listView.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);
listView.setTemplate(getTemplate());
}

private native String getTemplate() /*-{ 
 return ['<tpl for=".">',
 '<div class="{style}">{foo.name}</div>', 
 '</tpl>', 
 '<div class="x-clear"></div>'].join(""); 
}-*/;

The set template defines how each row is drawn. And it uses symbolic replacements to do this with standard HTML syntax. This is very powerful feature and they use it throughout the GXT platform for almost every control.

I think this feature would make vaadin much more flexible than it is right now. For example to do this in vaadin, i could not use a list control I had to use a table control and disable the header, borders, sorting, collapsing etc to make it look like a list control.

___
 Imported from https://dev.vaadin.com/ issue #9258

**Comment by hesara** [comment]
Renderers and HtmlRenderer were implemented for Grid in Vaadin 7.4, and made somewhat easier to customize with lambdas in 8.0.
