### ISSUE TITLE
Support URLs without fragments in Navigator

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2691]
**Originally by @Artur-**

___
Navigator should support using session history management instead of URI fragments (#!) for browsers which support push state (not in IE8,IE9, Androids and maybe others).

When using session history management:
 - If the user navigates to a #!/my/view url it should change to /my/view.

When not using session history management
 - If the user navigates to /my/view he should be redirected to #!/my/view

The Navigator API must use both the path and the fragment to decide the navigation state. If a fragment is present, it overrides the path, e.g. /my/view#!/my/secondview shows secondview

**Comment by tsuoanttila** [comment]
This issue has been resolved with the `PushState` based navigation in Vaadin 8.2.0.
