### ISSUE TITLE
Define common variables for SASS themes

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2700]
**Originally by @emarc**

___
We should define  variables for some common properties, that could then be used in themes and especially add-ons. 

For instance, if Base defined e.g $disabledFontColor, an add-on could make use of that variable in it's theme. When the add-on is then added to a project, the add-on would automatically adopt the color used in the main theme used in the project.

Potential candidates include colors, margins, paddings, gradients, borders, ... 

___
 Imported from https://dev.vaadin.com/ issue #9381

**Comment by jouni** [comment]
Probably not worth fixing any more, as all old themes (including base) are going to be deprecated in version 8. After that, the Valo variables will fulfill this need.
