### ISSUE TITLE
Rename CssLayout to SimpleLayout

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2709]
**Originally by @jouni**

___
Since CssLayout has been an integral part of the framework for such a long time, and one of our main goals is to try and hide all the mess of CSS from the developers, we could rename CssLayout to SimpleLayout. The protected getCss method could be moved to AbstractLayout so all layouts would have the same possibility of making small CSS adjustments on a component basis from the server side (a somewhat frequent request, which we have ignored).

The plain name "SimpleLayout" would indicate that it doesn't do anything special or guarantee any positioning of the contained components, and that it's the most light-weight of the layouts. And the new name shouldn't scare anyone any more.

It is almost like an AbstractLayout in a sense, which others could easily extend or use as a base for their own component containers.

**Comment by jouni** [comment]
Wontfix. Would be simple to change in the code, but a lot of hassle to update all existing documentation.

Framework 9 will probably not include this layout any more, so this issue is less relevant anyway.
