### ISSUE TITLE
Make open/close transitions possible with CSS for all overlay elements

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2746]
**Originally by @jouni**

___
In order to allow theme developers to make CSS transitions work for opening and closing overlay elements, we need to
 - add a CSS class (e.g. `v-overlay-opened`) to the element when it's attached to the DOM and then remove it right after it with a 0ms delay (i.e. DeferredCommand)
 - add a CSS class (e.g. `v-overlay-closed`) to the element before it is removed from the DOM, and then remove the element either after predefined delay or after a transitionEnd even on the element

The former is easy to implement, but the latter requires either browser/feature sniffing whether the browser supports transition events or fixing the delay (restricts the transition duration). Both should probably be done directly to VOverlay.

___
 Imported from https://dev.vaadin.com/ issue #9457

**Comment by jouni** [comment]
This feature was added in 7.3, together with the Valo theme.
