### ISSUE TITLE
Allow icons to be placed "inside" a TextField without resorting to layout and CSS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2757]
**Originally by @jouni**

___
Currently it is not possible to add an icon inside a TextField (see pic) using Java APIs only. It can be hacked together using either plain CSS (a background image on the input) or by using a wrapping layout and placing an Embedded and TextField on top of each other.

This is a common use case which should be covered by the Java API directly. The developer should be able to define where the icon for the TextField is placed: either beside the caption as currently or inside the field.

What comes to implementation, we only a have two options: either wrap the input element statically or dynamically with a span/div, or use a CSS background (we inflexible, since the field size won't respect the icon height automatically and the background can be overridden by CSS (and no other background image can be used in older browsers then for the input).

I opt for a wrapper element, since that would let us get rid of this annoying issue: https://dev.vaadin.com/ticket/2384
We could style the wrapper element instead, and reset all styles for the inner input element (`appearance: none`)

___
 Imported from https://dev.vaadin.com/ issue #9476

**Comment by jouni** [comment]
Valo theme (introduced in 7.3) provides a workaround for this, when you use TextFields inside core layouts that handle captions: https://demo.vaadin.com/valo-theme-2/#!textfields

I don’t think we will fix this for our current GWT based textfield implementation. Framework 9 together with Vaadin Core Elements should finally fix this issue for real.
