### ISSUE TITLE
Allow sub-window to be resized from any corner and side

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2758]
**Originally by @jouni**

___
Currently a sub-window can only be resized from the bottom-right corner. We should add drag handles to every side and corner for better usability.

It is not necessary to have static visual resize indicators (other than the cursor) in those places. We could probably even remove the bottom-right indicator.

___
 Imported from https://dev.vaadin.com/ issue #9477

**Comment by TatuLund** [comment]
Finally implemented in Vaadin 14.3 by Dialog component.
