### ISSUE TITLE
Using inner class RPC interface does not work.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2823]
**Originally by @Legioth**

___
You can compile a widgetset that uses an RPC interface that is defined inside some other class or interface, but at runtime there will be an exception because no meta data can be found for the interface.

This is most likely caused by some code using Outer.Inner and some code using Outer$Inner. We should either ensure that inner interfaces can be used or make the compiler refuse to compile a widgetset with such RPC interfaces.

___
 Imported from https://dev.vaadin.com/ issue #9607

**Comment by mvysny** [comment]
That is true. I just encountered this bug. Basically the browser will show a rather non-informative message:
```
Error performing server to client RPC callsjava.lang.IllegalStateException: There is no information about pl.exsio.plupload.client.PluploadClientRpc.setOption Did you remember to compile the right widgetset?
.....
Caused by: com.vaadin.client.metadata.NoDataException: There are no parameter type data for pl.exsio.plupload.client.PluploadClientRpc.setOption
```

**Comment by Artur-** [comment]
Seems like the client side class metadata generator uses the binary name `Outer$Inner` whereas the server sends the interface name in a source name format `Outer.Inner`.
