### ISSUE TITLE
There should be a UI.destroy() or cleanup()

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2907]
**Originally by @Artur-**

___
The method would be called from user code when it is essential that the the UI is immediately removed from its VaadinSession. Typical use case would be an app where you have UI specific login/logout and at logout want to ensure that the UI is cleaned immediately to save memory.

___
 Imported from https://dev.vaadin.com/ issue #9756

**Comment by TatuLund** [comment]
I would assume that UI#detach() should do the job.
