### ISSUE TITLE
Improve Locale handling with system messages

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2965]
**Originally by @Legioth**

___
#4127 adds a way of getting SystemMessages for a specific Locale. In addition to this, we should ensure the most appropriate SystemMessages is used:
* If the Locale of a UI or VaadinServiceSession is changed, the client-side messages (e.g. the communication error message) should also be updated
* Requests to the server should include information about the set Locale to enable returning appropriate messages e.g. if the VaadinServiceSession that held the users's Locale setting can't be found.

___
 Imported from https://dev.vaadin.com/ issue #9869

**Comment by TatuLund** [comment]
Implemented since Vaadin 7.0
