### ISSUE TITLE
Managing class loaders with OSGi

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#2999]
**Originally by @jdahlstrom**

___
Each OSGi bundle has a dedicated class loader and there is no overarching fallback "system loader". This means that a bundle cannot dynamically load classes or resources that reside in another bundle unless it somehow has access to that bundle's class loader. The `Import-Package` and `Export-Package` manifest attributes do not help here, as those are only used to resolve static dependencies at deployment time.

This currently causes (at least) two critical issues with Vaadin:

1. The server bundle cannot actually load the `UI`s and/or `UIProviders` in a user application unless the application overrides `VaadinService.getClassLoader()` as follows:

```
public class OsgiTestServlet extends VaadinServlet {

    @Override
    protected VaadinServletService createServletService(
            DeploymentConfiguration deploymentConfiguration) {
        VaadinServletService service = new VaadinServletService(this, deploymentConfiguration) {
            @Override
            public ClassLoader getClassLoader() {
                return getClass().getClassLoader();
            }
        };
        // init() needed in 7.1, invalid in 7.0
        service.init();
        return service;
    }
}
```

2. The server bundle cannot serve the widgetset and themes from their respective jars.  This could be partially solved by turning the `vaadin-themes` and `vaadin-client-compiled` jars into [fragments](http://wiki.osgi.org/wiki/Fragment) of the `vaadin-server` bundle so they have a common class loader. Of course, if `getClassLoader()` is overridden as above, this does not help and the application must repackage Vaadin widgetset and themes in its own bundle - not very nice.

See http://njbartlett.name/2010/08/30/osgi-readiness-loading-classes.html

**Comment by elmot** [comment]
OSGi support is completely rewritten in 8.1, most probably we can close this ticket.
Sass compiler and push under OSGi have their own tickets:
#8832, #5642
