### ISSUE TITLE
Add Scala support for client side

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3085]
**Originally by @hezamu**

___
Scala support for client side would be a huge differentiator from stock GWT. To achieve this we could port the [Scala GWT project](https://github.com/scalagwt) to GWT 2.5 and incorporate it to Vaadin.

Some notes
 - Ask Typesafe if they would collaborate with the effort, having eg. Grzegorz Kossakowski would be a great help.
 - Ask Typesafe if they would adopt the Scala compiler patches for Jribble support. It might be possible to incorporate them as a compiler plugin.
 - Superdevmode and source maps might potentially need a lot of work. Decide if we can do without those, at least at first release.

**Comment by hezamu** [comment]
This issue can be closed, no longer relevant.
