### ISSUE TITLE
ALWAYS put a wrapper div around TextField's <input /> element

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3111]
**Originally by @marlonrichert**

___
In the current implementation, sometimes there's a wrapper div around TextField's input element, and sometimes there's not. This makes it impossible to create a re-usable theme for your TextFields, since you first have to know what kind of Layout your TextField is in before you can theme it!

Please **always** use the same DOM structure for each instance of a given Component class, regardless of the context. Components' DOM structure should not be context-sensitive, because it makes creating re-usable, context-free themes impossible!

(See also #2757 for a related issue.)

**Comment by jouni** [comment]
As noted, you can do some workarounds when you know what layouts you use. Valo uses this and provides a workaround for icons inside textfields with it (a workaround for #2757)

And similarly, I don’t think we will fix this for our current GWT based textfield implementation. Framework 9 together with Vaadin Core Elements should finally fix this issue for real, although it might introduce some other theming related issues, as shadow DOM will be introduced and you can’t target any elements freely inside.
