### ISSUE TITLE
Performance: ability to set visible columns along with data source for table

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3130]
**Originally by _vilo_**

___
The setContainerDataSource method sets visible columns to all property ids in the container and immediately populates the table (i.e. calls getValue for properties). Only after that I'm able to call setVisibleColumns to see only few of the columns. This is inefficient, especially when it causes many lazy-initialized columns to be initialized.

Analogical case is found in Form, which already has a two-parameter setItemDataSource(Item, Collection) method, which helps exactly in the same case.

The use case is common, for example BeanContainer automatically maps all properties of a bean.

This subsequently causes slower performance of Spring Roo plugin applications.

___
 Imported from https://dev.vaadin.com/ issue #10171

**Comment by TatuLund** [comment]
GeneratedPropertyContainer was added in Vaadin 7.4
