### ISSUE TITLE
FieldGroup should be able to notify when field value changes

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3194]
**Originally by _rsmeds_**

___
FieldGroup should be able to notify listeners when the value of any field in the group changes.

A typical situation in which you want to listen to changes in any field is to enable "Save" and "Revert" buttons once any unsaved changes have been made. Doing this is currently very cumbersome.

FieldGroup has the .isModified() method, but that doesn't help much if you don't know when to check it.

So you have to add a valuechangelistener or such to every single field in a fieldgroup if you want to know when a field in the group has changed value. And also a TextChangeListener to textfields since they don't emit valuechangeevents until focus moves out of them. Sure, you can use a FieldFactory to add listeners to each field, but it's still unecessary boilerplate for such trivial functionality.

If we had something like addModificationListener() that could be used instead to react to changes in the fieldgroup, that would help a lot.

___
 Imported from https://dev.vaadin.com/ issue #10298

**Comment by TatuLund** [comment]
In Vaadin 8 Binder there is global value change listener which solves this problem.
