### ISSUE TITLE
Allow Fields in a FieldGroup to be defined as read only

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3234]
**Originally by _auke-_**

___
Since ticket  #9076 is resolved one is able to mark properties of a datasource as read only. But when using the BeanFieldGroup with existing beans in a BeanItem it would be much more convenient to mark certain fields as read only instead of marking the bean properties read only. This way one can just use the setItemDataSource method to update the form with a new bean and use the same bean in different forms and let the ui component decide whether a field is read only or not.

The attached patch allows a ReadOnly annotation to be added to the Field members.

___
 Imported from https://dev.vaadin.com/ issue #10387

**Comment by TatuLund** [comment]
In Vaadin 8 Binder has API to control readonly status both on form and binding level.
