### ISSUE TITLE
Implement method for moving items in a container (w/ patch)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#324]
**Originally by @Artur-**

___
A method for moving items in a container would be very useful for instance when you have a (ordered) table with "move up" & "move down" buttons that moves the current selection. 

Could easily be added to IndexedContainer (Container.Indexed):

```
public void moveItemTo(Object itemId, int newIndex) {
  int index = indexOfId(itemId);
  if (index < 0 || newIndex < 0 || newIndex >= itemIds.size()) {
     return;
  }
	    	
  itemIds.set(index, itemIds.get(newIndex));
  itemIds.set(newIndex, itemId);
}
```

then a move up / move down can be implemented by e.g.

```
Object selected = virtualFoldersTable.getValue();
virtualFoldersTableContainer.moveItemTo(selected,
virtualFoldersTableContainer.indexOfId(selected) + 1);
virtualFoldersTable.refreshCurrentPage();
```

instead of the current method of removing the itemId, readding it at the correct position and setting all properties again.

Refresh should of course be automatic.

___
 Imported from https://dev.vaadin.com/ issue #713

**Comment by KyleRogers** [comment]
Ticket can be closed as Container got removed in Vaadin 8 and replaced with DataProvider, see https://vaadin.com/download/release/8.0/8.0.0/release-notes.html#incompatible
