### ISSUE TITLE
Table Header, additional components and grouping

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3273]
**Originally by _adavie_**

___
This is hard to describe in words- so I've attached a picture for a feature that is in ZK to be able to add grouping meta-headers to a table, which may or may not include components as well.

The table feature in Vaadin is adequate, but compared to ZK, jQuery, extJS, to name a few, it is starting to be somewhat limited.

___
 Imported from https://dev.vaadin.com/ issue #10463

**Comment by TatuLund** [comment]
Multiple header row and grouping feature has been included in Grid component since Vaadin 7.6 and Vaadin 8.0
