### ISSUE TITLE
An empty vertical layout can cause the parent v-slot to use 2px space

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3307]
**Originally by @Artur-**

___
See test MovingInvisibleField. After pressing the button there is an empty VerticalLayout inside another VerticalLayout. In all other browsers the height of the slot containing the VerticalLayout is 0. In IE8 it is 2.

___
 Imported from https://dev.vaadin.com/ issue #10527

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
