### ISSUE TITLE
Tree error indicator in wrong position in IE8

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3308]
**Originally by @Artur-**

___
See test TreeKeyboardNavigationScroll. The error indicator is not pushed to the far right but stays after the first node. Can't reproduce in IE9 in IE8 mode.

___
 Imported from https://dev.vaadin.com/ issue #10528

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
