### ISSUE TITLE
Natural width of a Window containing a 100% wide content different in IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3324]
**Originally by @Artur-**

___
See test CenteredWindowWithUndefinedSize. The Window is undefined wide and contains a 100% wide component. In IE9 the whole Label is visible while in other browsers the window is as wide as the caption. 

___
 Imported from https://dev.vaadin.com/ issue #10556

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
