### ISSUE TITLE
Wrap captions and components together

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3332]
**Originally by _rsmeds_**

___
I think components and their captions should be wrapped in a common wrapper-div, regardless of layout. That way, it would be possible to theme them together properly, and with CSS specify whether the caption should be above or to the left of the component.

___
 Imported from https://dev.vaadin.com/ issue #10572

**Comment by TatuLund** [comment]
With exception of FormLayout this has been done since Vaadin 7.0
