### ISSUE TITLE
CustomLayout doesn't check if Layout is read properly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3337]
**Originally by _cri_**

___
Hello,
the CustomLayout-cosntructors don't check for exceptions when reading the template from file or input stream.
We had problems with too many open files on our linux server, which results in InputStream throwing a NullPointerException.
But because we use MVP, this was hidden (a) inside the view factory, which was in turn called by our own PresenterFactory.
Together with some non-working logging code i'm still investigating, this made debugging the problem quite hard. It would've been easier, if CustomLayout had checks in place for exceptions which come from the File/Stream reading and re-throw them, together with the layout name if possible.
This should be quite easy.

___
 Imported from https://dev.vaadin.com/ issue #10583

**Comment by TatuLund** [comment]
Related to https://github.com/vaadin/framework/issues/4295
