### ISSUE TITLE
Figure out a better solution for extra scrollbars in IE

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3364]
**Originally by @Artur-**

___
IE8-IE10 adds extra scrollbars when a container div with "overflow: auto" contains one or several inline blocks which either
a) contains no text node
or
b) has overflow: hidden

The extra scrollbars in the parent come from extra spacing being reserved by IE below the last inline block. The size of the spacing is relative to the font-size, for a 20px font-size (on the body) the spacing is 6px. Increasing the font-size to 50px increases the spacing to 13px.

The current workaround for this is to define font-size:0 for all v-scrollables which makes the extra spacing 0 and removes the unnecessary scrollbars. To compensate for this all root widget elements (v-widget) define font-size: $font-size, where $font-size is defined for the theme. 

This approach makes using em:s and relative (%) font-sizes impossible for the root element in widgets, as these would be relative to the parent element font-size, which is 0. It also makes specifying layout and widget sizes impossible using em:s (percentages work fine) as em:s in sizes are also relative to the parent font-size.

**Comment by jouni** [comment]
Closing as wontfix, as all old themes will be deprecated in version 8. You can use the documentation workarounds in this issue for your custom themes.
