### ISSUE TITLE
Extra scrollbar in sub window in IE8, IE9, IE10

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3381]
**Originally by @tepi**

___
See test screenshot UndefinedHeightSubWindowAndContent. There is a  scrollbar in IE8-10 which should not be there.

Also seems to fail only when FormLayout is used in the window. Any other layout has no scrollbar issues.

**Comment by TatuLund** [comment]
IE8 to IE10 are not supported browsers with Vaadin 8, thus we are closing this as wont fix.
