### ISSUE TITLE
OptionGroup component : adding "selected" style name to selected item(s)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3387]
**Originally by _tatann_**

___
For OptionGroup components, it would be nice to add a "selected" style name for the selected element.

```
<div class="v-select-optiongroup">
    <span class="v-radiobutton v-select-option">
        <input type="radio" name="PID3648" value="on" id="gwt-uid-8" tabindex="0" />
        <label for="gwt-uid-8">
            <div>Option 1</div>
        </label>
    </span>
    <span class="v-radiobutton v-select-option">
        <input type="radio" name="PID3648" value="on" id="gwt-uid-9" tabindex="0" checked="" />
        <label for="gwt-uid-9">
            <div>Option 2</div>
        </label>
    </span>
    <span class="v-radiobutton v-select-option">
        <input type="radio" name="PID3648" value="on" id="gwt-uid-10" tabindex="0" />
        <label for="gwt-uid-10" />
            <div>Option 3</div>
        </label>
    </span>
</div>
```

In this example, the second radio button is checked, therefore the span containing could have a "selected" class name like this :
```
<span class="v-radiobutton v-select-option selected">
```

This could apply to any component allowing selection, like checkboxes.

related forum discussion : https://vaadin.com/forum/-/message_boards/view_message/2279226

___
 Imported from https://dev.vaadin.com/ issue #10709

**Comment by sirbris** [comment]
Is something like that now possible in Vaadin 8?

**Comment by Legioth** [comment]
It should be quite easy to add this functionality to `CheckBoxGroup` and `RadioButtonGroup` in Framework 8.
