### ISSUE TITLE
Image load events from VCaption are not propagated correctly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3463]
**Originally by @johndevs**

___
Component containers might need to know when the icon in the VCaption is loaded so they can re-layout accordingly. Currently at least in Tabsheet and Accordion the VCaption owner is set to null meaning that that when the icon is loaded no event is propagated to the layout.

This can be noted from the debug console with the message:
```
Warning: Icon load event was not propagated because VCaption owner is unknown.
```

And here is the relevant code snipped from VCaption (lines 384-391):
```
 /*
  - The size of the icon might affect the size of the component so we
  - must report the size change to the parent TODO consider moving
  - the responsibility of reacting to ONLOAD from VCaption to layouts
  -/
  if (owner != null) {
      Util.notifyParentOfSizeChange(owner.getWidget(), true);
  } else {
      VConsole.log("Warning: Icon load event was not propagated because VCaption owner is unknown.");
  }

```

___
 Imported from https://dev.vaadin.com/ issue #10870

**Comment by bjung82** [comment]
![grafik](https://cloud.githubusercontent.com/assets/3159661/25652101/c8b7c934-2fe6-11e7-84af-cc69e0b60cd8.png)

This is still causing unnecessary warnings - would be nice to get rid of these. These warnings hide other "real" warnings because the clutter the console..
