### ISSUE TITLE
FieldGroup should have an option to disable validation until the first commit

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3520]
**Originally by @hesara**

___
In Vaadin 6 a Form did not (by default) validate an initial form before it was filled in by the user but only on first commit.

There should be some easy way to obtain the same behavior when using a FieldGroup.

**Comment by TatuLund** [comment]
Vaadin 8 uses Binder instead of FieldGroup and hance number of enhancements over it, including this one.
