### ISSUE TITLE
Multitple file upload

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#354]
**Originally by @mstahv**

___
Add support for multiple simultaneous file uploads (i.e. select some files, press upload -> leave for coffee).

Consider implementing this with java applet to also enable drag n drop of multiple files etc.

___
 Imported from https://dev.vaadin.com/ issue #935

**Comment by TatuLund** [comment]
In [Vaadin 8 DnD upload](https://vaadin.com/docs/v8/framework/advanced/advanced-dragndrop.html) supports multiple files uploading.

[EasyUploads add-on](https://vaadin.com/directory/component/easyuploads) from directory supports multifile upldoading

Vaadin 14 [Upload](https://vaadin.com/components/vaadin-upload) component supports multiple files uploading
