### ISSUE TITLE
Scroll event for Panel

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3566]
**Originally by _jsven007_**

___
It was a nice feature to have a scroll event in the panel if the Panel was scrolled to the bottom and you can set a offset that the event was fired before the end was reached.
This feature was to load some data lazy in a layout. I think it was a good Idear for the Panel or a new Control that extends from the Panel.

___
 Imported from https://dev.vaadin.com/ issue #11095

**Comment by hesara** [comment]
I think this is essentially the same issue as #973.
