### ISSUE TITLE
Make DefaultFieldGroupFieldFactory support ColorPicker

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3590]
**Originally by @Legioth**

___
Make it so that fieldGroup.buildAndBind("myColorPropertyId") creates a sensibly configured color picker component and that specific implementations can be selected using the more specific overload of the method.

This depends on converting the color picket components to implement Field<Color>, see #11163.

___
 Imported from https://dev.vaadin.com/ issue #11164

**Comment by elmot** [comment]
There is no DefaultFieldGroupFieldFactory in Vaadin 8+
