### ISSUE TITLE
TreeTable.getItemIds() should return ALL items in the Tree

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3611]
**Originally by _sjmcdowall_**

___
Current, if you have a TreeTable (say with a Hierarchical Container) and the underlying container has has some parent/child relationships, such that some of the "tree" would be closed, the getItemIds() only return the VISIBLE items.  This doesn't seem logical, especially as the TreeTable also implements the getVisibleItemIds().  

Seems that getItemIds() should return all of them, and the programmer can use getVisibleItemIds() if he/she only wants those.

Right now, I don't know of a way to get all the items in a Hierarchical Tree ... 

___
 Imported from https://dev.vaadin.com/ issue #11211

**Comment by djbrown** [comment]
I have the same problem. Are there any news on this?

**Comment by TatuLund** [comment]
> I have the same problem. Are there any news on this?

Vaadin 7 is no longer actively supported, so there is likely not going to be change in behavior anytime soon.
