### ISSUE TITLE
setCursorPosition() does not update scroll position of read only TextArea in webkit

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3644]
**Originally by @Legioth**

___
As reported in #8769, it seems that TextArea.setCursorPosition() does not properly update the scroll position in webkit browsers if the TextArea is set as read only.

___
 Imported from https://dev.vaadin.com/ issue #11292

**Comment by lucasmontec** [comment]
This TextArea.setCursorPosition() is not working on mozilla, nor on chrome and even on edge.
