### ISSUE TITLE
Add "getCookie" (singular) method to "VaadinRequest" class, to complement the plural "getCookies".

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3692]
**Originally by _basil.bourque_**

___
The *VaadinRequest* class:
https://vaadin.com/api/7.0.3/com/vaadin/server/VaadinRequest.html
…has a method to return a collection of Cookie objects:
https://vaadin.com/api/7.0.3/com/vaadin/server/VaadinRequest.html#getCookies()

As a convenience, this class should also have a method to return a single cookie. Pass the name of a cookie, get back a Cookie object or, if no such cookie exists, get back null or empty string. Without this method every Vaadin programmer working with cookies has to write the same code to loop over the collection as shown in the wiki page:
https://vaadin.com/wiki/-/wiki/Main/Setting+and+reading+Cookies

Furthermore, I would think the singular "getCookie" is actually the common use-case, not the plural "getCookies".

--Basil

___
 Imported from https://dev.vaadin.com/ issue #11383

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/2445
