### ISSUE TITLE
Smooth visual transition when switching between tabs on a TabSheet.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3780]
**Originally by _basil.bourque_**

___
This is a cosmetic issue, not a big deal, but add this to my ultimate Vaadin wish-list.

Currently (Vaadin 7.0.4) when the user clicks on the various tabs of a TabSheet, the entire area below the tabs displays a brief flash. 

I imagine this is because the entire area within the web browser's window's pane is being erased with the other tab's content then drawn in. So perhaps what I am seeing is the area going white then the other tab's content & widgets being drawn. The effect is annoying but does not hamper usability. The effect is similar to an eInk book reader (Nook, Kindle, Kobo) that between page turns wipes its screen to black before redrawing the next page's text.

I don't recall noticing this in my prior work with Vaadin 6, but it may have been the same.

I am especially noticing the effect today where nearly all my tabs have the same content (four Table instances in a GridLayout). That might make a good test case if you want to investigate this issue: Make a TabSheet where all the tabs contain the same content.

I don't know what a solution might be. Perhaps the pie-in-the-sky answer would be a subtle animation transition where the bit map of the previously-selected tab's content briefly dissolves into the now-selected tab's displayed content. Or perhaps a more practical solution would be somehow not clearing the old content until the new content is more fully rendered; something akin to double-buffered bitmap swapping. Or at least do some preparatory work such as configuring Table instances before clearing the old content.

--Basil Bourque

___
 Imported from https://dev.vaadin.com/ issue #11570

**Comment by aoede3** [comment]
Vaadin dynamically inlines "visibility:hidden" onto the .v-scrollable area when switching tabs. Depending on any child elements visibility you can/may still see them (and consider it as a strange flash of content) whilst the tab transitions. The following 'hack' overrides this to display:none for the v-scrollable area and makes it look smoother. 

.v-scrollable[style*="visibility: hidden;"] {
        display: none!important;
}
