### ISSUE TITLE
Date field should support disabling specific days

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#3895]
**Originally by _vmartis_**

___
Support for date range is nice solution (#6241). It resolve a half of our requirements. Our customer from bank enviroment require disabling also a speficift days. For example, you can't select non-workindaysys. Can you implement also this restriction? Now we are using a JQuery datepicker wrapped with GWT, with some other customization and it's hell.

___
 Imported from https://dev.vaadin.com/ issue #11781

**Comment by TatuLund** [comment]
In Vaadin 8, you can add custom validators with Binder to single out un-desired dates.
