### ISSUE TITLE
Flash component does not resize correctly when set to full size

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4035]
**Originally by _lorenzo.benvenuti_**

___
Calling method "setSizeFull" on a Flash component doesn't bring the expected result:

- in Chrome the component doesn't fill the parent component horizontally (and, if inserted in a VerticalLayout, the component below overlaps with Flash content, see chrome.png)

- in Firefox and IE9 component is not resized both horizontally and vertically (see firefox.png and ie9.png)

Also find attached a full project to reproduce the issue.

Thank you,

lorenzo

___
 Imported from https://dev.vaadin.com/ issue #11975

**Comment by ripla** [comment]
@Artur- still reproducible in 7.7.6. Chrome 55.0.2883.95, Firefox 50.1.0 and Safari 10.0.2. I don't see any overlapping, but the Flash component is not full size.

**Comment by ChirpChirp** [comment]
Even Demo Page in Vaadin is still broken. And lest you think Flash is dead, there are valid use cases for it. Browsers don't support all features that Flash has, for instance, Safari doesn't have WebRTC.
