### ISSUE TITLE
Consider adding presentation level validators

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4047]
**Originally by @Artur-**

___
Some times it would be beneficial to be able to validate the presentation value before it is passed to a converter. This would be possible if you could select whether your validator is a validator for the presentation or model when you add it to a field. The chain would then be presentationValidator->converter->modelValidator instead of the current converter->modelValidator where converter does the work of presentationValidator also. 

___
 Imported from https://dev.vaadin.com/ issue #11992

**Comment by tsuoanttila** [comment]
Vaadin 8 Binder allows you to do validation both before and after conversion.
