### ISSUE TITLE
FileDownloader should work on MenuItems and Table/Tree Actions

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4057]
**Originally by _OpenESignForms_**

___
Because MenuItem and Actions are commonly clicked on to do work in Vaadin, it would be nice if they were supported for the use of FileDownloader.extend().

___
 Imported from https://dev.vaadin.com/ issue #12008

**Comment by stewert72** [comment]
Any news on this? In 7.7.7 FileDownloader.exetnd(...) is still don't accepting MenuItem. Need this too.

There is also a discussion here (with workaround solution): https://vaadin.com/forum/#!/thread/1966628/1966627

**Comment by heruan** [comment]
Any update on this? A milestone possibly? In my opinion having `MenuItem` a subclass of `Button` may align things up, allowing them to be extended and having a consistent API.

**Comment by marocms-com** [comment]
I'm also interested for this. Any further plans how to handle this?

**Comment by bingele28** [comment]
As the workaround with hidden Button does not work on iOS devices, I'd be glad to use MenuItem and FileDownloader.
I'm working with 7.7.13 where this is not yet working.

Is this still open? Any estimation for rolling out this enhancement?
