### ISSUE TITLE
Support vaadinPush js with externalJQuery

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4178]
**Originally by _CodingFabian_**

___
Our application uses jquery 1.9.1, which we pull from google cdn in minified version.
Now with push a second version of jquery is loaded.
It would be great if vaadin would offer a way so that I only load it once.
Because vaadin push is loaded as very first script, I don't see a good way of preventing that.
I could add it to the bootstrap page, but still the pushJs would load its own.

___
 Imported from https://dev.vaadin.com/ issue #12198

**Comment by Artur-** [comment]
#7381 changes to use the non-JQuery version in 7.7+. This is also nowadays the only supported version in Atmosphere.
