### ISSUE TITLE
Expose a JavaScript API for using ResourceLoader

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4180]
**Originally by @Legioth**

___
`ResourceLoader` could be quite useful for JavaScript Connectors that might want to dynamically load external scripts. The class is however only accessible using GWT right now. 

Create a JavaScript API for using `ResourceLoader`.

___
 Imported from https://dev.vaadin.com/ issue #12201

**Comment by sirbris** [comment]
Any news on that topic?

**Comment by sirbris** [comment]
Is there a better way now to load javascript files, than using the JavaScript annotation?

**Comment by TatuLund** [comment]
Just pointing out, that with Flow framework, the handling of JavaScript libraries is done via tools like npm and webpack (exact tools may change in the future), which pretty much solves the problem mentioned here.
