### ISSUE TITLE
ListSelect: ClickListener

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4185]
**Originally by _asashour_**

___
Hi all,

I would be great if ListSelect has .addClickListener(), which is useful for e.g. capturing double clicks.

https://vaadin.com/forum#!/thread/3568274

___
 Imported from https://dev.vaadin.com/ issue #12206

**Comment by ssindelar** [comment]
Clicklistener seems like a basic function, wondering why it is missing. The ability to react to double clicks would really increase the usefullness of the component.
