### ISSUE TITLE
Support returning values when using RPC

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4262]
**Originally by @Legioth**

___
There are many cases where it would be useful to be able to get a result back from calling an RPC method. 

It is not desirable to directly return a value because of the asynchronous nature of the communication. Instead, the RPC method could return an instance of `RpcResult<T>` to which a callback can be added. The actual implementation of the RPC method would then produce its return value as usual, but then wrap it as a `RpcResult<T>` before actually returning. The framework would then take care of unwrapping the value, sending it over the wire, find the corresponding callback if one has been registered and invoke that callback with the originally returned value.

This design would enable asynchronous message passing without the cumbersome system with two different interfaces with magic naming conventions as used by GWT-RPC.

___
 Imported from https://dev.vaadin.com/ issue #12306

**Comment by AlexByte** [comment]
Why it's not implemented?

**Comment by TatuLund** [comment]
> Why it's not implemented?

Something like this has been implemented in Vaadin Flow framework that is used in our newer platforms. 

E.g. server -> client -> server

`component.getElement().executeJs(...).then(value -> { ... });`
