### ISSUE TITLE
VaadinSession should prevent usage after the underlying session is invalidated

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4278]
**Originally by @jdahlstrom**

___
Currently, a background thread can continue accessing `VaadinSession` practically indefinitely even after the underlying session is invalidated. However, any direct access to the wrapped session will throw `IllegalStateException`. Certain `VaadinSession` operations, `lock()` most importantly, should probably check whether the wrapped session is still valid and throw if not.

Note that `UI.access()` already throws `UIDetachedException` if the session is closed.

___
 Imported from https://dev.vaadin.com/ issue #12327

**Comment by TatuLund** [comment]
In Vaadin 8 this is not needed anymore. In VaadinService getWrappedSession will throw SessionExpiredException which is catched in handleRequest(). This should effectively guard this.
