### ISSUE TITLE
Consider making all Vaadin threadlocals non-inheritable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4337]
**Originally by @Artur-**

___
The inheritable threadlocals of Vaadin become memory leaks if you spawn long running threads from a Vaadin request thread as the long running thread will retain references to the UI and VaadinSession instance (see https://github.com/vaadin/framework/issues/4321).  The inheritable threadlocals for these made sense previously for the use case where you spawn a short living thread related to one UI however when the access method was introduced it took over the job of ensuring that UI.getCurrent() and VaadinSession.getCurrent() return the correct instance.

Is there really any need for having inheritable threadlocals anymore?

___
 Imported from https://dev.vaadin.com/ issue #12417

**Comment by TatuLund** [comment]
Fixed by https://github.com/vaadin/framework/pull/96 in Vaadin 8+
