### ISSUE TITLE
TabSheet placement and orientation

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4357]
**Originally by _mwisnicki_**

___
Allow changing tabsheet placement (top, left, right, bottom) and orientation of captions. Vertically oriented left tabs should have captions rotated -90deg CW while right tabs would be rotated by 90deg.
Horizontal top and bottom same as vertical left.

Some subset of it was probably requested in #5606 but its author was not very specific.

___
 Imported from https://dev.vaadin.com/ issue #12451

**Comment by Szdnez** [comment]
This feature is still missing. Are there any activities on it?
