### ISSUE TITLE
Custom ValidatorFactory to BeanValidator

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4362]
**Originally by _joni.ollila_**

___
Would it be possible to change BeanValidator implementation so that one could use custom ValidatorFactory instead of the default one. I need to get BeanValidation to use different message bundle than the default one. Currently I have solved it by taking copy of whole BeanValidator source and changing implementation of getJavaxBeanValidatorFactory method to use custom ValidatorFactory.

___
 Imported from https://dev.vaadin.com/ issue #12459

**Comment by TatuLund** [comment]
I think this is a bit outside Vaadin scope, as JSR-303 provides some standard approaches for localization, see for example https://dzone.com/articles/jsr-303-loading-messages-i18n
