### ISSUE TITLE
com.vaadin.ui.Audio always preloads media, hanging ui

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4409]
**Originally by _rsutton@asteriskit.com.au_**

___
need to be able to set the preload="none" option for the Audio component.

the ui becomes unresponsive while the Audio control downloads the entire media preemptively.

___
 Imported from https://dev.vaadin.com/ issue #12516

**Comment by hesara** [comment]
Fixed in 7.7 branch, picked to master in #9797.

**Comment by hesara** [comment]
V8 fix will be in 8.1.2
