### ISSUE TITLE
CheckBox/OptionGroup should update the HTML checked attribute when the value is changed

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4596]
**Originally by @jouni**

___
The checked attribute is set once when the CheckBox is initially rendered, but not updated when the value of the checkbox is changed by the user.

Since IE8 doesn't support the :checked pseudo-class selector, this would allow theme developers to theme checkboxes as well.

OptionGroup should also work similarly, for both single and multiple selection modes (radiobuttons and checkboxes).

___
 Imported from https://dev.vaadin.com/ issue #12827

**Comment by jouni** [comment]
Wontfix. IE8 support will be dropped in version 8, so this issue is less relevant.
