### ISSUE TITLE
Add support for multiple element queries in Vaadin Locator API

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4721]
**Originally by @thinwire**

___
TestBench 4 semantics require being able to select more than one element using the new Vaadin Locator syntax. Queries such as //VButton should return ALL matching buttons, not just the first one.

___
 Imported from https://dev.vaadin.com/ issue #13016

**Comment by tsuoanttila** [comment]
Should be fixed in TB4, `ElementQuery::all` gets the list of all components matching your search
