### ISSUE TITLE
Vaadin Locators should support server-side classnames

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4724]
**Originally by @thinwire**

___
Constructing query strings based on client widget name alone is counter-intuitive and error-prone; instead of having to specify _VScrollTable`, a simple `_Table` should suffice. Users don't care about the client-side specifics.

___
 Imported from https://dev.vaadin.com/ issue #13019

**Comment by tsuoanttila** [comment]
Fixed Framework 7.2
