### ISSUE TITLE
Table scroll position is lost in page refresh when using portlet in IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4786]
**Originally by _Tapio Aali_**

___
When using IE9, if I scroll a table inside a portlet and then refresh the page, the scroll position is lost. This seems to happen at least with Liferay 6.1.2 CA GA3 but not with standalone applications.

Example application:
```
Window window = new Window();
setMainWindow(window);

Table table = new Table("My table2");
table.setSizeFull();
table.setImmediate(true);
table.addContainerProperty("Property", String.class, null);
for (int i = 0; i < 20; i++) {
    table.addItem(new Object[] { "Value " + i }, i);
}
window.addComponent(table);
```
Open a page containing the portlet in IE9, scroll the table down and then refresh the page. The scroll position is lost. This seems to be a regression that has appeared between 6.7.9 and 6.8.0 RC1.

___
 Imported from https://dev.vaadin.com/ issue #13160

**Comment by TatuLund** [comment]
Vaadin 6 is no longer a supported product and thus we close this as won't fix.
