### ISSUE TITLE
Select loses focus after typing a letter in IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4822]
**Originally by _micael.kirouac@telus.com_**

___
When typing a letter in a Select component just after the page loaded, the textfield inside the select loses the focus. This only happens the first time. After giving the focus back to the text field (by clicking with the mouse), the focus stays on the text field.

It looks like showing the overlay for the first time causes the textfield to lose the focus.

Below is the code used to reproduce the problem.

```
import com.vaadin.ui.Select;
import com.vaadin.ui.VerticalLayout;

public class TestLayout extends VerticalLayout
{

	@Override
	public void attach()
	{
		super.attach();
		
		Select select = new Select();
		select.addItem("a");
		select.addItem("aa");
		select.addItem("aaa");
		select.addItem("ab");
		select.addItem("abb");
		select.addItem("aaaa");
		
		
		addComponent(select);
		
	}
}
```

___
 Imported from https://dev.vaadin.com/ issue #13229

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
