### ISSUE TITLE
Scrolling a table with setCurrentPageFirstItemId fails randomly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4823]
**Originally by _aiolos_**

___
I'm having problems scrolling to the currently selected line in my table. When I add a new line to the bottom of the table I use table.size() as the itemId. When I want to scroll I do :

```
table.setValue(i);
if ((i < table.getCurrentPageFirstItemIndex())
|| (i > table.getCurrentPageFirstItemIndex() + table.getPageLength())) {
table.setCurrentPageFirstItemId(i);
} 
```

This works most of the times for a table with many lines and a vertical scrollbar, but sometimes the row is properly selected but the table doesn't scroll. In those cases getCurrentPageFirstItemIndex gives me i which is the correct value. So the table thinks it has scrolled but it hasn't. I also tried

```
table.setCurrentPageFirstItemId(table.getValue());
```

```
table.setCurrentPageFirstItemIndex(i);
```

both of which should work because the item id is the same as the index, but both of them do the same thing. They work most of the times but sometimes the table doesn't scroll despite table.getCurrentPageFirstItemIndex() giving the correct value.

I also tried refreshRowCache and markAsDirty but none of them helped.

This does not happen for specific values of i. The same i might work one time and not work another. This depends (I believe) on the line that was previously selected.

___
 Imported from https://dev.vaadin.com/ issue #13230

**Comment by tepi** [comment]
I'd say this needs more info. I tested this with the UI pasted below, using Vaadin 7.7.16. 

I ran quite a large number of tests with different amounts of selecting and scrolling forwards and backwards, and also tried selecting and scrolling to a random row. The scrolling worked fine every single time.

It would help a lot if someone could provide even approximate values for what to select and scroll to, and which row was selected before the action.

```
public class MyUI extends UI {

	private int selected;

	@Override
	protected void init(VaadinRequest vaadinRequest) {
		final VerticalLayout layout = new VerticalLayout();
		layout.setSizeFull();
		setContent(layout);

		Table t = new Table();
		t.setSizeFull();
		layout.addComponent(t);
		layout.setExpandRatio(t, 1);
		t.setSelectable(true);

		IndexedContainer ic = new IndexedContainer();
		ic.addContainerProperty("name", String.class, null);
		for (int i = 0; i < 10000; i++) {
			ic.addItem(i);
			ic.getContainerProperty(i, "name").setValue("Item #" + i);
		}
		t.setContainerDataSource(ic);

		selected = 9000;
		layout.addComponent(new Button("Select and scroll", e -> {
			t.select(selected);
			if ((selected < t.getCurrentPageFirstItemIndex())
					|| (selected > t.getCurrentPageFirstItemIndex() + t.getPageLength())) {
				t.setCurrentPageFirstItemId(selected);
			}
			selected -= 100;
		}));
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}
```

**Comment by TatuLund** [comment]
It is possible that behind the symptoms there is a real issue. But since we are not able to create a method to reliably reproduce the problem and hence systematically debug it, we are closing this issue as won't fix.
