### ISSUE TITLE
Overlay divs don't inherit style names from UI and components

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4837]
**Originally by _lorenzo.benvenuti_**

___
When using a component generating an overlay (ComboBox, PopUpView) the div generated for the overlay does not inherit:

- styles of the UI
- styles of the component that generates the overlay

Consider for instance the code:

@Theme("overlaystyles")
public class OverlaystylesUI extends UI {

    @Override
    protected void init(VaadinRequest request) {	    
    
        setStyleName("custom-ui-style");	    

        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

        ComboBox comboBox = new ComboBox();
        comboBox.addStyleName("custom-combobox-style");
        comboBox.addItem("First");
        comboBox.addItem("Second");
        comboBox.addItem("Third");
        layout.addComponent(comboBox);
		
    }

}

When opening the dropdown a new div is generated:

```html
<div id="OverlayStyles-729840946-overlays" class="v-app overlaystyles v-overlay-container" ...>
    <div class="v-shadow"... >...</div>
    <div class="v-filterselect-suggestpopup v-filterselect-suggestpopup-custom-combobox-style" ... >...</div>
</div>
```

I expected it to be:

```html
<div id="OverlayStyles-729840946-overlays" class="v-app overlaystyles v-overlay-container custom-ui-style custom-combobox-style" ...>
    <div class="v-shadow"... >...</div>
    <div class="v-filterselect-suggestpopup v-filterselect-suggestpopup-custom-combobox-style" ... >...</div>
</div>
```

In this way I could:

- customize the v-shadow style for different components

- style the overlay in different ways depending on the UI style

Same thing happens using a PopUpView, I guess it applies to all components generating an overlay.

This issue is probably related to ticket #2067.

Thank you

___
 Imported from https://dev.vaadin.com/ issue #13251

**Comment by jouni** [comment]
I think this is a duplicate of #2067 (as mentioned in the initial description, if we agree that it is not necessary to add all component specific style names to the overlay container (which seems really unnecessary). The shadow element is already deprecated, and should not be used in any themes any more.

Please reopen if I missed some part of the issue.
