### ISSUE TITLE
Table: size() function called more times than needed

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#484]
**Originally by @Peppe**

___
The table contains functions that constantly needs the size of the container to perform its duties. You get this size by calling size(). However, size() is called multiple times inside tablefunctions instead of just storing the function and this causes unnecessary function calls. For example refreshRenderedCells() has six occurrences of size() A better solution would be to call size() the first time it is needed inside the function and store it to a temporal variable.

refreshRederedCells() changes would therfore be
Line ~1163: int size = size(); and thereafter every occurence of size() -> size

___
 Imported from https://dev.vaadin.com/ issue #1771

**Comment by KyleRogers** [comment]
As Vaadin Table reaches EOL soon, this can be closed.

See https://vaadin.com/download/release/8.0/8.0.0/release-notes.html#incompatible

**Comment by pleku** [comment]
If someone still thinks this issue should be fixed for the 7.7 Table, please comment here.

Closing since `Table` has been deprecated since 8.0.
