### ISSUE TITLE
Slider is nearly uselss

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4930]
**Originally by _mwisnicki_**

___
Slider has multiple UI bugs making it rather annoying to use:

1. Dragging handle (ball) second time does not work - component loses focus every other click.
2. Clicking on slider track does not move handle towards mouse unlike in any other UI library.
3. Active area (part which responds to mouse events) of component is uncomfortably small. I miss the component around half the time.

___
 Imported from https://dev.vaadin.com/ issue #13388

**Comment by SomMeri** [comment]
This bug can be closed, as of 7.7.10 slider does not have issues mentioned here.

**Comment by TatuLund** [comment]
> This bug can be closed, as of 7.7.10 slider does not have issues mentioned here.

Closed
