### ISSUE TITLE
setValue(Object newValue, boolean repaintIsNotNeeded) in AbstractSelect doesn't care about the NullSelectionItemId.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4954]
**Originally by _fahrenheit_**

___
I'm using an OptionGroup, and when selecting the null item (represented by nullSelectionItemId), the null value is not affected to the OptionGroup. Instead, it keeps the value of the nullSelectionItemId.

I think that the problem is coming from the setValue(Object newValue, boolean repaintIsNotNeeded) method in AbstractSelect.

When looking at this method, there is no test on the nullSelectionItem.

```
else if (newValue == null || items.containsId(newValue)) {
   super.setValue(newValue, repaintIsNotNeeded);
}
```

Shouldn't it be something like this ? 

```
else if (newValue == null || items.containsId(newValue)) {
   if (newValue == getNullSelectionItemId()) {
      newValue = null;
   }
   super.setValue(newValue, repaintIsNotNeeded);
}
```

Thanks for you for your consideration.

___
 Imported from https://dev.vaadin.com/ issue #13417

**Comment by pichlerm** [comment]
The bug also affected us: when setting a null-label with OptionGroup.setNullSelectionItemId the ValueChangeListener of the OptionGroup was not triggered.

Until the bug is fixed, we are changing the nullLabel to null in setValue as a workaround.

```
    final String nullLabel = "n/a";
    OptionGroup optionGroup = new OptionGroup(label) {
      private static final long serialVersionUID = -330667189892805579L;
      @Override
      protected void setValue(Object newFieldValue, boolean repaintIsNotNeeded, boolean ignoreReadOnly)
          throws com.vaadin.data.Property.ReadOnlyException, ConversionException, InvalidValueException {
        if (nullLabel.equals(newFieldValue)) {
          newFieldValue = null;
        }
        super.setValue(newFieldValue, repaintIsNotNeeded, ignoreReadOnly);
      }
    };
...
      optionGroup.setNullSelectionAllowed(true);
      optionGroup.setNullSelectionItemId(nullLabel);
```

**Comment by pichlerm** [comment]
The RadioButtonGroup of Vaadin 8 works fine: null selection works normally, the workaround is no longer needed.
