### ISSUE TITLE
Vaadin component traverse utility

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4957]
**Originally by _santeriv-profit_**

___
Currently in Vaadin 7 there are 

- .getAncestor
- .getParent

what is missing from core is traverser like call

- .getChildren

-> here is quite generic recursive example of 'getchildren' which can be used if wanted:

https://gist.github.com/santeriv/8330212 

- other links: https://vaadin.com/old-forum/-/message_boards/view_message/217290

What do you think?

___
 Imported from https://dev.vaadin.com/ issue #13420

**Comment by santeriv** [comment]
(note to self)
