### ISSUE TITLE
ComboBox paging does not work correctly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4989]
**Originally by _Sebastian.Dietrich_**

___
I've noticed that ComboBox paging seems to work weirdly. If I e.g. step through the example combobox in http://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box with the arrow-keys it shows the first again when having reached the page bottom, and then the next.
i.e. it starts with "Afghanistan", goes down correctly to "Argentina", then shows again "Afghanistan" with no line having the focus, and then starts at the top of the second page with "Armenia".

___
 Imported from https://dev.vaadin.com/ issue #13464

**Comment by SebastianDietrich** [comment]
Seems as if the bug was fixed in the meantime

**Comment by Artur-** [comment]
Thanks for checking, closing this then
