### ISSUE TITLE
API for Table alwaysRecalculateColumnWidths

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5015]
**Originally by _santeriv-profit_**

___
Every time I have eg.

- CustomField eg. with at least 2 components
* ComboBox + TextField(s) in editable Table (TableFieldFactory) and on ComboBox.ValueChange I need to adjust automatically the column size as I've made textFields visible. If I do not inherit my own table and set this property to true. New visible field is not visible as column width is not updated. 

Spawned from http://dev.vaadin.com/ticket/7922#comment:10

- Related (review) issue : http://dev.vaadin.com/ticket/2066#comment:2

___
 Imported from https://dev.vaadin.com/ issue #13505

**Comment by santeriv** [comment]
(note to self)
