### ISSUE TITLE
Support for cookies

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#503]
**Originally by @jojule**

___
Currently writing and reading cookies in applications requires too much low-level coding. Direct support with proper API (on WebApplicationContext ?) should be created.

___
 Imported from https://dev.vaadin.com/ issue #1849

**Comment by KyleRogers** [comment]
Reading and writing Cookies is possible using VaadinRequest and VaadinResponse obtained from VaadinService, e.g.

```VaadinService.getCurrentRequest().getCookies();```

See https://vaadin.com/wiki/-/wiki/Main/Setting+and+reading+Cookies

Issue can be closed, I think.
