### ISSUE TITLE
Combobox popup detach from the textfield when the view is scrolled

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5043]
**Originally by _simardj_**

___
Steps to reproduce:

1. Go to http://demo.vaadin.com/book-examples-vaadin7/book#component.select.combobox.basic
2. Resize your browser so a scrollbar appears in the "Basic Use" view.
3. Click on the dropdown to make the popup visible.
4. Move your mouse pointer away from the popup (anywhere else on the view is good).
5. Use the mousewheel to scroll the view down.

Note that the entire page scroll, but the popup stay at a fixed location, floating on the page, away from its parent combobox component.

___
 Imported from https://dev.vaadin.com/ issue #13555

**Comment by samie** [comment]
Still happening in Vaadin 7.7.6
