### ISSUE TITLE
Table rows are selected with from a mouseup / pointerup event

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5058]
**Originally by @jouni**

___
If you start a drag from outside the table, and end the drag on a table row, the row will get selected. This should not happen. Only if the mouseup event happens after a mousedown event on the same row has happened, should the row be selected.

___
 Imported from https://dev.vaadin.com/ issue #13572

**Comment by jouni** [comment]
Probably a wontfix, as Table will be deprecated in version 8.
