### ISSUE TITLE
Firefox collapses layout spacing when the page is unloaded

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5118]
**Originally by @jouni**

___
When Firefox unloads a Vaadin app page, all v-spacing elements are collapsed to 0x0 size, causing an ugly jumping layout.

Test by reloading any application with layouts that have spacing enabled, for instance http://matti.app.fi/dawn/

A proposed solution is to add some DOM content to the v-spacing elements. An empty comment block is probably enough (heard from an outside developer who had tested it).

___
 Imported from https://dev.vaadin.com/ issue #13663

**Comment by jouni** [comment]
Can’t reproduce any more.
