### ISSUE TITLE
VVideo overrides width/height based on video metadata

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5136]
**Originally by @anezthes**

___
Example code:

		Video video = new Video();
		video.addStyleName("video-layout");
		
		ExternalResource resource = new ExternalResource("https://s3.amazonaws.com/videos.vaadin.com/vaadin_fin_web002.mp4");
		
		video.setSource(resource);
		video.setWidth("480px");
		video.setHeight("320px");
		video.setHtmlContentAllowed(true);
		
		return video;

Simply add that to a layout and you'll see the size NOT being 480x320.

___
 Imported from https://dev.vaadin.com/ issue #13683

**Comment by TatuLund** [comment]
For Vaadin 8 users this issue is addressed in v1.2.1+ of AudioVideo add-on https://vaadin.com/directory/component/audiovideo
