### ISSUE TITLE
Implement RadioButton

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#515]
**Originally by @magi42**

___
There is a need for single radio button components, not just radio button groups with OptionGroup. They are necessary if the layout of the radio button group needs to be more complex and the user wants to place the individual radio buttons hirself. For example, you might want to have radio buttons in a Table column.

___
 Imported from https://dev.vaadin.com/ issue #1948

**Comment by TatuLund** [comment]
This component has been implemented in Vaadin 10+, see more at [Vaadin Radio Button](https://vaadin.com/components/vaadin-radio-button)
