### ISSUE TITLE
Upload remains in the background after cancel (interrupt)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5165]
**Originally by _vinaddala_**

___
I was looking into a bug where upload remains in the background after it got canceled (interrupted) by the user. I was able to see busy network activities until I refreshed the page or closed the tab. The root cause was that the synthesized target frame never got removed and kept doing the upload. My workaround was to remove that DOM node manually and issue was gone.

It's somewhat related to #6881 where the other half of the issue was fixed, meaning new request was able to start, but old one didn't get removed.

I think this is something should be addressed in the Vaadin API level so I file this ticket. 

___
 Imported from https://dev.vaadin.com/ issue #13728

**Comment by Ansku** [comment]
Fixed in Vaadin 8.3.0.beta2

**Comment by lmenko** [comment]
This is issue is still present in Vaadin 8.4.2. and should be reopened, can be reproduced with Chrome 68, FireFox 61 but Not in Safari.
