### ISSUE TITLE
Regression? #11275 still broken in 7.1.15

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5171]
**Originally by _CodingFabian_**

___
I see the problem from #11275 happening still in 7.1.15. I checked the code, the text/cache is there, but it doesnt seem to work

___
 Imported from https://dev.vaadin.com/ issue #13738

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/3631

Fixed by https://github.com/vaadin/framework/pull/8291
