### ISSUE TITLE
Add missing HTML5-Attributes for Video Component

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5178]
**Originally by _buuzta_**

___
In the Video Component Class (or AbstractMedia.class) are missing attributes for the HTML5 video-tag.

- preload (auto, metadata or none) [Specifies if and how the author thinks the video should be loaded when the page loads]
* loop (true or false) [Specifies that the video will start over again, every time it is finished]

IMHO the preload attribute might be very important for many of the developers.

___
 Imported from https://dev.vaadin.com/ issue #13745

**Comment by hesara** [comment]
Fixed in 7.7 branch, picked to master in #9797.

**Comment by hesara** [comment]
V8 fix will be in 8.1.2
