### ISSUE TITLE
VToolTip causes scroll to top

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5195]
**Originally by _maxime.lemieux@telus.com_**

___
Tooltips that does not fit in the window cause panel to scroll to top. 

Steps : [[BR]]

1- Scroll down[[BR]]

2- Mouse over a label to show tooltip[[BR]]

3- Panel will automaticly scroll to top[[BR]]

```
#!div style="font-size: 80%"
Code highlighting:
  {{{#!java
      VerticalLayout layout = new VerticalLayout();

      for(int i = 0; i < 30; i++)
      {
          Label l = new Label("testlabel");
          l.setDescription("asdddddddddddddddddddasddddddddddddddd asd");
          l.setWidth("50px");
          layout.addComponent(l);
          layout.setComponentAlignment(l, Alignment.MIDDLE_RIGHT);
      }
      
      Panel panel = new Panel();
      panel.setHeight("300px");
      panel.setScrollable(true);
      panel.setContent(layout);
      
      return panel;
  ```
}}}

___
 Imported from https://dev.vaadin.com/ issue #13797

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
