### ISSUE TITLE
ComboBox maxLength input

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5196]
**Originally by _dogrush009@gmail.com_**

___
when combobox.setNewItemsAllowed(true), there is not any method to set a maxlength to the input (like TextField.setMaxLength(int)).

Suggested Method:
combobox.setMaxLength(int maxLength);

___
 Imported from https://dev.vaadin.com/ issue #13800

**Comment by TatuLund** [comment]
The feature has been added to https://vaadin.com/directory/component/prefixcombobox
