### ISSUE TITLE
GridLayout with span adds extra spacing.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5230]
**Originally by _Dmitrii Rogozin_**

___
In grid layout when component takes several rows, and all other documents in one of the rows are set invisible grid layout adds extra spacing.
In test case provided after pressing the button TextArea should have the same size. Hiding other components in the same row should not affect the size of the span.

After fix https://dev.vaadin.com/review/#/c/3618/ the problem is more "visible" because of the size of change, but before this change the problem was there, just the spacing was less.

___
 Imported from https://dev.vaadin.com/ issue #13853

**Comment by cornzy** [comment]
maybe this issue is related to #5230 but it has nothing to do with column span.
