### ISSUE TITLE
memory usage higher with vaadin 7.2 websockets

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5293]
**Originally by _vinaddala_**

___
with vaadin 7.2 after enabling websocket we see a slightly high memory usage in the browsers we tested Chrome (win) Safari Mac. 

Chrome: 280MB 7.2 w/websocket
Chrome: 186MB 7.1.12 w/websocket

Is there any info we can provide to track this usage down? Is vaadin 7.2 expected to use more memory.

___
 Imported from https://dev.vaadin.com/ issue #14001

**Comment by TatuLund** [comment]
There was a known memory leak that could have been causing something like this, which is now fixed in Vaadin 8.11.1 by https://github.com/vaadin/framework/pull/12042
