### ISSUE TITLE
Vaadin API to set SCSS variables

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5295]
**Originally by @marlonrichert**

___
It is very common for our customers to have one deployment of a webapp that they serve to their various customers in the cloud. Very often, they would like to be able to slightly customize the appearance of the app for each of their customers. For example, show their customer's logo and have the look & feel be more in tune with their customer's corporate colors.

Changing the logo is already possible through the Vaadin API by means of setIcon(…). However, changing colors or other aspects of the L&F by setting a SCSS variable in the theme is not yet possible. This is a feature that is often requested by our customers. Please implement. :)

___
 Imported from https://dev.vaadin.com/ issue #14004

**Comment by TatuLund** [comment]
This need has been taken into account in Vaadin 10+ using CSS custom properties.
