### ISSUE TITLE
VScrollTable row rendering is broken on scrolling.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5299]
**Originally by _afeher_**

___
Table and TreeTable are both affected. (from version 7.1.7 to HEAD of master) \\
Browser independently reproducible.

-*Reproduce with Table:** \\
Create and layout a Table with the following conditions:
- The table must have a container property with other type than plain String (like Label).
- More items have to be added to the table than it can display in its viewport (let's say 100).
Create and layout a Button to trigger scrolling through table.setCurrentPageFirstItemId(id); 
- where 'id' should be somewhere in the middle of the table (like the 60th item).

-*Test:** \\
Initially everything should be OK. \\
The viewport's first row is set to 0. and 15 rows are displayed by default.

After pressing the button: \\
Bottom part of the viewport is not rendered at all. \\
On scrolling to the top random amount of empty rows can be found. \\
(Scrolling manually back and forth through the items may result in well rendered rows again.)

There are more forum threads and tickets mentioning this issue.

- https://vaadin.com/forum/#!/thread/19524/17553
- https://vaadin.com/forum/#!/thread/1817196/1817195
- https://vaadin.com/forum/#!/thread/186858/197095
...
- http://dev.vaadin.com/ticket/6160
- http://dev.vaadin.com/ticket/13436
...

Thanks to the author of the ticket #13436 \\
A small (slightly modified) test UI to reproduce the behavior is attached.

After a Git bisecting session it turns out that the following commit causes the regression:

Commit:  0e9ff32598ed86d5f24a8bce5c5c898d81dc2c84 \\
Date:    Wed Oct 2 16:33:41 2013 +0300 \\
Comment: Ported regression fixes in 6.8 for #12407 to 7.1 branch \\
         Change-Id: Ie46ab97fc1ff89dd241eec9182ed0f92164b754d \\

By the commit above the 
```
firstRowInViewPort = firstvisible;
```
 value assignment is removed from 
```
updateFirstVisibleAndScrollIfNeeded(UIDL uidl)
```
 method.
Adding back the assignment (on HEAD of branch 7.2) solves the problem, however would be great to verify that the fix does not cause any further regressions and have this issue fixed in a Vaadin release.

___
 Imported from https://dev.vaadin.com/ issue #14008

**Comment by TatuLund** [comment]
According to https://github.com/vaadin/framework/issues/4969 this is fixed since Vaadin 7.5.10
