### ISSUE TITLE
Tree leaf nodes should not be expandable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5316]
**Originally by @jouni**

___
Clicking a Tree item where the expansion indicator would be located gives the item the v-tree-node-expanded style regardless of the 'isChildrenAllowed" setting.

Leaf nodes should never get the style. Also the aria-expanded attribute changes. I'd recommend fixing this as well, as the style could cause unexpected behaviour.

___
 Imported from https://dev.vaadin.com/ issue #14029

**Comment by jouni** [comment]
Can’t reproduce in Sampler anymore.
