### ISSUE TITLE
Run all current screenshot tests using Valo instead of Reindeer/Runo

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5319]
**Originally by @jouni**

___
This should give us a view into any possible issues Valo might have.

___
 Imported from https://dev.vaadin.com/ issue #14032

**Comment by jouni** [comment]
Also, as of Vaadin 8, all old themes are deprecated, and we should start doing screenshot tests with Valo instead (if not doing so already) and consider updating all existing tests from Reindeer/Runo to Valo.

@Legioth, do you have any thoughts about this?

**Comment by Legioth** [comment]
I'm not sure it's worth the effort to go through old screenshots and update them. Would surely be nice, but also lots of manual work.

All new tests should of course use Valo.

**Comment by jouni** [comment]
Yep, I wasn’t really expecting us to update them. As most of them will be irrelevant in the future any way, the ROI isn’t that great.
