### ISSUE TITLE
FieldGroup binder with collections

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5332]
**Originally by _frezelth_**

___
I would really like to see implemented in Vaadin binding with collections.

For instance I would have 2 classes:

```
public class One {

    private String property;
    private List<Many> collection;
    // getters setters
}

public class Many {
    private String name;
    private String address;
    // getters setters
}
```

With Spring MVC I would be able to bind things like this:
```
<form:input path="collection[${status.index}].name" />
```
I would like to have something like this in Vaadin:
```
fieldGroup.bind(textField, "collection["+index+"].name");
```

See: https://vaadin.com/forum#!/thread/7688714

Thomas

___
 Imported from https://dev.vaadin.com/ issue #14057

**Comment by zygimantus** [comment]
Using Vaadin 8 this is deprecated. Are there any alternatives of this use case in Vaadin 8?
