### ISSUE TITLE
Individual ComboBox items should be stylable with CSS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5343]
**Originally by @jouni**

___
The items in the ComboBox drop down menu should be allowed to have individual custom style names, similarly as Table items and Tree items.

___
 Imported from https://dev.vaadin.com/ issue #14076

**Comment by macjuan** [comment]
We have implemented this functionality with <vaadin-combo-box> web component and are planning to release a way to use that and any other web component natively from Vaadin Framework 8.x in a more developer friendly way than the HTML Imports feature that was part of Framework 8.0 release.

**Comment by martin-garnier** [comment]
Hi, I would really much enjoy that functionality in Vaadin 8, any news on that?

Thanks!

**Comment by knoobie** [comment]
Isn't that already possible with ComboBox#getStyleGenerator since 8.0?

**Comment by elmot** [comment]
Thanks, @knoobie, you are absolutely right. Please use `com.vaadin.ui.ComboBox#setStyleGenerator` for this in Vaadin 8.
