### ISSUE TITLE
Missing component visible listener for ComponentContainer

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5355]
**Originally by _PAX_**

___
I have several instances of ComponentContainer that I display in TabSheet. Some of them execute time-consuming computations in order to create their content to be displayed. I need a lazy loading mechanism in form of a "component visible listener" for these panels.

I known, I also could use a selection changed listener in TabSheet but this is sophisticated in my environment.

___
 Imported from https://dev.vaadin.com/ issue #14100

**Comment by TatuLund** [comment]
This is far from trivial case. However there is extension in Directory that gives a component an ability to sense whether it is in the view port and event to observe if the status of view port presence has changed https://vaadin.com/directory/component/viewportextension-add-on
