### ISSUE TITLE
FontAwesome not working in IE9 when the font is served using HTTPS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5361]
**Originally by _blackbeltdev_**

___

No icon appears when viewing the following in IE9. It works in IE10, Firefox, and Chrome.

            final Button actionButton = new Button();
            actionButton.addClickListener(clickListener);
            //actionButton.addStyleName(Textura.BUTTON_LINK);
            actionButton.setHtmlContentAllowed(true);
            actionButton.setCaption(String.format("<span class='textura-green'>%s</span> %s", FontAwesome.PLUS.getHtml(), caption));
            title.addComponent(actionButton);
            title.setComponentAlignment(actionButton, Alignment.MIDDLE_RIGHT);

___
 Imported from https://dev.vaadin.com/ issue #14109

**Comment by lrozenblyum** [comment]
It's reproduced in IE11 as well.

**Comment by lrozenblyum** [comment]
Since it affects IE11 which is still supported, can it receive some priority? It causes bugs in rendering even on simple UI elements like a checkbox which has tick drawn via webfont.

**Comment by TatuLund** [comment]
See workaround at https://github.com/vaadin/framework/issues/10792
