### ISSUE TITLE
Moving a window in IE8 broken after resizing it

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5393]
**Originally by _comag_**

___
1. Go to Vaadin Sampler / Window Demo with IE8
2. Move the window around - all ok
3. Resize the window with the mouse
4. Try to move around the window again - it did not work or the positioning gets messed up

___
 Imported from https://dev.vaadin.com/ issue #14160

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
