### ISSUE TITLE
Vaadin Calendar Component Scroll Problem in Internet Explorer

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5412]
**Originally by _hsncr_**

___
When I click and hold to select range on calendar, scrolling corrupts and my first click on hours changes because calendar scrolls to top.

For example, I want to select range between 09:00 PM and 11:00 PM, and when I start to click on 09:00 PM, calendar scrolls to top and selects 07:00 AM as start time in internet explorer. 

In other browsers(Chrome and Firefox), calendar scrolls to top after my range selection is done.

___
 Imported from https://dev.vaadin.com/ issue #14194

**Comment by TatuLund** [comment]
> Patch has solved problem, but still some flickering on week and dayly view exists in IE 8,9, 10 exists.

I am closing this ticket as Internet Explorer versions older than 11 are no longer supported.
