### ISSUE TITLE
Add ability to better customize VaadinService-level error handling

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5424]
**Originally by @jdahlstrom**

___
Currently `VaadinService.handleExceptionDuringRequest` sends a critical notification (in the case of UIDL requests) or rethrows the exception (other requests) in addition to invoking the session error handler. It should be possible to customize this behavior eg. by swallowing the exception and sending a custom error page.

___
 Imported from https://dev.vaadin.com/ issue #14212

**Comment by atamakosi** [comment]
Any updates on this?
