### ISSUE TITLE
Send connector hierarchy only if actually changed

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5436]
**Originally by @jdahlstrom**

___
Currently the full list of ComponentContainer child ids is collected and sent every time the container is marked as dirty, including simple state changes that have nothing to do with the hierarchy. To optimize this, there could be a more fine-grained API for only marking the state OR the hierarchy as dirty.

___
 Imported from https://dev.vaadin.com/ issue #14226

**Comment by TatuLund** [comment]
related to https://github.com/vaadin/framework/issues/4195

**Comment by TatuLund** [comment]
Step of optimization has been done after this issue report here https://github.com/vaadin/framework/commit/39c7d9f68a3723feeebf3b05646aaef2fe3ce070
