### ISSUE TITLE
Warning dialog when leaving page w/ unsaved data

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#545]
**Originally by @emarc**

___
Basic use case: user modifies some data, but does not press 'save', then exits the app (navigates to new url or closes window); a warning dialog should be shown, giving the user the option to stay on the page to finish the task.

First discussed here: http://forum.itmill.com/posts/list/462.page

Some points:

The unsaved data can be either 
 1. on the server (e.g. incomplete multi-page form, or save/confirm button not pressed), or 
 2. on the client (user filled in some fields, but has not pressed any button).

We do not always want to show the warning - depending on the application, it's often safe to discard the data. 

Also, in both cases the _client_ needs to know that it's supposed to show the warning dialog (we can't really ask the server, then show the dialog if needed).

So it seems like we need to be able to tell the client (on-the-fly) whether it's supposed to show the warning _always_ or _only if there are pending variable changes_ or _never_. Probably for each window.

 

___
 Imported from https://dev.vaadin.com/ issue #2056

**Comment by TatuLund** [comment]
In Vaadin 10 Router concept there is [BeforeLeaveObserver](https://vaadin.com/docs/v14/flow/routing/tutorial-routing-lifecycle.html)
