### ISSUE TITLE
Streaming + Firefox + Multiple tabs break

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5476]
**Originally by _CodingFabian_**

___
When using Push Mode streaming, and firefox, push fails most of the time. the javascript console says: cannot parse messageLength and prints out the same uuid that is used for the x-atmosphere-trackingid.
I switched to long polling and its fine.

___
 Imported from https://dev.vaadin.com/ issue #14311

**Comment by TatuLund** [comment]
Most browsers have limitation for simultaneous http connections to the same site. This limits number of open tabs when Push is used. The limitation does not apply to Websocket connections, which can be used to workaround the problem.
