### ISSUE TITLE
Abstract implementations for Table.ColumnGenerators and FieldFactories that provide component caching

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#550]
**Originally by @jouni**

___
We need a way to handle situations like #2049. All generated component references should be cached with itemId-propertyId keys, and those components would be reused whenever possible.

___
 Imported from https://dev.vaadin.com/ issue #2071

**Comment by TatuLund** [comment]
See also https://github.com/vaadin/framework/issues/2360
