### ISSUE TITLE
ComboBox item icons and setWidth causes item caption to wrap with Chameleon

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5504]
**Originally by @anezthes**

___
I was trying to fix the alignment of item icons for comboboxes in chameleon. When I tried setting the width of the combobox, I discovered that the item caption is wrapped.

___
 Imported from https://dev.vaadin.com/ issue #14355

**Comment by jouni** [comment]
Most probably a wontfix, as Chameleon theme will be deprecated in version 8.

Please reopen if this is a serious issue in your application.
