### ISSUE TITLE
The VAADIN folder should also be served relative to the servlet path

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5529]
**Originally by @Artur-**

___
If you deploy a VaadinServlet with a /foo/bar/* mapping, it should serve the VAADIN folder at /foo/bar/VAADIN. Using a 
```
resources=.
```
parameter, you can make the servlet try to load the static content from /foo/bar/VAADIN but the servlet does not recognize that as a valid path for static content.

This should work without further configuration:
```
	@WebServlet(value # { "/foo/bar/*" }, asyncSupportedtrue, initParams # { @WebInitParam(name"Resources", value = "/foo/bar") })
	@VaadinServletConfiguration(productionMode # false, uiMappingtest1UI.class)
	public static class Servlet extends VaadinServlet {
```

This should also work, provided you end the URL in a slash:
```
	@WebServlet(value # { "/foo/bar/*" }, asyncSupportedtrue, initParams # { @WebInitParam(name"Resources", value = ".") })
```

___
 Imported from https://dev.vaadin.com/ issue #14398

**Comment by Legioth** [comment]
This was apparently fixed ages ago through https://github.com/vaadin/framework/commit/1e978a6ba0924c240803543a31d024b7c649f4ce.
