### ISSUE TITLE
Javadoc for setPrimaryStyleName() does not mention that only one primary name is supported

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5535]
**Originally by @hesara**

___
The javadoc for Component.setPrimaryStyleName() should indicate that a component can only have one primary style name, and multiple parts separated by space are not supported.

GWT UIObject.setStylePrimaryName() does not support multiple primary style names, either.

___
 Imported from https://dev.vaadin.com/ issue #14411

**Comment by TatuLund** [comment]
In Vaadin 8 JavaDoc states "Changes the primary style name of the component", Changes -> implies only one. Is it clear enough?
