### ISSUE TITLE
Custom font loading should be more controllable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5549]
**Originally by @jouni**

___
Currently the Valo theme inspects the $v-font-family variable to see if any custom bundled fonts are in use, and includes the corresponding @font-face declarations for it.

In case a developer wants to use another version of the same font, the automatic font loading should be disabled somehow.

Possible solutions:

 1. Provide a new boolean flag to disable the automatic loading
 2. Provide a new list variable per custom font indicating what font weights to load, e.g. `$v-font-open-sans: 300, 400, 600, italic 400, italic 600;`. If the variable is true, all weights are loaded. If false, no weights are loaded.

This should apply to the bundled Font Awesome icon font as well.

**Comment by nartamonov** [comment]
This fix is really needed for non-latin based developments because default fonts contain only latin character sets. Raise priority please!
