### ISSUE TITLE
Websockets do not work on Tomcat 8 if you have mapped the same servlet to multiple locations

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5570]
**Originally by @Artur-**

___
```
@Push
public class T8testUI extends UI {

	@WebServlet(value # { "/foo/*", "/bar/*", "/VAADIN/*" }, asyncSupportedtrue)
	@VaadinServletConfiguration(productionMode # false, uiT8testUI.class)
	public static class Servlet extends VaadinServlet {
	}

	@Override
	protected void init(VaadinRequest request) {
		final VerticalLayout layout = new VerticalLayout();
		layout.setMargin(true);
		setContent(layout);

		Button button = new Button("Click Me");
		button.addClickListener(new Button.ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				layout.addComponent(new Label("Thank you for clicking"));
			}
		});
		layout.addComponent(button);
	}

}
```

1. Deploy to Tomcat 8
2. Open /foo - websockets work
3. Open /bar - websockets fail and it falls back to long polling

___
 Imported from https://dev.vaadin.com/ issue #14477

**Comment by gatanaso** [comment]
We are running into this issue as well, using Vaadin 8.9.x and Tomcat 8. Websockets don't work if the same servlet is mapped to different locations.

What would be a recommended way to work around this issue? 

BR,
Goran

**Comment by TatuLund** [comment]
My understanding is that this is a known and documented limitation. There is should be warning logged about multiple servlet mappings when application starts.
