### ISSUE TITLE
Vaadin UI comparison frequently fails when dealing with proxies

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5587]
**Originally by _Juuso Valli_**

___
Current behavior is causing assert failures when using CDI proxies for UI's. Similar problems are likely to pop up with Spring. For example VaadinSession.removeUI fails an assert as does ConnectorTracker.cleanConnectorMap.

The UI class should have a robust equals method that works with any combination of proxies / underlying objects, and this method should be used throughout instead of a == comparison.
One could implement this for example by comparing the UIIDs and the UIs' sessions.

___
 Imported from https://dev.vaadin.com/ issue #14508

**Comment by tsuoanttila** [comment]
There are fixes for the original `removeUI` issue in #10574 and #10575 . This is definitely something we should fix everywhere in the FW that UI "equals" would be based on `UIId`. Is the connector already registered issue related to components or UIs or both?
