### ISSUE TITLE
Valo demo flaws in iOS 7 with Chrome 36

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5622]
**Originally by _basil.bourque_**

___
When using an iPad Air running iOS 7.1.2 in the Chrome browser 36.0.1985.57 today 2014-09-02, I see several problems with the Valo demo at 
https://vaadin.com/valo

I used the default theme and default "Desktop" mode (widget below the demo box area).

# "Selects" tabThe lists of "Option 1", "Option 2", etc. appears on my Mac, but in iOS those boxes are empty. They say "0 Items". 

On both "TwinCol Select" groups, typing into the box and tapping the "+" button fails to add any items to the lists.

Below "Left Column" in a "0 Items" widget. Below that is a white box that stretches to far to the right. The white box is underneath a "<" button.

# "Checkboxes"  tabSometimes the checkboxes refuse to toggle. For example, tap the "Be Option Two" box. The box is highlighted with a blue glow. But the box will not become checked, even with repeated tapping. I cannot reproduce this.

# "Common UI Elements" tabThe spinner never stops spinning. Tapping one of the three "x" seconds items in segmented control has no effect. I tried tapping those items before and during the spinning, but no effect.

The segmented controls "Type" and "Additional Style" make it difficult to visually identify which are selected and which are not. I did not even realize at first that "Additional Style" was multi-select.

The faint light-colored text in some of the Notifications is impossible to read. Example: Choose "Error" + "Success".

# "Forms" tabThe text of the "Bio" field appears too low, almost like there is a line of blank text at the top.

# "Sliders" tabThe sliders do function. But they ignore a quick gesture. Seems I have to tap on the round circle, wait a long moment, and then begin the slide movement. In contrast, when I do a quick a tap-and-slide, nothing happens.

___
 Imported from https://dev.vaadin.com/ issue #14587

**Comment by jouni** [comment]
Can’t reproduce with the latest Chrome for iOS (iOS 10, iPhone 6s). The TwinColSelect is quite unusable on Chrome for iOS, but that is mostly a “cantfix”, but also a “wontfix” for now, as we don’t want to reimplement TwinColSelect without the native select elements.

Please open new issues for specific problems you still have.
