### ISSUE TITLE
TextArea cannot be scrolled with Valo theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5631]
**Originally by @vaadin-marcus**

___
A TextArea's content cannot be scrolled with the Valo theme. Same TextArea is scrollable when switching back to Reindeer theme.

___
 Imported from https://dev.vaadin.com/ issue #14599

**Comment by jouni** [comment]
Wontfix, as there’s a clear workaround, and the root cause of this issue is a critical fix for CSS layouting issues in Valo.
