### ISSUE TITLE
Displaying component information in read-only mode.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5679]
**Originally by _krosh08_**

___
Vaadin 7.2.3 release removed input prompt from read-only or disabled ComboBox component (see [#10573](http://dev.vaadin.com/ticket/10573)). 

However, it would be quite useful to display information in the component without setting the component's value. For example, if we want to display default application values (values, which the application will use if no user input is made). 

We suggest an additional API call to be added for this purpose. For example, *setEmptyValueInfo*() 
If set, this information will be displayed in read-only mode of the component that has no value in the input-prompt-fashion (grayed out). In edit mode the input prompt will take precedence if specified.

This should be applicable to all the Vaadin components, which allow input prompt (hint).

___
 Imported from https://dev.vaadin.com/ issue #14676

**Comment by sukhmel** [comment]
Was there any progress regarding this?
