### ISSUE TITLE
Layout issue with Valo theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5696]
**Originally by _mkn@compart.com_**

___
Nesting several Horizontal- and VerticalLayouts will lead to a broken layout. Scrolling is not correct.

As you can see from the attached example, this workes fine with Reindeer theme, using Valo the result is incorrect.

See also: https://vaadin.com/forum#!/thread/8210143

___
 Imported from https://dev.vaadin.com/ issue #14719

**Comment by jouni** [comment]
Closing as invalid.
