### ISSUE TITLE
Window resize listeners should be communicated lazily by default

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5719]
**Originally by @mstahv**

___
In Vaadin 6 series window size change listener used to communicate values lazily so that the server side listener was triggered only when window resizing paused or stopped. In Vaadin 7 series, each size change event is sent to server eagerly by default, generating lots of obsolete traffic. There is a flag for in in the server side API, but if I can't find it, probably most wont. Therefore I'd suggest to change the default back to lazy .

**Comment by mstahv** [comment]
fixed in https://github.com/vaadin/framework/pull/10675

**Comment by TatuLund** [comment]
This has been implemented since Vaadin 8.4.0
