### ISSUE TITLE
Tabsheet does not work with injectcted Compoments (vaadin cdi 1.0.0.beta2)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5725]
**Originally by _raffael_**

___
Since ViewScoped and UIScoped are now NormalScope and the Components are proxied the Tabsheet does not display injected components anymore.
A simple fix is to change the isRenderd() in Method Tabsheet.java from

```
	public boolean isRendered(Component childComponent) {
		return childComponent == getSelectedTab();
	}
```
to

```
	public boolean isRendered(Component childComponent) {
		return childComponent.equals(getSelectedTab());
	}

```
Maybe some null checking should be done too.

A test project to demonstrate the bug can be found here: 
https://gitlab.com/qwasli/vaadin-cdi-test

___
 Imported from https://dev.vaadin.com/ issue #14772

**Comment by bingtimren** [comment]
This problem just costed me a whole day debugging. Can someone fix it? I'm working on Vaadin 8.1.1 and Vaadin-CDI 2.0.0
