### ISSUE TITLE
No horizontal scrollbar in TableTooManyColumns test when using Valo theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5749]
**Originally by _sergey@vaadin.com_**

___
TableTooManyColumns test UI (http://localhost:8888/run/TableTooManyColumns?restartApplication) produces no horizontal scrollbar when using Valo theme, while it does in Reindeer. Screenshots attached.

It goes down to this css fix (_global.scss):

```
    .v-scrollable {
      overflow: auto;

      // "Unnecessary scrollbar" related fixes
      > .v-widget {
        // This is needed for IE
        vertical-align: middle;

        // Needed for all browsers. Can't really show anything outside the
        // scrolling area anyway, so we can safely hide any overflow
        overflow: hidden;
      }
    }

```

This ticket is related: http://dev.vaadin.com/ticket/14631

I applied similar fix, but used more specific selector (base/common.scss):

```
.v-scrollable.v-panel-content > .v-widget
```

___
 Imported from https://dev.vaadin.com/ issue #14810

**Comment by jouni** [comment]
Closing as invalid.
