### ISSUE TITLE
Push creating too many Atmosphere threads on Glassfish 4.1 on Solaris

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5759]
**Originally by _klaudetamertiku@gmail.com_**

___
Same application (Vaadin 7.3.2, push enabled) is deployed on Glassfish 4.1, JDK 1.7.0_67 

After limiting the number of atmosphere-related threads by setting the params org.atmosphere.cpr.broadcaster.maxProcessingThreads # 10 and org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads10,

still there are too many threads of type Atmosphere-Scheduler-x if the application is deployed on Solaris (247 threads) and only 4 threads of this type if the application is deployed Windows

For more details: 

[https://vaadin.com/forum#!/thread/8332456/]

[https://groups.google.com/forum/#!searchin/atmosphere-framework/thread/atmosphere-framework/zwTC_p4yNWY/jn_hkXZ0gxEJ]

This problem is the same also using Vaadin 7.2.7

___
 Imported from https://dev.vaadin.com/ issue #14827

**Comment by TatuLund** [comment]
This has been apparently fixed by limiting to ApplicationConfig.SCHEDULER_THREADPOOL_MAXSIZE
https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.5.x/modules/cpr/src/main/java/org/atmosphere/util/ExecutorsFactory.java#L189
