### ISSUE TITLE
Tabsheet "icons-on-top" style shifts the selected tab text & icon up

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5783]
**Originally by @jouni**

___
The selection border pushes the tab caption content up.

The line 546 in _tabsheet.scss should only be applied if the tabsheet has the "framed" style applied as well. This could be moved alongside the line 474.
```
.#{$primary-stylename}-tabitem-selected .v-caption {
  padding-bottom: round($v-unit-size/6) + first-number($v-border);
}
```

___
 Imported from https://dev.vaadin.com/ issue #14870

**Comment by jouni** [comment]
Can’t reproduce any more.
