### ISSUE TITLE
Vaadin does not work inside the JavaFX webkit engine

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5799]
**Originally by _pjc158_**

___
Vaadin does not seem to work when used with the JavaFX webkit engine.

We have tried the JavaFX webkit engine with other web applications and they seem to work fine.

A plank page is displayed.

___
 Imported from https://dev.vaadin.com/ issue #14899

**Comment by mvysny** [comment]
I am led to believe that Vaadin actually works with the JavaFX browser. Please check out this project: https://github.com/mvysny/testbench-simplest-demo
It uses TestBench+Selenium to run tests inside a JavaFX browser. Apparently the Vaadin page is rendered properly as can be seen from the screenshot produced during the test run - the `target/screenshot.png` file.
