### ISSUE TITLE
Nested Responsive layouts fail

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5809]
**Originally by _HermanBovens_**

___
The Responsive extensions provides component-based responsivity, but this currently only works at a single level.

The root cause for nested Responsive layouts not working is that if the nested layout needs to change size depending on a breakpoint of the parent layout, it needs to have it's size specified in CSS (and thus an undefined size in java).  But the responsive extension only works for layouts that have a relative size specified in java.

See [https://vaadin.com/forum#!/thread/8417250] for a more elaborate description.

___
 Imported from https://dev.vaadin.com/ issue #14917

**Comment by HermanBovens** [comment]
Migrated root cause issue: https://github.com/vaadin/framework/issues/5810
