### ISSUE TITLE
External dependencies versions for OSGi package import statements are not centralised

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5818]
**Originally by @macprzepiora**

___
Version strings used to assemble OSGi manifest package import statements are not centralised as e.g. ant properties, but embedded straight in import statement strings in build scripts.

For example both shared/build.xml and server/build.xml specify that the resulting jars should have import statement for org.json package (that is provided by bundle not built when building core Vaadin project) in their MANIFEST.MF. The version is embedded in the property named "shared.osgi.import" defined in target "jar". This has already caused a problem for users using OSGi environment when json dependency version was changed for 7.3 branch, but the build scripts weren't updated (see #14618).

org.json is only example, there are other dependencies that should be taken care of, like jsoup packages, guava, streamhtmlparser or flute

It would be much better if version strings were centralised (e.g. in master build.xml) for OSGi imports, or, ideally, the versions were extracted from dependency bundles that export them (during the build).

___
 Imported from https://dev.vaadin.com/ issue #15106

**Comment by elmot** [comment]
OSGi support is completely rewritten in 8.1, most probably we can close this ticket.
