### ISSUE TITLE
Valo demo page fails to close sub-window.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5821]
**Originally by _basil.bourque_**

___
1) Go to Valo theme demo, on the "Common UI Elements" tab.
http://demo.vaadin.com/valo-theme/#!common

2) Scroll down near the bottom.

3) In the "Dialogs" section, click the "Open Window" button.

BUG: The sub-window that opens cannot be closed. Clicking the "OK" and "Cancel" buttons do nothing. Clicking outside the dialog does nothing. Even clicking the web browser's Reload button refreshes the app but leaves that same sub-window displayed!

___
 Imported from https://dev.vaadin.com/ issue #15111

**Comment by jouni** [comment]
Wontfix
