### ISSUE TITLE
Issues with Chrome & Radio Buttons/CheckBoxes

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5830]
**Originally by _lwilliamson_**

___
Have just noticed a new problem wih Google Chrome and my application (the issue doesnt exist on Firefox or IE10). I recently updated to Vaadin 7.3.3, and this issue definitely didnt exist in 7.3.0. Having said that, I cant rule out my PC auto-updating Chrome within the same timeframe. Chrome version is 38.0.2125.104 m.

The problem is quite simply that clicks on radio buttons and check boxes do not respond when a batch of text is selected on the browser. When the selection is cleared, things work OK again.

The following code highlights the issue, but you can also replicate it on your vaadin sampler. 

(Using Chrome) When the window shows, select some text on the label, and then try and select an option. It doesnt work. You can see the little circle blink as though it does react to the press, but it is not selected. Eventually it will select (click away until it does), and you are ok from that point onwards until you select text again.

On Firefox and IE10, the option group is always selected immediately.

```
@PreserveOnRefresh
@Theme("valo")
public class TestUI extends UI
{    
    
    @Override
    public void init(VaadinRequest vaadinRequest)
    {
        VerticalLayout vl = new VerticalLayout();
        vl.setSizeUndefined();
        vl.setSpacing(true);
        
        Label label = new Label("Test Label");
        label.setSizeUndefined();        
        vl.addComponent(label);
        
        OptionGroup testGroup = new OptionGroup();
        testGroup.addItem("Option 1");
        testGroup.addItem("Option 2");
        testGroup.setImmediate(true);
        testGroup.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);                        
        testGroup.setSizeUndefined();
        
        vl.addComponent(testGroup);                
        setContent(vl);            
    }               
}
```

___
 Imported from https://dev.vaadin.com/ issue #15125

**Comment by jouni** [comment]
Can’t reproduce any more with macOS Sierra, Chrome 54.
