### ISSUE TITLE
Heartbeat should invoke showCommunicationError on missed heartbeats

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5836]
**Originally by _CodingFabian_**

___
when the client side heartbeating misses heartbeats it does not do anything.
I propose it should invoke connection.showCommunicationError

___
 Imported from https://dev.vaadin.com/ issue #15131

**Comment by sirbris** [comment]
We are also facing this issue (current version 8.4.3)! When the third heartbeat was missed, our UI allows one more interaction and then just gets disabled... shouldn't there be some kind of error message?
