### ISSUE TITLE
Humanized notification doesn't disappear on Android default browser

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5870]
**Originally by _ngsage_**

___
When displaying a simple humanized notification using Notification.show() the message is correctly displayed on the screen but doesn't disappear after a few seconds like on Chrome & Firefox. I'm using the Android browser 4.2.2.

Also, there is no way of making the notification go away...

___
 Imported from https://dev.vaadin.com/ issue #15185

**Comment by dRaftom** [comment]
same issue here: on Windows: google Chrome / MSIE

code used:
```
public static void NotifyUser(Information information)
  {
    Notification notification = new Notification(information.getCaption(),
        information.getContent(),
        Notification.TYPE_HUMANIZED_MESSAGE, true);

    // Customize it
    notification.setDelayMsec(1700);
    notification.setHtmlContentAllowed(true);

    // Show it in the page
    getCurrent().access(() -> notification.show(Page.getCurrent()));
  }
```

notification.setDelayMsec(1700); doesn't work
