### ISSUE TITLE
Lost focus after closing Window

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5891]
**Originally by _ipedja_**

___
Problem is when I use Runo theme after closing modal window it works fine, it is focused on textfield.
When Valo theme is used it will focus back to Button after closing Window. Actually you can see that it focuses on TextField and than instantly focuses back on Button.

```
    @Override
    protected void init(VaadinRequest request) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

        Button button = new Button("Open window");
        final TextField textField = new TextField("Focus shoud go here");
        
        button.addClickListener(new Button.ClickListener() {
            public void buttonClick(ClickEvent event) {
                Window window = new Window("WINDOW");
                window.setModal(true);
                window.addCloseListener(new CloseListener() {
                    @Override
                    public void windowClose(CloseEvent e) {
                        textField.focus();
                    }
                });
                addWindow(window);
            }
        });
        layout.addComponents(button, textField);
    }
```

___
 Imported from https://dev.vaadin.com/ issue #15226

**Comment by ricardovm** [comment]
I'm having this problem too. Using ipedja's code (first comment) with 8.1.1, it still removes focus from the TextField. It's annoying to the users must to use the mouse to focus the field after migrating to Valo.

**Comment by ricardovm** [comment]
Interesting that with `$v-animations-enabled: false;`, the `focus()` problem after a `Window.close()` is solved.

**Comment by sirbris** [comment]
Any news on this topic? I'm struggling with the same issue... good hint with disabling animations btw

**Comment by jouni** [comment]
My first guess is that this line affects the focusing for some reason: 
```java
// No event previews should happen after the animation has
// started
Overlay.this.setPreviewingAllNativeEvents(false);
```
https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Overlay.java#L756-L758

**Comment by Legioth** [comment]
Who will take care of updating the release notes to mention this breaking change?

**Comment by elmot** [comment]
@anasmi, can you, please,  update the release notes?

**Comment by elmot** [comment]
@jouni, why the line you are pointing at, does not affect Runo?

**Comment by jouni** [comment]
@elmot because Runo does not specify any animations for the window. The presence of an animation is checked here (and the previous code block I linked to is contained within that if-statement): https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/widgets/Overlay.java#L729-L730
