### ISSUE TITLE
Add html data-value to every input with a wrapper element

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5919]
**Originally by _santeriv-profit_**

___
It would be nice if all inputs would carry currently selected data- attribute in their wrapper element <span> (see example in below link)

Then you could do something with just Vaadin Themes/SASS/CSS like this http://jsfiddle.net/whP2F/65/ 

basically it is all about of making possible of using CSS

```
 content: attr(data-something-meaningfull);
```

If this improvement idea feels too risky then you could consider of flagging it like 

Field.setHtmlDataEnabled(true)

or alike.

___
 Imported from https://dev.vaadin.com/ issue #15277

**Comment by santeriv** [comment]
(note to self)
