### ISSUE TITLE
ComponentContainerViewDisplay add setter and getter for container

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5920]
**Originally by _santeriv-profit_**

___
In case you use an UI base class for some reason where a default Navigator is created. And you just want to replace the ViewDisplay in your own UI inherited from the base class.

It is not by API not possible thus this kind of reflection **workaround** is needed 

```
    Layout viewContent = getViewContent();
    //WORKAROUND for Vaadin missing feature it should be possible reset easier if just ViewDisplay changes
	  ComponentContainerViewDisplay display = (ComponentContainerViewDisplay) getNavigator().getDisplay();
    try {
	    Field containerField = ComponentContainerViewDisplay.class.getDeclaredField("container");
	    containerField.setAccessible(true);
	    containerField.set(display, viewContent);
    } catch (NoSuchFieldException | SecurityException | IllegalAccessException | IllegalArgumentException e) {
	    throw new RuntimeException("UI configuration problem with ComponentContainerViewDisplay.class container-> "+ComponentContainerViewDisplay.class.getDeclaredFields());
    }
```

The title of the issue says the all. 

In case you do not want go to ComponentContainerViewDisplay then resetting of ViewDisplay should be possible, instead of constructing new Navigator. 

___
 Imported from https://dev.vaadin.com/ issue #15278

**Comment by santeriv** [comment]
(note to self)
