### ISSUE TITLE
vaadin-sass-compiler ConsoleMessageNode improvements

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5923]
**Originally by _santeriv-profit_**

___
See eg. http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_5 

Currently @error does nothing and @warn outputs with Severe level

It is nice that something can be outputted if needed using @debug

```
!#.scss
@debug 10em + 12em;
```

Which currently outputs to console
```
!#console.out (actual)
Nov 25, 2014 11:30:05 AM com.vaadin.sass.internal.tree.ConsoleMessageNode traverse
INFO: 10em + 12em
```
```
!#console.out (expected)
Line 1 DEBUG: 22em
```

I would appreciate if the 'extra line' 
```
Nov 25, 2014 11:30:05 AM com.vaadin.sass.internal.tree.ConsoleMessageNode traverse
```
could be replaced with line element information like in errors (com.vaadin.sass.internal.parser.SCSSParseException) instead or just removed.

also some magic variables like currently parsed file could be nice eg. **$vaadin-sass-compiler-global-variables-current-file**

or even if maps are supported

```
function vaadin-sass-compiler-variables-get($map-key) {
  return map-get($vaadin-sass-compiler-global-variables,$map-key);
}
@debug "Experimenting stuff at #{vaadin-sass-compiler-variables-get("current-file")}";

```

___
 Imported from https://dev.vaadin.com/ issue #15282

**Comment by santeriv** [comment]
(note to self)
