### ISSUE TITLE
The ability to choose tab alignment in TabSheet

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#593]
**Originally by @wolfie**

___
It would be nice if I could define where the tabs would be aligned, and not just have them always on the left hand side. Right-alignment should be useful, but I could imagine having them centered would have its uses.

At least for the right alignment, something that might be worthy of consideration is whether the tabs would be populated left-to-right or right-to-left. Maybe the developer could define it herself?

___
 Imported from https://dev.vaadin.com/ issue #2322

**Comment by TatuLund** [comment]
In Vaadin 8 Valo theme there are style presets for different alignments, [see the demo](https://demo.vaadin.com/valo-theme/#!tabs).
