### ISSUE TITLE
Valo disables copy/paste from error tooltips

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5946]
**Originally by @Artur-**

___
It's not possible to copy/paste the error message from a component error

___
 Imported from https://dev.vaadin.com/ issue #15323

**Comment by sirbris** [comment]
will this be possible one day? would be really helpful!

**Comment by sirbris** [comment]
workaround would be:
```
.popupContent .v-errormessage {
   -webkit-user-select: all;  /* Chrome 49+ */
   -moz-user-select: all;     /* Firefox 43+ */
   -ms-user-select: all;      /* No support yet */
   user-select: all;          /* Likely future */   
}
```
