### ISSUE TITLE
Can't copy paste exception message if there is a ServiceException (Valo)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5963]
**Originally by @Artur-**

___
This is because ".v-app" defines user-select: none. It sucks.

___
 Imported from https://dev.vaadin.com/ issue #15346

**Comment by jouni** [comment]
Are those messages log to the browser console by any chance? I think that would be the correct fix for this issue, that you could copy the error message from there.

**Comment by Legioth** [comment]
Why is `user-select: none` is necessary there?

**Comment by jouni** [comment]
That’s a good question. “Why are server error messages shown in a tooltip”, is also a good one :)

I guess there’s no good reason not to have error messages selectable. I think this is just an oversight, that that style is inherited from `.v-app`.
