### ISSUE TITLE
Grid is focusable but not Focusable

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6009]
**Originally by @jdahlstrom**

___
Grid can be focused by the user but not programmatically; its tab index is also always 0 and cannot be set except by manipulating the element directly. The server side should implement `Component.Focusable` and the clientside `c.g.g.user.client.ui.Focusable`; focus and blur event should probably be implemented as well.

___
 Imported from https://dev.vaadin.com/ issue #15425

**Comment by Legioth** [comment]
Grid is `Focusable` nowadays.
