### ISSUE TITLE
Header widgets are not unregistered

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6012]
**Originally by @Artur-**

___
When a Grid is detached, an error is logged to the debug window:
```
Widget is still attached to the DOM after the connector (TextFieldConnector (851)) has been unregistered. Widget was removed.
```
The TextFieldConnector in this case is the filtering text field in http://demo.vaadin.com/sampler/?debug#ui/grids-and-trees/grid/features

___
 Imported from https://dev.vaadin.com/ issue #15428

**Comment by lennartfricke** [comment]
I just want to leave note  that I still experience this behaviour in vaadin 8.3.1.
