### ISSUE TITLE
Grid editable mode conditions

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6024]
**Originally by @MTzukanov**

___
Nowhere documented that it cannot be editable in multiselect mode. Or it's supposed to be but it's a bug?

___
 Imported from https://dev.vaadin.com/ issue #15445

**Comment by TatuLund** [comment]
This issue needs better description about actual issue. Atleast in newest Vaadin 8.4 versions Grid editor works also in multi select mode.
