### ISSUE TITLE
Ritch Text Area 'create link' function wontt work at firefox 34.0.5 and Internet Explorer 9.0.8

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6113]
**Originally by _gnemeth_**

___
The ritch text area 'create link' function wont work at firefox 34.0.5 and internet explorer 9.

After than i push the Create link button, and fill the popup form, than press OK, not present the link in the text area. But it work property at Chrome.

___
 Imported from https://dev.vaadin.com/ issue #16203

**Comment by TatuLund** [comment]
This is duplicate of https://github.com/vaadin/framework/issues/11888

And issue has been fixed in Vaadin 8.10.5
