### ISSUE TITLE
Saving with Grid editor doesnt update the client side

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6178]
**Originally by _MarcelloGarini_**

___
Switching from 7.4.0.beta1 to beta2 broke the client side refresh while saving with editor. Values are correctly saved on database.

___
 Imported from https://dev.vaadin.com/ issue #16479

**Comment by yashh08** [comment]
Does anybody know how to save grid data to database on saveClickListsner and how can we save the edited grid data toexact same row?
I may not be able to ask the question properly? But If anyone know the proper way please help.
Help would be greatly appreciated. Thanks!

**Comment by Ansku** [comment]
Cannot reproduce in either 7.7 or 8.12 so I assume this one got fixed at some point.
