### ISSUE TITLE
Grid: calculated scroll position assertions breaks browser debugging in chrome

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6278]
**Originally by @manolo**

___
For some reason in chrome it is very frequent that the calculated scroll position does not match the dom position in just 1 pixel. It could be caused by number rounding, but not sure.

The assertion warning about that causes debugging breakages with the message: 'calculated scroll position (1678) did not match the DOM element scroll position (1677)' 

IMO this assertion should be a console warning until it is definitely fixed

___
 Imported from https://dev.vaadin.com/ issue #16608

**Comment by glucas** [comment]
I'm getting this with decimal values, e.g.

calculated scroll position (24.600000000000023) did not match the DOM element scroll position (24)
