### ISSUE TITLE
Can't scroll below row 40366 in IE8-IE11

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6290]
**Originally by @Artur-**

___
1. Open http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/large-dataset
2. Set items to 100000
3. Scroll down to the end

Expected result: Grid shows 100000, 10000000000 as the last row
Actual result: Grid shows 40366, 1629413956 as the last row

___
 Imported from https://dev.vaadin.com/ issue #16635

**Comment by KyleRogers** [comment]
This issue is still valid in Vaadin 7.7 and according to @Artur- can be applied to Vaadin 8 as well, see #8860 .

I'm hoping for a fix that gets ported back to Vaadin 7.7 because I cannot upgrade to Vaadin 8 due to browser requirements (especially IE 8) imposed by our client(s).

**Comment by Legioth** [comment]
For the record, the limit in Chrome seems to be 883 010 rows with the default rows height, even though it's not possible to scroll back any more after reaching that far.

**Comment by Legioth** [comment]
Limit seems to be 235 469 in Firefox according to #9752

**Comment by connect2code** [comment]
Is this bug resolved? I was to start implementing lazy loading for my table. If this bug still persist will have to look for a work around.

**Comment by jouni** [comment]
Even though it doesn’t really help current Framework users, this issue is solved in the next generation grid, starting from `<vaadin-grid>` v2 upwards: https://vaadin.com/blog/-vaadin-grid-2-0-with-million-dollar-scrolling

You can use it with Vaadin 10/Flow.

**Comment by elmot** [comment]
It works now.

**Comment by jouni** [comment]
@elmot, is there a demo which proves this? At least Sampler hasn’t been updated with this fix.

**Comment by elmot** [comment]
I just opened present sampler and could not reproduce the bug there.
There were some fixes to Grid since last update to the ticket, so it's plausible that the bug is "already fixed". 
If someone is able to reproduce, the bug will be reopen, of course.

**Comment by elmot** [comment]
Ok, thanks. Needs further investigation
