### ISSUE TITLE
Make Grid a field or make select components based on Grid

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6292]
**Originally by @mstahv**

___
Table is in many applications used as a field (selecting 1-N rows). As Grid does not work as a select like the old Table, it cannot easily be used in proper data binding.

___
 Imported from https://dev.vaadin.com/ issue #16638

**Comment by Legioth** [comment]
Handled by the `asSingleSelect()` and `asMultiSelect()` methods introduced in 8.0.
