### ISSUE TITLE
Make beans/DTOs first class citizens in Grid API

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6293]
**Originally by @mstahv**

___
In most cases Vaadin users will use List/Collection of basic DTOs that he/she wants to list in the Grid. API should be primarily optimized for this use case. Currently to use them in Grids you need to learn some cumbersome Container-Item-Property API.

Also Grid should have proper typing for its selection APIs, so that developers can get the selected DTO(s) from the Grid without guessing that the type is (that happens using the now prominent Container item id strategy).

___
 Imported from https://dev.vaadin.com/ issue #16639

**Comment by Legioth** [comment]
Done in Vaadin 8.
