### ISSUE TITLE
Table gets wrong selection mode on laptops with touch screens

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6356]
**Originally by @vaadin-marcus**

___
VScrollTable sets the multiselect mode based on a check if a device supports touch events. As many business laptops are now equipped with both touch screens and physical keyboards/mice, this isn't optimal.

```java
    private void setMultiSelectMode(int multiselectmode) {
        if (BrowserInfo.get().isTouchDevice()) {
            // Always use the simple mode for touch devices that do not have
            // shift/ctrl keys
            this.multiselectmode = MULTISELECT_MODE_SIMPLE;
        } else {
            this.multiselectmode = multiselectmode;
        }
    }
```

___
 Imported from https://dev.vaadin.com/ issue #16808

**Comment by TatuLund** [comment]
In version 7.7.20 setMultiSelectTouchDetectionEnabled(boolean) was added so that Table can be forced not to detect touch mode.
