### ISSUE TITLE
Grid should support undefined width based on column widths

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6358]
**Originally by @Artur-**

___
In many cases you want a grid where all your columns are "undefined" wide and the whole grid is just as wide as necessary to make the columns fit. This should be supported so that an "undefined" wide Grid is not fixed to 400px but is based on the sum of column widths (no column expansion done)

___
 Imported from https://dev.vaadin.com/ issue #16822

**Comment by TatuLund** [comment]
GridScrollExtension provides getColumnResizeCompensationMode(ColumnResizeCompensationMode.RESIZE_GRID), which implements the feature.

https://vaadin.com/directory/component/gridscrollextension-add-on
