### ISSUE TITLE
ComboBox/DateField button icons not visible in IE8 with Valo theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6363]
**Originally by @Ansku**

___
When set inside a Window and using Valo theme ComboBox and DateField don't display their buttons in IE8. Could not reproduce using the IE8 compatibility mode with IE11. 
```
public class FieldsUI extends UI {

    private class FieldWindow extends Window{
        public FieldWindow() {
            VerticalLayout layout =new VerticalLayout();
            setContent(layout);

            layout.addComponent(new ComboBox("Combo"));
            layout.addComponent(new DateField("Date"));
        }
    }

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        UI.getCurrent().addWindow(new FieldWindow());
    }
}
```

Original report: https://vaadin.com/forum/#!/thread/9283704

___
 Imported from https://dev.vaadin.com/ issue #16829

**Comment by TatuLund** [comment]
Just to note here that in scope of Vaadin 8 IE8 is not a supported browser, and thus this is not a bug in Vaadin 8.
