### ISSUE TITLE
Allow keyboard row navigation in Grid editor

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6370]
**Originally by @magi42**

___
Allow navigating between rows when Up/Down arrow keys are pressed. The navigation should only be allowed if the fields are unmodified - otherwise the current row would need to be either saved or cancelled (this feature would make edit reset a bit useful).

___
 Imported from https://dev.vaadin.com/ issue #16839

**Comment by TatuLund** [comment]
This is especially relevant for unbuffered Grid editor. Grid FastNavigation Add-On attempts to bring features needed for fluent keyboard based data input in Grid https://vaadin.com/directory#!addon/gridfastnavigation-add-on

**Comment by TatuLund** [comment]
Implemented in GridFastnavigation add-on
