### ISSUE TITLE
BrowserFrame is reloaded when changing layout

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6405]
**Originally by _lorenzo.benvenuti_**

___
A BrowserFrame inside an HorizontalLayout (actually I haven't tried with other containers) is reloaded if other children of the container are hidden. The attached UI replicates the problem: if you click on "Set frame content", then every time you close and reopen the panel a new download is triggered.

Thank you,

lorenzo

___
 Imported from https://dev.vaadin.com/ issue #16932

**Comment by Legioth** [comment]
This is a direct consequence of #7713. Hiding a does in this case have the same effect as removing the child.
