### ISSUE TITLE
Fade in notifications

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#643]
**Originally by @jouni**

___
Currently notifications do not fade in, they only fade out.

I propose they should also fade in, only faster than the fade out. The human eye will react to motion (e.g. opacity changes) more likely than to sudden changes in the view.

This is true atleast when the sudden change happens in the edges of sight (where things are more blurry). This can happen when the user is concentrating to the upper left corner of the window, and a tray notification appears in the lower right corner. I notice the fading out much more easily.

A sound cue would help enourmously in most of the cases, but we don't have sound support yet, so.

___
 Imported from https://dev.vaadin.com/ issue #2535

**Comment by jouni** [comment]
It is possible to theme the transitions since 7.3. Please close this issue.
