### ISSUE TITLE
Valo menu responsive smallest breakpoint broken in IE8 and IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6453]
**Originally by @jouni**

___
In IE9, the menu is collapsed outside the viewport, but the space reserved for the menu is not cleared from the main layout, leaving a large blank dark gray area visible.

In IE8, the menu is not collapsed at all, it is always visible.

___
 Imported from https://dev.vaadin.com/ issue #17040

**Comment by TatuLund** [comment]
IE8 and IE9 ares not a supported browsers with Vaadin 8, thus we are closing this as wont fix.
