### ISSUE TITLE
Re-introduce HeartbeatInterceptor for push

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6457]
**Originally by @Artur-**

___
HeartbeatInterceptor will cause an idle push connection to be closed and reconnected after a while (60s by default). In 7.3 the interceptor is enabled but in 7.4 it has been disabled because of https://github.com/Atmosphere/atmosphere-javascript/issues/141. Once there is a fix for https://github.com/Atmosphere/atmosphere-javascript/issues/141, the interceptor should be re-enabled. 

If there are some issues (e.g. race condition) in setting up the push connection and the heartbeat interceptor is disabled, the application will potentially stop working with a loading indicator being shown forever. If the heartbeat interceptor is enabled, the loading indicator will be shown for 60s and after that the push connection will be closed and re-opened, which may succeed if the original cause was a rare race condition and the app will then continue to work.

___
 Imported from https://dev.vaadin.com/ issue #17052

**Comment by peholmst** [comment]
We should get this fixed. I have a customer that needs this functionality. I re-enabled the interceptor locally and it appears to be working now, even though Atmosphere/atmosphere-javascript#141 is still open.
