### ISSUE TITLE
Grid automatically shows all rows.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6500]
**Originally by _basil.bourque_**

___
The Grid component (new in Vaadin 7.4) should have a feature where it automatically resizes to show all rows. 

Useful in situations where we know we have a small set of data and we are sure we want to display all rows. Use cases include a small picklist, or a "Current Status" on a dashboard type of app.

I imagine a new command "setHeightToShowAllRows". That command would have the effect of:

```
this.setHeightMode( HeightMode.ROW );
this.setHeightByRows( this.getContainerDataSource().getItemIds().size() ); // Show all rows.
```

That `setHeightByRows` would happen every time the backing container of data changed. So the calling programmer would only have to call "setHeightToShowAllRows" once, and thereafter the widget would automatically resize anytime the data changed. Very convenient to the calling programmer.

___
 Imported from https://dev.vaadin.com/ issue #17147

**Comment by jouni** [comment]
Should be fixed. Please reopen if HeightMode.UNDEFINED doesn’t work for you.
