### ISSUE TITLE
Tooltip when Grid header is too small for content

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6514]
**Originally by _michaelvogt_**

___
Sometimes it is necessary to keep the column width small, leading to the problem that the header content (usually text in that case) doesn't fit anymore. 

It would be helpful when Vaadin adds a tooltip in case this happens, so the user can see the full text of the header in such a situation when hovering the mouse over the respective header.

___
 Imported from https://dev.vaadin.com/ issue #17207

**Comment by AlexWagner** [comment]
Using the title-attribute for getting tooltips in header cell works. The column is sortable but the look of the tooltip is standard browser like.

When using a Label component in the header cell, tooltips look like all other Vaadin tooltips. Unfortunatly you cannot sort any longer the column if you click on that Label.

So it would be nice to have a option like that for columns

`column.setHeaderDescription("my description")`

that uses the Vaadin tooltips AND enables sorting

**Comment by tsuoanttila** [comment]
Duplicate of #7527, `HeaderCell::setDescription` is available starting from Vaadin 8.4.0.
