### ISSUE TITLE
Design does not recognize inheritance corectly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6537]
**Originally by _jotbepunkt_**

___
I have a base view for all my master data editing (providing the support for the save, cancel and changelog button. 
```
public abstract class DataDetailViewBase<BO, PRESENTER> extends VerticalLayout  {
  
   private final FieldGroup fieldGroup = new FieldGroup();
   private Button saveButton;
   private Button cancelButton;
   private Button showChangelogButton;

   private PRESENTER presenter;

   public DataDetailViewBase() {
      Design.read(this);

      saveButton.addClickListener(event -> presenter.save());
      cancelButton.addClickListener(event -> presenter.cancel());
      showChangelogButton.addClickListener(event -> presenter.showChangelog());
   }

}
```
and I have several concrete classes like this:

```
@DesignRoot
public class CustomerViewImpl extends DataDetailViewBase<CustomerBo, CustomerPresenter> implements CustomerView {

   private TextField nameTextField;
   private TextField name2TextField;
   // and some more fields
  
}
```
having an HTML file like this:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" name="design-properties"
	content="{&quot;RULERS_VISIBLE&quot;:true,&quot;GRID_TYPE&quot;:&quot;RegularGrid,20&quot;,&quot;SNAP_TO_OBJECTS&quot;:true,&quot;SNAP_TO_GRID&quot;:true,&quot;GUIDELINES_VISIBLE&quot;:true,&quot;GRID_VISIBLE&quot;:true,&quot;SNAPPING_DISTANCE&quot;:10,&quot;PAPER_WIDTH&quot;:768,&quot;PAPER_HEIGHT&quot;:1024,&quot;THEME&quot;:&quot;valo&quot;}">
</head>
<body>
	<v-vertical-layout id="horizontalLayout" spaceing="true" width="100%"
		height="100%">
		<v-form-layout>
			<v-text-field _id="nameTextField"/>
			<v-text-field _id="name2TextField"/>
			<!-- and some more fields -->
		</v-form-layout>
		<v-horizontal-layout>
			<v-button _id="showChangelogButton" caption="show change log"/>
			<v-button _id="saveButton" caption="save"/>
			<v-button _id="cancelButton" caption="cancel"/>
		</v-horizontal-layout>
		
		</v-vertical-layout>
</body>
</html>
```

When I instanciate the concrete class, `Design.read(this)` is called by the constructor of my base class. After the call all the fields of the concrete class are filled but not the buttons in the base class. These are still null, and the call of `saveButton.addClickListener()` results into an NPE. When I add the annotation `@DesignRoot` to the base class, it results in an error that a file named `MachineDataDetailViewBase.html` is missing. 
 

___
 Imported from https://dev.vaadin.com/ issue #17259

**Comment by StephanPirnbaum** [comment]
I just ran into the same issue. Is there a workaround or fix available for this problem? 

I find this use case legit as it is sometimes necessary to have e.g. a basic form layout with common fields and, depending on the sub page you visited, further controls. For the sake of re-usability, this should work ootb.
