### ISSUE TITLE
Readonly date field with Resolution.MINUTE can not be made editable properly

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6565]
**Originally by _myucel_**

___
When a DateField with Resolution.MINUTE is created as read only and it's state is changed at runtime, hour and minute fields can not be edited. They are rendered as read only. If date field is not created as read only, but it's state is changed at runtime, everything is ok. This bug doesn't exist before version 7.2.1. I'm not sure but it might be related with issue #10262. 

___
 Imported from https://dev.vaadin.com/ issue #17319

**Comment by carlislefox** [comment]
This is still a bug in 8.0.4, if you flag a DateTimeField as readonly then change it to readOnly(false), the time selector will be stuck at 00:00 and not be editable.

**Comment by claudiocrociati** [comment]
In the 8.1.6 version the bug is still present

**Comment by krizda** [comment]
Actual in 8.4.3. Waiting for fix.

**Comment by krizda** [comment]
Workaround



    @Override
    public void setReadOnly(boolean readOnly) {
        super.setReadOnly(readOnly);
        VaadinUI.getCurrent().push();
    }

**Comment by ZheSun88** [comment]
The issue is fixed by #11249, and will be included in the next release.
