### ISSUE TITLE
Grid is unusable on Windows Phone and Surface touch devices

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6574]
**Originally by @jouni**

___
Windows Phone 8.1, Lumia 920

The Grid can barely be scrolled with the swipe gesture, and when you actually manage to get it to scroll, it's awfully slow.

Scrolling horizontally works better for some reason.

Rendering a Grid also takes a relatively long time on Windows Phone.

Sampler was used as a test.

___
 Imported from https://dev.vaadin.com/ issue #17337

**Comment by lochehong** [comment]
i'm having this problem with huawei mate 10 pro as well. but not on other huawei phones.
