### ISSUE TITLE
Wrong week number in DateField

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6583]
**Originally by _bogdanudrescu_**

___
Same as http://dev.vaadin.com/ticket/14437 but on Vaadin 6.

https://vaadin.com/forum/#!/thread/9640935

___
 Imported from https://dev.vaadin.com/ issue #17365

**Comment by asashour** [comment]
I believe this should be closed, since it is relevant to Vaadin 6.

**Comment by tsuoanttila** [comment]
Indeed. Closing the issue.
