### ISSUE TITLE
Valo theme: Error Notifications have no visual close indicator

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6587]
**Originally by _phansson_**

___
[Notifications](https://vaadin.com/api/7.4.3/com/vaadin/ui/Notification.html) of type ERROR_MESSAGE are supposed to have a visual close indicator. From "Book of Vaadin" (my highlighting):
[[Image(http://s21.postimg.org/ade5hnwlz/Notification_with_Valo_theme_error_book.png)]]

[[BR]]

Unfortunately this is not the case for the Valo theme which has no close indicator:

[[Image(http://s1.postimg.org/5fq9tka0v/Notification_with_Valo_theme_error.png)]]

The result is - for an application using the Valo theme - that the user doesn't know how to react when a `ERROR` type Notification is displayed.

(if you wonder why the second line doesn't appear on a line of its own inside the box this is because of [ticket 16558](http://dev.vaadin.com/ticket/16558) which is a different matter)

___
 Imported from https://dev.vaadin.com/ issue #17373

**Comment by jouni** [comment]
Fixed in 8.0 in #8296

**Comment by 6PATyCb** [comment]
What about 7.0?

**Comment by 6PATyCb** [comment]
My bad, 7.7.12 works fine. Thx.
