### ISSUE TITLE
uitest.war should not contain TB4 tests

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6649]
**Originally by @Artur-**

___
The uitest war file currently contain all TB4 tests and possible other unrelated classes. It should really contain only the UI classes.

Some servers such as Wildfly 8.2 and JBoss EAP 6.4 will scan through the war on deployment and try to load all classes. For each failure, e.g. because a super class cannot be found, a stack trace will be written to the log. Because of this, deployment of uitest.war is incredibly slow (and logs several millions of rows)

___
 Imported from https://dev.vaadin.com/ issue #17578

**Comment by Legioth** [comment]
I assume this was fixed by when the project was mavenized since all TB tests were moved to `src/main/test`.
