### ISSUE TITLE
Window with large contents shouldn't reset scroll position when polling.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6650]
**Originally by @Ansku**

___
If there is a default-sized (undefined) Window with large enough contents that it won't fit the browser window and scrollbars appear, scroll position resets at (almost) every polling. If the Window is given a defined size that is smaller than the contents, scroll position won't jump.

___
 Imported from https://dev.vaadin.com/ issue #17579

**Comment by TatuLund** [comment]
The issues still persist with Vaadin 7.7.15 but is fixed in Vaadin 8
