### ISSUE TITLE
Grid shows not needed horizontal scrollbar in IE11

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6653]
**Originally by _moberwasserlechner_**

___
Although not needed grid shows a horizontal scrollbar in IE 11.

Additionally there are vertical lines looking like left and right border of the scrollbar.

The vertical lines are only visible if there are not enough rows to fill the grid's height. The scrollbar stays.

IE11
[[Image(chrome_no_horizontal_scrollbar.png)]]

Chrome
[[Image(ie11_notneeded_horizontal_scrollbar.png)]]

___
 Imported from https://dev.vaadin.com/ issue #17582

**Comment by Seb-Sch** [comment]
I still experience the issue with the not needed horizontal scrollbar using IE11 / Edge on Vaadin 8.5.1. 
Chrome / Firefox is not affected.
Is it planned to solve this issue or are there any workarounds available?
