### ISSUE TITLE
Clicked button borders messed up in FF3/Mac

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#666]
**Originally by @hannuvaadin**

___
Example screenshot from Sampler's Icons sample.

1. Click Save button.
2. Click somewhere else in window.
3. Button's borders remain thick and messed up.

(This ticket probably in wrong category.)

___
 Imported from https://dev.vaadin.com/ issue #2637

**Comment by Artur-** [comment]
Don't think anybody uses Firefox 3 anymore
