### ISSUE TITLE
A non-modal window opened from a modal window can go behind the modality curtain

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6686]
**Originally by _lorenzo.benvenuti_**

___
If a non-modal window is opened from a modal window and then the modal window is clicked, the non-modal window goes behind the modality curtain. See attached UI.

Thank you,

lorenzo

___
 Imported from https://dev.vaadin.com/ issue #17720

**Comment by SomMeri** [comment]
The issue is still valid in vaadin 7.7.13 and in vaadin 8.5.1. We have the same problem.
