### ISSUE TITLE
Add origin to all events which can be fired both based on user actions and programmatically

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6718]
**Originally by @Artur-**

___
Many Grid events provide a
```
public boolean isUserOriginated()
```
which tells if the events was fired as a direct result of a user actions or by some server API call.

This should be added to all events, with the most critical probably being ValueChange.
Today you have to use boolean tricks in many cases to disable event handling at certain points. 

An example would be a "select all" functionality where you have a "select all" checkbox and individual checkboxes. If the "select all" checkbox is checked, you want to check all individual checkboxes. If the last unchecked individual checkbox is checked, you want to check the "select all" checkbox, but not at this point check all individual checkboxes.

___
 Imported from https://dev.vaadin.com/ issue #17820

**Comment by Legioth** [comment]
Added to value change events in Vaadin 8. Please open separate tickets for specific events that miss this functionality.
