### ISSUE TITLE
Vaadin TreeTable field factory is executed multiple times

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6725]
**Originally by _abhiramgiri_**

___
n an editable TreeTable the field factory for a single propertyId and ItemId the field factory is executed so many times.

I have one TreeTable with 5 records. All records are having 4 child.The table has 4 column. First time for 5 record the field factory create field is called 5*4=20 times. It is needed for for no of column and no of rows. I expanded one record and its having 4 child row. In this case the field factory is called 5*4*4=80 times for each row. Here total no of parent rows are 5 and child rows are 4. So total rows=9. When I click expand of one row total 9 rows to paint in table. So its calling the field facory about 9*4 factorial times. Its slowig down the performance of table.

___
 Imported from https://dev.vaadin.com/ issue #17838

**Comment by Pereitor** [comment]
Is this really open after? I cannot believe my eyes

**Comment by TatuLund** [comment]
I did brief look to example app code, it could be optimized. Now children are added and removed when tree is expanded and collapsed. This means that when tree is expanded all the fields need to be re-created, thus many calls done.

```
        tbl.addExpandListener(new Tree.ExpandListener() {

            @Override
            public void nodeExpand(Tree.ExpandEvent event) {
                List<SampleDTO> ddd = getTableData();
                for (SampleDTO dto : ddd) {
                    addItem(dto);
                    hierarchicalContainer.setParent(dto, event.getItemId());
                }

            }
        });
        tbl.addCollapseListener(new Tree.CollapseListener() {

            @Override
            public void nodeCollapse(Tree.CollapseEvent event) {
                hierarchicalContainer.removeItemRecursively(event.getItemId());
            }

        });
```
