### ISSUE TITLE
Custom Field ignores caption

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6747]
**Originally by _javydreamercsw_**

___
I created a custom field and noticed the caption is ignored.I had to add the caption outside of the field constructor to make it work.

___
 Imported from https://dev.vaadin.com/ issue #17906

**Comment by pwilkin** [comment]
This is still an issue in 8.4. The workaround does work, but causes layouting problems and requires further CSS workarounds to be viable.
