### ISSUE TITLE
Notification messages should stack

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#676]
**Originally by @emarc**

___
When multiple ~~tray~~ notification messages are shown within a short period of time, they are shown at the same position (over each other), which makes the messages unreadable. Instead, they should be stacked.

See example screenshot.

**Comment by heruan** [comment]
This is vital in my opinion: if N notifications are sent at the same time, N-1 notifications get lost. Was this ever addressed? @Legioth was this ever addressed? It's not easy to track this imported issues.

**Comment by hesara** [comment]
This has not been addressed in the framework, but there are various add-ons available that support such notification stacking (Toastr, Notifique and more at https://vaadin.com/directory#!browse/search=notification ).

**Comment by TatuLund** [comment]
This has been taken into account in the new Notification component in Vaadin 14 https://vaadin.com/components/vaadin-notification
