### ISSUE TITLE
Add support for container-sourced images in Grid

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6804]
**Originally by _vilo_**

___
We have images stored in a database. With `Table`, we used `ColumnGenerator` to generate `Image` components right from `byte[]` data from the container. With `Grid`, this is not easily possible, because `ImageRenderer` only supports `ThemeResource` and `ExternalResource`, but `StreamResource` is not supported.

Current workaround is to use a servlet to supply images, which has to duplicate complex access right logic and cannot load images in batch (as it does not know which images will be loaded on the current page). Or it has to communicate over session, which is also complex.

Or is there something I miss?

___
 Imported from https://dev.vaadin.com/ issue #18113

**Comment by TatuLund** [comment]
One alternative is to use BlobImageRenderer from https://vaadin.com/directory/component/grid-renderers-collection-for-vaadin7

**Comment by TatuLund** [comment]
Based on lack of comments BlobImageRenderer from https://vaadin.com/directory/component/grid-renderers-collection-for-vaadin7 seems to be satisfactory implementation.
