### ISSUE TITLE
Grid: Scrollbars missing in iOS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6807]
**Originally by @Saulis**

___
Tried with Chrome and Safari running on iPhone, also with Safari on iPad2 simulator. No scrollbars.

Used: http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features to test.

___
 Imported from https://dev.vaadin.com/ issue #18130

**Comment by pleku** [comment]
Verified issue with iOS10 on iPhone6s. Does not replicate on desktop Safari / Chrome on Mac OSX.

Escalator internals for showing the scroll bar when there is scrolling works as it should, but for some reason the `scroll-thumb` is not visible; it is not rendered at all.

For instance, I was able to get the `scroll-track` visible (with bg-color), but for some reason the `scroll-thumb` just never gets visible.

**Comment by pleku** [comment]
To fix this, it might take a full redesign / implementation of the css for the Escalator's scroll bars.

**Comment by TatuLund** [comment]
As stated above. Unfortunately currently architecture of Grid does not make it feasible to fix this in Vaadin 8. Having said that, I would like to note, that this use case should be tested in <vaadin-grid> of the Core Elements, fixed there if possible for future Vaadin Platform.

**Comment by jouni** [comment]
For the record, this issue is fixed in `<vaadin-grid>`, v2 upwards.

It has some rendering quirks when horizontal scrolling is also used (the vertical scroll indicator shifts horizontally as well), but it still provides the visual feedback of the current scroll position.
