### ISSUE TITLE
Can't focus/select rows below row 1316 in IE10

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6810]
**Originally by @Artur-**

___
See http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/large-dataset

In IE 10, you can't select any row below 1316 by clicking on it. If you click on 1316, the focus outline is cut in half (see https://vaadin.com/forum#!/thread/9705023/10192136). If you click on 1317 or below, the focus outline disappears. It's unclear if you still focus the row or now, but visually it is not shown as focused.

If you navigate with the down/up key on the keyboard, the focus outline moves as expected to 1317 in the case that you are in the bottom part of the grid so that it scrolls at the same time. If you navigate and the grid does not scroll, then the focus is moved but the outline is not shown until you reach the upper edge.

Both IE9 and IE11 work properly.

**Comment by TatuLund** [comment]
IE10 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
