### ISSUE TITLE
Grid: Column maximumWidth not respected

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6811]
**Originally by @Saulis**

___
Given a simple test:

    protected void setup(VaadinRequest request) {
        Grid grid = new Grid(createContainer());

        grid.getColumn("column1").setMaximumWidth(100);

        grid.setWidth("500px");
        addComponent(grid);
    }

    private Container.Indexed createContainer() {
        IndexedContainer c = new IndexedContainer();
        c.addContainerProperty("column1", String.class,
                "<span>column1</span>");

        c.addItem();
        return c;
    }

The column width seems to be ~140px although it should be 100px.

___
 Imported from https://dev.vaadin.com/ issue #18150

**Comment by TatuLund** [comment]
In[ GridScrollExtension](https://vaadin.com/directory/component/gridscrollextension-add-on) add-on there is workaround against this issue with Vaadin 8.
