### ISSUE TITLE
Textfield text is not fully visible in portlet on Liferay with IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6832]
**Originally by _mgrankvi_**

___
When using IE9 with a Portlet running under Liferay the TextField content falls down and is only half visible in some cases. Focus may bring the text fully visible or it may not.

Test setup has Vaadin 7.4.7 (same with atleast 7.3.8), Liferay6.2 and IE9 (9.0.8112.16421)

Same problem appears in Vaadin directory (see attachment)

___
 Imported from https://dev.vaadin.com/ issue #18210

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
