### ISSUE TITLE
Grid editor with non-Valo themes

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6833]
**Originally by @tepi**

___
The Grid editor row looks quite horrible with any non-Valo theme. Especially Runo and Chameleon are bad, Reindeer is quite ok.

The issue is worst on IE8 but also bad on other browsers.

___
 Imported from https://dev.vaadin.com/ issue #18211

**Comment by TatuLund** [comment]
Legacy themes are part of the compatibility library in Vaadin 8. They are not maintained and provided as is.
