### ISSUE TITLE
Grid gets stuck when toggling column visibility

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6841]
**Originally by @Ansku**

___
In the attached test UI, open the side bar, click to hide the hideable column, then click again to try to make the column visible again. Chrome and IE11 at least freeze before column reappears, haven't tested on other browsers. Doesn't seem to happen if there's only one column. If there's no ?debug the browser doesn't get stuck for nearly as long, but the column still fails to reappear.

___
 Imported from https://dev.vaadin.com/ issue #18227

**Comment by Ansku** [comment]
Tested with 7.7 and 8.6, can't reproduce anymore.
