### ISSUE TITLE
Opening or closing a tree node does not update height on IE8

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6886]
**Originally by @tepi**

___
See com.vaadin.tests.components.tree.TreeWithIcons test in Vaadin.

1. Open the test UI
2. Expand the first node
3. The panel containing the tree does not grow in height (see screenshot)

___
 Imported from https://dev.vaadin.com/ issue #18322

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
