### ISSUE TITLE
Header disappears from Grid

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6903]
**Originally by @amahdy**

___
Open this:

http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/multi-select

- Select a row by clicking on a checkbox.
- Press on keyboard "TAB" button ~10 times.

-*Result** Grid header jumps out of display.
**Expected** The header should stay as a frozen row.

-*Reason** The hidden row tries to gain focus, resulting on forcefully pushing the rows up by one. You can see this clearly if you add a CSS rule to color the checkbox on focus.

There is a discussion about making tabindex=-1 going on here: https://github.com/vaadin/components/pull/36#issuecomment-115161097

___
 Imported from https://dev.vaadin.com/ issue #18347

**Comment by amahdy** [comment]
Still an issue.

**Comment by amahdy** [comment]
Still an issue.

**Comment by amahdy** [comment]
Still an issue.
