### ISSUE TITLE
Vaadin Push & JAAS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6918]
**Originally by @henrikerola**

___
When using a form based JAAS authentication & Vaadin push, the JAAS login doesn't work in the case when Vaadin UI is active in the browser and the application server is restarted. Steps to reproduce:

1. Login to the app so that Vaadin UI is active on a browser tab
2. Restart your server
3. refresh the browser tab, this displays the login form
4. Login and you should see URL like in the browser: http://localhost:8080/SessionTest/auth/PUSH?v-uiId=0&v-csrfToken=1082c8a5-a3fe-4d64-b27f-9cf51d0d9de4&X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=122227eb-8413-43aa-a519-6d718236123d&_=1435622945451 and the Vaadin application is not loading. See the attached screenshot.

I think that Vaadin should detect the JAAS login in this case and redirect to http://localhost:8080/SessionTest/auth/ to bootstrap the Vaadin application.

To run the attached eclipse project on a Tomcat, add the following to your tomcat-users.xml:

```
<role rolename="administrator"/>
<user username="admin" password="admin" roles="administrator"/>
```

___
 Imported from https://dev.vaadin.com/ issue #18373

**Comment by chvndb** [comment]
I still have this issue. Any fix to this?

**Comment by chvndb** [comment]
The problem also occurs when the sessions expires. When the user then logs in again, he gets redirected to the PUSH url which is not something the user should be exposed to.

**Comment by elmot** [comment]
As a workaround, I can propose to add a `Filter`, which detects GET requests to push url without `Upgrade: websocket` header and redirect those to the application root.

**Comment by chvndb** [comment]
Thank you for the tip. It seems to work. I added the filter to my security configuration:

```
@Configuration
@EnableWebSecurity
@EnableVaadinSharedSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true, proxyTargetClass = true)
public class ConfigurationSecurity extends KeycloakWebSecurityConfigurerAdapter {
  
  ...

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.httpBasic().disable();
    http.formLogin().disable();
    http.anonymous().disable();
    http.csrf().disable();
    http
        .authorizeRequests()
        .antMatchers("/vaadinServlet/UIDL/**").permitAll()
        .antMatchers("/vaadinServlet/HEARTBEAT/**").permitAll()
        .anyRequest().authenticated();
    http
        .logout()
        .addLogoutHandler(keycloakLogoutHandler())
        .logoutUrl("/sso/logout").permitAll()
        .logoutSuccessUrl("/");
    http
        .exceptionHandling()
        .authenticationEntryPoint(authenticationEntryPoint());
    http
        .addFilterBefore(keycloakPreAuthActionsFilter(), LogoutFilter.class)
        .addFilterBefore(keycloakAuthenticationProcessingFilter(), BasicAuthenticationFilter.class)
        .addFilterBefore(concurrentSessionFilter(), ConcurrentSessionFilter.class)
        .addFilterAfter(new FilterPush(), ConcurrentSessionFilter.class);
    http
        .sessionManagement()
        .sessionAuthenticationStrategy(sessionAuthenticationStrategy());
    http.sessionManagement()
        .sessionFixation().migrateSession()
        .invalidSessionUrl("/")
        .maximumSessions(1)
        .maxSessionsPreventsLogin(false)
        .sessionRegistry(sessionRegistry());
  }

  ...

}
```

with `FilterPush` defined as follows:

```
public class FilterPush extends OncePerRequestFilter {
  @Override
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
      FilterChain chain) throws ServletException, IOException {
    String uri = request.getRequestURI();
    if (uri.startsWith("/vaadinServlet/PUSH")) {
      String value = request.getHeader("Upgrade");
      if (value == null) {
        response.sendRedirect("/");
      }
    }
    chain.doFilter(request, response);
  }
}
```

**Comment by chvndb** [comment]
This can be closed as far as I am concerned.
