### ISSUE TITLE
CSRF token - Insufficient entropy?

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6921]
**Originally by _vpbalint_**

___
I looked at the anti-CSRF code of Vaadin and found that the token is generated using UUID.randomUUID():

https://github.com/vaadin/vaadin/blob/5b92ec790e3d3949992275d54ee8ac61ad94c157/server/src/com/vaadin/server/VaadinSession.java#L779

According to the documentation the UUID generated this way is the Leach-Salz type that only meant to provide uniqueness but not randomness. The generated values are basically time dependent, most bits are leaked across users. The exact time of the token generation could be brute-forced, or guessed with good accuracy in some situations (working hours, passive interception of encrypted connections...)

Frankly, I'd be surprised to see an actual CSRF attack against Vaadin even without CSRF protection (in the best attack I found I still had to guess a paintable ID...), but as a defense-in-depth measure I'd suggest to use java.security.SecureRandom.

___
 Imported from https://dev.vaadin.com/ issue #18379

**Comment by Legioth** [comment]
The JavaDocs of `UUID.randomUUID()` that is used for CSRF tokens describe it to use "a cryptographically strong pseudo random number generator", even though it is true that generic UUIDs are easily guessable.
