### ISSUE TITLE
Focus of input in grid cells are stolen

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6924]
**Originally by @amahdy**

___
When I add a text input element into a cell by creating such element and adding it to cell's element in renderer function, that input element cannot keep its focus. Shortly after (almost instantenously) user clicks the input element, it gets stolen, probably by the row selection. The problem persists in all possible selection-modes.

Copied from: https://github.com/vaadin/components/issues/31

Reproduction code:

```
    public Grid GridRendererSample() {

        Grid grid = new Grid();
        grid.setSizeFull();

        grid.addColumn("Test", String.class).setRenderer(new HtmlRenderer());

        grid.addRow("<input type='text' value='test 1' />");
        grid.addRow("<input type='text' value='test 2' />");
        grid.addRow("<input type='text' value='test 3' />");

        return grid;
    }
```

-*Steps**
1. Click on any input text.
2. Try to type anything using the keyboard.

The focus is lost but not very well seen because of the valo theme.

___
 Imported from https://dev.vaadin.com/ issue #18393

**Comment by amahdy** [comment]
Still an issue.

**Comment by tsuoanttila** [comment]
This works as intended. If you want to have a meaningful `Widget` in a `Grid` you should write a custom `WidgetRenderer` that will make the `input` a `Widget`. Grid is instructed not to mess with `Widget`s, and the `HTMLRenderer` is intended to be used for simple things like formatting a piece of text with `<b>`.

I don't really even get the use-case of the original ticket as those inputs will never tell anyone that you actually changed the value, nor will they persist when scrolling the Grid.

**Comment by amahdy** [comment]
To respond to the use case question: It was an issue in `vaadin-grid` and debugging it lead to finding the main issue in GWT Grid.
