### ISSUE TITLE
Unmanaged Client Side Exception when detaching grid with details opened

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6937]
**Originally by _Serge_**

___
When detaching a grid where a detail has been opened, the detach raised in exception and client side process is hanging. This generate a situation where the client is not in sync anymore with the server side.

The error message is only displayed in debug mode in the chrome browser.

Sample code is attached, just click on one line in the grid in order to open the detail, and then click the button in the right panel. The left panel turns blank instead of displaying a message. 

Code runs correctly if the details are not displayed.

Seems that an assert exception is raised from the Flyweight code.

___
 Imported from https://dev.vaadin.com/ issue #18426

**Comment by lrozenblyum** [comment]
I couldn't reproduce the original issue in 7.7.6. However in current Vaadin there are similar issues related to open details, removal of rows etc, I'll try to generate simple test cases.

**Comment by Legioth** [comment]
@lrozenblyum Thank you for investigating! I'll close this issue since it seems like it's no longer relevant. Please open a new issue if you have a test case for something similar.
