### ISSUE TITLE
Support using client side timeout for push

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6939]
**Originally by @Artur-**

___
The default client side timeout in Atmosphere was disabled in #13015 as there is no support for handling the timeout event on the client side. 

___
 Imported from https://dev.vaadin.com/ issue #18429

**Comment by TatuLund** [comment]
For setting time out in LONG POLLING mode pushLongPollingSuspendTimeout servlet parameter was introduced in Vaadin 7.6 https://vaadin.com/docs/v8/framework/articles/ConfiguringPushForYourEnvironment.html#what-can-you-do-to-avoid-this
