### ISSUE TITLE
[upload] Upload does not fire events if same file name is uploaded

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6989]
**Originally by _spungin_**

___
Using Chrome-Latest

I have an upload component in immediate mode, and there is a combo on my form that lets me choose the destination.

If I select a destination, then select a file to upload, the operation succeeds.

If I then change my destination and reselect the same file, the upload component does not receive any events whatsoever.  If I rename my file and select it, the upload it works.  It seems the browser or the client code is caching the last uploaded filename and refusing to resend it. 

Solution 1:  If the API had a 'clear' or 'reset' method, I would call it.
Solution 2:  Reset the control after a successful upload, or provide an option to do so.

Workaround.  After uploading, replace the upload component with a new one.

___
 Imported from https://dev.vaadin.com/ issue #18500

**Comment by Ansku** [comment]
Fixed in Vaadin 8.3.0.beta2
