### ISSUE TITLE
NPEs should not be thrown explicitly for illegal arguments

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#699]
**Originally by @hesara**

___
Functions such as ContainerHierarchicalWrapper.addItem should not explicitly throw NullPointerException but IllegalArgumentException.

In general, there are no or very few situations where it makes sense to explicitly throw NPE.

___
 Imported from https://dev.vaadin.com/ issue #2791

**Comment by TatuLund** [comment]
This has been mostly implemented by Vaadin 7 & 8 with few exceptions.
