### ISSUE TITLE
Grid editor misalignment when opened by double-clicking a cell partially in view

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6994]
**Originally by @Ansku**

___
Steps to reproduce:
1. Open GridEditorFrozenColumnsUI (you may set frozen column count to 0 as this is not related to those, you just need an editable Grid with a horizontal scrollbar)
1. Double-click the last **partially visible** column
1. Cancel the editing
1. Move the scrollbar enough to get the next column partially visible
1. Double-click the new partially visible cell of the **same row** that you edited in step 2
-> cells in editor will shift so that even the next column is visible, while the rest of the Grid will only shift enough to make the clicked column visible -> misalignment

The area with save and cancel button will shift also, but stay in same position in relation to the editor cells that they would be if the editor cells weren't shifted too much -> the whole area ends up too far left (with some Grid contents to the point of not being visible at all), and there's no background colour on the leftover bit which leaves the Grid row underneath to show through.

If you scroll the grid to the point where the editor and main Grid are again in alignment, editor contents will stay where they are supposed to say for any further scrolling from there on -- until you repeat the original steps again.

This far I have only been able to reproduce this when scrolling to right, double-clicking partially visible cells on the left edge and scrolling a bit more left from there to double-click again doesn't seem to have the same results.

Tested with Chrome 43 on Windows 7, in branches 7.5 and master, and also in a separate project with 7.5.2.

IE11 in master branch already has misalignment with first double-click, and I couldn't reproduce this at all on brief testing with Firefox 39.

___
 Imported from https://dev.vaadin.com/ issue #18506

**Comment by TatuLund** [comment]
Fixed in 7.7.14

**Comment by AlexByte** [comment]
What if I was faced with this in v8?

**Comment by TatuLund** [comment]
Yes, I was actually able to reproduce the issue with Vaadin 8 as well,

I added fix in my Editor alignment bug fixes hot fix collection -> https://vaadin.com/directory/component/grideditorcolumnfix-add-on

**Comment by AlexByte** [comment]
Why these bugs are not fixed in vaadin instead of addon?

**Comment by AlexByte** [comment]
@TatuLund save and close button are still misalignment.

**Comment by AlexByte** [comment]
@TatuLund it didn't fix editor misalignment.  vaadin 8.6.4

**Comment by TatuLund** [comment]
@AlexByte did you use v0.3.1 of the add-on?

> save and close buttons are still misalignment.

Yes, I noticed that, the styles are quite wonkty for that part, I did not yet figure out by quick look how to fix that.

**Comment by AlexByte** [comment]
@TatuLund yes, i try 0.3.1. The problem occurs when you click on the right edge of the table.
