### ISSUE TITLE
Grid classname v-grid-row-focused even without focus

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7002]
**Originally by @amahdy**

___
By default the first Grid row has 'v-grid-row-focused' classname. It's a bit confusing.
Also when you select any item from the Grid and then blur, last selected row retains this classname.

This causes issues especially when styling the grid row based on focused row, the styles and effects are repeated once the grid gains focus again.

___
 Imported from https://dev.vaadin.com/ issue #18521

**Comment by amahdy** [comment]
Still a valid issue u dummy stupid bot!

**Comment by amahdy** [comment]
Still an issue.
