### ISSUE TITLE
Push messages can be lost when a proxy disconnects the connection

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7012]
**Originally by @Artur-**

___
If there is a proxy between the browser and the server and the proxy is using a timeout, it will cause disconnection of the push channel for a brief moment of time until the client has reconnected. If a push happens on the server during this time, it will be pushed into the void as the server has no idea that the connection is no longer valid.

___
 Imported from https://dev.vaadin.com/ issue #18539

**Comment by TatuLund** [comment]
Just noting here, the linked Atmosphere issue has been fixed in the versions used in the newest Vaadin 7.7 and Vaadin 8 releases.
