### ISSUE TITLE
ClientRpc interface does not work as an inner class

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7013]
**Originally by @Legioth**

___
Declaring a ClientRpc interface as an inner class (e.g. in the Connector class) causes a client-side exception when invoking any method from the server. Doing the same with ServerRpc interfaces seems to work without problems.

This is most likely caused by a mixup between Inner.Outer and Inner$Outer naming schemes.

___
 Imported from https://dev.vaadin.com/ issue #18540

**Comment by Artur-** [comment]
Same as #2823
