### ISSUE TITLE
Sporadic ComboBox shadow rendering error in IE8

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7026]
**Originally by @thinwire**

___
When opening Internet Explorer 8 after a restart with a clean cache and starting up a Vaadin test application the first time, on some (apparently rare) occasions ComboBox shadows are rendered incorrectly. This problem goes away when the ComboBox is reopened, and sometimes does not appear at all.
This error shows up occasionally in internal testing, but is currently ignored due to it probably being caused by anything from cache issues, node size being requested and reported before it's actually been recalculated (i.e. IE8 bug) or because of any other reason, including gremlins and leprechauns.

Please reply to this ticket if
a) you identify a valid way to replicate it
b) _YOUR_ tests break because of it 
or
c) you think you know what's going on

The Framework team is currently not actively working on a solution, due to this being a sporadic, purely cosmetic issue.

___
 Imported from https://dev.vaadin.com/ issue #18565

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
