### ISSUE TITLE
Auto-grow for multiline TextField

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#703]
**Originally by @jouni**

___
We could add a feature for textfield that would enabled it to grow when the user types in enough text, so a new line would appear. That would make the need for a scrollbar inside the textfield void.

See Facebook/GetSatisfaction comments for example.

___
 Imported from https://dev.vaadin.com/ issue #2797

**Comment by TatuLund** [comment]
This behavior is part of the[ Vaadin 10+ TextArea](https://vaadin.com/components/vaadin-text-field) component
