### ISSUE TITLE
Write example showing how to extend TextRenderer/HtmlRenderer to show a tooltip.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7030]
**Originally by _basil.bourque_**

___
See [this thread in Forums](https://vaadin.com/forum/#!/thread/9616384/10270495) about people interested in showing a tooltip when user hovers the mouse pointer over a row or cell in a Grid.

I have already filed [Ticket # 17,374](http://dev.vaadin.com/ticket/17374) asking for such a feature to be built-in.

In the meantime, it would be both useful and educational if an example were written to show us end-programmers how to roll-our-own, possibly by extending TextRenderer or HtmlRenderer. But I do not comprehend how to extend a renderer.

As Håkan Arvidsson posted:
--
The concept of custom renderers is documented in the Vaad in book "15.4.1. Renderers".
However I don't understand how to bring the VTooltip class into the picture.

Could you provide a short explanation or a reference where this is documented?
---

___
 Imported from https://dev.vaadin.com/ issue #18578

**Comment by TatuLund** [comment]
This feature is superceded by setDescriptionGenerator(..)
