### ISSUE TITLE
class naming conflicts due to commons-lang3 packaged inside vaadin-client-compiler.jar

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7039]
**Originally by _HermanBovens_**

___
vaadin-client-compiler.jar has commons-lang3 packaged inside it instead of as a dependency.  This would not be a problem if the package had been renamed, but it hasn't.  So the classes in org.apache.commons.lang3 inside the jar conflict with my dependency on a newer version of commons-lang3.

Please fix this, either by adding it as a regular maven dependency or by renaming the package inside the jar (e.g. jarjar can do this).

___
 Imported from https://dev.vaadin.com/ issue #18587

**Comment by TatuLund** [comment]
This should not be a concern with Vaadin 7.7 and newer framework versions. The compiler jars are no-longer transitive dependencies. One just needs to verify that vaadin-client-compiler dependency is imported in compile-scope, and things should work.
