### ISSUE TITLE
Select All feature for Grid cells.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7046]
**Originally by _blanford_robinson_**

___

When entering cells in edit mode on the grid component, it would be helpful if we were given the option to "select all" text on edit.  This would allow for faster data entry.

grid.getcolumn().setSelectAllOnClick(true).

___
 Imported from https://dev.vaadin.com/ issue #18602

**Comment by TatuLund** [comment]
The feature is far from trivial to implement in generic case, since API of the different fields is different. However there is an implementation that works with most common fields provided by GridFastNavigation add-on https://vaadin.com/directory/component/gridfastnavigation-add-on
