### ISSUE TITLE
IE8 first renders TwinColSelect without value incorrectly on Liferay

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7047]
**Originally by @hesara**

___
When a TwinColSelect is first rendered on Liferay with IE8, the height of the right side is rendered as a single row. Adding a value causes the height of the right side to be recalculated correctly, after which removing the value does not break the rendering.

This is only reproducible with IE8 on Liferay (tested with Liferay 6), not e.g. with similar test code and Vaadin "liferay" theme as a servlet.

___
 Imported from https://dev.vaadin.com/ issue #18603

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
