### ISSUE TITLE
Remove unnecessary DOM elements from TwinColSelect and clean up CSS

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#705]
**Originally by @jouni**

___
The button DIV contains one extra decoration DIV that is not used, and it should be removed.

Simplify the CSS as well, currently there are redundant properties applied to at least .i-select-twincol-buttons .i-button.

___
 Imported from https://dev.vaadin.com/ issue #2803

**Comment by jouni** [comment]
Irrelevant, please close.
