### ISSUE TITLE
Give possibility to display rows having different heights in Grid object

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7059]
**Originally by _pdechandol_**

___
Today, the Grid object does not allow to display rows having different heights. This a very common feature, and it's a problem not to be able to do this.
It's possible to use CellGridGenerator and RowStyleGenerator to attribute custom heights to the rows but it breaks the scroll functionality in the grid.

___
 Imported from https://dev.vaadin.com/ issue #18626

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/9355
