### ISSUE TITLE
inline-icon is incorrectly rendered when using inside a FormLayout

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7071]
**Originally by _aaaaa_aaaaa_**

___
Based on the example code provided by oddcully@freenode which can be found at http://pastebin.com/uXgBxsG8

I am trying to create a textfield with an inline-icon based on examples from Valo demo code base, but I am unable to do so.

The inline icon works fine when working with a standalone TextField.

But the problem appears when attempting to use it for a TextField within a FormLayout.

Something similar to that shown in this [[Image(http://i.imgur.com/320qmI5.png)]]

___
 Imported from https://dev.vaadin.com/ issue #18668

**Comment by heruan** [comment]
I confirm it too in Vaadin 8.0, this code:

```java
VerticalLayout verticalLayout = new VerticalLayout();
TextField nameField = new TextField("Name");
nameField.setIcon(FontAwesome.USER);
nameField.addStyleName(ValoTheme.TEXTFIELD_INLINE_ICON);
verticalLayout.addComponent(nameField);
```
produces this correctly:

![screen shot 2016-12-16 at 10 24 59](https://cloud.githubusercontent.com/assets/851745/21257719/ef8686f6-c379-11e6-9f7a-2afbd63ca234.png)

while this code:

```java
VerticalLayout verticalLayout = new VerticalLayout();
TextField nameField = new TextField("Name");
nameField.setIcon(FontAwesome.USER);
nameField.addStyleName(ValoTheme.TEXTFIELD_INLINE_ICON);
FormLayout formLayout = new FormLayout(nameField);
verticalLayout.addComponent(formLayout);
```
produces this:
![screen shot 2016-12-16 at 10 27 16](https://cloud.githubusercontent.com/assets/851745/21257810/4a8c6b60-c37a-11e6-95c5-49bdc5757724.png)

When will this be addressed?

**Comment by marquiswang** [comment]
Verified that this is still an issue in 8.3.2 and copied the issue to #10752

**Comment by dominic-simplan** [comment]
Still occurs in 8.6.3.
Is there any workaround?

**Comment by TatuLund** [comment]
Closing as duplicate

The workaround has been descriped in ticket https://github.com/vaadin/framework/issues/10752
