### ISSUE TITLE
Add Java abstraction for Valo responsive menu

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7137]
**Originally by @Artur-**

___
Using the responsive menu in Valo is really hard, not only because it is not documented but because there are no Java helpers for using it. It should be easy to make an abstraction providing API which is good for most cases.

Needs some research into what the abstraction level should be but something like `new ValoMenu();` `menu.addMenuItem(String text, Resource icon)` should be possible to do to get started easily.

___
 Imported from https://dev.vaadin.com/ issue #18885

**Comment by TatuLund** [comment]
The Java API for Valo menu is available as an add-on in the Directory https://vaadin.com/directory/component/sidemenu-add-on
