### ISSUE TITLE
Text flickering on combobox button in IE10 for long named item

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7143]
**Originally by _artamonov_**

___
We have combobox with long named items, select long named item and move mouse over combobox button. We see text flickering over button.

Reproduced in Vaadin Sampler and in 7.5.5
IE9-IE10

___
 Imported from https://dev.vaadin.com/ issue #18897

**Comment by TatuLund** [comment]
IE9 and IE10 are not supported browsers with Vaadin 8, thus we are closing this as wont fix.
