### ISSUE TITLE
Support adding columns to Grid without modifying the underlying container

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7154]
**Originally by @Artur-**

___
It would be nice to have the possibility to add "generated columns" to Grid, much like you can to with Table, without having to involve a custom container. To add a column with some action buttons today, you have the option of 
1. Selecting a property in the container which you happen not to use, and abuse that property for rendering the actions
2. Wrap the container in a GeneratedPropertyContainer, add a dummy property to it and change Grid to use that container

Another use case is showing data which originates from different properties in the item, e.g. bean contains "firstName" and "lastName", you want to display "name"

With something like a ValueProvider interface, this could be implemented as

{{{
grid.addColumn("name", cell -> {
    Item item = cell.getItem();
    return item.getProperty("firstName").getValue() + " " + item.getProperty("lastName").getValue();
});

___
 Imported from https://dev.vaadin.com/ issue #18922

**Comment by Artur-** [comment]
This is implemented in 8.0
