### ISSUE TITLE
Allow to disable MultiSelectMode.SIMPLE on touch-based devices

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7199]
**Originally by _pazitiffchik@gmail.com_**

___

There is comment in Table.#setMultiselectMode
     - Note, that on some clients the mode may not be respected. E.g. on touch
     - based devices CTRL/SHIFT base selection method is invalid, so touch based
     - browsers always use the {@link MultiSelectMode#SIMPLE}.

But there are laptops with touch screen. On this devices ctrl/shift base selection is valid. 
I have desktop only application and table with multiselect mode. 
And users on laptops with touch screen have some problems with using tables. 

Is there a way to force using MultiSelectMode.DEFAULT mode for all users?

___
 Imported from https://dev.vaadin.com/ issue #19032

**Comment by TatuLund** [comment]
Fixed by https://github.com/vaadin/framework/commit/a723b85680fe28082c9740c3ae26624b9b772d98

**Comment by TatuLund** [comment]
Duplicate of https://github.com/vaadin/framework/issues/11601
