### ISSUE TITLE
Favicon not working in IE9 (via HTTPS)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7216]
**Originally by _lrozenblyum_**

___
Favicon doesn't work in Vaadin in IE9 when served via https.

It is not shown in browser title. However the request for it is sent and the icon is received if we check the network activity

Loading via http works fine.

Maybe related (or has common cause) to #14109

___
 Imported from https://dev.vaadin.com/ issue #19078

**Comment by lrozenblyum** [comment]
The same bug is reproduced in IE11 as well.

**Comment by TatuLund** [comment]
IE9 is not a supported browser with Vaadin 8 and thus we close this as won't fix.
