### ISSUE TITLE
Failed to load bootstrap.js

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7220]
**Originally by _gopinathpatro_**

___
Intermittent but more often we are seeing the below issue while accessing our application.

Failed to load the bootstrap javascript: ./VAADIN/vaadinBootstrap.js?v=7.5.4

After this the page goes blank..

Is this a known issue to vaadin? 

___
 Imported from https://dev.vaadin.com/ issue #19091

**Comment by basil-bourque** [comment]
I too am seeing the following error message, on my existing project, and then again an brand-new Vaadin 14 project created on the "Start a new project with Vaadin" page.

>localhost:8080 says

>Failed to load the bootstrap javascript: ./VAADIN/vaadinBootstrap.js?v=8.9.1
