### ISSUE TITLE
Calendar: first day of week changes when changing week

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7253]
**Originally by @alvarezguille**

___
Happens when using the week navigation arrows '<' '>' with a Locale that is not the system Locale.

```
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        layout.setMargin(true);
        setContent(layout);

        setLocale(Locale.GERMAN);
        Calendar calendar = new Calendar();
        calendar.setSizeFull();
        calendar.setLocale(Locale.GERMAN);
        layout.addComponent(calendar);
    }
```

Tested with a clean new project created with archetype using:
- Java version: 1.8.0_40
- Vaadin version: 7.5.7
- Default locale: en_US

To reproduce:
- Open UI (first day is monday)
- Navigate to next week (first day is monday)
- Navigate to previous week (first day is sunday)

**Comment by aydincan** [comment]
We are also experiencing the same issue and I am using the version 7.7.10 :/
