### ISSUE TITLE
Video tag's poster attribute should not be rendered when a poster resource is not given

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7261]
**Originally by _myucel_**

___
When a poster resource is not given to Video component, poster="null" is rendered in html 5 video tag. It causes unwanted requests to server such as /app/null. Since poster attribute is optional, I think, it shouldn't be rendered whenever it isn't provided explicitly.

___
 Imported from https://dev.vaadin.com/ issue #19178

**Comment by hesara** [comment]
Fixed in 7.7 branch, picked to master in #9797.

**Comment by hesara** [comment]
V8 fix will be in 8.1.2
