### ISSUE TITLE
ImageRenderer should support font icons

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7278]
**Originally by @tmattsso**

___
the API for ImageRenderer supports Resources, and font icons are resources. Right now this combination just fails.

___
 Imported from https://dev.vaadin.com/ issue #19214

**Comment by TatuLund** [comment]
Font icons can be rendered using HtmlRenderer easily, see below an example of rendering check mark based on boolean property "something" of the bean

`    grid.addColumn(bean-> (bean.isSomething() ? VaadinIcons.CHECK_CIRCLE : VaadinIcons.CIRCLE).getHtml(), new HtmlRenderer()).setCaption("Checked");
`

**Comment by TatuLund** [comment]
Closed as duplicate for more generic ticket #7019
