### ISSUE TITLE
FileUploadHandler.cleanStreamVariable throws NPE if file upload component is not attached to UI during HTML5 dnd upload

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7289]
**Originally by @peterl1084**

___
During file upload with HTML5 based dnd a StreamVariable is needed that should be cleaned up after the upload. There is a problem in very special case where cleanup of StreamVariable will throw NullPointerException as it assumes that the upload component is still attached to the UI.

Please have a look com.vaadin.server.communication.FileUploadHandler:456 where cleanStreamVariable is called. Internally it will attempt to find the UI from connector but if during the file upload finishing or failure events the component becomes detached the UI will never be found resulting in NPE on line 693 (getConnectorTracker)

The (quite limited but annoying) special case is triggered with following steps:

1) DragAndDropWrapper with some component is added to Vaadin Window
2) HTML5File is acquired from WrapperTransferable via getFiles Transferable
3) StreamVariable is added to HTML5File
4) In StreamVariable's streamingFinished or streamingStarted methods the Window in which the DNDWrapper is, is closed.
5) Once the window is closed the current upload component is no longer attached to UI resulting the cleanup that happens AFTER streamingFinished method being called to fail as it tries to find the ui of upload component in cleanStreamVariable:693 which is invoked AFTER the invocation to finish method has returned.

Proposals to fix this:
1) Don't close the window after file upload, trivial but sometimes its required for UX
2) Change firing the finished event AFTER cleanup
3) Make another event in addition of finished event which is fired after cleanup
4) Change cleanStreamVariable:693 to lookup the UI with UI.getCurrent()

___
 Imported from https://dev.vaadin.com/ issue #19231

**Comment by ZheSun88** [comment]
Fixed with https://github.com/vaadin/framework/pull/11630
