### ISSUE TITLE
Add setWrapEnabled() to Grid columns.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7290]
**Originally by @TatuLund**

___
Sometimes the column label can be much longer than the width required to represent the data. In that kind of cases it would be beneficial to have API to control text line wrapping in the header. The API could be named e.g. setWrapEnabled. Currently this can be done by workaround using HTML in the header, but that is complicated.

___
 Imported from https://dev.vaadin.com/ issue #19232

**Comment by TatuLund** [comment]
GridExtensionPack is satisfactory implementation of this, hence closing.
