### ISSUE TITLE
TwinColSelect broken in single select mode

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7291]
**Originally by @jojule**

___
It still allows selecting multiple items and only occassionally clears the previous selection when adding another item.

Example:
```
        TwinColSelect s = new TwinColSelect("Choose only one");
        s.addItem("One");
        s.addItem("Two");
        s.addItem("Three");
        s.setMultiSelect(false);

        layout.addComponent(s);

        s.addValueChangeListener(e -> layout.addComponent(new Label(
                "Selected: " + s.getValue())));
```

Recording of the above: http://recordit.co/LXjjClfuGI

___
 Imported from https://dev.vaadin.com/ issue #19236

**Comment by TatuLund** [comment]
This has been fixed by removing setMultiSelect(); in Vaadin 8.
