### ISSUE TITLE
Add an annotation to mark a field as ignored when resolving a declarative layout class' fields.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7292]
**Originally by _spungin_**

___
I have several fields in a declarative layout that need to be initialized in a lazy fashion;  They are not declared in the html.  Vaadin throws an exception because the fields are null.

My solution is to add an annotation marking the rendering engine to ignore them.

___
 Imported from https://dev.vaadin.com/ issue #19237

**Comment by downdrown** [comment]
anything new about this? last activity was about 1 year ago... i think this would be pretty awesome!
will it be available in v7* ? because i work in a project which I cannot update to v8 currently...

**Comment by VictorPhilipp** [comment]
Still no support for this?
