### ISSUE TITLE
Vaadin Grid blinking effect

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7299]
**Originally by _lrozenblyum_**

___
When a Grid with setSizeFull is loaded into a Layout with setSizeFull, an effect occurs : Grid has size = part of browser and then it's resized to full size.
The problem starts to appear in 7.5.9 (unable to reproduce in 7.5.8).

The visual effect is especially annoying when the Grid contains a lot of columns & rows.

Example of code attached

___
 Imported from https://dev.vaadin.com/ issue #19248

**Comment by lrozenblyum** [comment]
The bug is returned again somewhere between 7.7.1 and 7.7.6.

In 7.7.1 the grid worked well, in 7.7.6 the issue is again here.

**Comment by Artur-** [comment]
Can't see any flickering with 7.7.6. This should have been fixed by #7815
If you compare http://test.vaadin.com/7.7.0/run/GridBasicFeatures?theme=valo&restartApplication with http://test.vaadin.com/7.7.6/run/GridBasicFeatures?theme=valo&restartApplication you can see the difference.

**Comment by lrozenblyum** [comment]
I'll need to create a minimal test case then - since in our application this effect is again here after upgrade to 7.7.6
