### ISSUE TITLE
Button in table does not immediately become visible on button.setVisible(true)

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7302]
**Originally by _seebass_**

___
We have a table displaying buttons in one column. The buttons are automatically set visible or invisible when some bean property changes. button.setVisible(false) works fine, button.setVisible(true) does not. The button only becomes visible after some other operation is executed, e.g. sorting or scrolling.

There is a workaround: when executing button.setVisible(true) also execute button.getParent().markAsDirtyRecursive()

See attached example.

___
 Imported from https://dev.vaadin.com/ issue #19255

**Comment by cdir** [comment]
We just had the same problem in our application. Due to our framework approach it is not easily possible for our implementers to use the suggested workaround.

**Comment by TatuLund** [comment]
I analyzed the test application. Our understanding is that this is not a bug. After Button visibility has been changed you need to call table.refreshRowCache() to force the updates.

```
	public void init(final VaadinRequest request) {
		Table table = new Table();
		table.addGeneratedColumn("visible", new ButtonColumnGenerator());
		final BeanItemContainer<Bean> beanItemContainer = new BeanItemContainer<Bean>(Bean.class, Collections.singleton(new Bean()));
		table.setContainerDataSource(beanItemContainer);
		
		Button toggleButton = new Button("toggle visibility");
		toggleButton.setSizeFull();
		toggleButton.addClickListener(new Button.ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				List<Bean> beans = beanItemContainer.getItemIds();
				for (Bean bean : beans) {
					Property<Boolean> itemProperty = beanItemContainer.getItem(bean).getItemProperty("visible");
					itemProperty.setValue(!itemProperty.getValue().booleanValue());
				}
				// This was missing in the test app
				table.refreshRowCache();
			}
		});
		
		VerticalLayout layout = new VerticalLayout();
		layout.setSizeFull();
		layout.addComponent(toggleButton);
		layout.addComponent(table);
		
		setContent(layout);
	}
```
