### ISSUE TITLE
Implement an efficient in-memory container for selection components

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7303]
**Originally by @hesara**

___
Most selection components (ComboBox, NativeSelect, Select, OptionGroup, ListSelect and TwinColSelect) by default use an IndexedContainer if no container is given by the user. As in most item caption modes they only need item IDs, this is very inefficient especially in terms of memory usage.

There should be a low memory-footprint container that can be used as the default backing container for such selection components.

___
 Imported from https://dev.vaadin.com/ issue #19256

**Comment by Legioth** [comment]
Not relevant any more with Vaadin 8.
