### ISSUE TITLE
Allow FileDownloader update components state before files download

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7305]
**Originally by _smolarek999_**

___
I have a use case where I have a table with check boxes and button to download a selected files. Unfortunately FileDownloader are updating component state just after file download. It means that during first click it is using old selection to do the download. 

One possible workaround is to make check boxes immediate, however it requires server round-trip call for each selection. It may be annoying for end-users and it increase network usage.

It will be beneficial to allow FileDownloader to first update state, and then request download. Currently it is possible but require hack, with hidden button. See http://stackoverflow.com/a/33692495/1344546

___
 Imported from https://dev.vaadin.com/ issue #19261

**Comment by pleku** [comment]
We're not looking for changing this behavior anymore in Vaadin 7, it does already work like this in Vaadin 8.

Closing this as _won't fix_.
