### ISSUE TITLE
Typo in book of vaadin

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7308]
**Originally by _jnash67@yahoo.com_**

___
On p286 in Browser Compatibility of CssLayout it has "stregth" instead of "strength".

___
 Imported from https://dev.vaadin.com/ issue #19264

**Comment by Legioth** [comment]
Not relevant anymore: https://github.com/vaadin/framework/search?utf8=%E2%9C%93&q=stregth&type=
