### ISSUE TITLE
Use array instead of switch case in Json conversion in class JsonPaintTarget

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#732]
**Originally by _jpirinen_**

___
In class JsonPaintTarget lookup array of escaped Json characters is used instead of switch case. Where possible, generics are used, Stringbuffers are replaced with Stringbuilders and Vectors with Lists.

___
 Imported from https://dev.vaadin.com/ issue #2876

**Comment by KyleRogers** [comment]
StringBuffer has already been replaced with StringBuilder. Stack/Vectors have been replaced with ArrayDequeue in Vaadin 8. Generics have been introduced. Patch cannot be applied out-of-the box.

Only change open is replacing switch-case with lookup array. But I doubt this will improve performance. Maybe some benchmark has to be made. Not shure whether this is an issue at all. I ~think~ this can be closed but someone else needs to approve.

**Comment by hesara** [comment]
I'd agree with KyleRodgers' evaluation - if this is to be optimized, we should start with new profiling rather than the obsolete patch.
