### ISSUE TITLE
Grid: wrong occurence of horizontal scrollbar

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7332]
**Originally by _Marcel Hallmann_**

___
Hi,

when I add soome rows to my grid the vertical scrollbar occurs - that's fine.

But: I would expect that the columns will use a bit less space to equalize the width of the scrollbar, but instead a horizontal scrollbar occurs - which is very very uggly.

You can see the same effect in the vaadin sampler:
1) go to http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features
2) enter "as" in the filter field - nothing matches, so the table is empty
3) reduce the visible columns (only tha last 3 should left)
4) now remove the "as" from the filter field

You will see that the grid is filled and the vertical scrollbar occurs.

Now use the mouse to reorder 2 columns - everything is as expected now!

___
 Imported from https://dev.vaadin.com/ issue #19320

**Comment by Ansku** [comment]
Fixed by #12058
