### ISSUE TITLE
HorizontalLayout width calculated wrong in Grid details row on IE8 & IE9

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7337]
**Originally by @Ansku**

___
100% wide HorizontalLayout doesn't cover much more than content width in IE8 and IE9 when set within a Grid details row.

___
 Imported from https://dev.vaadin.com/ issue #19326

**Comment by TatuLund** [comment]
IE8 and IE9 are not supported browsers with Vaadin 8, thus we are closing this as wont fix.
