### ISSUE TITLE
See if we can take advantage of the new displayName property in WebKit JS debugger

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#734]
**Originally by @jouni**

___
Profiling would be a lot more efficient, if we could use the newly added displayName property, that is supported at least in current WebKit nightlies.

See this blog post for a better explanation: http://www.alertdebugging.com/2009/04/29/building-a-better-javascript-profiler-with-webkit/

___
 Imported from https://dev.vaadin.com/ issue #2885

**Comment by jouni** [comment]
Seems irrelevant. Please close.
