### ISSUE TITLE
Refactor Sizeable interface

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#742]
**Originally by @Artur-**

___
## To consider
 - Should undefined be replaced by auto
   - WYSIWYG calls it auto and it feels more natural

## Refactoring proposal
 - Create a Unit enum which contains all available units and their CSS representation 
  - PIXELS,PERCENTAGE,EM, ...
 - Create a UnitValue class
  - Contains a value (float) and the unit (Unit)
  - Enables the usage of symmetric getters and setters: UnitValue getHeight(), setHeight(UnitValue)
  - Add convenience methods for creating UnitValue objects
   - public static UnitValue PIXELS(float value), PERCENTAGE(float value) etc
   - Can then write layout.setWidth(UnitValue.PIXELS(500));
   - Leave setWidth(String) in place so setWidth("500px") still works.
  - Make UnitValue immutable so the same unit value can be referenced from many places
   - Can then add a static UnitValue.UNDEFINED and user can write: layout.setWidth(UnitValue.UNDEFINED);
  - Contains method for converting the UnitValue to its CSS representation, preventing code duplication

 - Modify Sizeable interface
  - Add symmetric getter/setter
   - UnitValue getWidth/getHeight()
   - setWidth/setHeight(UnitValue)
  - Remove old deprecated methods (getWidthUnits(), setWidth(float))
  - Deprecate setHeight(float, int) in favor of setHeight(UnitValue)

 - Add similar getters/setters for top/bottom/right/left in ComponentPosition
 - Add similar getter/setter for split position in SplitPanel

 - Potential incompatibilities and problems
  - Sizeable (and thus AbstractComponent).getWidth()/getHeight() returns UnitValue instead of float. Old getters cannot be deprecated unless we change the name of setter and getter which does not seem reasonable. 
   - Existing code "component.getHeight()" has to be modified to "component.getHeight().getValue()". This is a minor inconvenience as getters are seldom used in normal code.
  - After this change there are two setHeight() methods in Sizeable: setHeight(String), setHeight(UnitValue). This means that null values can no longer be used directly to set the size to undefined e.g. setHeight(null) as this call is ambiguous.
   - Existing code "component.setHeight(null)" has to be modified to one of the following
    - component.setHeight((String)null);
    - component.setHeight("");
    - component.setHeight((UnitValue)null); // IMO this should throw an exception
    - component.setHeight(UnitValue.UNDEFINED); // This would be preferred  

Please comment. The code is trivial to implement, it removes duplicate code and makes the implementation clean.

**Comment by TatuLund** [comment]
Implemented since Vaadin 7.0
