### ISSUE TITLE
TextField does not check null representation for values from server

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#758]
**Originally by @hesara**

___
TextField converts user-entered values to null (in changeVariables) if they match its null representation. However, it does not convert values set by the server.

For instance, if the null representation is an empty string and an empty string has been entered in a database column that is nullable, conversions may or may not happen based on what the user does with the field.

Server-set values could be converted by moving the null representation check from TextField.changeVariables to TextField.getValue .

___
 Imported from https://dev.vaadin.com/ issue #3029

**Comment by asashour** [comment]
I believe this is not relevant for Vaadin 8.

**Comment by elmot** [comment]
Outdated, V6 is not supported anymore
