### ISSUE TITLE
Deprecate Button.STYLE_LINK and include ActiveLink from Sampler to Vaadin

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#759]
**Originally by @jouni**

___
Having a static style for Button causes unneeded complexity most importantly in themes, at least if the theme for button is as complex as it is with Reindeer. The link style is forced to revert all the styles that a normal button uses, which is totally backwards and adds a whole lot of selectors and properties to the button css.

We have a better component for this, the ActiveLink from Sampler.

**Comment by jouni** [comment]
Invalid issue in reality, please close.

**Comment by hesara** [comment]
Use the Link component in these cases.
