### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#775]
**Originally by @emarc**

___
We should support right-to-left languages, such as Arabic.

This at least means that we should provide RTL support in the theme, probably a few other things as well. 

GWT about RTL support:
*"GWT themes also come in RTL (right-to-left) versions to support languages written from right-to-left, such as arabic. To use a right-to-left theme, append RTL to the theme name. <inherits name='com.google.gwt.user.theme.standard.StandardRTL'/>"*

The main problem with this is that we do not currently have anyone that knows a RTL language - help needed for advice and testing.

**Comment by TatuLund** [comment]
Implement a RTL support for client side "helper" widgets https://github.com/vaadin/framework/issues/6226
Implement a RTL support for the simplest Vaadin components https://github.com/vaadin/framework/issues/6227
Implement a RTL support for Vaadin layouts, Window, and Panel https://github.com/vaadin/framework/issues/6229
Implement a RTL support for Vaadin layouts, Window, and Panelhttps://github.com/vaadin/framework/issues/6228

**Comment by TatuLund** [comment]
This work has been continued in Vaadin 14 scope

There is experimental add-on already

https://vaadin.com/directory/component/rtl-mode

Follow the roadmap for further details: https://github.com/orgs/vaadin/projects/1

**Comment by TatuLund** [comment]
This feature has been implemented in Vaadin version 14.3.0.

**Comment by parsa-JPM** [comment]
> This work has been continued in Vaadin 14 scope
> 
> There is experimental add-on already
> 
> https://vaadin.com/directory/component/rtl-mode
> 
> Follow the roadmap for further details: https://github.com/orgs/vaadin/projects/1

This add-on works magically and perfectly Thanks as an RTL community member, but why it wasn't implemented internally? and we have to add an external add-on to take advantage of it.

**Comment by emarc** [comment]
> > This work has been continued in Vaadin 14 scope
...
> This add-on works magically and perfectly Thanks as an RTL community member, but why it wasn't implemented internally? and we have to add an external add-on to take advantage of it.

It was – see the following comment, from one year ago :-)

Here is a blog-post about the topic: https://vaadin.com/blog/localization-gets-an-update-with-right-to-left-rtl-support

**Comment by TatuLund** [comment]
I am closing the ticket to avoid further confusion.
