### ISSUE TITLE
com.vaadin.server.VaadinService#runPendingAccessTasks might skip some of pending tasks

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#7956]
in case of RuntimeException thrown in `pendingAccess.run()` or  `pendingAccess.handleError(exception)`

We need additional try/finally guard there

**Comment by Legioth** [comment]
`pendingAccess.run()` is not the the `run()` method of the `Runnable` passed to e.g. `UI.access`. It's `FutureTask.run()` which runs the provided task and stores any exception in an instance field that is used for throwing when calling `pendingAccess.get()`. No exception handling should thus be necessary there.

The `handleError` call would on the other hand benefit from a try/catch just to be on the safe side.
