### ISSUE TITLE
Bandbox

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#796]
**Originally by @jojule**

___
ZK has a nice widget called Bandbox: "Bandbox allows customizable popup. Like combobox, users click a button to popup a window. Unlike combobox, the popup window could contain any kind of components."

Maybe Vaadin should have something similar?

___
 Imported from https://dev.vaadin.com/ issue #3150

**Comment by TatuLund** [comment]
This has been done as add-on in Directory

https://vaadin.com/directory/component/popupbutton
