### ISSUE TITLE
A com.vaadin.ui.Upload is unable to upload the same file twice in a row

### ISSUE THREAD

**Issue by prlj13** [vaadin/framework#7976]
If you use a com.vaadin.ui.Upload (set to immediate), and select a file it is uploaded.  But when you select the same file again it will not upload.

I purposely made the title identical to [issue 4212](https://github.com/vaadin/framework/issues/4212) because it may be the same issue:
  

If I change the Upload to not immediate I no longer have the issue.

I can recreate the issue using Chrome (v54) and IE (v11), but not Firefox.

I'm using Vaadin 7.5.9

**Comment by Artur-** [comment]
Do you have a test case to share for this? Can't reproduce on Chrome 55 / Mac, Edge/Win10 or IE11/Win10

**Comment by prlj13** [comment]
I can't seem to recreate it with a simple example either.  I must have a problem in my code.

Closing the issue.
