### ISSUE TITLE
SpreadSheet component

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#799]
**Originally by @jojule**

___
Limited implementation of Excel -styled spreadsheet. This is fairly close to Table in idea, but the implementation and user experience would be different. 

See Google Apps spreadsheet or ZK http://zssdemo.zkoss.org/ 

___
 Imported from https://dev.vaadin.com/ issue #3154

**Comment by hezamu** [comment]
This issue can be closed, no longer relevant.
