### ISSUE TITLE
addClickListener not working from external Jar file in 8.0.0.alpha9

### ISSUE THREAD

**Issue by cbmeeks** [vaadin/framework#7993]
So I have two projects.  A "CompanyVaadin" project and a "Demo" project.

The CompanyVaadin project is a collection of UI enhancements, themes, custom components, etc.  Basically, a reusable JAR file that we will use in all of our Vaadin projects.

The Demo project is just a simple demo of the CompanyVaadin features.

Now, we thought about using the newest 8.0.0.alpha9 version.  But when we do, the addClickListener throws an exception of "NoMethodFound" in the external dependency (CompanyVaadin) from within the Demo app.

We're using Java 8 and Tomcat 8, BTW

For example:

**CompanyVaadin.jar**

    public class ResetButton extends Button {
        ...
        @SuppressWarnings("serial")
        private void setDefaults() {
            components = new ArrayList<>();
            if (getCaption() == null || getCaption().equals(""))
                setCaption("Reset");

            addClickListener(
                (ClickListener) clickEvent -> ResetButton.this.reset()
            );
        }

        private void reset() {
            if (components == null || components.isEmpty()) return;
            for (Component component : components)
                resetComponent(component);
        }
        ...
    }

**DemoApp.war**

            ResetButton resetButton = new ResetButton("Reset");

This crashes with the following exception:

    java.lang.NoSuchMethodError: com.company.vaadin.components.action.ResetButton.addClickListener(Lcom/vaadin/ui/Button$ClickListener;)Lcom/vaadin/shared/Registration;
	at com.company.vaadin.components.action.ResetButton.setDefaults(ResetButton.java:85) ~[Company-Vaadin-1.0.2-SNAPSHOT.jar:na]

Rolling this back to Vaadin 7.7.3, the exact same code works fine.

Line 85 points to the addClickListener method.

I have also tried removing the actual code INSIDE the addClickListener method but it still crashes.

BTW, I've made sure the Vaadin version is exactly the same in both projects.

Also, I cannot seem to find the docs for version 8 alpha9.  For all I know, addClickListener may not be valid anymore.

**Comment by hesara** [comment]
As the return type of the addClickListener method has changed from void to Registration, old calls to it are source compatible but not binary compatible. Therefore, your CompanyVaadin JAR needs to be recompiled against Vaadin 8 for this to work.

The sources are in *-sources JARs in the same repository as the binaries and javadocs in *-javadoc JARs, so if your IDE is configured to fetch these from Maven, it should be able to show both the javadocs and the sources.
