### ISSUE TITLE
Microsoft Edge 38.14393.0.0 on Windows 10 does not render the circle and checkbox marks in TodoMVC example

### ISSUE THREAD

**Issue by macjuan** [vaadin/framework#7995]
Step to reproduce:

1) Open up Edge browser on Windows 10 machine
2) Navigate to framework8.app.fi
3) Click on TodoMVC
4) Add one todo line by entering the todo topic and pressing enter

Expected result:
New todo-line with circle component, text component

Actual result:
New todo-line without circle component but only with entered text component

Otherwise things work, clicks register and are handled properly as one can "press" on the circle to get strikethrough effect to the "done" item in the list.

**Comment by macjuan** [comment]
Same issue can be found with Internet Explorer 11 as well -> something fishy with how this component is rendered with Microsoft browser core.

**Comment by Legioth** [comment]
The demo has some custom CSS that apparently doesn't work in Microsoft's browsers.
