### ISSUE TITLE
Deleting an item in a grid has a sync issue on Chrome even after reset in 7.7.5

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#8011]
I manually delete the selected rows in the grid using:

```
for(Object selectedItem: grid.getSelectedRows())
    grid.getContainerDataSource().removeItem(selectedItem);

grid.getSelectionModel().reset();
```

According to the Vaadin documentation you need to call reset() on the selectionModel so that they are in sync, and that's great.

This all works great but only if I scroll down the grid with the mouse in the browser, so that the whole grid moves. If I don't scroll the grid in my browser then the mouse selects the wrong row by the exact number of rows that were previously selected before that row. So if I select row 2 and then delete it, then select row 3 it will in fact select row 4. If however I scroll down so that the grid view is refreshed then everything works exactly as expected and the correct row is selected.

**Comment by Artur-** [comment]
Is this a problem only for multiselect?

**Comment by FollowSteph** [comment]
I can confirm it's an issue with the multiselect, I never checked the single select. That being said if you've already fixed it then this is great to hear!
