### ISSUE TITLE
Adding Caption on or hiding Layout above Grid removes Grid Details

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#8015]
Vaadin version: 7.7.6
Scenario: a Grid with a DetailsGenerator placed on a VerticalLayout on a parent VerticalLayout. The parent layout also contains other child Layouts before the Grid. The Details element of one of the Grid's rows has been expanded. 

If you now do one of the following:
* Add a caption to the VerticalLayout that contains the Grid
* Add a caption to the parent VerticalLayout or a Layout that's above the Grid
* Set the visibility of a Layout that's above the grid to false

then the Details element is removed from the Grid. It's even removed from the DOM. 

You can get the Details element visible again by 
```java
grid.setDetailsVisible(itemId, false);
grid.setDetailsVisible(itemId, true);
```

Test project:
[grid-details-test.zip](https://github.com/vaadin/framework/files/656735/grid-details-test.zip)

**Comment by OlliTietavainenVaadin** [comment]
Addenum: setting the detailsVisible to false and true only works after the server round-trip.

**Comment by Legioth** [comment]
This is most likely a triggered by https://github.com/vaadin/framework/issues/7713, although there's apparently also some issues with how `Grid` behaves when being reattached.
