### ISSUE TITLE
Client side exception when removing a column

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8057]
With 8.0.0.beta1, it is not possible to remove a column from Grid.

To reproduce:
1. Open test called "GridBasics"
2. Select "Columns" -> "Column 0" -> "Remove"

**Comment by caalador** [comment]
Closing issue as it's the same as #493

**Comment by Artur-** [comment]
"PopupPanel placed on Table causes Out of sync" ?

**Comment by caalador** [comment]
Was supposed to point to the framework8-issues#493
