### ISSUE TITLE
`Grid.Column` ignores `caption` c'tor argument

### ISSUE THREAD

**Issue by christoph-frick** [vaadin/framework#8063]
- Vaadin version : 8.0.0.beta1

- Description of the bug : The docs of the constructor of `Grid.Column` suggest the caption will be set.  The `caption` is an agrument to the c'tor.  But the caption is always set to the empty string.

https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L800-L812

**Comment by pleku** [comment]
Grid's caption can only be set with the `Column:setCaption(String)` method. The constructor parameter has been accidentally removed when the caption was removed from the `addColumn` method.

**Comment by christoph-frick** [comment]
@pleku The doc comment still mentions the caption.

**Comment by pleku** [comment]
@christoph-frick oops and thanks, removed that too in #8080.
