### ISSUE TITLE
Remove "Use strict" in vaadinPush.debug.js

### ISSUE THREAD

**Issue by opitscope** [vaadin/framework#8065]
In current Version 7.7.6, the vaadin-push module contains a "use strict;" in vaadinPush.debug.js.

This causes errors in several tools, e.g. phantomJs when running selenium tests, because they try to trace the stack via arguments.caller.callee, which is forbidden in the strict mode.

The issue was already addressed in older versions, as I can see e.g. in comment in vaadinPush.debug.js, lines 41-45  in version 7.5.9.
Please remove the "use strict;" again! )

**Comment by Artur-** [comment]
Looks like the JQuery version of Atmosphere did not have "use strict" but the non-JQuery version has

**Comment by Artur-** [comment]
Created https://github.com/Atmosphere/atmosphere-javascript/issues/213

**Comment by opitscope** [comment]
It might make sense to leave the "use strict" in the productive code, as the atmosphere team denies to remove it in their code. Though, in the debug version of vaadin-push it breaks the tests. Would you mind removing this line in vaadinPush.debug.js, but leave it there for production version?
We need any option to run the tests without the strict js mode.
