### ISSUE TITLE
Add the collapse column capability from Table to Grid

### ISSUE THREAD

**Issue by nnilacqua** [vaadin/framework#8070]
The Vaadin Table has a collapse column capability for hiding or showing columns in a way that is controllable by the user through a gear in the upper right of the table. This is extremely valuable for responsive design where you want to minimize the number of columns within a table, while still allowing those columns to be shown through user actions. 

The Vaadin Grid is supposed to replace the Table, however the collapse column capability is not present in it. There is hiding columns for the Grid, which, while useful, isn't controllable by the user, which makes it's usefulness limited in responsive design. 

Please add Collapse Columns to the Grid.

**Comment by pleku** [comment]
That feature has been added to Grid in Framework version 7.5. if I recall correctly.

You can see it in this sample http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features and this is triggerable for Columns with the [Grid.Column.setHidable(boolean)] (https://vaadin.com/api/com/vaadin/ui/Grid.Column.html#setHidable-boolean-) method.

**Comment by bingele28** [comment]
Grid.Column.setHidable only let you hide a column. Restoring the visibility or showing the column again is not possible. From point of usability this is a blocker.

**Comment by tsuoanttila** [comment]
Can you open a new ticket with minimal code example where you see this happening?

**Comment by bingele28** [comment]
Thank you for the response, I wasn't able to recall this thread for an update.
Meanwhile I found that I got the issue while working with Vaadin 8.1.5. After switching to Vaadin 8.3.1 the items stay in the hideable menu. So the column could be hidden and shown again.
