### ISSUE TITLE
Valo theme> 7.5 on larger screens is all scaled smaller

### ISSUE THREAD

**Issue by ghost** [vaadin/framework#8083]
By downloading the Valo theme repository, and bringing it into the IDE (Eclipse, IntelliJ) with identical files, the display is not the same is much smaller and responsive rules are not applied, the 800-1100 rule is no longer met. Testing iMac 21-inch

There are many days that I try to replicate on several big screens, but the effect is always the same, fonts, icons wigted all scaled. I tried to download many repositories, including uitest of Vaadin, but the result is the same. Do you have an idea?

In this image you can see that the rules for responsive tablet are not applied, despite the css has compiled, and this is because everything is resized smaller. The code is identical to that of Vaadin, with the default themes of Vaadin. (https://demo.vaadin.com/valo-theme)
<img width="2048" alt="responsive-not-work" src="https://cloud.githubusercontent.com/assets/20452405/21453496/f040749e-c90f-11e6-94d9-ee164c94e045.png">

<img width="2048" alt="valo-from-repo" src="https://cloud.githubusercontent.com/assets/20452405/21453440/64896758-c90f-11e6-9e7c-52bb3ed1bc58.png">
<img width="2048" alt="original-valo" src="https://cloud.githubusercontent.com/assets/20452405/21453444/6be16488-c90f-11e6-9ff9-2afbba84d737.png">
<img width="2048" alt="schermata 2016-12-23 alle 13 03 28" src="https://cloud.githubusercontent.com/assets/20452405/21453504/0fe7e020-c910-11e6-8772-653cb4e0aab2.png">

The code is the same:
@import "variables";
@import "../tests-valo/valotest";

.tests-valo-dark {
   @include valotest;
}

**Comment by heruan** [comment]
I confirm this in 8.0.0.beta1 (and SNAPSHOT also), running `ValoThemeUI` of the latest `uitests` result is no responsiveness at all.

**Comment by heruan** [comment]
This seems to solve setting `ValoTheme.UI_WITH_MENU` as the primary style name.
