### ISSUE TITLE
Feature: Add previousValue to ValueChangeEvent<V>

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#8087]
Now we can only obtain new value from ValueChangeEvent but not the previous one. It will be very useful for event handling logic to know old value of HasValue<V>.

**Comment by pleku** [comment]
We can add this, but we will also want to make it so that then the `Event.getValue()` will not use `getSource().getValue()`, but instead use a captured value inside the event, that has been captured from the component in the event constructor.
