### ISSUE TITLE
First time page load is taking 2-3 seconds

### ISSUE THREAD

**Issue by charyseqnc** [vaadin/framework#8088]
Hi,
We have a build vaadin application using Vaadin 7.
We used default and spreadsheet widgets in our application. When we load the login page the cache JS file taking 1-2 sec to load and execute.
I have removed spreadsheet widget from widget set but no use.
May I know why that cache js used and why its taking time to load?

**Comment by elmot** [comment]
Hello,
That is gwt nature. By default, all the widgets are compiled to single quite big .js file(widgetset) and that file is mandatory to run any part of your UI.
You can optimize your widgetset. Please refer to https://vaadin.com/wiki/-/wiki/Main/Optimizing+the+Widget+Set
