### ISSUE TITLE
Feature: Extract equals used for previous / new value of AbstractField as AbstractField protected method available for overriding

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#8089]
Now AbstractField uses SharedUtil.equals for old/new value of field and it cannot be overridden.

Some custom fields need to use another comparison rule, e.g. instance equality.

See this [commit](https://github.com/cuba-platform/vaadin/commit/8cf9c11777ce2aa918566f2d94bd497c690950ac) as the example.

**Comment by pleku** [comment]
We can add this, but we will also want to make it so that then the `Event.getValue()` will not use `getSource().getValue()`, but instead use a captured value inside the event, that has been captured from the component in the event constructor.

**Comment by pleku** [comment]
Thanks for the feedback, we will try to do this immediately.
