### ISSUE TITLE
Adding an empty grid causes a client side exception

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8093]
```
layout.addComponent(new Grid())
```

Causes a client side exception in 8.0.0.beta1, contrary to 7.7.6 where an empty grid is rendered
```Caused by: java.lang.IllegalArgumentException: Number of columns can't be less than 1 (was 0)```

**Comment by WoozyG** [comment]
I can't find a way to avoid this when using a declarative design.  I can't add columns to the design, because I want to use a POJO type for data-item-type.  Even adding a dummy column to the grid in the design subclass constructor doesn't help.

**Comment by pleku** [comment]
The original issue this persists, tested with the top of the _master_ branch.

**Comment by elmot** [comment]
I can not reproduce the original issue using _master_ branch anymore. 

@WoozyG, please provide a code example.

**Comment by WoozyG** [comment]
I don't have my test case handy any more, but I'm not seeing issues like this now either.

**Comment by elmot** [comment]
Looks like the issue is fixed
