### ISSUE TITLE
Remove tracking of unregistered connectors

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8111]
e2e2b2c1e8acc2163d117dd8193b7ecc445f4ff8 fixes an issue in `Window` where `Window` did not call `markAsDirty` when closing the window, if a close listener threw an exception. This lead to the client side having the `Window` still visible, while the server had removed it. Clicking again on the close button caused only a warning to be logged on the server side because an RPC (`close`) was received for an already removed connector (component).

To avoid having similar issues for other broken component connectors, c598a852c2565b67226533622b5f75a3b588acf3 changed the handling of RPCs for unknown connectors to do a full resynchronization in addition to logging a warning. This is mainly a workaround for components broken in the same way as `Window` previously was.

53282726c5769bf763beb5d8576c71e0e7b5bef3 introduced a more complex concept of tracking which connectors the client thinks exist when sending a message to the server so that the server can silently ignore RPCs for connectors which have been recently been removed on the server, so recently that the client has not received this info before sending the RPC in question. RPCs for connectors which the client already knows that have been removed still cause a full resynchronization as this indicates a problem in the client side implementation of the component. The remove connectors are stored in a map which is cleaned whenever a message from the client is received as the messages contain a synchronization id telling the server what removals the client has received info about.

5b18c5469e40529fad0d3d014ab4237a56616d81 introduced an `acknowledge` message from the client to the server for pushed updates which include removed connectors, to allow the server to clean up the map where it stores which connectors the client knows have been removed. Failing to send a client -> server request would cause the map where removed connectors are stored to keep growing in size in monitoring style applications, where there is no other client -> server communication.

Now there is still the problem that if the client is disconnected and you update the UI on the server, it will keep tracking which connectors have been removed. As the client is no longer there, there is nobody who will send an `acknowledge` message and map will continue to grow in size until the session expires or the server runs out of memory.

To solve this problem, I suggest we revert all the above patches except for the fix for `Window` and go back to logging a message (with level FINE) when an RPC is received for a connector which is not attached. 

In most cases, this means that the server removed the component and the client did not get the info about it yet. This problem will resolve itself as the client either got the info pushed to it right after sending the RPC, or will get the info in the response for the request containing the RPC.

On the client side, we should add a warning if a connector tries to send an RPC when the client side already knows that the connector has been detached and not send the RPC. This will make it easier to spot broken component implementations.

We could additionally make `setParent` call `markAsDirty` on the old parent connector, which would ensure that the parent is updated whenever a child is removed (which was the original problem in `Window`)

**Comment by pleku** [comment]
Closed by 62c0d73
