### ISSUE TITLE
Implement DateTimeField and InlineDateTimeField

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8132]
Similar to the `DateField` and `InlineDateField` components currently implemented for Framework 8, but with these distinctions
* The server-side value type is `LocalDateTime`.
* Supported resolutions are `SECOND`, `MINUTE` and `HOUR`.
* Reuses the visual design of the components in Framework 7.
* Uses the same stylenames as `DateField` and `InlineDateField`. The assumption is that applications want to have the same looks regardless of whether time selection is used or not. The application developer can still add their own stylenames if they want to do some styling that only applies to one of the components.

Someone might want to fix usability issues in the old components as well, but top priority is to restore the old functionality so that there's a baseline for any potential improvements.

**Comment by Artur-** [comment]
Would these be different components than `DateField` and `InlineDateField`? If so, why?

**Comment by Legioth** [comment]
> Would these be different components than `DateField` and `InlineDateField`? If so, why?

They would be different components because they have different value types. `DateField` implements `HasValue<LocalDate>` whereas `DateTimeField` implements `HasValue<LocalDateTime>`.

**Comment by denis-anisimov** [comment]
It's hard to find common super something for `LocalDate` and `LocalDateTime`........
DateField should be ideally DateFiled<T> where T is either `LocalDate` or `LocalDateTime`.
But how to express this ?

Back to `Date` ? Then just back to compatibility component and nothing to do....

**Comment by denis-anisimov** [comment]
But the point is still correct: it's kind of usability issue to have two DateField for `LocalDate` and `LocalDateTime` just because....
A lot of code duplication as well.

**Comment by Artur-** [comment]
Is it worth it, taking into account that you can get a `LocalDate` from a `LocalDateTime` using `toLocalDate`?

**Comment by Legioth** [comment]
> A lot of code duplication as well.

That depends on how it's internally implemented. I don't see why there couldn't be a generic base type that does all the common stuff and then only the differences are implemented separately for each case.

> it's kind of usability issue to have two `DateField` for `LocalDate` and `LocalDateTime` just because

I see this as similar to the distinction between `CheckBoxGroup` and `RadioButtonGroup` that are mostly similar, but have one key difference.

**Comment by denis-anisimov** [comment]
Good point.
Though if you need `DateTime<LocalDate>` (most popular usecase) then each time you need to do conversation back and forth.
Again: usability issue.

**Comment by denis-anisimov** [comment]
>That depends on how it's internally implemented. I don't see why there couldn't be a generic base type that does all the common stuff and then only the differences are implemented separately for each case.

There will be either a duplication or ugly fragile adaptation code because of differences.
Like a decision what to do with `Resolution` ( and convert it each time).

**Comment by Legioth** [comment]
> There will be either a duplication or ugly fragile adaptation code because of differences.

Sounds like you're the right guy for finding a suitable tradeoff between fragility, duplication and complexity! 😄 

> Like a decision what to do with `Resolution` ( and convert it each time).

There should be separate types in the user-facing API, but the underlying implementation might of course benefit from having a common type (e.g. similar to how numerical identifiers are used in the Framework 7 implementation). It might actually also make sense to rename them to `DateResolution` and `DateTimeResolution` to avoid confusion and import conflicts).

**Comment by denis-anisimov** [comment]
The first round of refactoring: https://github.com/vaadin/framework/pull/8146
