### ISSUE TITLE
Vaadin Push incompatible with jetty 9.4.0

### ISSUE THREAD

**Issue by Corni** [vaadin/framework#8134]
Hi,

both Vaadin 7.7.6 and 8.0.0.beta1 are incompatible with jetty 9.4.0.v20161208, as soon as server push (WEBSOCKET or WEBSOCKET_XHR) is enabled.
As soon as the user loads a UI, they get a session expired message.

I can provide a minimum working example if necessary.

**Comment by Artur-** [comment]
Created https://github.com/Atmosphere/atmosphere/issues/2241

**Comment by Augar** [comment]
Hi!

Is it possible that the recent update for the vaadin atmosphere has triggerd this problem once again?
https://github.com/vaadin/framework/commit/0f08e30f6e735716f6bb4135c22103c2b65911aa
We saw this update has been made to vaadin: 
 <atmosphere.runtime.version>2.4.5.vaadin2</atmosphere.runtime.version>

We are facing an issue regarding Jetty 9.4.x and Vaadin 8.0.3 + 8.0.4
https://vaadin.com/forum#!/thread/15523853

If we use Jetty 9.4.x + Vaadin 8.0.3/8.0.4 and activate the @PUSH annotation we are recieving "Session expired" as soon as we open the website.

If we remove the @PUSH everything seems fine.

Using Vaadin 8.0.2 + @PUSH works fine.
Using Jetty 9.3.x + @PUSH + Vaadin 8.0.3/8.0.4 works fine.

Anybody got an idea on this issue?

**Comment by Augar** [comment]
G'Day

Did a test using 
- Jetty 9.4.5.v20170502
and 
- Vaadin 8.0.5

Same result as with Jetty 9.4.4 -> did not work

**Comment by mvysny** [comment]
Thank you! Using 8.1.0.beta1 with Jetty 9.4.2.v20170220 fixed the Atmosphere/Push issue for me.

**Comment by kolleggerm** [comment]
Will this feature be available for Vaadin 7?

**Comment by elmot** [comment]
@kolleggerm, most probably yes.

**Comment by elmot** [comment]
Oops... I did not know some important details.
The patch most likely is not going to be backported to 7. Please use Vaadin 8.

**Comment by Legioth** [comment]
The main challenge is that the new Atmosphere version requires Java 8. This means that someone would have to identify and backport the fixes related to Jetty 9.4 to an older version of Atmosphere.

**Comment by mvysny** [comment]
What if they are using Vaadin 7.7 with Java 8? Would just upgrading of the atmosphere library work?

**Comment by pinonpierre** [comment]
I don't understand because I tried to use 8.1.0.beta1 with Jetty 9.4.2.v20170220 and it doesn't work for me

Is it solved?

**Comment by jreznot** [comment]
8.1.3 Still does not work with Jetty 9.4.6.v20170531

Works for me with 9.3.20.v20170531

**Comment by pinonpierre** [comment]
Vaadin 8.1.3 works with Jetty 9.4.5.v20170502.

**Comment by lanmaster** [comment]
Vaadin 8.1.3 doesn't work with Jetty 9.4.5.v20170502 on my project.

**Comment by pinonpierre** [comment]
@jreznot, @lanmaster: Can you give us more details because "it doesn't work" is not enough to identify your issue.

FYI, since recently, we need to add 2 dependencies for websockets:

```
		<dependency>
			<groupId>org.eclipse.jetty.websocket</groupId>
			<artifactId>websocket-server</artifactId>
			<version>${jetty.version}</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.websocket</groupId>
			<artifactId>javax-websocket-server-impl</artifactId>
			<version>${jetty.version}</version>
		</dependency>
```
and configure the webAppContext for jsr356 web sockets:


`WebSocketServerContainerInitializer.configureContext(webAppContext);`

**Comment by jreznot** [comment]
Hi,
Check this Gradle project https://github.com/jreznot/electron-java-app
Simply import it using Eclipse / Intellij and start org.strangeway.electronvaadin.Launcher class in IDE
It works perfectly with servlet 3.0 configuration and org.eclipse.jetty.websocket:websocket-server:9.3.20.v20170531

Does not work with 9.4.6.v20170531.

**Comment by lanmaster** [comment]
@pinonpierre Thanks a lot. After adding 
`        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>javax-websocket-server-impl</artifactId>
            <version>${jetty.version}</version>
        </dependency>
`
it works with 9.4.6.v20170531 !

**Comment by jreznot** [comment]
Unfortunately, it still writes to log 
> WARNING: Websocket protocol not supported

And returns 501 error on PUSH endpoint, so actually WebSocket transport still does not work

**Comment by ChristinaSi** [comment]
> and configure the webAppContext for jsr356 web sockets:
> WebSocketServerContainerInitializer.configureContext(webAppContext);

@pinonpierre  Where do I configure this? And what do I have to set in webAppContext? I'm getting the error 
`javax.servlet.ServletException: Not running on Jetty, JSR-356 support unavailable` 
after adding the dependencies for websockets.

**Comment by gnkuzmin** [comment]
Vaadin 12/13 + push (PushMode.MANUAL) with embedded Jetty 9.3.25.v20180904 works right.
With embedded 9.4.15.v20190215 only with Transport.LONG_POLLING.
With other transport: "Session Expired
Take note of any unsaved data, and click here or press ESC key to continue.", "endRequest called when no request is active."
Have I wrong configuration?

**Comment by bihu1** [comment]
@gnkuzmin Did you solve the problem? I'm facing with the same one with Vaadin 23 and I'm searching for solution.
