### ISSUE TITLE
Vaadin 7.7.6 with push incompatible with jetty 9.3.15.v20161220	

### ISSUE THREAD

**Issue by Corni** [vaadin/framework#8135]
Hi,

vaadin 7.7.6 is incompatible with 9.3.15.v20161220 when used with push, as it cannot initialize the comet support class org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.
This can be seen from the logfiles attached, where I start once with 9.3.14 (working) and with 9.3.15 (not working anymore).
[vaadin-776-jetty-9.3.15.log.txt](https://github.com/vaadin/framework/files/682283/vaadin-776-jetty-9.3.15.log.txt)
[vaadin-776-jetty-9.3.14.log.txt](https://github.com/vaadin/framework/files/682282/vaadin-776-jetty-9.3.14.log.txt)

**Comment by Artur-** [comment]
https://github.com/Atmosphere/atmosphere/issues/2242

**Comment by Artur-** [comment]
Fixed in #9359
