### ISSUE TITLE
ServletException when passing invalid values in v-cw, v-ch, v-loc, v-uild parameters

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#8151]
Manipulating request parameters v-cw, v-ch, v-loc, v-uild and changing in invalid input can cause a NumberFormatException when the request is evaluated.

This is reported as a security vulnerability: internal server state is exposed to the client.

Test input: 
URL encoded POST input v-cw was set to acu6960%EF%BC%9Cs1%EF%B9%A5s2%CA%BAs3%CA%B9uca6960

Error message found: java.lang.NumberFormatException: For input string: POST /ccp-1.0.0.1034/?v-1473327650698 HTTP/1.1 Content-Length: 371 Content-Type: application/x-www-form-urlencoded Referer: http://[REDACTED]:8501/ccp-1.0.0.1034/ Cookie: JSESSIONID_8501=1296E345AC0D400C54387CBF6C209DFD; username=WebAdmin2; JSESSIONID_8501=1296E345AC0D400C54387CBF6C209DFD Host: 172.25.43.27:8501 Connection: Keep-alive Accept-Encoding: gzip,deflate User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21 Accept: / theme=basetheme&v-appId=ccp1001034-1240028127&v-browserDetails=1&v-ch=0&v-curdate=147332 7650698&v-cw=acu6960%EF%BC%9Cs1%EF%B9%A5s2%CA%BAs3%CA%B9uca6960&v-dstd=0&v-dston=false&v -loc=http%3A%2F%2F172.25.43.27%3A8501%2Fccp-1.0.0.1034%2F&v-rtzo=-330&v-sh=1110&v-sw=192 0&v-tzo=-330&v-vh=0&v-vw=0&v-wn=javascript%3AdomxssExecutionSink(2%2C%22'%5C%22%3E%3Cxss tag

**Comment by Legioth** [comment]
In what way is the returned exception a security vulnerability? I'm quite sure there are also lots of other ways of triggering server-side exceptions, and I'd say that the solution is to configure the server to not expose any sensitive information when an exception happens instead of blocking anything that might cause an exception.

**Comment by OlliTietavainenVaadin** [comment]
(asked for comment)
