### ISSUE TITLE
The default MultiSelectionModel should not silently have a limit of 1000 elements

### ISSUE THREAD

**Issue by twolf2919** [vaadin/framework#8158]
- Vaadin version: all
- Bug: Vaadin Grid's default MultiSelectionModel only allows for selection of 1000 elements
- If possible, minimal reproducible example: just create a Grid populated with more than 1000 elements, set selection mode to MULTI and select "Select All" checkbox in the header.  When retrieving the selected items, only 1000 are returned.

The behavior is obviously wrong - and insidiously so: a developer who creates a Grid and does not know about the 1000 selection limit will create an application that works incorrectly (e.g. real case: an app whose database contained 4000 "user" rows, and an admin using the Vaadin GUI did "Select All" to notify all users of some important event - only to find later that 3,000 of them hadn't been notified!)

I had a discussion with Ollie about this and his point of view was:
     "I can see your point. It's not a simple choice either way - if you consider the worst case scenario (and the framework must consider it), either the system doesn't work quite as expected, or it fails completely. If you feel that you've got a solid argument for behavior that's acceptable in all cases, please submit a ticket at GitHub".

I understand his point about resource considerations, but a framework, before all other considerations, must be *correct*.  The above behavior is simply not correct.

At a minimum, if the default limit to selection is 1,000 - there should also be a user-visible warning - e.g. instead of simply showing "Select All", it should be something like "Select first 1000" or "Select All*" with some sort of tooltip or other presentation to explain the caveat.  Alternatively, leave the text as "Select All", but bring up a  warning popup when the user does "Select All" and the Grid contains more than 1000 items.  Either way, if the framework has the limitation, it should not be the application developer's job to explain the limitation to the user (especially when he might not even know about the limitation).

With this change in place, the resource constraints are still taken into consideration and the user (and, before then, hopefully the developer) will at least know about the issue.  If the developer knows the limitation he can, if he is willing to accept the resource tradeoff, explicitly create a MultiSelectionModel with a larger (or no!) limit.

**Comment by Legioth** [comment]
We are actually trying out a new approach in Vaadin Framework 8 beta1. We still don't want to have a default setting that might lead to using up all server-side memory by doing a single "Select All" operation on a Grid that is backed by huge amounts of lazy-loaded data. We also want to avoid doing any user-visible indications that would compromise the looks of the component or require texts that would need to be translated to the user's language.

The approach we're trying out is that "Select All" is by default only enabled if Grid is configured to use in-memory data since the selection tracking in that case still uses less memory than the data itself. With lazy loaded data, Grid will simply hide the "Select All" checkbox with the default settings. The application developer can still explicitly enable or disable the checkbox instead of using the default that depends on the type of data. Our thinking is that explicitly enabling the feature in potentially "dangerous" cases would mean that the application developer has a chance of realizing the potential implications.

What do you think about this approach?

**Comment by twolf2919** [comment]
Hi Leif (or is it Legioth - the email notification said the former :-)
I can understand your desire to keep the looks of the component clean - but my second suggestion (warning dialog when they click on the "Select All") does not have that issue.  But you do have a point about warning messages in the framework requiring translations.

I have to plead ignorance about in-memory versus lazily loaded data when it comes to Grid.  I'll assume my usage (I pass Grid a BeanItemContainer that was given a possibly large Collection) is in-memory?  If so, what does "configured" mean?  I don't really explicitly "configure" the grid for in-memory usage.  Anyway, if that's the case, your approach would definitely address my use case.  But for developers who use 'lazily loaded data' - I guess by tying the Grid, somehow directly to a database table - how do you plan on alerting them to the reason why, when they do grid.setSelectionMode(Grid.SelectionMode.MULTI) no "Select All" appears?  I guess the easiest way is via proper javadoc description for that method which gives the above explanation?  Yes, I think that would be sufficient.  Not seeing is definitely better than seeing and getting wrong results upon selection.

On a related subject: why is Vaadin using checkboxes for multiple selection rather than the more direct multi-row selection?  I'm guessing it is because of browser limitations (Grid, unlike some other form widgets, isn't backed by a OS-specific native UI component with shortcut support)?  When I first enabled multi-select, I was surprised to see that extra column - seemed very clumsy to me (I'm an old Swing/desktop developer and sometimes still struggle with the limitations of web UIs :-)

**Comment by twolf2919** [comment]
I just thought of an even simpler variant of your approach: just don't show that column at all - regardless of in-memory or lazily-loaded - if there's more than some MAX_SELECT_ALL rows in the data.  Just as with your approach, the developer would know something's not right when he sets the Grid to MULTI and no column shows up....and then he can, as per the javadocs, increase that max to something that makes sense in his particular machine (and if he sets the max to "infinity", he takes responsibility for the resource issues.

**Comment by pleku** [comment]
Hi. We considered the approach of having the max limit confugable in V8.0 (compared to V7), but decided to instead to just disable it by default for lazy loading data provider. It is possible for the application developer to configure the visibility, depending on what e.g. the size of the data set is.

For V7 however, we might want to do something proposed here to avoid the app developer or end user confusion, when select all is not really select all.

**Comment by Legioth** [comment]
> just don't show that column at all if there's more than some MAX_SELECT_ALL rows in the data.

This approach has the drawback that applications that are not carefully tested with the amount of data used in production might have different behavior during development compared to production use.

**Comment by focbenz** [comment]
How can the "Select All" checkbox with the default setting be shown explicitely with the latest v8 (currently RC2) or will this just be changed for v7 ?

**Comment by pleku** [comment]
@focbenz For 8.0 for in memory data it is visible by default, but for `BackEndDataProvider` you need to explicitly enable it with:
```java
MultiSelectionModelImpl model = (MultiSelectionModelImpl) grid.getSelectionModel(); // note missing generics type
model.setSelectAllCheckBoxVisibility(true);
```

Please do note, that then if the user selects all, all the rows from backend will be fetched into the server side memory.

**Comment by pleku** [comment]
This is quite well hidden, probably we could make it more visible by declaring the method in the `MultiSelectionModel`

**Comment by focbenz** [comment]
Yes - that should make it easier to find.
Also the available options are now with (v8 rc2) defined in an Enum SelectAllCheckBoxVisibility which describes the behavior you already explained in the DEFAULT setting: DEFAULT, VISIBLE, HIDDEN
```
MultiSelectionModelImpl<?> model = (MultiSelectionModelImpl<?>) grid.getSelectionModel();
model.setSelectAllCheckBoxVisibility(SelectAllCheckBoxVisibility.VISIBLE);
```
Since that no longer belongs to this discussion will try and test this with a simple example because I could not get the select all displayed in the application with v8 rc2.
