### ISSUE TITLE
UI constructor cannot have parameters even if a proper UIProvider is registered

### ISSUE THREAD

**Issue by taurus227** [vaadin/framework#8161]
In Vaadin 7.7.6 if I define my UI with a constructor that has parameters and then register a UIProvider which is able to call that constructor, I still get:
```
 com.vaadin.server.ServiceException: com....MyUI doesn't have a public no-args constructor
	at com.vaadin.server.ServletPortletHelper.verifyUIClass(ServletPortletHelper.java:84)
	at com.vaadin.server.ServletPortletHelper.initDefaultUIProvider(ServletPortletHelper.java:159)
	at com.vaadin.server.VaadinService.createAndRegisterSession(VaadinService.java:779)
```

This is because the DefaultUIProvider is registered first and verifyUIClass is invoked on MyUI even if the DefaultUIProvider will never be invoked for MyUI:
[https://github.com/vaadin/framework/blob/7.7.6/server/src/main/java/com/vaadin/server/ServletPortletHelper.java#L159](https://github.com/vaadin/framework/blob/7.7.6/server/src/main/java/com/vaadin/server/ServletPortletHelper.java#L159)

I propose to remove the verification or to defer it until DefaultUIProvider is actually invoked.

**Example**
In the below example I used Guice to instantiate the UI:
```
    @Singleton  
    @VaadinServletConfiguration(productionMode = false, ui = MyUI.class)  
    public class MyServlet extends VaadinServlet implements SessionInitListener {  

        protected final MyUIProvider uiProvider;  

        @Inject  
        public MyServlet(MyUIProvider uiProvider) {  
            this.uiProvider = uiProvider;  
        }  

        @Override  
        protected void servletInitialized() {  
            getService().addSessionInitListener(this);  
        }  
    }

    public class MyUIProvider extends UIProvider {  
        @Inject  
        private Injector injector; 
 
        @Override  
        public MyUI createInstance(UICreateEvent event) {  
            return injector.getInstance(MyUI.class);  
        }  

        @Override  
        public Class<MyUI> getUIClass(UIClassSelectionEvent event) {  
            return MyUI.class;  
        }  
    }  

    public final class MyUI extends UI {
        private SomeService someService;

        @Inject
        public MyUI(SomeService someService) {
            this.someService = someService;
        }
    }

    @WebListener  
    public class Bootstrap extends GuiceServletContextListener {  
        @Override  
        protected Injector getInjector() {  
            return Guice.createInjector(new ServletModule() {  
                @Override  
                protected void configureServlets() {  
                    serve("/*").with(MyServlet.class);
                    bind(SomeService.class).to(MyService.class).in(ServletScopes.SESSION);
                }  
            });  
        }  
    }

    public interface SomeService {
        public void doSomething();
    }


    public class MyService implements SomeService {
        @Override  
        public void doSomething() {
            System.out.println("Hello world!");
        }
    }
```

**Comment by Legioth** [comment]
You can work around this issue by removing the `@VaadinServletConfiguration` annotation from your servlet so that there won't be any `ui` parameter that triggers the creation of `DefaultUIProvider`. This approach does instead have the drawback that you'd might want to provide some other way of configuring other things that are configured through that annotation, e.g. `productionMode`.

We should also reconsider the logic in `initDefaultUIProvider`, but I'm not entirely sure how it should work. The problem is basically that the user would expect a UI class defined in `@VaadinServletConfiguration` or `web.xml` to actually be used, but this won't be the case if instead using some other UI provider that doesn't look at that parameter.

**Comment by taurus227** [comment]
Yes, the logic could be changed in `initDefaultUIProvider()`. As I understand, `DefaultUIProvider` needs to be initialized before any custom `UIProvider`s because of the LIFO handling order. This is fine, but before initializing the `DefaultUIProvider`, there is a check being done in `verifyUIClass()`. That's the check that throws an exception in my case. I don't see why this check needs to be done at this point. The check is only needed if there will be no custom `UIProvider` and based on LIFO the `DefaultUIProvider` is actually invoked. But `DefualtUIProvider` could do any checks necessary when it is actually being invoked. What are we losing by deferring the checks? What am I missing?

**Comment by mcollovati** [comment]
Issue is still relevant on Vaadin 8.3.3
