### ISSUE TITLE
Change setDescription to not render the text as HTML by default

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8185]
`AbstractCompnent.setDescription(String description)` should set the provided text as `innerText` in the DOM.

Also add `AbstractCompnent.setDescription(String description, ContentMode contentMode)` that can be used to explicitly set the text to be used as `innerHtml` in those cases where it's desired.

**Comment by denis-anisimov** [comment]
>AbstractCompnent.setDescription(String description) should set the provided text as innerText in the DOM.

should NOT set ?

>Also add AbstractCompnent.setDescription(String description, ContentMode contentMode)

So two methods ?
What's `ContentMode` ?

There is already `ContentMode` enumeration which is defined in the `com.vaadin.shared.ui.label` package. It contains 3 values: `TEXT`, `PREFORMATTED` and `HTML`. Should it be reused (which means it should be moved to another package) or some dedicated  `ContentMode` enum ?

**Comment by Legioth** [comment]
Should be set as `innerText` (or actually `textContent` which works in all browser). Should not be set as `innerHTML`.

Yes, there would be two methods. One with only one argument that is protected against XSS issues and one that lets the developer explicitly say that the description should be treated as HTML.

It might actually make sense to reuse the `ContentMode` enum that is currently specific for `Label`, and maybe even have `PREFORMATTED` as the default so that line breaks are preserved. Another design alternative might also be a separate boolean setter named e.g. `setDescriptionAsHtml` which would be similar to the already existing `setCaptionAsHtml`.

**Comment by denis-anisimov** [comment]
>Should be set as innerText (or actually textContent which works in all browser). Should not be set as innerHTML.

OK, misread the description, sorry.

I've extracted `ContentMode` from label already.
