### ISSUE TITLE
MenuBarElement: looking up menu items by ID rather than by a caption

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8186]
_From @vaadin-bot on December 1, 2015 11:24_

**Originally by _mvysny2_**

___
Instead of finding menu items by caption, I would consider adding a support for menu items to have developer-defined string ID, and changing the API to looking up menu items by this ID. This also helps if the application may be localized, which causes menu items to different captions based on locale.
This would also solve https://dev.vaadin.com/ticket/16874

___
 Imported from https://dev.vaadin.com/ issue #19327

_Copied from original issue: vaadin/testbench#799_

**Comment by Artur-** [comment]
_From @vaadin-bot on December 1, 2015 13:5_

**Originally by @Legioth**

---

Depends on #11307 in the framework.

**Comment by fante76** [comment]
Hi, any news about this problem?

**Comment by focbenz** [comment]
In our application we use FontIcons in front of the actual captions in the MenuItems. So it is even harder to identify those by captions. Would also very much like to see the ability to set IDs for the items inside the MenuBarElement.

**Comment by AlexWagner** [comment]
Moreover it would be useful if we could add/remove stylenames as in button component.

**Comment by focbenz** [comment]
Please do not stale this ... I think the suggestion to also add and remove stylenames might be good too.

**Comment by cdir** [comment]
I think @Artur- was right labeling this as a bug. I just rold our customers "no problem you get the ID for automated UI tests in a second" and then realize that it is not supported. Realy? This is a bug not an enhancement.

**Comment by TatuLund** [comment]
From Vaadin 8.12.1: if you set the MenuBar id, say "my-menu", the menu items will have generated id's "my-menu-1", "my-menu-2", ...
