### ISSUE TITLE
Problems with shift+arrow navigation in VCalendarPanel

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8196]
_From @vaadin-bot on August 12, 2014 9:25_

**Originally by @Ansku**

___
```
WebElement popupBody = popup.findElement(By.className("v-datefield-calendarpanel"));
new Actions(driver).keyDown(Keys.SHIFT).perform();
popupBody.sendKeys(Keys.ARROW_LEFT);
new Actions(driver).keyUp(Keys.SHIFT).perform();
```
should navigate to the previous month but doesn't work on IE9-11.

___
 Imported from https://dev.vaadin.com/ issue #14406

_Copied from original issue: vaadin/testbench#684_

**Comment by Artur-** [comment]
_From @vaadin-bot on August 12, 2014 9:44_

**Originally by @Ansku**

---

With Keys.ARROW_DOWN this doesn't seem to work for any of the test browsers (should navigate to previous year).

**Comment by Artur-** [comment]
_From @vaadin-bot on August 15, 2014 14:2_

**Originally by @Ansku**

---

The workarounds in PopupDateFieldExtendedRangeTest should also be removed when this one is fixed.

**Comment by hesara** [comment]
Also recent Firefox versions (at least 45) seem to have problems with this, at least in TB tests.
