### ISSUE TITLE
Add functionality for scrolling to a specific row in Grid

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8203]
`Grid` in Framework 8 does currently not have any way of scrolling to a specific row. Similar functionality is implemented for `Grid` in Framework 7.

As previously discussed, `DataProvider` doesn't provide any way of finding the index for a given item, so the API in Grid would have to be based on the index instead of the item.

**Comment by denis-anisimov** [comment]
There is the V7 test for this functionality which should be migrated :
com.vaadin.v7.tests.components.grid.GridDetailsLocation

**Comment by caalador** [comment]
@denis-anisimov Good to know that there is a test and testUI. I'll take that one into account also.

**Comment by denis-anisimov** [comment]
If you are going to implement methods `scrollToEnd`/`scrollToStart` then 
there is also GridFastAsyncUpdate test to migrate.
