### ISSUE TITLE
Initial column widths are not calculated for a Grid inside a split panel

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8210]
Works in 7.7, broken in 8.0. The columns widths jump into place when you start dragging the splitter.

Example code:
```
Grid<String> grid = new Grid<>();
grid.setWidth("100%");

grid.setItems("one", "two", "three");
grid.addColumn(string -> string);

HorizontalSplitPanel splitPanel = new HorizontalSplitPanel();
splitPanel.setFirstComponent(grid);
splitPanel.setWidth("100%");

addComponent(splitPanel);
```

**Comment by caalador** [comment]
@Legioth Can you re-test this on latest. Seems to be fixed, probably with https://github.com/vaadin/framework8-issues/issues/493

**Comment by caalador** [comment]
Tested issue with the Contacts demo and the issue has been fixed there also.

Closing issue.
