### ISSUE TITLE
Remove pointless type parameter from SortOrder from the Query API

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8215]
`Query.getSortOrders()` is currently defined to return `List<SortOrder<String>>`.  The `<String>` part there is completely redundant in this context. The API should be simplified to not expose the type parameter.

**Comment by denis-anisimov** [comment]
So does it mean that `SortOrder` shouldn't be generic at all ?
Or `Query` should be `List<SortOrder<Object>>` based ?

**Comment by Legioth** [comment]
What I care about is that the return type of `Query.getSortOrders()` would look as simple as possible, i.e. `List<SortOrder>`. 

I'm suspecting that all usage of `SortOrder` that we have in the framework is always `<String>`, and in that case the generics could just as well be removed and the class instead changed to use `String` instead of `T`. If there's still some case where some other type is actually used, then we'd have to consider whether it would be worthwhile to use different `SortOrder` to keep the `Query` API simple.

**Comment by denis-anisimov** [comment]
`Grid` uses `SortOrder<Column<T, ?>>`.

So it's not String everywhere. But this class is used by the `Grid` as a DTO.
We either can create another class for this or `SortOrder extends SomeSortOrder<String>`.
