### ISSUE TITLE
prependHeaderRow breaks Grid if grouping only one column

### ISSUE THREAD

**Issue by cbmeeks** [vaadin/framework#8234]
**Vaadin 8.0.0.beta1**

I have a Grid where I am trying to group some header columns.  Grouping two or more cells works fine but attempting to group one column causes the entire grid to not render correctly (in the header).

This works:

        Grid.HeaderRow groupingHeader = grid.prependHeaderRow();

        ....

        Grid.HeaderCell deliveryCell = groupingHeader.join(
                groupingHeader.getCell("destinationName"),
                groupingHeader.getCell("date"),
                groupingHeader.getCell("time")
        );

        Grid.HeaderCell handlingCell = groupingHeader.join(
                groupingHeader.getCell("type"),
                groupingHeader.getCell("quantity"),
                groupingHeader.getCell("weight"),
                groupingHeader.getCell("length"),
                groupingHeader.getCell("width"),
                groupingHeader.getCell("height"),
                groupingHeader.getCell("stackable")
        );

        Grid.HeaderCell expediteCell = groupingHeader.join(
                groupingHeader.getCell("expedite"),
                groupingHeader.getCell("teamNumber"),
                groupingHeader.getCell("buyerName"),
                groupingHeader.getCell("partNumber"),
                groupingHeader.getCell("notes")
        );

Which produces this:

![image](https://cloud.githubusercontent.com/assets/49341/21861508/1c52245e-d803-11e6-8455-bff910bada12.png)

Notice where the red X is.  No headers there.

This, does NOT work:

        Grid.HeaderRow groupingHeader = grid.prependHeaderRow();

        ....

        Grid.HeaderCell deliveryCell = groupingHeader.join(
                groupingHeader.getCell("destinationName"),
                groupingHeader.getCell("date"),
                groupingHeader.getCell("time")
        );

        Grid.HeaderCell handlingCell = groupingHeader.join(
                groupingHeader.getCell("type"),
                groupingHeader.getCell("quantity"),
                groupingHeader.getCell("weight"),
                groupingHeader.getCell("length"),
                groupingHeader.getCell("width"),
                groupingHeader.getCell("height"),
                groupingHeader.getCell("stackable")
        );

        //  Cannot group this column
        Grid.HeaderCell poCell = groupingHeader.join(
                groupingHeader.getCell("poNumber")
        );

        Grid.HeaderCell expediteCell = groupingHeader.join(
                groupingHeader.getCell("expedite"),
                groupingHeader.getCell("teamNumber"),
                groupingHeader.getCell("buyerName"),
                groupingHeader.getCell("partNumber"),
                groupingHeader.getCell("notes")
        );

![image](https://cloud.githubusercontent.com/assets/49341/21861605/956c9fe0-d803-11e6-8a79-0834e9dbf594.png)

The only difference is that I've attempted to group one column.  I admit, it may sound silly to group one column.  But that is what the customer wants.  It's the only column in the grid that doesn't belong to any other group.

I can provide more code if needed.

**Comment by Artur-** [comment]
There is no need to add a single cell to a group, just use the cell without trying to join it with nothing. The bug seems to be that the check in `join` that ensures that at least two cells are joined is just an assert and will thus not be triggered unless you run the server with `-ea`
