### ISSUE TITLE
Provide an API to set a Grid column Renderer after column creation

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/framework#8250]
In Vaadin 8.0.0.beta1 there's no way to set a Renderer to a Grid column that has been already created. This makes it harder to separate creation and configuration logic which is required in some designs.

**Comment by Legioth** [comment]
Could you provide an example of some case where it would be useful to change the renderer after the column has been created?

**Comment by alejandro-du** [comment]
Yes. The Crud UI add-on allows developers to generate a CRUD interface for a domain class. It works by building a Grid (among other components) that includes the required columns. The add-on uses default configurations (captions, renderers, ...) and clients can adjust if needed. For example, clients may want to use a DateRenderer for a certain column (after the column is internally created by the add-on). Moreover, developers may want the end user to be able to adjust the date format at runtime.

**Comment by Legioth** [comment]
The generic types of `Column` might cause some problems for that kind of design, since e.g. `DateRenderer` is only valid for a `Column<ItemType, Date>` but not for a `Column<ItemType, String>`. This means that you'd still need some way of getting something that is typed as a `Date` column without falling back to unsafe casts.

**Comment by OlliTietavainenVaadin** [comment]
There's a slight dev UX downside I just discovered: I added a new column like this:
```
Grid.Column<Bean, Date> dateColumn = grid.addColumn(Bean::getDate);
```
Then I was trying to figure out how to add a Renderer to this new column; there's no way to do that. Of course once I learned that there can be a second parameter in addColumn it's simple, but before I got a hint, I don't know how I should have guessed that.

**Comment by mvysny** [comment]
I also vote for allowing to set the renderer. Currently, when the grid is created using the one-parameter Class constructor, the only way to change the renderer is to delete the column and create it anew.

**Comment by melistik** [comment]
Is also needed for my [vaadin-grid-util](https://github.com/melistik/vaadin-grid-util)

**Comment by phansson** [comment]
As the author of the [ClickableTextRenderer Add-on](https://vaadin.com/directory#!addon/clickabletextrenderer) I can only agree with melistik and others on this topic. I'll put a hold on the upgrade efforts of this add-on for now, but I'll be happy to review my decision once this has been resolved.

**Comment by hesara** [comment]
Fix should also be picked to 8.0 branch (without the 8.1 specific TreeGrid related parts).

**Comment by KasparScherrer** [comment]
The same problem exists in Vaadin Flow, but the method `Column::setRenderer` does not exist here. Is it done in a different way now, or was this feature just overlooked?

**Comment by Legioth** [comment]
The Grid for Vaadin 10+ has a slightly different relationship between the value provider and the renderer which means that this fix can most likely not be used as-is but would instead require a separate implementation.

In Vaadin 8, there is always a value provider and its output is then passed to the renderer. In Vaadin 10+, there is only a renderer which receives the whole row item and then most renderer implementations are internally using a value provider callback for extracting the right value from the item.
