### ISSUE TITLE
Introduce BeanValidationBinder that always uses bean validation

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8253]
The current design of `Binder` is slightly confusing and fragile since it might or might not add JSR 303 validators for its bindings.

We could make `Binder` never add any validators automatically, and then introduce `BeanValidationBinder` that always adds JSR 303 validators and throws a helpful exception from any constructor if there's no bean validation API or implementation on the classpath.

This would help avoid surprises both in the case when bean validation is expected and when it's not expected.

**Comment by Artur-** [comment]
Why is bean validation so special that it warrants a special implementation of `Binder`? Why is it not just a helper method in Binder, e.g. `addBeanValidationToEverything()` or a helper class for BeanValidation e.g. `BeanValidation.addValidation(binder)`?

**Comment by denis-anisimov** [comment]
I would avoid additional classes.

Could be solved as an additional parameter in the Binder's CTOR.

**Comment by Legioth** [comment]
Different behavor – different class.

Any "add" method is problematic since it should preferably also affect fields that are bound later. The semantics could also be "set", but then there would have to be additional bookkeeping in `Binder`.

An additional constructor parameter would instead require an additional class to describe what the parameter does, since e.g. `true` or `false` wouldn't be very explanatory. An additional parameter might on the other hand offer good discoverability.

**Comment by mstahv** [comment]
I don't know what kind of discussion you had about this change, but does this really mean that we don't embrace JSR 303? Having a special class that needs to be used, makes me think it is just a hack clued over some "real solutions". It would look much better in examples (and real code) if it just worked.

If, and only if, it was a real requirement to have it disabled, I'd provide something similar suggested by @denis-anisimov. In most cases I think the disabling JSR 303 validations could be implemented with [groups](http://beanvalidation.org/1.0/spec/#validationapi-validatorapi-groups) (I actually haven't checked if they are now supported, I hope they are).

**Comment by Legioth** [comment]
There hasn't to my knowledge been any other discussion about this change than what's visible here in this ticket. The change was actually supposed to be on the list of things that we should have a discussion about, but it was accidentally taken on as an already decided thing and implemented yesterday.

The idea here is not to avoid embracing JSR-303, but rather that the developer is free to choose whether it will be used or not, and that neither case should require more code than the other.

Requiring the user to set a group to disable validation or requiring an additional constructor parameter would both mean that one of the cases requires some boilerplate that shouldn't really be necessary.

**Comment by mstahv** [comment]
In some cases having a separate class may indeed be good, but not sure if here. I would have just added a flag to disable JSR 303 annotations. The default should be on, if implemented with separate class style, I'd make the special class from the special case (when JSR 303 annotations should be disabled).

**Comment by Legioth** [comment]
> The default should be on.

This is where the problems start. You think it should be on because it's convenient, many others think that "magic" such as JSR-303 should be off by default but still easy to explicitly enable because it makes it easier to understand what an isolated snippet of code does.

This is why I'm trying to find solutions where using magic or not using magic are on equal grounds when looking at the amount of code you need to write (except for variations in the length of names that would be auto completed). In that way, there's no need to have quite pointless arguments that try to find absolute truth from subjective topics.

In this case, I suggested that enabling JSR-303 should be a "special case" implemented by a subclass because it makes naming more obvious. `BeanValidationBinder` is a quite obvious name for a subclass that enables JSR-303 functionality. For the opposite, the only name variations that I could come up with were either based on confusing negations, e.g. `BinderWithoutBeanValidation`, or rather vague, e.g. `ManualValidationBinder`.

Yet another reason for why JSR-303 support should belong in a sub class rather than a super class can be seen by considering what the API would look like after we've added support for validation groups – it would be quite strange if a binder subclass with JSR-303 disabled would inherit a method such as `setValidationGroup(String group)`.

**Comment by denis-anisimov** [comment]
Magic is bad. I definitely agree here.
The only question : should be be the separate class or in the same class (via the CTOR parameter or so). But that's a different question and I'm not so sure.

**Comment by Legioth** [comment]
> should be be the separate class or in the same class (via the CTOR parameter or so)

We will at least need a separate class if/when we add API for configuring the used validation group.

The problem with a constructor parameter is that the non-default case would be more complicated, e.g. `new Binder<>(Person.class, BeanValidationMode.ENABLED)`.

This could be "fixed" by introducing factory methods with different names, e.g. `Binder.create()` or `Binder.createWithBeanValidation(Person.class)`, but those can just as well be introduced with the way it's implemented right now.

**Comment by mstahv** [comment]
Bean Validation is magic? I'd bet that those who consider it magic, don't have the annotations on their classes either. 

Our documentation/tutorials should favour BeanValidationBinder, otherwise it is very hard for people to find it. The configuration option suggested by @denis-anisimov would be much better in that sense.

**Comment by Legioth** [comment]
> The configuration option suggested by @denis-anisimov would be much better in that sense.

Could someone show code examples of what that would look like in practice for these three different cases:
1. Creating a `Binder` that doesn't try to use JSR-303 annotations even if the bean has such annotation.
1. Creating a `Binder` that uses JSR-303 annotations to define validators.
1. Same as 2., but configured to use a specific validation group name.

Please also describe how that approach compares to the currently implemented solution on these criteria:
1. Does someone reading the code have a fair chance of realizing that additional validators will be added based on what's defined in the bean class?
1. What happens if there's no JSR-303 implementation on the classpath?
1. How much boilerplate is necessary in each case?
1. Any other criteria that you consider important.

**Comment by denis-anisimov** [comment]
Bean Validation is magic is not magic.

Magic is the behavior which works differently depending on presence/absence of something in the classpath.
The behavior should be expected.

>Our documentation/tutorials should favour BeanValidationBinder
The documentation should be updated, yes. Not sure that `BeanValidationBinder` should be everywhere but it should be mentioned in many cases.
