### ISSUE TITLE
Problem with Grid and SQLContainer

### ISSUE THREAD

**Issue by swathly** [vaadin/framework#8260]
Hi,

I'm try to add a grid to a page on the Dashboard (I'm not sure Dashboard is related).

[![image.png](https://s23.postimg.org/sw8kllkff/image.png)](https://postimg.org/image/qro7kiisn/)

The image above shows the result. The column are just plain text and the scrollbars are above the grid. When I move the scrollbars it actually move the data below... what is going on? :)

Yoram

**Comment by Artur-** [comment]
Looks like the Grid theme is missing for whatever reason

**Comment by swathly** [comment]
I must have had corrupted default css and/or scss file, after readding the original it works!
