### ISSUE TITLE
Grid: Editor not saving values by pressing Enter

### ISSUE THREAD

**Issue by samuel-os** [vaadin/framework#8266]
There is a bug with Grid editor. It is not saving/comitting the values of the currently edited cell if comitted by pressing the Enter key.
If you tab to the next cell before or use the save button everything works fine.

You can check the behaviour in the attached example.

[sample.zip](https://github.com/vaadin/framework/files/713202/sample.zip)

**Comment by pichlerm** [comment]
I observed the same bug. It seems to occur when some grid columns are hidden. Then pressing the ENTER key in the grid editor stops working for those columns after the hidden ones (behaves like cancel;
pressing ENTER in columns before hidden ones and clicking the "save" button still works).

It happens both when the column is hidden by the program (the column "number" after the "id" my test program VaadingridtestUI.java) and when the user manually hides a column.
[VaadingridtestUI.java.txt](https://github.com/vaadin/framework/files/714033/VaadingridtestUI.java.txt)

The online demo of the grid item editor has no hidable columns, there it works -
http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/item-editor

Vaadin version 7.7.6.

**Comment by cbmeeks** [comment]
I have confirmed this bug with `8.0.0.beta1`.  When I have hidden columns, the enter key does not set the value.  But when I show all columns, pressing enter works as expected.
