### ISSUE TITLE
Grid column default comparator throws NullPointerException

### ISSUE THREAD

**Issue by oflege** [vaadin/framework#8282]
Vaadin version 8.0.0.beta1, Grid.java lines 821 ff
the default Comparator is constructed as

`                comparator = (a, b) -> {
                    @SuppressWarnings("unchecked")
                    Comparable<V> comp = (Comparable<V>) valueProvider.apply(a);
                    return comp.compareTo(valueProvider.apply(b));
                };
`

and will therefore trigger a NPE as soon as the valueProvider returns null; the same applies to the comparator created `if (Number.class.isAssignableFrom(valueType))` a few lines down.

An ideal solution would be to allow the user to specify whether null values should be considered less than or greater than non-null values similar to java.util.Comparator#nullsFirst/nullsLast

**Comment by Legioth** [comment]
Thank you for noticing this. We should definitely fix those to also work for `null` values.

We would still have to choose whether `null` should be first or last if the developer doesn't explicitly specify something. Which alternative would have been more useful in your case, @oflege?

My gut feeling is that we should just pick either as the default but not provide any API specific for overriding the default. I would assume that this is such a rare case that it's acceptable for the developer to instead use `setComparator` with a custom implementation to override the default.

**Comment by oflege** [comment]
for us, nullsLast would definitely be more useful
