### ISSUE TITLE
PopupDateField receives focus even though it is readonly.

### ISSUE THREAD

**Issue by RobertZenz** [vaadin/framework#8295]
The PopupDateField does receive the focus (for example by pressing Tab) even though it has been set to readonly. All other fields do not receive the focus when set to readonly. This is reproducible in the [popup-date-field showcase](http://demo.vaadin.com/sampler/#ui/data-input/dates/popup-date-field).

**Comment by TatuLund** [comment]
The problem does not happen with Vaadin 8.11.
