### ISSUE TITLE
Vaadin 8 Shortcut Keys API reference contains no longer existing AbstractField.FocusShortcut objects.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/framework#8297]
Hello.
I'm using the latest snapshot version of Vaadin 8 framework and currently trying to understand how shortcutListeners are created.
I've opened the [Shortcut Keys](https://vaadin.com/docs8/-/part8/framework/advanced/advanced-shortcuts.html) api reference page and it has a lot of examples mentioning the `AbstractField.FocusShortcut` class.
But I can not find any FocusShortcut class in the framework at all.

Can you please update the documentation?

**Comment by SomeoneToIgnore** [comment]
Duplicates https://github.com/vaadin/framework8-issues/issues/577

**Comment by Legioth** [comment]
https://github.com/vaadin/framework8-issues/issues/577 is about `Grid.select`, this is about `AbstractField.FocusShortcut `. I don't see how that could be a duplicate.

**Comment by eriklumme** [comment]
Still relevant!

**Comment by mstahv** [comment]
Could somebody who designed the new API please fix the documentation? Otherwise it takes a lot of time to get a good overall idea of the new API.

**Comment by Legioth** [comment]
There is a commit for both adding back the accidentally removed functionality and updating documentation in https://github.com/vaadin/framework/commit/316708b487e4c1464002bfdaddb1e0fef358c494, but for some reason no PR has been created for this and it has thus not been reviewed and merged.

**Comment by anasmi** [comment]
@pleku , could you merge master branch into your branch and create a pull request? 
And if not, can I do this?
