### ISSUE TITLE
Grid editor field not firing value change event

### ISSUE THREAD

**Issue by cbmeeks** [vaadin/framework#8299]
We have a grid with the editor enabled.

I'm trying to trigger an event when one of the cells is edited. 

The following code does nothing:

    grid.getColumn("myColumn")
            .getEditorField()
            .addValueChangeListener(
                    event -> Notification.show(event.getProperty().getValue().toString())
            );

After I make a change to the field and click "Save", nothing happens.  The item appears to take the change in the grid but the event is not fired.  I need to hook into this event so that I can run some pre-processing logic and save the entity.

I cannot find documentation on how to do this in Vaadin.

Thanks

**Comment by pleku** [comment]
Just tested with 7.7.7 and for me the ValueChangeListener is triggered when the value has changed. Cannot replicate this with the information provided, please provide more details. Closing as invalid.

You can also get an event from the Grid when the editor is opened, closed, moved and also you can fetch the underlying `FieldGroup` from `Grid` with `getEditorFieldGroup` and add a commit handler to that one.
