### ISSUE TITLE
Merge changes from 7.7.7

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8300]
#8286 needs a multi-module test: one `jar` module containing e.g. `src/main/resources/META-INF/resources/VAADIN/resource.txt ` and one `war` module depending on the `jar` module. The `war` module needs to have a `/*` mapped servlet and probably needs to be run using `mvn jetty:run-war`. Test test should verify that `/VAADIN/resources.txt` can be loaded

**Comment by pleku** [comment]
List of changes in 7.7.7 and actions taken https://docs.google.com/spreadsheets/d/19FB49_fR65_Ot-IrA7jiLMGQDa6DteIR1p3CNjxmnHo/edit#gid=0

**Comment by pleku** [comment]
All 7.7.7 changes have been merged and will be released in 8.0.2
