### ISSUE TITLE
A strange comma is presented in a DateField

### ISSUE THREAD

**Issue by jouni** [vaadin/framework#8303]
_From @nutteen on January 19, 2017 4:47_

The following code is used to create a date field with Thai locale.
The affect versions that has been tested are: Vaadin 7.x.x, and 8.0.0.beta1.

`DateField dateField = new DateField();`
`dateField.setCaption("Date:");`
`dateField.setLocale(new Locale("th", "TH"));`
`dateField.setValue(LocalDate.now());`

The current date as of the testing is 19/1/2017.

As a result of the test, in the DateField, it displays "19/1/2017," 
There's a strange comma after the year.

_Copied from original issue: vaadin/vaadin-date-picker#326_

**Comment by denis-anisimov** [comment]
This is fixed in 7.7 branch.
The fix will be migrated to the master and into 8.0 at some point later on.
