### ISSUE TITLE
Select multiple items on MultiSelects by providing collection of them

### ISSUE THREAD

**Issue by tdq** [vaadin/framework#8307]
Vaadin 8

It would be great to have `selectItems(Collection<T> items)` in `com.vaadin.ui.components.grid.MultiSelectionModel` interface.

**Comment by pleku** [comment]
This was originally scoped out from 8.0.0, but might make it. Can be added later on even a maintenance release too.

Not sure if API should allow `Collection` and discard duplicates, as the original issue suggests using `Set` instead. The current API also uses `Set` in other methods like `getSelectedItems()` and `updateSelection(Set<T> added, Set<T> removed)`, to which this is just a shorthand for `select.updateSelection(newSelection, select.getSelectedItems())`
