### ISSUE TITLE
Problem after click on Button

### ISSUE THREAD

**Issue by matthiaslarisch** [vaadin/framework#8313]
According to the correspondence between Enver Haase and me on the Vaadin Forum (https://vaadin.com/forum#!/thread/13270551) here is the minimal test case. The complete issue description can also be found in the forum.

[VaadinTest.zip](https://github.com/vaadin/framework/files/725890/VaadinTest.zip)

**Comment by enver-haase** [comment]
Use NativeButton instead of Button as a work-around.

I can confirm using Button eats the DOM's Mouse-Up events.

Not sure yet whether we should touch this behaviour that has been there forever through Vaadin 7 and 8 and maybe even 6.
