### ISSUE TITLE
Grid do not marks sorted columns

### ISSUE THREAD

**Issue by tdq** [vaadin/framework#8316]
FW8

Create Grid, fill by items and try to sort some column programmatically.
For example:

`
Grid<Person> grid = new Grid<>();
grid.addColumn(Person::getName).setCaption("Name");
grid.setItems(model.getItems());
grid.sort(grid.getColumns().stream().filter(c -> c.getCaption().equals("Name")).findFirst().get());
`

**Comment by denis-anisimov** [comment]
See this PR:
https://github.com/vaadin/framework/pull/8452
GridSortIndicatorTest is ignored because of this issue.
It should be enabled once the issue is fixed.

**Comment by focbenz** [comment]
Also affected by this issue of the missing sort indicator using latest Vaadin 8.0.2 release.

**Comment by dmarko484** [comment]
Also affected. Its significant issue when using Grid with database. We can't indicate current sort order now ...

**Comment by dmarko484** [comment]
Thanks a lot!!

**Comment by tsuoanttila** [comment]
This was picked to 8.0.7
