### ISSUE TITLE
Vaadin 8 Binding Null Representation Bug

### ISSUE THREAD

**Issue by fakeh** [vaadin/framework#8321]
I have a model that takes a char[] that I'd like to use with Binder.

I tried to use the following:

```
		binder.forField(password)
		.asRequired("Please enter a password")
		.withNullRepresentation("")
		.withConverter(String::toCharArray, String::new)
		.bind(LoginModel::getPassword, LoginModel::setPassword);
```

But this results in a NullPointerException when calling String::new with a null char[]. I would have expected withNullRepresentation to have taken care of both the presentation to model and model to presentation conversions, but it seems this is not the case.

Thanks, Dan.

**Comment by elmot** [comment]
I am not sure if this should be implemented in the framework. `withNullRepresentation` is about representation of null but not about conversion model's nulls. What if `null` is a valid value for the model, and some custom converter converts it to something application-specific?

In this particular case different order of conversions does the trick:
```
        Binder<LoginModel> loginModelBinder = new Binder<>();
        loginModelBinder.forField(password)
                .asRequired("Please enter a password")
                .withConverter(String::toCharArray, String::new)
                .withNullRepresentation(new char[0])
                .bind(LoginModel::getPassword, LoginModel::setPassword);
```
another option is null-proof converter
```
        Binder<LoginModel> loginModelBinder = new Binder<>();
        loginModelBinder.forField(password)
                .asRequired("Please enter a password")
                .withConverter(String::toCharArray, chars -> Objects.toString(chars, ""))
                .bind(LoginModel::getPassword, LoginModel::setPassword);
```

**Comment by Legioth** [comment]
`withNullRepresentation` is implemented as a "local" operation that is applied as one step in the "chain" of conversions and checks that are performed between the field and the bean.

There is unfortunately nothing that prevents it from being misunderstood as a "global" operation that would bypass the remaining steps of the chain. That mode of operation could indeed be quite useful in at least this case, and might actually not have any difference in many other cases. The `withReplacement` shorthand that I suggested in #8441 could be used in cases where a local operation is needed. The main question is however whether it would be confusing that all other `withXyz` methods introduce local operations whereas `withNullRepresentation` would be a global global operation. Would it be possible to use some other name scheme to make the difference clear?

**Comment by Legioth** [comment]
I created #8465 for my feature suggestion about a "global" null representation. I'll close this bug report since things work exactly as planned.

**Comment by fakeh** [comment]
Thanks Legioth. You described the issue as I see it very clearly!
Dan.
