### ISSUE TITLE
Use of Optional in HasValue

### ISSUE THREAD

**Issue by heruan** [vaadin/framework#8323]
In FW 8 alpha `HasValue.getValue()` did return an `Optional`, but in beta 1 it returns the value, possibly `null`. I'd personally find more consistent to return an `Optional`, empty if the value is equal to `HasValue.getEmptyValue()`. Or, at least, have a `HasValue.getOptionalValue()` method.

**Comment by Legioth** [comment]
We opted to change the return value back to `T` to make the type symmetric with the setter.

Adding a separate method that returns `Optional` seems like a good compromise!
