### ISSUE TITLE
After changing the DataProvider in a Grid the SelectionListener returns null for getFirstSelected

### ISSUE THREAD

**Issue by JarekToro** [vaadin/framework#8325]
Using Vaadin 8 Beta1

After calling `setDataProvider` with a new `DataProvider` after it already had a `DataProvider` visually it works the Information shown is the new information from the new `DataProvider`. However upon a `SelectionEvent` `event.getFirstSelected()` is `null`. When you scroll the table down further it starts working but the first 30ish items they all return null unless you scroll way down the back up.

I was able to solve the issue with this
```java
grid.setDataProvider(someDataProvider());
grid.getDataCommunicator().getKeyMapper().removeAll();
grid.getDataProvider().refreshAll();
```

but I believe that this is a bug and that it should clear itself upon setting a new DataProvider.

**Comment by Legioth** [comment]
Fixed by https://github.com/vaadin/framework/pull/8138, but not yet released.
