### ISSUE TITLE
Feature: Ability to get rid of Vaadin mentions in the application client side

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#8330]
Now "/VAADIN" directory is hard coded in the many classes of the framework. For enterprise apps it is not enterprise grade to pin static resources to a hard coded location.

Also should be a way to hide Vaadin version and do not send it to the client by security reasons.

**Comment by rucko24** [comment]
Thanks, some example of how you could deactivate those directories so that they are not visualized? Or better yet a redirect to a URL that takes me to the main class? To avoid that?

I am thinking of including Spring for handling those vistar or url incorrect.
