### ISSUE TITLE
Make compatibility aliases for isRequiredIndicatorVisible()

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#8337]
`isRequiredIndicatorVisible()` must have v7-compatible `isRequired()` aliases in legacy classes

**Comment by pleku** [comment]
The following should _added back_ into `AbstractFieldConnector`. 
    /**
     * Checks whether the required indicator should be shown for the field.
     * Required indicators are hidden if the field or its data source is
     * read-only.
     * <p>
     * NOTE: since 8.0 this only delegates to
     * {@link #isRequiredIndicatorVisible()}, and is left for legacy reasons.
     *
     * @return true if required indicator should be shown
     */
    public boolean isRequired() {
        return isRequiredIndicatorVisible();
    }

**Comment by denis-anisimov** [comment]
I think it shouldn't be added _back_ to `AbstractFieldConnector`.
Instead  we can create subclass for v7 classes only and define it there.

**Comment by pleku** [comment]
Sorry, meant the `AbstractFieldConnector` in the `v7` package (that is already existing).
