### ISSUE TITLE
Viewport orientation 

### ISSUE THREAD

**Issue by DukeNukem1990** [vaadin/framework#8353]
Vaadin Version: 7.7.6 with Vaadin Designer

Bug:
The Viewport keeps changing orientation (landscape -> portrait and back) without any input while in Preview mode.

Reproduction:
- Open any design in Preview Mode
- Click on the "change viewport orientation" button, repeatedly and in quick succession

**Comment by Artur-** [comment]
This issue was moved to vaadin/designer-issues#1310
