### ISSUE TITLE
FW8 API for sorting DataProvider is confusing

### ISSUE THREAD

**Issue by tmattsso** [vaadin/framework#8367]
I tried doing sorting like this:
`Comparator<Consultant> comparing = Comparator.comparing(Consultant::getTaxBracket);
dataProvider.setSortComparator(comparing);`

, but it doesn't compile because 'Consultant' isn't Serializeable. This doesn't make any sense, and isn't detailed in any documentation.

What I'd want is something like this instead, if the comparator truly has to be serializeable:

`SerializableComparator<Consultant> comparing = SerializableComparator.comparing(Consultant::getTaxBracket);
dataProvider.setSortComparator(comparing);`

**Comment by Legioth** [comment]
I actually lied to you. The compile error doesn't come from `Consultant` not being `Serializable`, but rather from some other irrelevant aspects of how generics work in Java. The main point is still that there is no good and reasonably obvious way of achieving this.

What you probably can do right now is
```
Comparator<Consultant> comparing = Comparator.comparing(Consultant::getTaxBracket);
dataProvider.setSortComparator(comparing::compare);
```
or alternatively for this particular case
```
dataProvider.setSortOrder(Consultant::getTaxBracket, SortDirection.ASCENDING)
```
