### ISSUE TITLE
Make Grid column types based on the value provider instead of the renderer

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8371]
You can create a grid column with a renderer that accepts a super type of the value provider type, so that e.g. a `ValueProvider<Person, Integer>` can be used with a `NumberRenderer` that is typed to `Number`. The problem is that `addColumn` will in that case return a `Column<Person, Number>` instead of the more specific `Column<Person, Integer>`.

**Comment by denis-anisimov** [comment]
Covered by #8458
