### ISSUE TITLE
Implement new Tree

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8376]
@Artur- commented on [Tue Sep 20 2016](https://github.com/vaadin/framework8-issues/issues/306)

Depends on #318

---

@pleku commented on [Tue Oct 11 2016](https://github.com/vaadin/framework8-issues/issues/306#issuecomment-252836139)

COULD HAVE, but not necessary for FW8.

**Comment by denis-anisimov** [comment]
Version 8.1.0.
But it's almost on the top of the product backlog......

**Comment by pleku** [comment]
Duplicate for #8617
