### ISSUE TITLE
There should be LocalDateRenderer and LocalDateTimeRenderer

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8377]
@pleku commented on [Mon Oct 03 2016](https://github.com/vaadin/framework8-issues/issues/367)

DateRenderer should not be Date based, should use e.g. Instant or something else so that user doesn't have to convert to Date.
Another option would be to have several Date related renderers for each type ? E.g. InstantRenderer, LocalDateRenderer ...

---

@pleku commented on [Tue Oct 11 2016](https://github.com/vaadin/framework8-issues/issues/367#issuecomment-252833377)

SHOULD HAVE, but not necessary for FW8.

**Comment by Legioth** [comment]
I don't think the existing `DateRenderer` should be changed. We should instead introduce a new class with similar functionality but a different input type.

**Comment by nikkijuk** [comment]
I will today implement my own LocalDateRenderer because I need one, and I believe everyone using Java 8 date types will at the end do the same.. I can't wait Vaadin 8.1 and I believe many others won't wait either.

**Comment by markathomas** [comment]
+1 - this is problematic now that DateField returns LocalDate but DateRenderer requires Date
