### ISSUE TITLE
Implement Binder.isValid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8378]
@Artur- commented on [Thu Sep 29 2016](https://github.com/vaadin/framework8-issues/issues/344)

`Binder.isValid()` checks the validation status but does not make all validation errors visible in the way that `validate()` does

---

@pleku commented on [Tue Oct 11 2016](https://github.com/vaadin/framework8-issues/issues/344#issuecomment-252859220)

SHOULD HAVE, but not necessary for FW8.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/framework/issues/8274

**Comment by Legioth** [comment]
Closing as duplicate
