### ISSUE TITLE
Spring integration to Vaadin

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#838]
**Originally by _antoni_**

___
Hi,
there is needed functionality to create Application as Spring beans with all Springs functionality (IOC for example, etc).

I did implement such functionality in the vaadin-examples project. 

I'd made com.vaadin.terminal.gwt.server.SpringApplicationServlet class. Also there is new file META-INF/applicationContext.xml to show how to declare Application as a bean. There are made changes to the web.xml. The HelloWorld application is used as the Application bean. 
The only change is made to HelloWorld class is sessionId printing to see that all configurations works as designed.

spring.jar is added to the WEB-INF/lib folder. This is only file will not be uploaded.

Please try the changes and include this example to all community.

Changes:
web.xml
.............
        
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>classpath*:/META-INF/applicationContext.xml</param-value>
	</context-param>
.............
	
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>
	
	<listener>
		<listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>
	</listener>
.............
	
	<servlet>
		<servlet-name>SpringHelloWorld</servlet-name>
		<servlet-class>com.vaadin.terminal.gwt.server.SpringApplicationServlet</servlet-class>
		<init-param>
			<param-name>applicationBean</param-name>
			<param-value>helloWorldBean</param-value>
		</init-param>
	</servlet>
.............
	<servlet-mapping>
		<servlet-name>SpringHelloWorld</servlet-name>
		<url-pattern>/SpringHelloWorld/*</url-pattern>
	</servlet-mapping>
	
The HelloWorld:
String sessionId = 
            ((WebApplicationContext) getContext())
            .getHttpSession().getId();
    
        main.addComponent(new Label("Session id: ".concat(sessionId)));

Thanks
Antoni

___
 Imported from https://dev.vaadin.com/ issue #3370

**Comment by anasmi** [comment]
Hi!

We are going through the process of closing issues, which were fixed in the newer versions of the framework, or have never been verified. This feature has been implemented in the newer versions.[Vaadin + Spring Documentation](https://vaadin.com/framework/spring)

If you disagree with the decision of closing this particular issue, please re-open it or create a new one, with explanation and/or example to reproduce.

Thanks for your help and contributions!
