### ISSUE TITLE
Fields mapped to a bean property with @NotNull or @NotEmpty should be visually marked as required

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8382]
@Legioth commented on [Wed Sep 07 2016](https://github.com/vaadin/framework8-issues/issues/198)

Still needs to consider the exact details since e.g.  @NotNull would accept `""`, even though that is usually not considered acceptable for a required field.

This also relates to https://dev.vaadin.com/ticket/14746

---

@pleku commented on [Tue Oct 11 2016](https://github.com/vaadin/framework8-issues/issues/198#issuecomment-252859996)

SHOULD HAVE, but not necessary for FW8.

---

@Legioth commented on [Wed Nov 02 2016](https://github.com/vaadin/framework8-issues/issues/198#issuecomment-257796652)

#419 detaches the validation logic from the displaying of the standard required indicator. This means that we would only need some way of identifying which validation annotations are such that `field.setRequiredIndicatorVisible(true)` should be called when binding.

This could be done e.g. by configuring `Binder` with a list of annotation types or a predicate that checks each constraint to see if its semantics can be seen as "required." This would include at least `@NotNull` and `@Size(min = 1)` from the standard annotations in JSR-303, and maybe also supplemented with the commonly used `@NotEmpty` constraint defined by Hibernate Validator (though it should be implemented in a way that doesn't require Hibernate Validator classes to be on the classpath).

One open question is whether the configuration would be per `Binder` instance, or if it would be more useful to actually define this in a static fashion so that the same settings would be automatically used in all binders of the applications.

**Comment by Legioth** [comment]
I'd like to bump this into being a candidate for 8.0 since it would be a behavioural change that wouldn't cause any compilation errors, and might thus be problematic if introduced in a minor update.
