### ISSUE TITLE
Add chapter documentation file for migration

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8391]
Currently the migration guide is not visible in https://vaadin.com/docs8/

There should be a chapter file, like with other chapters e.g. https://github.com/vaadin/framework/blob/master/documentation/architecture/chapter-architecture.asciidoc.

IMO it should be the last on the list, __Migrating from Version 7 to 8__ or such

**Comment by Artur-** [comment]
Probably needs the menu to be updated here: https://github.com/vaadin/vaadin-docs/blob/master/website/_data/docs.yml

**Comment by samie** [comment]
Are we just ok to add something like this to docs.yml?

```
 migration:
      title: Migrating to Vaadin 8
```

**Comment by samie** [comment]
updates on this one? Currently all migration information is missing from website.

**Comment by pleku** [comment]
Fixed https://vaadin.com/docs8/-/part8/framework/migration/migrating-to-vaadin8.html
