### ISSUE TITLE
DateTimeField does not show weeknumbers.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/framework#8405]
Hello.

Looks like DateTimeField (and, apparently, other related components for date display, have tries DateField also) can not display week days.

Minimum working example:
```java
@SpringUI
@Theme("valo")
public class TestUi extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        DateTimeField dateTimeField = new DateTimeField();
        dateTimeField.setValue(LocalDateTime.now());
        dateTimeField.setShowISOWeekNumbers(true);

        CheckBox weekDaysToggle = new CheckBox("Toggle week days", dateTimeField.isShowISOWeekNumbers());
        weekDaysToggle.addValueChangeListener(e -> dateTimeField.setShowISOWeekNumbers(e.getValue()));

        setContent(new VerticalLayout(dateTimeField, weekDaysToggle));
    }
}
```

Vaadin framework version: 8.0-SNAPSHOT

**Comment by caalador** [comment]
The issue in the test is that the locale is not week number compatible:
Sets the visibility of ISO 8601 week numbers in the date selector. ISO 8601 defines that a week always starts with a Monday so the week numbers are only shown if this is the case.

But another problem is that the state of the showWeekNumbers doesn't change after first opening of the calendar popup. So if I open the popup with weekNumbers (fi_FI locale, shows week numbers) I can not remove the week numbers by saying `setShowISOWeekNumbers(false)`, and the other way if I open the popup without week numbers they won't show up for `setShowISOWeekNumbers(true);`

Having week numbers and changing locale does remove week numbers from the popup.
