### ISSUE TITLE
Allow usage of valid 'html location' in CustomLayout

### ISSUE THREAD

**Issue by Knoobie** [vaadin/framework#8416]
Currently it's only possible to add a component with the attribute location in the html layout. 
Location isn't a valid html attribut on most elements. 

> ( Example: ```html<div location="id"></div>``` )

How about adding additional support for data-location, so the W3C Markup Validation won't return unnaccessary errors? Additional it's an improvement for the german accessibility guideline, where a valid W3C Markup is a required (*).

* to reduce unnecessary points deduction - see http://testen.bitv-test.de/index.php?a=di&iid=27&s=n

**Comment by taurus227** [comment]
For the record, this is the relevant HTML5 spec section:
[Embedding custom non-visible data with the data-* attributes](https://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes)
