### ISSUE TITLE
Hello, some directories would reveal app information?

### ISSUE THREAD

**Issue by rucko24** [vaadin/framework#8417]
When accessing this links in the browser I get this 
https://demo.vaadin.com/dashboard/UIDL/?v-uiId=2

![errorappvaadin](https://cloud.githubusercontent.com/assets/17187599/22531790/a19bc982-e8b9-11e6-88cb-cd4be9faa6a2.png)

**I really want** to know if those directories or the information you show could cause my application to be vulnerable

http://my-app/VAADIN/themes/valo/fonts
http://my-app/VAADIN/themes/valo/fonts/roboto
http://my-app/VAADIN/themes/valo
http://my-app/VAADIN/themes/valo/shared
http://my-app/VAADIN/themes/valo/shared/img
http://my-app/VAADIN/widgetsets/com.vaadin.DefaultWidgetSet

http://my-app/UIDL/?v-uiId=2
http://my-app/HEARTBEAT/?v-uid=0
http://my-app/HEARTBEAT/?v-uid=1
http://my-app/HEARTBEAT/?v-uiId=1
http://my-app/AAP
http://my-app/cdn-cgi
http://my-app/cdn-cgi/images

**Comment by hesara** [comment]
What you are seeing in the screenshot is a normal (error) reply of Vaadin server side to the client side. The client side then parses and processes this, and displays it in a more appropriate format to the user. There is nothing sensitive in that default error, and in general these server to client messages just contain the instructions that the client side engine uses to display the UI. Thus, through this internal UIDL URL, the remote user can get effectively the same information he would see on the screen in the Vaadin application, but no additional application state etc. that stays on the server.

There are various protection mechanisms in place for things like the client trying to update a component that is not visible or not editable, the client replaying old messages, session hijacking etc.

The themes just contain the CSS for the application (which the browser needs to see anyway) and its sources. Likewise, the widgetsets directory just contains the compiled client side widget implementations, no application data. The DefaultWidgetSet does not contain anything related to your application, just the default widget implementations and communication mechanism. Heartbeats convey no information except about session expiration.

The APP path serves certain kinds resources your application has published for the client, so creating ClassResource, FileResource and StreamResource instances and using them can make those available - though normally only for the user for whose UI they were created. The APP paths are also used e.g. by the Upload component, but not exposing extra information to the user through such uses either.

The path cdn-cgi has nothing to do with Vaadin, and whether the information there constitutes a vulnerability by being exposed to the user is up to your application that is making those paths visible - I have no way of knowing what is served from those paths.

**Comment by Legioth** [comment]
In addition to Henri's answer, I'd like to offer these additions.

Most of the responses expose the fact that this is an application using some version Vaadin Framework, and some of the responses do also directly or indirectly expose information about which version of Vaadin Framework is used. This information is in itself not any security issue, but it might help an attacker determine how the application could be attacked. There are open issues related to this, e.g. https://github.com/vaadin/framework/issues/8330 and https://github.com/vaadin/framework/issues/7751.

> http://my-app/VAADIN/themes/valo/fonts
http://my-app/VAADIN/themes/valo/fonts/roboto
http://my-app/VAADIN/themes/valo
http://my-app/VAADIN/themes/valo/shared
http://my-app/VAADIN/themes/valo/shared/img
http://my-app/VAADIN/widgetsets/com.vaadin.DefaultWidgetSet

Depending on how your application is deployed and how your application server is configured, these URLs might either produce an empty response, a directory listing, a HTTP 404 response, or a HTTP 500 response that might or might not show a stacktrace.

If a directory listing is shown, then it's shown by the application server and not Vaadin Framework, and can thus also be disabled by configuring the application server. Even if a directory listing is shown, it wouldn't expose anything that an attacker couldn't already guess based on other sources.

An HTTP 500 response with a stacktrace may expose some information about e.g. what application server is used and how it's configured. This can be mitigated by configuring the application server to not show stacktraces in generic error pages.

**Comment by rucko24** [comment]
Thanks, 

Some example of how you could deactivate those directories so that they are not visualized? Or better yet a redirect to a URL that takes me to the main class? To avoid that?

**Comment by hesara** [comment]
Please keep discussion on the forum (https://vaadin.com/forum) as issue tracking is for bugs and feature requests.

How to disable directory listing is server dependent, so please consult the documentation of your application server. The browser still needs to be able to access individual URLs and get the correct replies from them when the client side knows the exact URL, so this doesn't change very much.

If you don't know in depth how and why you are doing so, combining Spring and CDI is usually not a good idea - it leads to considerably more complexity and potential sources of misconfiguration.

I assume you meant Spring Security in this case as Spring is a collection of a lot of different modules; if so, there are other alternatives that might fit the JEE/CDI world better. You could take a look at some JAAS providers, Shiro (there should be an example of using Shiro with Vaadin CDI) or some other approach.

Please take any further questions to the forum or other channels.
