### ISSUE TITLE
BOM should not use snapshot versions

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8424]
If you create a project using 8.0.0.beta1 + add a `vaadin-spring` dependency, the project does not compile. This is because a SNAPSHOT version of `vaadin-spring` is defined in the BOM but the project does not have a snapshot repository defined (and the BOM does not provide one either)

**Comment by hesara** [comment]
The final publishable BOM should be built separately from the framework, after all the relevant projects that depend on each other have been built. This does add some complexity to testing and releasing, but should help users.

**Comment by hesara** [comment]
Currently planning how to organize the building and release of the various pieces.

**Comment by hesara** [comment]
Initial steps towards this in #8484

**Comment by hesara** [comment]
Already done in the 8.0 branch, from which stable releases will be built.
Note that the master branch (while evolving towards 8.1) still uses some SNAPSHOT dependencies.
