### ISSUE TITLE
Make DragSource extension/component available in DropEvent

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8439]
When the drag has originated from the same UI, it would be nice to get the drag source component/extension in the drop event. This would make it really easy to pass the DnD operation data without using `dataTransfer.data` object when the DnD is happening inside the UI.

The easiest way to implement this might be to store it in the UI when a dragStart event has happened.

API:
```java
class DropEvent extends Component.Event {
...
  /**
   * If the drag had originated from this UI, this returns the source component.
   */
  public Optional<Component> getDragSourceComponent() {...}

  /**
   * If the drag had originated from this UI, this returns the source extension.
   */
  public Optional<DragSourceExtension> getDragSourceExtension() {...}
}
```

Could be easily done as a variable stored in the UI, that has public API that is used when the `DropEvent` happens:
```java
public void setActiveDragSource(DragSourceExtension extension) {...}
public DragSourceExtension getActiveDragSource() {...}
```
This needs to be cleared by the `DragSourceExtension` on a `dragend` event.

**Comment by pleku** [comment]
Could be nice to make it possible to get the component/data from drags that have originated from other browser windows (UIs).

**Comment by wbadam** [comment]
I have some concerns regarding this solution. If the component is stored in the UI, all _dragstart_, _dragend_ and _drop_ server side listeners must be registered to set and remove the currently dragged element.

Wouldn't it be better to store the drag source's connector ID in the client side `DataTransfer` and retrieve the corresponding component using that ID during server side _drop_? My quick test showed it quite easy to do.
