### ISSUE TITLE
DateField with Resolution.MONTH: Selection of current month not possible

### ISSUE THREAD

**Issue by sularak** [vaadin/framework#8447]
...or at least its not easy/intuitive.

To reproduce:
-https://demo.vaadin.com/sampler/#ui/data-input/dates/popup-date-field
-delete value/set to null
-select Resolution MONTH
-try to select the current month;) You can only enter it by hand or go back and forth with the arrows. Or is there another possibility?

Imo, it would be obvious/intuitive to also select a month by clicking on the blue month label, not only by navigating with the arrows.

Vaadin version 7.7.6

**Comment by sarahfuchs** [comment]
Still not working fo vaadin 8.1.3 resolution year or month. 
If days can be selected by clicked, months and years shold listen to clicks too.
I get that problem if I add a field without setting an explicit value. All looks great, except tha I cant choose the first opened year or month:
    VerticalLayout myLayout=  = new VerticalLayout();
    DateField dyf = new DateField();
    dyf.setResolution(DateResolution.YEAR);
    dyf.setCaption("year");
    myLayout.addComponent(dyf);
    DateField dmf = new DateField();
    dmf.setCaption("month");
    dmf.setResolution(DateResolution.MONTH);
    myLayout.addComponent(dmf);
