### ISSUE TITLE
ComboBox setPageLength(0) makes last line invisible if empty selection is allowed (8.0.0beta2)

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#8448]
While setting comboBox page length to zero, the last line in popup's window becomes invisible. Occurs only if setEmptySelectionAllowed is set to true
Code to reproduce:
```
ComboBox<String> cb = new ComboBox<>();
cb.setItems(Arrays.asList("1", "2", "3")); //3 will not be listet
cb.setPageLength(0);

```
Works right if `cb.setEmptySelectionAllowed(false);` applied

**Comment by pleku** [comment]
There was some ComboBox related fixes in 8.0.0.RC2, not able to replicate this anymore.
