### ISSUE TITLE
Allow intercept Window.CloseShortcut action or provide "Cause" in CloseEvent (Vaadin 8)

### ISSUE THREAD

**Issue by retomerz** [vaadin/framework#8457]
We need to know how a com.vaadin.ui.Window was closed.
More precisely: A event when the Window was closed by a shortcut.

At the moment (Vaadin 8 beta2) it is possible to override addCloseShortcut to register a custom CloseShortcut extension.
This is not optimal because we need to copy to code of the addCloseShortcut method.

One solution would be to introduce a new method like this:
```java
/**
 * Allow Window extension to create a custom CloseShortcut extension too.
*/
protected CloseShortcut createCloseShortcut(int keyCode, int... modifiers) {
    return new CloseShortcut(this, keyCode, modifiers);
}
```

and addCloseShortcut would use this method to create a CloseShortcut instance.

Another solution could be to add a "Cause" property to the CloseEvent which indicates how the close event was triggered, f. e:
```java
public enum CloseCause {
    Shortcut,
    Programmatically
}
```

**Comment by pleku** [comment]
We would consider this as a candidate for 8.1
