### ISSUE TITLE
Fix Binder javadoc regarding JSR 303

### ISSUE THREAD

**Issue by alejandro-du** [vaadin/framework#8459]
8.0.0.beta2. Javadoc documentation in some methods of the Binder class promise to add BeanValidators if a JSR 303 implementation is in the classpath. This is not the case anymore. I suggest adding a comment pointing to the new BeanValidationBinder class to avoid developers wasting time trying to figure out why the validation doesn't work.

**Comment by pleku** [comment]
Not just javadocs, but also the documentation should mention this clearly. Currently searching for _beanvalidationbinder_ from `*.asciidoc` files gives 0 results.

**Comment by pleku** [comment]
Also there should probably be a similar static helper for customizing property set like `Binder.withPropertySet(PropertySet<Bean>)`

**Comment by denis-anisimov** [comment]
There is a separate issue about ascii docs for BeanValidationBinder.
