### ISSUE TITLE
Make the declarative format support the Grid(Class) constructor

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#8467]
A `Grid` created using `new Grid<>(SomeBean.class)` should be written out with the fully qualified class name in an attribute so that when the declarative file is read, you can still use `myGrid.addColumn("propertyName")`.

Any column created based on property name should be stored as such in the declarative format so that it can be recreated with a binding to the same property name.

**Comment by pleku** [comment]
@ripla do you something for this from the FW ?

**Comment by ripla** [comment]
@pleku Currently the Designer stores the generic type in a `data-item-type` attribute which defaults to `java.lang.String`. How you are planning to store the bean type, columns and rows?
