### ISSUE TITLE
Programmatically open the editor row in Grid for an item based on row index

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/framework#8477]
Vaadin version: 8.0-SNAPSHOT

Apparently, there is no way to programmatically open the edit menu for Vaadin 8 Grid component.
It was possible in Vaadin 7.
Can you add the method to Vaadin 8 Grid please?

**Comment by caalador** [comment]
In Vaadin 8 you can do: `grid.getEditor().setEnabled(true);`
We only do not have the shorthand from Vaadin 7 `grid.setEditorEnabled(true);`

**Comment by SomeoneToIgnore** [comment]
I am talking about opening the actual edit dialog: 
![screen shot 2017-02-07 at 14 19 37](https://cloud.githubusercontent.com/assets/2690773/22690889/7c4cdd34-ed40-11e6-8afe-e596825c3415.png)

Vaadin 7 could do this with `editItem` method, Vaadin 8 can not do this at all, apparently.

**Comment by caalador** [comment]
That seems to be so as it's probably the same as `protected void doEdit(T bean)` in the editor implementation which is only called from the client side call to the RPC.bind method.

**Comment by tsuoanttila** [comment]
The issue is that our DataProvider is not providing indexes for arbitrary objects of type T. We could solve it similar to the scroll to row issue and have edit(int rowIndex).

**Comment by pleku** [comment]
This is now about row index based API (easy), #8820 is about item based API (difficult)

**Comment by pwilkin** [comment]
I'm all for just doing `scrollToRow(int row)` and `editRow(int row)` and leaving the index detection (potentially hard computationally) to the `DataProvider`. However, this should be done ASAP - currently, the new `Grid` is basically useless for editing lists containing an "add" button (I can add a bean, but under the new API I can't immediately open it for editing), which is probably one of the most appealing ways to use inline `Grid` editing. 

I could probably code the `editRow` part, not sure if I know how to do the `scrollToRow` one though - any hints?

**Comment by pwilkin** [comment]
Created pull request for this, would welcome any comments.
