### ISSUE TITLE
Infinite loop if DataProvider returns no rows

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8479]
If `size` in a DataProvider returns 1 but `fetch` returns an empty stream, Grid will ask again and again and again for data although there is none (e.g. somebody has deleted the row between the `size` call and the `fetch` call). The UI shows a row without data, a blinking loading indicator and completely stops working.

**Comment by pleku** [comment]
Not a blocker for 8.0, can be fixed in a maintenance.

**Comment by casz69** [comment]
We reproduce this in 8.0.3
