### ISSUE TITLE
100%x100% sub window produces extra scrollbars in the parent view in IE7

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#848]
**Originally by @Artur-**

___
Adding a 100%x100% sub window should make a window that fills the screen and no scrollbars should appear.

With IE7 (IE6+IE8 ok) adding a 100%x100% sub window adds scrollbars to the main view when using runo. 

See com.vaadin.tests.components.window.EmbeddedInSubWindow.

___
 Imported from https://dev.vaadin.com/ issue #3406

**Comment by TatuLund** [comment]
IE8 is not a supported browser with Vaadin 8, thus we are closing this as wont fix.
