### ISSUE TITLE
BackEndDataProvider/CallBackDataProvider APIs are hard to implement

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8488]
Vaadin version: 8.0.0.beta2

Implementing dataproviders directly form IDEs is hard as the interfaces takes in "nameless" functional interfaces. Thus, it is hard for users to understand what he should implement and how. Descriptive names for the interfaces (and documentation in those) would help.

**Comment by pleku** [comment]
Change to types `FetchCallBack` and `SizeCallBack`.

Verify if it effects documentation, demos, archetypes (?).
