### ISSUE TITLE
There is a limit and offset parameters passed for "count lambda" in CallbackDataProvider

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8489]
Vaadin Versin: 8.0.0.beta2

The lambda expression that is supposed to get the count of available objects in CallbackDataProvider gets a Query parameter that contains offset and limit. Based on the javadocs it is not clear if developer should obey those values (return the count of actually returned objects) or if he/she should return the actual size of the "database table".

**Comment by Legioth** [comment]
The query also contains sorting parameters that are equally pointless for counting.

**Comment by pleku** [comment]
Would need to split the query to `CountQuery` and `FetchQuery`, which will complicate cases where filters etc. are applied.

For now, could just clearly document the usage of `Query` for the count operation.
