### ISSUE TITLE
Query parameter passed to CallbackDataProvider contains int types

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8490]
Vaadin version 8.0.0.beta2

Based on some "espionage" (looking at Spring Data repositories and DeltaSpike Data), at least the size be of type long instead of int. Even if long values wouldn't be properly supported by Grid ATM, implementing the API would be much easier if the data types would match with the rest of the industry.

**Comment by pleku** [comment]
Effects demos, documentation, archetypes.

**Comment by Legioth** [comment]
From this follows that `Query.getOffset()` would also have to return `long`, and then `Query.getLimit()` should probably also return `long` just for consistency. This in turn means that users would instead have to explicitly cast to int when e.g. passing the offset to `Query.setFirstResult(int startPosition) in JPA. I'm not sure which alternative is worse here...
