### ISSUE TITLE
Creating lazy binding to ComboBox could be much easier than it is

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8494]
version: 8.0.0.beta2

To create lazy binding to ComboBox currently requires delopers to develop against DataProvider interfaces. If there would be APIs optimized for ComboBox use cases (and lazy loading only) the task could be much more easier for developers. The Query object passed to lambdas contain obsolete parameters, the filter string, offset and limit could then be passed directly to the lambda.

Slightly related to  #8492

**Comment by mstahv** [comment]
Also the getFilter returns Optional, I guess because the abstraction tries to work in some other use cases as well. If the API would be optimised for ComboBox, the filter could be just string and always defined ("" if nothing typed by the user). This forces user to do extra checks with the optional interface.

**Comment by Legioth** [comment]
So if I understand correctly, you suggestion would mean that we would add a shorthand method to `ComboBox` that would be used like this (with explicit lambda param types just for the sake of clarity):
```
myComboBox.setDataProvider(
    (String filter, int offset, int limit) -> myService.findByFirstName(filter, offset, limit),
    (String filter) -> myService.countByFirstName(filter));
````

And actual usage could be as simple as `myComboBox.setDataProvider(myService::findByFirstName, myService::countByFirstName)` as long as you can define your service methods to exactly match the lambda signatures.

**Comment by pleku** [comment]
If this makes it, should verify that documentation / archetypes / demos uses this instead.

**Comment by Legioth** [comment]
Would also be good to have a similar shorthand in Grid:

```
myGrid.setDataProvider(
  (List<QuerySortOrder> sortOrders, int offset, int limit) -> [...],
  () -> [...]);
```
