### ISSUE TITLE
Consider whether DragSource component should be automatically removed from UI when dropEffect is move

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8510]

**Comment by wbadam** [comment]
Browsers have major inconsistencies around the usage of dropEffect.

Default is different, on Chrome it's `move`, on FF it's `copy` and can be changed by modifier keys. It probably also depends on the OS.
Also, `effectAllowed` could cancel a drop event if the actual `dropEffect` is not listed, but it apparently doesn't on Safari and IE.

An alternative is to mention in the docs that `move` should remove the drag source component and leave it to the developer to implement that behaviour.

**Comment by wbadam** [comment]
Related to this ticket that the `dropEffect` on `drop` event isn't necessarily representative, e.g. on Chrome it is always `none`.
Consider removing `getDropEffect` from `DropEvent` class.
`dropEffect` is available on `dragend` event according to the HTML standard and that event should be used for removing drag source when the effect was `move`.

**Comment by pleku** [comment]
Currently it is up to the developer to decide what they want to do when `dragend` happens. They are able to get the `dragend` the drop effect and remove the component if necessary. Doing things automatically by the framework might be confusing to some, so not doing anything for this for now.

Closing this ticket, might introduce this feature later on if there is feedback for wanting it.
