### ISSUE TITLE
Use generic for TextRenderer instead of casting

### ISSUE THREAD

**Issue by tdq** [vaadin/framework#8519]
I have to cast TextRenderer in this code

public AbstractRenderer<PatientModel, String> getRenderer() {
                return new TextRenderer();
            }

just because
public class TextRenderer extends AbstractRenderer<Object, String> {...}

but why not to make it like this:

public class TextRenderer extends AbstractRenderer<? extends Object, String> {...} or
public class TextRenderer extends AbstractRenderer<?, String> {

**Comment by jdahlstrom** [comment]
Java does not permit wildcards in supertype declarations. To get the typing right one would have to parameterize TextRenderer with the grid value type like this:
```
public class TextRenderer<T> extends AbstractRenderer<T, String> 
```
