### ISSUE TITLE
spring-boot-devtools do not work together with declarative files

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8528]
If you have a Spring Boot project and include `spring-boot-devtools`, Spring will use a `RestartClassLoader´ to load application classes so that it can throw away that class loader and all application classes when some part of the application changes. If you use a declarative design file and include a (custom) component from the project itself, you will get an error while binding that component to a field:
```
Caused by: java.lang.IllegalArgumentException: Can not set my.project.MyCustomComponent field my.project.DesignFile.customComponentField to my.project.MyCustomComponent
```

The field `type` is a class loaded by `RestartClassLoader` but the instance created by `Design.read` is created by the parent class loader:
```
instance.getClass().getClassLoader()
	 (sun.misc.Launcher$AppClassLoader) sun.misc.Launcher$AppClassLoader@18b4aac2
field.getType().getClassLoader()
	 (org.springframework.boot.devtools.restart.classloader.RestartClassLoader) org.springframework.boot.devtools.restart.classloader.RestartClassLoader@7662323c
```

**Comment by Artur-** [comment]
Workaround, add to your UI class: 

```
    static {
        Design.setComponentFactory(new DefaultComponentFactory() {
            @Override
            protected Class<? extends Component> resolveComponentClass(
                    String qualifiedClassName, DesignContext context) {
                try {
                    return (Class<? extends Component>) Class
                            .forName(qualifiedClassName);
                } catch (ClassNotFoundException e) {
                    throw new DesignException("Unable to load class", e);
                }
            }
        });
    }
```

As the UI class is loaded by the `RestartClassLoader`, this will also cause other project classes to be loaded using the same one

**Comment by Legioth** [comment]
Do you happen to know whether the RestartClassLoader is set as the context classloader? In that case, a proper fix to the framework could be to make the default component factory implementation use that classloader if available.
