### ISSUE TITLE
Automatic grid columns should work with designer

### ISSUE THREAD

**Issue by m-bermel** [vaadin/framework#8534]
Vaadin version: 8.0-SNAPSHOT

[Automatic added columns based on bean](https://github.com/vaadin/framework/blob/953e7212d84619332cba22888aa653462f9c1706/documentation/components/components-grid.asciidoc#automatically-adding-columns) should also be working with generated grids defined in a design.

**Comment by Legioth** [comment]
The framework part of this is covered by #8467. The rest would be up to the designer team.

**Comment by m-bermel** [comment]
Didn't knew that. Thanks for the answer!
