### ISSUE TITLE
TextField doesn't return value in time in a Window

### ISSUE THREAD

**Issue by m1h43l** [vaadin/framework#8564]
I got a login window with a TextField (username), PasswordField (password) and a button (login action, with enter for click shortcut). If I type and hit enter the value for the last thing i entered is not available. If I enter the password and immediately hit enter then the password is not returned by the getValue() method. Same goes for the TextField. The value is available if I wait for some moments. Seems there is a delay.

Workaround: Setting the ValueChangeMode.EAGER in the window

Vaadin Version 8.0.0.beta1
Server: Karaf 4.0.8 with Jetty 9.2.19.v20160908
Java : OpenJDK 8
Example Code: https://gist.github.com/tsuoanttila/5179da30b5a6436a13b0ee9c7020eae9

**Comment by Legioth** [comment]
Thank you for reporting.

`TextFieldConnector` in Framework 7 implements `BeforeShortcutActionListener` to handle exactly this case. This has apparently been omitted in the new `TextField` implementation that we're using in Framework 8.

**Comment by Legioth** [comment]
Seems like `BeforeShortcutActionListener` shouldn't be needed any more since this is nowadays expected to be handled through `TextFieldConnector.flush()`. Still something that should be investigated.
