### ISSUE TITLE
Using SerializableBiFunction for e.g. lazy Combobox filtering isn't documented properly

### ISSUE THREAD

**Issue by tmattsso** [vaadin/framework#8574]
The JavaDocs don't provide any help on how to use the methods, and the parameter type names are of no help either. It is completely impossible to figure out how it works by looking at the API.

**Comment by Legioth** [comment]
I think you forgot to mention the crucial detail that the method in question is `DataProvider.withConfigurableFilter(SerializableBiFunction<Q, C, F> filterCombiner)`.

There is an example of using this method in https://vaadin.com/docs8/-/part8/framework/datamodel/datamodel-providers.html#lazy-filtering, but it could be good to have something about it in the documentation about ComboBox as well.
