### ISSUE TITLE
add setItemEnabled(T, boolean) helper back to RadioButtonGroup and CheckBoxGroup

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8580]
Vaadin version: 8.0.0.rc1

Previously in V7 there was a handy API to disable certain item. Now one needs to provide a SerializablePredicate with setItemEnabledProvider to achieve the same. While the new API is probably really efficient and easy for the component developer, the old version was super handy for simple cases. The old version could be added there as well for convenience, with a reference in javadoc to the provider version.

**Comment by pinonpierre** [comment]
I agree, it's really boring to use ItemEnabledProvider in certain circumstances.

My workaround is to keep a list of Enabled items in my class but I can't easily provoke the refresh only of the visual of "Enable state" of CheckBoxGroup

**Comment by mstahv** [comment]
Verified that this is still valid in 8.3.2
