### ISSUE TITLE
Depracated classes should refer to replacements

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8581]
Vaadin version: 8.0.0.rc1

I tried to get rid of the deprecated com.vaadin.v7.OptionGroup. It was really hard to find out the actual class that replaced it. All classes that have depracated annotation in them, should contain javadoc to guide users to a replacement.

**Comment by Legioth** [comment]
`OptionGroup` and `DateField` were fixed in #8584, will fix the ones with more obvious replacements later.
