### ISSUE TITLE
MenuBar.MenuItem description (tooltip) lacking the content mode option

### ISSUE THREAD

**Issue by hesara** [vaadin/framework#8591]
In Vaadin 8.0.0.beta2 and later, tooltips are by default not in HTML mode. AbstractComponent has two versions of setDescription - one with the ContentMode parameter. However, MenuBar.MenuItem lacks the second setDescription(String, ContentMode), so HTML tooltips cannot be used for menu items.

**Comment by balugege** [comment]
I am effected by this. 
Temporary solution for me was to set the description of the MenuBar/AbstractComponent with ContentMode.HTML and then don't set a description for the MenuItems so the fallback to the description of the AbstractComponent

**Comment by balugege** [comment]
I created a pull request regarding this issue https://github.com/vaadin/framework/pull/9984
