### ISSUE TITLE
Documentation on HierarchicalDataProvider

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8616]

**Comment by elmot** [comment]
Container.Hierarchical and all the subclasses deprecation tags should be updated to tip new  HierarchicalDataProvider

**Comment by elmot** [comment]
When implemented, please update `@deprectated` in:
- [ ]  `ContainerHierarchicalWrapper`
- [ ]  `Container.Hierarchical`

**Comment by hesara** [comment]
Split off remaining deprecation related tasks to #9330.
