### ISSUE TITLE
Components in Grid

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8625]
It should be possible to have _any_ components in Grid's body's cells, just like with Table component.

This is an epic split into several tickets for the actual implementation.

**Comment by heruan** [comment]
Is there a branch available to follow, contribute and test the development of this?

**Comment by pleku** [comment]
@heruan the work for this is planned to start next week and you can follow e.g. the subtickets currently (#8622, #8623). Will include it in an 8.1.0. alpha release as soon as possible.

**Comment by heruan** [comment]
Thank you @pleku for the info. I've just issued PR #8806 proposing a column feature which may work in synergy with this.

**Comment by pleku** [comment]
All subtickets implemented and pending release in 8.1.0.alpha1
