### ISSUE TITLE
Getting NPE after upload

### ISSUE THREAD

**Issue by mejmo** [vaadin/framework#8629]
Vaadin 7.7.7

Uploading of files gives me often NPE in **com.vaadin.server.communication.ServerRpcHandler** at the line 571:

```
ServerRpcManager<?> rpcManager = connector.getRpcManager(interfaceName);
```

because the connector is null. I can reproduce this bug in 50% of cases and I do not have really currently a clue what decides if the upload works or not. After the server restart it seems to be working. But after third upload I get NPE. There seems to be some bug which was solved in year 2012, but it should be fixed now (rootId was not given and vaadin could not find the connector).

Any hint?

**Comment by Legioth** [comment]
Might be a regression caused by https://github.com/vaadin/framework/pull/8153.

**Comment by mejmo** [comment]
It had to come in lately, my last update was 1 year ago - it worked by now, so it has to be something with 7.7.7

**Comment by mejmo** [comment]
Solved. From some older examples I copied

```
           event.getUpload().markAsDirty();
````

And then I deleted some UI actions in uploadSucceeded method. Now I do not get any NPE.

**Comment by invenius** [comment]
I get a reproducable NPE at the very same place 

`com.vaadin.server.communication.ServerRpcHandler.parseServerRpcInvocation(ServerRpcHandler.java:571)`

if I try to upload files bigger than about 5MB with 7.7.7. If I go back to 7.7.6, the problem vanishes. Also, it only seems to appear on a Tomcat JSP server, with a Websphere, I have no problem.

The code line, mejmo removed, is not in my code, so it cannot be the cause.

**Comment by inahas** [comment]
I am getting the same exception in 7.7.7 while clicking on a regular button. I believe it is related to hiding/showing components on a page.

My application listens to events on a queue and when an event arrives it fires ui.access() call to refresh the UI which involves changing the visibility of some buttons/panels. If at the same time a user is interacting with something on that page, I get the NPE exception:

`com.vaadin.server.communication.ServerRpcHandler.parseServerRpcInvocation(ServerRpcHandler.java:571)`
If I increase the frequency of external events I can reproduce the issue 100% of the time. Going back to 7.7.6 clears the issue. So it definitely is a regression.

**Comment by RookieGuy** [comment]
The problem seems to be that the upload component disables the button while the file is uploaded
failing code
`Upload upload = new Upload("upload", fileReceiver);
upload.addSucceededListener(this::uploadSucceeded);
`
Here the error started to appear with 7.7.7 as well in  vaadin-server, stack trace:
`java.lang.NullPointerException: null
        at com.vaadin.server.communication.ServerRpcHandler.parseServerRpcInvocation(ServerRpcHandler.java:571)
        at com.vaadin.server.communication.ServerRpcHandler.parseInvocation(ServerRpcHandler.java:534)
        at com.vaadin.server.communication.ServerRpcHandler.parseInvocations(ServerRpcHandler.java:500)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:336)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)`

**Comment by inahas** [comment]
Until the fix is released, this is the workaround that I used. I added the following to my servlet class:

    //
    @Override
    protected VaadinServletService createServletService(DeploymentConfiguration deploymentConfiguration) throws ServiceException
    {
        VaadinServletService service = new MyVaadinServletService(this, deploymentConfiguration);
        service.init();
        return service;
    }

    @SuppressWarnings("serial")
    private static class MyVaadinServletService extends VaadinServletService
    {
        public MyVaadinServletService(VaadinServlet servlet, DeploymentConfiguration deploymentConfiguration) throws ServiceException
        {
            super(servlet, deploymentConfiguration);
        }

        @Override
        protected List<RequestHandler> createRequestHandlers() throws ServiceException
        {
            List<RequestHandler> handlers = super.createRequestHandlers();
            handlers.add(new MyUidlRequestHandler());
            return handlers;
        }

    }

    @SuppressWarnings("serial")
    private static class MyUidlRequestHandler extends UidlRequestHandler
    {
        @Override
        protected ServerRpcHandler createRpcHandler()
        {
            return new MyServerRpcHandler();
        }
    }

    @SuppressWarnings("serial")
    private static class MyServerRpcHandler extends ServerRpcHandler
    {
        @Override
        protected void handleInvocations(UI ui, int lastSyncIdSeenByClient, JsonArray invocationsData)
        {
            try
            {
                super.handleInvocations(ui, lastSyncIdSeenByClient, invocationsData);
            }
            catch (NullPointerException ex)
            {
                // Just swallow the exception
            }
        }
    }
    // --------- END WORKAROUND
