### ISSUE TITLE
Grid does not clean up components when columns removed

### ISSUE THREAD

**Issue by Snap252** [vaadin/framework#8638]
referencing [bug #8140](https://github.com/vaadin/framework/issues/8140)

Vaadin version: 7.7.7
when using a PropertySetChangeNotifier as DataSource, columns are removed/added automatically, and header cells are removed but not cleaned up.

example:

	package test.failure;
	
	import com.vaadin.data.Container.Indexed;
	import com.vaadin.data.util.IndexedContainer;
	import com.vaadin.ui.Button;
	import com.vaadin.ui.Grid;
	
	public class FailureGrid extends Grid {
	
		public FailureGrid() {
			Indexed i = new IndexedContainer();
			setContainerDataSource(i);
			i.addContainerProperty("c1", String.class, "does not matter 1");
			i.addContainerProperty("c3", String.class, "does not matter 2");
	
			HeaderRow h1 = prependHeaderRow();
			h1.getCell("c3").setComponent(new Button("This one will be an orthan"));
			h1.getCell("c1").setComponent(new Button("Click me to fail!", _ignore -> i.removeContainerProperty("c3")));
		}
	}

- just instantiate it, add to UI and press the first (left most) button in the header

hint:

	com.vaadin.ui.Grid.StaticSection.removeColumn(Object)

* cell is removed but not detached

**Comment by Snap252** [comment]
Thx for the fast response... will it be available in the 7.7.8 release and in the 7.7 branch?

**Comment by pleku** [comment]
@Snap252 , should be in 7.7.8.
