### ISSUE TITLE
Documentation: Example of Grid sorting aren't up to date (FW8, Rc2)

### ISSUE THREAD

**Issue by nikkijuk** [vaadin/framework#8639]
https://vaadin.com/docs8/-/part8/framework/components/components-grid.html

Example on docs doesn't compile, static "by" method doesn't exist. 

// Sort first by city and then by name
grid.sort(Sort.by(cityColumn, SortDirection.ASCENDING)
              .then(nameColumn, SortDirection.DESCENDING));

**Comment by ahie** [comment]
It is indeed incorrect. Thank you for pointing this out.
