### ISSUE TITLE
Grid cell value using value-providers

### ISSUE THREAD

**Issue by heruan** [vaadin/framework#8656]
Given the awesome enhancements in FW8 `Grid`, I was surprised to see missing a quite common use case about adding columns:

```java
ComboBox<Group> groupBox = new ComboBox<>();
groupBox.setItemCaptionGenerator(Group::getName);
groupBox.setItems(groups);

Grid<User> grid = new Grid<>();
grid.addColumn(User::getGroup)
// .setValueGenerator(Group::getName) --> this is missing, value will be Group.toString()!
.setEditorComponent(groupBox, User::setGroup);
```

I really hope the next release will support this!

**Comment by ahie** [comment]
Unless I'm misunderstanding what you want to achieve, you could do this with the following lambda:

```
grid.addColumn(user -> user.getGroup().getName());
```

**Comment by heruan** [comment]
Thank you @ahie, I know that but then I cannot do this:

```java
.setEditorComponent(groupBox, User::setGroup);
```

since the type of column would be `String` and not `Group`.

**Comment by ahie** [comment]
Oh yes of course, my bad. The simplest way around the lack of this feature would be overriding `toString`. If that is not possible, a custom `Renderer` implementation would also do the trick.

**Comment by heruan** [comment]
I'm overriding `toString()` right now, but I'd really like to see this in the next release 😉

**Comment by heruan** [comment]
I've implemented this `Renderer`

```java
public class ValueProviderRenderer<T> extends TextRenderer {

    private ValueProvider<T, String> stringProvider;

    public ValueProviderRenderer(ValueProvider<T, String> stringProvider) {
        this(stringProvider, "");
    }

    public ValueProviderRenderer(ValueProvider<T, String> stringProvider, String nullRepresentation) {
        super(nullRepresentation);
        this.stringProvider = stringProvider;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JsonValue encode(Object value) {
        if (value == null) {
            return super.encode(null);
        } else {
            return Json.create(this.stringProvider.apply((T) value));
        }
    }

}
```

that can be used like this

```java
ComboBox<Group> groupBox = new ComboBox<>();
groupBox.setItemCaptionGenerator(Group::getName);
groupBox.setItems(groups);

Grid<User> grid = new Grid<>();
grid.addColumn(User::getGroup, new ValueProviderRenderer<>(Group::getName))
.setEditorComponent(groupBox, User::setGroup);
```

**Comment by Legioth** [comment]
I think this is an excellent idea. I'd even suggest making this a feature of the regular `TextRenderer` instead of introducing a separate renderer class for it.

**Comment by heruan** [comment]
Thank you @Legioth, to be honest since I started working on this I would have preferred to avoid using renderers to make to logic more abstract and decoupled from the presentation type of the column. So I came up with #8806 which adds a presentation logic that can be used with any existing renderer.
