### ISSUE TITLE
All components are tested on all supported browsers

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8668]
@pleku commented on [Sat Dec 03 2016](https://github.com/vaadin/framework8-issues/issues/535)

Automated tests on supported browsers for all components:
- Mozilla Firefox 48+, ESR 45
- Internet Explorer 11
- Edge 14+
- Safari 9+
- Google Chrome 53+

Manual testing on mobile browsers, or if possible to setup automated tests, for components that should work on mobile devices:
- Safari 9+ or newer on iOS
- Chrome 42+ or newer on Android

---

@hezamu commented on [Wed Dec 07 2016](https://github.com/vaadin/framework8-issues/issues/535#issuecomment-265388063)

Consider https://hiptest.net/ for managing the testing. You can talk with Designer team, Risto in particular to learn more.

**Comment by hesara** [comment]
Tag selected tests as smoke tests and run them on all supported browsers, including mobile browsers, and run them automatically with a service that supports all of them.

**Comment by hesara** [comment]
Fully automated tests for all supported browsers will not happen by beta1
