### ISSUE TITLE
Regression in Vaadin 8.0.0: fix from #8413 didn't get merged in properly

### ISSUE THREAD

**Issue by bc15** [vaadin/framework#8671]
Fix from issue #8413 (Vaadin 7.7.7) didn't get merged properly into Vaadin 8.0.0, and hence doesn't work in Vaadin 8.0.0
See issue #8413 for more details and testcase.

**Comment by pleku** [comment]
Thanks for reporting this. We are currently in progress of merging the fixes from 7.7.7 #8300 and those will be released in 8.0.1 quite soon. Closing this ticket as it is part of #8300.

**Comment by bc15** [comment]
Still doesn't work in 8.0.1 ...

**Comment by elmot** [comment]
We are still merging fixes. Please wait until 8.0.2.
