### ISSUE TITLE
Valo theme not displaying icons for widgets

### ISSUE THREAD

**Issue by aimran50** [vaadin/framework#8674]
The tree nodes show some weird \foda square image instead of expand/collapse arrows. The richtext also shows just small square boxes like \f12c. When I inspect DOM and check the css this is how it looks like:

.engage .v-richtextarea .gwt-RichTextToolbar-top div[title="Toggle Subscript"]::before {
    content: "\f12c";
}
.engage .v-richtextarea .gwt-RichTextToolbar-top div::before {
    font-family: ThemeIcons;
}

- Vaadin 7.7.7
- Tomcat 8
- JDK 8
- jars included in web app(see screenshot).
- error shows on all latest versions of browsers(firefox, chrome & IE)
- tried with Vaadin versions, 7.7.3 & 7.6.4 and all versions have the same issue.

![firefox_2017-02-21_23-58-54](https://cloud.githubusercontent.com/assets/25983194/23262916/0f47a99e-f9a2-11e6-9ec8-41310c924f9e.png)
![n360_2017-02-22_00-00-18](https://cloud.githubusercontent.com/assets/25983194/23262917/0f481de8-f9a2-11e6-8667-9d68e117dd40.png)
![vaadin-webapp-jars](https://cloud.githubusercontent.com/assets/25983194/23262918/0f4bbc14-f9a2-11e6-9dc1-eb1c1e89334a.png)

**Comment by elmot** [comment]
This issue looks like web font loading fail. That might be caused by various misconfigurations in the project. Could you, please, share a repository with your code or provide an example of the bug?
