### ISSUE TITLE
Vaadin 8 Grid is 5 times slower than Vaadin 7 to render columns

### ISSUE THREAD

**Issue by neerup** [vaadin/framework#8678]
- Upgraded Vaadin 7.7.7 to Vaadin 8.0.0 in my project. 
And now rendering of grids is very slow.
In my application performance has gone from 1.5 Sec to 8 Sec to render 80 columns, 
even when there is no data to show.
This makes migrating to 8.0.0 imposible

- Is there any work around for this?

- I'm using Vaadin version 8.0.0
- Minimal reproducible example
Add this grid to UI

		Grid<String> grid = new Grid<>();
		grid.setSizeFull();
		for (int i = 0; i < 80; i++) {
			grid.addColumn(row -> "novalue").setCaption("Column_" + i).setWidth(200);
		}

**Comment by macjuan** [comment]
There were other reports claiming Grid in 8 is 10 times slower to render. Pretty interesting, especially when I thought that Grid was pretty much the same in 7 and 8.

**Comment by hesara** [comment]
There seem to be issues at attach time (very large number of forced reflows on the client side) when the grid has a large number of columns - already investigating this.

**Comment by hesara** [comment]
Preliminary test results for #8848 tests, grid with 80 columns and 10 rows.
Note that the times are for slow test VMs - significantly faster on a fast local browser.

Browser | V7 Compatibility Grid | V8 Grid
----------- | ---------------------------- | ----------
PhantomJS | 2963 ms | 1657 ms
Chrome | 3305 ms | 1894 ms
Firefox 45 | 6185 ms | 2418 ms
IE11 | 5652 ms | 2262 ms

**Comment by acsadam0404** [comment]
This is still not working correctly. Testing with vaadin 8.1. I made a minimal example that shows that v8 grid is much slower than the v7 table. I don't have measurements as I don't know how can I measure the rendering time, but simply doing a browser refresh on both project is self explanatory.

[grids.zip](https://github.com/vaadin/framework/files/1263832/grids.zip)

**Comment by scrmtrey91** [comment]
Yeah grid is still very slow (thus the UI loading is slower).

**Comment by brunojcm** [comment]
I still feel the same, using Vaadin 8,1.4 TreeGrid. It used to be faster in V7, even with bigger grids.

**Comment by monestri** [comment]
Very slow. 20 tables x 8 columns with no data takes about 8 seconds to load. Using 8.1

**Comment by acsadam0404** [comment]
Opened a new issue for this https://github.com/vaadin/framework/issues/10232 because this one don't have enough attention.
