### ISSUE TITLE
Access to Grid.Column.valueProvider or Grid cell value needed

### ISSUE THREAD

**Issue by aley2003** [vaadin/framework#8680]
The value to display for Vaadin 8 Grid Cells is calculated by the Grid.Column.valueProvider.
We want to export the displayed Grid data (the value of the cells) into Excel/CSV.
Therefore we need access to the valueProvider or the concrete data value for every cell in the Grid.

**Comment by melistik** [comment]
This is also needed for my [vaadin-grid-util](https://github.com/melistik/vaadin-grid-util)
