### ISSUE TITLE
Go through all recently deprecated classes and guide to replacement in javadocs

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8682]
- Vaadin version 8.0.0

I complained this previously as well and I think the issue was already closed, but I guess all classes were not tackled. At least BeanFieldGroup and FieldGroup have absolutely no hint about replacements.

**Comment by mstahv** [comment]
Note, this came up via a comment on a youtube video where user had no clue what to do next.

**Comment by ssindelar** [comment]
I'm currently migrating a medium project with around 30 Views. I noticed the missing migration hints especially with Validators and Converter. The compatibility sources give no clue how to implement common use cases.

* Validation without a Bean
* ConverterFactory. I central place to handle all the conversion. I think this is no longer possible.
* More advanced stuff like replacing code that uses Field<?>. AbstractField can't be used in all cases. E.g. ComboBox is no subclass of AbstractField. I had to use the generic type

>  <T extends Component & Focusable & HasValue<?>>

 to model what I needed from Field<?>

**Comment by krasnyt** [comment]
I would also like to know why was Calendar component excluded or if there will be a replacement soon in future releases. For backwards compatibility now we are forced to have the 'compatibility' dependency on classpath (+ including warnings due to deprecating this class).

**Comment by pleku** [comment]
@ssindelar thanks for the feedback. I've created #8692 for the missing methods in grid, that is simply just a regression we've missed.

**Comment by pleku** [comment]
@krasnyt while we don't have any active plans on developing the Calendar component further, we agreed that it could still be worthwhile to make a version of it which has Java 8 style API's and supports `DataProvider` instead of Container`. However, I cannot currently give any guarantees on when that will be done. See #8217
