### ISSUE TITLE
Grid in 8.0 is missing headerVisible footerVisible methods

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8692]
The missing methods from version 8 compared to 7 are
* `setHeaderVisible(boolean) : void`
* `isHeaderVisible() : boolean`
* `setFooterVisible(boolean) : void`
* `isFooterVisible() : boolean`

**Comment by asashour** [comment]
I believe this should be closed, the mentioned methods are implemented since `8.1.1`
