### ISSUE TITLE
Migration to Vaadin 8

### ISSUE THREAD

**Issue by mbx2015** [vaadin/framework#8699]
When Migrated to vaadin 8, My vaadin designs created with vaadin designer cannot be open, I get the error com.vaadin.v7.ui.TextField .... cant be cast to com.vaadin.ui.TextField ...

**Comment by fante76** [comment]
You need to substitute every component of version 7 with new of version 8. You can do it manually or with the migration tool provided by Vaadin Team (I preferred manual choice).
Also check the version attribute in designer html files to be 8.0.5.
