### ISSUE TITLE
Unnecessary sroll down after refreshRowCache() in Table with Chrome 56+ browser

### ISSUE THREAD

**Issue by Scraelos** [vaadin/framework#8707]
Vaadin version 7.7.7
Browser version Chrome 56 and newer.

How to reproduce
1. Create UI with Table which contains 1000 rows
2. Open it with Chrome 56+ browser or other browser with chrome 56+ engine.
3. Scroll down, so Table requests next page(for example scroll down to item 100).
4. Click 'refresh' button to make table.refreshRowCache()
5. As you can see, table scrolls down without any user action after table.refreshRowCache() is done.
6. You can not reproduce such behaviour with other non-chrome engine browser(IE, Firefox, etc).

Working example http://178.236.245.251:8383/tabletest/
Source code:
[vaadin-app.zip](https://github.com/vaadin/framework/files/806031/vaadin-app.zip)

**Comment by rubberony** [comment]
I'm also seeing this on Vaadin 6.x and Vaadin 7.x

**Comment by rubberony** [comment]
Struggling to make sense of their issue tracking but it looks like maybe
https://bugs.chromium.org/p/chromium/issues/detail?id=687061

**Comment by Scraelos** [comment]
can someone from vaadin team investigate this issue?

**Comment by snp0k** [comment]
Having this problem with Vaadin 6.8.15 and 8.0.6 on Chromium 58.0.3029.110
But looks good on Firefox 53.0.3

**Comment by Catchwa** [comment]
> Struggling to make sense of their issue tracking but it looks like maybe
https://bugs.chromium.org/p/chromium/issues/detail?id=687061

The bug @rubberony found seems to have been fixed in the latest Chrome (but the bug still persists for me). I'd rather not have to make my users switch their preferred browser.

**Comment by gWestenberger** [comment]
We had a similar problem with Table. It was caused by Chrome's "scroll anchoring" feature, which is enabled by default since Chrome 56. We solved it by adding the following rule to our CSS:

`.v-table, .v-table * {
  overflow-anchor: none;
}
`

**Comment by rubberony** [comment]
@gWestenberger  Nice one! This appears to work.  I did find find a chrome issue that explains this.  Sorry about the previous one guys.
https://bugs.chromium.org/p/chromium/issues/detail?id=594886

**Comment by Scraelos** [comment]
@gWestenberger We can not express how we happy about this! Thank you very much!
