### ISSUE TITLE
Please publish JPA Container for Vaadin 8

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#8717]
Currently, including https://vaadin.com/directory#!addon/vaadin-jpacontainer in your Vaadin 8 project will fail, either at compile time or at runtime: 
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.vaadin.addon.jpacontainer.JPAContainer, unresolved supertypes: Indexed
    class com.vaadin.addon.jpacontainer.EntityContainer, unresolved supertypes: Container, Sortable, ItemSetChangeNotifier, Buffered, Filterable
    class com.vaadin.addon.jpacontainer.HierarchicalEntityContainer, unresolved supertypes: Hierarchical
```

To allow gradual migration to Vaadin 8, could you please consider releasing a special version of JPA Container which is only compatible with Vaadin 8 and v7 Grid?

**Comment by mvysny** [comment]
I apologize, I should have opened this bug here: https://github.com/vaadin/jpacontainer

**Comment by mvysny** [comment]
Anyway, this fork is Vaadin8-compatible: https://github.com/mvysny/jpacontainer

**Comment by mstahv** [comment]
New build is in the directory.

**Comment by hesara** [comment]
Marking milestone "invalid" as ticket in the wrong repository even though new version released.
