### ISSUE TITLE
Grid header is not rendering components in joined cells (8.0)

### ISSUE THREAD

**Issue by ChristianRosenau** [vaadin/framework#8722]
This affects Version 8.0!
When I set a component to a single header field, it is rendered fine. But when I join columns and set a component to this new created cell, nothing is rendered at all. (When only setting text or html, it works fine btw.). Maybe this bug relates to the data cell rendering, which (currently) doesn't allow components in cells.

See example code:
```
static class TestModel 
{
	String test;
	String combine1;
	String combine2;
}

Grid<TestModel> grid = new Grid<>(TestModel.class);
HeaderRow headerRow = grid.appendHeaderRow();
headerRow.getCell("test").setComponent(new Label("I am visible"));
headerRow.join("combine1","combine2").setComponent(new Label("I am not visible"));
```

**Comment by tsuoanttila** [comment]
@ChristianRosenau Thank you for the bug report. This looks like a regression in the header handling. It is not related to components in body cells, since it is done in a completely different way. Indeed the code you sent should work.
