### ISSUE TITLE
UI freezes when navigating away form Grid View

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#8748]
Using Vaadin 8.0.0, I have 2 Views registered with Navigator, one with a Grid component and another one with just a Label. Navigating from the Grid View in to the Label View using a Button ClickListener results in the following client side exeption. This exception freezes the Vaadin UI (eternally flashing loading indicator) and the user needs to refresh the browser tab to get back in to a usable state.

No custom client side used. Widgetsets on classpath: com.vaadin.addon.spreadsheet.Widgetset, com.vaadin.addon.charts.Widgetset and com.vaadin.DefaultWidgetSet

```
Error: Uncaught client side exception
Given Column does not exist.
java.lang.AssertionError: Given Column does not exist.
   at Unknown.vC_g$(AppWidgetset-0.js@8:9842)
   at Unknown.qWd_g$(AppWidgetset-0.js@9:174843)
...
```

Stack trace from superdevmode:

<img width="1298" alt="screen shot 2017-03-06 at 18 10 18" src="https://cloud.githubusercontent.com/assets/886091/23621237/1f538794-029a-11e7-98f0-2165cd31fb9a.png">

Video demo w/o debug mode:
https://youtu.be/h2OD9jdXhwk
Video demo w/ debug mode:
https://youtu.be/GOWIkmgfrkE

**Comment by Artur-** [comment]
Code to reproduce?

**Comment by Wnt** [comment]
I think it's the multi selection mode that triggers it: https://gist.github.com/Wnt/53e3615615ac89a19953e243ad61055a

**Comment by Artur-** [comment]
Partly fixed by #8329 it seems

**Comment by Wnt** [comment]
I tried running the same application with current master + @Artur-'s patch. Now I get a different error message when the Grid View is unloading:
Error: java.lang.IllegalArgumentException: count must be between 0 and the current number of columns (0)
Stack trace in superdevmode:
https://youtu.be/2xJUqpyXhtA

**Comment by Artur-** [comment]
Seems I simplified the test case too much
