### ISSUE TITLE
When using TreeGrid, I want to decide which rows should be expanded, so that I can show the necessary data to the user

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8759]
```java
/**
 * Expands the given item.
 * <p>
 * If the item is currently expanded, does nothing.
 * If the item does not have any children, does nothing.
 * 
 * @param item
 *      the item to expand
 */
public void expand(T item) { ... }
```

For implementation, there are two cases:
1. The item is currently visible -> just expand it and push _enough items_ to browser
2. The item is not visible -> need store the item and compare all fetched items to that one. When it is finally fetched, it should set as expanded and push those rows to the client side.

**Comment by pleku** [comment]
Another thing is, that the user might want to specify any such node that is initially expanded, to be something that cannot be collapsed at all. This feature is present in one customer app, where all root level items are not collapsible, but always expanded, hiding the collapse/expand toggle.

**Comment by hesara** [comment]
It looks like we should provide an expand(T item) method instead of just initial expand support. Thus, implementing initial expand separately might just lead to API bloat and more maintenance overhead.

See also related issues #8877 and #8890 that might be resolved together with this.

**Comment by pleku** [comment]
Ticket updated from _expanding initially_ to _expand(T item)_.

Yet another thing that should be concerned with this is the `collapse(T item)` method.
