### ISSUE TITLE
Combobox in embedded Vaadin 8

### ISSUE THREAD

**Issue by ropoman** [vaadin/framework#8778]
Hi,

After migration to Vaadin 8 I find that my comboboxes have a new bug. When opened they display the selection choices only at the correct position when the window is at top position and not scrolled. When I scroll down the combobox content is displayed too high. The more I scroll down the greater is the offset to the correct position.

I am embedding Vaadin in a div as described in https://vaadin.com/docs/-/part/framework/advanced/advanced-embedding.html as you can see in http://pastebin.com/ZKPMMghC

This is the Vadin component to reproduce the problem:
```
public class Test extends UI {
	@Override
	protected void init(VaadinRequest vaadinRequest) {
		VerticalLayout vl = new VerticalLayout();
		for (int i=0; i<20; i++)
			vl.addComponent(new Label(""+i));
		ComboBox<String> cb = new ComboBox<>();
		vl.addComponent(cb);
		for (int i=0; i<20; i++)
			vl.addComponent(new Label(""+i));
		setContent(vl);
 	}
}
```

Thanks,
Roland

**Comment by hesara** [comment]
On which browsers are you seeing this? We have seen a similar issue with Firefox and IE11 (ComboBoxPopupWhenBodyScrollsTest in the framework project), but not Webkit/Blink based browsers such as Chrome, though I haven't tested this with your embedding code.

**Comment by ropoman** [comment]
I see the problem in Firefox and IE. There is no issue in Chrome

**Comment by hesara** [comment]
I may have found a fix for this, though not tested yet in the embedded case - will see if this makes it to the next maintenance release or the one after it.

**Comment by ropoman** [comment]
I still have this problem in 8.0.3

**Comment by ropoman** [comment]
I still have this problem only in a very special case: Only when using the Designer and only when the ComboBox is within a CssLayout. I was unable to reproduce the problem with Java alone. I attach the design
TestDesign.html.txt
[TestDesign.html.txt](https://github.com/vaadin/framework/files/879401/TestDesign.html.txt)
