### ISSUE TITLE
Allow more efficient usage of ValueContext with Conversion through Binder

### ISSUE THREAD

**Issue by peterl1084** [vaadin/framework#8780]
Binder allows applying Converters to Bindings which are automatically executed when data flows from Fields to Bean and the other way around. 

Vaadin 8 introduced concept of ValueContext that describes the context of the conversion in terms of possible conversion instance specific meta data. This ValueContext is potentially very useful as it allows passing in data to singleton converters which are intended to be immutable and cannot accept outside configuration.

Right now Binder$BindingImpl has protected method createValueContext() which I would like to be able to overwrite. Unfortunately this is next to impossible as Binder$BindingBuilderImpl directly instantiates BindingImpls making it very difficult for adding code in between. Hence, I think easiest way would be to allow specifying with 'with-syntax' a ValueContextProvider.

For example

`withConverter(Converter<TARGET, NEWTARGET> converter, ValueContextProvider vcp)`

where ValueContextProvider would be function returning ValueContext instance.

The default implementation could just return the ValueContext as is.

This way developer could specify his own ValueContext where he could easily append meta data for binding specific conversion that is not defined through Converter, further custom Converter implementations could then be made which utilize the already existing convertToModel, convertToPresentation methods where the ValueContext is already passed into.

**Comment by peterl1084** [comment]
https://github.com/vaadin/framework/pull/8794

**Comment by Legioth** [comment]
One drawback with this approach is that the `Converter` implementation would have to do `instanceof` checks on the `ValueContext` instance that it receives.

What's the purpose of having a singleton converter instance? Would it make more sense that you instead have a singleton converter provider with appropriate methods for creating configured converter instances?

**Comment by peterl1084** [comment]
The basic converters implemented currently as is would not require changes. This feature is more about allowing specialized converters to receive such data from outside if necessary. Singleton converters are just a way to minimize overhead and memory consumption in such environments where they can easily be defined for example through dependency injection capable beans.

Also, as the ValueContext is already passed into the converters in Converter interface level, leveraging this potential with developer providable implementation would only make the abstraction better.

**Comment by peterl1084** [comment]
Right now another way to do what I'd like to is to set this "meta data" as the data of the component that the conversion concerns. Then read this data through the getData method within the converter implementation. Although this sounds at least to me much more a kludge than having a framework supported abstraction for determining the actual conversion specific context.

Another option would be to allow easier overwriting of Binder related value context creation.

**Comment by Legioth** [comment]
> Singleton converters are just a way to minimize overhead and memory consumption

Except that more-or-less exactly the same amount of memory would instead be used for each `ValueContextProvider` instance that is in use.

You can then instead achieve the same result by wrapping the singleton converter in a custom converter class that creates a custom `ValueContext` and passes that to the original converter. In that way, there wouldn't even be any need for changes to the framework,

I'm wouldn't want to add functionality that explicitly encourages doing things in a way that requires `instanceof` checks for doing anything practical.
