### ISSUE TITLE
Column should be non-sortable by default (at least with lazy loading data providers)

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8792]
Vaadin version 8.0.1

If developer makes a simple lazy loading connection with a Grid and the backend, columns can be sorted from the UI, but the UI seems broken as nothing happens in the listing. It would be better if columns would be non-sortable by default and sortable only when the developer knows he can do the sorting.

It is possible, but difficult to find, to configure all columns to be non-sortable with this call:

            grid.getColumns().forEach(c -> c.setSortable(false));

**Comment by pleku** [comment]
Need to decide whether doing this change now affects the behavior or not. Might atleast disable sorting by default when a lazy data provider is used, but not with a in-memory one ?

**Comment by mstahv** [comment]
For in memory listings, for properties that framework can sort, the sorting should definitely be on by default.
