### ISSUE TITLE
Upload component theming wrong when inside a LAYOUT_COMPONENT_GROUP

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#8796]
Upload component should get non-rounded borders on the sides where there are more components when it's positioned inside a LAYOUT_COMPONENT_GROUP. 
What happens instead: all corners are rounded.
Example code:
```
mainMenuLayout = new CssLayout();
mainMenuLayout.addStyleName(ValoTheme.LAYOUT_COMPONENT_GROUP);

Upload upload = new Upload();

mainMenuLayout.addComponent(upload);

MenuItem miActionParent = menuBar.addItem("Action", null);
mainMenuLayout.addComponent(menuBar);

miActionParent.addItem("Delete File", e -> {});
```
What it looks like in the UI:
<img width="583" alt="screen shot 2017-03-09 at 13 55 03" src="https://cloud.githubusercontent.com/assets/886091/23751207/8b6a676c-04d0-11e7-88a6-4209a3c69578.png">

**Comment by pleku** [comment]
v7 issue #8824
