### ISSUE TITLE
Declarative for FormLayout with no margin is incorrect

### ISSUE THREAD

**Issue by ripla** [vaadin/framework#8800]
The following test case works with Framework 7 but fails in Framework 8, since the default margins changed. The problem is in detecting the default margin and not writing the changes to declarative.

```
@Test
public void formLayoutMarginSerializationTest() throws IOException {
   ByteArrayOutputStream baos = new ByteArrayOutputStream();
   FormLayout formLayout = new FormLayout();
   formLayout.setMargin(false);
   Design.write(formLayout, baos);
   FormLayout serializedFormLayout = (FormLayout) Design.read(new ByteArrayInputStream(baos.toByteArray()));
   Assert.assertEquals(formLayout.getMargin(), serializedFormLayout.getMargin());
}
```

**Comment by amahdy** [comment]
I have a design written in v7. vaadin:upgrade8 then text editor and changed `vaadin7` to `vaadin`.
Now whenever I open the design file and try to change margins of the formLayout, it does not save changes.

Problem in Eclipse and IntelliJ.

I can change margins if I start a new design. The problem only with the migrated file.

Here is how the broken formLayout is declared:

```html
<vaadin-form-layout size-auto>

</vaadin-form-layout>
```
