### ISSUE TITLE
Allow Converters to have error message provider

### ISSUE THREAD

**Issue by peterl1084** [vaadin/framework#8809]
Right now it's possible to define various Converters such as StringToBigDecimalConverter which all have conversion error message String as their constructor parameter. In some cases where I18N is used, it would be more beneficial to allow using error message supplier or Supplier<String> as additional value.

This way the converter could ask for translated error message from whatever provider instance.

**Comment by mstahv** [comment]
Needed to get this example upgraded to Vaadin 8: https://github.com/peholmst/vaadin4spring/blob/master/samples/i18n-sample/src/main/java/org/vaadin/spring/samples/i18n/TranslatedUI.java

**Comment by Legioth** [comment]
There's already something similar for validators with `ErrorMessageProvider`. Would probably make sense to also support the same for converters.

**Comment by pleku** [comment]
Slightly related to #8379

**Comment by pleku** [comment]
This is still very much valid.
