### ISSUE TITLE
Grid row details has wrong height with dynamic-height components

### ISSUE THREAD

**Issue by heruan** [vaadin/framework#8813]
When the grid details generator produce a container with components having dynamic-height (e.g. listings with data-providers) the details height is wrong. For example:

```java
grid.setDetailsGenerator(item -> new CheckBoxGroup<>("Actions", actions));
```

produces

<img width="521" alt="screen shot 2017-03-10 at 17 53 07" src="https://cloud.githubusercontent.com/assets/851745/23804509/7497bd1a-05ba-11e7-9c2a-7fe4df27dc0f.png">

Wrapping the `CheckBoxGroup` in a `VerticalLayout` doesn't help, neither does setting explicit heights.

**Comment by tsuoanttila** [comment]
This seems to be a bug in CheckBoxGroup not telling its size correctly when Grid asks for it. Works with old OptionGroup out of the box.

**Comment by tsuoanttila** [comment]
After taking a closer look at this issue, it looks like a duplicate of #7341

The component does report its size in the browser as it is supposed, but the spacer is already opened and won't react to the resize.

**Comment by heruan** [comment]
Thank you @tsuoanttila for the good catch, I totally missed that (I admin issues from @vaadin-bot seem quite abandoned, but I understand the migration here created quite an overhead on old issues). I'll keep an eye on that too!
