### ISSUE TITLE
Need to ignore "session expired" warning when navigating to a bookmarked URL

### ISSUE THREAD

**Issue by jflamy** [vaadin/framework#8814]
I have an application with many "slave" public-address displays that get updated via server push (used in a sports competition to display results to the public)
It is sometimes necessary to restart the web server during a competition.  The new "communication lost, retrying" feature is perfect, *except* that when the communication is re-established with the new restarted web server, there is the "Hit ESC to continue" prompt, which ruins everything.   Each UI is navigable, and has everything it needs in the URI.

Please make the prompt optional, and allow an automatic refresh when connection is re-established.

**Comment by jflamy** [comment]
A solution to this problem is provided in this forum post.
https://vaadin.com/forum#!/thread/15866827/15949356

**Comment by TatuLund** [comment]
The answer is to apply `messages.setSessionExpiredURL(null);` when setting custom SystemMessagesProvider in servlet.
