### ISSUE TITLE
Update documentation to explicitly mention that JSR-303 annotations won't be used when binding with ValueProvider.

### ISSUE THREAD

**Issue by dve** [vaadin/framework#8815]
- Vaadin version : 8.0.2
- Description of the bug
If you bind a field to a bean property with validation annotations, one has to use `BeanValidationBinder.bind(String)` instead of `BeanValidationBinder.bind(ValueProvider, Setter)` because the later ones ignores the validation annotations.
- If possible, minimal reproducible example

```
import javax.validation.constraints.Size;

import com.vaadin.data.BeanValidationBinder;
import com.vaadin.data.Binder;
import com.vaadin.ui.TextField;

public class Test {
	private TextField textField;
	private Bean value;

	public static class Bean {
		@Size(min = 3)
		private String property;

		public String getProperty() {
			return property;
		}

		public void setProperty(String property) {
			this.property = property;
		}
	}

	public void buildForm() {
		Binder<Bean> binder = new BeanValidationBinder<>(Bean.class);
		// this works:
		// binder.forField(textField).bind("property");

		// but not this:
		binder.forField(textField).bind(Bean::getProperty, Bean::setProperty);

		binder.setBean(value);
	}
}
`

**Comment by Legioth** [comment]
Cannot do anything about this. There's nothing in Java that allows us to find those annotations based on `Bean::getProperty` or `Bean::setProperty` because of type erasure. When using `"property"` instead, we can use reflection based on the bean type to find everything needed.

The only thing we could do is to somehow improve documentation about this limitation.

**Comment by dve** [comment]
What about guessing it:

1. strip is/set/get from method names
1. make the first letter lower case
1. if there is a property with that name use it

> The only thing we could do is to somehow improve documentation about this limitation

That should be definitely done: it took me some time to find out why validators are ignored.

**Comment by Legioth** [comment]
The method name is not known either. The Java compiler changes `Bean::getProperty` into something similar to `bean -> bean.getProperty()` which for the implementation of  the `bind` method looks like any other implementation of the `ValueProvider` interface.

> That should be definitely done: it took me some time to find out why validators are ignored.

Where in the documentation would it has been most useful to mention this? I'm just trying to figure out what would be the most impactful place(s) to add it.

**Comment by dve** [comment]
Ok, I did not know about the javac behavior .

It should be in the java doc of  `Binder#bind` and in the Book of Vaadin.

**Comment by Legioth** [comment]
The problem with `Binder#bind` javadocs is that that the same javadocs are shared between the regular `Binder` and `BeanValidationBinder`. It might still make sense to add it there, but anything such would be only "overhead" from the perspective of someone who doesn't use bean validation annotations.

I was actually assuming that this was already covered by Book of Vaadin, but I cannot find it explicitly mentioned anywhere. I guess https://vaadin.com/docs/-/part/framework/datamodel/datamodel-forms.html#datamodel.forms.beans would be the natural place to mention it there.

**Comment by dve** [comment]
The link to the docs is where I would also place it. If you think its too much overhead for "non annotations user" then place it in the class level javadoc of `BeanValidationBinder` - I took a look into it ;-)

Is there at all a senece in using `BeanValidationBinder.bind(ValueProvider, Setter)`? If not maybe a waring in the log would be nice.

**Comment by Legioth** [comment]
`BeanValidationBinder.bind(ValueProvider, Setter)` is still useful if you also have a "computed property" that you want to bind, even though use is most likely quite uncommon.

**Comment by stadler** [comment]
+1 Please update the documentation. It is really frustrating to try to get this to work and in the end discover that it doesn't work due to a known limitation.

**Comment by NBau** [comment]
Additionally, it would be nice to allow the use of `BeanValidationBinder.bind(ValueProvider, Setter, AnnotatedElement)` for cases where the getter and setter need special handling (e.g. some JAXB generated beans do not follow strict bean rules).
