### ISSUE TITLE
V7 compatibility Upload throws a client sided exception at the end of the upload

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8859]
Version: 8.0.2

Code to reproduce:

        final Upload upload = new Upload();
        upload.setCaption("Raw Vaadin upload");
        
        upload.setReceiver(new Upload.Receiver() {
            @Override
            public OutputStream receiveUpload(String filename, String mimeType) {
                return new ByteArrayOutputStream();
            }
        });

<img width="731" alt="screen shot 2017-03-16 at 21 54 08" src="https://cloud.githubusercontent.com/assets/1478052/24016078/6f550e38-0a93-11e7-9d87-24f42214c3d7.png">

**Comment by mstahv** [comment]
@elmot , was this already fixed here?  https://github.com/vaadin/framework/commit/264ee7696568827815604f1e22ce7e330775b3ce

Next question, when is it out?

**Comment by mstahv** [comment]
Can't reproduce this anymore with 8.0.3

**Comment by elmot** [comment]
Most probably fixed with #8782
