### ISSUE TITLE
Vaadin Grid looses scroll bars when size exceeds 500.000 rows

### ISSUE THREAD

**Issue by KyleRogers** [vaadin/framework#8860]
Vaadin Version: 7.7

We have a huge Grid with > 500.000 rows using LayzQueryContainer add-on. If the number of rows hits a certain limit (depending on browser) the scrollbars get lost and no scrolling is possible at all.

The table uses filtering thus a user ~can~ reduce the amount of rows displayed. Nevertheless initially he'll see all possible rows. The problem is related to #985 but applied to Grid: Depending on the browser there is a limit (starting with about 200.000 rows in IE up to 500.000 rows in Firefox/Chrome).

It is NOT an option to show a message to the user and force him to apply filters. I don't think many users will scroll 500.000+ rows but they should not be irritated by lost scroll bars or messages popping up. We do use LQC under the hood, thus there are not really 500.000 rows available at a time but there will be the illusion of a large data set that could be scrolled.

If there is a workaround, please advice.

Side note: We cannot upgrade to Vaadin 8 because our customer requires us to support IE 8 because he thinks lots of his own customers still use IE 8 and he fears to loose them.

I also found https://dev.vaadin.com/review/#/c/2756/ implementing a virtuall scroll bar that might fix the issue but it seems to be abandoned.

**Comment by Artur-** [comment]
This is the same issues as #6290 and upgrading to Vaadin 8 won't make a difference as the client side implementation of Grid is mostly the same

**Comment by KyleRogers** [comment]
Closing as Duplicate of #6290 - hopefully you'll address the issue soon. Especially if you [advertise lazy loading](https://vaadin.com/c/blogs/find_entry?noSuchEntryRedirect=https%3A%2F%2Fvaadin.com%2Fblog%3Fp_p_id%3D115%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-2%26p_p_col_count%3D2%26_115_struts_action%3D%252Fblogs_aggregator%252Fview_entry%26_115_entryId%3D15465231&entryId=15465231) and displaying large data sets in grid more and more users will run into this problem.

I'm in the bad situation that I've told my customers that we use super cool frontend technology that doesn't need pagination and will be able to handle large amounts of data and now I need to explain that we need to find a workaround ....
