### ISSUE TITLE
Make edited row available from com.vaadin.ui.components.grid.EditorSaveEvent

### ISSUE THREAD

**Issue by bobsyouruncle27** [vaadin/framework#8862]
In the new Vaadin 8 Grid, the edited row is not accessible by an EditorSaveListener without either binding to a new bean or resorting to reflection.

When a user clicks the "save" button after editing a row in a grid, the edited row needs to be available for persistence/etc. It is currently stored in a private field in com.vaadin.ui.components.grid.EditorImpl, but is not made available through any interface method.

I don't believe writing to a new bean instance (using Binder#writeBean) is acceptable as the only way to get the edited values, as (for example) the bean may be a persisted entity with a generated ID that shouldn't be "new"ed (and as there is no way to get the row being edited to my knowledge, so you would have to call Binder#writeBean with a newly created bean only).

See:
[https://vaadin.com/forum#!/thread/15416620](url)
[http://stackoverflow.com/questions/42495964/vaadin-8-grid-editorsavelistener](url)

**Comment by Legioth** [comment]
This has been fixed through #8658 and will be included in Vaadin Framework 8.0.3 that is currently being released.
