### ISSUE TITLE
Allow use of HTML in Label description

### ISSUE THREAD

**Issue by m1h43l** [vaadin/framework#8865]
In Vaadin 7 the description of a Label could contain HTML code. But now in Vaadin 8 everything is renderered as plain text.

I would like to use it in the following way:

```
Label l = new Label("Mihael Schmidt");
l.setDescription("E-Mail: <a href="mailto:mihael@rpgnextgen.com">mihael@rpgnextgen.com</a>");
```

Tested with Vaadin 8.0.0

**Comment by hesara** [comment]
You now need to use l.setDescription("myhtml", ContentMode.HTML) to explicitly allow HTML in captions.

**Comment by m1h43l** [comment]
Thanks.
