### ISSUE TITLE
Binder not working with nested properties

### ISSUE THREAD

**Issue by m1h43l** [vaadin/framework#8868]
In Vaadin 7 there was the BeanFieldGroup which could be used to bind UI components to nested properties of a bean. The Vaadin 8 changelog says that Binder replaces FieldGroup and BeanFieldGroup. But it doesn't seem to support nested properties.

My case:
```
Binder<Employee> binder = new Binder<>(Employee.class);
binder.forField(country).bind("address.country");
```
This results in an Exception. "Could not resolve property name address.country ..."

My research pointed me to the following call stack:
```
Binder(Class<BEAN> beanType)
  -> BeanPropertySet.get(beanType)
       -> BeanPropertySet(Class<T> beanType)
           -> BeanUtil.getBeanPropertyDescriptors(Class<?> beanType)
               -> getPropertyDescriptors(BeanInfo info);
               -> getBeanPropertyDescriptors(Class<?> cls)
```

It seems the two methods from BeanUtil which **do** support nested properties ( getPropertyDescriptor and getPropertyType ) are not used in this case.

Now how to bind to nested properties?

Tested with Vaadin 8.0.0.

**Comment by m1h43l** [comment]
Seems a duplicate of  #8384

**Comment by Legioth** [comment]
Yes, this is indeed a duplicate.
