### ISSUE TITLE
V8 : Programmatically open grid in editable mode

### ISSUE THREAD

**Issue by jflamy** [vaadin/framework#8870]
There is no way to open a grid for editing purposes.  Please allow editing on open -- programmer can provide filtering or user can navigate.    Simple-clicking on a cell in immediate mode is acceptable and intuitive. Nothing in the interface currently indicates need to double-click or hit enter, completely unsable for many cases where a table in edit mode worked just fine.   Don't want to mix grid and table in my interface.

**Comment by Legioth** [comment]
This is already discussed and tracked in https://github.com/vaadin/framework/issues/8820.
