### ISSUE TITLE
V8: Grid ButtonRenderer "Edit" button example needed

### ISSUE THREAD

**Issue by jflamy** [vaadin/framework#8871]
Need to document how an Edit button could be added to a grid row, triggering a doEdit(key) on the server.

**Comment by TatuLund** [comment]
Questions like this gets better served on our forum: https://vaadin.com/forum

Answer to your question, check https://github.com/vaadin/grid-renderers-collection-addon/ for reference. E.g. DeleteButtonRenderer most likely has similarity to what you are looking for.
