### ISSUE TITLE
Add clicklistener to notifications

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#888]
**Originally by @Artur-**

___
In some cases it would be very useful to be able to show a notification, e.g. tray notification, and react if the user clicks on it. An example would be a messaging (e.g. mail) application where a tray notification is shown when a message arrives and if the user clicks on the notification the full message is shown in a popup. No event would be fired if the notification fades away by itself.

___
 Imported from https://dev.vaadin.com/ issue #3638

**Comment by asashour** [comment]
I would like to get some insight how best to create a PR for this.

What are the restrictions for backward-compatibility?

Should `Notification` extends `AbstractExtension`, or should we have a new Notification class?

**Comment by Artur-** [comment]
I would aim to do this by making `Notification` extend `AbstractExtension`, as long as it is possible to keep the public API the same. Having multiple `Notification` classes would just be confusing
