### ISSUE TITLE
DataProvider.size() performance

### ISSUE THREAD

**Issue by casz69** [vaadin/framework#8885]
Hi, the interface com.vaadin.data.provider.DataProvider need to know how much records are in the source before fetch records.

This is a big performance problem for SQL backend because need to execute a count before fetch.

This compromises the performance, in big querys, when you must count a lot of records that will not be presented because they are not on the first pages. 

There is some solution to this issue?

**Comment by casz69** [comment]
I found same Issue: 

DataProvider API requires developer to report the size fo the data #8492

**Comment by hesara** [comment]
Closing this as duplicate of #8492.
