### ISSUE TITLE
Vaadin8 Framework hang if AbstractBackEndDataProvider.size() is greatest than number of records

### ISSUE THREAD

**Issue by casz69** [vaadin/framework#8897]
We are a Grid with a DataProvider for SQL sentences extending AbstractBackEndDataProvider.

We do one query for sizeInBackEnd() and other query for fetchFromBackEnd().

If between the query to get the size () and the other to get the fetch (), someone deletes records, then size() will be greatest than records returned by fetch().

In this case framework will loop doing get URL.

In our example size() return 5 but fetch only return 4 records.

Looping URL:

`http://localhost:18008/SaaeView/SegUI/UIDL/?v-uiId=0`

Post Data:
`{"csrfToken":"9814eddb-e12e-4c9b-b25d-9a99a290bfc0","rpc":[["48","com.vaadin.shared.data.DataRequestRpc","requestRows",[4,1,0,0]],["48","com.vaadin.shared.data.DataRequestRpc","dropRows",[[]]]],"syncId":47489,"clientId":47489}
`
Response:
`for(;;);[{"syncId": 48106, "clientId": 48106, "changes" : [], "state":{}, "types":{"48":"31"}, "hierarchy":{"48":[]}, "rpc" : [["48","com.vaadin.shared.data.DataCommunicatorClientRpc","setData",[4,[]]]], "meta" : {}, "resources" : {}}]
`
Another problem is that "for (;;);" is not a JSON response.

**Comment by Artur-** [comment]
Same problem as #8479

**Comment by pleku** [comment]
Closing as duplicate, lets keep discussion in #8479
