### ISSUE TITLE
Any plan to consider Kotlin DSL for Vaadin?

### ISSUE THREAD

**Issue by linux-china** [vaadin/framework#8900]
Now there are some Kotlin DSL for Vaadin, such as kaadin, https://github.com/mvysny/vaadin-on-kotlin.  You guys have plan to implement offical one?

**Comment by pleku** [comment]
No we don't have any plans for making official support at this phase. Closing this ticket, but if there would be a huge user demand for it in comparison to the "vanilla Java" or Scala version, then things might change.

Martin's add-on is probably as official as it gets, and I'm sure he is willing to accept contributions to that.

**Comment by linux-china** [comment]
@pleku  thanks. I will  watch on https://github.com/mvysny/vaadin-on-kotlin
