### ISSUE TITLE
ListSelect's addStyleName does not work

### ISSUE THREAD

**Issue by tmarlok88** [vaadin/framework#8901]
If I add a stylename to a ListSelect, it is not present in the generated HTML code.
example:
```
        ListSelect<String> testselect = new ListSelect<>();
        testselect.setItems(Arrays.asList("abc","def","ghi"));
        testselect.addStyleName("teststyle");
        right.addComponent(testselect);
```
the generated HTML:
`<div class="v-select"><select class="v-select-select" multiple="" size="10" tabindex="0"><option value="1">abc</option><option value="2">def</option><option value="3">ghi</option></select></div>`

whereas a NativeSelect (for example) works fine:
```
        NativeSelect<String> testselect = new NativeSelect<>();
        testselect.setItems(Arrays.asList("abc","def","ghi"));
        testselect.addStyleName("teststyle");
        right.addComponent(testselect);
```
html:
`<div tabindex="0" style="outline-style: none;" class="v-select teststyle -teststyle"><select class="v-select-select" tabindex="0"><option value=""></option><option value="1">abc</option><option value="2">def</option><option value="3">ghi</option></select></div>`

p.s.: setPrimaryStyleName() works as expected...

vaadin version is 8.0.3

**Comment by tsuoanttila** [comment]
Fix for this issue was picked for 8.0.6
