### ISSUE TITLE
Adding keyboard shortcut listener (ENTER) prevents value changes in Datefield (regression)

### ISSUE THREAD

**Issue by leidra** [vaadin/framework#8905]
Vaadin version 8.0.3 and 8.1.alpha1

com.vaadin.v7.ui.DateField is not sending the value to the server when the user writes the date in the text field. I have also tested it using plain V8 and it neither works.

[date-test.zip](https://github.com/vaadin/framework/files/861065/date-test.zip)

**Comment by mstahv** [comment]
Tried it and it appears that ENTER shortcut listener now prevents the datefield to do the value change listener (worked fine in V7) .This happens for both v7 and the new DateField. Modified the description a bit. The code to reproduce (derived from @leidra's zip):

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();

        final ShortcutListener shortcutListener = createShortCutListener();

        DateField dateField =  new DateField();
        dateField.setDateFormat("dd/MM/yyyy");

        dateField.addValueChangeListener(new Property.ValueChangeListener() {
            @Override
            public void valueChange(Property.ValueChangeEvent event) {
                Notification.show(event.getProperty().getValue().toString());
            }
        });

        dateField.addShortcutListener(shortcutListener);

        layout.addComponents(dateField);
        
        setContent(layout);
    }

    private ShortcutListener createShortCutListener() {
        return new ShortcutListener("caption", ShortcutAction.KeyCode.ENTER, null) {
            @Override
            public void handleAction(Object sender, Object target) {
                Notification.show(retrieveValueAsString(target));
            }

            private String retrieveValueAsString(Object target) {
                Object value;
                value = ((Field) target).getValue();
                return (value != null) ? value.toString() : null;
            }
        };
    }

**Comment by TatuLund** [comment]
Closing as duplicate to https://github.com/vaadin/framework/issues/10854
