### ISSUE TITLE
Static-initializer of ScssStylesheet overrides existing logging configuration

### ISSUE THREAD

**Issue by retomerz** [vaadin/framework#8907]
The static-initializer of com.vaadin.sass.internal.ScssStylesheet
loads a logging.properties provided by the vaadin-sass-compiler artifact.

So the existing logging configuration is changed when ScssStylesheet class is loaded.

The static-initializer should be removed. At least it should be possible
to disabled this behavior somehow without patching vaadin-sass-compiler.

**Comment by hesara** [comment]
To disable the configuration reading in the static initializer, you should be able to set the property java.util.logging.config.file - if it is set, the rest of the static initializer is not run.

Alternatively, you can make sure themes are compiled before running the application, which should make sure methods using ScssStylesheet are not called, and the static initializer is not run.

You could also go as far as excluding the dependency to vaadin-sass-compiler in your POM if you not using on-the-fly theme compilation.

**Comment by Artur-** [comment]
This seems to be fixed in https://github.com/vaadin/sass-compiler/pull/309. Does that change break something else?
