### ISSUE TITLE
When dropping items on a grid, I want to allow the user to drop both on top of rows and between rows, because the dropped item might become a child or a sibling

### ISSUE THREAD

**Issue by pleku** [vaadin/framework#8932]
When this mode is used, there should be some _threshold_  that specifies how many pixels on top and below the border between the rows specifies the drop in between rows, instead of on top of the row. This threshold should be configurable from the server side.

Should be done after #8401.

**Comment by wbadam** [comment]
Perhaps could use percentage instead of pixels as threshold. For example 14% would mean 5px in case of a normal 36px high Grid row.

**Comment by pleku** [comment]
Since the `Grid` can have the row height changed with server side API since 8.1, it might be good to make this configurable, meaning a setter and getter on the `GridDropTarget`.
