### ISSUE TITLE
Changing TextArea.Rows in Vaadin 8 design wysiwyg editor

### ISSUE THREAD

**Issue by ollipelkonen** [vaadin/framework#8934]
Vaadin 8.0.4
Vaadin Designer 2
in Ubuntu 16.04, Eclipse Neon
![vaadin_textarea_bug](https://cloud.githubusercontent.com/assets/7767052/24292322/85b1632c-1095-11e7-88d0-6802392ccecc.jpg)

I've played little bit with a new Vaadin 8 project and when i added new TextArea and tried to change Rows value to 1 (or anything else) in wysiwyg editor, error popup appears telling me that com.vaadin.ui.TextArea cannot be cast to com.vaadin.ui.GridLayout.
Adding Rows="1" in to source code does the trick, and modifying any of the other properties seem to work fine.

**Comment by nordligulv** [comment]
Moved to https://github.com/vaadin/designer-issues/issues/1392
