### ISSUE TITLE
You can't change columns in Grid

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8938]
Vaadin version: 8.0.4

Code to reproduce:

        final VerticalLayout layout = new VerticalLayout();
        
        Grid<String> grid = new Grid<>();
        grid.setItems("1", "2");
        
        grid.addColumn(s->"foo").setCaption("Foos");
        
        Button button = new Button("Click Me to show Bars");
        button.addClickListener( e -> {
            grid.removeAllColumns();
            grid.addColumn(s->"bar").setCaption("Bars");
        });
        
        layout.addComponents(grid, button);
        
        setContent(layout);

**Comment by Artur-** [comment]
The problem seems to actually be that you can't add columns. The new column is empty even if you do not do `removeAllColumns`
