### ISSUE TITLE
ButtonRenderer in Grid doesn't work if there is a hidden column added before, Vaadin 8.0.4

### ISSUE THREAD

**Issue by krasnyt** [vaadin/framework#8943]
ButtonRenderer in Grid doesn't work since Vaadin 8.0.3. 

Instead of rendering a Button I see a simple Label. This works in v8.0.2 although the button seems to have no styling (single _v-nativebutton_ class). As a simple example you can use [official doc](https://vaadin.com/docs/-/part/framework/components/components-grid.html#components.grid.renderer).

**Comment by Artur-** [comment]
Can't reproduce with 8.0.3 nor with 8.0.4

**Comment by krasnyt** [comment]
Ok, I found out that it is caused by a hidden column that was added **before** the 'button' column.

This works:
```
grid.addColumn(Person::getYear).setCaption("Year");
grid.addColumn(person -> "Delete", new ButtonRenderer<>());
```

This doesn't:
```
grid.addColumn(Person::getYear).setCaption("Year").setHidden(true);
grid.addColumn(person -> "Delete", new ButtonRenderer<>());
```

And by the way, how can we style these buttons?
