### ISSUE TITLE
Setting the MenuItem styleName to "selected" does nothing

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#8960]
Setting the styleName to e.g. "mysel" will correctly add the `v-menubar-menuitem-mysel` style to the menu item. However, setting the styleName to "selected" will add nothing and only the `v-menubar-menuitem` style will appear in the browser. Attaching sample application and a screenshot.

**Comment by mvysny** [comment]
![screenshot from 2017-03-28 13-25-29](https://cloud.githubusercontent.com/assets/254091/24400730/2d8885d6-13ba-11e7-80c1-e75aa7577c32.png)

**Comment by mvysny** [comment]
[vaadin-app.zip](https://github.com/vaadin/framework/files/875306/vaadin-app.zip)

**Comment by elmot** [comment]
`selected` is a kind of "reserved" styles. 
Please use another name.

Not a bug
