### ISSUE TITLE
Grid editor does not hide editor component

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/framework#8962]
Hiding a column when editor is open is not prevented, but the editor does not hide the component for the now hidden column either. This looks really weird in the UI, since the columns move, but editor widgets stay as is. Either prevent hiding while editor is open, or fix.

**Comment by TatuLund** [comment]
If you are using Grid in un-buffered mode, you can use GridFastNavigation version 2.3.5, which includes a fix for this issue.

https://vaadin.com/directory/component/gridfastnavigation-add-on

**Comment by TatuLund** [comment]
I published also standalone extension with the fix, that can be used with both buffered and un-buffered editor, when GridFastNavigation is not needed.

https://vaadin.com/directory/component/grideditorcolumnfix-add-on
