### ISSUE TITLE
DateField validation error message still stays after you correct a manual error

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#8991]
If I manually type in "a" as the date and click on another field the value will be blanked out. I then retype "a" again and click out of the field to see the error message. I then click on the calendar icon to have the field enter in a date for me. Even though the data is created, and correctly formatted, by DateField the validation message still stays until I select the date from the calendar popup a second time.

**Comment by Artur-** [comment]
Sounds like what is also described in #8687
