### ISSUE TITLE
Class doc for `Binder::bindInstanceFields` uses wrong (non-existent) method name in example code

### ISSUE THREAD

**Issue by basil-bourque** [vaadin/framework#8994]
In the class doc for [`Binder::bindInstanceFields`](https://vaadin.com/api/8.0.5/com/vaadin/data/Binder.html#bindInstanceFields-java.lang.Object-)
…the code sample says:

>binder.bindMemberFields(myForm);

…where I suspect you meant to call the method name being documented:

>Binder::bindInstanceFields(myForm);

**Comment by nikkijuk** [comment]
Noticed same .. Just wanted to check it, as vaadin code example in https://vaadin.com/framework seemed strange to me .. 

```
public class PersonForm extends FormLayout {
// Define the input fields for data.
TextField firstName = new TextField("First name");
TextField lastName = new TextField("Last name");
TextField email = new TextField("Email");
DateField birthday = new DateField("Birthday");

    public PersonForm() {
        addComponents(firstName, lastName, email, birthday);
    }
}

// Create a PersonForm and bind form fields to a person bean.
PersonForm form = new PersonForm();
new Binder<>(Person.class).bindInstanceFields(this);
```

3 last lines do seem to be missing something & misleading reader ..

I guess code is copy-pasted from vaadin documentation or sample app, but something has been lost in way, as there isn't anymore setBean (person) or readBean (person) methods shown, even if they are referenced in comment by saying "bind form fields to a person bean."

https://vaadin.com/docs/-/part/framework/datamodel/datamodel-forms.html

**Comment by tsuoanttila** [comment]
Hi @nikkijuk, there is indeed a problem in that code. The correct parameter to pass to `bindInstanceFields` would be the PersonForm instance `form`. Alternatively the Binder could be made part of the PersonForm where `this` would refer to the correct object. I'll ask to fix the demo code in the website.

**Comment by nikkijuk** [comment]
Documentation at Vaadin website is really good, and clarifies exactly what you said. Anyway, in javadocs is  example code which seems to be outdated and could be just removed - I guess it would make it easier to keep docs in sync. https://vaadin.com/api/8.1.3/com/vaadin/data/Binder.html#bindInstanceFields-java.lang.Object-

**Comment by tsuoanttila** [comment]
I already made a Pull Request with the method name update in the JavaDoc, so that problem should be gone soon. And yes, multiple locations of documentation is usually bad and we'll need to do some clean up and streamlining at some point when we have the time for it.
