### ISSUE TITLE
Exception on aborting file download using FileDownloader

### ISSUE THREAD

**Issue by werwolfberlin** [vaadin/framework#9014]
This Defect is based on https://github.com/vaadin/framework/issues/6217

When downloading a file using FileDownloader there happens an exception when aborting the download.
Please use the attached project in the zip file. Go to the UI class and replace the file name by a big file of your machine. optionally use bandwith limitation.

- Place a breakpoint in FileDownloader on line 162 (stream.writeResponse(request, response);)

- Start the Project and 

- click the button which triggers the download. 

- Cancel the download before it finishes. 

Be aware that Firefox and Chrome have download managers which already start the download before you chose to save or open it.
On cancelling there will be thrown an exception. In Tomcat it is a ClientAbortException which is from a Catalina library and extends an IOException. It might be that in other application servers also other exceptions are thrown.

My workaround for this is overwriting the method handleConnectorRequest as follows:

```

        @Override
        public boolean handleConnectorRequest(final VaadinRequest request, final VaadinResponse response, final String path) throws IOException {
            try {
                return super.handleConnectorRequest(request, response, path);
            }
            catch (final ClientAbortException ignored){ // Browsers are throwing exceptions on aborting downloads which don't really harm
                return true;
            }
        }
```

[vaadin-download.zip](https://github.com/vaadin/framework/files/893655/vaadin-download.zip)

**Comment by elmot** [comment]
I think this works as expected. The exception is a sign to the application that something went wrong and user did not get the file. Swallowing of the exception makes the problem detection impossible.
If your workaround isn't a workaround, it is a good way to get rid of the exception if such kind of the detection is unnecessary. The code might be a good addition to the FileDownloader article and/or it's javadoc.

**Comment by pleku** [comment]
As mentioned by @elmot , this is working as it should, but the javadocs / documentation should clarify that this can happen. Another thing to consider is to make it more easy to discover the fact that exception might be thrown on user aborting the download, so that application developers know that they need to handle that case. But, *that change is considered as an enhancement*.

**Comment by pleku** [comment]
Here is the documentation where it should be mentioned https://github.com/vaadin/framework/blob/a50b5d5fcd55fe0bf0241c77d040ebfd65baa233/documentation/articles/LettingTheUserDownloadAFile.asciidoc.
