### ISSUE TITLE
Vaadin: 8.0.4. Setting gridHeightMode(HeidhtMode.Undefined) results in displaying wrong amount of rows 

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#9020]
Setting grid to grid.setHeightMode(HeightMode.UNDEFINED); resuts in wrong amount of rows to be displayed.

Code to reproduce:
final VerticalLayout layout = new VerticalLayout();
		List<Person> people = Arrays.asList(new Person("Nicolaus Copernicus", 1543),
				new Person("Galileo Galilei", 1564), new Person("Johannes Kepler1", 1571),
				new Person("Johannes Kepler2", 1571), new Person("Johannes Kepler3", 1571));

		// Create a grid bound to the list
		Grid<Person> grid = new Grid<>();
		grid.setItems(people);
		grid.addColumn(Person::getName).setCaption("Name");
		grid.addColumn(Person::getBirthYear).setCaption("Year of birth");
		grid.setHeightMode(HeightMode.UNDEFINED);
		grid.setWidth("900px");
		layout.addComponent(grid);
		setContent(layout);

**Comment by anasmi** [comment]
![gridwrong](https://cloud.githubusercontent.com/assets/15248706/24690625/c651aa3c-19d6-11e7-8c17-eed33a61518a.jpg)

**Comment by tsuoanttila** [comment]
There was a fix for this in pull request #9104 merged to master yesterday. Will be picked to 8.0 and one part of the patch might apply for 7.7 as well.
