### ISSUE TITLE
Grid HeaderCell setComponent/getComponent should be a generic type

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9030]
- Vaadin version 8.0.5

In the moment the HeaderCell takes a Component and render it. This could be a Textfield, ComboBox, etc...

```
    /**
     * Returns the component displayed in this cell.
     *
     * @return the component
     */
    public Component getComponent();

    /**
     * Sets the component displayed in this cell.
     *
     * @param component
     *            the component to set
     */
    public void setComponent(Component component);
```
The Problem here is with Vaadin 8 that you have to cast it to the specific Element. For Example if you have a Textfield `final TextField textField = (TextField) headerCell.getComponent();` or if you have a ComboBox `final ComboBox<BooleanFilterBean> comboBox = (ComboBox<BooleanFilterBean>) headerCell.getComponent();`. Now the last one is with Vaadin 8 an unchecked cast. It Would be better to have a generic type for component. Maybe so HeadeCell also needs a type parameter.

```
public interface HeaderCell<T extends Component> extends Serializable {
...
	/**
	 * Returns the component displayed in this cell.
	 *
	 * @return the component
	 */
	public T getComponent();

	/**
	 * Sets the component displayed in this cell.
	 *
	 * @param component
	 *            the component to set
	 */
	public void setComponent(T component);
...
}
...
}
```

**Comment by Legioth** [comment]
If we have `HeaderCell<T extends Component>`, then what type should methods like `HeaderRow.getCell` be defined to return?
