### ISSUE TITLE
ComponentRenderer components disappear on Grid resize

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/framework#9032]
**Version:** Vaadin 8.1.0.alpha3

When resizing the Grid, components rendered with ComponentRenderer flicker and disappear.

![buttons-disappearing](https://cloud.githubusercontent.com/assets/883698/24765453/b4406fbe-1aac-11e7-9bf2-3bcb6aba905a.gif)

**Comment by TatuLund** [comment]
This is probably related to https://github.com/vaadin/framework/issues/11836

**Comment by TatuLund** [comment]
Closing as duplicate of #11836, the workaround is documented there.
