### ISSUE TITLE
ComboBox StreamResource as Icon is not working

### ISSUE THREAD

**Issue by ToArnld** [vaadin/framework#9041]
Vaadin Version: 8.1.0.alpha3

Setting a StreamResource as Icon of a ComboBox is not working. The image is not shown and I get the following warning:

15:14:59,690 WARNING [com.vaadin.server.ConnectorResourceHandler] (default task-46) GelitaNamePicker (3583) did not handle connector request for null/USERNAME_usericon.jpg

I think the problem is in the function ComboBox.updateSelectedItemIcon():
```java
private void updateSelectedItemIcon() {
        String selectedItemIcon = null;
        T value = getDataCommunicator().getKeyMapper().get(getSelectedKey());
        if (value != null) {
            Resource icon = getItemIconGenerator().apply(value);
            if (icon != null) {
                selectedItemIcon = ResourceReference
                        .create(icon, ComboBox.this, null).getURL();
            }
        }
        getState().selectedItemIcon = selectedItemIcon;
    }
```

The ResourceReference is created with "null" as key-parameter.
This leads to the following URI: app://APP/connector/2/3583/null/USERNAME_usericon.jpg

The code for setting the StreamResource as Icon:

```java
setItemIconGenerator(user-> {
	Resource r = new ThemeResource("../mytheme/img/profile-pic-300px.jpg");
	try {
		if(user.getPicSmall() != null){ 
			StreamResource.StreamSource imageSource = () -> new ByteArrayInputStream(user.getPicSmall());
			r = new StreamResource(imageSource, user.getUsrid() + "_usericon.jpg");
		}
	}catch(Exception ex){}
	return r;
});
```

The ThemeResource is shown as expected

**Comment by homer54** [comment]
I created a workaround for that issue. The icon resource isn't registred by using setResource(). So, I changed   updateSelectedItemIcon(), writeItem() and init(). Example:

```java
private void updateSelectedItemIcon() {
	String selectedItemIcon = null;
	T value = getDataCommunicator().getKeyMapper().get(getSelectedKey());
	if (value != null) {
		Resource icon = getItemIconGenerator().apply(value);
		if (icon != null) {
			if (icon instanceof StreamResource) {
				setResource("icons_"+value.hashCode(), icon);
			}
			selectedItemIcon = ResourceReference
					.create(icon, ComboBox.this, "icons_"+value.hashCode()).getURL();
		}
	}
	getState().selectedItemIcon = selectedItemIcon;
}
```
Note: I'ts necessary to apply those changes in the following methods:
- updateSelectedItemIcon()
- writeItem()
- init()

**Comment by hesara** [comment]
This concerns all ConnectorResource classes (FileResource, ClassResource, StreamResource).

**Comment by krasnyt** [comment]
+1
