### ISSUE TITLE
TreeGrid expand nodes after adding items

### ISSUE THREAD

**Issue by anthavio** [vaadin/framework#9050]
With Vaadin 8.1.0.alpha4 ~~8.1.0.alpha3~~
When creating HierarchyData and InMemoryHierarchicalDataProvider and grid.setDataProvider
Then using grid.expand(...) for parent nodes does nothing. Sadly, everything stays collapsed
```
private static TreeGrid<String> test() {
        TreeGrid<String> treeGrid = new TreeGrid<>();
        treeGrid.setCaption("Test");
        treeGrid.addColumn(String::toString).setCaption("String");
        HierarchyData<String> data = new HierarchyData<>();
        data.addItem(null, "parent1");
        data.addItem("parent1", "parent1-child1");
        data.addItem("parent1", "parent1-child2");
        data.addItem(null, "parent2");
        data.addItem("parent2", "parent2-child2");
        treeGrid.setDataProvider(new InMemoryHierarchicalDataProvider<>(data));
        treeGrid.setHeightByRows(5);
        treeGrid.expand("parent1");
        treeGrid.expand("parent2");
        return treeGrid;
    }
```

**Comment by ToArnld** [comment]
Same problem here. But with version 8.1.0.alpha4.

**Comment by anthavio** [comment]
Oh right 8.1.0.alpha4! Method TreeGrid.expand() does not event exist in 8.1.0.alpha3. 
I updated my original comment.

**Comment by ahie** [comment]
Thank you for reporting this issue. This will be fixed in the next alpha that is planned for release this Thursday.
