### ISSUE TITLE
New item value ignored in ComboBox when clicked outside of box

### ISSUE THREAD

**Issue by m1h43l** [vaadin/framework#9071]
I have a ComboBox where the user can select or enter data and the next step in the process is to click a button. But when the user enters new data the new data is ignored.

```
        List<String> streets = new ArrayList<>(Arrays.asList("My Way", "Highway"));
        ListDataProvider<String> dataProvider = new ListDataProvider<>(streets);
                
        final ComboBox<String> streetField = new ComboBox<>();
        streetField.setDataProvider(dataProvider);
        streetField.setNewItemHandler(item -> {
            streets.add(item);
            dataProvider.refreshAll();
            streetField.setSelectedItem(item);
            streetField.markAsDirty();
        });
        
        Button assign = new Button("assign");
        assign.addClickListener(event -> {
            Notification.show("Street: " + streetField.getValue());
        });
```

It seems that this is a regression, see https://github.com/vaadin/framework/issues/6914 .

Environment: Vaadin 8.0.0

**Comment by pinonpierre** [comment]
It's a problem for me too.

**Comment by rdavono** [comment]
This is still a problem in 8.1.0 Beta 1

**Comment by pinonpierre** [comment]
Any update?

**Comment by hesara** [comment]
I've seen quite different opinions on what should happen on blur 1) when new items are not allowed and 2) when new items are allowed, potentially also differentiating between exact and inexact matches. This would really require proper UX design and probably some configurability.

**Comment by Artur-** [comment]
The UX has been discussed multiple times with the conclusion that clicking outside the field is the same action as tabbing out. In both cases, the new item should be stored and not thrown away. This is what most users expect, and is also how Vaadin 7.7 works. 

As a general rule of thumb, I don't think there has been any UX redesign for components for Vaadin 8 so Vaadin 7.7 works pretty well as a reference on how they should behave. Of course, there are probably cases where this rule does not apply.

**Comment by sirbris** [comment]
still no new items added, when clicking outside the combobox (TAB-key works though) in 8.2.0.alpha2:
https://github.com/vaadin/framework/issues/9774
