### ISSUE TITLE
VaadinIcons missing default styles and bad look

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9072]
- Vaadin version: 8.0.5

I am migration to Vaadin 8. In Vaadin 7 i created a grid with filter comboboxes and filter items with FontAwesome Icons. For example:

![image](https://cloud.githubusercontent.com/assets/10894484/24961870/7512eea0-1f9a-11e7-9b9f-809b7168a124.png)

In Vaadin 8 i am using the new ComboBoxes and VaadinIcons. There are two problems. First there are missing some default styles (text-align) and the Icons looks very thin and not sharp/clear. The four borders of the square are not equal:

![image](https://cloud.githubusercontent.com/assets/10894484/24961983/c9bfaf38-1f9a-11e7-9112-f9c24a1d57f0.png)

If you compare the two styles you can see the difference. So the Icon in the combobox is left aligned and looks missplaced. Maybe the bad look comes from design or from missing styles. i don't know yet.

```
.Vaadin-Icons {
	font-family: "Vaadin-Icons";
}
```

```
.FontAwesome {
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	display: inline-block;
	text-align: center;
}
```

**Comment by hesara** [comment]
The location in ComboBox was addressed by #9637. The possible unsharpness is not yet addressed, and might need investigation (scaling to non-default size?).
