### ISSUE TITLE
Calling "clearSortOrder" in Grid does not clear sort indicators

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9074]
- Vaadin version: 8.0.5

If you have some sort directions and call "clearSortOrder" the sort indicators still remain.
All sort directions are correctly cleared.

![image](https://cloud.githubusercontent.com/assets/10894484/24962896/77322194-1f9d-11e7-9317-5bed3ba88d14.png)

**Comment by focbenz** [comment]
Can confirm this behavior also with the newest Vaadin release 8.1.6 and 8.1.7

**Comment by focbenz** [comment]
If this has not been fixed in latest 8.3.x or 8.4.x please fix this.

**Comment by knoobie** [comment]
Same problem with Vaadin 7.7 - a fix with 7 and 8 would be lovely.

**Comment by focbenz** [comment]
Awesome :1st_place_medal: !
Maybe @knoobie you want to help us out get some other bugs fixed as well :tongue:
