### ISSUE TITLE
ComboBox binder gives erroneous empty selection if item selected is higher in collection than page length

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#9085]
I don't know if this applies only when using the binder but I have been able to replicate it with 100% consistency. **_The code below will consistently replicate the issue_**.

Vaadin will always successfully select the correct comboBox item if you select to return successfulComboBoxSelection in the converter method convertToPresentation. It however will always result in an empty selection if you use invalidAndEmptyComboBoxSelection, even though both are valid options and should select the appropriate item in the combobox. 

The key is the pagelength, which is why I use that variable. So if I have a collection of 25 items then if the pagelength is greater than 25 you will always be able to select every item as expected. If however the pagelength is less than 25 any items above the pagelength in the collection (above index 25) will not be selected and will result in an empty selection in the comboBox. By default I believe the default pagelength is 10 so any combobox with more more than 10 items in the collection will fail and result in an empty selection using the converter with the binder.

```
@Theme("mytheme")
public class MyUI extends UI 
{
	static final int PAGE_LENGTH = 10;
	static final int INVALID_EXTRAS = 10;
	
    @Override
    protected void init(VaadinRequest vaadinRequest) 
    {
    	List<Person> people = new ArrayList<Person>();
    
    	for(int x=1; x<=PAGE_LENGTH + INVALID_EXTRAS; x++)
    		people.add(new Person(x, "John Smith " + x));

    	ComboBox<Person> personComboBox = new ComboBox<Person>();
    	
    	personComboBox.setItemCaptionGenerator(Person::getName);
    	personComboBox.setItems(people);
    	personComboBox.setPageLength(PAGE_LENGTH);

    	Invoice invoice = new Invoice(1, "Invoice for Barney", 3);

		Binder<Invoice> binder = new Binder<Invoice>();
		binder.forField(personComboBox)
				.withConverter(new ComboBoxPersonToIdConverter())
				.bind(Invoice::getPersonID, Invoice::setPersonID);
		binder.readBean(invoice);

    	setContent(personComboBox);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet 
    {
    }
    
}

class ComboBoxPersonToIdConverter implements Converter<Person, Integer>
{
	@Override
	public Result<Integer> convertToModel(Person person, ValueContext context)
	{
		// ignoring null case for simplicity.
		return Result.ok(person.getId());
	}

	@Override
	public Person convertToPresentation(Integer id, ValueContext context)
	{
		// return successfulComboBoxSelection();
		// return invalidAndEmptyComboBoxSelection();
	}
	
	private Person successfulComboBoxSelection()
	{
		return new Person(MyUI.PAGE_LENGTH-1);
	}
	
	private Person invalidAndEmptyComboBoxSelection()
	{
		return new Person(MyUI.PAGE_LENGTH + new Random().nextInt(MyUI.INVALID_EXTRAS));
	}
}

class Invoice
{
	private int id;
	private String description;
	private int personID;
	
	public Invoice(int id, String description, int personID)
	{
		super();
		this.id = id;
		this.description = description;
		this.personID = personID;
	}

	public int getPersonID()
	{
		return personID;
	}
	public void setPersonID(int personID)
	{
		this.personID = personID;
	}
}

class Person
{
	private int id;
	private String name;
	
	
	public Person(int id)
	{
		this.id = id;
	}
	
	public Person(int id, String name)
	{
		super();
		this.id = id;
		this.name = name;
	}

	@Override
	public int hashCode()
	{
		return id;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		return id == ((Person)obj).getId();
	}
	
	public int getId()
	{
		return id;
	}
	
	public void setId(int id)
	{
		this.id = id;
	}
	
	public String getName()
	{
		return name;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
}
```

**Comment by FollowSteph** [comment]
There may be an off by one error with the random selection in the converter, but ignore that for now. I also used the converter so that I can control which item is selected, but this could also have been done by just changing the line:

`new Invoice(1, "Invoice for Barney", 3);`

And changing the last argument 3 to be anything higher than pagelength. I did it through the converter but in essence it's the same thing, basically the personID for the Invoice object is at a higher index in the ComboBox'es collection then the pageLength value.

**Comment by FollowSteph** [comment]
Is there any planned progress on this bug?

**Comment by FollowSteph** [comment]
Are there any updates on this bug?

**Comment by jonasrotilli** [comment]
No prediction or help in this matter? I also have the problem. In the Binder documentation, there is nothing related / example to Combobox.

**Comment by elmot** [comment]
Some changes were made recently in ComboBox, please check if the issue is still reproducible with latest Vaadin version
