### ISSUE TITLE
V7 compatibility Grid should inherit AbstractLegacyComponent

### ISSUE THREAD

**Issue by hesara** [vaadin/framework#9095]
In Vaadin 8 compatibility packages, the V7 Grid does not inherit ALC and thus doesn't have some generic V7 API. V7 Grid should probably inherit ALC to support that API.

**Comment by hesara** [comment]
While investigating this, the benefits of actually implementing this are getting less and less clear to me:
* as far as I know, the read-only feature is really only used by the V7 Grid to set a style name - there is a separate mechanism (HasUserSelectionAllowed) for enabling or disabling selection of values by the user (#7880)
* the immediate mode is no longer really used in Vaadin 8, and calls to setImmediate()/isImmediate() can be removed in migration
* as the above mentioned features are less used, the related declarative syntax flags aren't really relevant for V7 Grid, either
* apart from this API, the superclass is of limited relevance, and where a common superclass is needed, AbstractComponent can usually be used instead

It should also be noted that the base classes of Grid, GridState (TabIndexState) and GridConnector (AbstractHasComponentsConnector) would all potentially need to be duplicated, or logic copied from them.

**Comment by Legioth** [comment]
The main benefit would probably be consistency with other components in the compatibility package.
