### ISSUE TITLE
Vaadin upload with large single-line file can result in an OutOfMemoryError

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#9102]
- Vaadin 8.0.5
- Uploading a large file (e.g. 5GB) without linebreaks can cause an OutOfMemoryError
Steps to reproduce:
* Create a test file, for example in Windows `fsutil file createnew dummy 5368709120` -> 5Gb file without line breaks.
* Upload this file with the Vaadin upload component used in a Vaadin portlet dropped in Liferay. 
* Since the FileUploadHandler always reads the first line, in this case, it will read 5Gb of data, which will result in a OutOfMemoryError.

**Comment by elmot** [comment]
Uploads of files larger than 2047Mbytes are completely broken under liferay 6.2. Looks like the upload request size is kept in `int` variable somewhere inside liferay. The only thing we can do with that is to prevent OOMs in our code.
