### ISSUE TITLE
Calendar component from FW8 compatibility did not show description as tooltip

### ISSUE THREAD

**Issue by ossd** [vaadin/framework#9107]
Since update to FW8 (8.0.5) and use of compatibility package, the calendar component did not show the description string as tooltip. Nothing happens, when you hover over an event with the mouse cursor. Is it a bug, or are there changes in the api?

**Comment by tsuoanttila** [comment]
Can you test if this is still an issue with the latest 8.2-SNAPSHOT ?

**Comment by TatuLund** [comment]
I tested it and tooltips works now ok.

**Comment by TatuLund** [comment]
Works with 8.2.0.alpha3
