### ISSUE TITLE
Add readonly for grid again

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9115]
- Vaadin version 8.0.5

In Vaadin 8 there is no method anymore to set a grid readonly.
But if you disable a grid in the moment the component is "dead" and grayed out. So i think there is a use case where you have to set a grid readonly let the user scroll through the grid but do not let components get selected or changed.

**Comment by JericoPablo** [comment]
Still not possible, is there a reason why you guys took out the readOnly mode?

**Comment by tsuoanttila** [comment]
You can prevent the user selection with `grid.getSelectionModel().setUserSelectionAllowed(false);` This will practically make the Grid already "Read Only". If you use `ComponentRenderer`, you need to deal with those components in the `ValueProvider` and refresh the data set to re-render the components. Is there something else missing from "Read Only"?

**Comment by JericoPablo** [comment]
thats exactly what i need, thank you!

**Comment by elmot** [comment]
@JericoPablo  can we close the ticket?

**Comment by JericoPablo** [comment]
yes! thanks again.
