### ISSUE TITLE
Items in the TreeGrid become randomly unselectable (null) after expanding nodes

### ISSUE THREAD

**Issue by AemonAlgiz** [vaadin/framework#9126]
I have a TreeGrid that lazy loads its children on expansion, though the side effect of this seems to be that after expanding the tree randomly (I haven't found a way to reliably replicate the issue, but it happens fairly often) nodes in the TreeGrid become unselectable (null) or the TreeGrid will throw an error similar to, 

java.lang.NullPointerException: Cannot find item for given key 19

**Comment by AemonAlgiz** [comment]
Code snippet on expanding a node:

proj.getNarrowerTerms(); is an api call that exists in our proprietary API that lets me call lower terms.

@SuppressWarnings("unchecked")
		public void addChildren(Term parent) {

			if (!parent.getExpanded()) {

				List<Term> children = parent.getChildren();
				Iterator<Term> childrenIt = children.iterator();

				while (childrenIt.hasNext()) {

					Term term = childrenIt.next();

					List<String> nextGen = proj.getNarrowerTerms(term.getTerm());
					Iterator<String> nextGenIt = nextGen.iterator();

					while (nextGenIt.hasNext()) {
						Term child = new Term(nextGenIt.next());
						child.setExpanded(false);
						child.setParent(term);
						term.addChildren(child);
					}

					parent.setExpanded(true);
					
					tree.addItems(term, term.getChildren());
					
					dataProvider.refreshItem(term);
					
				}
			} else {
				return;
			}

		}

**Comment by AemonAlgiz** [comment]
Just got the same issue to happen on the Vaadin demo:

![image](https://cloud.githubusercontent.com/assets/10222829/25264180/739ccfee-2622-11e7-8f99-b5e6bcf0b0dc.png)

**Comment by ecobham1** [comment]
I receive the error described above when expanding after refreshing item(s) in the data provider. As a temporary workaround, I have been resetting the data provider after each refresh call to clear any pending expands and drop all data from the underlying DataCommunicator, e.g.

```
dataProvider.refreshAll();
treeGrid.setDataProvider(dataProvider);
```

This is obviously less than ideal, hopefully the issue can be resolved soon

**Comment by AemonAlgiz** [comment]
I tried that as well but the issue will actually still happen from time to time, granted much less frequently. It seems to happen much more often if you're clicking through the tree very rapidly, which leads me to think that there's some kind of desync issue between the client and server.

**Comment by ahie** [comment]
Thank you for reporting these issues. Commit https://github.com/vaadin/framework/commit/60db37dfaaa7d04bb393a27b888110dc73299404 currently in master should address these and it will be included in the next pre-release. In the meanwhile a snapshot build can be used to verify whether these issues still persist.

**Comment by AemonAlgiz** [comment]
Seems to be fixed, ahie.
