### ISSUE TITLE
Grid Sort-Problems (Missing Sort indicator, default case sensitive, not clearing sort indicators)

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9135]
I have some problems with programmatic sorting a grid. I made a test project where you can play with sorting in a grid an can see some problems.

[SortProblems.gz](https://github.com/vaadin/framework/files/948919/SortProblems.gz)
(Just for information i have to change .zip(.ZIP) to. gz otherwise i can't upload the archive)

- Default sorting for String comparison is case sensitive. I think this should not be the case. The more common use case is case insensitive. Otherwise you have to programmatic set a comparator to every column. If you want to be case sensitive you can override this behaviour, but like i said imho this is not often wanted.

```
gridSort.addColumn(SortBean::getSortName).setComparator((o1, o2) -> o1.getSortName().compareToIgnoreCase(o2.getSortName())).setCaption("HeroName")
				.setId(columnSortName).setExpandRatio(3);
// Without the comparator from above sorting is case sensitive
//gridSort.addColumn(SortBean::getSortName).setCaption("HeroName").setId(columnSortName).setExpandRatio(3);
```

- If you set a comparator programmatic there is no sort indicator added to the grid columns. Neither in the single case nor in a multi sort case. My use case is the following: If the use has not ordered a column there is the default case sort by primary attribute and then if a `GridSortOrder` is set, then use this one. If multiple are set, use all of them.

```
	final List<GridSortOrder<SortBean>> sortOrder = gridSort.getSortOrder();
		if (sortOrder.isEmpty()) {
			// TODO: There is no sort indicator added for this column
			gridSort.getColumns().forEach(column -> {
				if (columnSortName.equals(column.getId())) {
					gridSort.setSortOrder(GridSortOrder.asc(column));
				}
			});

			// TODO: There is no sort indicator added for this column
			// gridSort.sort(gridSort.getColumn(columnSortName), SortDirection.ASCENDING);
			// gridSort.sort(gridSort.getColumn(columnSortName));
		} else {
			final GridSortOrderBuilder<SortBean> gridSortOrderBuilder = new GridSortOrderBuilder<SortBean>();
			sortOrder.forEach(gridSortOrder -> {
				if (gridSortOrder.getDirection() == SortDirection.ASCENDING) {
					gridSortOrderBuilder.thenAsc(gridSortOrder.getSorted());
				} else {
					gridSortOrderBuilder.thenDesc(gridSortOrder.getSorted());
				}
			});
			// TODO: There should be sort indicator added for every column
			gridSort.setSortOrder(gridSortOrderBuilder);
		}
```

- calling `clearSortOrder` does clear the sort order and sort the elements how the elements are added to the grid. But the indicators still remain. I opened a issue already here: #9074

**Comment by sirbris** [comment]
I also think that case insensitive sorting would be the better default... what would be the best approach to override that behavior for all columns (for projects with a huge amount of grids and properties)?

**Comment by sirbris** [comment]
@sebastianfilke have you found an easy general approach for case insensitve sorting meanwhile?
