### ISSUE TITLE
Manually test framework 8.1 on all supported browsers

### ISSUE THREAD

**Issue by hesara** [vaadin/framework#9139]
Test on all supported desktop and mobile browsers that are not extensively automatically tested.

This includes at least

- [  ] Edge
- [  ] Safari 9+ on MacOS
- [  ] Safari on iOS 9+
- [  ] Chrome 42+ on Android 4+

**Comment by hesara** [comment]
All of these done

**Comment by Legioth** [comment]
Did this also cover #9140 which is still in progress?

**Comment by hesara** [comment]
No - although the underlying TreeGrid was covered, Tree will require separate (quick) tests on each of these browsers.
