### ISSUE TITLE
Grid problem with components and focus 

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9144]
- Vaadin version: 8.1.0.alpha6

In the moment if you have a component in the grid (for example a checkbox) and click the checkbox it seems that the focus gets a short time the checkbox and then back the grid. the problem here is it flickers and if you click the checkbox a little bit faster the text of grid columns gets highlighted.

![image](https://cloud.githubusercontent.com/assets/10894484/25385037/e16e0ea4-29c2-11e7-954e-4aa39e8d3938.png)

I made a testproject which demonstrates the behaviour: [GridFocusProblem.gz](https://github.com/vaadin/framework/files/955001/GridFocusProblem.gz)

**Comment by TatuLund** [comment]
For better control handling events with rendered components, there is Column.setHandleWidgetEvents(..) method. See also https://github.com/vaadin/framework/issues/9649 and https://github.com/vaadin/framework/issues/10510
