### ISSUE TITLE
Horizontal CheckBoxGroup together with GridLayout is not rendered correctly, v8.0.5

### ISSUE THREAD

**Issue by krasnyt** [vaadin/framework#9148]
Horizontal CheckBoxGroup is not rendered correctly inside GridLayout. However, when I check any checkbox, it gets redrawn correctly. Example:

```
public class TodoUI extends UI {

    @Override
    protected void init(VaadinRequest request) {
        CheckBoxGroup<String> cbGroup = new CheckBoxGroup<>(null, DataProvider.ofItems("A", "B", "C"));
        cbGroup.addStyleName(ValoTheme.OPTIONGROUP_HORIZONTAL);

        GridLayout gridLayout = new GridLayout(2, 1);
        gridLayout.addComponent(new Label("Buggy"), 0, 0);
        gridLayout.addComponent(cbGroup, 1, 0);
        gridLayout.setSpacing(true);

        HorizontalLayout layout = new HorizontalLayout();

        layout.addComponent(gridLayout);
        layout.addComponent(new TextField("Input"));

        setContent(layout);
    }

}
```
This is what I get:
![wrong_checkboxgroup](https://cloud.githubusercontent.com/assets/6813833/25406973/e0697c64-2a08-11e7-8ad5-38e08d039bee.PNG)

This is what I get when I check any checkbox:
![correct_checkboxgroup](https://cloud.githubusercontent.com/assets/6813833/25406967/dbac378e-2a08-11e7-9b97-9d9099f8ee0f.PNG)

**Comment by krasnyt** [comment]
The same thing goes for RadioButtonGroup except it doesn't change at all when I check any option:

![optiongroup](https://cloud.githubusercontent.com/assets/6813833/25407492/caebb3b4-2a0a-11e7-9064-cb213c601c70.PNG)

**Comment by OlliTietavainenVaadin** [comment]
Possibly related issue: https://github.com/vaadin/framework/issues/7895
