### ISSUE TITLE
Make it possible to rewrite dependencies

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#9151]
Use cases:
1. Making sure that JQuery is loaded from only one location even though add-ons have defined a `@JavaScript` using different URLs
2. HTML imports can be rewritten to load a bundle instead of the individual HTML files

There should be a pluggable mechanism to add a rewrite implementation from an add-on and also possible to add a rewrite implementation from the application project

**Comment by Legioth** [comment]
This would in practice require a way of modifying the list of dependencies produced in https://github.com/vaadin/framework/blob/9abf1ee/server/src/main/java/com/vaadin/server/communication/UidlWriter.java#L285 before they are used anywhere.

One way of implementing this could be as follows:
* A service level listener interface that receives a `Stream< Dependency>` and an "event object" with contextual information such as the current UI, session and service. The listener method returns a `Stream< Dependency>` that will then be passed to the next listener or used by the framework after the last listener has been invoked.
* There's no known reason for why the list of listeners should be changed on-the-fly after service init. This means that the listeners could be treated in the same ways as request handlers, i.e. initialized by `VaadinService.init` with `VaadinServiceInitListener` being the primary mechanism for an application or add-on to contribute their own implementation to use.
