### ISSUE TITLE
Grid.Column.setHidden(boolean hidden) does not work properly | Vaadin 8.0.5

### ISSUE THREAD

**Issue by rntrp** [vaadin/framework#9152]
In Vaadin 8.0.5 the method `Grid.Column.setHidden(boolean hidden)` seems to be broken. Column visibility is set properly, however those changes do not appear correctly on the UI, for instance:
```java
class Row { String col1; String col2; String col3; }
Grid<Row> grid = new Grid<>(Row.class);
grid.getColumns().forEach(col -> col.setHidable(true));

// Columns will still be visible, even though Column.isHidden() == true:
Button hideCol1 = new Button("hide col1", e -> grid.getColumn("col1").setHidden(true));
Button hideCol2 = new Button("hide col2", e -> grid.getColumn("col2").setHidden(true));
Button hideCol3 = new Button("hide col3", e -> grid.getColumn("col3").setHidden(true));

// Won't work either:		
Button reset = new Button("reset column visibility", e -> {
  grid.getColumns().forEach(col -> col.setHidden(false));
  assert grid.getColumns().stream().noneMatch(col -> col.isHidden()); // OK!
});

// Add components to an arbitrary layout:
addComponents(hideCol1, hideCol2, hideCol3, reset, grid);
```
But clicking the entry within the dropdown menu in the top right corner of the grid works properly.

Interestingly, if you hide columns right after the grid init, it will work:
```java
class Row { String col1; String col2; String col3; }
Grid<Row> grid = new Grid<>(Row.class);
grid.getColumns().forEach(col -> col.setHidable(true));
grid.getColumn("col3").setHidden(true); // will work
// ...
```
My suggestion is that the visibility changes are somehow not propagated to the UI client.

**Comment by rntrp** [comment]
There is also a test (`com.vaadin.tests.components.table.TableToggleColumnVisibilityTest`) which verifies the column visibility for the **Table** with Selenium. One could adapt this test for the grid — and right now it would certainly fail.

**Comment by rntrp** [comment]
These lines within `com.vaadin.client.connectors.grid.GridConnector` look suspicious:
```java
getWidget().addColumnVisibilityChangeHandler(event -> {
  if (event.isUserOriginated()) {
    getRpcProxy(GridServerRpc.class).columnVisibilityChanged(
    getColumnId(event.getColumn()), event.isHidden());
  }
});
```
It only does the RPC logic if `event.isUserOriginated()`, which is certainly _not_ the case if you set the column visibility programmatically with `Grid.Column.setHidden(boolean hidden)`.

**Comment by rntrp** [comment]
bump

**Comment by rntrp** [comment]
Unfortunately _not_ fixed by #9530. May be fixed by #9707 if backported for 8.0.x

**Comment by tsuoanttila** [comment]
Hi, I just took your test code and run it with 8.1.1 (with getters and setters added to the Row class to make Grid autodetect them) and it seems to be working for me. Can you test it still with 8.1.1 or 8.1.2? If you're still facing issues with this, I'd like you to create a full test project and publish it to github for me to checkout and test to see why it's broken.

**Comment by rntrp** [comment]
Hey Teemu, there is actually no need to create a separate repo (I'll create it if you insist 😄), just copy-paste the code below into `MyUI.java` of the newly created Vaadin project.

Steps to reproduce:
1. Hide any column(s) via the grid column menu (not by buttons `hide col 1` etc.)
2. Press the "reset column visibility" button. Is should make all columns visible again — but it doesn't.
3. Now if you repeat step 1 with e.g. `hide col 1` button, then it'll work.

```java
// package, imports

@Theme("mytheme")
public class MyUI extends UI {
  @Override
  protected void init(VaadinRequest vaadinRequest) {
    final VerticalLayout layout = new VerticalLayout();
    Grid<Row> grid = new Grid<>(Row.class);
    grid.getColumns().forEach(col -> col.setHidable(true));

    // Columns will still be visible, even though Column.isHidden() == true:
    Button hideCol1 = new Button("hide col1", e -> grid.getColumn("col1").setHidden(true));
    Button hideCol2 = new Button("hide col2", e -> grid.getColumn("col2").setHidden(true));
    Button hideCol3 = new Button("hide col3", e -> grid.getColumn("col3").setHidden(true));

    // Won't work either:
    Button reset = new Button("reset column visibility", e -> {
      grid.getColumns().forEach(col -> col.setHidden(false));
      assert grid.getColumns().stream().noneMatch(col -> col.isHidden()); // OK!
    });
    layout.addComponents(hideCol1, hideCol2, hideCol3, reset, grid);
    setContent(layout);
  }

  @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
  @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
  public static class MyUIServlet extends VaadinServlet{}

  private static final class Row {
    String col1, col2, col3;
    public String getCol1() {return col1;}
    public void setCol1(String col1) {this.col1 = col1;}
    public String getCol2() {return col2;}
    public void setCol2(String col2) {this.col2 = col2;}
    public String getCol3() {return col3;}
    public void setCol3(String col3) {this.col3 = col3;}
  }
}
```

**Comment by tsuoanttila** [comment]
Ah! Now I understood what you meant in the ticket. Yes, there seems to be a "state not properly updated" type issue going on. Will fix this regression ASAP.
