### ISSUE TITLE
TextField cursorposition after last character

### ISSUE THREAD

**Issue by deformedpepper** [vaadin/framework#9157]
Since Vaadin 8 it seems impossible to set the cursorposition behind the last character in a TextField. It worked in Vaadin 7!

Vaadin version: 8.1.0.alpha4

Sample:
```
final TextField textfield = new TextField();
textfield.setValue("Some input");
textfield.setCursorPosition(textfield.getValue().length());
```

Expected: Caret position behind the character 't'.
Current: Caret position behind the character 'u'.

I was looking what causes this behaviour. A call to AbstractTextField.setCursorPosition(int) moves into
AbstractTextFieldConnector.AbstractTextFieldClientRpcImpl.selectRange(int, int):

```
public void selectRange(int start, int length) {
    int textLength = getAbstractTextField().getValue().length();
    start = restrictTo(start, 0, textLength - 1);
    length = restrictTo(length, 0, textLength - start);
    getAbstractTextField().setSelectionRange(start, length);
}
private int restrictTo(int value, int min, int max) {
...
}
```

The starting position of the selection range get's restricted to textLength - 1. I think this is wrong if we want to be able to set the caret position after the text.

**Comment by TatuLund** [comment]
Have you verified this issue with latest version 8.3.1?

**Comment by DSW-PS** [comment]
Can confirm this issue also applies to version 8.3.1.

**Comment by TatuLund** [comment]
We were also able to replicate it.
