### ISSUE TITLE
Chrome Support issue

### ISSUE THREAD

**Issue by mbx2015** [vaadin/framework#9158]
version 7.7.8
chrome version 58.xx
I just created a vaadin project with spring boot, with only a Label and TextField, 
When I fill the textfield with something and I leave the textfield it show me cookies disabled although the cookies are enabled

this issue is just on chrome, with firefox or other browser it works fine!

**Comment by Artur-** [comment]
Sounds like the infamous cookie problem in Chrome where a cookie is not sent to an http:// url if you have previously used an https:// url on the same host... Is that the case?

**Comment by mbx2015** [comment]
Yes definitly ! it's my case.

**Comment by Legioth** [comment]
We can unfortunately not do anything about how Chrome chooses to ignore cookies in that special case.

**Comment by mbx2015** [comment]
Yes indeed !
