### ISSUE TITLE
GridDragAndDrop duplicates rows on Android+Chrome, IE11, Edge

### ISSUE THREAD

**Issue by Ansku** [vaadin/framework#9174]
Vaadin version: 8.1-SNAPSHOT
Device: Samsung S7 / Android 7.0
Browser: Chrome
Vaadin core test: GridDragAndDrop
Description of the bug: Dragging a row from the source Grid to the target Grid creates a duplicate of the row to the target Grid instead of removing it from the source Grid and adding it into the target Grid. You can even drag the same row multiple times to create a big collection of duplicates to the target Grid. On desktop Chrome (Windows 7) the row is moved as expected and no duplicates are created.

**Comment by pleku** [comment]
Also reproducable on IE11 with the https://demo.vaadin.com/sampler/#ui/drag-drop/grid-drag-rows-html5 sample
