### ISSUE TITLE
Long description in TreeGrid on iOs 10.3, Safari, isn't wrapped if text is too long 

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#9179]
**TreeGridBasicFeatures, iOs 10.3, Safari**

Setting the TreeGrid description being long causes it to be cut off.
<img width="356" alt="img_2136" src="https://cloud.githubusercontent.com/assets/15248706/25482273/bce650e4-2b59-11e7-914d-7fd0f26cf40e.PNG">

**Comment by elmot** [comment]
Duplicate for #9121
