### ISSUE TITLE
GridDragAndDrop IllegalStateException trying to drag all rows from one Grid to another

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#9180]
**Chrom 57 version, GridDragAndDrop testing**

Trying to drag all rows from the first Grid to the second causes the IllegalStateException
<img width="580" alt="griddraganddrop" src="https://cloud.githubusercontent.com/assets/15248706/25482677/793946ce-2b5b-11e7-8efa-8a683f20b1ce.png">

**Comment by wbadam** [comment]
Is the case perhaps that the selected text was dropped on the Grid row?

Perhaps `GridDragSource` should check whether the drag event is initiated from by dragging a Grid row
