### ISSUE TITLE
TreeGrid Not Working in 8.1.0.alpha6 - IllegalAccessError

### ISSUE THREAD

**Issue by ktaylor713** [vaadin/framework#9190]
Trying to construct a TreeGrid yields the following exception:

java.lang.IllegalAccessError: tried to access field com.vaadin.data.provider.DataCommunicator.dataProvider from class com.vaadin.data.provider.HierarchicalDataCommunicator
	at com.vaadin.data.provider.HierarchicalDataCommunicator.<init>(HierarchicalDataCommunicator.java:83)
	at com.vaadin.ui.TreeGrid.<init>(TreeGrid.java:217)

The problem is caused by DataCommunicator.dataProvider field being private.  It needs to be protected. It is being accessed by a sub-class HierarchicalDataCommunicator.

**Comment by hesara** [comment]
The field is protected and has been so throughout most of the alphas. Please check your dependencies - I suspect there is either a copy of a Vaadin Framework class in your project, or also an 8.0 version of vaadin-server on your classpath.

**Comment by ktaylor713** [comment]
You are correct. An addon was including vaadin-server-8.0.5.  I should have looked for that. Resolved. Thanks.
