### ISSUE TITLE
Binder.removeBean() does not set hasChanges to false in Vaadin 8.0.5

### ISSUE THREAD

**Issue by jcgueriaud** [vaadin/framework#9193]
Hi everyone,

I've got a binder.
If I read a bean and modify a field --> binder.hasChanges is true (Perfect).
If I call removeBean then nothing changes on the screen and binder.hasChanges is still true.

I don't understand why it should be true after removeBean.
I write some code to test it: (just click on READ, modify the field, CHECK, REMOVE and CHECK).

    @Theme("mytheme")
    public class MyUI extends UI {

    private Window popup;
    
    private TextField value = new TextField();
    private Label hasChangesLabel = new Label("");
    private Binder<Pojo> binder;
    private Pojo p = new Pojo("test");
    
    
    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();
        
        if (binder == null){
            binder = new Binder<Pojo>();
            binder.bind(value,Pojo::getValue, Pojo::setValue);
        }
                
        Button checkHasChangesButton = new Button("CHECK",
                e -> {hasChangesLabel.setCaption(binder.hasChanges()?"CHANGES":"NO CHANGES");}
                );
        

        Button removeBeanButton = new Button("REMOVE", e -> {binder.removeBean();});
        
        Button readBeanButton = new Button("READ", e -> {binder.readBean(p);});
        Button setBeanButton = new Button("SET", e -> {binder.setBean(p);});
        

        layout.addComponents(hasChangesLabel, value, checkHasChangesButton,removeBeanButton,readBeanButton, setBeanButton);
        
        setContent(layout);
    }
    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }

    }

If I understand it correctly, removeBean = setBean(null) ( "unsetBean") so perhaps I should use readBean(null) to be consistent.

In fact, I don't know what  should be the right behaviour.

The original thread is here:
[https://vaadin.com/forum#!/thread/15750727](url)

**Comment by OlliTietavainenVaadin** [comment]
Binder.java:
```java
     // removeBean -> setBean(null);
     // assume hasChanges == true
     public void setBean(BEAN bean) {
        checkBindingsCompleted("setBean");
        if (bean == null) {
            if (this.bean != null) {
                doRemoveBean(true);
                clearFields();
            }
            // if removing, this.bean is null here, so `hasChanges` is not set to false
        }
        // ...
```

**Comment by Artur-** [comment]
It sounds a bit like you are mixing the "buffered" and "unbuffered" concepts. If you use `readBean`/`writeBean` you should not use `setBean`/`removeBean` and vice versa.

That said, if you do
```
binder.setBean(someBean);
binder.removeBean();
```
then `binder.hasChanges()` should return false. The javadoc even states that it should always return false "after readBean, setBean or removeBean"

**Comment by jcgueriaud** [comment]
You're right the javadoc said:
return false "after readBean, setBean or removeBean"
which is not the case here.
I know (not before posting this topic but now ;) ) that I'm mixing buffered/unbuffered stuff and this is a wrong way to use the binder.
So I did binder.readBean(bean); binder.readBean(null); (to "reset" the hasChanges() status of my binder).

I don't understand why the "buffered" and "unbuffered" concepts are mixed in one class because this let the developper (like me) to misuse the binder class and I don't get the use case where the 2 concepts are mixed.

**Comment by Legioth** [comment]
> I don't understand why the "buffered" and "unbuffered" concepts are mixed in one class

Because we would otherwise have a permutational explosion of almost identical classes, there's already `Binder` vs `BeanValidationBinder`. Separate classes for buffered and unbuffered would give `BufferedBinder`, `UnbufferedBinder`, `BufferedBeanValidationBinder` and `UnbufferedBeanValidationBinder`.

**Comment by jcgueriaud** [comment]
Ok I understand.
Thanks for your answer and your time :)

Like Artur said. I mixed the two concepts:
I should use setBean / removeBean OR readBean / readBean(null)

So I close the ticket.
