### ISSUE TITLE
Impossible to use custom DataCommunicator with Grid in 8.0

### ISSUE THREAD

**Issue by StarGuardian** [vaadin/framework#9206]
Vaadin 8.0.5

I need to use my own DataCommunicator with Grid, but there is no such possibility. AbstractListing has constructor which takes instance of DataCommunicator, but Grid uses only default constructor of AbstractListing which creates default DataCommunicator.

Suggested solution: add another constructor to Grid which allows to set DataCommunicator.
I'll send pull request soon.

**Comment by StarGuardian** [comment]
I have found out that code in master has the change already. It it going to be in 8.0.x and how soon?

**Comment by pleku** [comment]
That constructor has been introduced in 8.1 because of the `TreeGrid` component. We currently have no plans of backporting that constructor, so I recommend switching to latest 8.1 prerelease, which is 8.1.0.alpha6 (there will be a beta1 quite soon), or you could create a PR for the `8.0` branch for adding that.

**Comment by StarGuardian** [comment]
I have created 2 PRs: #9208 and #9209. First one is for 8.0 and second one is for master to maintain backward compartibility and correct javadocs.

**Comment by Legioth** [comment]
@StarGuardian Just out of curiosity: Why do you need to use a custom `DataCommunicator`?

**Comment by StarGuardian** [comment]
It's a long story :) I have grid which contains data from database (I use Hibernate ORM). My entity classes have overidden method equals, so equality of entities are equality of their primary keys (UUIDs), not all fields.
Data displayed in grid, then I update one record and refresh grid. Everything is OK - grid read data from database and send them to client correctly. Then I select updated row in grid and modified fields are replaced by their old values. I refresh data again and see correct values. But when I deselect that row - there are old values again!
I investigated that case and found that during handling select (and deselect) SingleSelectionModelImpl reads data from KeyMapper which belongs to DataCommunicator. But when I send refreshed data, KeyMapper can't detect that it is another object (because equals returns true) and still keep old data in its maps. That way SingleSelectionModelImpl gets obsolete data and puts it into grid.
The only way I found to fix it is using custom KeyMapper (and DataCommunicator) which uses more complex logic to determine if object is updated or not.

Another way is reverting method equals to its default implementation, but it causes another bugs in application, so I decided to use custom KeyMapper.

If something is unclear (because English is not my native language) please ask and I'll do my best to explain.
It's a long story :) I have grid which contains data from database (I use hibernate ORM). My entity classes have overidden method equals, so equality of entities are equality of their primary keys (UUIDs), not all fields.
Data displayed in grid, then I update one record and refresh grid. Everything is OK - grid read data from database and send them to client correctly. Then I select updated row in grid and modified fields are replaced by their old values. I refresh data again and see correct values. But when I deselect that row - there are old values again!
I investigated that case and found that during handling select (and deselect) SingleSelectionModelImpl reads data from KeyMapper which belongs to DataCommunicator. But when I send refreshed data, KeyMapper couldn't detect that it is another object (because equals returns true) and still keep old data in its maps. That way SingleSelectionModelImpl gets obsolete data and puts it into grid.
The only way I found to fix it is using custom KeyMapper (and DataCommunicator) which uses more complex logic to determine if object is updated or not.

Another way is reverting method equals to its default implementation, but it causes another bugs in application, so I decided to use custom KeyMapper.

If something is unclear (because English is not my native language) please ask and I'll do my best to explain.

**Comment by Legioth** [comment]
The framework has support for the scenario that you're describing. You can override `DataProvider.getId(T)` to return something that has a more suitable implementation of `equals` and `hashCode`.

With that being said, there's at least one know case where the implementation still uses the item for checking equality instead of using the container-provided id: https://github.com/vaadin/framework/issues/9380. This issue will hopefully be resolved quite soon.

**Comment by hesara** [comment]
Issue #9380 has been resolved in master, coming at least to 8.1.

**Comment by StarGuardian** [comment]
@Legioth, thank you. I have tried your solution and found that it works well when using method DataProvider.refreshItem(). But it doesn't work when using method DataProvider.refreshAll(), because KeyMapper doesn't use method getId when assigning key to object

**Comment by StarGuardian** [comment]
Probably it is fixed in #9380, I'll check it as soon as migrate to 8.1

**Comment by pleku** [comment]
Closing as it seems that this has been fixed when we added `TreeGrid`.
