### ISSUE TITLE
Binder.bindInstanceFields should bind sub properties

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#9210]
#8384 makes it possible to bind to sub properties but that feature is apparently not used when using `bindInstanceFields`. It should be possible to do e.g.

```
@PropertyId("customer.phoneNumber")
protected TextField phone;

...

BeanValidationBinder<Order> binder = new BeanValidationBinder<>(Order.class);
binder.bindInstanceFields(this);
```

to bind `Order.customer.phoneNumber` to the `phone` field.

**Comment by kaoecoito** [comment]
I have the same problem. When I upgraded from version 7 to 8.0.5 I could no longer use @PropertyId with the sub property.
