### ISSUE TITLE
Tree: unexpected horizontal scrollbar is shown when vertical scrollbar appears 

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#9229]
```
        Tree<String> tree = new Tree<>();
        tree.setHeight("150px");
        tree.setWidth("700px");
        HierarchyData<String> hierarchyData = new HierarchyData<>();
        hierarchyData.addItem(null,"Mercury");
        hierarchyData.addItem(null,"Venus");

// Items with hierarchy
        hierarchyData.addItem(null,"Earth");
        hierarchyData.addItem("Earth","The Moon");

        hierarchyData.addItem(null,"Mars");
        hierarchyData.addItem("Mars","Phobos");
        hierarchyData.addItem("Mars","Deimos");

        inMemoryDataProvider = new InMemoryHierarchicalDataProvider<>(hierarchyData);
        tree.setDataProvider(inMemoryDataProvider);
        tree.expand("Earth");
```
![image](https://cloud.githubusercontent.com/assets/5366945/25663185/a9b46dec-301f-11e7-9ffe-0f01c4cc3fe8.png)

**Comment by tsuoanttila** [comment]
The old Tree component did not actually support setting height, but the height was always dependant of the content of the Tree. And I think the new Tree should do the same. 

The competing scrollbars is an issue from escalator, there has been a detection and recalculations based on the existence of scrollbars, but hiding and showing them again seem to be broken in this particular case.
