### ISSUE TITLE
Vaadin Designer 2 Combobox content syntax not clear

### ISSUE THREAD

**Issue by fante76** [vaadin/framework#9240]
Vaadin version: 8.0.5
Vaadin Designer: 2.0 and 2.1
Description: adding a Combobox and setting its "content" property with following code:
```
<option>CSV</option>
<option>XML</option>
```
produces a declarative combobox like this:
```
<vaadin-combo-box required-indicator-visible caption="formatIdxOutput" page-length="3" empty-selection-allowed="false" id="WriteIndexParametersComponent.FormatIdxOutput" width="100px" data-item-type="java.lang.String" _id="formatIdxOutput">
     <option item="">XML</option>
     <option item="">XML</option>
</vaadin-combo-box>
```
Instead the (wright?) code:
```
<option item="CSV">CSV</option>
<option item="XML">XML</option>
```

Correctly compose the combo.
This happens both in new and existing designs.

With Vaadin 7 and designer 1.x this doesn't happen.

**Comment by Artur-** [comment]
This issue was moved to vaadin/designer-issues#1430
