### ISSUE TITLE
Undeprecate UriFragmentChangedListener and related methods

### ISSUE THREAD

**Issue by hesara** [vaadin/framework#9251]
UriFragmentChangedListener was deprecated in #8116 in anticipation of #8209 being merged, which didn't happen for 8.0. The deprecated API should be undeprecated while #8209 is not integrated.

**Comment by pinonpierre** [comment]
I'm not sure to understand, you will just undeprecate the UriFragmentChangedListener or you will replace it by another thing?

**Comment by Legioth** [comment]
> I'm not sure to understand, you will just undeprecate the UriFragmentChangedListener or you will replace it by another thing?

`UriFragmentChangedListener` will be undeprecated for now because there is no replacement for it. If/when a replacement is actually implemented, `UriFragmentChangedListener` will probably be deprecated again.

**Comment by hesara** [comment]
See #9743 for a reason not to deprecate UriFragmentChangeListener even after pushstate changes are included.

**Comment by QNENet** [comment]
Further to my issue #9743, to the best of my knowledge, UriFragmentChangeListener is the only way to prevent browser back button taking you away from your page.

**Comment by tsuoanttila** [comment]
UriFragment option will remain available and even the default for the time being. Can you open new issues from individual problems you've identified with the PushState based navigation so that we can take a look at each of those problems to see what we can about them?
