### ISSUE TITLE
Cannot Add/Remove Validator after Binder.bind() call

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9255]
Hi,

On Vaadin 8.0.5

I need to remove "required" property or remove a validator after the binder initilizing and it seems not possible !
Another fix for that can be to have capability to disable a validator (e.g.: validator.setEnable(false);)

**Comment by elmot** [comment]
Workaround: you can write your own Validator, which contains some real inner Validator and a boolean flag to skip the validation.

**Comment by Artur-** [comment]
Sounds like the password validator case in the "user admin" in the Bakery app starter. It's quite a bit of code just to get the field to be required for new users and not required when updating info for an existing user.

**Comment by hesara** [comment]
While not an ideal solution, another option is to remove and recreate the binding (requires #9932).

**Comment by Pooky** [comment]
I would also vote to implement this functionality into Vaadin 10. It's pretty common that you want add or remove validator on the fly. I mean if you store validator chain in some list, it should be pretty easy just to get validator and remove ("unbind") it from input.

**Comment by pinonpierre** [comment]
I created a workaround wrapper for that:

```
public class SwitchableValidatorWrapper<T, U extends Validator<T>> implements Validator<T> {

    private final U validator;
    private boolean enabled;

    public SwitchableValidatorWrapper(U validator) {
        this(validator, true);
    }

    public SwitchableValidatorWrapper(U validator, boolean enabled) {
        this.validator = Objects.requireNonNull(validator, "Validator cannot be null");

        this.enabled = enabled;
    }

    public U getValidator() {
        return validator;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public ValidationResult apply(T value, ValueContext context) {
        return enabled ? validator.apply(value, context) : ValidationResult.ok();
    }
}
```

**Comment by Pooky** [comment]
@pinonpierre That`s cool solution. Anyway you still need to store somewhere the reference for wraper and you can`t get it from input like myInput.getValidators().first().remove().setErrorMessage("That`s wrong");

**Comment by pinonpierre** [comment]
@Pooky

You can get the original validator on the wrapper with the getValidator method.

I don't understand your setErrorMessage("Thats wrong").remove()

**Comment by Pooky** [comment]
@pinonpierre  

Well, that's new to me. How you can use "getValidator" on textField? I discover only method "getDefaultValidator()" which I'm not really sure, what it does. The  setErrorMessage("Thats wrong").remove() is just pseudocode, how would I imagine vaadin could work, to make forms and validation more intuitive.

**Comment by pinonpierre** [comment]
@Pooky
Validators are not set on field but on binder. Therefore you cannot take validators from textfield.

Sorry but your pseudocode is not understanding because it doesn't work like this.

I think you should read documentation first

**Comment by TatuLund** [comment]
Is this related to https://github.com/vaadin/framework/issues/11091 ?

**Comment by pinonpierre** [comment]
No relation.
I want to remove a validator after Binder.bind() call.
The #11091 seems to spoke about a bad validation clean up after that the binding was removed

**Comment by TatuLund** [comment]
I closed this issue since, Binder.Binding::unbind() was added in version 8.2.

https://vaadin.com/api/framework/8.6.3/com/vaadin/data/Binder.Binding.html#unbind--
