### ISSUE TITLE
When a Field is not required and empty, validation should not be performed

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9257]
Hi,

On Vaadin 8.0.5

When a Field is not required and empty, other validators should not be executed.

For instance, if I have a not required textfield "postal code" that have a StringLengthValidator (min=5 and max=5).
When the field is empty, binder shouldn't execute the StringLengthValidator, no ?

Regards,

**Comment by Legioth** [comment]
You can achieve that by ensuring that the validators are defined in the desired order. `Binder` will run validators in the order they have been defined until encountering one that doesn't pass. This means that if you add the required validator first (i.e. by running `asRequired` before `withValidator` or `withConverter`), then no other validator will be run when the field is empty.

You're right that it would be great if the required validator would always automatically be injected as the first validator even if `asRequired` is called after e.g. `withValidator`.

**Comment by pinonpierre** [comment]
Sorry, but you did not understand what I said.

If the TextField is empty and if asRequired **is not set**, validators should not be executed!
(Because if field is optional, we should leave the field empty without any constraints)

**Comment by Artur-** [comment]
That would mean that you indicate that the value is valid even though it is not?
This is how Vaadin 6 worked and it had a bunch of problems (in practice empty is not always in sync with required)

**Comment by pinonpierre** [comment]
That would mean that an optional field is always valid when empty!
It's the definition of non-required, no?

**Comment by Legioth** [comment]
I agree that it would in most cases be useful that `Binder` wouldn't run any validators for non-required fields that are empty since you'd otherwise have to explicitly check for that condition in every actual validator.

There would still also have to be some kind of way of bypassing that logic for the special cases where you'd actually want to still perform validation.

There's also the slightly related case of allowing a null representation to bypass validators and converters. This is tracked in #8465.

**Comment by elmot** [comment]
I agree with @Artur. Having that bypass logic for empty filelds will produce lots of confusion. That feature may sound useful but usability should not break logic. I'd prefer to have "allowEmpty" flag on validator level rather than non-obvious shortcut logic in the Binder.
