### ISSUE TITLE
Time is incorrectly parsed in DateTimeField in some cases

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#9272]
In a test with simply
```
layout.addComponent(new DateTimeField());
```

a TestBench test consisting of
```
DateTimeFieldElement d = getDueDateTime();
d.setValue("12/5/25 09:52 AM");
Assert.assertEquals("12/5/25 09:52 AM", d.getValue());
```

does not pass when using JBrowserDriver. The assertion fails because the text in the field is offset by 4 hours (returned value is `12/5/25 05:52 AM`). The value that reaches the server is `07:52 AM`.

Looks like the client side is somehow using the timezone when parsing the date.

**Comment by asashour** [comment]
Is this still valid for `JBrowserDriver`? Because `MultiBrowserTest` test case passes, which means this is not related to `DateTimeField`, but to `JBrowserDriver`, or it is not valid now.
