### ISSUE TITLE
Spreadsheet setRotation not working

### ISSUE THREAD

**Issue by snander** [vaadin/framework#9279]
Using Vaadin framework 8.0.5, Spreadsheet  2.0.0, and applying the following style to a cell does not rotate the text as expected.

HSSFCellStyle myStyle = workbook.createCellStyle();
myStyle.setRotation((short)90);

HSSFCell c = row.createCell(columnNumber);
c.setCellStyle(myStyle);

Additionally, importing simple .xls or .xlsx files, created in Excel, which do contain rotated text into the Spreadsheet demo at https://demo.vaadin.com/spreadsheet/ does not yield the desired results.

**Comment by Artur-** [comment]
This issue was moved to vaadin/spreadsheet#526
