### ISSUE TITLE
Allow changing valueproviders after column creation

### ISSUE THREAD

**Issue by sirbris** [vaadin/framework#9280]
Vaadin 8.1.0.alpha6
It should be possible to set or change the ValueProvider in a Grid (like you now can with Renderer) after columns have been created.

**Comment by divid3byzero** [comment]
+1 for this. 

It can be real pain especially if you need to create grids dynamically and do not know the exact number of columns that you will be having.

**Comment by tsuoanttila** [comment]
Changing of the ValueProvider in a Column is not allowed for type safety reasons. We would need you, the user, to provide the ValueProvider for the column, a new renderer an possibly even a new ValueProvider for the renderer, possibly a new editor component and sorting instructions. If you absolutely must change the whole type of the column every now and then, I'd recommend doing:
```
Grid<T> grid;
Column<T, T> fullBeanColumn = grid.addColumn(t -> t);
``` 
and just change the renderer and it's value extractor. This is an ugly way to do it, but it can be done. Preferably if you need to get a different type of column you should make a new column.

This is only possible with the changes in 8.1.
