### ISSUE TITLE
VaadinService does not remove ServiceDestroyListeners

### ISSUE THREAD

**Issue by pvliss** [vaadin/framework#9291]
There is a very obvious bug and easy fix in method `VaadinService.removeServiceDestroyListener()`:

```
public abstract class VaadinService implements Serializable {
    ...
    public void removeServiceDestroyListener(ServiceDestroyListener listener) {
          serviceDestroyListeners.remove(serviceDestroyListeners);
    }
    ...
}
```

The fix is: 

```
public abstract class VaadinService implements Serializable {
    ...
    public void removeServiceDestroyListener(ServiceDestroyListener listener) {
          serviceDestroyListeners.remove(listener);
    }
    ...
}
```

I found this after profiling sessions in our Spring Boot-Vaadin application. The [Vaadin Spring Addon](https://github.com/vaadin/spring) registers a `ServiceDestroyListener` in [UIScopeImpl](https://github.com/vaadin/spring/blob/master/vaadin-spring/src/main/java/com/vaadin/spring/internal/UIScopeImpl.java) which is never removed when a session is destroyed, hence leading to a **memory leak** as sessions are never destroyed.

The problem seems to be caused from changes applied in commit 61938da3c22d62dc80c993a321ac2c6096510e08 for issue #7037.

I can create a pull request if you wish.

Regards,

**Comment by pvliss** [comment]
Hmmm, looking again at the code it seems that I have been seeing code from another vaadin version. 

Sorry for the trouble. 

Please ignore it.

**Comment by hesara** [comment]
Actually, this seems to be a real issue for service destroy listeners in master - but not for session destroy listeners, which is maybe what you saw when closing the issue.

**Comment by pvliss** [comment]
Hello @hesara,

I was just taking another look and was confused by the `removeSessionDestroyListener()`. Ye,s the issue is indeed in there. Thanks for double checking

**Comment by tsuoanttila** [comment]
This was picked to 8.0.7
