### ISSUE TITLE
Drag source's draggable attribute may be mistakenly removed when removing drag source extension and there are multiple extensions attached

### ISSUE THREAD

**Issue by wbadam** [vaadin/framework#9294]
When removing drag source extension, need to check if there are other drag source extensions attached and only remove `draggable` if there are no others.

**Comment by pleku** [comment]
Not sure if there really is a use case for having multiple `DragSource` or `DropTarget` extensions added to the same component. And even in those cases, one of the extensions might be adding the `draggable` attribute to some part of the component in DOM, but not actually to the root element.
