### ISSUE TITLE
com.vaadin.ui.Upload, uploadFinished method

### ISSUE THREAD

**Issue by andreika63** [vaadin/framework#9295]
Hi!
- Vaadin version: 8.0.5
- Description of the bug:
I'm trying to implement data upload, when file loaded into memory I use uploadFinished(Upload.FinishedEvent event) method to save data into database.
But if my save(data) method generates an exception (in my case save null data into NotNull database column)
uploadFinished method runs again from begin!
@Override
    public void uploadFinished(Upload.FinishedEvent event) {
            isReadyToReceive = false;
            count = 0;
            ByteArrayInputStream bais = new ByteArrayInputStream(buffer);
            DbfReader dbfReader = new DbfReader(bais);

            some method with exception...
}

**Comment by hesara** [comment]
Indeed, the framework first fires a SucceededEvent, and when it throws an exception, a FailedEvent is sent. As both are subclasses of FinishedEvent, the method uploadFinished is called again.

I agree this is not really ideal, but at least as a workaround in your case you can check the type of the event.
