### ISSUE TITLE
Error message and styling shown on entry of correct date in DateField.

### ISSUE THREAD

**Issue by TheFringe** [vaadin/framework#9298]
**Description**
After two incorrect entries and then a correct entry in a DateField, an error message and error styling is  shown. Related to #9296  

**Version**
8.0.6
8.0-SNAPSHOT
8.1-SNAPSHOT

**Test case**
[date-test.zip](https://github.com/vaadin/framework/files/992874/date-test.zip)

1. Enter correct date.

2. Enter an incorrect date

3. Enter a (different) incorrect date.

4. Enter a correct date.

**Comment by hesara** [comment]
See also #8687 - the same issue is also mentioned there.

**Comment by asashour** [comment]
I believe this should be closed, I can't reproduce with current `master` branch.

**Comment by tsuoanttila** [comment]
Tested with `8.2-SNAPSHOT` with the instruction in the first message, seems to work for me too.
