### ISSUE TITLE
Binder: missing isReadOnly method 

### ISSUE THREAD

**Issue by jrfinc** [vaadin/framework#9302]
I'm not sure if this is the correct place to put this, but I think the Binder is missing a getter for the readOnly property. 

I can do `binder.setReadOnly(true)`. But there is no `isReadOnly()`. Not sure if there's a reason behind leaving this out, but I would find it useful.  (I'm migrating from a fieldgroup to using a binder, and the fieldgroup used to have it).

**Comment by Artur-** [comment]
Sounds pretty much like #9116

**Comment by jrfinc** [comment]
Oops sorry, closing it.
