### ISSUE TITLE
Memory leak when updating the UI and no server visits or push take place

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#9303]
#7748 fixes a memory leak in ConnectorTracker when updating the UI without any updates going to the client. There are however more similar issues still in `ConnectorTracker`. 

Whenever you unregister a component, it gets added to the `unregisteredConnectors` set. This set, and related data structures, is cleaned only after a UIDL update is sent to the client. If there is no UIDL update sent, the `unregisteredConnectors` set will keep growing as long as you remove components from the UI.

**Comment by Artur-** [comment]
A solution to this would be to clean the set at the end of `UI.access` instead of after writing a UIDL

**Comment by hesara** [comment]
Probably will change milestone when integrating backport.
