### ISSUE TITLE
Vaadin Widgetset Not Compiling with Version 8.0.6

### ISSUE THREAD

**Issue by mikleing** [vaadin/framework#9314]
Vaadin Widgetset is not compiling with version 8.0.6.  It works on version 8.0.5.  To reproduce the issue create a new Vaadin Project using the vaadin-archetype-application using version 8.0.6.  Then compile the widgetset.  Here is the error that is generated:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building myapplication 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:update-widgetset (default-cli) @ myapplication ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] No widgetsets found - generating AppWidgetset if necessary.
[INFO] Updating widgetset AppWidgetset
[INFO] Adding resource directory to command classpath: C:\Users\mikle\workspace\myapplication\src\main\resources
[INFO] Adding resource directory to command classpath: C:\Users\mikle\workspace\myapplication\target\generated-resources\gwt
[INFO] Using com.vaadin:vaadin-client version 8.0.6
[INFO] Using com.vaadin:vaadin-client-compiler version 8.0.6
[ERROR] Error: Could not find or load main class com.vaadin.server.widgetsetutils.WidgetSetBuilder
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.126 s
[INFO] Finished at: 2017-05-13T11:13:30-05:00
[INFO] Final Memory: 14M/333M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:8.0.6:update-widgetset (default-cli) on project myapplication: Failed to update widgetset: Command [[
[ERROR] C:\Program Files\Java\jdk1.8.0_51\jre\bin\java com.vaadin.server.widgetsetutils.WidgetSetBuilder AppWidgetset
[ERROR] ]] failed with status 1
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by tsuoanttila** [comment]
I could not reproduce this issue. Tested this with a cleaned maven cache, generating the single module application archetype, added vaadin-charts to make the widgetset required. Update and compilation of the widgetset succeeded. Can you try removing all Vaadin 8.0.6 artifacts from your local maven repo and re-downloading?

**Comment by mikleing** [comment]
It appears this issue was likely caused by my Eclipse classpath not being correctly updated with changes to the Maven pom file.  To update the Eclipse classpath I had to run "mvn eclipse:eclipse" inside the project folder.  Maven builds, cleaning, and updating within Eclipse did not work.
