### ISSUE TITLE
New 8.1 Tree component missing all style methods

### ISSUE THREAD

**Issue by neerup** [vaadin/framework#9323]
The new 8.1 Tree is missing all style methods
Making it imposible to style trees individually

Missing implementation for methods:
    @Override
    public String getStyleName() {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public void setStyleName(String style) {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public void setStyleName(String style, boolean add) {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public void addStyleName(String style) {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public void removeStyleName(String style) {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public String getPrimaryStyleName() {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

    @Override
    public void setPrimaryStyleName(String style) {
        throw new UnsupportedOperationException(COMPOSITE_HAS_NO_DOM_OR_WIDGET);
    }

**Comment by pleku** [comment]
Thanks for the report!
