### ISSUE TITLE
ItemClick for Tree and TreeGrid do not support getButton() method

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#9335]
Regression from V7

**Comment by hesara** [comment]
I don't really understand what getButton() method this refers to and what it would do. ItemClick does have getSource() and getItem() but no more specific information about the column or component clicked, though.

**Comment by Legioth** [comment]
Corresponding events in the V7 version of `Tree` inherit `getButton()` from `com.vaadin.event.MouseEvents.ClickEvent`.

**Comment by hesara** [comment]
There are quite a few methods in the old ClickEvent, some of which might be superfluous, and whatever is applied to Tree.ItemClick should probably also be applied to Grid.ItemClick.

As a first step, adding MouseEventDetails to the ItemClick event as it can be used to obtain information about the mouse button and many other things.

**Comment by elmot** [comment]
Fixed via #9599

**Comment by pinonpierre** [comment]
There is an issue.
I updated to 8.1.0.rc1 and event of addItemClickListener is not emitted on right click.
