### ISSUE TITLE
Grid column should not behave like it's sortable if it can't be sorted

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#9350]
If you set up a column with a getter and do not provide a sort property, then the column behaves in the UI like it would be sortable (header click toggles the sort indicator up/down) but nothing happens when you click on the header. When the column can't be sorted, the UI should not react to header clicks in any way.

**Comment by Legioth** [comment]
Might want to have three different modes for column sortability similarly to the three different modes for the select all checkbox.

The default would be a mode that enables sorting if using an in-memory data provider or a sort property name (or column id, or sort order provider) is available.

Could also be debated whether we should throw an exception or log a warning if trying to use the explicitly enabled mode under circumstances where it's basically certain that it wouldn't work. By doing that, the developer would have a chance of understanding what they need to do to actually make it possible to sort the column.
