### ISSUE TITLE
ShortcutListener does not work inside PopupView

### ISSUE THREAD

**Issue by yoursnowyfriendleo** [vaadin/framework#9356]
Add a ShortcutListener does not work on fields or buttons inside Popup Views for the FIRST time you open popup view in a release build (works in debug build, though) and works any consecutive times.
Tested on popupbutton-2.6.0 and vaadin-server-7.7.9.

		VerticalLayout layout = new VerticalLayout();

		TextField tf = new TextField("Text field");
		tf.setImmediate(true);
		tf.focus();
		layout.addComponent(tf);

		Button btn = new Button("Click me!", (Button.ClickListener) event -> Notification.show("Btn"));
		btn.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		layout.addComponent(btn);

		addComponent(layout);

**Comment by yoursnowyfriendleo** [comment]
Debug build is development mode, i.e. logging and debugging enabled.

**Comment by Legioth** [comment]
Do you mean Vaadin's `productMode` setting, or is there also something else involved here?

**Comment by yoursnowyfriendleo** [comment]
Yeap, vaadin pruductMode setting
