### ISSUE TITLE
TreeGrid expanded/collapsed state out of sync problem

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/framework#9358]
When a TreeGrid is shown in a SubWindow, if a node is expanded, and then the SubWindow is closed (`window.close()`), if the same window is opened again (`UI.getCurrent().addWindow(window)`), the node in the client side appears collapsed, but the status of the server side of the component is expanded.

I've created a small example that reproduces the problem. If you run it, there is a button that will open a PopUp, showing the first node expanded programmatically, if you hit close and then open it again, the node will be collapsed, even though `treeGrid.expand()` was called explicitly. If you close the window, and then open it again, this time the node will be expanded, and so on.

This was reproduced on Vaadin 8.1.0.alpha6

[treegridproblem.zip](https://github.com/vaadin/framework/files/1009463/treegridproblem.zip)

**Comment by elmot** [comment]
Thanks for your feedback. Apparently there is a client-side cache is not reset properly.

**Comment by elmot** [comment]
Reproduced on alpha8.

**Comment by hesara** [comment]
Please test if this is still reproducible in 8.1.0.beta2, which had some hierarchy data handling fixes.

**Comment by tsuoanttila** [comment]
Updated the project to 8.1.0.beta2, issue was no longed reproduced. Closing. Please open a new issue if this is still a problem.
