### ISSUE TITLE
Layout iterator.remove() modifies internal list, causing inconsistent state

### ISSUE THREAD

**Issue by emarc** [vaadin/framework#9404]
Verified with 8.0.6.

The iterator() method of AbstractOrderedLayout, CssLayout (and probably others) just calls iterator() on the internal `LinkedList<Component> components`. As a result, calls to iterator.remove() are passed trough, and the component is removed from the layout's internal components list, but w/o doing the other things required to properly remove a component, leaving the layout in an inconsistent state.

Why is this important:
Calling iterator.remove() will (visually) remove the component or not, depending on other circumstances. This means that behaviour might change when something in a completely different part of the application is changed, leading to "interesting" debugging.
Also, the layout is _always_ left in an inconsistent state when iterator.remove() is used.

Example:
```
	protected void init(VaadinRequest vaadinRequest) {
		final VerticalLayout layout = new VerticalLayout();
		setContent(layout);

		Button button = new Button("Remove");
		layout.addComponent(button);
		button.addClickListener(e -> {
			Iterator<Component> it = layout.iterator();
			if (it.hasNext()) {
				final int before = layout.getComponentCount();
				Component removed = it.next();
				it.remove();
				final int after = layout.getComponentCount();

				System.err.println("Count " + before + "->" + after);
				System.err.println("Removed still has parent: " + removed.getParent());

				// You can see the removed component still has state, BUT this
				// will cause repaint for some reason; let's leave it commented
				// for a more clear example:
				// System.err.println("Removed still has alignment (state): " +
				// layout.getComponentAlignment(removed));

			} else {
				System.err.println("Layout is empty - WHAT are you clicking on?");
			}
		});

		button = new Button("Refresh");
		layout.addComponent(button);
		button.addClickListener(e -> {
			layout.markAsDirty();
		});

	}
```

**Comment by tsuoanttila** [comment]
This was picked to 8.0.7
