### ISSUE TITLE
Navigator.init(UI ui, NavigationStateManager stateManager, ViewDisplay display) should unregister default UriFragmentManager from Page object before setting the new one

### ISSUE THREAD

**Issue by apolds** [vaadin/framework#9406]
If you instantiate (or inject) a Navigator object with the default constructor, it will get the UriFragmentManager as default NavigationStateManager. The UriFragmentManager will register itself as UriFragmentChangedListener at the Page object.

Now, when you call Navigator.init(UI ui, NavigationStateManager stateManager, ViewDisplay display) to set a custom NavigationStateManager, the default UriFragmentManager will not be unregistered as UriFragmentChangedListener from the Page object.

So on each URI fragment change both, the default UriFragmentManager and the custom NavigationStateManager, will get called. This causes the Navigator to navigate twice.

Possible Solution:
```
protected void init(UI ui, NavigationStateManager stateManager,
            ViewDisplay display) {
        this.ui = ui;
        this.ui.setNavigator(this);
        if (stateManager == null) {
            stateManager = new UriFragmentManager(ui.getPage());
        }

        // unregister old stateManager
        if (getStateManager() != null && stateManager != null) {
            stateManager.setNavigator(null);
        }

        this.stateManager = stateManager;
        this.stateManager.setNavigator(this);
        this.display = display;
    }
```

**Comment by hesara** [comment]
Addressed in 7.7.10 and 8.1.0.beta1.
