### ISSUE TITLE
Impossible to Guarantee Current Value Without ValueChangeMode.EAGER

### ISSUE THREAD

**Issue by bdunn44** [vaadin/framework#9419]
Vaadin 8.1.0.alpha8

I would expect Vaadin to satisfy the following requirements:

1. Minimize server traffic.
2. Ensure that server side data matches client side input when processing events initiated by the user.
  a. I don't want to create a new user with a name entered 400ms ago. (Ex: "bdun" vs. "bdunn44")

With the current ValueChangeMode options it is impossible to guarantee that the value entered in a field will be accurately reflected on the server side without using ValueChangeMode.EAGER, and I'm not a fan of the baggage (additional traffic) that comes with it.

ValueChangeMode.BLUR is **very** close, but doesn't work if using a KeyCode shortcut.

```java
final TextField name = new TextField("Name");
name.setValueChangeMode(ValueChangeMode.BLUR);
name.setValueChangeTimeout(1000);
name.addValueChangeListener((e) -> System.out.println("Value Changed: " + e.getValue()));
final Button toggle = new Button(name.getValueChangeMode().toString());
toggle.addClickListener((e) -> {
    int o = name.getValueChangeMode().ordinal();
    int i = ValueChangeMode.values().length <= o+1 ? 0 : o+1;
    ValueChangeMode m = ValueChangeMode.values()[i];
    toggle.setCaption(m.toString());
    name.setValueChangeMode(m);
    System.out.println("New ValueChangeMode: " + m.toString());
});
final Button submit = new Button("Submit", 
    (e) -> System.out.println("Submitted value: " + name.getValue()));
submit.setClickShortcut(KeyCode.ENTER);
layout.addComponent(name);
layout.addComponent(toggle);
layout.addComponent(submit);
```

P.S. IMO, ValueChangeMode.BLUR should really be the default. Anything else (other than EAGER) almost guarantees errors when you have power users banging away at the keyboard, meaning I have to go through my application and manually set it everywhere.

**Comment by hesara** [comment]
In theory this should be handled by ShortcutActionHandler.fireAction() calling ApplicationConnection.flushActiveConnector(), which should save the value of the currently active (focused) text field or similar component before the shortcut is actually processed. Other fields (if in BLUR mode) should already have sent their values before the current component was focused. If this is not working, there is a bug in the mechanism.

**Comment by hesara** [comment]
In master (8.1), I was not able to produce different values for the two print statements using the BLUR mode, nor most other modes as in the example above and the keyboard shortcut for the button.

In timeout and lazy modes, I was able to get some value changes after the submit, but I suspect even these came from me actually pressing the keys in that order as I tried to go as fast as I could with two hands.

**Comment by bdunn44** [comment]
My apologies - the example I posted was incomplete. This should reliably reproduce the issue:

```java
VerticalLayout content = new VerticalLayout();
HorizontalLayout buttons = new HorizontalLayout();
final TextField name = new TextField("Name");
name.setValueChangeMode(ValueChangeMode.BLUR);
name.setValueChangeTimeout(1000);
name.addValueChangeListener((e) -> System.out.println("Value Changed: " + e.getValue()));
final Button toggle = new Button(name.getValueChangeMode().toString());
toggle.addClickListener((e) -> {
    int o = name.getValueChangeMode().ordinal();
    int i = ValueChangeMode.values().length <= o+1 ? 0 : o+1;
    ValueChangeMode m = ValueChangeMode.values()[i];
    toggle.setCaption(m.toString());
    name.setValueChangeMode(m);
    System.out.println("New ValueChangeMode: " + m.toString());
});
final Button submit = new Button("Submit", 
    (e) -> System.out.println("Submitted value: " + name.getValue()));
submit.setClickShortcut(KeyCode.ENTER);
buttons.addComponent(toggle);
buttons.addComponent(submit);
content.addComponent(name);
content.addComponent(buttons);
Window popup = new Window();
popup.setContent(content);
getUI().addWindow(popup);
```

It appears the issue occurs when the components are contained within a Window. Using a keyboard shortcut in this case does not fire a value change event in my environment.
