### ISSUE TITLE
Grid rowHeight should not or only optionally effect the header rows

### ISSUE THREAD

**Issue by christoph-frick** [vaadin/framework#9425]
Using V8.1-SNAPSHOT: when setting the rowHeight of the grid, all rows have that set height -- even the header rows (untested but assuming, this is the same for the footer).  The ideal behaviour would be to have rowHeight for each type of row (headers, footers, body rows) or at least to only effect the body rows by that setting.

**Comment by kamuffe** [comment]
Hi.

I aggree with Christoph.
Footer rows are affected as well. 

Additionally it would be nice if the row height are calculated by the contents. That way we needn't to set the height at all. E.g. if the row height is not set it gets calculated by the contents.

Regards :)

**Comment by wilsontjohnson** [comment]
I am also putting a vote in for this enhancement.

With the addition of component support inside of a grid this is sorely needed as one can have Layouts specified inside of each cell.

I would say that normally headers and footers are used for:
Toolbars relating to the whole grid (i.e. Submit Query, Remove all Filters...).
Single-Line Data for the whole grid (i.e. row count, response time, loading bars...).
Column Labels.
Column Filters.

At most I have had 3 headers of default height and 1 footer, If I need my inner column height to be 75px, that removes 300px of real-estate from my view.

Personally I consider this a bug/oversight as this goes against the ability to generate components for a grid.

**Comment by christoph-frick** [comment]
Thank you for patching this
