### ISSUE TITLE
@PreserveOnRefresh doesn't work with shared sessions

### ISSUE THREAD

**Issue by markathomas** [vaadin/framework#9435]
With @PreserveOnRefresh set and using shared sessions with spring-session failing over to another server does not preserve the current view.  In fact, on the first UI interaction after failing over to another server the UI reverts to the initial state.  I believe this is due in part to the clientId being reset to 0 causing a full repaint of the UI.

**Comment by Artur-** [comment]
`@PreserveOnRefresh` takes effect only when you refresh the browser and will then find the old UI instance and re-use that. If has no effect if you just do UIDL request, i.e. interactions in the UI. 

If the session fails over to another server, then everything should just work as long as the UIDL request finds 
1. the correct `HttpSession` instance (based on the JSESSIONID cookie)
2. the correct `VaadinSession` instance inside that (based on service name, i.e. servlet name)
3. the correct ´UI` instance inside that (based on `v-uiId` passed in the UIDL request)

Do you get this far? If it goes wrong after that, what I can think of is that some Spring injections go wrong for some reason.

**Comment by markathomas** [comment]
I can verify 1 and 2 above but i'm not sure about 3. there's definitely some issues after failing over as parts of the UI don't render anymore thus I'm forcing a page refresh after failing over.  I'll have to check the v-uiId

**Comment by brunojcm** [comment]
Any news on that? I'm also trying to investigate why I lose my session data when restarting the server with session serialization enabled.

**Comment by markathomas** [comment]
This is still a serious bug for me.

**Comment by TatuLund** [comment]
The issue description lacks some detail, but I would guess, the problem is the same as described here: https://github.com/vaadin/framework/issues/4422
