### ISSUE TITLE
Table Scrolling Wrong when updating items

### ISSUE THREAD

**Issue by Ramonrune** [vaadin/framework#9436]
Hello,

I'am using a ListContainer and a lazy list to load some data into a MTable.
But when i try to update MTable, scroll bar goes to a wrong area. It only happen's in the middle of table, not in the start or end. Example: update item 41 and scroll bar goes to item 81.

Code:
Add items into table:
List lazy = new LazyList<>(service::fetchTransactions, service::getTransactionCount, service.PAGE_SIZE);
ListContainer listContainer = new ListContainer(File.class, lazy);
table.setContainerDataSource(listContainer);

Update:
table.getItem(itemid).getItemProperty("propertyhere").setValue(status);
table.refreshRowCache();

Link to forum with a sample and more info.

https://vaadin.com/forum#!/thread/15708606

**Comment by Artur-** [comment]
Same as #9125
