### ISSUE TITLE
TreeGrid Item Removal Using an Iterator Produces an Inconsistent State

### ISSUE THREAD

**Issue by bdunn44** [vaadin/framework#9446]
8.1.0.beta1

I have a scenario where I need to refresh `TreeGrid` contents after certain user-initiated events. The logic for doing so is:

1. Add items which have not already been added
2. Remove items which no longer exist in the persistence layer

My initial approach was to use an `Iterator` to remove items, which appears to be buggy. When removing an item using this approach the item is no longer visible in the UI, but attempting to add it again fails. The example below reproduces this issue (add an item, remove it, and then add it again).

```java
HorizontalLayout buttons = new HorizontalLayout();
TreeGrid<String> tree = new TreeGrid<>();
TreeData<String> data = new TreeData<>();
tree.setDataProvider(new TreeDataProvider<>(data));
tree.addColumn(String::toString);
ComboBox<String> select = new ComboBox<>();
select.setEmptySelectionAllowed(false);
select.setItems(Arrays.asList("First", "Second", "Third"));
Label status = new Label();
Button add = new Button("Add Item", (e) -> {
	if (data.contains(select.getValue())) {
		status.setValue(select.getValue() + " has already been added!");
		return;
	}
	data.addItem(null, select.getValue());
	tree.getDataProvider().refreshAll();
	status.setValue(select.getValue() + " added");
});
Button remove = new Button("Remove Item", (e) -> {
	if (!data.contains(select.getValue())) {
		status.setValue(select.getValue() + " hasn't been added!");
		return;
	}
	Iterator<String> it = data.getChildren(null).iterator();
	while (it.hasNext()) {
		String sb = it.next();
		if (sb.equals(select.getValue())) {
			it.remove();
			break;
		}
	}
	tree.getDataProvider().refreshAll();
	status.setValue(select.getValue() + " removed");
});
content.addComponent(tree);
content.addComponent(status);
content.addComponent(select);
content.addComponent(buttons);
buttons.addComponent(add);
buttons.addComponent(remove);
```
These two methods of removing the item work as expected:
```java
data.removeItem(select.getValue());
```
```java
new ArrayList<>(data.getChildren(null)).forEach(s -> {
	if (s.equals(select.getValue())) {
		data.removeItem(s);
	}
});
```

**Comment by hesara** [comment]
Addressing this at the moment by making the child list returned by getChildren() immutable and documenting that. It would also be possible to use a custom iterator that supports remove(), but most parts of the framework do not take that approach so going for the simple and consistent solution that at least reports the error earlier and explicitly.
