### ISSUE TITLE
TreeGrid Sort and Refresh Should Maintain Expansion State

### ISSUE THREAD

**Issue by bdunn44** [vaadin/framework#9448]
8.1.0.beta1

I have a requirement where I need to refresh items within my `TreeGrid` hierarchy in response to user-initiated events (adds, updates, deletes). After refreshing these items, I need them to display in sorted order (instead of having new items appear at the bottom), however sorting clears the state of item expansion. 

```java
HorizontalLayout buttons = new HorizontalLayout();
TreeGrid<String> tree = new TreeGrid<>();
TreeData<String> data = new TreeData<>();
tree.setDataProvider(new TreeDataProvider<>(data));
tree.addColumn(String::toString);
for (String root : new String[]{"First", "Second", "Third"}) {
	data.addItem(null, root);
	for (String child : new String[]{"1", "2", "3"}) {
		data.addItem(root, root + " - " + child);
	}
}
Button sort = new Button("Sort", e -> tree.sort(tree.getColumns().get(0)));
Button refresh = new Button("Refresh", e -> tree.getDataProvider().refreshAll());
content.addComponent(tree);
content.addComponent(buttons);
buttons.addComponent(sort);
buttons.addComponent(refresh);
```

**Comment by scrmtrey91** [comment]
Yeah i noticed that too. TreeGrid should act like TreeTable in 7.7.9 which is working great. I know its beta but still, this feature is major to maintain state of component even if u fetch fresh (same data) from backend.  Also when sorting, it should maintain state.

**Comment by hesara** [comment]
HierarchicalDataCommunicator.sendDataToClient() does indeed call loadInitialData(), which resets the mapper and does not try to keep expanded node information. This is needed for some refresh situations like explicit reset where anything can have changed, but could be made less drastic in others like sorting (although we still need to recalculate HierarchyMapper.nodes and HM.collapsedNodes indices or reconstruct those structures).

I'd consider this a missing feature. I'll put this tentatively to the milestone 8.1.0 although I cannot guarantee that we manage to add this by then.
