### ISSUE TITLE
Off-by-one error when dragging a Grid row upwards in Sampler demo

### ISSUE THREAD

**Issue by jdahlstrom** [vaadin/framework#9451]
When dragging a row upwards in Grid, the row ends up at an index that is one less than expected. This might also be a bug in the sample based on the stack trace.

Version: Whatever Sampler is running

How to reproduce: 

1. Go to https://demo.vaadin.com/sampler/#ui/drag-drop/grid-drag-rows-html5
2. In the left-side Grid, drag any row upwards in `BETWEEN` mode
3. Observe that the row ends up one row higher than the marker indicated
4. If dragging to the top of the grid, observe that an `IOOBE` happens and the row is lost

**Comment by hesara** [comment]
This looks like a regression from a fix for a similar issue when dragging rows downwards in a Grid.

**Comment by jdahlstrom** [comment]
Yeah, figured. When you move downwards you have to take into account the index change due to the removed row, when you move upwards you don't.
