### ISSUE TITLE
BeanValidatorBinder will silently ignore missing setters

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#9466]
Vaadin 8.1.0.beta1

If a bean is accidentally missing a setter and it is edited by a Binder and bound by bind(String), Binder will silently ignore the missing setter and will silently not set any value to the bean. Since Binder is full of smart lambdas and closures, it is basically undebuggable, thus the programmer has no way of finding out that the setter is missing.
Is there any merit of having a read-only property in a Binder?

**Comment by hesara** [comment]
Read-only properties are commonly used and requested by users, and on the binding level it is clearly documented that if no setter is provider or if using a property name for binding and there is no corresponding setter, the binding is read-only. Likewise, Binder.bind(HasValue, String) javadoc clearly states that if there is no such setter, the binding is read-only.

I'd consider that the code works as intended and the javadoc is clear and explicit on this.
