### ISSUE TITLE
grid.getSelectedItems() not synchronized with dataprovider items

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9469]
Hi,

On Vaadin 8.0.5,

When the DataProvider associated to the grid is refreshed, the Grid.getSelectedItems() return old items. (FYI: I defined "Object getId(T item)" in the DataProvider)

My workaround is to manually call grid.deselect(oldItem) and to call after grid.deselect(newItem) to update it whereas getId method of DataProvider return the same ID

How can I do to always have SelectedItems synchronized?

Thanks,

**Comment by Artur-** [comment]
Possibly fixed in 8.1 by #9380

**Comment by pinonpierre** [comment]
I confirm

Thanks,
