### ISSUE TITLE
Vaadin Valo Menu Responsiveness broken in 8.1.0.beta1

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#9473]
If I go to https://demo.vaadin.com/valo-theme/#!common and resize the browser window, the menu is correctly shrink and even disappears when the window is too narrow. Please see screenshot below.

However, when I try to run the same valo theme application from Vaadin master sources (8.1-SNAPSHOT), the menu is not resized, instead the whole page 'zooms out'.

This is the screenshot from the online valo-theme demo, which works properly.
![screenshot_20170602_174742](https://cloud.githubusercontent.com/assets/254091/26731091/994fa706-47bb-11e7-8185-840d8474e2da.png)

**Comment by mvysny** [comment]
This is the screenshot from 8.1-SNAPSHOT:
![screenshot_20170602_175728](https://cloud.githubusercontent.com/assets/254091/26731504/fb848b02-47bc-11e7-9ec6-dde458b45301.png)

**Comment by tsuoanttila** [comment]
Tested the same functionality in my SideMenu add-on demo, and the same issue was not present there. Still need to test the valo-theme demo you tested, but at least it seems to be working elsewhere.

**Comment by mvysny** [comment]
Thank you for letting me know, I'll try the SideMenu add-on

**Comment by mvysny** [comment]
Okay, so when the `@Viewport("width=device-width, initial-scale=1.0")` annotation is missing from the UI, bloody Chrome's "Device Toolbar" zooms out instead of resizing of the window. I would really appreciate any hint of why is that a feature.
Anyway, by adding of the `@Viewport("width=device-width, initial-scale=1.0")` annotation to the UI (and making sure that `Responsive.makeResponsive(ui)` is called, finally the Chrome's "Device Toolbar" actually starts to resize the viewport instead of scaling it.
