### ISSUE TITLE
Grid items randomly updated

### ISSUE THREAD

**Issue by amahdy** [vaadin/framework#9475]
- Vaadin version: 8.0.6
- Description of the bug:
If the bean underlying the grid gets updated, the grid refreshes the items randomly.

- If possible, minimal reproducible example:

Using this POJO:

```java
public class P {
    String p;
    P(String p) {setP(p);}
    public String getP() {return p;}
    public void setP(String p) {this.p = p;}
}
```

Here is a complete detailed code on how to reproduce:

```java
public class MyUI extends UI {

    P v,w;

    @Override
    protected void init(VaadinRequest vaadinRequest) {

        List<P> x = Arrays.asList(new P("one"), new P("two"), new P("tri"));

        Grid<P> g = new Grid<>(P.class);
        g.setItems(x);

        g.asSingleSelect().addValueChangeListener(evt -> {
            w = evt.getValue();
            v = evt.getOldValue();
        });

        setContent(new VerticalLayout(new Label("1. Select an item from the grid,<br>" +
                "Click on the first button,<br>" +
                "Slect a different item,<br>" +
                "The modified value appears <b>too late</b>.<br><br>" +
                "2. Following previous steps,<br>" +
                "Click on the second button,<br>" +
                "Now try to select different items from the grid except the previously selected,<br>" +
                "Once you click on the previously selected <b>only</b> you get the updates.", ContentMode.HTML),
                g,
                new Button("[1] Change current value", evt -> {
            w.setP("Selected value changes.");
        }), new Button("[2] Change previous value", evt -> {
            v.setP("Unselected value does not change.");
        })));
    }
}
```

The problem mainly is that, the grid does not have consistent refresh mechanism when data is modified. At least when the item is not selected, it does not get updated if modified somewhere else.

Reference discussion: https://vaadin.slack.com/archives/C04JL39LW/p1496410060455926

**Comment by tsuoanttila** [comment]
You're not telling the Grid that you updated a data object. Since we no longer use extensive and memory consuming wrapping of every single object, the app developer needs to call `DataProvider#refreshItem` in order to make the grid update. See also: `Grid#getDataProvider`

When the user makes a change that causes the grid to re-render the row that was changed (deselect), the new data is used.
