### ISSUE TITLE
RadioButtonGroup in compibnation with Caption Generator and initial value does not work reliable

### ISSUE THREAD

**Issue by dathyrius** [vaadin/framework#9476]
Here is my example. The first option is selected automatically. If you change to the second option, the captions change but the first is shown as selected. If I remove the line " radioButtonGroup.setValue(0);" not item is selected initially, but the change of the captions is working. 

public class MyUI extends UI {

    int count;

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final VerticalLayout layout = new VerticalLayout();

        final RadioButtonGroup<Integer> radioButtonGroup = new RadioButtonGroup<>("RBG",
                Arrays.asList(0, 1));

        radioButtonGroup.setItemCaptionGenerator((e)
                -> {
            return e == 0 ? "German" + count++ : "Russion" + count++;
        });
        radioButtonGroup.setValue(0);
        layout.addComponents(radioButtonGroup);
        radioButtonGroup.addValueChangeListener((e) -> radioButtonGroup.getDataProvider().refreshAll());
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}

**Comment by tsuoanttila** [comment]
The issue lies somewhere between the initially selected value and the call to `refreshAll` method. When the value change listener is called after selecting the second option, the server-side state is correct and up to date, but the full refresh of every item is shown incorrectly on the client-side. I did not have time to debug all the way to the cause of this.

**Comment by hesara** [comment]
@dathyrius please re-test this with the latest 8.1-SNAPSHOT, or with 8.1.1 once it is out.
