### ISSUE TITLE
Modal Vaadin Designer license windows blocks Eclipse, no "continue unlicensed" button anymore

### ISSUE THREAD

**Issue by ilmarmors** [vaadin/framework#9484]
I'm using Eclipse Neon, I upgraded from Vaadin 7 to Vaadin 8. I have Vaadin Designer 1.3.2 and Vaadin Designer 2 2.1.2 installed in Eclipse, not sure which were used when I opened existing XXXFormDesign.html file

Previously user could open design html file in Vaadin Designer and, when licensing dialog pops-up, press "continue unclicensed" button, if he wanted. Now there is no such button, you can't close dialog box with red close button. And this is modal dialog, so you can't close html file. Very annoying, especially when you click on html file by accident.

![screen shot 2017-06-05 at 15 56 36](https://cloud.githubusercontent.com/assets/249045/26785400/cffdb314-4a0a-11e7-9ee5-2b2dbad39994.png)

I could continue using Eclipse only after I manually removed XXXFormDesign.html open tab reference in .metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi

**Comment by Artur-** [comment]
This issue was moved to vaadin/designer-issues#1452
