### ISSUE TITLE
Confirm dialog problems

### ISSUE THREAD

**Issue by ValentinTudorM** [vaadin/framework#9491]
Vaadin has as a big competitive advantage making the model-view-flow management very simple and straightforward.
A simple "details" as available variant of realizing a confirmation dialog (yes/no and similar) can blow-up this advantage. 
The available solutions are based on splitting the flow management in an asynchronous  manner, using listeners. Example Message Box Add-On or Confirmation Window from VAADIN Cookbok book.   
Example 
```
ConfirmWindow window = new ConfirmWindow("Question","Do you want to fetch " + value + "'s details?","Yes", "No");
window.setDecision(new Decision() {
@Override
public void yes(ClickEvent event) {
// fetch user
}
@Override
public void no(ClickEvent event) {
}
}
```

Consider that we can have consecutive yes/no simple validation question. It is an absolute useless over-design to split the flow functions every time. With 4 question, we will have 2^4 events functions ? That will be a mess.
Good technologies must provide physical support for protecting logical sequences.  We need support for confirmation dialogs that will not introduce artificial splits in the flow sequence.

**Comment by Legioth** [comment]
Your example is usually described as "callback hell". Googling for the phrase will find a bunch of (JavaScript based) blog posts that describe different approaches for restructuring the UI logic to make it easier to deal with.

To "properly" solve this on the framework level, we would either need language-level `async` functionality (similar to what has been introduced in `C#` and `JavaScript` in recent years) or alternatively the entire UI logic would have to be run in a thread detached from the HTTP request handling thread. I've heard of some cases where such functionality has been implemented on top of Vaadin Framework, but those have been quite complex solutions with some interesting drawbacks as well.

**Comment by ValentinTudorM** [comment]
Could be complicated, but is a target/goal for any technology:  protecting logical transactions/flows. The technology that could offer a such support is much more robust one ... if is properly used.
