### ISSUE TITLE
RadioButtonGroup cannot be reset (graphical representation)

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#9494]
Please see
https://vaadin.com/forum/#!/thread/15966627/15966626

for more information.

**Comment by enver-haase** [comment]
Tested with FW 8.0.6

**Comment by anasmi** [comment]
The same issue with Vaadin 8.1.0.alpha8

Both clear and setValue(null) remove the value from RadioButtonGroup, but visible representation stays.

**Comment by tsuoanttila** [comment]
Adding a link to a similar issue #9476 

The reason for breaking is most likely the same. Parts of the communication logic needs to be investigated to find out where this breaks and why.
