### ISSUE TITLE
Vaadin 8.0.5 – ComboBox.NewItemHandler looses items list

### ISSUE THREAD

**Issue by fgrazi** [vaadin/framework#9501]
NewItemHandler seems to lose the items list under certain circumstances. Can be
reproduced with self-contained code attached that basically reflects the example of
the tutorial).

If Confirm new planets is not checked, everything works normal (as in the
[MyUI.java.zip](https://github.com/vaadin/framework/files/1059608/MyUI.java.zip)

tutorial that works), but if it is checked, thus insertion is confirmed through
a modal dialog – that in most cases is convenient – then the list is cleared and
only the inserted planet appears.

Curious – even if the dialog is cancelled the list is cleared. It appears as if
NewItemHandler is vulnerable to modal dialogs (or focus lost?).

But actually the list is there, simply not shown. Calling markAsDirty is also
useless. My impression is that it is something related to the search 
key buffer that remains trapped when focus is lost.

**Comment by TatuLund** [comment]
This is fixed either in Vaadin 8.4 by NewItemProvider or finally in Vaadin 8.6 with some further fixes in ComboBox state handling.
