### ISSUE TITLE
Spreadsheet 2.0.0 - Error when typing percent cells

### ISSUE THREAD

**Issue by fgrazi** [vaadin/framework#9502]
I tried to enter percent cells in the spreadsheet. I typed:
  - "19" - Just fine the cell became 19.00
  - "19%" - OK again, acceptes as 19.00%
  - "19" - (no percent again): got 1900% instead of 19.99

Apparently after the first entry concluded by a percent sign all typed cells are assumes as percentage.

**Comment by Legioth** [comment]
Issue moved to [vaadin/spreadsheet #557](https://github.com/vaadin/spreadsheet/issues/557) via [**ZenHub**](https://www.zenhub.com/)
