### ISSUE TITLE
Grid: up arrow listener does not work

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#9507]
Shortcut listener on grid does not work with arrows. 

Example code - three listeners for `A`, `ARROW_UP` and `DELETE`:
````java
    addShortcutListener(new ShortcutListener("aaa", KeyCode.A, null) {
      
      @Override
      public void handleAction(Object sender, Object target) {
        System.out.println("a");
      }
    });

    addShortcutListener(new ShortcutListener("up", KeyCode.ARROW_UP, null) {
      
      @Override
      public void handleAction(Object sender, Object target) {
        System.out.println("UP");
      }
    });

    addShortcutListener(new ShortcutListener("delete", KeyCode.DELETE, null) {
      
      @Override
      public void handleAction(Object sender, Object target) {
        System.out.println("delete");
      }
    });
````

Then I focused the grid and pressed each key couple of times - the arrow was ignored. A worked, delete worked, arrow up did not worked.

Vaadin version: 8.0.6

**Comment by hesara** [comment]
The client side class Grid.CellFocusHandler.handleNavigationEvent() swallows certain keypresses that it handles itself. A custom implementation of GridEventHandler on the client side might be able to override this, but currently this cannot be done directly from server side code.

**Comment by SomMeri** [comment]
@hesara Thank you.

**Comment by TatuLund** [comment]
> A custom implementation of GridEventHandler on the client side might be able to override this

Grid FastNavigation add-on sort of does that and gives focus tracker and event to listen if you want to follow cursor key actions.

https://vaadin.com/directory/component/gridfastnavigation-add-on
