### ISSUE TITLE
Grid Multirow select Checkbox gets Invisible in Firefox

### ISSUE THREAD

**Issue by xasz** [vaadin/framework#9512]
Vaadin Version 8.0.5
Theme: Default Valo

If you have two grid and controll the content by gridselection from first to the second grid, the checkbox gets removed if you haven't set any content in it.
Only happens in Firefox Version 53.X
Not in Chrome or Internet Explorer.

`public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        final HorizontalLayout layout = new HorizontalLayout();
        
        HashMap<String, Collection<String>> contents = new HashMap<String, Collection<String>>();
		for(int i = 0 ; i < 100 ; i ++){
			ArrayList<String> strings = new ArrayList<String>();
	        for(int j = 0 ; j < 100 ; j ++){strings.add("Something Text " + j);}
	        contents.put("Category " + i, strings);
        }
		
		Grid<String> displayGrid = new Grid<String>();
		displayGrid.addColumn(source -> source).setCaption("Caption");
		displayGrid.setSelectionMode(SelectionMode.MULTI);
		
        Grid<Entry<String,Collection<String>>> chooserGrid = new Grid<Entry<String,Collection<String>>>();
        chooserGrid.addColumn(source -> source.getKey()).setCaption("Category");
        chooserGrid.setSelectionMode(SelectionMode.SINGLE);
        chooserGrid.setItems(contents.entrySet());
        
        chooserGrid.addSelectionListener(event -> {
        	Optional<Entry<String, Collection<String>>> row = event.getFirstSelectedItem();
        	if(row.isPresent()){
        		displayGrid.setItems(row.get().getValue());
        	}else{
        		displayGrid.setItems(new ArrayList<String>());
        	}
        });
        
//        Workaround - if you add this line, the problem does not appear 
//        displayGrid.setItems(new ArrayList<String>());
        
        layout.addComponent(chooserGrid);
        layout.addComponent(displayGrid);
        
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
![grafik](https://user-images.githubusercontent.com/1305196/26966261-a7f4b182-4cf9-11e7-9412-0f129c09f672.png)
`

**Comment by hesara** [comment]
Might be related to #9509

**Comment by TatuLund** [comment]
Re-tested with Vaadin 8.11 and Firefox and could not reproduce anymore, hence closed.
