### ISSUE TITLE
Make com.vaadin.data.BeanValidationBinder#bindInstanceFields extendable w/ custom Validators

### ISSUE THREAD

**Issue by OldIMP** [vaadin/framework#9516]
- Vaadin version: 8.0.6
- Description
Right now, Bindings of a BeanValidationBinder bound w/ **bindInstanceFields** cannot be extended w/ further Validators. It would be great if this is possible, e.g.
```java
binder.bindInstanceFields(this).forField(emailField).withValidator(new EmailValidator());
```
This request is similar to #8462 which focuses on the _custom binding resolution_. Here is the focus **additional custom validation**

**Comment by Legioth** [comment]
Would it be enough to do this in the opposite order: apply specific configuration using `forMemberField` before running `bindInstanceFields`.

The code for your example case does then look like this:
```
binder.forMemberField(emailField).withValidator(new EmailValidator());
binder.bindInstanceFields(this);
```

**Comment by OldIMP** [comment]
pls excuse my stupidity...
