### ISSUE TITLE
Designer css classes no more visible

### ISSUE THREAD

**Issue by fante76** [vaadin/framework#9533]
Vaadin version 8.0.6
Designer version 2.1.4

Open css style window from a component panel no more lists available css classes

Click a component, (example TextField). On properties panel click icon with 3 dots on property "StyleName". Resulting opened dialog has css list empty. Also "Select Theme" combobox is empty.

![image](https://user-images.githubusercontent.com/12963376/27134221-358cca6a-5115-11e7-973e-3fe00a5ac014.png)

**Comment by ripla** [comment]
This is a Designer issue. Moved to https://github.com/vaadin/designer-issues/issues/1458.
