### ISSUE TITLE
RadioButtonGroup/CheckBoxGroup: setting ClassResource as icon renders a broken link

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#9536]
Vaadin 8.1.0.beta1. Setting `setItemIconGenerator()` which produces `ClassResource` produces broken URLs and won't download the resource properly. Attaching screenshot.
![screenshot_20170614_220934](https://user-images.githubusercontent.com/254091/27150066-6d7303ca-514e-11e7-8c17-71c4a0e34c7a.png)

**Comment by mvysny** [comment]
The URL produced is `http://localhost:8080/APP/connector/0/56/null/document32.png` - that `null` looks suspicious.

**Comment by hesara** [comment]
The null key given in AbstractMultiSelect.MultiSelectDataGenerator might or might not be related to the problem.

In any case, I suspect this might apply to all ConnectorResource instances (ClassResource, FileResource, StreamResource) and potentially also to some other listing components - to check when addressing this.

**Comment by MartinUhlen** [comment]
Any progress on this issue?

#9041 fixed the corresponding issue for ComboBox, same thing needed here?
