### ISSUE TITLE
Documentation - The code example for ItemClickListener is invalid

### ISSUE THREAD

**Issue by pvliss** [vaadin/framework#9546]
This is minor but in the documentation for Grid the code example for section [Focus and clicks](https://vaadin.com/docs/-/part/framework/components/components-grid.html#components.grid.selection.clicks) is invalid or outdated.

It should instead read:

```
grid.addItemClickListener(event ->
    Notification.show("Value: " + event.getItem()));
```

**Comment by anasmi** [comment]
Hi, 

it looks like example has been updated accordingly! : )

Thanks for you help and contributions!
And have a nice day : )
