### ISSUE TITLE
TextField Caption should be able to render as <label for="... >

### ISSUE THREAD

**Issue by eepstein** [vaadin/framework#9548]
Vaadin 8.0.6

Building a form and setting Captions on TextFields the display looks fine, but the captions aren't clickable.

In particular, although all modern browsers support the <label for="id-of-input-element-goes-here"...> it seems Vaadin does not make use of the construct.  

Can a setting be added to the base class of form components that allows one to render Captions as HTML label elements?

**Comment by hesara** [comment]
As far as I can tell, this should be handled by AriaHelper.bindCaption() which does set the "for" attribute, "aria-labelledby" etc. and generates IDs if not explicitly set. Thus, at least for basic layouts, the "for" attribute is there.

However, some layouts might not use AriaHelper, and I believe just having the "for" attribute isn't enough to make a label clickable - perhaps also something else captures caption clicks.

**Comment by Legioth** [comment]
Focusing a field by clicking something with a corresponding `for` attribute probably only works automatically if the clicked thing is a `<label>`, whereas the captions managed by the framework are usually just using `<div>` or something equally generic.

**Comment by eepstein** [comment]
Why not make them into <label> elements by default ?   Why not use semantic HTML when possible?  And take advantage of the native browser functionality.

If it must be a <div> (home not, but I don’t know the code) then there’s still a way via JS to have it focus the corresponding element by Id.

**Comment by hesara** [comment]
How captions are managed (a VCaption handled by the layout containing the component) means this would probably not be specific to text fields.

One concern I have with changing from <div> to <label> would be the impact on themes - both the standard ones and custom themes. Thus, changing the default behavior would constitute a breaking change that cannot be introduced in a maintenance version. Perhaps a configurable option (handled in all the standard themes) could be introduced more easily, though.

**Comment by eepstein** [comment]
That’d work.  Having support for the Caption to be rendered as a <label> element, with some way to turn that on - either on a per-component basis or more broadly - would be enough.  Basically, more semantic HTML and leveraging of functionality built-in to the browser, and less Vaadin-specific ways of doing things that don’t line up too well with the standards.

**Comment by eepstein** [comment]
Sounds like this never got addressed.

**Comment by TatuLund** [comment]
@eepstein Yes and no. Although I can see that this is legit idea, at this point I see it would do more harm by breaking the established implementation.
