### ISSUE TITLE
Tree grid take too much time to be rendred in 8.1.beta2 comparing to 8.1.beta1

### ISSUE THREAD

**Issue by yakouch** [vaadin/framework#9555]
Hi,

I'm using a treegrid where I use NumberRenderer. The time spent using vaadin 8.1.beta2 to render the tree grid is 16702 ms while it take 7004 using vaadin 8.1.beta1

Regards,

**Comment by elmot** [comment]
Might be related to #9514. @tsuoanttila, can you have a look at that?

**Comment by hesara** [comment]
Both of these numbers sound very, very high. Could you provide some additional information on the size and structure of the tree, on the browser used and on whether it is actually the rendering time that is so long or how much of the time is spent on the server creating the tree and its data, and how much sending it to the client.

**Comment by yakouch** [comment]
I'm using for my test chrome 58.0.3029.110

The treegrid is displaying 35 rows (parents and child included) with 28 columns. Alomost all columns use the NumberRenderer using the method setRenderer. I'm using the method addColumn with a value data provider. Here is a screenshot of the performance analysis in Chrome

![image](https://user-images.githubusercontent.com/26090849/27330597-14e391c6-55cb-11e7-86fc-bebc16b16acd.png)

**Comment by tsuoanttila** [comment]
Related to the pull request @elmot mentioned. There's a missing safeguard in queueing the hierarchy column update multiple times.
