### ISSUE TITLE
Combobox filtered selection shows previous filtered drop-down list

### ISSUE THREAD

**Issue by peergynt** [vaadin/framework#9556]
Tried the following code with Vaadin 8.0.6 (based on the 'application' archetype):

ComboBox<String> combobox = new ComboBox<>("Pick one");
combobox.setEmptySelectionAllowed(true);
combobox.setItems("Algeria", "Germany", "Nigeria", "Norway", "Denmark", "Sweeden");

Using Chrome 58 on Windows, I open the webapp.
1. In the combobox, start typing: E R (no space). 3 countries should be left in the selection filter (Algeria, Germany, Nigeria)
2. Using the mouse, select 'Germany'
3. Click outside of the combobox, it should lose focus.
4. In the comboxbox 'main box', highlight 'Germany', delete it and press enter. This should select the empty entry.
5. Now click on the drop-down list, only the 3 previously filtered countries are shown (Algeria, Germany, Nigeria). This makes it look like there are only 3 options.

The drop-down filtered selection does not seem to be updated at the right time.
If I go back  in the combobox and type E N, it will correctly show: Denmark and Sweeden but if I cancel what I just typed (hit 'escape'), it leaves me with an empty combobox and now the drop-down list only shows Denmark and Sweeden.

**Comment by hesara** [comment]
Most likely fixed in current 8.1 betas (#9027) - please test with 8.1.0.beta2.

**Comment by peergynt** [comment]
Cannot reproduce with vaadin 8.1.0.beta2.
Closing issue. Thank you!
