### ISSUE TITLE
Vaadin 8.1.0.beta2 File Upload DND causes problem with Eclipse build

### ISSUE THREAD

**Issue by QNENet** [vaadin/framework#9559]
Using code from Vaadin sampler and the vaadin book the code fails to build as shown in attached image.
If the event lambda is empty it builds ok but any content in the lambda causes the failure.

![vaadindndfiles](https://user-images.githubusercontent.com/13142/27326814-e8264c76-55ef-11e7-815f-ddb20e000908.JPG)

**Comment by hesara** [comment]
Which Eclipse version are you using? Assuming that the code compiles with Maven or with some other compiler, this sounds like something that should be reported at https://bugs.eclipse.org/bugs/ . In the meanwhile, to get forward, I'd recommend trying to either upgrade Eclipse or simply convert one or both of the lambdas to a nested/anonymous type.

**Comment by QNENet** [comment]
Eclipse IDE for Java Developers
Version: Neon.2 Release (4.6.2)
Build id: 20161208-0600
If no other reports of problem in Vaadin environment I will try the nested /anon approach.
As my eclipse is over 6 months old I will upgrade and try again
Thx,
