### ISSUE TITLE
Apply styles to Grid columns in single line of code [Enhancement]

### ISSUE THREAD

**Issue by ThomasEll** [vaadin/framework#9565]
Often when creating Grids I find that I want to apply the same style to particular columns, and more importantly, that I want to apply the same style to a number of particular columns (for example aligning some columns in the Grid right, and leaving the rest with the default).

Currently doing this creates a lot of additional lines of code that all do essentially the same thing, with the only difference being the column that has been selected. I would like to be able to select all of these columns in one go, and then apply the same style to those that I have specified. 

For example, if you take the following lines of code:
```
grid.getColumn("maturityDate").setStyleGenerator(item -> "v-align-center");
grid.getColumn("valueDate").setStyleGenerator(item -> "v-align-center");
grid.getColumn("drawnDate").setStyleGenerator(item -> "v-align-center");
```
I would like to be able to reduce them down to something like:

`grid.getColumns("maturityDate", "valueDate", drawnDate").setStyleGenerator(item -> "v-align-center");`

**Comment by hesara** [comment]
This would imply a much larger change in creating some kind of a ColumnSet object which would provide some basic operations that apply to all of its columns, and would logically extend to more than just Grid and columns.

I'd recommend trying out the API in a subclass of Grid, and perhaps publishing an add-on to allow others to use this and to get more feedback on the API.

**Comment by Artur-** [comment]
You can do that using Java 8 streams
```
Stream.of("maturityDate", "valueDate", "drawnDate").map(grid::getColumn).forEach(col -> col.setStyleGenerator(item -> "v-align-center"));
```

**Comment by elmot** [comment]
I agree to @Artur-. I think the ticket can be closed.
