### ISSUE TITLE
Vaadin 8 compatibility packages and browsers

### ISSUE THREAD

**Issue by lorenzobenvenuti** [vaadin/framework#9571]
Hi,

we're evaluating the migration of our application from Vaadin 7 to Vaadin 8. The idea is to use the compatibility packages and then do the actual migration in a second phase; we're wondering if using this approach the supported browsers would be those declared for version 7 or version 8 (our guess it's that com.vaadin.v7.* Components correspond to Widgets from the Vaadin 7 widgetset, is it right?)

Thank you,

lorenzo

**Comment by Artur-** [comment]
This really seems like a forum question. The widgets are copied from FW7 more or less without changes. But the browser support comes from what the core of FW8 suports, e.g. IE8 will not work
