### ISSUE TITLE
TabSheet Component not accepting Tabindex

### ISSUE THREAD

**Issue by xoulz** [vaadin/framework#9574]
The TabSheet Component is not accepting a different TabIndex other then 0.
No matter what Index is set it always stays zero.

`TabSheet sheet = new TabSheet();`
`sheet.addTab(new Label("Label1"), "Tab1");`
`sheet.addTab(new Label("Label2"), "Tab2");`
`sheet.setTabIndex(1);`

![sheet](https://user-images.githubusercontent.com/3998703/27431874-4ef77c18-574e-11e7-99b7-61dafdd5e115.PNG)

**Comment by ThomasEll** [comment]
I don't think that setTabIndex is what you are actually wanting to do, based on your code snippet. 

Try setSelectedTab for selecting which tab is shown.

**Comment by xoulz** [comment]
Sorry maybe my code snippet was missleading. I dont want so select the Active Tab with setSelectedTab.

I want to set the tabIndex (the "tabindex" html attribute) of the TabSheet component which is the order amongst all Focusable Components within a Page.

**Comment by ThomasEll** [comment]
Ahhh OK, ignore me then haha

**Comment by OlliTietavainenVaadin** [comment]
TabsheetState has
```java
    /**
     * Index of the component when switching focus - not related to Tabsheet
     * tabs.
     */
    @NoLayout
    public int tabIndex;
```
, which is set by the `setTabIndex` method, but it is never read.
