### ISSUE TITLE
Vaadin 8 Designer 2.0 VerticalSplitPanel SplitPosition Error

### ISSUE THREAD

**Issue by tdrEEB** [vaadin/framework#9591]
Vaadin 8.0.6 
Eclipse Neo.3
Cant change the SplitPosition variable of the VerticalSplitPanel.
If you create any Designer-File and add a SplitPanel and try to change the variable to the value "50" , "50.0%" or "50px" you get the error:  "com/vaadin/client/WidgetUtil$CssSize".

**EDIT:** Or any other value

**Comment by tanbt** [comment]
Moved to https://github.com/vaadin/designer-issues/issues/1468.
