### ISSUE TITLE
Bad interpretation of Firefox useragent in IPhone (IOS)

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9592]
```
public class MyVaadinServlet extends VaadinServlet implements SessionInitListener {
        public void sessionInit(final SessionInitEvent event) throws ServiceException {

                WebBrowser webBrowser = new WebBrowser();
                webBrowser.updateRequestDetails(event.getRequest());

                if (webBrowser.isIOS()) {
                    System.out.println("IOS");
                }

                if (webBrowser.isFirefox()) {
                    System.out.println("Firefox");
                } else if (webBrowser.isSafari()) {
                    System.out.println("Safari");
                }

                System.out.println(String.valueOf(webBrowser.getBrowserMajorVersion()) + "." + String.valueOf(webBrowser.getBrowserMinorVersion()));
        }
}
```

When FireFox 7.5 (3349) Mobile on IPhone (IOS) is used, the output is:

```
IOS
Safari
5.0
```

The user agent is "Mozilla/5.0 (iPAd; CPU OS 11_0 like Mac OS/X)Apple WebKit/604.1.25(KHTML, like Gecko) FxiOS/7.5b3349 Mobile/15...."

Same issue on IOS 10 and on IOS 11

And the problem is Safari 5.0 is not supported by Vaadin and is very old!

**Comment by hesara** [comment]
The rendering engine used by practically all browsers on iOS is actually the Apple WebKit implementation rather than Gecko due to iOS security restrictions. See also the method isSafariOrIOS() that was added in 8.1 for this reason for the cases where you need to detect the rendering engine.

In any case, the current detection is clearly wrong - isFirefox() should return true and isSafari() should return false in this case.

**Comment by pinonpierre** [comment]
But we can see which browser is used from useragent

Some tests:
```
IPhone Safari = Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1
IPhone Firefox = Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) FxiOS/7.5b3349 Mobile/14F89 Safari/603.2.4 
```
The browser name + version is wrote: **FxiOS**/**7.5b3349**

For information on Windows:
```
Win 10 Chrome = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Win 10 Firefox = Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0
Win 10 IE = Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Win 10 Edge = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
```
The main issue for me is that Vaadin tell me that browser is Safari (webBrowser.isSafari() == true) but the version is not related with any browser. The version returned (webBrowser.getBrowserMajorVersion() == 5 & webBrowser.getBrowserMinorVersion() == 0) is not the version of Safari and is not the version of Firefox

**Comment by macjuan** [comment]
I think there is still lack of clarity how things should be. I understand that there is something bad here but what would be good?

**Comment by pinonpierre** [comment]
The best is to have something consistent between browser and browser version.
Because is an error to have:
"webBrowser.isSafari() == true" and "webBrowser.getBrowserMajorVersion() == 5 & webBrowser.getBrowserMinorVersion() == 0" at the same time.

2 solutions:
- You can return webBrowser.isFirefox() == true
- Or you can return the version of Safari

**Comment by wbadam** [comment]
I think the correct solution here is to return Firefox as the browser and its version (7.5 in the example) as browser version. Safari is in fact not the engine, AppleWebKit is.

The engine and its version can be found with `VBrowserDetails#isWebkit()` and `VBrowserDetails#getBrowserEngineVersion()`. Also `isSafariOrIOS()` that Henri mentioned can be of help when detecting the browser.
