### ISSUE TITLE
Outline empty on first load

### ISSUE THREAD

**Issue by fante76** [vaadin/framework#9598]
Vaadin 8.0.6
Vaadin Plug-in for eclipse 4.0.0.final
Vaadin Designer 2.1.4

Opening a designer HTML file with Vaadin Perspective active for the very first time after Eclipse started doesn't loads the outline view content.
Closing and reopening the same designer correctly load the outline.

![image](https://user-images.githubusercontent.com/12963376/27624562-8fac31bc-5be1-11e7-956c-9c7b4187703d.png)

**Comment by qtdzz** [comment]
@fante76 I guess it could be related to this issue https://github.com/vaadin/designer-issues/issues/1454

**Comment by fante76** [comment]
Yes, in fact I recently installed SonarLint, Thankyou.
