### ISSUE TITLE
When enabling DnD in my App and trying to verify whether the drop is acceptable, I want to easily give data to the drag sources that can be verified as easily in the drop targets, so that I can build my app more easily and not write JS in server side

### ISSUE THREAD

**Issue by wbadam** [vaadin/framework#9600]
Add method for `DragSourceExtension` to set key-value pairs to be checked when dragging. The pairs are transferred as data type as the types are available on both `dragenter` and `drop` events. Examples:
- `dragSource.setPayload("key", "value")` would transform to a data transfer item of type `"V-ITEM:STRING:KEY:VALUE"`
- `dragSource.setPayload("mykey", 123)` would transform to item of type `"V-ITEM:INTEGER:MYKEY:123"`

Add convenience API alongside with criteria script that takes _key_, _value_ and, for numeric type, _operator_ (`<`,`>`,`==`,`<=`,`>=`). Example:
- `dropTarget.setCriteria("key", "value")`
- `dropTarget.setCriteria("mykey", 123, "==")`

Both criteria script and this test should pass to allow drop on a certain target.

**Comment by Legioth** [comment]
I'd suggest defining the operator as an enum instead of using magic strings.

**Comment by wbadam** [comment]
Yes, that's the plan, it wasn't clear in description, sorry.
