### ISSUE TITLE
IOS IPhone / IPad: Click failed when Button has ToolTip

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9602]
On IOS (IPhone or IPad), when a description is set on a Button, the first click doesn't work and only show the tooltip and the second performed a real click.

You can reproduce that from the Vaadin Sampler. You just need to set a description on a Button and to tried to click on it just one time

**Comment by BrianSiimAndersenEG** [comment]
This is still an issue in 8.3.3. As soon as the button has a description, clicking the button the first time just shows the description, and does not click the button. The user has to click it again. This is misleading for the user - especially if the ValoTheme.BUTTON_LINK style is applied, and the button just appears to be a link. The user expects the first click to click the button, and do not expect to click it again.

**Comment by TatuLund** [comment]
Another workaround would be Page.getWebBrowser() and check if the user using iOS, not to add tooltips to buttons in the first place.
