### ISSUE TITLE
Grid: nested proprty can cause IllegalArgumentException

### ISSUE THREAD

**Issue by tistvan** [vaadin/framework#9609]
- Vaadin version: 8.1.0.beta3
- Description of the bug: If I have two classes with a same member field and one of these classes references to the other and I add the same member field as nested field to the Grid it throws this exception:
```
Caused by: java.lang.IllegalArgumentException: Duplicate ID for columns
	at com.vaadin.ui.Grid.setColumnId(Grid.java:4176)
	at com.vaadin.ui.Grid$Column.setId(Grid.java:1119)
	at com.vaadin.ui.Grid.addColumn(Grid.java:2473)
	at com.vaadin.ui.Grid.addColumn(Grid.java:2430)
```

- If possible, minimal reproducible example:
It's easier to explain the bug with the following code:

```java
   public static class A {
        private String name;
        private B b;

        //getters, setters
    }

    public static class B {
        private String name;

        //getters, setters
    }

...

    Grid<A> grid = new Grid<>(A.class);
    grid.addColumn("b.name"); //this line will throw the exception
    return grid;

```

Grid.addColumn("b.name") call sets the column id using the propertyDefinition instead of the given property name. The name from the property definition is "name" which is already exists in the grid.

Thanks,
István

**Comment by tistvan** [comment]
A similar problem exist in the (PropertySet, DataCommunicator) constructor but it is harder to reproduce that.
The constructor has the following lines:
```java
        // Automatically add columns for all available properties
        propertySet.getProperties().map(PropertyDefinition::getName)
                .forEach(this::addColumn);
```
The propertySet parameter is passed to this constructor using the BeanPropertySet.get(beanType) call which can produce nested properties sometimes. (I think the reason is that BeanPropertySet instances are cached and BeanPropertySet.getProperty() can add (nested) properties to it's underlying definition map.)

So I don't know exactly how but the bug can appear without the grid.addColumn("b.name"); line.

**Comment by mkyc** [comment]
@tistvan do you have workaround for first type (a.name b.name) of issue?

**Comment by tistvan** [comment]
@mkyc The workaround was calling the Grid's constructor without parameters and avoid adding columns as propertyId strings. I mean I added a column which calls my own reflection utility to get the value from the item.
```java
Grid<A> grid = new Grid<>();
Column column = grid.addColumn( item -> ReflectionUtils.getFieldValue(item, "b.name") );
column.setId("b.name"); //Optional. Can be useful if you massively use grid.getColumn()
return grid;
```

**Comment by TatuLund** [comment]
This was fixed by PR: https://github.com/vaadin/framework/pull/9925
