### ISSUE TITLE
Grid content selection changed listener

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9610]
On 8.1.0.beta3,

Goal:
I want to get all grid selected items and be notified each time the objects of selection has changed.

For information, DataProvider.getId(T item) is defined

The problem is:
I can be notified when the selection has changed by Grid SelectionListener.selectionChange but it's not possible to be notified when the selection has not changed (Same Id) and when the content of selection (other fields of objects) has changed.

I also tried to use a DataProviderListener.onDataChange but when it is emitted, the selection is not yet changed.

How can I do?

**Comment by elmot** [comment]
Are you looking for `DataProvider.refreshItem()`?

**Comment by pinonpierre** [comment]
No, I don't know the id of changed objects. I just said that I overrided the getId(T item) method of DataProvider

It's not a solution for me because I don't know which items are changed. I just call refreshAll() method and I wan't to know when content of selection has changed!

**Comment by tsuoanttila** [comment]
When ever you call `getSelectedItems` you get the items that were most recently sent to the client, unless given an updated item with `DataProvider.refreshItem`. Can you explain the need for having even more up-to-date data?

**Comment by pinonpierre** [comment]
Hi!

An example:

```
List<MyObject> myObjects = Arrays.asList(new MyObject(1, "one"), new MyObject(2, "two"), new MyObject(3, "three"));

DataProvider<MyObject, Void> dataProvider = new AbstractBackEndDataProvider<MyObject, Void>() {

    @Override
    protected Stream<MyObject> fetchFromBackEnd(Query<MyObject, Void> query) {
        System.out.println("Fetch Data...");
        return myObjects.stream();
    }

    @Override
    protected int sizeInBackEnd(Query<MyObject, Void> query) {
        System.out.println("Count Data...");
        return myObjects.size();
    }

    @Override
    public Object getId(T item) {
        return item.getId();
    }
};
dataProvider.addDataProviderListener(event1 -> System.out.println("Inside DataProviderListener"));

Grid<MyObject> grid = new Grid<>();
grid.setDataProvider(dataProvider);

mainLayout.addComponent(grid);

Button button = new Button("Ok");
button.addClickListener(event1 -> {
    System.out.println("Button Click. Call refreshAll");
    dataProvider.refreshAll();
});
mainLayout.addComponent(button);
```
When you click on the button, the console output is:

```
Button Click.
Call refreshAll
Inside DataProviderListener
Count Data...
Fetch Data...
```
You can see with this example that when a refreshAll is called, DataProviderListener is fire before any DataProvider Count or Fetch.

And the goal in my project is to show in a panel near grid the detail of the current selection.

When I call refreshAll, I need to refresh the panel too with the selected items. But I have now way to know when the object of selection is updated.

I can knows when the selection change (Items with different ids of current) but not when the items change itemself (because I implemented the DataProvider.getId(T item) method in my DataProvider and sometimes, some item fields change for a specific item id)

**Comment by tsuoanttila** [comment]
The first valid approach that comes to mind is to add a method to your specific data provider implementation to find a single item based on its id, and actually ask the most recent ones from the backend yourself. (or for more optimised approach, accept a list of ids and return the current objects). Selection actually does not really know anything about the contents of the objects, it just keeps track of the most recent ones it has seen for the users convenience.
