### ISSUE TITLE
Vaadin help

### ISSUE THREAD

**Issue by VadimLi** [vaadin/framework#9611]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

For bugs, please provide at minimum the following information:
- Vaadin version
- Description of the bug
- If possible, minimal reproducible example

**Comment by hesara** [comment]
Closing this as there is no information about a problem. Please use https://vaadin.com/forum or a support subscription for questions, and GitHub issues for bug reports and feature requests.
