### ISSUE TITLE
When creating my own HasValue implementation that wraps a field component, I want to use something similar to CustomField, so that I don't have to write lots of boilerplate.

### ISSUE THREAD

**Issue by Legioth** [vaadin/framework#9613]
The need for this can be seen e.g. in https://github.com/vaadin/framework/blob/e4e2328a3a78d652cd09ef8293f233d31d899415/uitest/src/main/java/com/vaadin/tests/components/grid/GridColumnPresentation.java#L24

**Comment by elmot** [comment]
Isn't it something similar to https://github.com/elmot/tipsandtricksbinder/blob/master/src/main/java/org/vaadin/tipsandtricks/binder/ReadonlyHasValue.java
and 
https://github.com/elmot/tipsandtricksbinder/blob/master/src/main/java/org/vaadin/tipsandtricks/TipsAndTricksUI.java#L53
?
