### ISSUE TITLE
Tree/TreeGrid 8.1 beta3 - not possible to delete visible and selected item. "could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?"

### ISSUE THREAD

**Issue by FoxyBOA** [vaadin/framework#9614]
Attempts to delete selected item from Tree/TreeGrid leads to "could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?" exception. 

Didn't find a workaround (yet), but the working code to hunt the bug is below. Push the button and check the exception
```
       TreeData<String> treeData = new TreeData<>();
       treeData.addItem(null, "A");
       treeData.addItem("A", "B");
       Tree<String> tree = new Tree<>(new TreeDataProvider<>(treeData));
       l.addComponent(tree);
       tree.expand("A");
       tree.select("B");
//       ((SingleSelectionModel)tree.getSelectionModel()).setDeselectAllowed(true);
       
       Button br = new Button("XXX", ev -> {
//    	   tree.getSelectionModel().deselect("B");
//    	   tree.deselect("B");
    	   tree.getTreeData().removeItem("B");
    	   tree.getDataProvider().refreshAll();
    	   tree.select("A");
       });
       l.addComponent(br);
```

> java.lang.IllegalArgumentException: Item B could not be found in the backing TreeData. Did you forget to refresh this data provider after item removal?
> 	at com.vaadin.data.provider.TreeDataProvider.hasChildren(TreeDataProvider.java:75)
> 	at com.vaadin.data.provider.HierarchyMapper.generateData(HierarchyMapper.java:177)
> 	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:449)
> 	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:349)
> 	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:311)
> 	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126)
> 	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
> 	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
> 	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
> 	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
> 	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
> 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:524)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
> 	at java.lang.Thread.run(Thread.java:745)
> 
>

**Comment by pinonpierre** [comment]
Same issue

**Comment by VadimLi** [comment]
I'm sorry, but may to use class TreeTable. And there is method "removeItem" in the class.

**Comment by FoxyBOA** [comment]
@VadimLi It's V7 API, would like to use 8.1 new Grid, TreeGrid and Tree

**Comment by VadimLi** [comment]
Then the Tree component is currently being developed and only available in the Framework 8.1 prerelease versions, starting from 8.1.0.beta1.  https://vaadin.com/docs/-/part/framework/components/components-tree.html#components.tree

**Comment by pinonpierre** [comment]
For my part, I don't have the choice. I migrated to 8.1.0.beta3 because there are too much bugs about Grid in 8.0.6 and there are too much work for a rollback to 7.

I need to Migrate my old Tree (7) to the new Tree (8.1) and I don't want to have TreeTable but only a simple Tree...

**Comment by FoxyBOA** [comment]
@VadimLi I understand the status of 8.1/TreeGrid/Tree and my point is to provide early feedback to the vendor.

Vadim, if you're a member of Vaadin team and it's official position of your company (i.e. "don't spam us issues till GA") put this statement as clearly as possible (on the company website, github repo etc.).
If you're a well-wisher who would like to help a stranger achieve the result (in my case remove selected node from a tree), thank you, I really appreciate it but I pursue another goal (see above).

И без обид :)
