### ISSUE TITLE
Vaadin 8.1 Tree horizontal scrollbars missing

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#9628]
Vaadin 8.1 Tree horizontal scrollbars are missing when there are wide children captions that the user just expanded or when re-opening a Tree (e.g. in TabSheet).

E.g. here missing horizontal scrollbars:
![screenshot from 2017-07-03 14-22-15](https://user-images.githubusercontent.com/886091/27792725-67a7ae8a-5ffb-11e7-9753-0b15cf53f590.png)

Online demo (takes a minute or two to boot up as it upgrades to latest snapshot on opening):
https://vaadinfiddle.com/editor/#!container/a5878bda19a3b90e20947fcfc09c8e3608ad93b23d77ab3fc2d9d897f3ed5808/src/main/java/org/vaadin/vaadinfiddle/MyUI.java

Demo project
[treegridheight.zip](https://github.com/vaadin/framework/files/1119474/treegridheight.zip)

Tested using Vaadin 8.1 SNAPSHOT vaadin-server-8.1-20170703.100423-235 & chromium browser on Linux

**Comment by pinonpierre** [comment]
For my part, I need to add "overflow: auto" on the parent tree ".v-slot" to have scrollbars

**Comment by elmot** [comment]
Partial workaround: you might put the Tree inside a Panel. 
Does not work perfectly but at least the scrollbar is shown.

**Comment by tsuoanttila** [comment]
The Tree component is a simplified version of the TreeGrid and is restricted in its customisability on purpose. If you want to have more configuration options, you should use TreeGrid. To make it look like the Tree, call `treeGrid.setPrimaryStyleName("v-tree8")`. Adding a single column to the TreeGrid and not setting any size on it at all makes it take the space it needs to display the full content.

With Pull Request #9756 you can do horizontal scrolling when needed by doing:
```
treeGrid.addExpandListener(e -> treeGrid.recalculateColumnWidths());
treeGrid.addCollapseListener(e -> treeGrid.recalculateColumnWidths());
```

If you think that the Tree component would still need more configuration on the Tree, I'd like to hear what kind of APIs you'd want for it and what they should do.

**Comment by pinonpierre** [comment]
But when I apply the primary stylename "v-tree8", I have style issues like:
- The vertical scrollbar still have the style of grid
- I cannot remove the header row

![image](https://user-images.githubusercontent.com/4507910/28783309-42a6382e-7610-11e7-9335-aa195ad94476.png)

I think that the tree component does automatically adapt its width

**Comment by tsuoanttila** [comment]
Header can be removed with `treeGrid.removeHeaderRow(0)`. Integrating it directly without adding a configuring API is changing the behaviour from the release. We need at least a boolean flag for it, to allow enabling/disabling automatic recalculation. The styling for scrollbars was not done when making the theme for the Tree because of the old Tree limitation of not using scrollbars, but always showing the full content. That part of the theme will need a fix anyway.

**Comment by pinonpierre** [comment]
It works like a charm now, thanks!
Any news about the bad theming of scroll bars? Is there an other issue?

Thanks!
