### ISSUE TITLE
Vaadin 8.1 unable to set height for the Tree component

### ISSUE THREAD

**Issue by Wnt** [vaadin/framework#9629]
Tree's setHeight methods have JavaDoc "This component's height is always set to be undefined. Calling this method will have no effect."

This makes it impossible for the developer to define where Tree's scrollbars are rendered to.

e.g. here I'd like to have the scrollbars on the bottom of the UI regardless of how many items I have in the Tree
![screenshot from 2017-07-03 14-22-02](https://user-images.githubusercontent.com/886091/27792654-145379ee-5ffb-11e7-8f8d-a0f75c169c03.png)

Online demo (takes a minute or two to boot up as it upgrades to latest snapshot on opening):
https://vaadinfiddle.com/editor/#!container/a5878bda19a3b90e20947fcfc09c8e3608ad93b23d77ab3fc2d9d897f3ed5808/src/main/java/org/vaadin/vaadinfiddle/MyUI.java

Demo project:
[treegridheight.zip](https://github.com/vaadin/framework/files/1119470/treegridheight.zip)

Tested using Vaadin 8.1 SNAPSHOT vaadin-server-8.1-20170703.100423-235 & chromium browser on Linux

**Comment by Wnt** [comment]
As a workaround one can extend Tree to override the non-working setHeight methods:
```
public class MyTree<T> extends Tree<T> {
	@Override
	public void setHeight(float height, Unit unit) {
		getCompositionRoot().setHeight(height, unit);
	}
	@Override
	public void setHeight(String height) {
		getCompositionRoot().setHeight(height);
	}
	@Override
	public void setHeightUndefined() {
		getCompositionRoot().setHeightUndefined();
	}
}
```

**Comment by pinonpierre** [comment]
Thanks for the workaround
