### ISSUE TITLE
Some sort of global StringToIntegerConverter for Vaadin 8

### ISSUE THREAD

**Issue by anthavio** [vaadin/framework#9632]
Vaadin 7 ConverterFactory and session.setConverterFactory() has been deprecated without replacement so now all numbers over 1000 in countless places in application are displayed with comma. So I can have to painstakingly visit every single UI element showing number and add manually set custom Converter in every one and leave precisely 0 that needs to show numbers with commas or whatever weird format is locale returning. 
Or maybe the could be some global switch for it, which would be very very nice as upgrading vaadin 7 to 8 brings tons of other issues and making it quite painful experience.

**Comment by hesara** [comment]
For the parts of the application where you use the V7 compatibility packages, you can still keep using the old approach. For the new parts and parts migrated to new mechanisms, perhaps using a custom subclass of Binder with some methods overridden or some new helpers would allow adding your default conversions etc. in a single place.

**Comment by anthavio** [comment]
Thank you and sorry for my bitterness
