### ISSUE TITLE
EventListeners are not removed from State

### ISSUE THREAD

**Issue by elmot** [vaadin/framework#9634]
It's done in `ComponentStateUtil.removeRegisteredEventListener()` but most of `Registration.remove()` and `removeListener(???)` methods do not do that. That means the listeners are not unregistered properly at client-side, and, thus, sometimes events (ex. context click events) stay not bubbled even if all the listeners for the event type was removed.

**Comment by bjung82** [comment]
This also happens for e.g. the CSS-Layout. ClickListeners that are removed via Registration.Remove are only removed from Server-Side but not from ClientSide. This causes problems like unnecessary roundtrips.

For CSS-Layout we fixed it like this:

public class FixedCSSLayout extends CssLayout {

	@SuppressWarnings("deprecation")
	@Override
    protected Registration addListener(String eventIdentifier,
            Class<?> eventType, Object target, Method method) {
		Registration eventRouterReg = super.addListener(eventIdentifier, eventType, target, method);
		//this is a vaadin bug... addRegisteredEventListener called in superclass, but corresponding
		//remove not called.
		//--> currently unclear if eventIdentifier and eventType are always distinct pairs, so unclear if
		//the following is a general solution for superclass - at least here this is fine, since only the
		//click listener is used by our code.
		return () -> {
			eventRouterReg.remove();
			if (getListeners(eventType).isEmpty()) {
				ComponentStateUtil.removeRegisteredEventListener(getState(),
	                    eventIdentifier);
			}
		};
	}	
	
	
}

**Comment by asashour** [comment]
I see that `removeListener()s` actually call `AbstractClientConnector`.`removeListener(String, Class, Object`, which calls the `ComponentStateUtil.removeRegisteredEventListener` when needed.
