### ISSUE TITLE
Vaadin 8.1.0.rc1 Tree ScrollBar doesn't work correctly and appareance is not correct

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9644]
On Vaadin 8.1.0.rc1

I have a tree with only 3 items.
When I expand items, scroll bar should appear (Vertically and Horizontally) to allow to scroll but nothing happen.

**Comment by elmot** [comment]
Related to #9503, #9629

**Comment by wbadam** [comment]
Duplicate of #9628? I think it's fixed now.

**Comment by pinonpierre** [comment]
The scrollBars works but the style of scrollbars is bad

![image](https://user-images.githubusercontent.com/4507910/28783309-42a6382e-7610-11e7-9335-aa195ad94476.png)
