### ISSUE TITLE
Vaadin 8.1.0.rc1 Tree.addItemClickListener doesn't work for the right click

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9645]
On Vaadin 8.1.0.rc1, the Tree.addItemClickListener doesn't work for the right click

**Comment by elmot** [comment]
This should be doable after fixing #9606 via `Tree.addContextClickListener`

**Comment by elmot** [comment]
Please use `Tree.addContextClickListener()`

**Comment by pinonpierre** [comment]
But how can I do to know the item clicked ?

**Comment by elmot** [comment]
There is an example in javadoc
https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Tree.java#L870

**Comment by Barnabet16** [comment]
Hello, I have the same problem.
But TreeContextClickEvent does not exist in Tree class.
And when I do "right click", a menu of the explorator appears...and there is no other action.

**Comment by elmot** [comment]
It's not released yet, will be in the next release. You can use 8.1-SNAPSHOT version to try it right now.

**Comment by Barnabet16** [comment]
Ok, thanks
