### ISSUE TITLE
Vaadin 8.1.0.r1 : Tree ContextClickListener is never fired

### ISSUE THREAD

**Issue by anasmi** [vaadin/framework#9647]
Trying to apply ContextClickListener on Tree has no effect, but it works with general grid as it should:

Example to reproduce:
 '
        
        Tree<String> tree = new Tree<>("Hardware Inventory");

        TreeData<String> data = new TreeData<>();
        data.addItems(null, "Desktops", "Laptops")
                .addItems("Desktops", "Dell GX240", "Dell GX260", "Dell GX280")
                .addItems("Laptops", "IBM T40", "IBM T43", "IBM T60");

        tree.setDataProvider(new TreeDataProvider<>(data));
        tree.expand("Desktops", "Laptops");
        tree.setItemIconGenerator(item -> {
            if (item.equals("Desktops")) {
                return VaadinIcons.DESKTOP;
            } else if (item.equals("Laptops")) {
                return VaadinIcons.LAPTOP;
            }
            return null;
        });
        tree.addContextClickListener(event -> {
            System.out.println("TREE CONTEXT LISTENER") ; // never printed
        });
`

**Comment by elmot** [comment]
Duplicate to #9606
