### ISSUE TITLE
Clicking a component inside a grid cell does not set focus on cell

### ISSUE THREAD

**Issue by neerup** [vaadin/framework#9649]
Hi
When the new component columns is used with Grid, focus does not follow the mouse when clicking on a component inside a grid cell.
Because of Issue #7833 it is necessary to add a LayoutClickListener to the components to have them select the row clicked on, but that does not move the focus to the clicked cell.
This is confusing for the users when focus does not follow the mouse clicks.

Vaadin 8.1.rc1

**Comment by jetdario** [comment]
I have the same problem.. have you found a solution?

**Comment by TatuLund** [comment]
The focus works when using Vaadin 8.3+ and Column.setHandleWidgetEvents(true);, if you base your custom component in ComponentColumn on e.g. Panel, which is focusable. Non-focusable component will naturally repell the focus.
