### ISSUE TITLE
Vaadin 8.1.0.rc1 Push Issue!

### ISSUE THREAD

**Issue by pinonpierre** [vaadin/framework#9654]
Hi,

A big issue for us.

Push issue doesn't work properly since 8.1.0.rc1 (It works on Vaadin 8.0.6)

Prerequires: PushMode.MANUAL

Example:
 ```
        VerticalLayout mainLayout = new VerticalLayout();
        setContent(mainLayout);

        Label label = new Label("Please wait");
        label.setVisible(false);
        mainLayout.addComponent(label);
        
        Button button = new Button("Hide me 3 secondes");
        button.addClickListener(event1 -> {
            button.setVisible(false);
            label.setVisible(true);

            new Thread(() -> {
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                button.getUI().access(() -> {
                    button.setVisible(true);
                    label.setVisible(false);
                    button.getUI().push();
                });
            }).start();
        });
        mainLayout.addComponent(button);
```

If you tried to click on the button several times, the label will disappear permanently but is present partially in the Web Browser DOM.

I also reproduced this in the fiddle but since 5 minutes the fiddle seem to have another issue about widgetsets: https://vaadinfiddle.com/editor/#!container/ed68093b4f17434a03fec8723dd72923ff6412d5f6a83b51f06707e3069ebf40

Can you take a look, please?

**Comment by wbadam** [comment]
I can confirm, reproduced with the given code on 8.1.0.rc1 (and 8.1.0.beta3) but cannot reproduce on 8.0.6.

As a clarification, the issue is that the server isn't pushing the `Label` component's text in the `"state"` JSON object on any subsequent pushes. First push works as expected. Using RPC works as expected.

First click:
```
Tue Jul 11 10:19:17 GMT+200 2017 com.vaadin.client.communication.AtmospherePushConnection
INFO: Received push (websocket) message: for(;;);[{"syncId": 2, "clientId": 2, "changes" : [], "state":{"1":{"childData":{"2":{"alignmentBitmask":5,"expandRatio":0},"4":{"alignmentBitmask":5,"expandRatio":0}}},"2":{"text":"Please wait"}}, "types":{"1":"2","2":"11"}, "hierarchy":{"1":["2","4"]}, "rpc" : [], "meta" : {}, "resources" : {}, "typeMappings" : { "com.vaadin.ui.Label" : 11 }, "typeInheritanceMap" : { "3" : 8 , "2" : 3 , "4" : 6 , "8" : 9 , "9" : 4 , "11" : 4 }, "timings":[263, 5]}]
```
Second click:
```
Tue Jul 11 10:19:54 GMT+200 2017 com.vaadin.client.communication.AtmospherePushConnection
INFO: Received push (websocket) message: for(;;);[{"syncId": 4, "clientId": 3, "changes" : [], "state":{"1":{"childData":{"2":{"alignmentBitmask":5,"expandRatio":0},"4":{"alignmentBitmask":5,"expandRatio":0}}}}, "types":{"1":"2","2":"11"}, "hierarchy":{"1":["2","4"],"2":[]}, "rpc" : [], "meta" : {}, "resources" : {}, "timings":[273, 10]}]
```

**Comment by tsuoanttila** [comment]
After some testing, it seems that the issue only exists in push with websockets. By changing transport from websocket to long-polling, I couldn't replicate the issue anymore. So for now as a workaround, you can use long-polling. We need to investigate further why it does not work with the websocket.

**Comment by Artur-** [comment]
Seems to be caused by #9305, and this issue is the same as #9693 for 7.7
