### ISSUE TITLE
Row selection in Grid in MultiSelect mode

### ISSUE THREAD

**Issue by zanonmark** [vaadin/framework#9657]
Is it possible to change the default behaviour so that a Grid in MultiSelect mode can still highlight the whole row if a single cell is clicked, line in SingleSelect mode?

Thanks,
Marco

**Comment by tsuoanttila** [comment]
You can customise the client-side event handling by making an extension for it. Or you can grab my add-on (GridExtensionPack) which contains a custom version of selection model that has the selection modes of old table component.

**Comment by zanonmark** [comment]
Sorry for my late reply, I'll have a look at your add-on.

Thanks,
MZ
