### ISSUE TITLE
Storing empty value for Label not possible via Properties editor

### ISSUE THREAD

**Issue by pahaloom** [vaadin/framework#9669]
There seems to be an issue with empty value entering at least for Label when using eclipse Vaadin Designer.

1. Create a Label and enter some value into its Properties,
2. Store design.
3. Re-open the design and using Properties editor clear the value and press enter.
4. Store design again and close it.
5. Open the design again and expect Value of the label now to be empty. Instead, whatever old value was preset at file opening time is used.

For example it is possible to switch into Source mode while the Property editor still has the label visible. From there it can be seen that when entering whatever value except empty string, the value gets updated into the source code.
When trying to clear the value by deleting it and and pressing enter, the value which was read by file opening time gets written instead. However into Properties editor of eclipse still misleadingly empty value gets displayed.
As a workaround in order to have empty valued stored, need to switch to Source mode and delete value manually.

**Comment by szolo** [comment]
See https://github.com/vaadin/designer-issues/issues/1477 in designer-issues repository. @elmot not a Framework issue, please close.

**Comment by elmot** [comment]
Thanks.
