### ISSUE TITLE
Invalid character encoding in PushHandler

### ISSUE THREAD

**Issue by Romanzek** [vaadin/framework#9679]
Vaadin 7.7.10

The com.vaadin.server.communication.PushHandler#sendNotificationAndDisconnect method used in com.vaadin.server.communication.PushHandler#sendRefreshAndDisconnect. But reponse uses default character encoding instead of UTF-8. For example com.vaadin.server.VaadinService#writeStringResponse changes the writer encoding to UTF-8 explicitly.
This problem leads to wrong user notification (invalid message encoding).

**Comment by zipper2110** [comment]
Really guys, it's important. I recently switched from polling to Push, and got the same bug - now all error messages (like "session expired" or "internal error") are displayed as a sequence of question marks.
