### ISSUE TITLE
Unnecessary dependency "GWT-User" since Vaadin8 - compatibility package

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9684]
- Vaadin version: 8.1.0.rc1

Since Version 8 with compatibility package of Vaadin there is an enormous increase of the ui project and so the war file size. Is gwt-user really necessary? In Version 7 there was no need for this dependency.

Vaadin 8.1.0.rc1:
![image](https://user-images.githubusercontent.com/10894484/28266586-f247a07c-6af5-11e7-84b0-07c9f6e7a633.png)

Vaadin 7.7.7
![image](https://user-images.githubusercontent.com/10894484/28266603-0cb8a9ec-6af6-11e7-87a0-b6abcd4c707b.png)

Comparison:
![image](https://user-images.githubusercontent.com/10894484/28266677-739d9780-6af6-11e7-8ff2-9aba95632ea9.png)

**Comment by hesara** [comment]
The gwt-user JAR is needed by vaadin-client and vaadin-compatibility-client, but none of those JARs is needed in the WAR. Please check your POM and use the Maven scope "provided" for the client JARs and only include vaadin-compatibility-client-compiled JAR in the WAR (if not using your own custom widgetset). In some cases with some custom widgets, a much smaller gwt-server JAR might be needed in the WAR.
