### ISSUE TITLE
Vaadin 8.1.0 rc1 - Grid HeaderRow setText() after join does not update caption

### ISSUE THREAD

**Issue by ironbark** [vaadin/framework#9686]
Hi,

1/ I have a grid and join two columns - and want to assign a new caption - just like the grid documentation example - but I don't create a new row - just use the default one.
The following code worked fine in 7.7.x 

HeaderRow def = grid.getDefaultHeaderRow();
Grid.HeaderCell c1 = def.getCell("col1 name");
Grid.HeaderCell c2 = def.getCell("col2 name");
def.join(c1,c2).setText("joined name here");

2/ Under 8.1.0 rc1, I do something very similar.

HeaderRow def = grid.getDefaultHeaderRow();
HeaderCell c1 = rr.getCell("col1 name");
HeaderCell c2 = rr.getCell("col2 name");
def.join(c1,c2).setText("joined name here");

What happens now is the column keeps the name of the second column ("col2 name") - it
does not have the new "joined name here" label applied.

(If I add the line c2.setCaption("ABC"); above the last/join line, then the ABC label is displayed. Looks like the join sets the label to the caption of the last column and the setText then does nothing. Adding and removing the setText() line does not change the caption.)

Thanks

**Comment by tsuoanttila** [comment]
After a quick investigation, it seems that this is broken only when the header is merged in init. That's why it has escaped our test, since in the test it's set in an already running grid. I have a patch for this.
