### ISSUE TITLE
Setting visibility of a component through access in UI not working properly anymore in 7.7.10

### ISSUE THREAD

**Issue by ChrSchmidt18057** [vaadin/framework#9693]
When in 7.7.10 the visibility of a component is switched using access in UI, the visibility of the component is not restored properly. The following example code shows the expected behavior in 7.7.9 and the unexpected behavior in 7.7.10. Maybe related to #9331?

```
import java.awt.Button;
import java.awt.Label;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.Title;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@Theme(ValoTheme.THEME_NAME)
@Push(value = PushMode.AUTOMATIC)
@Title("Demo")
public class DemoApplication extends UI {

	private static final long serialVersionUID = -4052123275953485731L;

	@Override
	protected void init(final VaadinRequest request) {
		final Button start = new Button("start");

		final Label label = new Label("test switching visibility on and off");
		label.setVisible(false);

		final VerticalLayout layout = new VerticalLayout(start, label);
		layout.setSizeFull();
		layout.setSpacing(true);
		layout.setMargin(false);
		setContent(layout);

		start.addClickListener(e -> {
			start.setEnabled(false);
			new Thread(new Runnable() {

				@Override
				public void run() {
					while (true) {
						access(new Runnable() {

							@Override
							public void run() {
								label.setVisible(!label.isVisible());
							}
						});
						try {
							Thread.sleep(1000);
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
					}
				}
			}).start();
		});
	}
}
```

**Comment by iiton** [comment]
I discovered similar issue, content in Panel started showing up randomly when the update is initiated from server side.

ChrSchmidt18057, you are correct and this issue seems to be related to the #9693.
With Vaadin 7.7.10 + 4 classes from 7.7.9 your issue will disappear.

com.vaadin.server.VaadinService
com.vaadin.server.VaadinSession
com.vaadin.server.communication.UidlWriter
com.vaadin.ui.ConnectorTracker

Current solution for me is the 7.7.9

**Comment by Artur-** [comment]
Fix for 8.1 in #9707, needs to be backported to 7.7

**Comment by bednar** [comment]
Hi @Artur-, Is there any schedule for the release [7.7.11](https://github.com/vaadin/framework/milestone/308)?

**Comment by OlliTietavainenVaadin** [comment]
If all goes well, 7.7.11 will be released tomorrow.

**Comment by bednar** [comment]
Thx @OlliTietavainenVaadin
