### ISSUE TITLE
8.1.0rc1 regression: Grid default header row does not accept components

### ISSUE THREAD

**Issue by pwilkin** [vaadin/framework#9694]
If you attempt to insert a component into the default Grid header row, it does not get rendered.

This worked fine in 8.0.6.

Reproducible example:

```        Grid<GridRowBean> grid = new Grid<>();
        grid.setItems(new GridRowBean("bla", 1.0), new GridRowBean("foo", 2.0));
        Column<GridRowBean, String> col1 = grid.addColumn(GridRowBean::getFirst);
        col1.setId("col1");
        col1.setCaption("BOOBOO");
        Column<GridRowBean, Double> col2 = grid.addColumn(GridRowBean::getSecond);
        col2.setId("col2");
        col2.setCaption("BLABLA");
        grid.getDefaultHeaderRow().getCell("col1").setComponent(new Button("TEST"));
        grs.addComponent(grid);

**Comment by pwilkin** [comment]
Generally, adding components into header rows works - if you remove the default header row and insert a new one, you can insert components. Just the default header row is "immune".

**Comment by tsuoanttila** [comment]
The root cause is the same as #9686 and according to my test, the same fix applies. Added a test for this issue to make sure it won't resurface.
