### ISSUE TITLE
ApplicationConnection's flushActiveConnector should consider elements in Overlays as well

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/framework#9697]
In Vaadin 8.0.6 the ApplicationConnection tries to find the active connector inside the UIConnector when that one should be "flushed". Unfortunately searching inside the UIConnector is not enough because the user might edited a text field inside an overlay which then won't be flushed.

**Comment by Artur-** [comment]
This was fixed in 3d6a25c2f17311126e96c8f68c6741412ca318a9

**Comment by attilapuskas** [comment]
Great, thanks!
