### ISSUE TITLE
Vaadin OSGi development environment

### ISSUE THREAD

**Issue by QNENet** [vaadin/framework#9699]
It would appear that the Vaadin OSGi developments have been conducted using Karaf as the runtime framework.
This limits the audience in the OSGi world to a small subset of users.
Being able to use Vaadin in the Bndtools environment would be a significant advantage.
This may already be possible, if so, some guidance in the form of demo or video is required.

**Comment by florianpirchner** [comment]
Hi,
there are some samples out demonstration how to use Vaadin with bndtools:

- https://github.com/osgi/osgi.enroute.examples.vaadin
- https://github.com/vaadin-osgi/vaadin-addons

If you have any questions, you are welcome.

best Florian
