### ISSUE TITLE
Chart export to SVG then converted to JPG with Batik results in a blank image

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/framework#9719]
**UPDATE I believe there is a bug in SVGGenerator because if I disable tooltip on the configuration before running SVGGenerator then everything works perfectly:**

`configuration.getTooltip().setEnabled(false);`

I'm using Vaadin's Charts 4.0.0  with Vaadin version 8.0.7 to generate an SVG file. I then try to convert this SVG file to a JPG file using Batik (I've tried both 1.7 and 1.9 - I tried 1.7 due to a possible issue in the latest version of Batik) but each time it's always blank.

My code to generate the SVG file:

```
Chart chart = new Chart();
chart.setHeight("450px");
chart.setWidth("100%");

Configuration configuration = chart.getConfiguration();
configuration.getChart().setType(ChartType.LINE);

configuration.getTitle().setText("Account Entries");

configuration.getxAxis().setType(AxisType.DATETIME);
configuration.getxAxis().setDateTimeLabelFormats(new DateTimeLabelFormats("%b %Y", "%Y"));

YAxis yAxis = configuration.getyAxis();
yAxis.setTitle(new AxisTitle("Profits"));
yAxis.setMin(0);

DataSeries entries = new DataSeries();
entries.setPlotOptions(new PlotOptionsLine());
entries.setName("Accounting Entries");

entries.add(new DataSeriesItem(Instant.now(), 24));
entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(1)), 45));
entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(2)), 78));
entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(6)), 105));

configuration.getxAxis().setTitle("Months");
configuration.getyAxis().setTitle("Sales");

configuration.addSeries(entries);
chart.drawChart(configuration);
```

My code to then convert the chart to an SVG file which I then save to a file is:

```
String svg = SVGGenerator.getInstance().generate(chart.getConfiguration());
```

My Code to convert to jpg with Batik is:

```
public static void main(String[] args) throws Exception 
{
     InputStream inputStream = new FileInputStream(new File("C:\\temp\\chart.svg"));

     JPEGTranscoder t = new JPEGTranscoder();
     t.addTranscodingHint(JPEGTranscoder.KEY_QUALITY, new Float(.8));

     TranscoderInput input = new TranscoderInput(inputStream);

     OutputStream outputStream = new FileOutputStream("C:\\temp\\chart.jpg");
     TranscoderOutput output = new TranscoderOutput(outputStream);

     t.transcode(input, output);

     outputStream.flush();
     outputStream.close();

     System.exit(0); 
}
```

The part that is causing the issue in the SVG file is:

```
<g class="highcharts-tooltip" style="cursor:default;padding:0;pointer-events:none;white-space:nowrap;" transform="translate(0,-9000000000)">
	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.049999999999999996" stroke-width="5" transform="translate(1, 1)"/>
	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.09999999999999999" stroke-width="3" transform="translate(1, 1)"/>
	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.15" stroke-width="1" transform="translate(1, 1)"/>
	<path fill="#FFFFFF" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"/>
	<text x="8" style="font-size:12px;color:#333333;fill:#333333;" y="20"/>
</g>

```

I've attached the generated SVF file but renamed to to chart2.txt which you can rename to chart.svg so that I could attach the file to the ticket. And the file chart.jpg is the blank image file in case it helps.

[chart2.txt](https://github.com/vaadin/framework/files/1168735/chart2.txt)
![chart](https://user-images.githubusercontent.com/19716286/28507217-16055de8-6fff-11e7-8670-f45cb8b0a3af.jpg)

**Comment by alvarezguille** [comment]
Thanks @FollowSteph for such detailed report! 
Unluckily I'll have to close this as this issue has been already reported in charts repository vaadin/charts#351, please subscribe to 351 to get updates.

**Comment by FollowSteph** [comment]
Out of curiosity what does the tooltip actually draw in the SVG file? In other words why is it generating anything at all in the SVG? I'm sure it's something I'm missing but I'm curious what it's doing...

**Comment by alvarezguille** [comment]
If you inspect the chart you can see the SVG and the tooltip is part of it. 

When you export to SVG using the export menu in clientside or the SVGGenerator you're just exporting the original SVG with all its content, including the tooltip. 

The tooltip by default is hidden so it might seem as it makes little sense, but if for some reason you have an always visible tooltip (which is not so easy without some javascript) then it will be a visible part of the generated SVG.

**Comment by devmania** [comment]
> **UPDATE I believe there is a bug in SVGGenerator because if I disable tooltip on the configuration before running SVGGenerator then everything works perfectly:**
> 
> `configuration.getTooltip().setEnabled(false);`
> 
> I'm using Vaadin's Charts 4.0.0 with Vaadin version 8.0.7 to generate an SVG file. I then try to convert this SVG file to a JPG file using Batik (I've tried both 1.7 and 1.9 - I tried 1.7 due to a possible issue in the latest version of Batik) but each time it's always blank.
> 
> My code to generate the SVG file:
> 
> ```
> Chart chart = new Chart();
> chart.setHeight("450px");
> chart.setWidth("100%");
> 
> Configuration configuration = chart.getConfiguration();
> configuration.getChart().setType(ChartType.LINE);
> 
> configuration.getTitle().setText("Account Entries");
> 
> configuration.getxAxis().setType(AxisType.DATETIME);
> configuration.getxAxis().setDateTimeLabelFormats(new DateTimeLabelFormats("%b %Y", "%Y"));
> 
> YAxis yAxis = configuration.getyAxis();
> yAxis.setTitle(new AxisTitle("Profits"));
> yAxis.setMin(0);
> 
> DataSeries entries = new DataSeries();
> entries.setPlotOptions(new PlotOptionsLine());
> entries.setName("Accounting Entries");
> 
> entries.add(new DataSeriesItem(Instant.now(), 24));
> entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(1)), 45));
> entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(2)), 78));
> entries.add(new DataSeriesItem(convert(LocalDate.now().plusMonths(6)), 105));
> 
> configuration.getxAxis().setTitle("Months");
> configuration.getyAxis().setTitle("Sales");
> 
> configuration.addSeries(entries);
> chart.drawChart(configuration);
> ```
> 
> My code to then convert the chart to an SVG file which I then save to a file is:
> 
> ```
> String svg = SVGGenerator.getInstance().generate(chart.getConfiguration());
> ```
> 
> My Code to convert to jpg with Batik is:
> 
> ```
> public static void main(String[] args) throws Exception 
> {
>      InputStream inputStream = new FileInputStream(new File("C:\\temp\\chart.svg"));
> 
>      JPEGTranscoder t = new JPEGTranscoder();
>      t.addTranscodingHint(JPEGTranscoder.KEY_QUALITY, new Float(.8));
> 
>      TranscoderInput input = new TranscoderInput(inputStream);
> 
>      OutputStream outputStream = new FileOutputStream("C:\\temp\\chart.jpg");
>      TranscoderOutput output = new TranscoderOutput(outputStream);
> 
>      t.transcode(input, output);
> 
>      outputStream.flush();
>      outputStream.close();
> 
>      System.exit(0); 
> }
> ```
> 
> The part that is causing the issue in the SVG file is:
> 
> ```
> <g class="highcharts-tooltip" style="cursor:default;padding:0;pointer-events:none;white-space:nowrap;" transform="translate(0,-9000000000)">
> 	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.049999999999999996" stroke-width="5" transform="translate(1, 1)"/>
> 	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.09999999999999999" stroke-width="3" transform="translate(1, 1)"/>
> 	<path fill="none" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"  stroke="black" stroke-opacity="0.15" stroke-width="1" transform="translate(1, 1)"/>
> 	<path fill="#FFFFFF" d="M 5 0 L 11 0 C 16 0 16 0 16 5 L 16 11 C 16 16 16 16 11 16 L 5 16 C 0 16 0 16 0 11 L 0 5 C 0 0 0 0 5 0"/>
> 	<text x="8" style="font-size:12px;color:#333333;fill:#333333;" y="20"/>
> </g>
> ```
> 
> I've attached the generated SVF file but renamed to to chart2.txt which you can rename to chart.svg so that I could attach the file to the ticket. And the file chart.jpg is the blank image file in case it helps.
> 
> [chart2.txt](https://github.com/vaadin/framework/files/1168735/chart2.txt)
> ![chart](https://user-images.githubusercontent.com/19716286/28507217-16055de8-6fff-11e7-8670-f45cb8b0a3af.jpg)

Dear FollowSteph,

thank you very much! You saved me a lot of headache. I'm using Vaadin 8.4.1 and Batik 1.11 together with phantomjs 2.1.1 and faced the same problem.
Disabling the tooltip works perfectly for me.
