### ISSUE TITLE
Make versioned documentation and demo

### ISSUE THREAD

**Issue by kiru** [vaadin/framework#9724]
Example: 
I go to: https://vaadin.com/docs/-/part/framework/components/components-listselect.html
First question: Which version does it show? All right, it is for "Vaadin Framework 8", mh ok, I still have no clue which actual version.  
So, we use Vaadin 7. Ok, I switch to https://vaadin.com/docs7/-/part7/framework/components/components-listselect.html. Same question, which version. I click on Live Demo and the demo is shown, but for version 8 (https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/list-select). 

A few suggestion: 

* Please show the actual version ( the full version!)
* Clarify somewhere, that Demo is for Version 8 
* Better: Make versioned documentation. A good example is Jooq (https://www.jooq.org/doc/3.9/manual/getting-started/)
* Make Demo for Vaadin 7 available 

Thank you, 
Kiru

**Comment by TatuLund** [comment]
Our documentation vaadin.com/docs and API vaadin.com/api sites have been versioned already for a while, hence closing.
