### ISSUE TITLE
Tabsheet: Provide hook for right-click on tab (For implementing "Close others", etc..)

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#9725]
Hi,

it would be a very nice improvement to have such a hook. We rely heavily on the tabsheet in our Application, and there are many tabs. There is currently no way to register a handler for right-click,
that knows the tab over which the cursor is positioned (This must not be the currently selected tab, of course!).

We want to add functionality like e.g. in Eclipse
* Close this
* Close others
* Close tabs to right
* Close All

Regards
Benjamin

**Comment by hesara** [comment]
This might be doable (although probably not very easy) with an Extension that hooks into VTabsheet. However, a support for a custom context click event on tabs (like Grid has its custom context click event type) would probably make this much simpler.

**Comment by bjung82** [comment]
A custom context click event wold be really nice :-)

**Comment by bjung82** [comment]
See the tips here for implementing this: #10418 

We implemented our own solution this way.
