### ISSUE TITLE
Inconsistent Tabindex on disabled Components - CheckBoxGroup and RadioButtonGroup

### ISSUE THREAD

**Issue by appreciated** [vaadin/framework#9731]
When having multiple Inputs as follows: 

````
<!doctype html>
<html>
 <head>
  <meta charset="UTF-8">
  <meta name="design-properties" content="{&quot;RULERS_VISIBLE&quot;:true,&quot;GUIDELINES_VISIBLE&quot;:false,&quot;SNAP_TO_OBJECTS&quot;:true,&quot;SNAP_TO_GRID&quot;:true,&quot;SNAPPING_DISTANCE&quot;:10,&quot;GENERATE_GETTERS&quot;:false,&quot;JAVA_SOURCES_ROOT&quot;:&quot;src/main/java&quot;,&quot;THEME&quot;:&quot;mytheme&quot;}">
  <meta name="vaadin-version" content="8.0.5">
  <meta name="package-mapping" content="com_vaadin:com.vaadin">
 </head>
 <body>
  <vaadin-vertical-layout>
   <vaadin-text-field _id="t1"></vaadin-text-field>
   <vaadin-text-field enabled="false" _id="t2"></vaadin-text-field>
   <vaadin-text-field _id="t3"></vaadin-text-field>
   <vaadin-check-box-group data-item-type="java.lang.String" _id="cb1">
    <option item="Option1">Option 1</option>
   </vaadin-check-box-group>
   <vaadin-check-box-group enabled="false" data-item-type="java.lang.String" _id="cb2">
    <option item="Option1">Option 1</option>
   </vaadin-check-box-group>
   <vaadin-radio-button-group data-item-type="java.lang.String" _id="rb1">
    <option item="Option1">Option 1</option>
   </vaadin-radio-button-group>
   <vaadin-radio-button-group enabled="false" data-item-type="java.lang.String" _id="rb2">
    <option item="Option1">Option 1</option>
   </vaadin-radio-button-group>
   <vaadin-text-field _id="t4"></vaadin-text-field>
  </vaadin-vertical-layout>
 </body>
</html>
````

As a user I expect the tab-behaviour to be consistent when "tabbing" through different components. Even so when several components are disabled or enabled.

Currently the wrapper of an enabled/disabled CheckBoxGroup/RadioButtonGroup has in both enabled and disabled state a tabindex of zero. 
This causes each checkbox/radiobutton group an additional step when "tabbing" through the example input above.

Apart from that, the disabled CheckBoxGroup/RadioButtonGroup looks the same as enabled ones (I'll open a secound issue for that).

**Comment by RhonanMS** [comment]
The same issue came up in our project. I have prepared a small example in order to provide additional information:

**Vaadin Framework version:** 
8.4.1

**Browser version:** 
- Firefox 6.0.2 (64-bit)
- Google Chrome 66.0.3359.170
- Internet Explorer 11.0.9600.19002

**Web container name and version:** 
Apache Tomcat 7.0.75

**Description of the bug:**
When tabbing between CheckBoxGroup and RadioGroup components, an additional press of the Tab key is required while leaving the previous Group and jumping to the next one. 
It seems that the surrounding <div class="v-select-optiongroup v-widget"> has a fixed tabIndex attribute value of 0 for both components.

**Minimal reproducible example:**


	final VerticalLayout layout = new VerticalLayout();

	List<String> cbg1Content = Arrays.asList("Entry 1", "Entry 2", "Entry 3");
	CheckBoxGroup<String> cbg1 = new CheckBoxGroup<>("Test 1", cbg1Content);
	layout.addComponent(cbg1);

	List<String> cbg2Content = Arrays.asList("Entry 1", "Entry 2", "Entry 3");
	CheckBoxGroup<String> cbg2 = new CheckBoxGroup<>("Test 2", cbg2Content);
	cbg2.setTabIndex(-1);
	cbg2.setReadOnly(false);
	layout.addComponent(cbg2);

	List<String> cbg3Content = Arrays.asList("Entry 1", "Entry 2", "Entry 3");
	CheckBoxGroup<String> cbg3 = new CheckBoxGroup<>("Test 3", cbg3Content);
	cbg3.setEnabled(false);
	layout.addComponent(cbg3);

	List<String> rbg1Content = Arrays.asList("Entry 1", "Entry 2", "Entry 3");
	RadioButtonGroup<String> rbg1 = new RadioButtonGroup<>("Radio Test 1", rbg1Content);
	layout.addComponent(rbg1);

	List<String> rbg2Content = Arrays.asList("Entry 1", "Entry 2", "Entry 3");
	RadioButtonGroup<String> rbg2 = new RadioButtonGroup<>("Radio Test 2", rbg2Content);
	rbg2.setTabIndex(-1);
	layout.addComponent(rbg2);

**Expected behavior:**
When tabbing through the entries and leaving the last entry of a previous component, the next entry should be tabbed to immediately. 

Calling setTabIndex() on the component should allow to change the (currently) fixed value of 0 for Group.
	
**Actual behavior:**
Between leaving the last entry and tabbing to the next entry, the tab-key has to be pressed an additional time because the tabindex of the CheckBoxGroup / RadioButtonGroup surrounding the entries is set to 0 and thus tabbable.

It should be set to -1 or be modifiable via setTabIndex.

**Comment by m-hraby** [comment]
I have a similar problem in Vaadin 8.5.1 with the RadioButtonGroup in a grid.
I put a tab index of -1 for the RadioButtonGroup which is also in div, but the input elements have a tab index of 0, which makes a tab stop again.
Example:
<td class="v-grid-cell v-align-center compact" role="gridcell" colspan="1" style="height: 23px; width: 90.6563px;">
	<div class="component-wrap" style="">
		<div tabindex="**-1**" class="v-select-optiongroup v-widget compact v-select-optiongroup-compact horizontal v-select-optiongroup-horizontal" role="radiogroup" style="outline-style: none;">
			<span class="v-radiobutton v-select-option">
				<input type="radio" name="gwt-uid-341" value="on" id="gwt-uid-450" tabindex="**0**">
				<label for="gwt-uid-450">Rab</label>
			</span>
			<span class="v-radiobutton v-select-option v-select-option-selected">
				<input type="radio" name="gwt-uid-341" value="on" id="gwt-uid-451" tabindex="**0**" checked="">
				<label for="gwt-uid-451">Nto</label>
			</span>
		</div>
	</div>
</td>

**Comment by m-hraby** [comment]
&lt;td class="v-grid-cell v-align-center compact" role="gridcell" colspan="1" style="height: 23px; width: 90.6563px;"&gt;
	&lt;div class="component-wrap" style=""&gt;
		&lt;div **tabindex="-1"** class="v-select-optiongroup v-widget compact v-select-optiongroup-compact horizontal v-select-optiongroup-horizontal" role="radiogroup" style="outline-style: none;"&gt;
			&lt;span class="v-radiobutton v-select-option"&gt;
				&lt;input type="radio" name="gwt-uid-341" value="on" id="gwt-uid-450" **tabindex="0"**&gt;
				&lt;label for="gwt-uid-450"&gt;Rab&lt;/label&gt;
			&lt;/span&gt;
			&lt;span class="v-radiobutton v-select-option v-select-option-selected"&gt;
				&lt;input type="radio" name="gwt-uid-341" value="on" id="gwt-uid-451" **tabindex="0"** checked=""&gt;
				&lt;label for="gwt-uid-451"&gt;Nto&lt;/label&gt;
			&lt;/span&gt;
		&lt;/div&gt;
	&lt;/div&gt;
&lt;/td&gt;
