### ISSUE TITLE
Disabled CheckBoxGroup/RadioButtonGroup looks the same as enabled

### ISSUE THREAD

**Issue by appreciated** [vaadin/framework#9732]
````
<!doctype html>
<html>
 <head>
  <meta charset="UTF-8">
  <meta name="design-properties" content="{&quot;RULERS_VISIBLE&quot;:true,&quot;GUIDELINES_VISIBLE&quot;:false,&quot;SNAP_TO_OBJECTS&quot;:true,&quot;SNAP_TO_GRID&quot;:true,&quot;SNAPPING_DISTANCE&quot;:10,&quot;GENERATE_GETTERS&quot;:false,&quot;JAVA_SOURCES_ROOT&quot;:&quot;src/main/java&quot;,&quot;THEME&quot;:&quot;mytheme&quot;}">
  <meta name="vaadin-version" content="8.0.5">
  <meta name="package-mapping" content="com_vaadin:com.vaadin">
 </head>
 <body>
  <vaadin-vertical-layout>
   <vaadin-check-box-group data-item-type="java.lang.String" _id="cb1">
    <option item="Option1">Option 1</option>
   </vaadin-check-box-group>
   <vaadin-check-box-group enabled="false" data-item-type="java.lang.String" _id="cb2">
    <option item="Option1">Option 1</option>
   </vaadin-check-box-group>
   <vaadin-radio-button-group data-item-type="java.lang.String" _id="rb1">
    <option item="Option1">Option 1</option>
   </vaadin-radio-button-group>
   <vaadin-radio-button-group enabled="false" data-item-type="java.lang.String" _id="rb2">
    <option item="Option1">Option 1</option>
   </vaadin-radio-button-group>
  </vaadin-vertical-layout>
 </body>
</html>
````

As a User I want to be able to visually distinguish between an enabled component and a disabled one.

**Comment by rntrp** [comment]
I confirm this for 8.1.1. The checkboxes get `v-checkbox-disabled` style instead of [docs-compliant](https://vaadin.com/docs/-/part/framework/components/components-optiongroups.html#components.optiongroups.disabling)  `v-disabled`

As a temporary workaround you can adapt the style from `.v-checkbox.v-disabled` like this:
```scss
.v-checkbox-disabled {
  cursor: default;
  opacity: 0.5;
  filter: alpha(opacity=50);
}
```

Hope it will be fixed soon.

**Comment by mstahv** [comment]
I assume this is the same as #9258

**Comment by appreciated** [comment]
Yes it is, should I close it in favor of #9258?

**Comment by mstahv** [comment]
Please, and go to the other ticket and vote for it by thumb up or by a comment that you find this important to be fixed. I find it very odd that this is not fixed yet.

**Comment by Juchar** [comment]
It seems that it is not fixed for the **label** of a CheckboxGroup, the text is not greyed out. Using Vaadin 12.0.5.

**Comment by appreciated** [comment]
Vaadin 8 has not much to do with Vaadin 12. Please open an issue at [vaadin-checkbox](https://github.com/vaadin/vaadin-checkbox) or/and [vaadin-radio-button](https://github.com/vaadin/vaadin-radio-button)
