### ISSUE TITLE
VaadinService improvements

### ISSUE THREAD

**Issue by rjahn** [vaadin/framework#9735]
It would be very useful to change some method modifiers in VaadinService:

* private isSessionActive -> protected
* private closeInactiveUIs -> protected
* private isUIActive -> protected
* private removeClosedUIs -> protected
* cleanupSession -> protected (if possible)

Above methods would avoid code duplication in derivated classes.

**Comment by hesara** [comment]
What are the use cases where each of these is needed?
Perhaps some refactoring providing a better API for those use cases would lead to a cleaner solution.

**Comment by rjahn** [comment]
The use case was this Issue #9734 

We tried to implement this feature and had problems with above methods. So we had to copy the code...
