### ISSUE TITLE
ColorPicker displays previous color not current one.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#9739]
https://vaadin.com/forum#!/thread/15961313

I've also noticed something else and this happens also on your vaadin sampler app. When you first click on the colorpicker button and change the color, the color on the button changes as expected. When you click on the button again the window displays the previous color and not the one currently on the button. You can change the color on the button but the color displayed on the window is always the first one.

**Comment by enver-haase** [comment]
On my application I have many colorpickers and they all display the first color of the first colorpicker that I happen to open. When I use getvalue to read the color they return the proper values (as displayed on the respective buttons) but the windows all start at the same color regardless of the color that the button shows. Since this happens on the sampler too it must be a bug. I've tested it on Firefox and Opera.

**Comment by aiolos01** [comment]
The issue has only been partially fixed. Now the color displayed on the button is correct. However when you click on it and the RGB panel opens it still has the first color of the button selected and not the current color.
The issue still exists on the sampler application.

**Comment by anasmi** [comment]
Hi,

the logic of color picker value change events was revisited and this issue and the one mentioned by @aiolos01 should be addressed by this [pull request](https://github.com/vaadin/framework/pull/10812).  We have merged it into the master and it should be available in the next release.

Thanks for you help and contributions! 
And have a nice weekends :)

**Comment by aiolos01** [comment]
Confirmed. It works as it should now. Thanks.
