### ISSUE TITLE
Use case for retaining addUriFragmentChangedListener

### ISSUE THREAD

**Issue by QNENet** [vaadin/framework#9743]
When processing Paypal the express checkout flow does not activate the addPopStateListener.
This may be a reason for not deprecating addUriFragmentChangedListener

	@SuppressWarnings("deprecation")
	@Override
	protected void init(VaadinRequest vaadinRequest) {

			getPage().addPopStateListener(new PopStateListener() {

			@Override
			public void uriChanged(PopStateEvent event) {
				
				System.out.println("POPSTATE CHANGE");
				enter(event.getUri());
			}
		});

		getPage().addUriFragmentChangedListener(new UriFragmentChangedListener() {

			@Override
			public void uriFragmentChanged(UriFragmentChangedEvent event) {

				String fragment = event.getUriFragment();
				System.out.println("fragment -> " + fragment);

				if (handlePaypal(fragment)) {
					
					System.out.println("PAYPAL HANDLED");
					
					nav.navigateTo(PAYPAL_SUCCESS);
				}

				enter(fragment);

			}

		});

		String fragment = getPage().getUriFragment();

		System.out.println("fragment -> " + fragment);

		// Read the initial URI fragment
		enter(fragment);
	}

	void enter(String fragment) {

		nav = new Navigator(this, this);

//		addViewChangeListener();

		nav.addView(OPENING_PAGE, new OpeningPageView(parent));
		nav.addView(PAYMENT_PAGE, new PaymentView(parent));
		nav.addView(PAYPAL_SUCCESS, new PaypalSuccess(parent));
		nav.addView(PAYPAL_CANCEL, new PaypalCancel(parent));

		nav.navigateTo(OPENING_PAGE);

	}

**Comment by hesara** [comment]
See #9251, which we missed in 8.1 even though originally planned for it.

**Comment by Legioth** [comment]
Duplicate of #9251.
