### ISSUE TITLE
Vaadin 8.x.x Grid big datasource view bug in Firefox

### ISSUE THREAD

**Issue by mdklab** [vaadin/framework#9752]
Vaadin Grid rows with numbers 235469 (zero based) and more is not visible in Firefox.

![firefox_bug](https://user-images.githubusercontent.com/4253140/28707562-861b82b2-7381-11e7-8586-6112eb4f4f97.png)

Vaadin 8.0.x and 8.1.x
Firefox 54.0.1
Test case: https://github.com/mdklab/vaadin-big-grid-bug

How to reproduce:
* run "mvn install"
* run "mvn jetty:run"
* open http://localhost:8080
* go to the row with number 235469 or more, make sure that rows is not visible

**Comment by Legioth** [comment]
Same issue as https://github.com/vaadin/framework/issues/6290, but the limit isn't reached as quickly in Firefox.

Closing this as a duplicate.
