### ISSUE TITLE
ValueChange event not fired in NewItemHandler

### ISSUE THREAD

**Issue by sirbris** [vaadin/framework#9774]
In Vaadin 8.1.0, when I set the NewItemHandler, there's no value change event fired... I could set it myself in the accept-method but then it wouldn't be user originated. In my opinion a user originated value change event should be fired, if the user added a new item to the ComboBox.

Example:
```
        ArrayList<String> items = new ArrayList<>();
        items.add("Item 1");
        items.add("Item 2");
        LobsterComboBox<String> cmb = new LobsterComboBox<>();
        cmb.setItems(items);
        cmb.setNewItemHandler(new NewItemHandler() {
            @Override
            public void accept(String inT) {
                items.add(inT);
                cmb.getDataProvider().refreshAll();
            }
        });
        cmb.addValueChangeListener(event -> System.out.println("userOriginated: " + event.isUserOriginated()));
```

**Comment by steeeffen** [comment]
I think this is a bug rather than a missing feature...

**Comment by sirbris** [comment]
Any updates on this one?
The behaviour of ValueChange and SelectionChange doesn't seem to be correct... what exactly is supposed to be the difference?
The SelectionChangeListener is fired when I add a new item from the UI (by hitting Enter after a new input), but the ValueChangeEvent isn't. When I tab out of the ComboBox after typing in a new value, neither the SelectionChange nor the ValueChange is fired. This is a bug, right?

**Comment by Ansku** [comment]
I'm afraid I can't reproduce this issue with regular ComboBox -- hitting enter adds the item, hitting enter the second time selects the item and triggers both value change and selection change events, and if you comment out in turn each of the updateCountLabel calls in my attached test UI you'll see that both events are marked user originated as well.

[Issue9774UI.txt](https://github.com/vaadin/framework/files/1431392/Issue9774UI.txt)

**Comment by sirbris** [comment]
There seems to be a difference when I click outside the combobox after entering a new value or use TAB. That it probably not intended right?

```
        ArrayList<String> items = new ArrayList<>();
        items.add("Item 1");
        items.add("Item 2");
        ComboBox<String> cmb = new ComboBox<>();
        cmb.setItems(items);
        cmb.setNewItemHandler(inT -> {
            items.add(inT);
            cmb.getDataProvider().refreshAll();
            cmb.setSelectedItem(inT);
        });
        cmb.addSelectionListener(event -> System.out.println("SELECTION"));
        cmb.addBlurListener(event -> System.out.println("BLURRED"));
        cmb.addValueChangeListener(event -> System.out.println("userOriginated: " + event.isUserOriginated()));
        addComponent(cmb);
```
First of all, BlurListener doesn't seem to get fired at all!?
SelectionListener on new items only work when I use the TAB key. Then of course the value change event will say that it is NOT user originated, since I set the value in the new item handler.
Hitting ENTER twice is definitely not intuitive. Can this behavior be configured somehow?
We need to use the ComboBox almost as it was a TextField, just with a few suggestions.

**Comment by sirbris** [comment]
Also, with the current behavior, it is possible, that after typing in text in the combox and leaving it, the shown text does not match the underlying selected value of the combobox. This is highly risky imho. The field should be marked invalid or the value needs to be reset. Either way the "real" selected value should be displayed in the combobox after leaving it (by TAB-key OR just clicking outside) or am I missing something?

**Comment by Ansku** [comment]
I did some further testing and could only reproduce a difference between tabulator and clicking in 8.1.6, but the behaviour itself is inconsistent (created a new issue about it, linked above). Still didn't manage to reproduce the case where selection happens but ValueChangeEvent doesn't fire, though.

**Comment by sirbris** [comment]
Sorry, a little mix up... The ValueChangeEvent is thrown (with TAB out), just not userOriginated=true, because you have to select the new entered item by code.

The desired behavior would be:
1. user enters text in the combobox (value does not exist in underlying dataprovider)
2. combobox loses focus (user tabs out or clicks anywhere else)
3. the new item was added to the dataprovider (done by code in the new item handler)
4. the new item is selected (which ultimately was user originated)

Since I have to select the new item myself, the ValueChangeEvent will never be user originated... can I manipulate it somehow?

**Comment by Ansku** [comment]
Sorry, missed this comment somehow -- the only way you can get a programmatically triggered ValueChangeEvent with user originated true is if you trigger it yourself, there is no built-in option for counting side effects of user actions as user originated.
