### ISSUE TITLE
Null caption for components inside FormLayout doesn't update UI

### ISSUE THREAD

**Issue by qtdzz** [vaadin/framework#9777]
### Description
* For FormLayout: childComponent.setCaption(null) won't clear the caption
* For all other layouts: childComponent.setCaption(null) will clear the caption 

childComponent.setCaption("") will clear for all the cases but the empty caption will be written into declarative `caption=""` which is redundant in Designer
The bug priority may be a bit low but we still need it fixed at some point
### Example
```
 @Override
    protected void init(VaadinRequest vaadinRequest) {
        VerticalLayout verticalLayout = new VerticalLayout();
        TextField textFieldVL = new TextField("Vertial Layout Caption");

        FormLayout formLayout = new FormLayout();
        TextField textField = new TextField("Form Layout Caption");
        Button buttonNull = new Button("Set Null");
        buttonNull.addClickListener((Button.ClickListener) event -> {
            textField.setCaption(null);
            textFieldVL.setCaption(null);
        });
        Button buttonEmpty = new Button("Set Empty");
        buttonEmpty.addClickListener((Button.ClickListener) event -> {
            textField.setCaption("");
            textFieldVL.setCaption("");
        });
        Button buttonMyCaption = new Button("Set MyCaption");
        buttonMyCaption.addClickListener((Button.ClickListener) event -> {
            textField.setCaption("Form Layout Caption");
            textFieldVL.setCaption("Vertial Layout Caption");
        });
        formLayout.addComponents(textField, buttonNull, buttonEmpty, buttonMyCaption);
        verticalLayout.addComponents(textFieldVL, formLayout);
        setContent(verticalLayout);

    }
```
### Vaadin version
8.1.0

**Comment by hesara** [comment]
This is most likely caused by https://github.com/vaadin/framework/blob/master/client/src/main/java/com/vaadin/client/ui/VFormLayout.java#L296 which should at least clear the content of the caption span and its ARIA properties if caption is null. I'm not sure if it would be better to remove the span, or just to treat a null caption like an empty one.
