### ISSUE TITLE
BlurListener not working!

### ISSUE THREAD

**Issue by sirbris** [vaadin/framework#9783]
Vaadin 8.1.1:
addBlurListener is not working... when I focus out of the textfield by mouse or keyboard the BlurEvent never gets fired.

Example:
```
TextField tf = new TextField("Test Blur:");
tf.addBlurListener(event -> System.out.println("BLURRED"));
```

**Comment by sirbris** [comment]
No one else experiencing this problem?
BlurListener also has no effect for ComboBox (Vaadin 8.1.5). Neither is the FocusListener btw or am I missing something?

**Comment by knoobie** [comment]
Tested with the latest SNAPSHOT on MacOS Firefox - can't reproduce it. 

What OS/Browser are you using? 

I don't think such a basic feature is faulty for months.

**Comment by draganr** [comment]
I have the same problem. See the tasks:
https://github.com/vaadin/framework/issues/10414
https://github.com/vaadin/framework/issues/10805

**Comment by Nakor74** [comment]
I have this issue with a DateField. After deleting the Focus-Listener the Blur-Listener is not fired anymore.
