### ISSUE TITLE
Vaadin Grid height issue, bug, problem

### ISSUE THREAD

**Issue by scrmtrey91** [vaadin/framework#9786]
Example:

I set caption of column header with setHtml("`Header <b> bold </b> <br> this is new line`")

While the new line is created, the height of header is not adjusted to the new content with additional new line. Instead it write the second line above content of cell bellow it and header height remains the same (too small, not auto adjusting). 

Using vaadin 8.1.1 version.

**Comment by scrmtrey91** [comment]
Because vanila vaadin does not provide this feautre , i managed to get auto height header to work with this addon / extension:  https://vaadin.com/directory#!addon/gridextensionpack-add-on 



This should be in vanila vaadin also.

**Comment by TatuLund** [comment]
Nowadays Grid has methods to set header, body and footer row heights separately, which should address is this problem.
