### ISSUE TITLE
DateField icon in HeaderRow Cell moves over to frozen column's space when horizontally scrolling the grid

### ISSUE THREAD

**Issue by evanzel** [vaadin/framework#9787]
Version : Vaadin 8.0 & 8.1 (this did not happen with Vaadin 7)
Description: I have a DateField as Component in a HeaderRowCell and the grid has a frozen column and can scroll horizontally.
When I scroll to the right; the icon from the datefield moves over to the frozen column contents instead of hiding, like any other component does.

Code to reproduce:

        Grid<SomeClass> grid = new Grid<>();
        Column col1 = grid.addColumn(s -> {return "col1";}).setWidth(100).setCaption("col1");
        Column col2 = grid.addColumn(s -> {return "col2";}).setWidth(200).setCaption("col2");
        Column col3 = grid.addColumn(s -> {return "col3";}).setWidth(999).setCaption("col3");
        grid.setFrozenColumnCount(1);
        HeaderRow headerRow = grid.addHeaderRowAt(1);
        headerRow.getCell(col1).setComponent(new Label("h1"));
        headerRow.getCell(col2).setComponent(new DateField());
        headerRow.getCell(col3).setComponent(new Label("h3"));
        layout.addComponents(grid);
        setContent(layout);

I provide images that show the result from scrolling.

<img width="393" alt="grid8datefield1" src="https://user-images.githubusercontent.com/14197533/28994015-7a0ef78c-79cc-11e7-9aea-7536f5e41b4a.png">
<img width="409" alt="grid8datefield2" src="https://user-images.githubusercontent.com/14197533/28994016-7a1056ea-79cc-11e7-9a3b-c744c9465dd3.png">

**Comment by fante76** [comment]
We found this problem too. It seems to be originated by wrong z-index. Renderer seems to apply frozen css class to scrolling columns also.

**Comment by dnDeveloper** [comment]
We have the same problem using DateFields in a grid HeaderRow. Vaadin 8.1.7

**Comment by evanzel** [comment]
This is still valid for 8.3.3
A quick workaround:
.v-datefield [class*="button"] {
        z-index: auto;
    }

**Comment by joha78** [comment]
This is still valid for 8.4.4

**Comment by Kalomo** [comment]
the existing workaround fixes the overlaying issue of the icon but unfortunately the icon will be hidden when the textfield gets the focus

![image](https://user-images.githubusercontent.com/42035833/43584906-ff0d891c-9663-11e8-9939-7ea296b0b6aa.png)
