### ISSUE TITLE
Vaadin Validators add Severity (INFO, WARN, ERROR)

### ISSUE THREAD

**Issue by sknitelius** [vaadin/framework#9792]
Currently all Validations are handled as a Fatal validation failure, i.e. all further processing is disallowed.

```
binder.forField(myField)
.withValidator(str -> str.matches("[a-zA-Z0-9]{1,20}"),"My error message")
```

However many business validations have informative characteristics. 

- Warnings - such as when certain thresholds are exceeded or approval from upper management is required.
- Info -  when unusual data is entered and should be rechecked.
- etc....

My proposal is to allow Validators to be defined with a severity level.

Similar to:
```
binder.forField(myField)
.withValidator(str -> str.matches("[a-zA-Z0-9]{1,20}"),"My info message"), Severity.INFO)
```

Severity.INFO - results in a blue Information-Icon for the field and blue border.
Severity.WARN - results in a yellow warn Icon and yellow border.
Severity.ERROR - same as current behavior (red border, etc...).

When checking `binder.isValid()` or `binder.writeBeanIfValid(myBean)` only Severity.ERROR validator failures are to be considered.

Extra methods should be added to check for Info and Warnings:
```
binder.hasWarnings()
binder.hasInfos()
```

**Comment by jdahlstrom** [comment]
This was one of the original design goals of the revamped validation system, but it never ended up being implemented due to the usual reasons. The architecture should still make implementing it fairly simple.
