### ISSUE TITLE
Grid fast setItems calls don't refresh the presentation of grid

### ISSUE THREAD

**Issue by scrmtrey91** [vaadin/framework#9793]
Example:

User picks date from InlineDateField(resolution MONTH), then changelistener set items to the grid according to the date in InlineDateField. 

First couple of tries the gird is working OK, but lets say after 2-3 times fast date change, grid stop responding to the new data (setItems). 

ps. the grid is not marked as final, just normal component declaration

**Comment by AemonAlgiz** [comment]
You should be able to call getDataProvider().refreshAll()

Does that not help?
