### ISSUE TITLE
Drag and drop non functional when using Windows + Chrome + Touchscreen. 

### ISSUE THREAD

**Issue by appreciated** [vaadin/framework#9798]
[Goto](https://demo.vaadin.com/sampler/#ui/drag-drop/drag-components-html5) and add a custom emulated device in the Chrome developement tools.

![desktop-touch](https://user-images.githubusercontent.com/1729845/29087062-e9aa2828-7c74-11e7-906b-dce78abf7640.PNG)

All gestures will be ignored.

Background:
This behaviour was actually observed with a Windows Computer (Windows 10) with a touchscreen and a mouse. Interestingly the gestures where working in the also installed Edge Browser for both inputs but not on the most current Chrome. 

When fixing this issue you might want to doublecheck that dragging with the mouse and dragging with the touchscreen is both working.

**Comment by appreciated** [comment]
My current workarround is manipulating the user agent depending on if the client has a touchscreen or not.

**Comment by appreciated** [comment]
It actually works when `setMobileHtml5DndEnabled(true);` is set

**Comment by OldIMP** [comment]
Duplicate of #9974
