### ISSUE TITLE
Vaadin 8.1 Tree setItemDescriptionGenerator

### ISSUE THREAD

**Issue by benjaminstern** [vaadin/framework#9803]
Since version 8 I don't find a replacement method for the missing setItemDescriptionGenerator() method on the vaadin tree. Is there another possibility to create a tooltip on an single tree item?

In my opinion the setItemDescriptionGenerator just got lost without a replacement method.

**Comment by kauvj** [comment]
Even we were using setItemDescriptionGenerator to generate some descriptions for each item but now after 8.1, this isn't available. Can someone confirm that this functionality is removed intentionally?

**Comment by rntrp** [comment]
The method is also missing from `RadioButtonGroup` and `CheckBoxGroup`.
