### ISSUE TITLE
[Vaadin 8.1] Widgetset compilation does not include custom widgets

### ISSUE THREAD

**Issue by T3rm1** [vaadin/framework#9814]
Vaadin 8.1

Project B has a maven dependency to a Vaadin addon
Project A depends on project B and has an implemantation of a custom widget in a package (not in root folder)

When I compile the widgetset for project A, I see in the log that it detects the widgetset of dependency of project B and the widgetset of project A in the subpackage. Next the widgetset of project A is overwritten with the collected information. It includes entry for the addon, default Vaadin widgetset and project A. Note that no AppWidgetSet.gwt.xml is created.

Next step is vaadin:compile
The first thing to observe is that the log output does not show anything about connector classes from the addon nor project A. The final compiled js file includes neither code of the addon nor of project A.

There a quite a few bug happening here:

- Manually written widgetset for custom widget in project A is overwritten
- No AppWidgetSet.gwt.xml is created
- Compiled js file has no code of any widget except default Vaadin widgetset.

**Comment by hesara** [comment]
Some of these are perhaps more for the forum than bugs, but trying address these here:

* If you have widgets and a widgetset in a separate module, the module should declare that in its manifest for those to be automatically added to the widgetset of the projects depending on it. If there are no such modules, there is no reason for the Maven plug-in to generate an AppWidgetset.gwt.xml. The manifest entries are something like:
```
Vaadin-Widgetsets: com.example.MyWidgetSet
Vaadin-Package-Version: 1
```
* Also, the sources of the client side of the widget must be available to the projects using them for the widgets to be included. This can be achieved with the sources plugin and an extra dependency with a classifier to include the sources, or by packaging the sources in the main JAR of the "add-on" module.
* In some very special cases where the above steps don't give you enough control, you can use a special (not really properly documented) comment in your widgetset to prevent automatic updates:
`<!-- WS Compiler: manually edited -->`

See the documentation pages [Creating add-ons](https://vaadin.com/docs/-/part/framework/gwt/gwt-addons.html), [Using add-ons](https://vaadin.com/docs/-/part/framework/addons/addons-maven.html) and [Add-on troubleshooting](https://vaadin.com/docs/-/part/framework/addons/addons-troubleshooting.html) for more information.

I think we can close this issue unless there is a clear bug not covered by what I wrote above.

**Comment by T3rm1** [comment]
I forgot to add that I tested all this with the Vaadin Eclipse plugin as well. So in that case the plugin should be able to see the source files and the maven sources plugin wouldn't be required, right? The gwt compiler showed the local path to the widgetset (target folder). But that didn't work either.
