### ISSUE TITLE
valo-themes-8.1.1.jar seems to include broken styles.scss

### ISSUE THREAD

**Issue by florianschneider** [vaadin/framework#9815]
Looking at the file, the Eclipse editor is telling me `invalid LOC header (bad signature)` , which does not occur on other versions of the file e.g. the 8.0.7 version.

**Comment by hesara** [comment]
I just checked the version from Maven Central (http://repo1.maven.org/maven2/com/vaadin/vaadin-themes/8.1.1/vaadin-themes-8.1.1.jar), which seems to be ok (including ZIP checksums in the JAR file), and the content of styles.scss looks good. Please remove the version in your Maven cache (the whole directory .m2/repository/com/vaadin/vaadin-themes/8.1.1) and re-download it.
