### ISSUE TITLE
Anonymous ClientSideCriterion results in exception

### ISSUE THREAD

**Issue by T3rm1** [vaadin/framework#9820]
It is not possible to implement an anonymous class of ClientSideCriterion. It's because in the paint method the name of the class is added as an attribute. Anonymous classes have no canonical name. They are null and null values are not allowed in the addAttribute method.

This should be fixed to allow cleaner code. Especially with Java 8 and lambdas.

**Comment by kauvj** [comment]
Is ClientSideCriterion still supported in vaadin 8?
