### ISSUE TITLE
Grid Columns : hide from menu is irreversible (Release 8.1) - with proposed fix !

### ISSUE THREAD

**Issue by ValentinTudorM** [vaadin/framework#9829]
Vaadin Release 8.1:
If some gris columns are set with is setHidable(true), and if the user deselect in the right-side menubar (with list of hidable columns) one column, that column also disappear from the menu and cannot be set as visible again.    

We have fixed this "hide grid column" issue by commenting the line in the below class and function.   
toggle.setStyleName("hidden", column.isHidden()); 
This line remove the column from the menu bar and if is removed will work.

Note: in your online example it is working. With Release 8.1 it is not working 

class com.vaadin.client.widgets.Grid.ColumnHider {

        private void updateHidingToggle(Column<?, T> column) {
            if (column.isHidable()) {
                MenuItem toggle = columnToHidingToggleMap.get(column);
                toggle.setHTML(createHTML(column));
                //toggle.setStyleName("hidden", column.isHidden()); // just comment this line
            } // else we can just ignore
        }
Anyway it is better to have the fix in official release instead of custom fixes

You own us a bug fix :)

**Comment by rntrp** [comment]
Possibly related to #9152.

**Comment by ValentinTudorM** [comment]
maybe - you can try the fix, if you have the debug mode - it is working for current problem, but it is necessary that fix to be added in an official release

**Comment by tsuoanttila** [comment]
Just tested this issue with the latest master as well as with the 8.1.2 and seems to be working for me. Can you inspect the DOM in your application to see if the elements are still in place? It could be possible that some CSS rule in your own theme is hiding the menu entry.

**Comment by ValentinTudorM** [comment]
It is a CSS problem indeed, but it is kind of vaadin CSS problem vs an add-on CSS. We have found in out CSS this part 

.hidden {
  display: none !important;
}
That part was added by a add-on  - wt-pdf-viewer-1.0.1.jar. They made a design mistake, I think "hidden" has to much visibility. 
Anyway. in our case:

toggle.setStyleName("hidden", column.isHidden()); 

it use, i think a too generic name, that could interfere with CSS parts as the ones from pdf-viewer.

This kind problem was reported also by others
- https://github.com/vaadin/vaadin-grid/issues/197 
- https://github.com/vaadin/vaadin-grid/issues/525

So, because "At least the .hidden class used inside the dropdown is sure to clash with a very large amount of existing CSS in the wild. " (quote from 197) maybe you can change this too generic name.

**Comment by ValentinTudorM** [comment]
Other technologies as Angular or React have better protection against "global variables"
https://angular.io/guide/component-styles
In Vaadin, if you do not have a such protection, then 
- for your css, you maybe write a good code
- for add-ons you have no protection if their are reusing one of your "names"
So, it is better to use less generic names.

In this case "hidden" is too generic (as was mentioned in issue 197), and our proposal is to change this name. If is not changed - we and other users will not have any other choice except removing   
toggle.setStyleName("hidden", column.isHidden());
line ... and maintain a custom code

**Comment by Legioth** [comment]
I don't think there's anything we can do about this on a generic level.
