### ISSUE TITLE
Grid - important - focus lost after cell editing - with proposed fix !

### ISSUE THREAD

**Issue by ValentinTudorM** [vaadin/framework#9832]
Vaadin Release 8.1.  

// when grid editor is closed with ESC, the focus is correctly set on grid (blue text)
// the same action must be done in all cases (when editor is closed from ENTER and from Cancel or Save buttons)
Important 
- Grid usability require a behavior that allow editing using only the keyboard (without requiring mouse to restore the lost focus). It is fundamental!
- the behavior must be consistent on all events: if you have solved for Esc case, you must solve also for the others   

---------------- code called on ESC:  it is working well; focus remain on grid
class DefaultEditorEventHandler {

    protected boolean handleCloseEvent(EditorDomEvent<T> event) {
        if (isCloseEvent(event)) {
            event.getEditor().cancel();
            FocusUtil.setFocus(event.getGrid(), true); // this is the focus restore that works
            return true;
        }
        return false;
    }

---------------- code called on ENTER:  focus it is lost
    protected boolean handleBufferedMoveEvent(EditorDomEvent<T> event) {

          ....

            // Save and close.
            event.getGrid().getEditor().save();
            FocusUtil.setFocus(event.getGrid(), true);  // MISSING  - keep focus on grid
            return true;
        }

        return false;
    }

---------------- code called on Save and Close buttons:
class Grid.Editor {

            saveButton.addClickHandler(new ClickHandler() {
                @Override
                public void onClick(ClickEvent event) {
                    save();
                    FocusUtil.setFocus(grid, true);   // MISSING  - keep focus on grid
                }
            });

            cancelButton.addClickHandler(new ClickHandler() {
                @Override
                public void onClick(ClickEvent event) {
                    cancel();
                    FocusUtil.setFocus(grid, true);   // MISSING  - keep focus on grid
                }
            });

You own us more bugs fixes (as for #9829) :)

Important - similar problem it is manifesting also for stand-alone controls (Date Picker, Combos etc). Focus it is lost after value selections and other events. Cannot edit only via keyboard - big problem in usability.

**Comment by tsuoanttila** [comment]
Thank you for pointing out this issue! Next time, please make a pull request while you're at it! We like receiving PRs from outside for simple issues, and will help you finish it up and get your contributions in the framework.
