### ISSUE TITLE
FileDropTarget Broken

### ISSUE THREAD

**Issue by ghost** [vaadin/framework#9846]
Vaadin 8.1.2

The `FileDropTarget` is not working at all in my environment. Tested with Firefox, Chrome and Edge.

```java
final Panel content = new Panel();
content.setSizeFull();
content.setContent(new Label("Drop Files Here!"));
new FileDropTarget<>(content, event -> {
	System.out.println("FileDropEvent detected!");
	event.getFiles().forEach(file -> System.out.println(file.getFileName()));
});
setContent(content);
```

When files are dropped, the browser attempts to open the file (i.e. redirects to `file://path/to/dropped/file`).

**Comment by bdunn44** [comment]
Any updates?

**Comment by hesara** [comment]
I'm not able to reproduce this with current master (which is quite close to 8.1.2) and the provided sample. Tested with Chrome 60 and Firefox 51, DefaultWidgetSet.

Is there anything in your environment that may affect this?

**Comment by nfekete** [comment]
I have the same problem. It doesn't work in Chrome 62.0.3202.94 (64-bit) and in Firefox 57.0 and 57.0.1 (64-bit). Interestingly, it works in Edge (41.16299.15.0) though. I just tried with the latest maven archetype from https://vaadin.com/framework/get-started#maven using version 8.1.7 and the above source code from @bdunn-dsc

**Comment by nfekete** [comment]
I found out the reason for the problem: the JS expression `("ontouchstart" in window)` returns `true` in both Chrome and Firefox (see tested versions above), so Vaadin considers them as touch enabled browsers. `DropTargetExtensionConnector` doesn't register a drop listener if the browser is a touch enabled browser **and** the `mobileHTML5DndEnabled` property of the UI is not explicitely set to true. The solution is to set it in the `UI.init()` method:
```java
@Override
protected void init(VaadinRequest request) {
    setMobileHtml5DndEnabled(true);
    ....
}
```

Current touch event support for the browsers look like this: https://caniuse.com/#search=touchstart
