### ISSUE TITLE
Grid with component column cause exception by sorting 

### ISSUE THREAD

**Issue by RomeoAT** [vaadin/framework#9853]
when i add component column in grid, and try to sort grid content by other column getting following exception: 
[com.vaadin.server.DefaultErrorHandler] (default task-62) : java.lang.IllegalArgumentException: Comparison method violates its general contract!
	
![exc](https://user-images.githubusercontent.com/31248848/29572618-23c9842a-875d-11e7-9aef-925ae1fcfa96.png)

**Comment by hesara** [comment]
I suspect this problem is specific to the comparators you are using, or somewhere else in your application. Do you try to sort on multiple columns at once?
Can you provide a simple program that allows us to reproduce the problem, and a description of the steps to take?

**Comment by RomeoAT** [comment]
@hesara thanks for ur answer. Exactly i've forget to implement the comparable interface. After extending the current used Component and implementing this with comparable interface. All thing work fine now.

**Comment by RomeoAT** [comment]
@hesara thanks for your answer. Exactly i've forget to implement the comparable Interface with the current used component class in Grid Component Column.

**Comment by hesara** [comment]
Closing this issue as not a framework issue.
Note also that if you don't want to make component columns sortable, you can also use Column.setSortable(false).
