### ISSUE TITLE
Vaadin 8: NativeSelect not allowing empty codes shows selection while empty

### ISSUE THREAD

**Issue by sergetania** [vaadin/framework#9854]
1. Create a NativeSelect field
2. Populate it with a list of items for the user to select from
3. Set it to not allow empty codes.
4. Set its value to empty
5. Observe that the combo will display the first item from the list (in Vaadin 7 it used to remain empty)
6. The value of the combo will be empty.... but the combo on the page WILL SHOW that the first item is selected!

Why does it show a selected item if its value remains empty? How is the user supposed to select the first item then? It should either show blank on the page like it did in Vaadin 7(compatibility is good!) or populate the combo value with the selected item.

To see the problem using the attached project, go to 
http://localhost:8080/v8-nativeselect/#!View
[v8-nativeselect.zip](https://github.com/vaadin/framework/files/1242992/v8-nativeselect.zip)

**Comment by mstahv** [comment]
You should call setValue(null), not setValue("") if you want to have it as undefined initially. Then it works as expected.
