### ISSUE TITLE
Upload throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/framework#9859]
This static method in FileUploadHandler will fail if it reads a zero-length line:

```java
private static String readLine(InputStream stream) throws IOException {
        ByteArrayOutputStream bout = new ByteArrayOutputStream();
        int readByte = stream.read();
        while (readByte != LF) {
            if (readByte == -1) {
                throw new IOException(
                        "The multipart stream ended unexpectedly");
            }
            bout.write(readByte);
            readByte = stream.read();
        }
        byte[] bytes = bout.toByteArray();
        return new String(bytes, 0, bytes.length - 1, UTF8);
    }
```

If bytes.length is 0 on the last line of code, it will throw an exception because it tries to read a range from 0 to -1.

Exception thrown:  
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
 at java.lang.String.checkBounds(Unknown Source)
 at java.lang.String.<init>(Unknown Source)
 at com.vaadin.server.communication.FileUploadHandler.readLine(FileUploadHandler.java:312)
 at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:364)
 at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:288)
 at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1464)
```

- Vaadin version: 8.1.2

**Comment by hesara** [comment]
Do you have a file to upload to reproduce this? Does this happen with empty files, or with files with empty lines, or only under some more complicated circumstances?

**Comment by hesara** [comment]
The line numbers in the stack trace seem to match the version of FileUploadHandler that was in 8.0 and perhaps up to 8.1.0.beta1, but not in 8.1.0.beta2 nor in the 8.1.2 version.

**Comment by hesara** [comment]
When do you see the issue? With an empty file? With a file that has an LF without a preceding CR? With consecutive LFs in the file? Some other case? Do you only see the issue in Liferay, or also in other environments? Which OS etc.?

**Comment by OlliTietavainenVaadin** [comment]
According to the report, the file in question was a randomly generated large file (multi-gigabyte) uploaded in a Liferay portlet. Original test data was created on Windows with `fsutil file createnew dummy 5368709120`. @elmot recreated a similar file as follows:
``` Tested by making a file (contents 012345678 with no linebreaks), and then type big.file.bin >>big.file.bin repeated many times.```
but obviously that file won't have any empty lines.

**Comment by hesara** [comment]
Files created with fsutil only contain the requested number of zero bytes AFAIK.
No problems found in a test on MacOS with a file of over 5GB consisting of zeroes nor one with the sequence "012345678" repeated 6e8 times (without line breaks). Using current master (relevant classes identical to 8.1.2), Jetty, Chrome.

It looks like this really is a Liferay specific issue, perhaps also Windows specific or browser dependent.

**Comment by hesara** [comment]
Tested on Liferay 7.0.10 GA1, MacOS, Chrome, Vaadin Framework 8.1.2 with the same files with numbers, no line breaks. Files of various sizes from 900B to 900MB caused no problems although for the largest files, processing (by Liferay?) took very long (minutes) after upload but before the application got the data.
The upload of a 5+GB file did not complete in a reasonable amount of time, probably due to limited memory allocated to the Liferay process. This seems to indicate that Liferay caches the data before passing it on to the application.

**Comment by hesara** [comment]
Also tested with a 180MB file with empty lines in the middle as well as random content binary files of 64MB and 512MB, Liferay 7 and Vaadin Framework 8.1.2 without being able to reproduce the issue.

**Comment by elmot** [comment]
Looks like the issue is fixed
