### ISSUE TITLE
Text-overflow ellipsis is not correctly rendered for TreeGrid

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9867]
- Vaadin version: 8.1.2, Chrome Version 60.0.3112.101

The hierarchy column does not correctly render the text-overflow ellipsis. The text ist still present and the dots remain on top of the text. You can see it in your own examples:
https://demo.vaadin.com/sampler/#ui/grids-and-trees/tree-grid/in-memory-hierarchical-data-provider

**Comment by gsonghet** [comment]
Vaadin 8.3.1, Chrome 64.0.3282.140
Bug ist still there...
