### ISSUE TITLE
DoubleClick doesn't work on hierarchy column in TreeGrid

### ISSUE THREAD

**Issue by sirbris** [vaadin/framework#9868]
In Vaadin 8.1.2 the ItemClickListener doesn't seem to work correctly on the hierarchy column... normal Click always works but DoubleClick just works on the other columns.

```
        treeGrid.addItemClickListener(inEvent -> {
            if (inEvent.getMouseEventDetails().isDoubleClick()) {
                System.out.println("DOUBLE CLICK");
            } else {
                System.out.println("CLICK");
            }
        });
```

**Comment by bjung82** [comment]
I can confirm this bug. But in our case the double click only works of the click is on another column than the hierarchy column AND if this column is a leaf in the tree.

**Comment by wbadam** [comment]
I can partly verify, double click is _not_ registered on a hierarchy column when the content is clicked and it _is_ registered when the click happens outside of the content.

`HierarchyRenderer` seems to swallow the double click event.

**Comment by bjung82** [comment]
:-)
