### ISSUE TITLE
Simplify setup for new open source devs for vaadin/framework

### ISSUE THREAD

**Issue by sknitelius** [vaadin/framework#9875]
The instructions currently state that you only have to run` mvn install` on framework.

However this fails due to an unresolvable dependency on vaadin-maven-plugin Version 8.1-SNAPSHOT.

Cloning vaadin-maven-plugin should do the trick, however its pom currently points at the latest version of vaadin-client. If I am not mistaken Maven 3 dropped support for LATEST, so that had to be corrected to 8.1-SNAPSHOT as well.

So I had to jump back to the framework project -> vaadin-client clean install-> jump to vaadin-maven-plugin clean install.

Now finally I can actually run clean install on vaadin/framework.

**Comment by hesara** [comment]
The top-level POM does define a pluginRepository vaadin-snapshots that does contain vaadin-maven-plugin 8.1-SNAPSHOT, so I wonder if some module does not inherit the root module and thus does not have it available.

Note also that the Maven plug-in only uses vaadin-client in its tests, so skipping tests or using any recent released version of vaadin-client in the tests should work.
