### ISSUE TITLE
compress vaadinBootstrap.js

### ISSUE THREAD

**Issue by tstsogoo** [vaadin/framework#9876]

**Comment by hesara** [comment]
The file vaadin-server*.jar already contains a pre-gzipped version of vaadinBootstrap.js. However, it seems that the version query parameter added for #4189 in https://github.com/vaadin/framework/commit/65904ffbdebc861a45c1b504d244d02a12f4561b makes VaadinServlet not serve the pre-compressed version, so it would only get served compressed if there is a compression filter active on the server.

As this used to work out of the box, considering this a regression and thus marking as a bug.

**Comment by hesara** [comment]
Actually, my test in the framework project gave incorrect results - the gzipped version is served automatically despite the URL parameters. Thus, marking this issue as invalid (already working).
