### ISSUE TITLE
Unable to deselect item in grid when it has been preselected

### ISSUE THREAD

**Issue by jalzola** [vaadin/framework#9882]
**Vaadin version 7.6.6**

**PROBLEM:**
Whenever an item is preselected in a grid, when I try to deselect it I am unable to do so. Also if I add a selection listener to the grid and try to deselect the preselected row no event is fired.

I only can deselect the preselected row it if I select another element in the table. 

**REPRODUCTIBLE EXAMPLE:**
This is the grid that I am using (I am preselecting the second row):

Grid grid = new Grid();
grid.setCaption("My Grid");
grid.addColumn("name", String.class);
grid.addColumn("born", Integer.class);
grid.addRow("Nicolaus Copernicus", 1);
grid.addRow("Galileo Galilei", 2);
grid.addRow("Johannes Kepler", 3);
grid.setHeightByRows(3);
grid.select(2);

**Comment by tsuoanttila** [comment]
Hi @jalzola,

Have you tried the most recent Vaadin 7 (currently 7.7.10) to see if this problems exists there as well? There has been fixes to the selection models of the Grid, which most likely relate to your problem here.

**Comment by jalzola** [comment]
@tsuoanttila sorry for the late response. I just tried it, using 7.7.3 and still the error ocurrs

**Comment by KatriHaapalinna** [comment]
Not reproducible in latest 7.7.x or 8.x release.
