### ISSUE TITLE
8.x: Typing a non-matching filter too fast makes ComboBox delete all items

### ISSUE THREAD

**Issue by zanonmark** [vaadin/framework#9915]
As reported on https://vaadin.com/forum#!/thread/16627944.

Quick-typing a non-matching filter in a ComboBox makes this widget delete all of its items.
I.e.: if the ComboBox contains "aaa", "bbb", "ccc" and one types "kkk" very fast (few tenths of a second), the ComboBox removes all items, even after clearing the filter.

To test, browse to [https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box](https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box), type "kkk" and see all of the items disappear.

Found on 8.1.2 and 8.1.3 and verified with Firefox and Chrome under Windows and Linux.
I can't tell about previous versions.

**Comment by tuscland** [comment]
We have the same issue with Vaadin 8.1.5. Our ComboBoxes use filtered DataProviders from lists or callbacks. 

When the bug is triggered, the list becomes empty and requests are no longer made to the backend, even if we modify the filter string.

We traced the problem back to the reset status of the DataCommunicator being true (waiting for a hard reset that never happens), thus preventing any filtered list update. 

However it seems this problem does not happen if we do not use a DataProvider and rather set the items directly using ComboBox.setItems(). This only works for short lists obviously.

**Comment by zanonmark** [comment]
I personally set the items with .setItems(LinkedList<T>). I still haven't checked with the latest versions anyway...

**Comment by vonloxley** [comment]
I’ve got the same problem using setItems(). However my List _is_ rather long.

**Comment by tsuoanttila** [comment]
Can you check if this still happens with the 8.1.6 release yesterday?

**Comment by vonloxley** [comment]
It still happens in the [Sampler](https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box) with FF 52.4.0.

**Comment by knoobie** [comment]
@vonloxley Sampler uses a 8.1-SNAPSHOT, so the fix isn't there.

**Comment by vonloxley** [comment]
The problem is still there with Vaadin 8.1.6 and Firefox 56.0 (64-Bit) as well as Google Chrome Version 62.0.3202.62 (Offizieller Build) (64-Bit). It can be reproduced by fast-typing and deleteng nonsense. 

Is there anything we can do to help?

**Comment by juhawilppu** [comment]
I also confirm that it's reproducing on Vaadin 8.1.6 with Chrome. It does not reproduce if you first click on the handle to show the list of answer options and then try searching by typing. It only reproduces if your first action is to search by typing.

**Comment by juhawilppu** [comment]
I would like to stress the fact that this not a meaningless bug. I have a long form where a required combobox is at the bottom. When this bug happens, the user is not able to save the form at all and will need to scrap all the inputted form data.

I guess I'll need to remove the required validation from this field for now.

**Comment by juhawilppu** [comment]
I figured out a workaround. The dropdown selection will still show an empty list on the first click but it will show the options on the second click.

```
comboBox.addBlurListener(new BlurListener() {
    @Override
    public void blur(BlurEvent event) {
        Optional<MsOption> value = comboBox.getOptionalValue();
        if (!value.isPresent()) {
            comboBox.setItems(options);
        }
    }
});
```

**Comment by phillipjohnson** [comment]
I am not quite sure if this is the same bug, but it seems related. In this case all the items get removed when the user's provided option doesn't match anything in the list.

![q3jlsk0iqp](https://user-images.githubusercontent.com/1959996/33908002-02469d42-df55-11e7-9631-9e39937531f1.gif)

I ended up disallowing text input since it wasn't needed here.

Vaadin 8.1.2 on Chrome 62.

**Comment by zanonmark** [comment]
The bug is still present on 8.2.1.

**Comment by tomekkup** [comment]
reproducible in 8.3.0 ! please fix  :( :(

**Comment by fabioebner** [comment]
Any news?

**Comment by TatuLund** [comment]
Have you checked if this issue still persists in 8.3.2.  It may be related to recently fixed issue: https://github.com/vaadin/framework/issues/10624

**Comment by fabioebner** [comment]
The bug is still present on 8.3.2

**Comment by zanonmark** [comment]
The bug is still present on 8.3.3.
Anything we can do to help to track it?

Thanks,
MZ

**Comment by fabioebner** [comment]
As such a basic crowd does not have the proper attention of the developers, I wonder if the vaadin is so used when it is said by themselves. I know that the attention with the clients is terrible.

**Comment by tsuoanttila** [comment]
I am having problems reproducing this issue on both 8.3.3 and 8.4.0. Can someone provide me with the minimal reproducible code and how to make it happen? 

I tested with Chrome 66 on Mac using the following code:
```
ComboBox<String> combobox = new ComboBox<>();
		combobox.setItems("aaa", "bbb", "ccc");
```

I typed in as fast as my keyboards allows `ddd`. I tried using doing it as the first action. Follow up actions I tried were immediately deleting the text, clicking outside of the combobox, pressing escape or enter. Every time when I opened the drop down box by either typing something that exists, pressing down or clicking the dropdown button the list contains items I've set.

If you have a 100% accurate way to reproduce this, please share it.

**Comment by juhawilppu** [comment]
Easiest way to reproduce it is to use keyboard only: Navigate the UI components using the Tab-key and when the ComboBox gets focused, you can wait multiple seconds and then write "ddd". It should show blank and clearing the textfield should still not show any options.

If it still doesn't reproduce, I can make you a minimal code example. (I have not tested with 8.3 or 8.4 myself.)

**Comment by fabioebner** [comment]
Anyone test in 8.4.0?

**Comment by tsuoanttila** [comment]
Still happens with 8.4.0, found a way to test this, working on a fix.

**Comment by fabioebner** [comment]
I tried to make a lazy loading and don't works too :(

**Comment by tsuoanttila** [comment]
Ok, after getting back to the ticket this morning I'm having again hard time to get this to replicate to actually work on a fix. 

One thing that came to mind that might be causing some issue in here.. Are you using `NewItemHandler` in you combobox? If yes, please switch to the use of `ComboBox::setNewItemProvider`.

There's at least an issue with the older, now deprecated, `NewItemHandler` that not adding the new entry for the given text requires some API calls from the developer to make sure Combobox is aware that new item was not added. The new API returns an `Optional` and combobox will automatically fix its state accordingly.

Symptoms of this issue mentioned above is the ComboBox popup not opening properly but just flashes on the screen.

**Comment by zanonmark** [comment]
Hi, and thanks for taking care of the issue.

As far as my code is concerned, it looks like:
```
        this.provinceIdWidget = new ComboBox<AProvinceRecord>(t("Province"));
        this.provinceIdWidget.setItemCaptionGenerator(AProvinceRecord::getProvince);
        this.provinceIdWidget.setWidth("100%");
        this.provinceIdWidget.addBlurListener(this);
        this.contentWidget.addComponent(this.provinceIdWidget);
```

Thanks,
MZ

**Comment by juhawilppu** [comment]
I tried to make a small code example that reproduces the bug but now I couldn't reproduce it either!

The code is very similar to what I have in my real application. My real app is bigger (and slower), though, but it's quite fast nevertheless. I also tried adding hundreds of textfields with a for-loop, but it didn't make a difference.

If anyone wants to take a look at the code and continue from here:
https://github.com/juhawilppu/vaadin-combobox-mwe

**Comment by tuscland** [comment]
The issue is easier to reproduce when you use a callback based DataProvider and slow down internet on your browser.

**Comment by fabioebner** [comment]
For me only use .setItems will reproduce the error :D

**Comment by tsuoanttila** [comment]
@fabioebner Can you make a whole new test project from single module archetype with 8.4.0 and get it to reproduce there? Once you see it happen, push that project to github and link the URL here. I'm still having real problems reproducing it and getting access to a project where someone else can confirm the issue happens might help me find out the root cause of all of this. I went through the RPC calls with `setItems` and `CallbackDataProvider` with network throttling, slowdown in the backend requests as well as read through the code related to this issues.. I'm starting to run out of ways to figure this one out.

**Comment by m-bermel** [comment]
@tsuoanttila 
Seems to be still existing in 8.4.4. Only way I could reproduce this was by using the CPU slowdown in Chrome and kinda hammering the keys. Maybe depends on the number of layouts/elements used on the page and client/browser performance.

See a short screen grab here: 
![localhost_8080](https://user-images.githubusercontent.com/11294127/42100238-f24620e0-7bbf-11e8-9950-17af60a96e19.gif)
![image](https://user-images.githubusercontent.com/11294127/42100264-097064e2-7bc0-11e8-9c7e-9d875012490f.png)

Used minimal working example https://github.com/m-bermel/vaadin-cb

If you want I can try to create a larger example with more layouts and elements.

**Comment by simpletasks** [comment]
I tried @m-bermel sample project with no issue. No miss behave. Also tried demo on https://demo.vaadin.com/sampler/#ui/data-input/multiple-value/combo-box and this reproduce issue. I do not see complete project source code to test it locally. Difference is that vaadin demo is remote to me and @m-bermel example is on localhost! But my link is up100M/down100 so I do not think that link speed is issue.
I would like to grab source of vaadin demo for combo box to test it.

**Comment by focbenz** [comment]
Hopefully this also fixes the reported problem referenced here:
https://github.com/vaadin/framework/issues/10549#issuecomment-406354549

**Comment by zanonmark** [comment]
I would like to thank all of you who spent their time in fixing this annoying bug.
It seems to work properly now.

Thanks,
MZ
