### ISSUE TITLE
BeanValidationBinder doesn't work when binding field with getter/setters

### ISSUE THREAD

**Issue by haiwan** [vaadin/framework#9918]
if I create a BeanValidationBinder like this
`BeanValidationBinder<FormValue> binder = new BeanValidationBinder<>(FormValue.class);`
If I bind field with property name, then validation works
`binder.forField(emailBoundWithPropertyName).bind("emailBoundWithPropertyName");`
But if I bind the field with getter/setters, then it doesn't work
```
binder.forField(emailBoundWithGetterSetter).bind(FormValue::getEmailBoundWithGetterSetter,
				FormValue::setEmailBoundWithGetterSetter);
```

Tested Vaadin version: 8.1.3

Attached you can find a small demo application.

[vaadin-app.zip](https://github.com/vaadin/framework/files/1269454/vaadin-app.zip)

**Comment by Artur-** [comment]
The reason is that `FormValue::getEmailBoundWithGetterSetter` in Java only provides `Binder` with a way to call the getter. It does not provide a method reference to the getter, or even info about the name of the getter

**Comment by haiwan** [comment]
Thank you for your quick reply, I don't think I fully understand what you mean. If I want to use this API for binding, how should I do it?
`public Binding<BEAN, TARGET> bind(ValueProvider<BEAN, TARGET> getter,
                Setter<BEAN, TARGET> setter);`

**Comment by Artur-** [comment]
As far as I know, you have to add the validator manually if you use that method

**Comment by haiwan** [comment]
Ok, I think finally I understand. I will close this issue.
