### ISSUE TITLE
OOM issue in Application

### ISSUE THREAD

**Issue by CMQuintiles** [vaadin/framework#9919]
Hi Team,
    We are facing out of memory issue in our application. Please find below details- 
    Vaadin version: 7.7.7
    Description of the bug: 
	1. When user opens the application in multiple browser tabs or windows, an UI instance   is created 
             in the memory per tab/window all bound to the same HTTP Session.
	2. On session timeout, these UI instance which are no longer accessible still stays in the memory 
            and not getting garbage collected. 
	3. As a result, there is an upward trend in the memory consumption as and when the number of 
            users increase but doesn’t go down when users count decreases.
         4. That cause OOM issue in our application. 
This require urgent attention .

**Comment by Artur-** [comment]
Hi,

you should check with a profiler if you keep a reference to the UI instance, which causes it to remain in memory (e.g. a static variable referring to the UI). Vaadin does not retain any references to the UI instances except inside the HTTP session, and these references are removed when the HTTP session is invalidated by the server.

If you think it's a Vaadin problem and not a problem in your application, please provide an example application where the problem can be seen.
