### ISSUE TITLE
Datefield: Resizing window or scrolling with mouse wheel separates calender popup-window from entryfield

### ISSUE THREAD

**Issue by bjung82** [vaadin/framework#9926]
Hi,

This issue can always be reproduced in the vaadin sampler application:
https://demo.vaadin.com/sampler/#ui/data-input/dates/popup-date-field

Regards
Benjamin

**Comment by hesara** [comment]
Perhaps something like the solution for #9869 could also be applied to VAbstractPopupCalendar, though it looks somewhat non-trivial (might need custom subclass of VOverlay; interaction with PopupPositionCallback; potential for race conditions).
