### ISSUE TITLE
Fix to #9427 violates builder contract

### ISSUE THREAD

**Issue by pwilkin** [vaadin/framework#9927]
The fix to #9427 is terribly counterintuitive. I had to actually read the original issue to understand why my code wasn't working. The reason is that this design violates the general builder pattern contract, which is that chained method calls should work the same as consecutive method calls on the builder. There should be no reason why a builder returns a new instance of a builder class instead of just modifying its own state.

**Comment by tsuoanttila** [comment]
Hi @pwilkin and thank you for bringing this to our attention. The reason it's currently implemented that way is to maintain the type safety when doing conversion from one type to the other. What is your expectation of how the code using the BindingBuilder would look like?

I tried to quickly make the change so you could use the existing binder with consecutive method calls, and the end result was quite ugly:
```
BindingBuilder<Person, ?> ageBinding = binder.forField(ageField);
((BindingBuilder<Person, String>) ageBinding)
    .withConverter(new StringToIntegerConverter("foo"));
((BindingBuilder<Person, Integer>) ageBinding).bind(Person::getAge, Person::setAge);
```

If the type is omitted from the BindingBuilder, then there's no longer any way to provide compilation time errors from misconfigured Bindings, which is one of the biggest benefits of the new Binder over the old FieldGroup.

As of right now, all other methods than `builder.withConverter` and `builder.withNullRepresentation` return the exact same instance and can be used as a builder. Only when applying a conversion of some kind the builder is a new instance.

**Comment by pwilkin** [comment]
Your rationale with type safety is valid, so maybe some sort of different naming convention? Generally "with*" is expected to meet the builder contract, maybe something like `builderForConverter`?

My case is such that I'm making a dynamically typed field where the target class is determined at runtime from some metadata object, so I'm casting to BindingBuilder<Object, Object> anyway. That's why I never saw it coming.

**Comment by tsuoanttila** [comment]
This is btw quite related to #9619 , I'd almost call it a duplicate.

**Comment by pwilkin** [comment]
It is :> which reinforces my point that it's counterintuitive, esp. when other "with*" methods don't return a new object. I'd propose the following: 

* change the method name to something like `builderForConverter`, `convert` or 'transformWithConverter'
* add a visible documentation warning that the method changes the returned builder
