### ISSUE TITLE
TreeGrid Filter only compares root elements

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9933]
Vaadin version: 8.1.3

In the moment if you add a filter with `public default <V> void addFilter(ValueProvider<T, V> valueProvider,
            SerializablePredicate<V> valueFilter)` the values only for the root elements getting compared. The child elements are not getting compared. so they always gets filtered.

``
treeGrid.addFilter(column.getValueProvider(), value -> {
					return String.valueOf(value).toLowerCase().contains(textField.getValue().toLowerCase()) || value == null || String.valueOf(value).isEmpty();
				});
``

**Comment by tepi** [comment]
I think I am experiencing the same or similar issue. In short, if I use a filter on a TreeGrid, the filtering logic seems to immediately filter out a parent node that does not pass the filter without even checking the child nodes. This is different from how the TreeTable works and it also makes impossible to filter any non-trivial hierarchical data. Below is a simple application demonstrating this.

`package org.test;

import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.data.TreeData;
import com.vaadin.data.provider.TreeDataProvider;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Button;
import com.vaadin.ui.TreeGrid;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import javax.servlet.annotation.WebServlet;

public class TreeGridFilteringUI extends UI {

  @Override
  protected void init(VaadinRequest vaadinRequest) {
    final VerticalLayout layout = new VerticalLayout();

    TreeData<String> treeData = new TreeData<>();
    treeData.addRootItems("1", "2", "3");
    treeData.addItems("1", "1_1", "1_2", "1_3");
    treeData.addItems("2", "2_1", "2_2", "2_3");
    treeData.addItems("3", "3_1", "3_2", "3_3");

    TreeDataProvider<String> treeDataProvider = new TreeDataProvider<>(treeData);

    TreeGrid<String> treeGrid = new TreeGrid<>();
    treeGrid.addColumn((item) -> item);
    treeGrid.setDataProvider(treeDataProvider);

    layout.addComponents(treeGrid,
        new Button("Filter with 1", e -> treeDataProvider.setFilter(row -> row.contains("1"))));
    setContent(layout);
  }

  @WebServlet(urlPatterns = "/*", name = "TreeGridFilteringUIServlet", asyncSupported = true)
  @VaadinServletConfiguration(ui = TreeGridFilteringUI.class, productionMode = false)
  public static class TreeGridFilteringUIServlet extends VaadinServlet {
  }
}
`

When you click the button, a filter is added to the data provider. The filter simply checks if the row (which is a string) contains "1". The expected result is that the children "2_1" and "3_1" would be visible after filtering (along with their parent nodes which do not pass the filter). Instead, root nodes "2" and "3" are filtered out completely.

**Comment by mahdiafactory** [comment]
You can expand your filtering logic in a way that a node isn't filtered out if one of its children matches the filter. 

```
// filter by name
TextField nameField = new TextField();
nameField.addValueChangeListener(event -> {
    if (nameField.getValue().isEmpty()) {
        //clear and expand all items
	dataProvider.clearFilters();
	expandAll();
    } else {
        //set hierarchical filter
	dataProvider.setFilter(detail -> matchesFilter(detail, nameField.getValue()));
    }
});
...
private boolean matchesFilter(LoadingViewDetail detail, String filter) {
		if (StringUtils.containsIgnoreCase(detail.getName(), filter)) {
			return true;
		}
		return detail.getChildren().stream().filter(child -> matchesFilter(child, filter)).findFirst()
						.orElse(null) != null;
	}
```

**Comment by enver-haase** [comment]
I'd like to add: Vaadin version 14.2

Client-Side Filtering is needed for that Vaadin version.
What is needed for the use case we have: the complete sub-tree shall be displayed if one node fulfils the filtering criteria.

**Comment by enver-haase** [comment]
See https://github.com/vaadin/vaadin-grid-flow/issues/819 for the Vaadin Flow version.
