### ISSUE TITLE
Modality curtain doesn't block NativeSelects in IE6

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#996]
**Originally by @ripla**

___
To test:

```
        NativeSelect ns = new NativeSelect();

        Window modalWindow = new Window();
        modalWindow.setModal(true);
        modalWindow.center();

        mainLayout.addComponent(ns);
        mainLayout.getWindow().addWindow(modalWindow);
```

___
 Imported from https://dev.vaadin.com/ issue #4261

**Comment by anasmi** [comment]
Hi,

I will close this issue, as currently developed and maintained versions of the framework, don't work with IE6.
If issue is still important to you or could be reproduced in another browsers, please, create a new ticket to us providing relevant info.
Thank you for your interest and contribution! : )
