### ISSUE TITLE
Heatmap (xAxis title not showing)

### ISSUE THREAD

**Issue by SaraLouage** [vaadin/framework#9961]
- Vaadin version
8.0 - 8.1.3
- Description of the bug
Heatmap xAxis title is showing halfly (text is cut off horizontally). Also in export svg.
- If possible, minimal reproducible example

**Comment by SaraLouage** [comment]
![capture](https://user-images.githubusercontent.com/11866480/30279911-c245bb08-970e-11e7-9221-0d3f17d2f2b7.PNG)

**Comment by johannesh2** [comment]
I think this is a Vaadin Charts issue. I copied your report here: https://github.com/vaadin/charts/issues/450
Could you please comment which version of Charts you are using.
