### ISSUE TITLE
Vaadin polling on Beanstalk amazon

### ISSUE THREAD

**Issue by SaraLouage** [vaadin/framework#9963]
For bugs, please provide at minimum the following information:
- Vaadin version
8.0-8.1.3
- Description of the bug
We deployed a vaadin 8 web app on amazon Beanstalk with tomcat 8. In the vaadin app we have enabled pooling via setPollInterval(X) and the logic for updating the GUI with a simple new Label. This works perfectly locally on our Tomcat but when we deploy it on AWS Beanstalk this doesn't work. 

After researching online we discovered that on AWS Beanstalk they use an Apache HTTP reverse proxy sever before the Tomcat container which runs our vaadin app. Can this Apache server cause this problem? 
- If possible, minimal reproducible example

**Comment by Artur-** [comment]
Polling uses the exact same mechansim as all other UI events so if you can click a button or enter a text in a TextField, then polling should also work (@Push is a different case though)

**Comment by SaraLouage** [comment]
Hi Artur,

Thanks for responding. We understand how polling and push works as everything works locally on our side. Our problem is that when we deploy a simple application which has polling enabled (polling interval set to 1 second) on aws beanstalk this doesn't work. We think that maybe the reverse proxy server before the Tomcat on aws might cause this issue. Do you have any suggestions or some work around for this?

**Comment by thomaszbz** [comment]
Using spring boot 1.5.9 and vaadin 8.3.0, I'm experiencing the same Problem as @SaraLouage .

When I run the application in local dev environment, a progressbar refreshes as soon as I have set the polling interval to e.g. 1s. This holds true for both: polling as well as pushing (with `LONG_POLLING` transport).

When deploying the application to Elastic Beanstalk (Tomcat is behind nginx) then the progressbar is not updated any more and I also can't change visibility during e.g. a file upload (which also works locally). This also holds true for pull and push method.

I'd also be interested in a way to work around this EB/nginx problem.

**Comment by TatuLund** [comment]
Are you able to modify proxy settings?

See 
https://vaadin.com/docs/v8/framework/articles/ConfiguringPushForYourEnvironment.html

"If you are in control of the proxy, configure it not to timeout/kill push connections (connections to the /PUSH url)"

Here are some examples: https://vaadin.com/forum/#!/thread/11538752/11542480
