### ISSUE TITLE
grid nested layouts

### ISSUE THREAD

**Issue by SaraLouage** [vaadin/framework#9964]
- Vaadin version
8.0 - 8.1.3
- Description of the bug
Grid does not have the possibility to add nested layouts. The table did have this option. 
- If possible, minimal reproducible example

**Comment by TatuLund** [comment]
Grid has concept of ComponentRenderer which allows to add content to cells based on component, including layout components. See more https://vaadin.com/docs/v8/framework/components/components-grid.html section Component Renderer.
