### ISSUE TITLE
Add method expandAll/collapseAll for Tree and TreeGrid

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9969]
- Vaadin version 8.1.3

In the moment there is only a function to expand a specific item or a list of items. But for the list the items are only expanded for the root elements. So either expand should scan the childs (via childItemProvider?) in the list and expand them or make a method without parameter for expanding and collapsing all items.

**Comment by hesara** [comment]
If implemented in the framework, this should not be done simply by iterating over all nodes and calling expand() as it fires an event after every expansion, but in a more efficient way.
An application that knows there are only a small number of expandable nodes can also use simple iteration.
