### ISSUE TITLE
Grid.setRowHeight should also set line-height to avoid uglyness

### ISSUE THREAD

**Issue by waschmittel** [vaadin/framework#9991]
I use

> myGrid.getColumn("foo").setStyleGenerator(item -> "v-align-middle");

to middle-align my Grid contents after setting row height with:

>myGrid..setRowHeight(42);

However, when focussing a cell, the focused cell it top-aligned and looks like this:
![image](https://user-images.githubusercontent.com/4701616/30397850-7a1f6e20-98ce-11e7-85b9-a3982a3c89a0.png)

The issue seems to be that `height: 42px;` is set, but `line-height` is not.
If I set`line-height: 42px;` it revolves the issue.

This seems to be a sensible default to me anyway, since it prevents text from sticking to the top of the row in any case.

**Comment by waschmittel** [comment]
Just learned at the Dev Day that I can set $v-grid-row-height in the theme as a workaround. Thanks!
I am happy now :-) , but still consider this a layout bug.

**Comment by mvysny** [comment]
I believe this is definitely a bug in Vaadin since the API for setting row height (`Grid.setRowHeight()`) is in Java, but the Grid looks ugly unless the CSS `line-height` is changed as well, but that's not possible to do from Java. Still present in Vaadin 8.7.0.

**Comment by TatuLund** [comment]
I applied the change to the framework to see if it brakes regression tests and also tested locally. Setting the line height is not a generally usable default in Grid. For example wrapping long texts in cells wont work nicely. I would say based on my testing, that current behavior is a good default and if you need something else, then the right approach is to solve it with application specific theming.
