### ISSUE TITLE
Grid recalculateColumnWidths doesn't work when using the Grid with a dataProvider

### ISSUE THREAD

**Issue by tistvan** [vaadin/framework#9996]
Hello,

Vaadin version: 8.1.4
Description of the bug:
When using Grid with DataProvider recalculateColumnWidths doesn't work for the newly added items.

Minimal reproducible example:
```java
List<TestItem> testItems = Lists.newArrayList(new TestItem("short1"), new TestItem("short2"));

Grid<TestItem> grid = new Grid<>();
grid.addColumn(TestItem::getName).setCaption("Name");
grid.addColumn( testItem -> "col2").setCaption("Col 2");
grid.addColumn( testItem -> "col3").setCaption("Col 3");
grid.setDataProvider(new ListDataProvider<>(testItems));


Button button = new Button("add row", e -> {
    testItems.add(new TestItem("Wiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiide"));
    grid.getDataProvider().refreshAll();
    grid.recalculateColumnWidths();
});
```

The columns are initially 33% wide. When I click to the add row button first time the column widths remain the same. When I click to the button second time the column widths recalculated normally.

The workaround is changing the grid.getDataProvider().refreshAll()  line to grid.setDataProvider(grid.getDataProvider()).

Thanks

**Comment by tistvan** [comment]
I reproduced the bug in VaadinFiddle: 
 https://vaadinfiddle.com/editor/preview/920f7be721a001cc69fd9586de889f2325ec3a0bbef11a868fc76dde161ffb51/src/main/java/org/vaadin/vaadinfiddle/MyUI.java
In this example the grid should recalculate the column widths when I add new items to it with the add row button. But the width isn't recalculated properly when you add the first item. For the second item it works.

**Comment by TatuLund** [comment]
This could be fixed by https://github.com/vaadin/framework/pull/10579

**Comment by Saxintosh** [comment]
The bug still exists in Vaadin 8.8.1
The workaround works...
