### ISSUE TITLE
TreeGrid client side IndexOutOfBoundsException after expanding new node

### ISSUE THREAD

**Issue by Hedath** [vaadin/framework#9997]
After adding a new root and child node to the tree, and expanding the new root node, a client side exception is thrown.
For example, when adding the items to an empty tree, this exception is thrown:
```
SEVERE: Error performing server to client RPC calls
java.lang.IndexOutOfBoundsException: The given index (1) was outside of the current number of rows (0..0)
```

After this exception, the grid refreshes its entire content (dropRows, and requestRows RPC calls), and recovers (so the exception is not visible on the UI, only in console).

Vaadin version:
8.1.4

Code sample to reproduce:
```
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        TreeGrid<Item> tree = new TreeGrid<>(Item.class);
        Button button = new Button("Add new item", e -> addItem(tree));

        setContent(new VerticalLayout(tree, button));
    }

    private void addItem(TreeGrid<Item> tree) {
        Item parent = new Item("Parent");
        Item child = new Item("Child");

        TreeData<Item> treeData = tree.getTreeData();
        treeData.addItem(null, parent);
        treeData.addItem(parent, child);

        tree.getDataProvider().refreshAll();

        tree.expand(parent);
    }

    public static class Item {
        private String name;

        public Item(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
```

**Comment by Hedath** [comment]
I can still reproduce it with vaadin version 8.3.2.

**Comment by robsilvia** [comment]
A work around is to do the following:

Instead of using tree.expand(parent), use tree.getDataCommunicator().expand(menuItem, false);

tree.expand calls tree.getDataCommunicator().expand(menuItem, true), which is telling Vaadin to refresh an existing item. tree.getDataCommunicator().expand(menuItem, false) just marks the item as expanded, which is fine as the item is new and gets communicated as expanded.

**Comment by elmot** [comment]
First of all, please provide `hashcode`/`equals` for your `Item` and check if it works or not

**Comment by robsilvia** [comment]
I can confirm this occurs with an equals and hashCode defined.



    public static class Item {
        private final String name;

        public Item(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj == this) return true;

            if (obj instanceof Item) {
                Item otherItem = (Item) obj;
                return Objects.equals(this.name, otherItem.name);
            }

            return false;
        }

        @Override
        public int hashCode() {
            return Objects.hash("item", name);
        }
    }

This problem only arises when adding and expanding items to a tree already resident on the client side.

If you look at TreeGrid.expand(Collection):

    public void expand(Collection<T> items) {
        HierarchicalDataCommunicator<T> communicator = getDataCommunicator();
        items.forEach(item -> {
            if (!communicator.isExpanded(item)
                    && communicator.hasChildren(item)) {
                communicator.expand(item); // includes client side sync
                fireExpandEvent(item, false);
            }
        });
    }

I'm pretty sure this should be:

    public void expand(Collection<T> items) {
        HierarchicalDataCommunicator<T> communicator = getDataCommunicator();
        items.forEach(item -> {
            if (!communicator.isExpanded(item)
                    && communicator.hasChildren(item)) {
                communicator.expand(item, false); // does not include client side sync
                fireExpandEvent(item, false);
            }
        });
    }
